- Gemfile
- Gemfile.lock
Sentry alerts
`SENTRY_DSN ` has been added as a Github Secret
- Add sentry gem
🚢
> [0017] Add Sentry gem

- .github/workflows/build.yml
- docker-compose.yml
- wait-for-command.sh
added docker-compose as env vaiable
Added docker-compose as env vaiable so that docker compose can run and referrence docker compose yml file.
> [44] added docker-compose as env variable

- app.json
> Refactor heroku app.json

- .github/workflows/build.yml
Push Docker Images to DockerHub
Push Docker Images to DockerHub
> Push docker image to DockerHub

- .gitignore
- terraform/modules/paas/data.tf
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace-variables/qa.tfvars
- terraform/workspace-variables/qa_backend.tfvars
`terraform` files for creating service in Gov UK PaaS
```bash
cd terraform
terraform init -backend-config=workspace-variables/qa_backend.tfvars
terraform plan -var-file=workspace-variables/qa.tfvars -out qa.tfplan
terraform apply "qa.tfplan"
```
> initial terraform files for creating PaaS services

- app/controllers/trainees/contact_details_controller.rb
- app/controllers/trainees_controller.rb
- app/views/layouts/application.html.erb
- app/views/trainees/contact_details/index.html.erb
- app/views/trainees/new.html.erb
- app/views/trainees/personal_details/index.html.erb
- app/views/trainees/previous_education/index.html.erb
- app/webpacker/packs/application.js
- config/routes.rb
- db/migrate/20200902142317_add_contact_details_to_trainees.rb
- db/schema.rb
- spec/controllers/trainees/contact_details_controller_spec.rb
- spec/factories/trainees.rb
- spec/rails_helper.rb
- https://trello.com/c/M7Jhkztn/23-m-add-contact-details-form
- Add contact details form so data can be added to trainee
- Create or find a trainee
- Add their contact details
- Should see data inside database
- Or reload the page after saving and info should be displayed on the form
> [23] Add contact details form

- .github/workflows/build.yml
- .gitignore
- terraform/modules/paas/main.tf
- terraform/terraform.tf
- terraform/workspace-variables/qa.tfvars
configure github action to use terraform and deploy to pass
> [12] Deploy to Paas via terraform

- app/controllers/trainees/training_details_controller.rb
- app/controllers/trainees_controller.rb
- app/views/trainees/training_details/edit.html.erb
- config/routes.rb
- db/migrate/20200903085102_add_training_details_to_trainees.rb
- db/schema.rb
- spec/features/edit_training_details_spec.rb
- spec/features/trainees/edit_training_details_spec.rb
- spec/support/page_objects/trainees/training_details.rb
Training details page for the first iteration of register.
- Added `/trainees/<id>/training-details`
- Added feature spec
> 27 created training details form

- app/presenters/trainee_training_details.rb
- app/views/trainees/show.html.erb
- spec/controllers/trainees_controller_spec.rb
- spec/factories/trainees.rb
- spec/features/trainees/trainee_summary_spec.rb
- spec/support/page_objects/sections/training_details.rb
- spec/support/page_objects/trainees/summary_page.rb
Update to the summary page.
-  Added the training details section to the summary page
-  Added specs
> 28 add training details summary

- .github/workflows/build.yml
- docker-compose.yml
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace-variables/qa.tfvars
creating single image to run multiple background job
> 39 deploy one bakcground jobs container

- .github/workflows/build.yml
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace-variables/qa.tfvars
Pass variable between build steps
Set the status of application deployed to Paas to "Started". This was previously set to false.
> 39 fix terraform deployment

- .github/workflows/build.yml
- config/initializers/semantic_logger.rb
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace-variables/qa.tfvars
Add logging capabilities using Logit
The proposal is not to change anything; but to add new functionality and capabilities
> Add logit to Register web_App

- README.md
- app/services/feature_service.rb
- app/views/pages/home.html.erb
- config/settings.yml
- spec/features/view_pages_spec.rb
- spec/services/feature_service.rb
- spec/services/feature_service_spec.rb
- spec/support/features.rb
- https://trello.com/c/E47aN3UJ/121-implement-features-service
- Implement a service module to handle feature flag checking
- Add basic feature flag smoke test
- Toggle the sample feature flag on/off locally and assert the text in the home page shows/hides
> [121] Implement features service

- .github/workflows/build.yml
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
Add new DDTP environment variables through terraform
> [115] Add DDTP environment variables to terraform

- .github/workflows/build.yml
> update TF_VAR secrets spelling error

- Gemfile.lock
- app/views/trainees/contact_details/edit.html.erb
- app/views/trainees/course_details/edit.html.erb
- app/views/trainees/new.html.erb
- app/views/trainees/personal_details/edit.html.erb
- app/views/trainees/previous_education/edit.html.erb
Update the form builder to latest v2.
> Bump govuk_design_system_formbuilder to v2

- app/components/summary_card/view.html.erb
- spec/components/summary_card/view_preview.rb
- spec/components/summary_card/view_spec.rb
View https://dfe-twd-rttd-pr-75.herokuapp.com/view_components/summary_card/view
> [248] Add actions to summary card component

- .tool-versions
- Dockerfile
- Gemfile
- Gemfile.lock
We're on 2.7.1
Upgrade to 2.7.2
> [236] Upgrade Ruby to 2.7.2

- app/components/trainees/confirmation/contact_details/view.html.erb
- app/components/trainees/confirmation/contact_details/view.rb
- config/locales/en.yml
- spec/components/trainees/confirmation/contact_details/view_preview.rb
- spec/components/trainees/confirmation/contact_details/view_spec.rb
> 244 m confirm page al

- app/components/trainees/confirmation/personal_details/view.rb
- spec/components/trainees/confirmation/personal_details/view_preview.rb
- spec/components/trainees/confirmation/personal_details/view_spec.rb
> [244] Add preview and spec file for personal details confirm component

- app/components/trainees/confirmation/degrees/view.html.erb
- app/components/trainees/confirmation/degrees/view.rb
- spec/components/trainees/confirmation/degrees/view_preview.rb
- spec/components/trainees/confirmation/degrees/view_spec.rb
- Needed to pull in some work from ticket 224, please ignore first commit
- Adds new degrees confirmation component.
- we still need to add proper paths to the actions but that will be added in another PR once we have created those pages
- Visit https://dfe-twd-rttd-pr-100.herokuapp.com/view_components/trainees/confirmation/degrees/view
- Try out each example https://dfe-twd-rttd-pr-100.herokuapp.com/view_components/trainees/confirmation/degrees/view
> [223] Add Degree confirmation component

- app/components/trainees/confirmation/degrees/view.html.erb
- app/components/trainees/confirmation/degrees/view.rb
- app/controllers/trainees/confirm_details_controller.rb
- app/controllers/trainees/degrees_controller.rb
- app/views/trainees/show.html.erb
- config/routes.rb
- spec/components/trainees/confirmation/degrees/view_preview.rb
- spec/components/trainees/confirmation/degrees/view_spec.rb
- spec/features/trainees/degrees/editing_degree_spec.rb
- spec/support/page_objects/trainees/degrees_confirm.rb
Confirmation page to degree user journey
Add confirmation page to degree user journey
Visit https://dfe-twd-rttd-pr-101.herokuapp.com/
- Create a new trainee 
- Add a few degrees for the new trainee
- View an existing Trainee (eg. https://dfe-twd-rttd-pr-101.herokuapp.com/trainees/2) 
- Try to view the degree for the trainee and edit an existing degree
> [223] Add confirmation page to degree user journey

- app/components/start_page_banner/view.html.erb
- app/views/pages/start.html.erb
https://trello.com/c/mzNxn9LI/366-update-start-page-production-with-new-content-prototype
Change start page to reflect prototype start page! 
Prototype start page - https://register-prototype.herokuapp.com/start-page
Modified start page -
> 366 Change content for start page

- .github/workflows/build.yml
Latest version has fixes for few issues we have been seeing in the pipeline.
Use latest version of terraform cloudfoundry provider.
> [449]use cf provider 0.12.6

- .github/workflows/build.yml
- terraform/modules/paas/main.tf
- terraform/terraform.tf
upgrade terraform to ver 0.13 in order to leverage new features
upgrade terraform to ver 0.13
> [450] upgrade terraform to ver 0.13

- .github/workflows/build.yml
Pin terraform to 0.13.5
Pin terraform to 0.13.5
> Pin terraform to 0.13.5

- app/views/trainees/show.html.erb
Updated the overview page so that it is in line with the prototype
Updated content and structure of the page.
The changes proposed in this PR should match the design in the prototype here: https://register-prototype.herokuapp.com/new-record/overview
> [367] Updated overview page in line with prototype design

- .erdconfig
- app/components/trainees/confirmation/diversity/view.html.erb
- app/components/trainees/confirmation/diversity/view.rb
- app/controllers/trainees/diversity/ethnic_groups_controller.rb
- config/initializers/diversity_enums.rb
- config/locales/en.yml
- spec/components/trainees/confirmation/diversity/view_preview.rb
- spec/components/trainees/confirmation/diversity/view_spec.rb
#136 needs to be merged first
- Adds new diversity confirmation component
Visit https://dfe-twd-rttd-pr-123.herokuapp.com/view_components/trainees/confirmation/diversity/view 
and test out the component in the different states
> [352] Add Diversity Confirmation component

- app/components/users/persona/view.html.erb
- app/components/users/persona/view.rb
- app/controllers/users_controller.rb
- app/views/users/personas.html.erb
- config/routes.rb
- spec/components/users/persona/view_preview.rb
- spec/components/users/persona/view_spec.rb
- Adds a new User Personas component
- Add `/users/personas` endpoint
View https://dfe-twd-rttd-pr-143.herokuapp.com/users/personas
View https://dfe-twd-rttd-pr-143.herokuapp.com/view_components/users/persona/view/single_profile
> [382] Add personas login page

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
Set the propensity to be able to manage secrets in a file
Currenty we have too many secrets on GhA (GitHub Actions). The idea is to consolidate these into a single file where application. The long term objectives is to move this Azure keyVault
> set secrets

- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace-variables/app_config.yml
In preparation for multi-stage (environment) deployment, the app specific environment variables are stored in yml file
Environment specific variables for each stage e.g. QA, Staging or Production are now emcompassed into a yml list
> Configure non secrets environment variable into yml file

- app/components/trainees/confirmation/programme_details/view.html.erb
- app/components/trainees/confirmation/programme_details/view.rb
- spec/components/trainees/confirmation/programme_details/view_preview.rb
- spec/components/trainees/confirmation/programme_details/view_spec.rb
https://trello.com/c/9r0pBHJR/303-s-confirm-trainee-programme-details-component
* Added a component for the programme details confirmation
* Added a test and preview for this component
Component preview
> 303 Add programme details confirmation component

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- terraform/workspace-variables/qa.tfvars
- terraform/workspace-variables/qa_backend.tfvars
- terraform/workspace-variables/staging.tfvars
- terraform/workspace-variables/staging_backend.tfvars
We need to migrate the application to reside in its new permanent PaaS workspace. Currently, it seats in register-qa workspace, but needs to be moved to bat-qa. 
This effort (PR) is to align it with the rest of the other application, as part of stragetic move to consolidte workspace between BAT application.
Specifiy new workspace that the application will reside moving forward. Also adopt the new credentials for the new workspace.
> Deploy to new-bat workspace

- spec/components/trainees/confirmation/programme_details/view_spec.rb
https://trello.com/c/9r0pBHJR/303-s-confirm-trainee-programme-details-component
This is a quick follow-up pr for a change to a test, accidentally omitted it from the main pr https://github.com/DFE-Digital/register-trainee-teachers/pull/154
* Fixed a test as requested by @defong
> 303 Change test for blank confirmation summary

- app/helpers/confirm_details_helper.rb
- app/models/progress.rb
- Fixes the following build error https://github.com/DFE-Digital/register-trainee-teachers/runs/1389429020 currently in `master`
- Handles the programme details section in the `Progress` class
> Fix failing programme details feature spec

- .github/workflows/deploy.yml
- .gitignore
- terraform/workspace-variables/staging_backend.tfvars
Deploy to Staging environment
Add continuous deploy logic to the build pipeline
> Deploy to statging environment

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- terraform/workspace-variables/app_config.yml
- terraform/workspace-variables/production.tfvars
- terraform/workspace-variables/production_backend.tfvars
Add Production deployment to the Github Action's deployment workflow
Add Production deployment to the Github Action's deployment workflow. 
The following files will be introduced:-
* terraform/workspace-variables/production.tfvars
* terraform/workspace-variables/production_backend.tfvars
The following files would be modified:-
*.github/workflows/deploy.yml
*terraform/workspace-variables/app_config.yml
> 432 deploy register to production

- app/controllers/trainees/check_details_controller.rb
- app/views/trainees/check_details/show.html.erb
- app/views/trainees/show.html.erb
- config/routes.rb
- spec/features/trainees/submit_for_trn_spec.rb
- spec/support/page_objects/trainees/check_details/show.rb
- spec/support/page_objects/trainees/summary.rb
This is not a complete page. It adds the basic layout that will be used
and more tickets will be created to fixed and tweak this page until it's finished.
- Review basic page mockup and flow.
- additional content and functionality will be added in another ticket.
> [507] Adds "Review this record" page

- README.md
We aren't using Travis
Add Github Action badges (build and deploy)
🚢
> Add proper badges to readme

- config/environments/qa.rb
- config/environments/review.rb
- config/environments/staging.rb
- config/settings/qa.yml
- config/settings/review.yml
- config/webpacker.yml
We have 3 additional environments that we'd like to control better - qa, staging and review
Add environment files and settings for 3 additional environments
🚢
> [481] Add extra environment files

- README.md
- config/application.rb
- config/environments/production.rb
- config/initializers/canonical_rails.rb
- manifest.yml
- Naming
- Update to canonical meta tag to the production domain
- Update cookie session name
- Update remaining boilerplate stuff to actual app name
####Cookie name before and after
🚢
> [475] Update canonical meta tag and other things 😅

- app.json
We now have a `review` environment so we should use it for review apps on Heroku
Update environment for review apps
🚢
> Update rails env for review apps

- .github/workflows/deploy.yml
- .github/workflows/smoke-test.yml
This is to add a smoke-test placeholder for Register app
Add smoke-test.yml file, which is triggered by dispatch workflow, waits for result before testing the next deployment.
> Add smoke test to build pipeline

- app/components/trainees/confirmation/record/view.html.erb
- app/components/trainees/confirmation/record/view.rb
- app/views/trainees/check_details/show.html.erb
- spec/components/trainees/confirmation/record/view_preview.rb
- spec/components/trainees/confirmation/record/view_spec.rb
Visit https://dfe-twd-rttd-pr-197.herokuapp.com/view_components/trainees/confirmation/record/view
> [521] Add record confirmation component

- app/components/trainees/confirmation/record/view.rb
- spec/components/trainees/confirmation/record/view_preview.rb
- spec/components/trainees/confirmation/record/view_spec.rb
> [xxxx] Fixed freeze ball of string

- docs/adr/0003-connections-to-dttp-dynamics.md
- docs/adr/index.md
Document decision to keep the logic of how to interact with DTTP and it's data model inside of the app versus in a separate shim.
Decision was made in the past, this just documents are reasoning for it.
Is anything missing from the options analysis, rational for why, etc?
This PR depends on #203 which should be merged first.
> add adr 0003 for connections to dttp dynamics 

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Add alert when build fails
The essessnce of this PR is to add alert mechnisim on CI build failure. At the moment, this is not being captured and alerted.
> Add CI build notification failure

- app/components/header/script.js
- app/components/header/style.scss
- app/components/header/view.html.erb
- app/components/header/view.rb
- app/views/layouts/application.html.erb
- spec/components/header/view_preview.rb
- spec/components/header/view_spec.rb
We will need to update the links to the "Your account" and "Sign out"
once the endpoints have been created
Visit https://dfe-twd-rttd-pr-210.herokuapp.com/view_components/header/view
> 498 - Add Header component

- config/settings/production.yml
- config/settings/qa.yml
- config/settings/staging.yml
Settings for DSI
Add settings for DfE Sign-In for staging and prod env's - `issuer` and `profile `
🚢
> [544] Add dsi settings for staging and prod

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- terraform/modules/statuscake/main.tf
- terraform/modules/statuscake/provider.tf
- terraform/modules/statuscake/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace-variables/production.tfvars
- terraform/workspace-variables/qa.tfvars
- terraform/workspace-variables/staging.tfvars
Add statusCake ping monitoring for Register application. As part of our system's availability and monitoring, it is essential we regularly check for downtime. 
Add statusCake ping monitoring for Register application
> Add statucake monitoring

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/errors_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/personas_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/sign_in_controller.rb
- app/controllers/trainees_controller.rb
- app/controllers/trn_submissions_controller.rb
- spec/controllers/sessions_controller_spec.rb
- spec/features/authentication_spec.rb
- spec/support/dfe_sign_in_user_helper.rb
- spec/support/features/authentication_steps.rb
unauthenticated users are redirected to the sign in page
Ensure unauthenticated users are redirected to the sign in page
> 490 unauthenticated users are redirected to the sign in page

- README.md
> Fix 404 link

- app/components/start_page_banner/style.scss
- app/components/start_page_banner/view.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/start.html.erb
- spec/components/start_page_banner/view_spec.rb
- spec/features/view_pages_spec.rb
- spec/support/page_objects/start.rb
Start page content and phase banner
- Update start page content
- Add phase banner
> 605 update start page

- README.md
- docs/govuk_paas.md
Find has some helpful PAAS docs. We would like some helpful PAAS docs.
Link in the README & additional documentation copied from Find.
> Add PAAS docs

- app/views/trainees/personal_details/edit.html.erb
Content
Remove first name hint text
🚢
> [641] Remove hint text from first name

- app/views/pages/start.html.erb
Content is confusing users
Remove content from start page
🚢
> [640] Remove content from start page

- app/views/trainees/new.html.erb
Content
Update trainee id hint text
🚢
> [639] Update trainee id hint text

- app/components/trainees/confirmation/personal_details/view.rb
- app/views/trainees/degrees/_uk_degree_form.html.erb
- app/views/trainees/degrees/new.html.erb
- app/views/trainees/degrees/type/new.html.erb
- config/locales/en.yml
- spec/components/trainees/confirmation/personal_details/view_spec.rb
AO Pilot
Content changes to degree
🚢
> 605 more content updates

- .github/workflows/deploy.yml
- .gitignore
- Makefile
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace-variables/app_config.yml
- terraform/workspace-variables/production.tfvars
- terraform/workspace-variables/qa.tfvars
- terraform/workspace-variables/review.tfvars
- terraform/workspace-variables/review_backend.tfvars
- terraform/workspace-variables/staging.tfvars
Add makefile to allow dynamic creating of Review appliaton. The Make file aslo makes it easily to call Terraform commands from the commandLine without supplying lengthy terraform arguments. 
add makefile
> Add makefile to CI\CD

- terraform/terraform.tf
Refactor deployment secrets
It used to be individual github secrets but it's easier to manage as 1 yaml file
> Read statuscake credentials from infra secrets yaml

- terraform/modules/paas/main.tf
Frequest Staging failed error
Avoid rate limiting on non authenticated pulls from docker hub
Also added binding to logit
> Add docker credentials to background job

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Deployment failures because of pipeline concurrency issues
Implement turnstyle and matrix in deploy workflow
> Enforce sequential deployment pipeline

- Makefile
The files are named production instead of prod
Rename prod to production in makefile
> Rename Makefile production target

- app/views/trainees/degrees/_non_uk_degree_form.html.erb
- app/views/trainees/degrees/_uk_degree_form.html.erb
- config/initializers/naric_non_uk.rb
- spec/support/page_objects/trainees/new_degree_details.rb
Non-uk degree page
- Update page title
- Change order of fields
- Change NARIC options
> [653] Update non-uk degree page layout

- app/views/trainees/check_details/show.html.erb
Record overview page
Re-order sections to match prototype and some content
🚢
> [667] Update content on trainee record review

- .dockerignore
Some unneccesary files and folders are added to the docker image during build e.g Terrform folder etc
Introduced .dockerignore file.
> 682 add dockerIgnore

- .github/workflows/build.yml
Add Turnstyle action to Build workflow
In an attempt to mitigated against the ongoing concurrency issues, it would help if we also add the Turnstyle Action (softprops/turnstyle@v1) to Build workflow.
> Add Turnstyle action to build workflow

- app/views/errors/internal_server_error.html.erb
- app/views/errors/not_found.html.erb
- app/views/errors/unprocessable_entity.html.erb
- config/locales/en.yml
> [724] Add page titles to error pages

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Use DfE forked turnstyle action
Use DfE forked turnstyle action
> Use DfE forked turnstyle action

- app/components/trainees/confirmation/degrees/view.rb
- app/views/trainees/degrees/_uk_degree_form.html.erb
- app/views/trainees/degrees/type/new.html.erb
- spec/components/trainees/confirmation/degrees/view_spec.rb
Content tweaks when adding another degree and a non-uk degree
Update content
> [739] Update content when adding an additonal degree

- Dockerfile
- Makefile
Add-bundle-path-to-path-variable. The means we could do `bundle exec rails c` within the App
Add /usr/local/bin to PATH in docker image
> Add /usr/local/bin to PATH in docker image

- app/views/trainees/edit.html.erb
- app/views/trainees/personal_details/show.html.erb
trainees#edit
Remove section headings from the trainee edit page
🚢
> [766] remove headings from trainee edit

- README.md
> Mention generating seeds in readme

- app/components/trainees/filters/view.html.erb
- app/components/trainees/filters/view.rb
- app/views/trainees/index.html.erb
- spec/features/trainees/filtering_trainees_spec.rb
A few tweaks to the filters:
* Make the links more descriptive for screen reader users.
* Reduce heading sizes of labels
> Filters tweaks

- Makefile
- config/environments/pen.rb
- config/settings/pen.yml
- config/webpacker.yml
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/modules/statuscake/main.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace-variables/app_config.yml
- terraform/workspace-variables/pen.tfvars
- terraform/workspace-variables/pen_backend.tfvars
- terraform/workspace-variables/production.tfvars
- terraform/workspace-variables/qa.tfvars
- terraform/workspace-variables/staging.tfvars
Need an environment for pen tests.
Add pen test environment.
This branch was tested by deploying a build out to the PEN test environment, logging in and using the system. This demonstrates that the PEN test environment is usable, although deploys need to be performed from the cmdline (currently un-documentated).
> [753] add pen environment

- README.md
Update README file with link to confluence page on resetting application secrets and password
Update README file with link to confluence page on resetting application secrets and password
> Update README file with link to resetting secrets

- Gemfile
- Gemfile.lock
- app/services/slack_notifier_service.rb
- config/settings/test.yml
- spec/services/slack_notifier_service_spec.rb
https://trello.com/c/2Fc8tzQ0/705-s-m-configure-for-slack-notifications
> 705 Add slack-notifier gem

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/models/provider.rb
- app/models/trainee.rb
- app/models/user.rb
- db/migrate/20210108163200_install_audited.rb
- db/schema.rb
- spec/models/provider_spec.rb
- spec/models/trainee_spec.rb
- spec/models/user_spec.rb
- spec/spec_helper.rb
Auditing models
- Add (audited)[https://github.com/collectiveidea/audited] gem
- Add audit to user model as a starting point
```ruby
user = User.last
user.first_name => # "Bob"
user.update!(first_name: "Ryan")
user.audits
```
> 704 add audit

- .github/workflows/smoke-test.yml
- .rspec
- spec/requests/smoke/health_check_spec.rb
- spec/requests/smoke_tests/health_check_spec.rb
-https://trello.com/c/kQtyhpFk/710-m-healthcheck-smoke-test
- Create a new spec directory for smoke tests
- Setup a basic health check smoke test to assert response of system without stubs
- Setup a tag to run specs without smoke tests by default
- Run smoke tests in build workflow
> [710] Healthcheck smoke test

- app/views/layouts/application.html.erb
Analytics
We can add Google Analytics (and other tracking tools) and set up goals etc with GTM
🚢
> [837] Add google tag manager

- app/views/errors/internal_server_error.html.erb
- app/views/errors/not_found.html.erb
- app/views/errors/unprocessable_entity.html.erb
- config/locales/en.yml
Content on error pages
Update content to match prototype
🚢
> [845] Content updates on error pages

- app/controllers/pages_controller.rb
- app/views/pages/data_requirements.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/pages_controller_spec.rb
https://trello.com/c/Fn0yqXbr/835-s-data-requirements-page
* Added data requirements page that can be reached from home page in future PR
* Added controller test
Navigate to /data-requirements to see markup rendered
> [835] Add data requirements page

- app/views/layouts/application.html.erb
Google Tag Manager
We have a BAT account and we can't move containers so I've created a new one
🚢
> [837] Update google tag manager ID

- app/components/personas/view.html.erb
Dead persona
Easter is still sometime away, performing dark magic instead
https://rtt-review-pr-402.herokuapp.com/personas
It broke all the other review apps
> [881] Fixed dead persona

- config/environments/production.rb
- config/initializers/content_security_policy.rb
PEN test security improvements
- Add `preload` attr to STS header
- Add Content Security Policy headers to cover GA, GTM and Azure
> 842 pen test fixes

- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/pages/start.html.erb
> [883] Home and start page cleanup

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/smoke-test.yml
- Makefile
- config/environments/sandbox.rb
- config/settings/sandbox.yml
- terraform/modules/statuscake/main.tf
- terraform/workspace-variables/app_config.yml
- terraform/workspace-variables/sandbox.tfvars
- terraform/workspace-variables/sandbox_backend.tfvars
Create Sandbox environment
Create Sandbox environment
> Setup register sandbox environment

- spec/components/header/view_preview.rb
- spec/components/trainees/timeline/view_preview.rb
Fix tests in master which are failing the build.
> Fix failing tests

- app/views/sign_in/index.html.erb
Email subject line change on sign in page
> [967] Edit subject on support link for sign in page

- app/components/application_record_card/view.html.erb
- app/components/application_record_card/view.rb
- app/components/dynamic_back_link/view.rb
- app/components/trainees/confirmation/programme_details/view.html.erb
- app/components/trainees/confirmation/programme_details/view.rb
- app/components/trainees/filters/style.scss
- app/components/trainees/filters/view.html.erb
- app/components/trainees/outcome_details/view.html.erb
- app/components/trainees/record_details/view.html.erb
- app/views/layouts/trainee_record.html.erb
- app/views/trainees/confirm_deferrals/show.html.erb
- app/views/trainees/confirm_withdrawals/show.html.erb
- app/views/trainees/outcome_details/confirm.html.erb
- app/views/trainees/outcome_details/recommended.html.erb
- app/views/trainees/withdrawals/show.html.erb
- config/locales/en.yml
- spec/components/application_record_card/view_spec.rb
- spec/components/dynamic_back_link/view_spec.rb
- spec/components/trainees/confirmation/programme_details/view_spec.rb
- spec/components/trainees/filters/view_spec.rb
- spec/components/trainees/record_actions/view_spec.rb
- spec/features/trainees/filtering_trainees_spec.rb
- spec/features/trainees/recommending_for_qts_spec.rb
Withdrawal page updates
- Content
- Form legend styles
- Backlink label
- Cancel CTA
> [883] Clean up withdrawal page

- app/views/pages/data_requirements.html.erb
The markup on the data-requirements page is not correct and the back link does not work.
- Change div's and span's to correct markup
- Fix back link
- pull down the code and inspect the code
- Navigate to the data-requirements page on the website and check the back button works and the page is as it should be.
> [978] Fix up data requirements page

- app/views/trainees/review_draft/show.html.erb
- https://trello.com/c/ylnBNeHE/983-update-task-list-section-heading-in-build-in-line-with-prototype
- Update copy
> [983] Update task list section heading in build, in line with prototype

- app/components/header/view.html.erb
Use sentence case and make text match design system header.
> Use sentence case for text

- app/lib/dttp/code_sets/ethnicities.rb
- config/initializers/diversity_enums.rb
Ben Pearce and I discovered during our DTTP mappings meeting that "Irish Traveller" was missing from the ethnicities list.
> Add Irish Traveller to Dttp::CodeSets::Ethnicities::MAPPING

- app/components/application_record_card/view.rb
- spec/components/application_record_card/view_spec.rb
These should really be an h3 or not a heading.
There's already h2s these sit within.
> Reduce heading level of trainee card

- config/locales/en.yml
These two messages have been really bugging me. 
Words by @EmmaFrith.
> Improve language of error messages

- app/views/errors/internal_server_error.html.erb
- app/views/errors/not_found.html.erb
- app/views/errors/unprocessable_entity.html.erb
- app/views/pages/accessibility.html.erb
- app/views/pages/privacy_policy.html.erb
> [1058] Fixed email is not in use

- app/views/trainees/degrees/type/new.html.erb
> [1030] Fix heading type on degree page

- app/components/trainees/deferral_details/view.html.erb
> [1039] Add missing hidden span for deferral date change link

- app/lib/dttp/batch_request.rb
- spec/lib/dttp/batch_request_spec.rb
- Minor refactoring and spec improvements for `Dttp::BatchRequest`
> Improve BatchRequest spec to ensure correct headers and body are sent

- .github/workflows/deploy.yml
- Makefile
- terraform/modules/paas/main.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace-variables/production.tfvars
Upgrade postgres service plan to `small-ha-11` from `tiny-unencrupted-11`
Upgrade postgres service plan to `small-ha-11`
> 1022 upgrade register database plan

- app/views/layouts/trainee_record.html.erb
- config/locales/en.yml
> [1043] Remove trainee name from show page title

- app/services/trns/submission_checker.rb
- lib/tasks/example_data.rake
- spec/services/trns/submission_checker_spec.rb
> [1090] Added training details to be validated

- app/components/trainees/confirmation/degrees/view.html.erb
- app/components/trainees/confirmation/degrees/view.rb
- app/views/sign_in/index.html.erb
- app/views/trainees/review_draft/show.html.erb
- app/views/trn_submissions/show.html.erb
Use the correct `govuk_button_link_to` helper instead of links with `govuk-button` class - this is needed so the component gets correctly shimmed for AT and responds to the space bar.
I did a manual search of `govuk-button` class to review where it was used.
> Use correct helper for button-links

- .github/workflows/build.yml
> fix-workflow

- .github/workflows/build.yml
revert worflow name
revert workflow name
> revert workflow name - deploy to Paas

- config/settings/sandbox.yml
We don't want to write test users to production in the sandbox environment.
Use the QA DTTP paths for sandbox.
> [xxx] Use QA DTTP paths

- .github/workflows/deploy.yml
- .gitignore
- Makefile
- terraform/data.tf
- terraform/modules/statuscake/main.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace-variables/local.sh
- terraform/workspace-variables/production.sh
- terraform/workspace-variables/production.tfvars
- terraform/workspace-variables/qa.sh
- terraform/workspace-variables/qa.tfvars
- terraform/workspace-variables/review.tfvars
- terraform/workspace-variables/sandbox.sh
- terraform/workspace-variables/sandbox.tfvars
- terraform/workspace-variables/staging.sh
- terraform/workspace-variables/staging.tfvars
Integrate terraform with keyvault
This is a move away from storing application and infrastructure secrets on Github Actions.
data azurerm_key_vault
> 728 read secrets from azure key vault

- app/views/trainees/personal_details/edit.html.erb
Change `Last name` to `Last names` to be more inclusive
> [1104] Change last name to last names

- config/settings.yml
- config/settings/qa.yml
- config/settings/review.yml
> [1135] Amended trainee export to be on

- config/webpacker.yml
> [XXXX] Add sandbox env to webpacker config

- app/controllers/trainees/personal_details_controller.rb
- db/migrate/20210224154323_remove_other_nationality.rb
- db/schema.rb
- https://trello.com/c/TNb7p39J/1144-remove-other-nationality-option-in-prod-via-a-migration
- Remove the "other" record from the db
> [1144] Remove this redundant record

- Gemfile
- Gemfile.lock
- README.md
- config/skylight.yml
Adding skylight to the app.
All the gubbings required to get Skylight working, including the badge in the README. We'll still need to add the appropriate env var to configure the token.
> [927] add skylight

- terraform/workspace-variables/production.tfvars
- terraform/workspace-variables/qa.tfvars
- terraform/workspace-variables/sandbox.tfvars
- terraform/workspace-variables/staging.tfvars
Use correct `servercode` from https://app.statuscake.com/API/Locations/json
London, Manchester and Dublin
> Use correct node_locations for Status Cake

- app/views/trainees/start_dates/edit.html.erb
- config/locales/en.yml
https://trello.com/c/L0UlVCKD/1192-remove-pointless-hint
Removes hint and adds a better page title.
> [1192] Remove hint

- app/components/trainees/sort_links/script.js
- app/components/trainees/sort_links/style.scss
- app/components/trainees/sort_links/view.html.erb
- app/components/trainees/sort_links/view.rb
- config/locales/en.yml
https://trello.com/c/mHM5NW5G/1180-s-sort-link-markup
- Reduce HTML complexity
- Make the HTML more semantic
- Make the sort links screen reader friendly
Visually, nothing changes, just better markup.
> [1180] Improve sort link markup

- app/lib/dttp/code_sets/grades.rb
> Make capitalisation consistent

- app/controllers/sessions_controller.rb
- app/controllers/system_admin/providers_controller.rb
- app/models/provider.rb
- app/views/system_admin/providers/new.html.erb
- config/locales/en.yml
- db/migrate/20210309155415_add_code_to_providers.rb
- db/schema.rb
- spec/components/trainees/timeline/view_preview.rb
- spec/factories/providers.rb
- spec/models/provider_spec.rb
https://trello.com/c/K00TnpxK/1228-s-add-provider-code-to-providers
* Add column "code" to providers
* New field on system admin new provider page
* CSV export of providers from production to backfill code
> [1228] Add code to Provider model

- config/initializers/redis.rb
https://trello.com/c/DBUTm3VJ/1275-fix-redis-connection-issue-on-all-environments
- Update Redis initializer to use `VCAP_SERVICES`
> [1275] Fix Redis connection on all environments

- config/settings/audit.yml
We have an audit environment...
It has personas enabled.
It shouldn't have personas enabled.
Un-enable them and...
* Use DfE Signin
> [xxx] Use DSI in audit env

- app/controllers/system_admin/providers_controller.rb
- app/views/system_admin/providers/new.html.erb
- db/migrate/20210309140020_add_apply_sync_to_provider.rb
- db/schema.rb
- spec/features/providers/creating_a_new_provider_spec.rb
- spec/support/page_objects/providers/new.rb
https://trello.com/c/Yo3PV3HD/1237-per-provider-enable-disable-apply-sync
Added apply_sync_enabled field to providers table
Checkbox on Provider new page that sets value to true when selected
Add to feature test
Validation out of scope?
At /system-admin/providers/new
> [1237] Per provider enable/disable Apply sync

- app.json
- config/initializers/redis.rb
> [1279] Add redis to review apps

- app/components/trainees/confirmation/course_details/view.html.erb
- app/views/trainees/course_details/edit.html.erb
- app/views/trainees/review_draft/show.html.erb
- config/settings/audit.yml
Missing settings variable in audit env. There are a few small changes due to the linter.
> [1281] Missing settings variable in audit env

- Gemfile
- Gemfile.lock
Fix for https://github.com/DFE-Digital/register-trainee-teachers/commit/2f6a8e7697a37e471687949094d8302a1afa9bce/checks
🚢
> Bump mimemagic

- Dockerfile
- Gemfile.lock
Bump mimemagic to 0.3.9
Install freedesktop.org.xml package
> Bump mimemagic to 0.3.9

- spec/features/authentication_spec.rb
- spec/features/providers/creating_a_new_provider_spec.rb
- spec/features/trainees/defer_trainee_spec.rb
- spec/features/trainees/degrees/adding_degree_spec.rb
- spec/features/trainees/delete_trainee_spec.rb
- spec/features/trainees/diversities/edit_disabilities_spec.rb
- spec/features/trainees/diversities/edit_disability_disclosure_spec.rb
- spec/features/trainees/diversities/edit_disclosure_spec.rb
- spec/features/trainees/diversities/edit_ethnic_background_spec.rb
- spec/features/trainees/diversities/edit_ethnic_group_spec.rb
- spec/features/trainees/edit_course_details_spec.rb
- spec/features/trainees/edit_personal_details_spec.rb
- spec/features/trainees/edit_trainee_id_spec.rb
- spec/features/trainees/edit_trainee_training_route_spec.rb
- spec/features/trainees/filtering_trainees_spec.rb
- spec/features/trainees/recording_training_outcome_spec.rb
- spec/features/trainees/reinstating_a_trainee_spec.rb
- spec/features/trainees/viewing_an_existing_trainee_spec.rb
- spec/features/trainees/withdraw_trainee_spec.rb
https://trello.com/c/WIYovpYi/1359-use-page-objects-consistently
- Replace calls to `page` with the relevant page object
- Minor factorings
> [1359] Use page objects consistently

- app/components/trainees/confirmation/reinstatement_details/view.rb
- app/components/trainees/confirmation/withdrawal_details/view.rb
- config/environments/development.rb
- config/environments/test.rb
- config/locales/en.yml
Missing translations
Set config for `raise_on_missing_translations` to be `true` for `development` & `test` only
Also removed unused items 
Hopefully we have enough test coverage to stop it needless surfacing
> 1360 missing translations should raise hell

- app/controllers/trainees/start_dates_controller.rb
- app/controllers/trainees/trainee_ids_controller.rb
- app/controllers/trainees/training_details_controller.rb
https://trello.com/c/QPMRWsPd/1366-check-unused-controller-methods
This PR removes a couple of `def confirm` controller methods that are now being handled by the generic `ConfirmDetailsController`.
🚢
> [1366] Remove unused controller methods

- Gemfile
- Gemfile.lock
mimemagic gem
Remove mimemagic gem
:ship:
> [xxxx] Remove mimemagic gem

- app/views/trainees/confirm_deferrals/show.html.erb
- app/views/trainees/contact_details/edit.html.erb
- app/views/trainees/course_details/edit.html.erb
- app/views/trainees/deferrals/show.html.erb
- app/views/trainees/outcome_dates/edit.html.erb
- app/views/trainees/outcome_details/confirm.html.erb
- app/views/trainees/personal_details/edit.html.erb
- app/views/trainees/reinstatements/show.html.erb
- app/views/trainees/start_dates/edit.html.erb
- app/views/trainees/trainee_ids/edit.html.erb
- config/locales/en.yml
https://trello.com/c/8nO4xkX2/1365-fix-inconsistant-use-of-i18n
* Links reused often is now I18n
> [1365] fix inconsistent i18n use

- app/views/trainees/degrees/_non_uk_degree_form.html.erb
We've seen a few users try to enter a town or an institution name in this box - this should hopefully make it clearer we're asking for a country.
> Update label to make clearer we're asking for a country

- docs/adr/0004-non-integer-trainee-ids.md
- docs/adr/index.md
- docs/adr/template.md
We have ADRs. We didn't have one for this decision.
* Add ADR for non-integer trainee IDs.
Read the thing... 😁
> [864] ADR 4 - non-integer trainee IDs

- db/migrate/20210401153358_change_level_on_course.rb
- db/schema.rb
- spec/models/course_spec.rb
db datatype issues
Fixed db datatype issues
If you got data you on your own
> [xxxx] fixed db level

- .rubocop.yml
- app/models/course.rb
- app/models/trainee.rb
- app/services/teacher_training_api/import_course.rb
- config/initializers/training_routes.rb
- db/migrate/20210401134151_add_route_to_course.rb
- db/schema.rb
- spec/factories/courses.rb
- spec/models/course_spec.rb
Routes to courses
Added routes to courses
got annoyed with `# frozen_string_literal: true` so added to autocorrect
> [1379] store route in courses

- app/views/sign_in/index.html.erb
Add missing embedded ruby operator
Visit signin page to verify bug is gone
> Bug Fix on Sign in Page

- app/views/trainees/index.html.erb
- config/locales/en.yml
no records message
Added better no records message
Login as Bridget Campbell
> [1446] Added better no records message

- db/migrate/20210420150757_create_schools.rb
- db/schema.rb
To unblock other tickets that depend on the schools table
> [1552] Add migration for schools table

- app/models/school.rb
- app/services/school_search.rb
- db/migrate/20210421143341_add_lead_school_to_schools.rb
- db/migrate/20210421154952_add_partial_index_to_schools.rb
- db/schema.rb
- spec/factories/schools.rb
- spec/services/school_search_spec.rb
https://trello.com/c/HzPiXKMd/1553-l-school-search-service
- New search service object `SchoolSearch`
- Partial index for the column `lead_school` so that we only index where the value is TRUE (no point indexing for FALSE since it adds no value)
Study code and specs - confirm it matches requirements
> [1553] School search service

- app/models/trainee.rb
- db/migrate/20210422143630_add_lead_school_to_trainees.rb
- db/schema.rb
- spec/models/trainee_spec.rb
https://trello.com/c/OZG89cfc/1591-s-create-association-between-trainees-and-schools
Should merge after PR https://github.com/DFE-Digital/register-trainee-teachers/pull/785
* new column "lead_school_id" added to trainees
* belongs_to association added to Trainee for School (optional)
> [1591] added belongs_to association for lead_school for trainee

- app/controllers/api/application_controller.rb
- app/controllers/api/schools_controller.rb
- config/application.rb
- config/locales/en.yml
- config/routes.rb
- config/routes/api_routes.rb
- config/routes/system_admin_routes.rb
- spec/controllers/api/schools_controller_spec.rb
- spec/rails_helper.rb
- spec/support/api_request_helpers.rb
- https://trello.com/c/XYlxQsQH/1555-l-school-search-api
- Build up the initial schools endpoint 
- Populate the schools table and use postman to query `/api/schools` with any of the following params `query`, `limit`, `lead_school`
> [1555] - Schools api endpoint

- app/lib/training_route_manager.rb
- app/models/trainee.rb
- app/views/trainees/review_draft/show.html.erb
- config/initializers/training_routes.rb
- config/settings.yml
- db/schema.rb
- spec/factories/trainees.rb
- spec/lib/training_route_manager_spec.rb
- spec/models/trainee_spec.rb
https://trello.com/c/iudIYbt4/1557-s-add-schools-section-to-review-draft
* Add schools direct option to training route manager. Will check if the trainee's training route is either school direct route then render the school section accordingly if feature flag is also enabled
* Add conditional logic to show view
* Add unit test to check that a trainee on school direct route will see school section
* Status tag out of scope but hardcoded as status is a required argument to component. 
Toggle school direct feature flags in settings.yml  and add a trainee to check if a trainee on those routes will see school section
> [1557] Add schools section to review draft

- app/services/trainees/create_timeline_events.rb
- spec/services/trainees/create_timeline_events_spec.rb
https://trello.com/c/l9SrTiPZ/1574-s-anonymise-admin-names-from-the-timeline
Before: If a system admin (like a dev) made a change to a trainee on behalf of a user, their full name would be visible on the timeline.
Now: We just show 'Administrator' rather than the dev's name. Names of other users are still visible.
- Log in as the system admin 'Adam Baker'
- Choose a non-draft trainee
- Make a change to the trainee e.g. change their name
- Visit the timeline
- See that "Administrator" is visible rather than "Adam Baker" for the related timeline entry
> [1574] Anonymise usernames for system admins in the timeline

- app/forms/contact_details_form.rb
- app/forms/training_details_form.rb
- app/views/trainees/training_details/edit.html.erb
- config/locales/en.yml
- spec/forms/contact_details_form_spec.rb
- spec/forms/publish_course_details_form_spec.rb
- spec/models/provider_spec.rb
- spec/models/user_spec.rb
https://trello.com/c/MaOwWunO/1622-error-message-changes
See the checklist on the trello ticket.
Visit the pages as described on the trello ticket, submit the forms empty to see the error messages.
> [1622] Content changes to error messages

- app/components/trainees/confirmation/lead_school/view.html.erb
- app/components/trainees/confirmation/lead_school/view.rb
- app/controllers/trainees/confirm_details_controller.rb
- app/helpers/confirm_details_helper.rb
- app/models/progress.rb
- config/locales/en.yml
- config/routes.rb
- db/schema.rb
- spec/components/trainees/confirmation/lead_school/view_preview.rb
- spec/components/trainees/confirmation/lead_school/view_spec.rb
https://trello.com/c/wrrdpIck/1561-m-lead-schools-confirm-page
* new component for lead school confirm page
* add new trainee, add lead school
> [1561] lead schools confirm page

- config/settings/qa.yml
https://trello.com/c/Jhg4dnT5/1639-switch-on-school-direct-salaried-route-in-qa-environment
> [1639] Enable school direct salaried route for QA environment

- config/settings/qa.yml
https://trello.com/c/e6WcQyk7/1657-switch-on-schools-direct-tuition-fee-route-in-qa
> [1657] Enable school direct tuition fee route for QA environment

- app/models/provider.rb
- db/migrate/20210505144359_add_ukprn_to_dttp_provider.rb
- db/schema.rb
- spec/factories/providers.rb
- spec/models/provider_spec.rb
ukprn is not the same as code
Added ukprn to provider and remove code validation
:shipit:
> [1648] Added ukprn to provider

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- Makefile
- config/environments/rollover.rb
- terraform/workspace-variables/app_config.yml
- terraform/workspace-variables/rollover.sh
- terraform/workspace-variables/rollover.tfvars
- terraform/workspace-variables/rollover_backend.tfvars
Deploy app to rollover environment
Terraform config for rollover environment
Created app secrets in key-vault for rollover.
Deploy app to rollover after sandbox.
> Deploy app to rollover environment

- config/settings.yml
- config/settings/qa.yml
- config/settings/staging.yml
- Enable the provder-led features in qa/staging
First part required to send a provider-led trainee to DTTP for testing. Waiting on this PR https://github.com/DFE-Digital/register-trainee-teachers/pull/901
> Enable provider-led features in QA/Staging

- app/views/trainees/employing_schools/_no_results.html.erb
- app/views/trainees/employing_schools/_results.html.erb
- app/views/trainees/employing_schools/edit.html.erb
- app/views/trainees/lead_schools/_no_results.html.erb
- app/views/trainees/lead_schools/_results.html.erb
- app/views/trainees/lead_schools/edit.html.erb
- app/views/trainees/lead_schools/index.html.erb
Similar to https://github.com/DFE-Digital/register-trainee-teachers/pull/929 but using design system classes
as suggested [here](https://github.com/DFE-Digital/register-trainee-teachers/pull/929#discussion_r643855477)
Similar to https://github.com/DFE-Digital/register-trainee-teachers/pull/929
> [1867] Change autocomplete field widths to three-quarters

- app/controllers/pages_controller.rb
- app/views/pages/data_requirements.html.erb
- app/views/pages/guidance.html.erb
- app/views/pages/home.html.erb
- config/locales/en.yml
- config/locales/pages/data_requirements/en.yml
- config/locales/pages/guidance/en.yml
- config/routes.rb
- spec/controllers/pages_controller_spec.rb
Add content changes to the guidance page.
[Ticket](https://trello.com/c/Kwc3pH1Q/1827-s-content-changes-to-guidance)
> [1827] Add guidance page content changes

- .github/workflows/build.yml
- .github/workflows/delete-review-app.yml
- .github/workflows/deploy.yml
- .github/workflows/smoke-test.yml
- Makefile
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace-variables/production.tfvars
- terraform/workspace-variables/qa.tfvars
- terraform/workspace-variables/review.tfvars
- terraform/workspace-variables/review_backend.tfvars
- terraform/workspace-variables/rollover.tfvars
- terraform/workspace-variables/sandbox.tfvars
- terraform/workspace-variables/staging.tfvars
Create review app on PaaS
Terraform configuration for review apps.
Workflow changes to deploy review app on PaaS
Workflow to delete review app on PR close/merge.
> Review apps on PaaS

- config/locales/en.yml
> [1859] Added tweaks to Timeline labels

- app/components/trainees/record_actions/view.rb
- app/views/trainees/outcome_dates/edit.html.erb
> Fix specs on master

- app/components/trainees/confirmation/training_details/view.rb
- app/components/trainees/sections/view.rb
- app/controllers/trainees/confirm_details_controller.rb
> Remove code no longer in use - all sections now support save-on-confirm

- app/lib/notify_on_timeout.rb
The method signature of slack notifier has changed. 
Update this calling code that was missed.
> [xxx] Update `NotifyOnTimeout` to use the new method

- app/lib/dttp/code_sets/allocation_subjects.rb
- db/seeds.rb
https://trello.com/c/JrmoS9dk/2010-s-seed-subject-specialisms-into-table
Seed data into respective tables
> [2010] Seed subject specialisms and allocation subject data

- spec/lib/page_tracker_spec.rb
https://trello.com/c/IVY6BECg/2027-tidy-up-page-tracker-spec
Fix it friday
Session is spelt sesssion throughout the spec
> [2027] Tidy Page tracker spec session

- spec/factories/courses.rb
- [This trello ticket](https://trello.com/c/1q7uMtaB/2067-bug-flakey-example-data-generate-test)
- Added unique to the Faker code generator that creates code
- Run the spec `rspec spec/lib/tasks/example_data_spec.rb`
> [2067] Created unique constraint on the courses factory/faker

- app/views/layouts/application.html.erb
- config/settings.yml
- config/settings/production.yml
- config/settings/staging.yml
> [2080] Update google tag manager snippet

- app/controllers/trainees/funding/training_initiatives_controller.rb
- config/locales/en.yml
- spec/features/form_sections/teacher_training_data/edit_training_initiative_spec.rb
https://trello.com/c/NI1M2o1g/1992-m-funding-ui-joining-everything-together
* direct to bursary page if there is bursary, otherwise redirect to confirm the page
* With bursary add "School direct (tuition fee)" with course "Applied biology"
> [1992] Funding - UI - joining everything together

- config/settings/staging.yml
This feature was set to true in the secrets file, which isn't the right
place for it really. This change moves it into the settings flie.
> set staging to persist to dttp

- Makefile
Manage review apps via command line (and delete if necessary)
Amend targets to make them work with review apps
run deploy-plan and destroy
> [2145] Review app Makefile targets

- app/controllers/trainees/confirm_details_controller.rb
- config/locales/en.yml
- spec/features/form_sections/personal_and_education_details/degrees/delete_degree_spec.rb
https://trello.com/c/ktwCe1bJ/2148-general-snagging-confirm-page
* All confirm page titles start with "Confirm trainee's xxx"
* Complete each section to see confirm page
> [2148] General snagging - confirm page

- app/views/trainees/funding/bursaries/edit.html.erb
- config/locales/en.yml
https://trello.com/c/tHMWxyRB/2129-bursaries-updated-form-for-early-years-salaried
* Text updated for early years
* Add new trainee with _Early Years (salaried)_ route
* Add funding, see bursary form
> [2129] Bursaries - updated form for Early Years (salaried)

- spec/services/trainees/create_from_apply_spec.rb
:ship: 
use `match_array`
:wolf:
> [2174] Fixed array flakey ordering of tests

- config/settings/staging.yml
> Enable school direct routes in staging

- config/settings/staging.yml
> Enable sync from dttp jobs in staging

- .github/workflows/smoke-test.yml
- .tool-versions
- Dockerfile
- Gemfile
- Gemfile.lock
We use Ruby. There's a new version.
Upgrade to it.
* Draft as ruby-build hasn't been updated yet.
> Upgrade to Ruby 2.7.4

- .github/workflows/database-backup.yml
We currently don't store the backup and rely of on PaaS for backups and retention.
A workflow to take a backup of the database and store it in Azure storage.
> Workflow to backup prod DB in Azure storage

- app/helpers/task_list_helper.rb
- app/lib/training_route_manager.rb
- config/initializers/training_routes.rb
- config/locales/en.yml
- config/settings.yml
- config/settings/development.yml
- config/settings/qa.yml
- config/settings/review.yml
- config/settings/staging.yml
- spec/features/end_to_end/pg_teaching_apprenticeship_journey_spec.rb
- spec/models/trainee_spec.rb
- spec/services/dttp/contact_update_spec.rb
- spec/services/dttp/register_for_trn_spec.rb
- spec/support/features/training_route_steps.rb
- spec/support/page_objects/trainees/new.rb
PGTA route
Added PGTA route
Works as prototype
> [2231] Add pgta route

- config/settings/production.yml
https://trello.com/c/uvwVNq3C/2277-enable-provider-led-and-school-direct-routes-in-production
> [2277] Enable provider-led and school routes in prod

- config/settings/production.yml
> [2277] Toggle publish course flags

- app/lib/dttp/params/degree_qualification.rb
- app/lib/dttp/params/placement_assignment.rb
- spec/lib/dttp/params/degree_qualification_spec.rb
- spec/lib/dttp/params/placement_assignment_spec.rb
https://trello.com/c/DxtBYIob/2235-s-send-degree-date-to-dttp
* `PlacementAssignment` and `DegreeQualification` updated to include `dfe_undergraddegreedateobtained` which sets degree graduation year as "2021-01-01" format
> [2235] Send degree date to DTTP

- docs/adr/0005-store-invalid-data-in-a-column-against-applyapplication.md
As a follow up to https://github.com/DFE-Digital/register-trainee-teachers/pull/1169, add an ADR.
:eyes:
> Add adr on storing invalid data against ApplyApplication

- app/components/badges/view.html.erb
- app/components/badges/view.rb
- app/controllers/pages_controller.rb
- app/view_objects/home_view.rb
- app/views/pages/_badges.html.erb
- app/views/pages/home.html.erb
- app/views/trainees/funding/bursaries/_non_tiered_bursary_form.html.erb
- app/views/trainees/funding/bursaries/_tiered_bursary_form.html.erb
- config/locales/en.yml
- spec/components/badges/view_preview.rb
- spec/components/badges/view_spec.rb
- spec/view_objects/home_view_spec.rb
https://trello.com/c/vkEYmIYr/2389-update-homepage
- Applies the changes to the homepage as per the prototype.
- Includes a tidy up of the `Badges` component, which included unneeded code distinguishing between full-width squares and narrow-squares.
- Moves logic into the `HomeView`, importantly `registered_state_counts` so that the badges and the counts elsewhere on the homepage should always align.
> [2389] Update homepage

- app/lib/dttp/code_sets/course_subjects.rb
Add new subject mappings that have been added to DTTP
> [2381] Add DTTP subject mappings for new subjects

- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
#1220 requires `BLAZER_DATABASE_URL`
Create a separate service-key for database connection
Configure BLAZER_DATABASE_URL
> Set BLAZER_DATABASE_URL environment variable

- app/forms/personal_details_form.rb
- spec/forms/personal_details_form_spec.rb
https://trello.com/c/4mOZFjkX/2427-nationality-issue
Fixes the following bugs:
- Any values selected in “other_nationalities” in the personal details
form were overwriting (and being duplicated) values for British and 
Irish
- Deselecting “Other” was not ignoring any other nationalities that
had been previously added, and was also still running validations on them
- The check to try and match a nationality entered was a raw value but
not selected was still validating that the non-raw field was not blank,
even when it could calculate it from the raw value.
- Rerendering the page with errors was leaving the raw values intact
in the autocompletes even if they had been successfully matched with 
the correct titleized name
Try to break the form in some way or reproduce the bugs mentioned above …
> [2427] Fix nationalities bugs

- config/locales/en.yml
Hint text
Amended `portion`  to `part`
:ship:
> [2438] Amended `portion`  to `part`

- config/settings/production.yml
https://trello.com/c/VZCucU0m/2324-release-eytsao-eytspg
- Switch on the EY(AO) and EY(PG) routes in production.
> [2324] Release EY(AO) and EY(PG)

- config/settings/production.yml
https://trello.com/c/jtDgaLwO/2325-complete-pgta
- Release the PGTA route to production.
> [2325] Release PGTA route to prod

- app/lib/training_route_manager.rb
- config/settings.yml
- spec/components/course_details/view_spec.rb
- spec/features/end_to_end/school_direct_salaried_journey_spec.rb
- spec/features/end_to_end/school_direct_tuition_fee_journey_spec.rb
- spec/forms/course_details_form_spec.rb
- spec/lib/training_route_manager_spec.rb
https://trello.com/c/eUwJMDDc/2488-m-course-study-mode-question-feature-flag
* New feature flag `course_study_mode`, default `false`
> [2488] Course study mode question - feature flag

- app/components/funding/view.rb
- app/forms/funding/form_validator.rb
Fixes stashing behaviour when updating funding information from the trainee record page.
> Fix funding stashing behaviour

- app/components/training_details/view.html.erb
- app/components/training_details/view.rb
- app/views/trainees/training_details/edit.html.erb
- config/locales/en.yml
https://trello.com/c/VJMp2jqa/2416-s-missing-information-ui-training-details-section
> [2416] Missing information UI (Training details section)

- app/views/pages/accessibility.html.erb
- config/locales/pages/accessibility/en.yml
Updating the accessibility page in line with DAC's audit and adding a back link.
- Update the accessibility page content in line with the Trello ticket
- Add a back link
- Visit `/accessibility`
> [2448] Update accessibility page

- app/lib/dttp/code_sets/course_study_modes.rb
- app/lib/dttp/mappable.rb
- app/lib/dttp/params/placement_assignment.rb
- spec/lib/dttp/params/placement_assignment_spec.rb
https://trello.com/c/abUO5hnT/2430-m-course-study-mode-question-sending-to-dttp
* `dfe_studymodeid@odata.bind` param added to `Dttp::Params::PlacementAssignment`
> [2430] Course study mode question - sending to DTTP

- app/controllers/concerns/publish_course_next_path.rb
- app/forms/confirm_publish_course_form.rb
- config/settings/qa.yml
- spec/forms/confirm_publish_course_form_spec.rb
- Fix study mode feature flag
- Switch the study mode question on in QA
> [XXXX] Fix study mode feature flag

- app/jobs/dttp/retrieve_award_job.rb
- app/models/trainee.rb
- app/services/dttp/retrieve_award.rb
- spec/jobs/dttp/retrieve_award_job_spec.rb
- spec/models/trainee/state_transitions_spec.rb
- spec/services/dttp/retrieve_award_spec.rb
- spec/services/trainees/create_timeline_events_spec.rb
Change `awarded_at` date to use DTTP supplied value instead of current time.
> [2474] Set QTS awarded_at date to the value of dfe_qtseytsawarddate

- app/lib/dttp/code_sets/bursary_details.rb
- app/lib/dttp/code_sets/funding_bands.rb
- app/lib/dttp/mappable.rb
- app/lib/dttp/params/placement_assignment.rb
- spec/factories/bursaries.rb
- spec/factories/trainees.rb
- spec/lib/dttp/params/placement_assignment_spec.rb
https://trello.com/c/wffvfcGh/2051-m-funding-send-bursaries-to-dttp
Sends the relevant bursary-related parameters to DTTP.
> [2051] Funding - send bursary details to DTTP

- app/jobs/apply_api/import_applications_job.rb
- app/services/apply_api/import_application.rb
- spec/jobs/apply_api/import_applications_job_spec.rb
- spec/services/apply_api/import_application_spec.rb
- spec/support/api_stubs/apply_api.rb
- [This trello ticket](https://trello.com/c/Utr5xzjR/2472-s-hesa-duplicates)
- Added a conditional to skip any apply applications that have a `training_provider_type` of `'university'`
- Run the test suite or import an apply application that has a `training_provider_type` of `university`
> [2472] Added conditional to skip hei provider apply applications

- app/views/trainees/index.html.erb
- spec/support/page_objects/trainees/index.rb
Create a trainee button
Amended button text to `Create a trainee record`
> [2620] Amended button text to `Create a trainee record`

- config/initializers/training_routes.rb
- config/locales/en.yml
- config/settings.yml
- config/settings/development.yml
- config/settings/review.yml
- spec/models/trainee_spec.rb
Provider led undergrad route
Add provider led undergrad route
:ship:
> [2587] Add provider led undergrad route

- config/settings.yml
- config/settings/staging.yml
https://trello.com/c/ueZhqVy9/2653-test-apply-integration-with-real-data-final-snag
- Enable feature flag so we can test importing applications from Apply
> [2653] Enable importing applications from apply (staging only)

- config/initializers/training_routes.rb
- db/data/20210831150141_add_bursaries.rb
Bursary
Added bursary for provider led undergrad, £9000 for maths/physic
:shipit:
> [2586] Added bursary for provider led undergrad

- app/forms/outcome_date_form.rb
- config/locales/en.yml
- spec/forms/outcome_date_form_spec.rb
- spec/support/features/training_details_steps.rb
Outcome date
Added validation to prevent future dates for outcome
Put in a future date
> [2550] Added validation to prevent future dates for outcome

- config/settings/qa.yml
- config/settings/review.yml
> [xxx] Enable Provider-led (UG) in QA and EY (salaried) in review

- config/settings/development.yml
- config/settings/qa.yml
- config/settings/review.yml
> [xxx] Enable the early years and opt in undergrad in QA

- .github/workflows/database-backup.yml
- db/scripts/sanitise.sql
Provide a sanitised database copy for debugging/local development purposes.
https://trello.com/c/15unia02/2694-sanitise-production-database
SQL script to sanitise user, trainee data.
Amend the daily database backup workflow to sanitise 
the backup using the above script and upload sanitised dump as artifact.
Are the scripts accurate?
> Sanitise production database 

- config/initializers/training_routes.rb
- config/locales/en.yml
- https://trello.com/c/P2C18M2M/2717-snags-opt-in-and-early-years-ug
- Fix award type label for opt-in ug
- Fix missing translation for missing data
> [2717] A couple of early years and opt-in undergrad snags

- app/services/exports/trainee_search_data.rb
- spec/services/exports/trainee_search_data_spec.rb
https://trello.com/c/Y1ps3onL/2723-rename-csv-export-column-for-trainee-id
What it says up there.
> [2723] Rename CSV column provider_training_id -> provider_trainee_id

- config/settings/production.yml
https://trello.com/c/g6l77uNL/2730-release-sending-funding-to-dttp
We held off sending funding to DTTP until we had tested the integration. Now we have tested as much as we can in the staging environment, we're enabling it in production.
🚢
> [2730] Enable sending funding to DTTP in prod

- config/settings/production.yml
- config/settings/sandbox.yml
https://trello.com/c/qNjJP3Nh/2742-release-ey-salaried-route
Release the Early years (salaried) route to production (and sandbox) environment.
🚢
> [2742] Release EY (salaried) route to prod (and sandbox)

- app/lib/dttp/params/placement_assignment.rb
- spec/lib/dttp/params/placement_assignment_spec.rb
UG routes do not require degrees so we omit sending this information to DTTP
> [xxxx] Omit degree subject params for UG routes

- app/controllers/trainees/apply_applications/confirm_courses_controller.rb
- app/forms/apply_applications/confirm_course_form.rb
- app/models/trainee.rb
- https://trello.com/c/5ywXm1Uu/2737-snag-some-courses-not-being-picked-up
- https://trello.com/c/wLFIR7Dj/2740-snag-course-information-is-shown-as-missing-data
- https://trello.com/c/ZjdGlIYu/2739-snag-order-course-list-alphabetically
- Fixes a few snags from the apply integration mainly around the components not displaying the trainee course data properly
- Also orders the course list shown to apply drafts
- Handles redirecting correctly to the confirm page if an apply draft choses to enter a subject manually
> Xxxx a few apply snags

- app/lib/dttp/code_sets/course_subjects.rb
Fixes https://sentry.io/organizations/dfe-bat/issues/2520356788/?project=5552118&referrer=slack
> Update DTTP entity id for Chinese languages

- app/lib/dttp/code_sets/qualification_aims.rb
- app/lib/dttp/code_sets/routes.rb
- app/lib/dttp/params/placement_assignment.rb
- spec/lib/dttp/params/placement_assignment_spec.rb
Omit sending the params above for UG routes
> [xxxx] - Omit undergraddegreedateobtained params for UG routes

- config/initializers/training_routes.rb
- db/data/20210916114659_add_scholarships.rb
- db/seeds.rb
Scholarships
Seeding scholarships
> [2702] Added seedlings for scholarships

- app/services/trainees/create_from_apply.rb
- spec/services/trainees/create_from_apply_spec.rb
- spec/support/api_stubs/apply_api.rb
- https://trello.com/c/OODT7zPw/2741-snag-handle-disability-information
- Fixes missing nationality and gender information
- Handles other cases of disability information
> [2741] Handle disability information and fix missing nationality/gender

- config/settings/production.yml
- config/settings/sandbox.yml
- config/settings/staging.yml
> [xxxx] - Turn Opt in, provider led and early years UG routes in prod

- app/lib/dttp/params/placement_assignment.rb
- spec/factories/trainees.rb
- spec/lib/dttp/params/placement_assignment_spec.rb
https://trello.com/c/awOJzRV2/2751-m-update-dttp-funding-params-to-include-scholarships
Sends scholarship details to DTTP.
> [2751] Send scholarship details to DTTP

- app/components/funding/view.rb
- app/controllers/trainees/funding/bursaries_controller.rb
- app/forms/funding/bursary_form.rb
- app/forms/funding/form_validator.rb
- app/lib/funding_manager.rb
- app/views/trainees/funding/bursaries/_non_tiered_bursary_form.html.erb
- app/views/trainees/funding/bursaries/_tiered_bursary_form.html.erb
- app/views/trainees/funding/bursaries/edit.html.erb
- config/locales/en.yml
- config/settings.yml
- config/settings/qa.yml
- config/settings/review.yml
- spec/forms/funding/bursary_form_spec.rb
- spec/forms/funding/form_validator_spec.rb
- spec/support/features/funding_details_steps.rb
- spec/support/page_objects/trainees/funding/bursary.rb
https://trello.com/c/jmBMGGwt/2704-m-add-scholarship-option-to-bursary-form
* Refactored `BursaryForm` to change from boolean to funding_type.
* Updated component to show scholarship
* Feature flag `scholarship` added
* Choose `Provider-led (postgrad)` route and `Chemistry`. Go to funding section.
> [2704] Add scholarship option to bursary form

- app/forms/publish_course_details_form.rb
https://trello.com/c/0BImWPo2/2735-bug-study-mode-isnt-updated-when-changing-publish-course
* `study_mode` & `course_start_date` is set from course when course is changed
> [2735] Bug - study mode isn't updated when changing publish course

- config/settings/staging.yml
:shipit: 
:shipit: 
Works with #1434
> [2756] Added scholarship to staging

- config/settings/production.yml
- config/settings/sandbox.yml
- config/settings/staging.yml
Enable study mode question in prod, staging and sandbox.
🚢
> [xxx] Enable study mode feature in prod

- config/settings/development.yml
- config/settings/production.yml
- config/settings/sandbox.yml
Enable scholarships in prod and sandbox (plus development).
🚢
> [xxx] Enable scholarships in production

- app/components/form_components/autocomplete/script.js
- app/components/form_components/country_autocomplete/script.js
Add beginning/end anchors to regex.
> [2749] Add beginning and end anchors to regex

- app/components/degrees/view.rb
- app/views/trainees/degrees/_uk_degree_form.html.erb
- spec/features/form_sections/personal_and_education_details/degrees/adding_degree_spec.rb
- spec/features/form_sections/personal_and_education_details/degrees/editing_degree_spec.rb
- spec/support/features/degree_information_steps.rb
https://trello.com/c/XreOZOa7/2771-first-class-honours-should-be-honours
* Updated views to show grade capitalised.
* Degree edit page, confirm page
> [2771] First-class Honours - should be ‘honours’

- db/data/20210921134907_reset_update_sha_for_funding.rb
Fix the data migration in prod.
> [xxx] Fix data migration for funding

- db/data/20210924102858_enable_spply_sync_for_providers.rb
> [2800] Added data migration to enable apply sync for all providers

- docs/support_playbook.md
We do lots of things on support but we don't document them. Let's start...
* Add page
* Add instructions for Retrieve TRN timeouts.
> [xxx] Add support playbook doc

- db/scripts/sanitise.sql
We have a sanitised version of the DB backup with PII removed. Now we have turned the apply integration on we need to remove the application attributes.
Sanitise application attributes
Sanitise trainee_id - this often contains trainee's names
> [xxx] Update sanitise script

- docs/support_playbook.md
We have a support playbook. It doesn't have much stuff in it yet.
Add instructions for fixing missing schools
> [xxx] Add missing school to playbook

- app/lib/funding_manager.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/production.yml
- config/settings/qa.yml
- config/settings/review.yml
- config/settings/sandbox.yml
- config/settings/staging.yml
Removing the Scholarships feature flag because "Scholarships ain't going anywhere"
What it says on the tin
> [2822] Remove scholarship

- app/views/trainees/training_routes/_form_fields.html.erb
- config/settings.yml
- config/settings/development.yml
- config/settings/review.yml
- spec/features/end_to_end/teach_first_journey_spec.rb
Remove `enable_teach_first_provider` feature flag.
> Remove enable_teach_first_provider feature flag

- app/lib/dttp/code_sets/bursary_details.rb
Add mapping to Postgraduate ~Bursary~ Grants in DTTP.
:shipit:
> Add grant mapping for pg teaching apprenticeship route

- app/forms/trn_submission_form.rb
- config/settings/test.yml
- spec/forms/trn_submission_form_spec.rb
School validation was getting bypassed
School validation via the TrnSubmissionForm was getting skipped
> [3096] Fixed school validation as it was getting bypassed

- docs/support_playbook.md
Add unwithdrawing a trainee instructions to `support_playbook.md`
> Add unwithdrawing a trainee instructions to support_playbook.md

- config/locales/en.yml
https://trello.com/c/UMzMztaz/3176-content-change-lead-and-employing-schools
Added content changes.
> [3176] Content changes for lead and employing schools forms

- app/components/record_details/view.rb
- config/locales/en.yml
- spec/components/record_details/view_spec.rb
- spec/factories/trainees.rb
- spec/features/form_sections/teacher_training_data/edit_trainee_start_status_spec.rb
https://trello.com/c/3DnYjTL4/3161-trainee-start-date-row-record-view
* Updated `RecordDetails` component to dynamically set trainee start date row
* Non-draft Trainee record details page.
> [3161] Trainee start date row - record view

- db/data/20211118144020_update_trainee_withdrawal_date.rb
https://trello.com/c/zos238JK/3230-update-withdrawal-date-on-withdrawn-trainee
- Data migration to change trainee withdraw date
> [3230] Change trainee withdraw date

- db/data/20211118144020_update_trainee_withdrawal_date.rb
The data migrations also run on staging so we need to make sure they
don't fail if the records being updated don't exist.
Handle nil trainee.
> [xxx] Fix failing data migration

- config/settings/production.yml
- config/settings/qa.yml
- config/settings/staging.yml
We're ready to start sending events in qa, staging and production now. 
Enable the feature in those environments.
> [xxx] Enable BigQuery in qa, staging and production

- db/data/20211117164147_update_trainee_trns.rb
https://trello.com/c/571WVMDX/2943-duplicate-trainees
Still waiting on one more trainee. They currently have 2 TRNs in DQT; waiting to find out which one is correct.
- Data migration to make the TRN changes for a group of trainees
> [2943] Update trainee TRN's

- db/data/20211122140126_seed_academic_cycles.rb
Forgot to actually seed the academic cycles from this PR https://github.com/DFE-Digital/register-trainee-teachers/pull/1749 😞
> [3235] Seed academic cycles

- README.md
There were some small commands/ clarifications that would have been useful for me to have when setting up my repo. 
I have added them to the readme so that in future devs might have a smoother onboarding.
Please let me know if you'd like it formatted differently! 
Small readme changes.
> update readme with correct setup info

- docs/big_query_setup.md
Instructions for creating a BigQuery dataset and credentials for sending analytics events to. This has been done for register now so we'll probably move these docs to somewhere more data-ish when such a place exists.
Add docs.
Read 'em and then ask yourself... Could I do this?
> [xxx] Big Query setup docs

- config/locales/en.yml
https://trello.com/c/6me29388/3234-l-course-years-ui
* Copy fix on course years UI
> [3234] Course years UI - copy fix

- db/service_updates.yml
Service updates about the census publication.
> Census publication update

- app/controllers/trainees_controller.rb
- app/helpers/trainee_helper.rb
- app/models/academic_cycle.rb
- app/models/trainee_filter.rb
- app/services/trainees/filter.rb
- app/views/trainees/_filters.html.erb
- config/locales/en.yml
- spec/helpers/trainee_helper_spec.rb
- spec/models/academic_cycle_spec.rb
- spec/models/trainee_filter_spec.rb
- spec/services/trainees/filter_spec.rb
https://trello.com/c/LiMuMYZH/3238-s-start-year-filter
* New start year filter on trainees page
* See trainees page, select filter.
> [3238] Start year filter

- config/settings/dttpimport.yml
For testing the DTTP sync.
Flip the flag.
🚢
> [xxx] Switch on sync_trainees_from_dttp in dttpimport env

- app/controllers/trainees_controller.rb
- app/models/trainee_filter.rb
- app/services/trainees/filter.rb
- app/views/trainees/_filters.html.erb
- config/locales/en.yml
- spec/models/trainee_filter_spec.rb
- spec/services/trainees/filter_spec.rb
https://trello.com/c/v18RJEtD/2732-s-add-study-mode-filter
- Add study mode filter to trainees page. 
- Test in review app that the filter works
> [2732] Add study modes filter to trainees

- app/helpers/course_details_helper.rb
- app/services/trainees/filter.rb
- spec/services/trainees/filter_spec.rb
Add allocation subject for grouped sciences so that it appears as a filter option
> 3288 add grouped sciences filter option

- .github/PULL_REQUEST_TEMPLATE.md
We have a PR template. We have some things we would like to remember when we review a PR.
Add some helpful reminders to said template...
Read 'em.
> [xxx] Update PR template

- app/models/dttp/trainee.rb
- app/services/trainees/create_from_dttp.rb
Move `latest_placement_assignment`, `earliest_placement_assignment` and `sorted_placement_assignments` over to `Dttp::Trainee` as suggested by @AbigailMcP 
:ship:
> Move *_placement_assignment accessors to Dttp::Trainee

- app/services/exports/trainee_search_data.rb
- spec/services/exports/trainee_search_data_spec.rb
https://trello.com/c/p1HJ3xdo/3289-s-include-undergrad-postgrad-in-csv-export
* New export column `course_level` added
* Trainees list, click export these records
> [3289] Include undergrad / postgrad in csv export

- app/controllers/system_admin/schools_controller.rb
- app/models/school.rb
- app/policies/school_policy.rb
- app/views/system_admin/_tab_nav.html.erb
- app/views/system_admin/schools/index.html.erb
- config/locales/en.yml
- config/routes/system_admin_routes.rb
- spec/features/system_admin/schools/list_schools_spec.rb
- spec/policies/school_policy_spec.rb
- spec/support/features/page_helpers.rb
- spec/support/page_objects/schools/index.rb
https://trello.com/c/a0B1uprL/3371-m-schools-list
* New `schools` section in system admin with list of all schools
* Login as admin, go to system admin and click `Schools`
> [3371] Schools list

- app/controllers/system_admin/lead_schools_controller.rb
- app/policies/lead_school_policy.rb
- app/views/system_admin/_tab_nav.html.erb
- app/views/system_admin/lead_schools/index.html.erb
- config/locales/en.yml
- config/routes/system_admin_routes.rb
- spec/features/system_admin/lead_schools/list_lead_schools_spec.rb
- spec/policies/lead_school_policy_spec.rb
- spec/support/features/page_helpers.rb
- spec/support/page_objects/lead_schools/index.rb
https://trello.com/c/6Nk2hZD5/3372-s-lead-schools-list
* New section in system admin for lead schools
* login as admin user and go to system admin section, click on lead schools
> [3372] Lead schools list

- spec/factories/academic_cycles.rb
- spec/factories/courses.rb
- spec/factories/dttp/api_placement_assignment.rb
- spec/factories/trainees.rb
- spec/support/date_helpers.rb
https://trello.com/c/yaFrPv0c/3448-specs-failing-after-entering-2022
- Update factories to use the correct recruitment cycle year
> [3448] Fix failing specs that were affected after entering 2022

- app/controllers/system_admin/lead_schools_controller.rb
- app/views/system_admin/lead_schools/index.html.erb
- app/views/system_admin/lead_schools/show.html.erb
- config/routes/system_admin_routes.rb
- spec/features/system_admin/lead_schools/show_lead_school_spec.rb
- spec/support/features/page_helpers.rb
- spec/support/page_objects/lead_schools/show.rb
https://trello.com/c/W41YJZPI/3373-s-lead-school-page
Depends on:
https://github.com/DFE-Digital/register-trainee-teachers/pull/1848
* Show page added for lead school
* Login as admin, go to system admin, click on "Lead school" and click into a lead school.
> [3373] lead school page

- app/services/trainees/create_from_dttp.rb
**Background:**
- DTTP has option 'Not known' for disabilities and ethnicities, Register does not.
- Register has option 'Not provided' for disabilities and ethnicities, DTTP does not.
When we send to DTTP, we map "Not provided" => "Not known".
Now we're mapping in the other direction, so DTTP "Not known" comes through as "Not provided"
This makes things confusing.
https://trello.com/c/6rAWkoy1/3459-fix-imported-dttp-trainees-with-incomplete-ethnicity-sections
**This PR:**
- Calculates `diversity_disclosure` in a separate method, since this depends on both disability and/or ethnicity presence. Before it was being calculated first based on disability, then based on ethnicity.. which would override the first calculation!
- Records a disability_disclosure of "disability_not_provided" when …
> [3459] Update calculations of diversity and disability disclosure

- config/analytics.yml
analytics.yml defines the fields we send to BigQuery. There were a few missing.
* Add missing IDs to course_subjects and apply_applications
* Add academic_cycle_id to funding_methods
* Remove the duplicate apply_applications#id field
The entities will need resending as import events to BQ. I'll so that in the console (note to self, we should add that in the support console).
Just spellings/naming really.
> [3446] Update analytics.yml

- app/components/user_card/view.html.erb
- app/components/user_card/view.rb
- app/controllers/system_admin/lead_schools/users_controller.rb
- app/views/system_admin/dttp_providers/show.html.erb
- app/views/system_admin/dttp_users/index.html.erb
- app/views/system_admin/lead_schools/index.html.erb
- app/views/system_admin/lead_schools/show.html.erb
- app/views/system_admin/lead_schools/users/edit.html.erb
- app/views/system_admin/lead_schools/users/new.html.erb
- app/views/system_admin/providers/show.html.erb
- config/locales/en.yml
- config/routes/system_admin_routes.rb
- spec/factories/lead_school_users.rb
- spec/factories/users.rb
- spec/features/system_admin/lead_schools/users/creating_a_new_user_spec.rb
- spec/features/system_admin/lead_schools/users/viewing_users_spec.rb
- spec/support/page_objects/lead_schools/index.rb
- spec/support/page_objects/lead_schools/show.rb
https://trello.com/c/A1JAbOiS/3376-m-add-user-to-lead-school
* New `lead_schools/users` controller added
* New user form creates user and add association with LeadSchool
* Login as admin, go to systems admin, click on lead school, add user.
> [3376] Add user to lead school

- app/lib/dttp/code_sets/institutions.rb
https://trello.com/c/wVCzlueo/3521-s-non-importable-dttp-degrees-missing-institution
- Add a couple of missing institutions that were preventing degrees from being imported.
> [3521] Add missing institutions to DTTP code set

- db/service_updates.yml
Adds a service update about when we collect start dates.
> Service updates for start dates

- README.md
Remove note about installing graphviz from readme, as we do not use that anymore.
> Update readme, remove note about installing graphviz

- app/components/funding/view.rb
- app/services/trainees/create_from_dttp.rb
https://trello.com/c/g40od0yp/3498-m-trainees-with-no-bursary-awarded-in-dttp-are-coming-through-with-incomplete-funding-sections
- Fix `Trainees::CreateFromDttp` so it doesn't leave values in the DB `NULL` when computing funding attributes
- Refactor `Funding::View#grant_funding_row` to make it easier to read
> [3498] Trainees with no bursary awarded in DTTP are coming through with incomplete funding sections

- app/components/form_components/autocomplete/script.js
https://trello.com/c/m0DlB1CT/3501-m-degree-type-autocomplete-bug
* I don't know how, but it works
* Set course name one (or some other autocomplete field) to non-listed value
* Does it show "undefined" when you first click the textbox?
> [3501] Autocomplete undefined bug fix

- config/locales/en.yml
https://trello.com/c/Ux4tMuCL/3573-s-bad-translation-in-missing-details-banner-for-full-time-part-time
- Translation update for study mode when missing
> [3573] Change translation for study mode when missing

- app/components/navigation_bar/style.scss
- app/components/navigation_bar/view.html.erb
- app/components/navigation_bar/view.rb
- app/helpers/organisation_helper.rb
- app/views/layouts/application.html.erb
- config/settings/review.yml
- spec/components/navigation_bar/view_spec.rb
https://trello.com/c/ZXKXSEAg/3599-m-organisation-context-switching-component
* Dependent on PR: https://github.com/DFE-Digital/register-trainee-teachers/pull/1968
* Updated `NavigationBar` component to allow right aligned menu item
* Added change organisation link on application layout.
* Login with user which has multiple providers
* I have added Bridget Campbell to two providers
> [3599] Organisation context switching component

- .github/workflows/smoke-test.yml
- .tool-versions
- Dockerfile
- Gemfile
- Gemfile.lock
- package.json
https://trello.com/c/pxKgASD7/3649-update-docker-base-image
This is to resolve security vulnerabilities in the base image
alpine, ruby and nodejs will be updated in this change
ruby:2.7.4-alpine3.12 to ruby:2.7.5-alpine3.15
nodejs 12.18.3 to 16.14.0
ruby 2.7.4p191 to ruby 2.7.5p203
check locally
check review app
> Update docker base image to ruby:2.7.5-alpine3.15

- config/initializers/personas.rb
Update persona names.
Redistribute implied genders.
> [xxx] Rename personas

- app/services/send_welcome_email_service.rb
- config/settings.yml
- spec/services/send_welcome_email_service_spec.rb
https://trello.com/c/C40nFwLy/3672-lead-school-welcome-email
* Updated existing `WelcomeEmailMailer` to use new lead school user welcome template
* Updated `SendWelcomeEmailService` to only send email to lead school users
* 🤷‍♀️
> [3672] Lead school welcome email

- config/locales/pages/guidance/en.yml
https://trello.com/c/TXqpuRaS/3546-update-guidance-for-lead-schools
* Guidance locale updated with new section
* Go to `/guidance` page
> [3546] Update guidance for lead schools

- app/services/trainees/create_timeline_events.rb
- app/views/drafts/index.html.erb
- app/views/layouts/application.html.erb
- config/locales/en.yml
- spec/controllers/pages_controller_spec.rb
- spec/features/trainee_actions/submit_for_trn_spec.rb
- spec/support/page_objects/start.rb
Some bug fixes
1. Ensure ITT is correctly capitalised on timeline (and add an abbreviation)
2. Change Draft tab and heading from "Draft records" to "Draft trainees"
1. Login as any user and check draft tab and heading.
2. Login as "Provider A" and view the timeline events against the trainee.
https://register-pr-2065.london.cloudapps.digital/trainees/euZy83fhwsDDaG7Ns4fJSX8X/timeline
or make some edits against another trainee and check their timeline.
> [3527] [3704] bug fixes

- config/locales/en.yml
- config/locales/pages/accessibility/en.yml
https://trello.com/c/oPnnM5G0/3552-update-accessibility-statement
* Updated accessibility page with content changes
* Login and click the "accessibility" link on the footer.
> [3552] Update accessibility statement

- db/migrate/20220224173011_add_state_to_hesa_collection_request.rb
- db/schema.rb
There is a failing migration in main that wasn't caught on the PR.
Fix it.
> [xxx] Fix broken migration

- config/settings/qa.yml
We are soon going to be launching a feature to allow users to belong to more than one organisation.
We want to test and demo this with support users prior to release.
> [xxx] Enable the multi org feature on QA

- app/jobs/dqt/register_for_trn_job.rb
- app/jobs/dqt/retrieve_trn_job.rb
- app/lib/dqt/client.rb
- app/models/dqt/trn_request.rb
- app/services/dqt/register_for_trn.rb
- app/services/dqt/retrieve_trn.rb
- config/settings.yml
- db/migrate/20220225152144_create_dqt_trn_requests.rb
- db/schema.rb
- spec/factories/dqt/trn_requests.rb
- spec/jobs/dqt/register_for_trn_job_spec.rb
- spec/jobs/dqt/retrieve_trn_job_spec.rb
- spec/models/dqt/trn_request_spec.rb
- spec/services/dqt/register_for_trn_spec.rb
- spec/services/dqt/retrieve_trn_spec.rb
https://trello.com/c/5peN6dPU/3709-l-dqt-trn-request-jobs-services
* Jobs and services added to register and retrieve TRN from DQT
* Run on console? 🤷‍♀️
> [3709] DQT TRN request jobs & services

- app/jobs/hesa/retrieve_collection_job.rb
- app/services/trainees/create_from_hesa.rb
- spec/jobs/hesa/retrieve_collection_job_spec.rb
Change the way validations are handled during a HESA import.
> [XXX] HESA import - handle trainee validation exceptions

- .github/actions/deploy/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/build.yml
- .github/workflows/deploy.yml
The workflows that initiate a deployment use workflow_dispatch, this can result in unnecessary failures when subsequent workflow doesn't wait and makes logs harder to read. 
This change refactors the workflow to use reusable actions.
- Confirm that workflow conditions and results remain the same.
> Refactor deployment workflows

- app/components/application_record_card/view.html.erb
- app/components/application_record_card/view.rb
- app/controllers/base_trainee_controller.rb
- app/controllers/trainees_controller.rb
- app/helpers/course_details_helper.rb
- app/models/academic_cycle.rb
- app/models/trainee_filter.rb
- app/services/trainees/filter.rb
- app/view_objects/start_year_filter_options.rb
- app/views/trainees/_filters.html.erb
- app/webpacker/styles/_govuk_overrides.scss
- config/locales/en.yml
- spec/components/application_record_card/view_spec.rb
- spec/factories/academic_cycles.rb
- spec/helpers/course_details_helper_spec.rb
- spec/models/academic_cycle_spec.rb
- spec/models/trainee_filter_spec.rb
- spec/services/trainees/filter_spec.rb
- spec/view_objects/start_year_filter_options_spec.rb
Render start year on record card and add a start year filter
> [3547] Add Start Year Filter for Historic Trainees

- db/service_updates.yml
Added information about DTTP switch off.
> Added new section to news and updates

- app/jobs/dqt/queue_trainee_updates_job.rb
- app/jobs/dqt/update_trainee_job.rb
- app/lib/dqt/client.rb
- app/lib/dqt/params/trainee_request.rb
- app/lib/dqt/params/trn_request.rb
- app/models/trainee.rb
- app/services/dqt/trainee_update.rb
- config/sidekiq_cron_schedule.yml
- db/migrate/20220315113557_add_dqt_update_sha_to_trainees.rb
- db/schema.rb
- spec/jobs/dqt/queue_trainee_updates_job_spec.rb
- spec/lib/dqt/params/trainee_request_spec.rb
- spec/models/trainee_spec.rb
- spec/services/dqt/trainee_update_spec.rb
https://trello.com/c/jziJaqoy/3779-m-dqt-updates
* Added new column `dqt_update_sha` to trainees
* Created jobs, services and API request to update DQT
* Lotsa backend
> [3779] DQT Updates

- spec/features/system_admin/users/add_a_lead_school_to_user_spec.rb
Fix a flakey test whereby a different to expected school was being selected from a dropdown.
> [xxx] Fix flakey lead school search spec

- app/views/request_an_account/index.html.erb
- config/locales/en.yml
https://trello.com/c/Pc91XzlT/3872-update-content-for-request-an-account-page-on-production
* Updated page with new content
* Go to `/request-an-account`
> [3872] Update content for Request an account page on production

- config/locales/pages/guidance/en.yml
https://trello.com/c/VLUv1GpP/3896-update-about-register-trainee-teachers-page-on-production
- Removed information
The sections "Register access for lead schools" and "Funding" cannot be commented out due to the file type.
- Company screenshot in Trello card with review app under `/guidance`
> [3896] Guidance page content update

- .github/workflows/build-and-deploy.yml
- Gemfile
- Gemfile.lock
Add job that posts output of bundle audit to register_tech channel. 
Insight into how to test this new functionality would be very handy
> 3807-Add-job-to-check-dependency-vulnerabilities

- Gemfile.lock
> [xxxx] Update nokogiri to 1.13.4

- config/analytics.yml
We send data to BigQuery based on the analytics.yml file. There was some oddness in it.
The school table had some duplicate fields and a couple of fields `data` and `session_id` that do not exist on the `School` model.
cc/ @alexchristensenedu - #twd_data_insights
> [xxx] Fix analytics.yml

- app/views/request_an_account/index.html.erb
- config/locales/en.yml
Update content on request an account page.
Visit `/request-an-account` and compare with https://register-prototype.herokuapp.com/request-an-account
- ~[ ] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?~
- ~[ ] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?~
~NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml~
> [3972] Update request an account page content

- config/analytics.yml
> Update analytics.yml to add created_from_hesa

- config/locales/en.yml
- config/locales/pages/privacy_policy/en.yml
Privacy Policy updated to https://register-prototype.herokuapp.com/privacy-policy
Content changes to the /privacy-policy page
Login to the deploy app and compare /privacy-policy to  https://register-prototype.herokuapp.com/privacy-policy
> [3927] Update privacy policy

- app/lib/hesa/client.rb
- spec/lib/hesa/client_spec.rb
https://trello.com/c/xgQ17ac7/4029-fix-hesa-login
- Update `Hesa::Client` to handle the recent update to HESA's login form
> [4029] Adjust Hesa::Client to handle new HESA login page

- app/controllers/funding/monthly_payments_controller.rb
- app/controllers/funding/trainee_summaries_controller.rb
- app/helpers/navigation_helper.rb
- app/views/layouts/application.html.erb
- config/routes.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/review.yml
https://trello.com/c/kYXimT36/4002-s-funding-feature-flag-and-page-structure
- Add funding feature flag
- Add `funding/monthly-payments` route and corresponding controller and empty view
- Add `funding/trainee-summary` route and corresponding controller and empty view
- Add nav link to funding, visible if feature flag is enabled
- Visit `funding/monthly-payments`.. see it's empty
- Visit `funding/trainee-summary`... see it's empty
- See that there's a funding link in the nav that links to monthly-payments
> [4002] Funding feature flag and page structure

- app/models/funding/payment_schedule.rb
- app/models/funding/payment_schedule_row.rb
- app/models/funding/payment_schedule_row_amount.rb
- app/models/funding/trainee_summary.rb
- app/models/funding/trainee_summary_row.rb
- app/models/funding/trainee_summary_row_amount.rb
- db/migrate/20220422163025_create_funding_trainee_summaries.rb
- db/migrate/20220422163744_create_funding_trainee_summary_row.rb
- db/migrate/20220422165007_create_funding_trainee_summary_row_amounts.rb
- db/migrate/20220425165149_create_funding_payment_schedules.rb
- db/migrate/20220425165745_create_funding_payment_schedule_rows.rb
- db/migrate/20220425170224_create_funding_payment_schedule_row_amounts.rb
- db/schema.rb
6 new models for the new funding feature. Discussed the naming also with Ralph. Have namespaced new models under Funding.
~~I've used different naming compared to what we used in the spike and wrote on the ticket as felt these names are possibly a bit clearer.~~
After a lot of discussion as a team, the models are called:
`Funding::PaymentSchedule`
`Funding::PaymentScheduleRow`
`Funding::PaymentScheduleRowAmount`
`Funding:TraineeSummary`
`Funding:TraineeSummaryRow`
`Funding:TraineeSummaryRowAmount`
I'm not sure if we want to update any analytics files off the back of these changes at the moment.
* Add new funding namespace with relevant models for funding feature
* Add PaymentSchedule which has many payment_schedule_rows
* Add PaymentScheduleRow which has many payment_schedule_row_amounts …
> [4003] Funding Models

- app/models/provider.rb
- app/models/school.rb
We need to add associations to the new funding models in the Provider and School model. This should have been in [4003] Funding Models. https://github.com/DFE-Digital/register-trainee-teachers/pull/2281 
* Add associations on `Provider` and `School` to `funding_payment_schedules` and `funding_trainee_summaries`
* Check i've added the associations correctly! They are polymorphic on `payable_id`
> [xxx] Add funding associations on Provider and School

- app/controllers/pages_controller.rb
- app/views/pages/data_sharing_agreement.html.erb
- app/views/pages/home.html.erb
- config/locales/en.yml
- config/locales/pages/data_sharing_agreement/en.yml
- config/routes.rb
https://trello.com/c/PDOYLnAN/4050-dsa-upload-to-production
- Add the data sharing agreement page
- Linked from footer
> [4050] Add data sharing agreement page and link from footer

- app/lib/hesa/client.rb
- spec/lib/hesa/client_spec.rb
Need to also send the submit button with the form, without this there
was no button=login param being sent in and the HESA system was
breaking.
> [4061] Fix login to HESA

- app/view_objects/funding/monthly_payments_view.rb
- spec/factories/funding/payment_schedule_row_amounts.rb
- spec/factories/funding/payment_schedule_rows.rb
- spec/factories/funding/payment_schedules.rb
- spec/view_objects/funding/monthly_payments_view_spec.rb
https://trello.com/c/PhPOLnQn/4004-m-fundingmonthlypaymentsview
- New view object `Funding::MonthlyPaymentsView`
> [4004] Funding::MonthlyPaymentsView

- app/services/exports/trainee_search_data.rb
- spec/services/exports/trainee_search_data_spec.rb
Fix issue where academic year is always showing up as 'nil'. Have it correctly list academic year. Change the name of academic year to start year.
Pull down export check its working.
> 4048 fix start year export

- config/settings/production.yml
We had disabled the HESA integration due to firstly the authentication issues caused by MFA and then some data issues that we uncovered.
These issues have both been addressed now so...
* enable HESA integration in production
* We've been running it in dttpimport since the 3/5 with no issues.
> [xxx] Enable HESA integration in production

- db/service_updates.yml
We have enabled the HESA integration.
Add a service update notifying users.
> [4097] Add service update for HESA integration

- Makefile
- docs/disaster-recovery.md
- docs/maintenance-mode.md
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
A DR process is required to handle data corruption.
https://trello.com/c/1ZgbV0NE
- Add a DR process to docs and supporting make recipe and scripts to execute it
- Document the maintenance page process
Ensure the process meets the requirements in [technical guidance](https://technical-guidance.education.gov.uk/infrastructure/disaster-recovery/#data-corruption).
> Add dr docs data corruption

- .github/actions/deploy/action.yml
- .github/workflows/build-and-deploy.yml
https://trello.com/c/QTYqpCFJ/582-register-build-workflow-notification-bug
Fix variables in notifications
See:
- https://ukgovernmentdfe.slack.com/archives/CGVNJ2Q2F/p1652699727576309
- https://ukgovernmentdfe.slack.com/archives/CGVNJ2Q2F/p1652700278431949
> Fix workflow notification messages

- .github/actions/deploy/action.yml
- Makefile
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace-variables/dttpimport.tfvars.json
- terraform/workspace-variables/production.tfvars.json
- terraform/workspace-variables/qa.tfvars.json
- terraform/workspace-variables/sandbox.tfvars.json
- terraform/workspace-variables/staging.tfvars.json
The deployment URL must be changed since the official URL has changed
Refactor terraform, makefile and workflow so it reads from terraform config and stop creating extra routes.
Includes minor makefile and workflow improvements
Run terraform plan agains existing environments
This will cause routes to be recreated which may cause a few seconds outage. This must be done out of hours.
> [579] Update register environment url in workflow

- db/service_updates.yml
https://trello.com/c/X35JMCks/4024-news-and-updates-post-for-service-domain-update
Updated news section to mention domain name change
Review the start page and check latest news and updates is there
> [4024] news and updates - new domain

- .github/actions/deploy/action.yml
The URL of the review app deployment doesn't work anymore
Fix the URL in the workflow
See below URL
> Fix review app deployment URL

- db/scripts/sanitise.sql
We create a sanitised backup of the register DB.
Clear the PII from the hesa_students table in the sanitised backup.
> [xxx] Sanitise the hesa_students table

- db/data/20220516105534_fix_funding_methods_for20192020.rb
https://trello.com/c/1POTbi8l/4128-fix-funding-rules-for-2019-20
Add data migration that:
- Deletes the funding method's we have for 2019/20
- Adds the correct ones based on the section "Undergraduate bursary" in the manual: https://www.gov.uk/government/publications/initial-teacher-training-itt-bursary-funding-manual/initial-teacher-training-bursaries-funding-manual-2019-to-2020-academic-year#undergraduate-bursary
> [4128] Add data migration to fix funding methods for 2019/20

- .github/workflows/delete-review-app.yml
Review apps are not deleted after the PR is closed
App the refactoring to the delete workflow
Compare delete and deploy workflows
> [585] Fix delete review app workflow

- app/views/request_an_account/index.html.erb
- config/locales/en.yml
https://trello.com/c/GlYk1czE/4047-update-content-on-request-an-account-page-to-make-clear-who-can-get-a-register-account
Added in extra heading and steps to make it easier to follow
Updated on who can get an account after support incident where a school got an account to Register when they shouldn't have
> [4047] Content update request account

- db/scripts/sanitise.sql
Now that we will be able to import funding data for providers and lead schools, we need to make sure we are sanitising this data in db/scripts/sanitize.sql so we only pull down an anonymised version.
https://trello.com/c/wqSZRyL9/4177-sanitise-funding-data
- Delete funding_payment_schedules, funding_payment_schedule_rows, funding_payment_schedule_row_amounts
- Delete funding_trainee_summaries, funding_trainee_summary_rows, funding_trainee_summary_row_amounts
- Run against your local database and check that there is no PII
> [4177] Sanitize funding tables

- app/controllers/funding/payment_schedules_controller.rb
- app/services/exports/funding_schedule_data.rb
- app/views/funding/payment_schedules/show.html.erb
- config/locales/en.yml
- spec/features/funding/payment_schedule_spec.rb
- spec/services/exports/funding_schedule_data_spec.rb
- spec/support/page_objects/funding/payment_schedule.rb
We need to build an export function for the payment schedule with a column for each payment type, a row for each month and a total.
Sample output:
- I've split up the data processing into 2 steps. Step 1 extracts all the data and sets it up in an array of hashes (one for each line of the export) using raw pence values for the amounts. Step 2 formats the amounts and serialises all the data to CSV. I think this helps make the code a little clearer but it was done this way mainly to make the data processing easier to test.
> [4185] Export for payment schedule

- config/analytics.yml
Updated analytics.yml file to include hesa_updated_at in the trainees section
Required in BQ to support Funding Extract
Addition of hesa_updated_at field in the trainee section
> Updated analytics.yml file

- config/settings.yml
- config/settings/development.yml
- config/settings/review.yml
- config/settings/test.yml
We're releasing the funding feature.
Turn it on in all environments
> [4167] Switch funding feature flag

- Makefile
- bin/backup-review-database
- bin/upload-review-backup
- docs/disaster-recovery.md
Verify DR documentation and add doc updates and scripts to support testing with review environments
Validation of process and alignment with updates previously done to publish DR process.
> DR document updates and add review testing

- app/jobs/trainees/set_academic_cycles_job.rb
- app/models/trainee.rb
- app/services/trainees/set_academic_cycles.rb
- app/services/trainees/update.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/review.yml
- spec/factories/academic_cycles.rb
- spec/factories/hesa/metadata.rb
- spec/services/trainees/set_academic_cycles_spec.rb
- spec/services/trainees/update_spec.rb
https://trello.com/c/IAIVr8od/4254-l-setacademiccycles-service
Adds a new `SetAcademicCyles` service which sets the start_acaedmic_cycle and end_academic_cycle on trainees. Rules are as follows:
Rules for determining start
* Commencement date
* ITT start date
* Default to current cycle
Rules for determining end
* Award date or withdrawal date
* Course ITT end date
* Course duration and ITT start date
* Default to UG 3 years, part time 2 and otherwise 1.
Then:
* Call new service from new `SetAcademicCyclesJob`, guarded by a new feature flag
* Call new job from our existing `Trainees::Update` service so it's fired whenever a trainee is updated by a user
**Things to check**
* **There are none in prod!** 🎉 
* 56,318 non-draft trainees have no awarded_at, withdraw_date, itt_end_date or …
> [4254] SetAcademicCycles service

- docs/support_playbook.md
Just a small PR to add some information about some of the error codes we commonly see on the DQT jobs. 
* update support playbook with error code info
* read through the info and check if I've missed anything
> [xxx] Add DQT job error codes to support playbook

- docs/adr/0007-store-academic-cycles-on-trainees.md
https://trello.com/c/6hofy0Ds/4249-s-adr-for-academic-cycles
- Add ADR for storing academic cycles on trainees
- Read it
> [4249] Add ADR for storing academic cycles on trainees

- app/jobs/trainees/set_academic_cycles_job.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/review.yml
We don't ever want to _not_ do this now.
Remove the flag and the one place it was used.
🚢 
> [xxx] Remove not-needed set_trainee_academic_cycles feature flag

- db/service_updates.yml
We're about to deploy a new start page design.
Add latest news entry for start page outlining the new filters and tiles.
> [xxx] Add new latest news entry

- README.md
Sorry.
Whenever I open this file my linter gets very sad. Also a couple of the links weren't rendering correctly.
Make me happy.
🚢 
> [xxx] Fix linting issues in the README

- app/components/form_components/autocomplete/sort/stop_words.js
Same pr as #https://github.com/DFE-Digital/dfe-autocomplete/pull/4
Adding here until we swap over to using that library.
> Add 'with' to list of stop words

- Gemfile
- Gemfile.lock
- app/services/degrees/fix_to_match_reference_data.rb
- spec/services/degrees/fix_to_match_reference_data_spec.rb
The dfe-reference-data has had some more synonyms added which will allow us to map more degrees to make them valid.
* Upgrade to f7d9ee41a (v 1.0 isn't quite released yet)
* Change a spec to cover an issue we were having and use single subjects instead of subjects which includes combined that we don't support yet.
> [xxx] Upgrade DfE reference data

- docs/support_playbook.md
I've added a few bits of info that I've picked up on my support week. Thought these might be helpful to document.
I've mainly added info about some of the errors we see coming in on the various DQT jobs.
* Update support_playbook.md
* Have a read, see if you think this makes sense or if anything needs adding/changing
> [xxx] Add error code help to support playbook

- db/service_updates.yml
Context
https://trello.com/c/9iDmdgO3/4296-send-email-to-scitts-about-apply-integration-and-creating-draft-records
Changes proposed in this pull request
Added new content to the news and updates section about Apply integration
> [4296] News and updates about Apply integration

- db/service_updates.yml
Context
https://trello.com/c/9iDmdgO3/4296-send-email-to-scitts-about-apply-integration-and-creating-draft-records
Change 'everyday' to 'every day'
> 4296 News and updates grammar error fix

- .github/workflows/database-backup.yml
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace-variables/production.tfvars.json
Postgres DB for TAD/Funding to use for analysis.
https://trello.com/c/QlBKKSDC/653-register-prod-snapshot
Will create new resources in bat-prod
- register-postgres-analysis
- register-postgres-analysis-key
Updates for new db
- Terraform configuration file updates
- Terraform updates for database-backup workflow
Added to nightly restore from prod db.
deploy-plan
> Create analysis database for TAD/Funding queries

- terraform/workspace-variables/productiondata.tfvars.json
We need workers for the HESA<->Register<->DQT end-to-end testing. 
- Update Terraform config to add 2 workers (same as prod)
> [xxx] Enable workers in productiondata environment

- db/service_updates.yml
https://trello.com/c/zBjn5ljm/4613-create-email-and-news-and-updates-for-release-of-report-to-sign-off-trainees-for-the-new-academic-year
We've released the new report. We want to add news and updates so that users are aware.
To add a new update about the report.
Check the update is there, formatting is correct and it's all jazzy.
> 4613-update-for-new-report

- .github/workflows/build-and-deploy.yml
- .github/workflows/deploy.yml
- .github/workflows/smoke-test.yml
https://trello.com/c/AqsJobyi/4343-remove-register-sandbox
Removing sandbox env as not used
Remove sandbox from the deployment workflows.
Check workflow syntax
Confirm deploy works correctly after merge
> Remove sandbox env from deployment workflows

- .github/workflows/build-and-deploy.yml
- docker-compose.yml
https://trello.com/c/5127oXEX/4657-add-sentrydsn-to-enable-sentry-messaging-in-ci-pipeline-test-build
Add SENTRY_DSN to pipeline rspec tests
Add to docker-compose.yml for web env used in tests
Update build-and-deploy workflow to check and load SENTRY_DSN if exists in APP-SECRETS (QA env)
check workflow run
> Add SENTRY_DSN to rspec build tests

- db/data/20220913090459_fix_trainees_statuses.rb
Data migration is failing in staging the trainees are unlikely to exist.
- Add guard syntax against `nil` values
> [xxx] Fix data migration during a staging run where data might not exist

- docs/uploading_funding_csvs.md
So that it's not just in my notes app :)
Add documentation for importing the monthly funding data into Register from provided csvs.
Check that it makes sense - could you do this next month?
> [4667] Add doc for importing the monthly funding data

- db/service_updates.yml
HESA changed the first commit deadline for trainee data to 17 October from 14 October.
A news and update about this.
Check it says the right date.
Check the link works.
https://trello.com/c/rxTpsUiA/4726-superficially-rename-system-admin-to-support-for-register
> Change to HESA deadline on News and Updates

- Gemfile
- Gemfile.lock
This reverts commit b7cdc0f663143608835c6cb52c169a01dfe09104, reversing changes made to 04b9d99426a40d8338c10c4e4af63b638f5fb63a.
It seems that the upgrade of `dfe-analytics` caused CI errors.
Reverting the commit that upgraded `dfe-analytics`.
> Revert "Merge pull request #2763 from DFE-Digital/dependabot/bundler/dfe-analytics-v1.5.1"

- config/settings/production.yml
> [support] Set hesa_import.sync_collection feature flag to false

- app/services/dqt/find_teacher.rb
The DQT API require three data items to return a teacher.
Add email address to the parameters we send to the `/teachers/find` endpoint so that a teacher is returned.
🚢 
> [xxx] Fix Dqt::FindTrainee service

- config/settings/production.yml
Whilst we fix some issues re duplicated trainees.
> [xxx] Temporarily disable HESA integration

- app/models/trainee.rb
We're adding a uniqueness validation to hesa_id to prevent duplicate trainees being created from TRN data and collection endpoints.
> [xxx] Add uniqueness validation to hesa_id on trainee model

- config/settings/production.yml
> [xxx] Turn back on the HESA integration

- docs/uploading_funding_csvs.md
Enhances the docs outlining funding uploads
> update uploading_funding_cvs docs

- app/helpers/degrees_helper.rb
- app/services/degrees/dfe_reference.rb
- app/views/trainees/degrees/_uk_degree_form.html.erb
- db/data/20221010142433_backfill_unmapped_hesa_degree_grades.rb
- spec/factories/degrees.rb
- spec/forms/degree_form_spec.rb
- spec/services/degrees/dfe_reference_spec.rb
https://trello.com/c/lQMnnzis/4764-investigate-why-so-many-hesa-trainees-have-unmapped-grades-for-degrees
We're getting lots of degrees from the HESA import which don't have a mapped grade. This is because we constructed our own grades list based off the `dfe-reference` gem as Register only allows a limited list of grades to choose from. However, our grades list is preventing the HESA degree importer from finding the other grades not listed in Register.
Therefore, `Degrees::DfeReference` needs to changed so it can allow Register to continue showing a limited number of supported grades but also allow  `Degrees::CreateFromHesa` to find unsupported grades.
This PR also updates the degree form so that it displays supported and unsupported grades if the user is a system admin and the trainee …
> [4764] Investigate why so many hesa trainees have unmapped grades for degrees

- Gemfile
- Gemfile.lock
- app/jobs/dqt/register_for_trn_job.rb
- config/initializers/sidekiq.rb
DQT are happy for us to remove the throttling of DQT requests
> Remove sidekiq throttling

- .github/workflows/build-and-deploy.yml
- .github/workflows/build-nocache.yml
Dependabot is creating too many distracting PRs
Pin to the major version and let the workflow use the latest minor version
Check the workflow run
> Remove GitHub action minor version pinning

- app/jobs/dqt/sync_trainee_state_job.rb
`SyncTraineeStsteJob` is retrying a lot of times in quick succession on a HTTP error
Space out the retries and limit it to 5 retries.
> [XXX] Sync trainee job http error retry throttling

- db/data/20221011140515_add_missing_disabilities_from_tad_check.rb
> only update trainees disabilities if trainees exist

- service_unavailable_page/web/public/internal/index.html
We have a page that we can deploy as a static site in the event that there is a problem with the service. We used this in a recent incident and updated the content and styling.
This content is relevant to the recent incident that we had but we should commit the change as we've updated the format and given the content a bit of thought so it may be useful for inspiration in any future use.
* Update content
* Update formatting
> [xxx] Update maintenance page

- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/workspace-variables/productiondata.tfvars.json
Missed the productiondata environment in https://github.com/DFE-Digital/register-trainee-teachers/pull/2853
> [710] Deploy postgres 13 to productiondata

- db/data/20221025133503_add_other_to_no_country_no_institution_degrees.rb
- db/data/20221025155728_backfill_uk_degrees_with_other_institution.rb
Fixes migrations for #2863 and #2865
> [4879] degrees coming from hesa with no country and no institution

- .github/workflows/copy-database-to-postgres13.yml
Ugrade to postgres 13
Add manual workflow to copy the data
> [710] Workflow to copy database to postgres 13

- .github/workflows/copy-database-to-postgres13.yml
The copy workflow syntax is invalid
Fixed the workflow syntax
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/3329394599
> [710] Fix copy DB workflow

- terraform/workspace-variables/production.tfvars.json
- terraform/workspace-variables/productiondata.tfvars.json
Migration to postgres 13
Point production and productiondata to postgres 13. The data was migrated from postgres 11 in these 2 environments.
> Point production and productiondata to postgres 13

- .github/workflows/database-backup.yml
Migration to postgres 13. The DB backup job must be updated
> Use postgres 13 in database backup job

- app/services/degrees/create_from_csv_row.rb
- docs/uploading_funding_csvs.md
> [xxx] Fix - Bulk upload of degrees where type is missing

- .github/workflows/database-backup.yml
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace-variables/qa.tfvars.json
- terraform/workspace-variables/staging.tfvars.json
Continue postgres 13 migration
- point qa and staging to postgres 13
- deploy a new postgres 13 for analysis
- updated refresh job to refresh analysis pg 13
Update the connection in sqlpad
> [710] Migrate qa, staging, analysis to postgres 13

- .tool-versions
- docs/disaster-recovery.md
- docs/maintenance-mode.md
Some things were missing from the docs during a recent incident.
Add the things... to the docs.
Update the cf version in .tool-versions.
📖
> [xxx] Update docs

- .github/workflows/database-backup.yml
- terraform/modules/paas/main.tf
Finalise migration to postgres 13
Update DB backup workflow to update register analysis on postgres 13
Create service key to access via sqlpad
> [710] Migrate postgres analysis to postgres 13

- terraform/modules/paas/main.tf
Typo, it's still pointing to 11
Use postgres 13 service name
> [710] Fix register analysis DB service key

- .github/workflows/database-backup.yml
Typo in the DB name broke the refresh
Fix analysis DB name
> [710] Fix analysis DB refresh job

- lib/tasks/trainees_hpitt_bulk_submit.rake
This line of code is now executed as part of `Dqt::RegisterForTrn`
> [xxx] Remove redundant line of code

- app/controllers/base_trainee_controller.rb
- spec/controllers/trainees_controller_spec.rb
corrects the restriction introduced to non-sys-admin users in #2892
> [4947] - remove restrictions for trainee download for non-sys-admins

- app/controllers/reports_controller.rb
- spec/controllers/reports_controller_spec.rb
Fix sentry [error](https://sentry.io/organizations/dfe-teacher-services/issues/3727083476/?project=5552118)
Remove the redundant `data` attribute.
`ReportsController` tests added
> [XXX] Fix missing data attribute for data_for_export

- config/locales/pages/privacy_policy/en.yml
https://trello.com/c/rA5bOEyf/4949-update-privacy-policy-page
Adds new section 'The data we collect from all users':
Updates title 'Provider staff data' -> 'Provider staff data and user analytics data
- Go to `/privacy-notice` and check the content.
> [4949] Update privacy policy page

- app/views/guidance/_manually_registering_trainees.md
Per https://github.com/DFE-Digital/register-trainee-teachers-prototype/pull/592 we're updating the guidance for SCITTs. They will no longer need to contact us via email to register PE with EBacc trainees - they just need to add the appropriate subjects.
> Update EBacc guidance

- docs/support_playbook.md
Update the support docs for DQT integration things.
👀 
> [xxx] Update support docs

- app/view_objects/home_view.rb
Sentry [error](https://sentry.io/organizations/dfe-teacher-services/issues/3778550816/?referrer=slack)
```
undefined method `<' for nil:NilClass
```
> Fix nil comparison error

- .github/PULL_REQUEST_TEMPLATE.md
Added a couple more items to the PR checklist to remind us about DQT things and docs!
* Two more items on the checklist
* Read them, do they make sense
> [xxx] Add two items to PR checklist

- config/blazer.yml
This updates the blazer config to make the reports more useful.
I've added these for allocation subjects, routes, states, and academic cycles. They let us have a dropdown on the report that users can use to pick their chosen option. For example, we could have a report that let users filter by allocation subject - and choose the allocation subject at run time.
These will generally use the id from the column to look up more useful data. For example, using the course UUID to return the course name and code. I've done this for course_uuid, course_allocation_subject_id, start_academic_cycle_id, employing_school_id, lead_school_id, trainee_state, trainee_study_mode, training_initiative, training_route
For most of these I've used the existing column name. Where I thought the column name may be …
> Use smart variables in blazer

- config/blazer.yml
Shows the provider's name in Blazer
> Add provider_id as a smart column

- docs/support_playbook.md
Sometimes trainees are incorrectly recommended for award and need to be fixed manually.
Update the support playbook to cover "Incorrectly awarded trainee"
> Update support playbook

- docs/ar_encryption_setup.md
The service uses AR encryption for certain information. Adding documentation to ensure the setup process is detailed.
Add doc with link and command
> Add documentation of how to generate AR keys

- config/blazer.yml
The smart columns I added before Christmas seem to be working well, so this adds several more for:
* course_education_phase
* sex
* disability_disclosure
* withdrawal_reason
> Add more enums to blazer config

- docs/support_playbook.md
Document convenience commands for bulk managing the sidekiq queue.
> [xxx] Add sidkiq queue commands to the support playbook

- app/controllers/system_admin/dead_jobs_controller.rb
- app/services/dead_jobs/base.rb
- app/services/dead_jobs/dqt_recommend_for_award.rb
- app/services/dead_jobs/dqt_update_trainee.rb
- app/services/dead_jobs/dqt_withdraw_trainee.rb
- app/views/system_admin/_tab_nav.html.erb
- app/views/system_admin/dead_jobs/index.html.erb
- app/views/system_admin/dead_jobs/show.html.erb
- config/locales/en.yml
- config/routes/system_admin_routes.rb
- spec/services/dead_jobs/dqt_recommend_for_award_spec.rb
- spec/services/dead_jobs/dqt_update_trainee_spec.rb
- spec/services/dead_jobs/dqt_withdraw_trainee_spec.rb
- spec/support/shared_examples/dead_jobs.rb
Provides system admins a page to download or view a list of trainees that have failed in sidekiq
https://user-images.githubusercontent.com/6339025/211364934-1f566d46-bbef-4228-bb34-4a37c00e4803.mov
> [5111] - dead jobs download and view facility

- app/services/dead_jobs/base.rb
> potential fix of dead jobs QA error

- db/data/20230116124245_fix_awarded_trainees.rb
Data migration failed because `Trainee#from_param` will throw an `ActiveRecord::RecordNotFound` error if the record cannot be found which happens in non-prod environments. 
- Use `find_by` without the bang operation
> [xxx] Fix data migration

- db/data/20230120102649_fix_uwe_trainees.rb
UWE Bristol have lots of data changes. This is mainly withdrawals, that they didn't report via either HESA collection.
See the relevant trello card for the data details
Update trainees to withdrawn state with reasons and dates
> [5163] Amend uwe trainees to withdrawn

- app/components/dqt_data_summary/view.rb
- spec/components/dqt_data_summary/view_preview.rb
Add guard clauses to qts_date and DoB in dqt data summary
🚢 
> [xxx] Add guard clauses to qts_date and DoB in dqt data summary

- db/data/20230214121925_backfill_21_to_22_disabilities_from_apply.rb
https://trello.com/c/2Kdlvra1/5247-m-apply-to-disability-21-22-backfill
- Data migration file
- Uploaded CSV file to production so it can be processed
- Tested it locally using a local CSV file. Works as expected.
> [5247] Data migration to fix disability information for Apply trainees for 2021/2022

- app/controllers/bulk_update/recommendation_uploads_controller.rb
- app/controllers/reports_controller.rb
- app/helpers/navigation_helper.rb
- app/helpers/users_helper.rb
- app/services/find_bulk_recommend_trainees.rb
- app/views/bulk_update/recommendation_uploads/_no_trainees.html.erb
- app/views/bulk_update/recommendation_uploads/_upload_trainees.html.erb
- app/views/bulk_update/recommendation_uploads/check.html.erb
- app/views/bulk_update/recommendation_uploads/new.html.erb
- app/views/bulk_update/recommendation_uploads/show.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- spec/features/bulk_upload/recommending_trainees_spec.rb
- spec/helpers/users_helper_spec.rb
- spec/support/features/page_helpers.rb
- spec/support/page_objects/recommendation_uploads/new.rb
- spec/support/page_objects/recommendation_uploads/show.rb
https://trello.com/c/Q3s2sriX/5250-l-bulk-qts-user-journey
- New controller to handle UI around uploading and editing upload of trainees for recommendation
- Link in header 'Bulk recommend'
- Only shows for accredited provider users
- New `new` page (/upload)
- link to download CSV (this just hooks into previous work, no changes to download)
- shows count of trainees in CSV
- conditional content for when you have no trainees to recommend
- button to upload but no actual functionality
- New `show` page (/upload-summary)
- placeholder counts
- button to check page
- New `check` page (/check-pending-updates)
- placeholder page, this will be for accordions
- Removing export from the reports section
- Actual recommending for award and confirmation
- Upload of CSV
- Accordion UI
- UI counts …
> [5250] Bulk QTS user journey - basic controllers and 'happy-path' views

- Dockerfile
SNYK vulnerability fixes
https://security.snyk.io/vuln/SNYK-ALPINE315-PKGCONF-3244398
Add fixed versions to Dockerfile
Check build SNYK scan
> SNYK vulnerability fix for pkgconf

- app/services/dqt/sync_teacher.rb
Wrong key was used to extract last name
> [xxx] Fix: Dqt::SyncTeacher used "dateOfBirth" attribute for last name

- app/controllers/guidance_controller.rb
- app/views/guidance/bulk_recommend_trainees.md
- app/views/guidance/show.html.erb
- config/routes.rb
https://trello.com/c/y5sBNdW4/5272-s-bulk-qts-guidance-page
- New page using markdown
- Log in
- Visit `/guidance`
- Click on link "Bulk recommend trainees for QTS or EYTS"
> [5272] Bulk QTS: guidance page

- app/views/guidance/show.html.erb
The bulk QTS feature is not ready yet. This work was mistakenly merged into `main` branch. Removing link to guidance page until the work is complete.
> [xxx] Remove "Bulk recommend trainees for QTS or EYTS" link - not ready yet

- config/initializers/sentry.rb
Register is the bad boy of BAT in Sentry
Reduce the sample rate from 100% to 10%
https://develop.sentry.dev/sdk/performance/#tracessamplerate
> [XXX] Reduce Sentry transaction sampling rate

- Gemfile
Some non-production dependencies are required for the pen test env.
> [5232] Add pen env dependencies

- app/models/bulk_update/recommendations_upload.rb
- spec/models/bulk_update/recommendations_upload_spec.rb
We were including rows with missing dates and errors in both the missing dates count and the errors count.
Exclude them from the missing dates count, we show them as errors.
🚢 
> [xxx] Bulk recommend - fix missing dates count

- db/data/20230328103533_change_trainee_statuses_to_awarded.rb
https://trello.com/c/8dNukLzg/5336-dttp-itt-result-change-report
- Data migration to change a number of trainees to awarded and update `itt_end_date`
> [5336] Data migration to change a number of trainees to awarded

- app/controllers/bulk_update/recommendations_errors_controller.rb
- app/helpers/recommendations_upload_helper.rb
- app/views/bulk_update/recommendations_checks/show.html.erb
- app/views/bulk_update/recommendations_errors/show.html.erb
- app/views/bulk_update/recommendations_uploads/_upload_trainees.html.erb
- app/views/bulk_update/recommendations_uploads/edit.html.erb
- app/views/bulk_update/recommendations_uploads/show.html.erb
https://trello.com/b/BBEuhbHM/register-sprint-board
Update all back links in flow.
Check all the back links work as expected.
> [5331] Bulk recommend -update back links

- docs/support_playbook.md
Remove reference to editing audit logs for cleanliness in the support playbook. Audits should remain so we can see the history of a record. It is better to know exactly what happened to a record than the audit log be short.
> [5200] remove reference to editing audit log

- app/views/layouts/application.html.erb
Fix incorrect beta banner text
> Fix beta banner text

- app/controllers/bulk_update/recommendations_checks_controller.rb
- app/views/bulk_update/recommendations_errors/show.html.erb
- app/views/bulk_update/recommendations_uploads/_summary_all_dates.html.erb
- app/views/bulk_update/recommendations_uploads/_summary_bullets.html.erb
- app/views/bulk_update/recommendations_uploads/confirmation.html.erb
- spec/features/bulk_upload/recommending_trainees_spec.rb
A few minor content bugs were found and listed in https://trello.com/c/vpLYCAVu/5366-snagging-ticket-for-bulk-qts
Addresses said content bugs
> [5366] - Snagging ticket for Bulk QTS

- .github/workflows/delete-v2-review-app.yml
Fix an error that causes the delete-aks-review-app workflow to fail
Update the workflow to set the terraform version correctly
create aks review app and confirm it's deleted on merge/close
> Fix delete-aks-review-app workflow

- app/controllers/bulk_update/recommendations_checks_controller.rb
- app/views/bulk_update/recommendations_checks/show.html.erb
https://trello.com/c/Fmuc8635/5415-s-trainees-to-check-on-accordion-page-are-not-in-correct-order
Order by csv_row_number on check who you'll recommend page
Check that the rows are correctly ordered on the "Check who you'll recommend" page
> [5415] Order by csv_row_number on Check who you'll recommend page

- app/controllers/bulk_update/recommendations_uploads_controller.rb
- app/views/bulk_update/recommendations_uploads/edit.html.erb
- spec/features/bulk_upload/recommending_trainees_spec.rb
When trying to `Change who you’ll recommend for QTS or EYTS` using the Bulk Recommend feature, and encounter any validation errors (e.g trying to submit the form without uploading a new CSV file), the system would render the wrong page, while displaying the correct error message. 
The problem comes from the fact that both `:new`( Choose page) and `:edit` (Change page) pages will use the same `BulkUpdate::RecommendationsUploadsController#create` action when the form is submitted. This method was only rendering `:new` if a validation error occurred.
We need to render the `:edit` page if the user is on the `Change who you’ll recommend for QTS or EYTS` page and a validation error occurs. 
Ticket: https://trello.com/c/i6UWpuyK
Fixes the above bug. We now render the correct page. …
> [5417] Bugfix: Bulk import wrong page render

- config/settings.yml
Replace feedback collection form url. Switching from Google form to Microsoft Forms.
Changes the link to the feedback form.
https://trello.com/c/PE6op6CV
Check the Feedback links in both footer and header.
> [5409] Replace feedback collection form url

- docs/aks-cheatsheet.md
Add cheatsheet documentation for AKS
Add doc
check the document
> Add aks cheatsheet

- app/controllers/trainees/outcome_details_controller.rb
https://trello.com/c/i8d2tBSa/5446-allow-for-hesa-trainees-to-be-awarded-individually
- Update `Trainees::OutcomeDetailsController` to use specific authorisation rules instead of the generic one inherited
- Log in as a provider
- Find a HESA traine
- Recommend for award and follow journey
- Everything should work the same as non-HESA trainee
> [5446] Allow for hesa trainees to be awarded individually

- app/models/provider.rb
- spec/models/provider_spec.rb
https://trello.com/c/chKGl3mE/5468-updating-a-providers-code-orphans-their-courses
- Update `Provider` model to track `code` changes and update related courses
> [5468] Fix: updating a provider's code orphans their courses

- app/services/bulk_update/recommendations_uploads/validate_trainee.rb
- config/locales/en.yml
- spec/features/bulk_upload/recommending_trainees_spec.rb
- spec/services/bulk_update/recommendations_uploads/create_recommendations_upload_rows_spec.rb
- spec/services/bulk_update/recommendations_uploads/validate_csv_row_spec.rb
- spec/services/bulk_update/recommendations_uploads/validate_csv_spec.rb
- spec/services/bulk_update/recommendations_uploads/validate_file_spec.rb
- spec/services/bulk_update/recommendations_uploads/validate_trainee_spec.rb
Update error messages for bulk qts uploads. See trello cards for spreadsheet containing changes.
> 5383 Update error messages bulk qts

- .gitignore
- app/components/placement_details/view.html.erb
- app/components/placement_details/view.rb
- app/components/review_draft/apply_draft/view.html.erb
- app/lib/training_route_manager.rb
- app/models/reports/trainee_report.rb
- app/models/reports/trainees_report.rb
- app/models/trainee.rb
- app/views/trainees/show.html.erb
- config/locales/en.yml
- spec/components/placement_details/view_spec.rb
- spec/components/review_draft/apply_draft/view_spec.rb
- spec/lib/training_route_manager_spec.rb
- spec/models/reports/trainee_report_spec.rb
- spec/models/trainee_spec.rb
- spec/views/trainees/show.html.erb_spec.rb
Display placement details when available and made them exportable in the CSV.
The placement data comes in like this from `hesa_students` table:
```ruby
placements: [{"school_urn"=>"103560", "placement_days"=>"84"}]
```
However, in order to display the placement details as in the picture, we need to fetch that info from `schools` table.
Analysing the data, it seems like the max amount of placements for a trainee in the latest hesa collection is 5.
Sometimes hesa students will contain placements with urns that are not real. We call these magic urns. E.g
```ruby
[{"school_urn"=>"900000", "placement_days"=>"40"}]
```
In this case we won't have any school records and instead display a hardcoded label.
Ticket: https://trello.com/c/Du0zqTiH
- Display placement details when available on the …
> [5448] Display placement details when available

- terraform/aks/application.tf
- terraform/aks/variables.tf
Refactor terraform application configuration to use the aks/application_configuration module 
Update module ref before merging
terraform file updates
make review_aks deploy-plan
> refactor app config terraform to use module

- .github/actions/deploy_v2/action.yml
- Gemfile
Enable data seed for aks review apps
Update deploy v2 workflow
Add review_aks to gemfile
deploy aks review app
ran via shell on manual aks review app
> Enable aks review app seed data

- .github/workflows/build-and-deploy.yml
- .github/workflows/deploy-v2.yml
- Gemfile
- terraform/aks/databases.tf
- terraform/aks/variables.tf
- terraform/aks/workspace-variables/production_aks.tfvars.json
- terraform/aks/workspace-variables/productiondata_aks.tfvars.json
- terraform/modules/azure/storage.tf
Add AKS QA env to deployment workflows
- runs parallel to paas deployments, and failure will not cause the workflow to fail
Updates to database settings for aks envs
- Add qa_aks env to build-and-deploy workflow
- Add build-v2 workflow for aks envs
- Update db settings in aks tfvars.json
- Updates to terraform db resources
make deploy-plan
check workflows on merge
> Create aks qa env

- .github/actions/deploy_v2/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/deploy-v2.yml
- .github/workflows/scheduled-aks-db-restore.yml
Add AKS Staging env to deployment workflows
- runs parallel to paas deployments, and failure will not cause the workflow to fail
Add staging_aks to deploy and restore workflows
Check workflows syntax
Check workflows on merge
> Add aks staging env to workflows

- db/data/20230605141019_award_trainees_5484.rb
Award trainees to match TRA data
Award by slug
> [5484] Award trainees

- app/controllers/system_admin/pending_trns_controller.rb
- app/views/system_admin/pending_trns/index.html.erb
https://trello.com/c/C5pk7nVe/5526-improve-content-to-pending-trn-page-to-make-actions-clearer
- Add link to trainee record to pending TRN's list
- Ignore discarded trainees pending TRN 
> [5526] Improve content to pending trn page to make actions clearer

- .github/workflows/scheduled-aks-db-restore.yml
Syntax error in scheduled-aks-db-restore workflow causes productiondata restore to fail
see https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/5274991400/jobs/9540010821
change
environment: matrix.environment
to
environment: ${{ matrix.environment }}
in prod step
already works in non-prod step
check worklow after next run
> fix syntax error in scheduled-aks-db-restore wf

- app/views/guidance/registering_trainees_through_hesa.md
A lot of the content on this page was out of date. In particular it referred to using the ITT provider portal.
The page also had information about recording outcomes. We now have a separate guide for that and it didn't fit well on a page which is supposed to be about registering trainees.
None.
> Update guidance about registering trainees through HESA

- terraform/aks/.terraform.lock.hcl
- terraform/aks/application.tf
- terraform/aks/provider.tf
- terraform/modules/azure/main.tf
Changes have been made to the AKS modules which require an update in the repo terraform.
Update terraform and azurerm versions for aks
change key_vault_secret_name to secret_yaml_key
make qa_aks deploy-plan
deploy aks review app
check secrets as expected
> fix for aks module changes

- docs/govuk_paas.md
Tiny change because a couple of us forgot this command and we needed it to log into the prod console.
List the `set-space-role` command.
> Include `set-space-role` command in PaaS cheatsheet

- .github/workflows/build-and-deploy.yml
https://trello.com/c/vHdVbk4w/5591-auto-merge-dependabot
Add a build step to automatically merge dependabot PRs for minor version updates where the build passes and they're not likely to introduce breaking design changes.
Looks about right?!
> Build step to automagically merge dependabot PRs

- app/components/notice_banner/view.html.erb
- app/view_objects/missing_data_banner_view.rb
- config/locales/en.yml
- db/schema.rb
- spec/view_objects/missing_data_banner_view_spec.rb
Content from @johndoates 
Changes:
* Update the banner heading to refer to QTS or EYTS award rather than 'outcome'
* Use a regular bulletted list rather than bold links
* Remove the text 'is missing' from each link
Note: ideally each missing data link would start lowercase. I was unsure how to do this but perhaps a dev could help.
> Update content in missing data banner

- config/settings/production_aks.yml
Disable hesa_trn_requests for the prod aks env 
Will be re-enabled during the migration
update setting in production_aks.yml 
check yml
> Disable hesa trn requests from prod aks env

- .github/workflows/delete-review-app.yml
Dependabot review apps are not being deleted
Update delete review app workflow to delete dependabot review apps
check wf syntax
check dependabot review apps are being deleted after merge
> Fix delete review app to delete dependabot rv apps

- app/lib/dqt/params/trn_request.rb
https://dfe-teacher-services.sentry.io/issues/4293623006/?alert_rule_id=4544549&alert_type=issue&project=5552118&referrer=slack
off the back of a few hundred dead jobs. relevant slack thread: https://ukgovernmentdfe.slack.com/archives/C04HLTPG1RR/p1687857071795219
save navigation for TRN params builder
> Safe nav operator for trn_request params builder

- terraform/aks/statuscake.tf
- terraform/aks/workspace-variables/production_aks.tfvars.json
- terraform/aks/workspace-variables/staging_aks.tfvars.json
Fix statuscake for aks staging and prod
change tfvars
use terrafile for aks statuscake
make staging_aks deploy-plan
make production_aks deploy-plan
> Fix statuscake for aks staging and prod

- config/settings/staging.yml
Revert sign in method to DFE sign in for staging
To support https://github.com/DFE-Digital/register-trainee-teachers/pull/3386
> [xxx] Revert sign-in-method for staging

- db/scripts/sanitise.sql
Staging will be used for integration testing once again, particularly for the AKS migration.
Adds additional `DELETE`'s for new tables containing PII
* check we won't need the data that is being deleted for integration testing
* check if there is any other attributes or tables that should be changed or deleted
> [5667] - updates sanitise sql script

- .github/workflows/database-backup.yml
- .github/workflows/restore-staging-sanitised.yml
- config/settings/staging_aks.yml
Add sanitised data db restore for the staging (aks) env
- Add staging restore step to scheduled backup & restore workflow
- Add staging db restore workflow
- Update staging_aks config/settings
Check workflow
> Add sanitised data db restore for staging env

- config/settings/staging_aks.yml
Disable analytics for staging aks
Update config/settings
check syntax
> Disable analytics for staging aks

- db/data/20230711081023_fix_trn_with_correct_one_5678.rb
Incorrect Trn
Fixed trn with the correct one
It's against prod.
> [5678] Fixed trn with the correct one

- db/data/20230711151049_fix_incorrectly_awarded_trainee_5676.rb
Incorrectly recommended for QTS
Put the trainee back to `in training`
:shipit:
> [5676] Fixed incorrectly recommended for QTS

- app/models/reports/trainee_report.rb
- spec/models/reports/trainee_report_spec.rb
missing i18n in trainee report after withdrawal journey update
> [xxxx] - fix i18n bug for trainee report

- .tool-versions
Housekeeping
Bumping tool versions for asdf
:shipit:
> [xxxx] Amended tool version numbers

- app/controllers/funding/base_funding_controller.rb
- app/controllers/system_admin/users_controller.rb
- app/models/bulk_update/recommendations_upload.rb
https://trello.com/c/9KVtSd1G/5668-n1-query-systemadmindeadjobscontrollershow
Been trying to track down the N+1 reported by Sentry in the ticket above but hard to reproduce since it's in the Sidekiq dead set (which isn't backup/sanitised). Ended up finding/fixing a few others in the process.
> [5668] Nip a few N+1s

- .github/workflows/backup-and-restore.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/database-backup.yml
- .github/workflows/deploy.yml
- .github/workflows/scheduled-aks-db-restore.yml
Migrate productiondata environment to AKS
Update workflows
Check workflows
> Migrate productiondata env to aks

- db/data/20230713151823_fix_incorrectly_awarded_trainee_5686.rb
Incorrectly awarded trainee
Fixed incorrectly awarded trainee
:shipit:
> [5686] Fixed incorrectly awarded trainee

- .github/workflows/next-academic-year-tests.yml
- spec/spec_helper.rb
Scheduled CI tests for next academic
The schedule task to be run at 6 am
:shipit:
nah
> [5683] Added scheduled CI tests for next academic year

- .github/workflows/database-backup.yml
Secret is specified incorrectly in backup workflow for the aks restore steps
fix the secret name
check it matches the github secret
> Fix secret in backup workflow

- .github/workflows/next-academic-year-tests.yml
Next academic year tests
Fixed incorrectly set environment variables for build
:shipit:
> [5683] Fixed incorrectly set environment variables for build

- app/lib/dttp/code_sets/degree_subjects.rb
- app/lib/dttp/code_sets/institutions.rb
- app/lib/dttp/code_sets/jacs_subjects.rb
- app/lib/hesa/code_sets/countries.rb
- config/initializers/subjects/degree_subjects.rb
These are covered in `.rubocop.yml`.
> Remove explicit disable `CollectionLiteralLength` rules

- .tool-versions
asdf az tooling
Amended az plugin for asdf
Added kubectl plugin for asdf
:shipit:
> [xxxx] Amended az plugin for asdf

- terraform/aks/variables.tf
Fix blazer_database_url app secret in aks variables
change variable
manually deployed to productiondata so can check if it works
> fix blazer database url in tf vars

- config/webpacker.yml
Webpacker
Fixed noisy console messages
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/5576298381/jobs/10187504930?pr=3431#step:4:1278
```
RAILS_ENV=review_aks environment is not defined in config/webpacker.yml, falling back to production environment
```
> [xxxx] Fixed noisy console messages from webpacker

- .github/workflows/database-backup.yml
fix k8 config in database backup workflow
- prod cluster in s189p01 not s189t01
Also don't delete the backup, then try and restore using it
Update workflow
Check workflow, which has been successfully rerun using this branch
> fix k8 config in database backup workflow

- .github/workflows/build-and-deploy.yml
- .rspec-parallel
- Gemfile
- Gemfile.lock
- README.md
- app/components/form_components/autocomplete/script.js
- app/components/form_components/autocomplete/sort/index.js
- app/components/form_components/schools_autocomplete/script.js
- app/components/form_components/tracker.js
- app/components/form_components/users_autocomplete/script.js
- app/webpacker/scripts/global/disable-browser-autofill.js
- config/database.yml
- spec/factories/nationalities.rb
- spec/features/form_sections/teacher_training_data/edit_course_details_spec.rb
- spec/features/form_sections/teacher_training_data/employing_school_search_spec.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
- spec/support/capybara.rb
- spec/support/database_cleaner.rb
https://trello.com/c/fNIyGyT5/5688-set-up-parallelisation-of-ci-tests
Took a couple of punches from the CI but have managed to get the build down to around 8-10 mins-ish (from 30ish). 
- Add parallel testing gem and configure the Github workflows to use it
- Split out lint into its own step to also be parallelised 
- Add database cleaner gem to properly clean out tests (we seem to have issues with stale data not being cleared out)
It has been thoroughly reviewed by the CI believe me.
> [1316] Break up and parallelise build/test step

- .github/workflows/build-and-deploy.yml
So both steps can start at the same time in parallel to speed things up a little more.
> [xxxx ] Remove dependant on lint for test step

- config/settings.yml
We've deployed to AKS
Turn off the maintenance banner
> Turn off maintenance banner

- .github/actions/smoke-test_v2/action.yml
Point smoke test to correct environment after aks migration
Update smoke test v2 to use app-env
check smoke test
> Fix smoke test to correct env after migration

- .github/workflows/database-backup.yml
Database backup failed as ran out of space on the github runner.
Move some of the steps around, and delete backup files when no longer needed.
Add slack message for failed workflow.
Check workflow
> Fix database backup disk space issue

- app/services/dqt/recommend_for_award.rb
- app/services/dqt/trainee_update.rb
- app/services/dqt/withdraw_trainee.rb
- spec/services/dqt/recommend_for_award_spec.rb
- spec/services/dqt/update_spec.rb
- spec/services/dqt/withdraw_trainee_spec.rb
Reverts DFE-Digital/register-trainee-teachers#3454
> Revert "[5709] - update itt-outcome DQT endpoints with trainee slug"

- docs/support_playbook.md
Old `cf`
Use `kubectl`
It works
> [5752] Amended `cf` to be `kubectl`

- .github/workflows/database-backup.yml
Add sqlpad grants after analysis db has been restored
Add grant statements to workflow
check workflow syntax
> Add sqlpad grants after analysis refresh

- app/views/guidance/_course_details.html.erb
- app/views/guidance/_database_only.html.erb
- app/views/guidance/_funding.html.erb
- app/views/guidance/_personal_details.html.erb
- app/views/guidance/_schools.html.erb
- app/views/guidance/_trainee_progress.html.erb
- app/views/guidance/hesa_register_data_mapping.html.erb
With the new academic year starting some of the HESA guidance requires updating.
Various minor content updates to the HESA mapping guidance page
N/A
> Update HESA mapping guidance page

- config/settings.yml
- config/settings/productiondata.yml
Settings updated to allow for Apply Application imports
This was tested in productiondata in #3438
> [5816] - update settings for Apply Application import

- db/service_updates.yml
Service update message for Apply applications
adds Service update entry
This has been copied from [this doc](https://educationgovuk.sharepoint.com.mcas.ms/:w:/r/sites/TeacherServices/_layouts/15/doc2.aspx?sourcedoc=%7B3BE6080D-2E1D-4480-BEC5-944FCD104C8E%7D&file=News%20and%20update%20article%20-%204%20August%202023.docx&action=default&mobileredirect=true&cid=7e3659f4-cc5e-4e7a-868c-b7552d7b420a).
> [5816] - Service update for Apply Applications

- terraform/aks/workspace-variables/production_aks_Terrafile
Production env terrafile should point to the stable release for terraform-modules
Updated terrafile version
make production_aks deploy-plan
> Update production terrafile version to stable

- app/components/provider_card/view.html.erb
- app/components/record_details/view.rb
- app/controllers/system_admin/providers/confirm_deletes_controller.rb
- app/controllers/system_admin/providers_controller.rb
- app/models/provider.rb
- app/views/system_admin/providers/confirm_deletes/show.html.erb
- app/views/system_admin/providers/edit.html.erb
- app/views/system_admin/providers/show.html.erb
- config/analytics.yml
- config/locales/en.yml
- config/routes/system_admin_routes.rb
- db/migrate/20230731090931_add_discarded_at_to_provider.rb
- db/schema.rb
- spec/features/system_admin/providers/editing_a_provider_spec.rb
- spec/support/page_objects/providers/new.rb
Soft deletion of providers
Allow soft deletion of providers
> For the #twd_data_insights team
A `discarded_at` column is added to the `provider` table
Go and delete the provider, it associated users will also be removed
> [5763] Allow soft deletion of providers

- app/services/trainees/create_from_hesa.rb
Linter issue
Fixed linter issue
:shipit: 
> [xxxx] Fixed linter issues

- spec/factories/degrees.rb
- spec/features/form_sections/teacher_training_data/apply_applications_spec.rb
- spec/features/system_admin/dead_jobs/viewing_dead_jobs_spec.rb
- spec/features/trainee_actions/change_course_spec.rb
- spec/features/trainee_actions/edit_trainee_training_route_spec.rb
- spec/models/degree_spec.rb
`next academic year tests`
Skipping tests that cannot logically happen 
Time can only be controlled by time lord
:shipit: 
> [5844] Fix failing `next academic year tests`

- .github/workflows/database-backup.yml
Disable backups to staging while HESA testing
> [5717] - disable database backups to staging whilst HESA testing

- config/locales/pages/privacy_policy/en.yml
Some minor changes to the privacy policy are needed to reflect recent changes to the service.
- Remove references to address collection
- Remove section about hosting
- Change updated at date
- Does this match the document attached to the ticket?
> [5810] August 2023 privacy policy updates

- .github/workflows/build-and-deploy.yml
- .github/workflows/database-backup.yml
While HESA testing we:
* stopped backups to the Staging DB
* stopped deploys to staging on merge to main
Restores both of these
> [5717] - restore Staging workflow after HESA testing

- app/views/guidance/dates_and_deadlines.html.erb
HESA collection date has changed from 1st September to 7th September
Change the date on the guidance page
N/A
> HESA collection date changed from 1 to 7

- app/components/export_with_count_button/view.html.erb
- app/views/reports/_census_period.html.erb
> Fix stray code

- app/views/guidance/census_sign_off.md
Digital email
Fixed digital email
:shipit: 
Go to https://register-pr-3549.test.teacherservices.cloud/guidance/census-sign-off
> [xxxx] Fixed digital email

- app/views/reports/_outside_period.html.erb
Stray quote
Remove stray quote
:shipit: 
Go to https://register-pr-3547.test.teacherservices.cloud/reports
> [xxxx] Remove stray quote

- config/settings.yml
MsForm link
Added MsForm link
Go to https://register-pr-3548.test.teacherservices.cloud/reports/itt-new-starter-data-sign-off
> [5973] Added MsForm link

- .github/workflows/build-and-deploy.yml
- .github/workflows/next-academic-year-tests.yml
- Gemfile
- Gemfile.lock
- docs/testing.md
- spec/spec_helper.rb
Deployments
There are a number of items that causes the github action to fail.
These are now set to be retried if it does.
For `Build and Deploy`
- Run Snyk to check Docker image for vulnerabilities
- All tests
For `Next academic year tests`
- Run Rspec tests for next academic year
- Run Rspec tests
The beloved `rspec-retry` was retired.
> [5927] Fix deployments

- .github/workflows/delete-v2-review-app.yml
Dependabot PR's are not deleting the review app on close
Update delete-review-app workflow to include closed PR's with the 'dependencies' label
Check wf
> Update delete review app wf to del dependabot prs

- app/views/guidance/performance_profiles_outside.html.erb
A missing link has been identified to the documentation on performance profiles methodology.
Fix missing link
N/A
> Fix missing link to performance profiles methodology

- app/views/guidance/_trainee_progress.html.erb
- db/service_updates.yml
A couple of minor content changes requested
Fixes to latest post title and guidance table
N/A 
> Hotfix minor content changes

- docs/support_playbook.md
Playbook
Amended so we add audit_comment as well
:ship: 
> [6048] Playbook default to add `audit_comment`

- app/services/hesa/sync_students.rb
- spec/services/hesa/sync_students_spec.rb
We made some changes to the HESA integration as part of this PR https://github.com/DFE-Digital/register-trainee-teachers/pull/3465. This just handles some leftovers.
> [xxx] Fix HESA attribute name change

- .github/workflows/build-nocache.yml
build-no-cache workflow fails due to invalid tf_vars_file setting
update from review to review_aks
check build-no-cache workflow
> fix build-no-cache tf_vars_file setting

- .github/workflows/build-and-deploy.yml
`SHA`
There was mismatch of `sha`...
The output `image-tag` did not match `IMAGE_TAG`
https://github.com/DFE-Digital/register-trainee-teachers/blob/7c5bdccbe0346ed3bd0dc83537dcd532c6bb0641/.github/workflows/build-and-deploy.yml#L29
https://github.com/DFE-Digital/register-trainee-teachers/blob/7c5bdccbe0346ed3bd0dc83537dcd532c6bb0641/.github/workflows/build-and-deploy.yml#L213
Take the sha, and compare it back manuelly
https://register-pr-3624.test.teacherservices.cloud/sha
`13085caecec176c01dca0ac9554cda849f513131`
https://github.com/DFE-Digital/register-trainee-teachers/tree/13085caecec176c01dca0ac9554cda849f513131
Which this PR with this sha `7c5bdccbe0346ed3bd0dc83537dcd532c6bb0641`
https://github.com/DFE-Digital/register-trainee-teachers/pull/3624 …
> [xxxx] Fixed build mismatch

- config/initializers/dfe_analytics.rb
The entity table check job will run every night and sends data to verify that the latest version of an entity table in BigQuery matches the database.
Enable the nightly checksunm in thne DfE Analytics config file.
Ensure the config in DfE Analytics is set correctly.
> [6159] Enable nightly checksum in DfE Analyics

- config/initializers/dfe_analytics.rb
Reverts DFE-Digital/register-trainee-teachers#3634
> Revert "[6159] Enable nightly checksum in DfE Analyics"

- config/settings.yml
- config/settings/production.yml
https://trello.com/c/kjBZ86H0/6135-create-new-feedback-form-using-ms-forms
Change one URL to another one
Click a link?
> Update feedback link

- .gitignore
gz files
Added to git ignore 
The backup are now in archive format
> [xxxx] Added *.sql.gz to be ignored

- app/view_objects/home_view.rb
https://ukgovernmentdfe.slack.com/archives/C0616S7QJ01
1 week expiry for home view counts
> [xxxx] - cache homeview counts for a week (temporarily)

- app/models/trainee.rb
Which, god willing, won't bring the database to its knees.
The existing `Trainee.incomplete` scope produced some very odd SQL with a `NOT IN (inner query)` that was making Postgres really quite unhappy.
A more straightforward, if less elegant, scope.
> A more efficient implementation of the incomplete scope

- config/database.yml
- terraform/aks/workspace-variables/dv_review_aks.tfvars.json
- terraform/aks/workspace-variables/production_aks.tfvars.json
- terraform/aks/workspace-variables/productiondata_aks.tfvars.json
- terraform/aks/workspace-variables/qa_aks.tfvars.json
- terraform/aks/workspace-variables/staging_aks.tfvars.json
Generally a [good thing to do](https://www.citusdata.com/blog/2017/04/28/postgres-tips-for-rails/) so long/troublesome queries can be terminated without bottling up the db.
> [xxxx] Set statement timeouts on db

- .github/workflows/build-and-deploy.yml
- docs/support_playbook.md
Playbook
Added a bit for turning off `dfe-analytics`.
Removed it from auto merge for `dependabot`.
It caused high level system load to the extent that the system and related systems high load as well as the system becoming non-responsive
> [xxxx] Playbook for disabling analytics

- terraform/aks/workspace-variables/dv_review_aks.tfvars.json
- terraform/aks/workspace-variables/production_aks.tfvars.json
- terraform/aks/workspace-variables/productiondata_aks.tfvars.json
- terraform/aks/workspace-variables/qa_aks.tfvars.json
- terraform/aks/workspace-variables/staging_aks.tfvars.json
Fixes the failing deploy in `main`
> [xxxx] Fix bad variable name complaint

- terraform/aks/workspace-variables/production_aks.tfvars.json
Prod workers restarting
Increase prod worker memory from 1G to 2G 
make production_aks deploy-plan CONFIRM_PRODUCTION=y
> Increase prod worker memory to 2G

- terraform/aks/workspace-variables/production_aks.tfvars.json
prod worker running out of memory with 2G available
Increase to 3G
make production_aks deploy-plan CONFIRM_PRODUCTION=y
> Increase prod worker memory to 3G

- terraform/aks/workspace-variables/staging_aks.tfvars.json
Increase staging app and worker memory for testing hesa import
Update worker and app memory in staging tfvars
make staging_aks deploy-plan
> Increase staging app and worker memory

- app/components/placement_details/view.html.erb
- app/components/placement_details/view.rb
- app/components/review_draft/apply_draft/view.html.erb
- app/components/review_draft/draft/view.html.erb
- app/components/sections/view.rb
- app/forms/submissions/base_validator.rb
- app/forms/submissions/trn_validator.rb
- app/models/trainee.rb
- app/views/trainees/check_details/_draft_trainee_check_details.html.erb
- app/views/trainees/show.html.erb
- config/locales/en.yml
- spec/components/placement_details/view_preview.rb
- spec/components/placement_details/view_spec.rb
- spec/components/sections/view_preview.rb
- spec/factories/placements.rb
- spec/factories/trainees.rb
- spec/forms/submissions/missing_data_validator_spec.rb
- spec/forms/submissions/trn_validator_spec.rb
- spec/models/trainee_spec.rb
Check trainee record page placement details section
Show the differentiating placement detail views
Create an applicable draft trainee
And you should be able to manipulate by adding or removing the placements or simply transverse the service to give one of the following views.
http://localhost:5000/view_components/sections/view/continue_sections_placements
http://localhost:5000/view_components/sections/view/continue_sections_placements_validated
http://localhost:5000/view_components/sections/view/start_sections_placements
http://localhost:5000/view_components/sections/view/start_sections_placements_validated
http://localhost:5000/view_components/placement_details/view
default
one placements
two placements
five placements
NOPE …
> [6251] Check trainee record page placement details section

- app/controllers/trainees/placements/confirm_details_controller.rb
- app/forms/placements_form.rb
- app/forms/submissions/base_validator.rb
- app/forms/submissions/missing_data_validator.rb
- app/forms/submissions/trn_validator.rb
- config/locales/en.yml
- config/routes.rb
- spec/forms/placements_form_spec.rb
- spec/forms/submissions/missing_data_validator_spec.rb
Placements validator
Add/amend the validators so that they are executed or by pass in the right order
it works
> [6360] Placements validator

- app/components/review_draft/draft/view.html.erb
- app/forms/submissions/base_validator.rb
- app/forms/submissions/trn_validator.rb
- app/lib/training_route_manager.rb
- app/views/trainees/check_details/_draft_trainee_check_details.html.erb
- spec/lib/training_route_manager_spec.rb
Usage of placement_details flag
Centralising the usage of placement_details flag
:ship: 
> [6365] Amended so Feature flag `placement_details` is part of trainee `requires_placements?`

- config/settings.yml
old placement flag
Removed old placement flag
:shipit:
> [6367] Removed old placement flag

- config/settings.yml
- config/settings/productiondata.yml
Feature flag for `trainee_placement` for `productiondata`
Added feature flag for `trainee_placement` for `productiondata`
When we are ready for placement
> [6368] Added feature flag for `trainee_placement` for `productiondata`

- app/components/placements/view.rb
- app/controllers/trainees/placements_controller.rb
- app/forms/placement_form.rb
- app/forms/placements_form.rb
- app/views/trainees/placements/_form.html.erb
- app/views/trainees/placements/edit.html.erb
- app/views/trainees/placements/new.html.erb
- config/routes.rb
- db/data/20231116145800_sluggify_existing_placements.rb
- spec/features/form_sections/teacher_training_data/placements/editing_trainee_placements_spec.rb
- spec/forms/placement_form_spec.rb
- spec/forms/placements_form_spec.rb
Existing placement
Added update an existing placement functionality
It works
> [6232] Update an existing placement

- .tool-versions
nodejs
Amended nodejs to match package.json
:ship: 
> [xxxx] Amended nodejs to match package.json

- spec/forms/placement_form_spec.rb
Unused code
Removed it
The joy of less is more
> [xxxx] Removed unused negated matcher

- app/forms/placement_form.rb
- spec/forms/placement_form_spec.rb
Failed urn validation
Amended so failed urn validation the details are open
> [6445] Amended so failed urn validation the details are open

- data/lead_schools_publish.csv
- data/schools_gias.csv
- docs/setup-development.md
Update new schools list
Amened csv to be more updated
Updated all the csv as well as the commands to be be up to date
Just need to follow https://github.com/DFE-Digital/register-trainee-teachers/blob/main/docs/setup-development.md#schools-data on production
> [6446] Update new schools list

- app/components/placement_details/view.rb
Placement ordering
Removed reversed placement ordering
Add two placements, they should be the same ordering on the confirm placement as well as the trainee record
https://register-pr-3798.test.teacherservices.cloud/trainees/KFkxdSw75AaXK6S3vXDLNRKq/placements/confirm
https://register-pr-3798.test.teacherservices.cloud/trainees/KFkxdSw75AaXK6S3vXDLNRKq/check-details
> [6464] Removed reversed placement ordering

- app/components/placements/view.html.erb
- app/views/trainees/placements/details/edit.html.erb
- spec/components/placements/view_spec.rb
Placement wordings
Amended wordings
Added period full stop
It is now legible.
https://register-pr-3800.test.teacherservices.cloud/trainees/PHYXYSsxbypBs1AJd2oqR2TJ/placements/confirm
https://register-pr-3800.test.teacherservices.cloud/trainees/PHYXYSsxbypBs1AJd2oqR2TJ/placements/confirm
> [6465] Amended wordings

- config/initializers/dfe_analytics.rb
- config/sidekiq_cron_schedule.yml
Please see [Trello](https://trello.com/c/noYCE9mi/6486-schedule-enable-entity-table-checks) for more details.
Entity table checks are sent from the App to BigQuery to perform nightly QA checks on the BigQuery tables. Any alerts generated by BigQuery are monitored and picked up by DI Team support and investigated.
- Enables entity tables checks in Register
- Create a Sidekiq CRON job to schedule entity tables checks every night at 00:30
- Ensure that at least version 11.1.3 of DfE Analytics is used
- Ensure proposed change implemented
Evidence for entity table checks in Staging:
DB Performance on staging. Note the time marked 12:27 AM prior to the job staring at 12:30 AM:
The number of tables in [analytics.pii](https://github.com/DFE-Digital/register-trainee-teachers/blob/main/config/analyt …
> Schedule and enable entity table checks

- terraform/aks/databases.tf
Remove alert window size from redis
> Remove alert window size from redis

- app/models/reports/bulk_placement_report.rb
- app/views/bulk_update/bulk_updates/index.html.erb
- app/views/bulk_update/placements/new.html.erb
- spec/services/exports/bulk_placement_export_spec.rb
content updates from https://trello.com/c/J8Zg6qnF/6512-bulk-bug-party-1-3-5-and-7-implement-content-changes
* updates wording in new and index
* updates CSV export
> [6512] - content updates

- app/views/guidance/performance_profiles_outside.html.erb
User facing texts
Amended user facing texts
It reads fine :baby_chick: 
https://register-pr-3844.test.teacherservices.cloud/guidance/performance-profiles
> [6335] Amended user facing texts

- config/settings/production.yml
Placements are now on
Amended so the placements are now on
:shipit:
> [6540] Amended so the placements are now on for production

- config/environments/test.rb
DEPRECATION WARNING: Setting action_dispatch.show_exceptions to false is deprecated. Set to :none instead
Fixed deprecation warning
:shipit:
> [xxxx] Fixed deprecation warning

- app/controllers/guidance_controller.rb
- app/views/guidance/bulk_upload_placement_data.html.erb
- app/views/guidance/check_data.md
- app/views/guidance/manage_placements.html.erb
- app/views/guidance/performance_profiles.html.erb
- app/views/guidance/show.html.erb
- config/routes.rb
- config/settings.yml
https://trello.com/c/zqiAOisd/6533-register-guidance-about-placements-2-updates-and-2-new-pages
- Updates to existing guidance pages to include information about placements
- Adds two new guidance pages around placements
View the "how to use service" link and double check the new pages. The links are also below:
https://register-pr-3849.test.teacherservices.cloud/
> [6533] Update guidance pages to include placement content

- app/models/reports/trainee_report.rb
https://ukgovernmentdfe.slack.com/archives/C023EC79M6Y/p1702648587087069
nil school issue
Fixed nil school issue
:shipit:
> [xxxx] Fixed nil school issue

- app/views/guidance/dates_and_deadlines.html.erb
Missing prefix `with_`
Fixed missing prefix `with_`
> [xxxx] Fixed missing prefix `with_`

- app/javascript/scripts/components/form_components/providers_autocomplete.js
- app/javascript/scripts/components/form_components/schools_autocomplete.js
Autocomplete undefined
Fixed autocomplete undefined issue
> [6463] Fixed autocomplete undefined issue

- .github/workflows/database-backup.yml
Restore DB workflow was failing -  credential was set to AZURE_CREDENTIALS_AKS_TEST
Set Staging DB restore workflow's to AZURE_CREDENTIALS_STAGING_AKS
> Update azure credentials for staging

- config/settings.yml
- config/settings/development.yml
- config/settings/productiondata.yml
- config/settings/qa.yml
- config/settings/review.yml
- config/settings/staging.yml
- config/settings/test.yml
Claiming `upload_funding` feature flag
Added defaults for the `upload_funding` feature flag
Nothing to see other is it named right and that it is off for production
> [6579] Added upload funding feature flag

- spec/features/form_sections/teacher_training_data/placements/adding_trainee_placements_spec.rb
- spec/features/form_sections/teacher_training_data/placements/deleting_draft_trainee_placements_spec.rb
- spec/features/form_sections/teacher_training_data/placements/deleting_trainee_placements_spec.rb
unused code
Removed unused code
Nothing breaks
> [xxxx] Removed unused code

- .rubocop.yml
- app/controllers/system_admin/upload_fundings_controller.rb
- app/helpers/users_helper.rb
- app/views/system_admin/_tab_nav.html.erb
- app/views/system_admin/upload_fundings/index.html.erb
- config/locales/en.yml
- config/routes/system_admin_routes.rb
- spec/features/system_admin/upload_funding/viewing_upload_funding_spec.rb
- spec/helpers/users_helper_spec.rb
- spec/support/features/common_steps.rb
Upload funding index page
Added menu option
Added upload funding index page
It is a placeholder until the static content can be replaced
> [6579] Added static upload funding index page

- app/views/trainees/_search_results.html.erb
Skip to results
Added skip to results for the filter
Use the keyboard tab key, as it is hidden from view.
> [6621] Added skip to results for the filter

- .github/actions/smoke-test/action.yml
- spec/smoke/login_spec.rb
- spec/spec_helper_smoke.rb
* #3955 and #3954 both did not pass the smoke test step
* this should fix things by passing in necessary environment variables via github secrets.
🤞
> 6528 smoke test (take three)

- .github/actions/smoke-test/action.yml
- .github/workflows/smoke-test.yml
- spec/smoke/login_spec.rb
- spec/spec_helper_smoke.rb
> [6528] smoke test take four

- .github/workflows/smoke-test.yml
- spec/smoke/login_spec.rb
- spec/spec_helper_smoke.rb
This simply ups the wait time as well as adds dotenv/load for local testing. follows on from these attempts:
#3959 
#3958 
#3957 
#3955 
#3954
> [6528] - more smoke test wrangling

- .github/workflows/smoke-test.yml
- Gemfile
- Gemfile.lock
- spec/smoke/login_spec.rb
- spec/spec_helper_smoke.rb
#3963 is working fairly well, but the test is quite flakey despite extending wait time
* uses `find_button("the buton").click` instead of `click_on "the button"`
* adds retry
* tested locally and via smoke test workflow and get green consistently
> [6528] smoke test with retry

- spec/smoke/login_spec.rb
> [xxxx] - skip smoke test

- .github/actions/deploy/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/deploy.yml
- spec/smoke/login_spec.rb
smoke tests are still failing on merge. This should provide the correct secrets/ENV vars to the deploy job
> [6528] - add secrets to build-and-deploy

- .github/actions/deploy/action.yml
- .github/workflows/database-backup.yml
- .github/workflows/delete-review-app.yml
- .github/workflows/deploy.yml
- .tool-versions
- Makefile
- docs/aks-cheatsheet.md
- terraform/aks/provider.tf
> [925] Enable Azure RBAC authentication on AKS #2

- Makefile
Failure: https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/7710732722/job/21015132685
Enable by default in CI
Code review (same as [template](https://github.com/DFE-Digital/teacher-services-cloud/blob/main/templates/new_service/Makefile))
> [925] Fix production deployment with CONFIRM_PRODUCTION

- app/views/pages/privacy_notice.md
Add some text, as per [Trello](https://trello.com/c/bepJ9BNB/6699-implement-jisc-suggestions-to-privacy-notice)
Check the review app
> Privacy notice text changes to include Jisc

- app/views/bulk_update/placements/new.html.erb
Update text as per [Trello](https://trello.com/c/Sj5iDpRt/6639-update-the-bulk-add-placements-page-to-say-that-up-to-5-placements-can-be-added).
And a bit of whitespace cleanup
Check the review app
> Update bulk placements page to say that up to 5 placements can be added

- config/settings.yml
- config/settings/development.yml
- config/settings/productiondata.yml
- config/settings/qa.yml
- config/settings/review.yml
- config/settings/staging.yml
- config/settings/test.yml
Enables the funding uploads feature in prod. Important to make sure correct files are uploaded to the correct pages/forms. This doc helps https://github.com/DFE-Digital/register-trainee-teachers/blob/bb1fb8f9da608768acb67edcfa90241cc9a49743/docs/uploading_funding_csvs.md?plain=1#L22
> [xxx] Enable funding uploads

- app/lib/funding/parsers/base.rb
- app/services/funding_data_importer.rb
- spec/lib/funding/parsers/lead_school_payment_schedules_spec.rb
- spec/lib/funding/parsers/lead_school_trainee_summaries_spec.rb
- spec/lib/funding/parsers/provider_payment_schedules_spec.rb
- spec/lib/funding/parsers/provider_trainee_summaries_spec.rb
> [xxx] - Fix args in parser so rake task can run

- .github/workflows/database-backup.yml
Intermittently database backup failures
Added concurrency for database backup at at time for one pipeline to run.
Keep an eye on DB backup pipeline failures(if atall)
> Add concurrency to DB backup workflow

- config/locales/en.yml
`itt_started_but_trainee_did_not_start` message
Amended `itt_started_but_trainee_did_not_start` message
:shipit:
> [6771] Amended `itt_started_but_trainee_did_not_start` message

- app/controllers/api/trainees_controller.rb
- app/serializers/trainee_serializer.rb
- app/services/api/trainees/withdraw_response.rb
- spec/requests/api/v0.1/trainees/withdraw_spec.rb
- spec/requests/api/v0.1/trainees_spec.rb
- spec/services/api/trainees/withdraw_response_spec.rb
Doubled jsoned
Return hash and let rail json it
:shipit:
> [xxxx] Amended to return hash instead of json

- app/controllers/api/trainees/withdraw_controller.rb
- app/controllers/api/trainees/withdraws_controller.rb
- app/controllers/api/trainees_controller.rb
- config/routes/api_routes.rb
Minor tweaks
It is trainee slug not id
It is withdraw no withdraws
:shipit:
> [xxx] Minor api routes tweaks

- app/views/bulk_update/bulk_updates/index.html.erb
- app/views/bulk_update/placements/new.html.erb
- app/views/guidance/manage_placements.html.erb
- app/views/guidance/performance_profiles_outside.html.erb
The guidance on placements required updating by the content designers.
Minor content changes to the guidance on placements.
N/A
- [] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
> Content changes to placement guidance

- spec/controllers/autocomplete/providers_controller_spec.rb
- spec/controllers/autocomplete/schools_controller_spec.rb
- spec/rails_helper.rb
- spec/support/api_request_helpers.rb
unneeded old api helper
Remove unneeded old api helper
:shipit:
> [xxxx] Remove unneeded old api helper

- .github/workflows/build-and-deploy.yml
Reverts DFE-Digital/register-trainee-teachers#4071
> Revert "[6796] - remove QA from build and deploy temporarily"

- Gemfile.lock
nokogiri
Added linux version of nokogiri
:shipit:
> [xxxx] Added linux version of nokogiri

- terraform/aks/workspace-variables/production.tfvars.json
- terraform/aks/workspace-variables/qa.tfvars.json
- terraform/aks/workspace-variables/staging.tfvars.json
https://trello.com/c/PeW6uOPQ/1639-register-statuscake-updates
Change statuscake to monitor /healthcheck instead of /ping
Add new contact group that includes the register tech channel
make qa deploy-plan
> Update statuscake contact group and monitor path

- config/settings.yml
Malformed json
Fixed malformed json
:shipit: 
> [6778] Fixed malformed json

- config/settings/sandbox.yml
`send_data_to_big_query` is set explicitly 
`send_data_to_big_query` setting to false
:shipit: 
> [6778] Amended `send_data_to_big_query` setting to false

- .github/workflows/reset-sandbox-database.yml
:shipit: :facepalm: 
https://github.com/DFE-Digital/register-trainee-teachers/pull/4129#discussion_r1532224288
> [6863] Amended qa to production

- Gemfile
> [6863] Added required gems for sandbox

- app/views/guidance/about_register_trainee_teachers.md
guidance text
Amended guidance text
https://educationgovuk.sharepoint.com.mcas.ms/:w:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7BBFA890CD-19D9-44D3-80AF-0AEC807CA0DA%7D&file=About%20Register%20trainee%20teachers.docx&action=default&mobileredirect=true
https://register-pr-4190.test.teacherservices.cloud/guidance/about-register-trainee-teachers
> [6840] Amended guidance text

- app/controllers/api/trainees_controller.rb
- app/serializers/degree_serializer/v01.rb
- app/serializers/placement_serializer/v01.rb
- app/serializers/trainee_serializer/v01.rb
- app/services/api/append_metadata.rb
- app/services/api/create_trainee.rb
- app/services/api/find_duplicate_trainees.rb
- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
- spec/serializers/degree_serializer/v01_spec.rb
- spec/serializers/placement_serializer/v01_spec.rb
- spec/serializers/trainee_serializer/v01_spec.rb
- spec/services/api/append_metadata_spec.rb
- spec/services/api/find_duplicate_trainees_spec.rb
- spec/services/api/trainees/save_placement_response_spec.rb
[6940-remove-progress-object-foreign-keys-and-any-internal-fields-from-responses](https://trello.com/c/hFL7lfYy/6940-remove-progress-object-foreign-keys-and-any-internal-fields-from-responses)
Currently the API returns internal attributes that shouldn't be exposed publicly. This PR refactors the Serializers to exclude those.
1. Enhance specs to test for all attributes per Entity
2. Remove internal attributes from API responses:
* primary keys
* foreign keys
* progress
* dttp_update_sha
3. Resolve bugs
> [6940] Refactor v01 Serializers

- app/models/trainee.rb
- spec/requests/api/v0.1/put_trainee_spec.rb
[6978-potential-bug-updating-a-trainee-locally-returns-422](https://trello.com/c/dzwUr2US/6978-potential-bug-updating-a-trainee-locally-returns-422)
Resolves bug where `hesa_trainee_detail` record was attempted to be replaced on update
Add the `update_only: true` option to the `hesa_trainee_details` nested attributes
> Enable update_only: true for hesa_trainee_detail_attributes

- app/controllers/api/base_controller.rb
- app/views/api_docs/reference/v0.1/_reference.md
- spec/requests/api/v0.1/put_trainee_spec.rb
- spec/requests/api/v0.1/trainees/put_degrees_spec.rb
[6982-error-message-when-json-is-invalid-could-be-better](https://trello.com/c/mVyfgiux/6982-error-message-when-json-is-invalid-could-be-better)
The current error message is too generic
Render the Exception's capitalized error message
> Refactor ActionController::ParameterMissing message

- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
> Fix post_hesa_trainees_spec

- app/components/contact_details/view.html.erb
- app/components/contact_details/view.rb
- app/components/course_details/view.html.erb
- app/components/course_details/view.rb
- app/components/degrees/view.html.erb
- app/components/degrees/view.rb
- app/components/diversity/view.html.erb
- app/components/diversity/view.rb
- app/components/funding/view.html.erb
- app/components/funding/view.rb
- app/components/iqts_country/view.html.erb
- app/components/iqts_country/view.rb
- app/components/mappable_summary/view.html.erb
- app/components/mappable_summary/view.rb
- app/components/personal_details/view.html.erb
- app/components/personal_details/view.rb
- app/components/placement_details/view.html.erb
- app/components/placement_details/view.rb
- app/components/schools/view.html.erb
- app/components/schools/view.rb
- app/components/sections/view.rb
- app/components/summary_card/view.rb
- app/components/training_details/view.html.erb
- app/components/training_details/view.rb
h3 without h2
Amended to default to h2 where applicable
QA with the issue vs review app with the fix
There are 11 confirmations pages
1. personal_details
1. contact_details
1. diversity
1. degrees
1. course_details
1. training_details
1. schools
1. funding
1. trainee_data
1. iqts_country
1. placements
Below is a sampling of 4
> [6834] Amended to default to h2 instead of h3 as there is no h2

- app/models/api/hesa_trainee_detail_attributes/v01.rb
- spec/models/api/hesa_trainee_detail_attributes/v01_spec.rb
- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
Validation for course age range
Added validation for course age range
There is validation for course age range
> [7052] Added validation for course age range values

- app/views/guidance/manually_registering_trainees.md
A minor content tweak requested for a guidance page.
Content change to the "Manually registering Trainees" guidance page.
N/A
> Minor content change

- .github/workflows/build-and-deploy.yml
- app/models/hesa/trainee_detail.rb
As part of Zoonou accessibility testing, we provided the QA environment for them to test, with no changes being deployed.
Now that the testing has concluded we can put QA back in the pipeline.
https://trello.com/c/PF8ij3J8/7165-put-qa-back-in-the-deployment-pipeline-after-zoonou-have-finished-their-accessibility-testing
* Add QA back into the deployment pipeline
* Also updates a model annotation to keep it up to date with recent changes.
> [7165] Put QA back in the deployment pipeline after Zoonou have finished their accessibility testing

- terraform/aks/application.tf
- terraform/aks/variables.tf
- terraform/aks/workspace-variables/qa.tfvars.json
- terraform/aks/workspace-variables/review.tfvars.json
- terraform/aks/workspace-variables/staging.tfvars.json
https://trello.com/c/bjfo0jo9/1812-onboard-services-to-logitio
Send test cluster logs to logit
Add enable_logit:true to aks deployments for test envs
Check review app logs are in logit and correctly formatted
Check logs not going to log analytics
> send test container logs to logit.io

- .github/actions/bring-docker-image-up/action.yml
- .github/actions/deploy/action.yml
https://trello.com/c/Qq32XwAj/1837-register-update-github-actions
Some workflows still using old versions of azure/login and setup-terraforrm
Update actions in workflows
Check workflows complete successfully
> Update github actions to latest versions

- terraform/aks/workspace-variables/production.tfvars.json
- terraform/aks/workspace-variables/productiondata.tfvars.json
- terraform/aks/workspace-variables/sandbox.tfvars.json
https://trello.com/c/bjfo0jo9/1812-onboard-services-to-logitio 
Send prod cluster logs to logit
Add enable_logit:true to aks deployments for prod envs
make env deploy-plan
> send prod container logs to logit.io

- .github/actions/deploy/action.yml
- .github/workflows/deploy.yml
- config/settings/pen.yml
* Adds pen testing ENV to the deploy workflow
* switches from OTP to DSI for sign-in
> [7238, 7239] - Adds pen to deploy workflow

- app/assets/stylesheets/application.scss
- app/controllers/api/trainees/degrees_controller.rb
- app/controllers/api/trainees_controller.rb
- app/lib/api/error_response.rb
- app/models/api/v0_1/degree_attributes.rb
- app/services/api/get_versioned_item.rb
- app/services/api/trainees/save_degree_response.rb
- app/services/api/trainees/save_placement_response.rb
- app/services/api/v0_1/hesa_mapper/attributes.rb
- app/services/api/v0_1/hesa_mapper/degree_attributes.rb
- config/locales/en.yml
- spec/models/api/v0_1/degree_attributes_spec.rb
- spec/requests/api/v0_1/post_hesa_trainees_spec.rb
- spec/requests/api/v0_1/put_trainee_spec.rb
- spec/requests/api/v0_1/trainees/post_degrees_spec.rb
- spec/requests/api/v1_0/post_hesa_trainees_spec.rb
- spec/requests/api/v1_0/put_trainee_spec.rb
- spec/requests/api/v1_0/trainees/post_degrees_spec.rb
https://trello.com/c/TymIkYpu/7204-post-degree-missing-validation
* Added validations to Degrees so that they are properly validated on POST and PUT
* Refactored the Degrees pipeline a bit
* Couple of other small tweaks
Do the POST and PUT Degree endpoints validate as expected for `uk` and `non_uk` degrees.
> [7204] POST degree missing validations

- app/services/api/trainees/award_recommendation_service.rb
- app/validators/api/trainees/award_recommendation_validator.rb
- config/locales/en.yml
- spec/services/api/trainees/award_recommendation_service_spec.rb
[7196-endpoint-post-trainees-traineeid-recommend-for-qts](https://trello.com/c/BZDMISax/7196-endpoint-post-trainees-traineeid-recommend-for-qts)
* Refactor #call
* Remove the OutcomeDateForm as a dependency
* Add a Custom Validator
> [7196] -  Add POST /trainees/{trainee_id/recommend-for-qts part 2

- data/schools_gias.csv
- docs/setup-development.md
Upload new schools list from Get information about schools
Updated the csv in use
Needed for production as well as source of truth,
https://github.com/DFE-Digital/register-trainee-teachers/blob/main/docs/setup-development.md#import-schools-from-csv-dataschools_giascsv
> [7313] Upload new schools list from Get information about schools

- app/views/guidance/dates_and_deadlines.html.erb
The guidance notes have been updated for the new 2024-2025 academic year.
Content changes to go live on the 1/8/24.
Minor content updates
> Deadline dates updated for 2024-25

- config/settings/productiondata.yml
itt reform
set itt reform to true
> [xxxx] Amended itt reform to be true

- app/services/bulk_update/recommendations_uploads/validate_csv_row.rb
- config/locales/en.yml
- spec/services/bulk_update/recommendations_uploads/validate_csv_row_spec.rb
[Sentry Error](https://dfe-teacher-services.sentry.io/issues/5607423490/?alert_rule_id=4544549&alert_type=issue&environment=production&notification_uuid=6e72990a-1b49-4464-b01e-48796f1cef43&project=5552118&referrer=slack) 
This exception looks like it's caused by bad data, but we currently raise any exceptions all the way up to the controller and do nothing to handle it. We have a [ValidateCsvRow](https://github.com/DFE-Digital/register-trainee-teachers/blob/main/app/services/bulk_update/recommendations_uploads/validate_csv_row.rb) class that validates the row on initialisation. Any errors are added to a messages array, and the `valid?` method just checks if there are any messages in that array. But if an exception is raised, we raise this error all the way up to the controller and the …
> Bulk Recommendations Uploads: Catch Exceptions When Parsing a CSV Row

- app/views/guidance/show.html.erb
- app/views/landing_page/home.html.erb
Content change requested to remove academic year from guidance link text.
As noted above, to remove the need to make the content dynamic or update each academic year.
> Removed academic year from link text

- app/services/copy_providers_to_lead_partners_service.rb
- config/analytics.yml
- db/migrate/20240712150631_add_accredited_to_providers.rb
- db/schema.rb
- lib/tasks/copy_providers_to_lead_partners.rake
- spec/factories/lead_partners.rb
- spec/factories/providers.rb
- spec/services/copy_providers_to_lead_partners_service_spec.rb
- spec/spec_helper.rb
[7340-amend-providers-rake-task-to-support-scitts-and-remove-accreditation](https://trello.com/c/8Z0Wph2o/7340-amend-providers-rake-task-to-support-scitts-and-remove-accreditation)
* Allow the Service to receive record_type param
* Mark providers to accredited false
* Wrap iteration in a transaction
> [7340] Amend Providers rake task to support SCITTs and remove accreditation

- db/service_updates.yml
News article added for "Updating how you recommend trainees for qualified teacher status (QTS) or early years teacher status (EYTS)"
Additional news item added to ```service_updates.yml```
N/A
> News article added

- config/environments/production.rb
- terraform/aks/application.tf
- terraform/aks/variables.tf
- terraform/aks/workspace-variables/production.tfvars.json
- terraform/aks/workspace-variables/qa.tfvars.json
- terraform/aks/workspace-variables/sandbox.tfvars.json
- terraform/aks/workspace-variables/staging.tfvars.json
Scrape the web app process custom metrics
https://trello.com/c/Zlih3dRZ/1889-scrape-custom-metrics
Add enable_prometheus_monitoring to web app
Exclude metrics from ssl
Remove from review tfvars before merge
make env deploy-plan
Check metrics are being collected for the review app
> Scrape custom metrics

- config/initializers/mappings/allocation_subject_to_specialism_mapping.rb
- config/initializers/subjects/allocation_subjects.rb
- config/initializers/training_routes.rb
- db/data/20240703223532_add_funding_rules_for_2024_25.rb
- db/seeds.rb
https://trello.com/c/FmXsAXFa/7311-update-register-for-24-25-funding-rules
https://trello.com/c/9IezQ5kc/7253-24-25-training-initiatives-updates-pgta-funding-rates-for-languages-next-academic-year
We need to set up the funding rules for 2024 based on the [published rules](https://www.gov.uk/government/publications/funding-initial-teacher-training-itt/funding-initial-teacher-training-itt-academic-year-2024-to-2025).
There is one structural change for 2024 with French, German, and Spanish languages having a different grant amount than other languages.
* Add new funding rules to training routes
* Add new allocation subjects for French, German, and Spanish
* Add a data migration to set up the rules in the database
* Add new funding to db seeds
* Fix a typo for `provider_let_postgrad_salaried` …
> [1830, 7253] Update Register for 2024/25 funding rules

- config/locales/en.yml
- spec/requests/api/v0_1/put_trainee_spec.rb
[7386-prepare-for-testing-the-switchover-to-lead-partners-from-lead-schools-and-accredited-providers
](https://trello.com/c/WkTG2QUH/7386-prepare-for-testing-the-switchover-to-lead-partners-from-lead-schools-and-accredited-providers)
* Fix spec
> [7386] Fix specs

- app/views/guidance/_census_sign_off_inside.html.erb
- app/views/guidance/_census_sign_off_outside.html.erb
- app/views/guidance/_course_details.html.erb
- app/views/guidance/_database_only.html.erb
- app/views/guidance/_funding.html.erb
- app/views/guidance/_personal_details.html.erb
- app/views/guidance/_schools.html.erb
- app/views/guidance/_trainee_progress.html.erb
- app/views/guidance/about_register_trainee_teachers.md
- app/views/guidance/census_sign_off.md
- app/views/guidance/check_data.md
- app/views/guidance/hesa_register_data_mapping.html.erb
- app/views/guidance/manage_placements.html.erb
- app/views/guidance/performance_profiles_outside.html.erb
- app/views/guidance/registering_trainees_through_hesa.md
- app/views/reports/_outside_period.html.erb
- app/views/request_an_account/index.html.erb
This branch contains a number of content changes to go live on the 1st August 2024 in preparation for the ITT reforms and the 2024/25 academic year.
This was forked from `7386-itt-reform-testing-for-productiondata-env` so will be merged back into that rather than `main`.
Various content changes.
N/A
> Content changes for 24 25 academic year

- app/views/guidance/bulk_recommend_trainees.md
- app/views/guidance/registering_trainees_through_hesa.md
- config/locales/en.yml
Branch to cleanup last minute content changes before deployment for new academic year.
Various minor content changes and typos fixed.
N/A
> Further content changes

- app/models/academic_cycle.rb
- app/views/system_admin/funding_uploads/confirmations/show.html.erb
- app/views/system_admin/funding_uploads/index.html.erb
- app/views/system_admin/schools/index.html.erb
Renames some missed "Lead Schools" text to "Lead Partners" 
> Rename "Lead School" Text to "Lead Partners" 

- config/settings/staging.yml
Workaround for production deploy
> Switch on DSI fallback on `staging`

- config/settings.yml
- config/settings/development.yml
- config/settings/productiondata.yml
- config/settings/review.yml
- config/settings/test.yml
`lead_partner` and `itt_reform` to be true
Amended `lead_partner` and `itt_reform` to be true
Setting defaults
> [7399] Amended `lead_partner` and `itt_reform` to be true

- config/settings/staging.yml
Staging sign_in_method
Amended sign_in_method to dfe-sign-in
It stopped smoking
> [7421] Amended sign_in_method to dfe-sign-in

- app/services/trainees/create_from_apply.rb
https://trello.com/c/R0hNBrBl/7452-missingcourseerrors-in-sandbox?
Bypass missing course error for sandbox environment on create from apply service
> bypass missing course error in sandbox

- .devcontainer/Dockerfile
- .github/actions/smoke-test/action.yml
- .tool-versions
- Dockerfile
- Gemfile
- Gemfile.lock
- package.json
Alpine & Ruby & NodeJS version is a bit old
Updated Alpine & Ruby & NodeJS version
Nothings breaks and should fix 
https://github.com/DFE-Digital/register-trainee-teachers/actions/workflows/build-nocache.yml
> [xxxx] Amended to alpine 3.20 and ruby 3.2.5 and nodejs 20.15.1

- .github/actions/build/action.yml
- .github/actions/deploy/action.yml
- .github/actions/lint/action.yml
- .github/actions/send-slack-notification/action.yml
- .github/actions/smoke-test/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/build-nocache.yml
- .github/workflows/database-backup.yml
- .github/workflows/next-academic-year-tests.yml
- .github/workflows/reset-sandbox-database.yml
- .github/workflows/tests.yml
The deploy_and_build.yml file has become really unwieldily. 
Break it up to smaller bits
Best to review per commits
> [7457] Refactor github actions to smaller units

- Gemfile
- Gemfile.lock
A number of dependencies seems to be affected by Rails 7.2 update
Update dfe-analytics to v1.14.1
dfe-analytics was previously affected by the Rails 7.2 update
> [7498] Amended dfe-analytics to v1.14.1

- Gemfile.lock
Reverts DFE-Digital/register-trainee-teachers#4576
It got yakked
> Revert "Bump data_migrate from 9.4.2 to 9.4.4"

- Gemfile
- Gemfile.lock
The ripple effects of rails 7.2
Version 9.4.4 was yanked as an unintended consequences of  rails 7.2
Version 11.0.0.rc3 was for rails 7.2
https://github.com/ilyakatz/data-migrate/issues/325#issuecomment-2299322951
https://github.com/DFE-Digital/register-trainee-teachers/pull/4580
> [xxxx] Amended to use version 11.0.0.rc3

- .github/workflows/build-and-deploy.yml
- .github/workflows/database-backup.yml
- .gitignore
- app/services/set_hesa_test_records.rb
- app/services/trainees/create_from_hesa.rb
- config/settings/staging.yml
- spec/services/set_hesa_test_records_spec.rb
HESA testing - prepares staging environment 
* sets DQT endpoint to pre-prod
* removes staging from deploy pipeline
* [TODO] adds script for resetting test trainees
TODO
> [7502] - prepare config/actions/scripts for HESA testing

- app/services/set_hesa_test_records.rb
- spec/services/set_hesa_test_records_spec.rb
> [7502] correct trn spec

- app/models/lead_partner.rb
- spec/factories/users.rb
- spec/features/funding/payment_schedule_spec.rb
- spec/features/funding/trainee_summary_spec.rb
- spec/models/lead_partner_spec.rb
[7528-trainee-summary-show-page-for-lead-partners-not-working](https://trello.com/c/GdYE16UR/7528-trainee-summary-show-page-for-lead-partners-not-working)
* Delegate to school or provider
> [7528] Add LeadPartner#funding_trainee_summaries

- config/settings.yml
https://trello.com/c/LdOUNiaw/7547-reports-page-linking-to-2023-sign-off-form
Update link for data signoff form for current academic year
> [7547] - update form link for data sign off

- config/settings.yml
- config/settings/production.yml
HESA testing has concluded so once HESA have switched to the new collection in production we can switch to it too.
* Turn on HESA integration feature flags
* Change the HESA collection settings to the new values for 2024
* Anything else need changing?
> [7540] Turn on HESA integration and change settings for new HESA collection

- spec/smoke/login_spec.rb
Smokey
Update smoke tests in preparation for dsi change
The flow has changed, previous one form now a form each, one for username and one for password.
Check it out here
https://github.com/DFE-Digital/register-trainee-teachers/actions/workflows/smoke-test.yml
> [7569] Update smoke tests in preparation for dsi change

- docs/openapi.md
- public/openapi/v0.1.yaml
- public/openapi/v1.0-pre.yaml
- spec/factories/degrees.rb
- spec/factories/placements.rb
- spec/factories/trainees.rb
- spec/requests/api/v0_1/get_trainees_spec.rb
- spec/requests/api/v1_0_pre/get_trainees_spec.rb
- spec/requests/api/v1_0_pre/trainees/post_withdraw_spec.rb
- spec/spec_helper.rb
- spec/support/openapi.rb
- spec/support/shared_examples/register_api_endpoint.rb
Noisy diff
Less noisy diff
Pull do the repo, run these command individually without any changes 
There should be a lot less noise diff now
```bash
OPENAPI=1 bundle exec rspec spec/requests/api/v1_0_pre/
OPENAPI=1 bundle exec rspec spec/requests/api/v0_1/
```
Probably best to review with https://github.com/DFE-Digital/register-trainee-teachers/pull/4632/commits
> [7581] [spike] Use static data for api doc generation

- .github/workflows/database-backup.yml
- .github/workflows/reset-sandbox-database.yml
Updated pipeline to use shared action
Updated pipeline to use shared action
> Updated pipeline to use shared action

- spec/smoke/login_spec.rb
Sept 24
https://ukgovernmentdfe.slack.com/archives/C5S500XB6/p1726571951561119
Update smoke tests in preparation for DSI change for Sept 24
For Sept 24
> [7569] Update smoke tests in preparation for DSI change for Sept 24

- app/models/api/v0_1/trainee_attributes.rb
- app/services/concerns/has_course_attributes.rb
- app/services/concerns/primary_course_subjects.rb
- spec/requests/api/v1_0_pre/post_hesa_trainees_spec.rb
Follow up for https://github.com/DFE-Digital/register-trainee-teachers/pull/4659
* Fix spec
* Remove `_attribute` param
> Fix spec, remove unnecessary param

- app/services/lead_partner_search.rb
- app/views/system_admin/lead_partners/index.html.erb
- app/views/system_admin/user_lead_partners/new.html.erb
- config/locales/en.yml
- spec/features/form_sections/teacher_training_data/lead_partner_search_spec.rb
https://trello.com/c/Qtu1DWRG/7617-lead-partner-search-instructions-arent-accurate
Adds ability to search by postcode for lead partners and updates help text.
> [7617] Fix lead partner search

- app/views/guidance/_census_sign_off_inside.html.erb
- app/views/guidance/_census_sign_off_outside.html.erb
- app/views/guidance/census_sign_off.md
[Trello ticket](https://trello.com/c/YDUP6nYn/7657-census-sign-off-guidance-tiny-typo)
* Just adding apostrophes where necessary
https://register-pr-4705.test.teacherservices.cloud/guidance/census-sign-off
Possessiveness or plurality?
> [7657] Fix a tiny typo in the Census sign-off guidance

- .github/workflows/build-and-deploy.yml
- .github/workflows/database-backup.yml
Reverts DFE-Digital/register-trainee-teachers#4694
re-enables productiondata deployment and nightly db overwrite
> Revert "[7544] - disable productiondata deploy/backup"

- app/views/guidance/_census_sign_off_inside.html.erb
- app/views/guidance/census_sign_off.md
[Trello card](https://trello.com/c/EgFHxpfm/7660-add-correct-census-sign-off-form-in-register-guidance)
* Update Census form link for 2024/25
Check the new link goes to the right place
> [7660] Update Census form link for 2024/25

- .github/workflows/code-coverage.yml
- .github/workflows/coverage-tests.yml
Address gitactions issues
Amended name as it clashes with another
Removed unneeded matrix
Amended so it can be ran on demand
Should just work
> [7650] Address gitactions issues

- .github/actions/build/action.yml
Build can be ran on demand
Amended build so it can be ran on demand
> [7650] Amended build so it can be ran on demand

- app/controllers/trainees/employing_schools_controller.rb
- app/controllers/trainees/lead_partners_controller.rb
Follow up for https://github.com/DFE-Digital/register-trainee-teachers/pull/4713
* Refactor strong params
* Use lead_partner_id in Trainees::LeadPartnersController
* Use employing_school_id in Trainees::EmployingSchoolsController
> [7630] Improve how lead partners are displayed on trainee records - part 2

- app/views/trainees/employing_schools/details/edit.html.erb
- app/views/trainees/lead_partners/details/edit.html.erb
- config/locales/en.yml
More changes for https://github.com/DFE-Digital/register-trainee-teachers/pull/4713
* Change links to missing model to point to the details page
* Change details pages css for title
> [7630] Improve how lead partners are displayed on trainee records - part 3

- app/services/lead_partner_search.rb
Fixed spec
Fixed spec by converting  query to be subquery
```ruby 
bundle exec rspec ./spec/controllers/autocomplete/lead_partners_controller_spec.rb
```
> [7650] Fixed spec by converting  query to be subquery

- app/controllers/concerns/api_monitorable.rb
- docs/api-monitoring.md
- spec/requests/api/monitoring_spec.rb
We need to document the process for creating dashboards and visualisations in Grafana. 
I've updated the markdown file for api monitoring to include details about Grafana with screenshots. I've also removed two metrics from the concern, because these are tracked by default with Yabeda and Prometheus.  
> Grafana Docs

- spec/support/features/course_details_steps.rb
Fixed tests that was using incorrect subjects
Fixed tests that found early growth pain
First commit shows the failure point
Second commit uses the correct secondary subjects
```bash
bundle exec rspec ./spec/features/end_to_end/provider_led_undergrad_journey_spec.rb:10 
```
> [7650] Fixed early growth pain

- spec/components/schools/view_spec.rb
- spec/controllers/trainees/lead_partners_controller_spec.rb
Lead partner/employing school details
Amended tests for lead partner/employing school details
```bash
bundle exec rspec ./spec/components/schools/view_spec.rb ./spec/controllers/trainees/lead_partners_controller_spec.rb
```
> [7650] Amended tests for lead partner/employing school details

- config/locales/en.yml
- spec/features/trainee_actions/add_lead_partner_and_employing_school_spec.rb
[7723-update-copy-for-lead-partner-search-field](https://trello.com/c/o99AeNPv/7723-update-copy-for-lead-partner-search-field)
* Change Lead Partners search hint for trainees
> [7723] Update copy for lead partner search field

- app/views/guidance/dates_and_deadlines.html.erb
[Trello](https://trello.com/c/D4cEhdQa)
Removes old copy for the year 23/24 
> Update Dates and Deadlines 

- docs/support_playbook.md
Add instructions for support dev to understand how to convert a `Provider` into a `LeadPartner`
> Add instructions for converting a provider into a lead partner

- spec/factories/schools.rb
School name flake
https://github.com/DFE-Digital/register-trainee-teachers/pull/4774
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/11628204404/job/32383046103?pr=4774
Amended generated school name to be unique
Run this on `main` until there is a collision, then run again `xxxx-non_js_lead_partner_search_spec-flake` until you are happy
```bash
bundle exec rspec ./spec/features/form_sections/teacher_training_data/non_js_lead_partner_search_spec.rb:21 -s 43903
```
The search test is using the name as a unique identifier where by the name is from the school.
https://github.com/DFE-Digital/register-trainee-teachers/blob/main/spec/features/form_sections/teacher_training_data/non_js_lead_partner_search_spec.rb#L59-L61 …
> [xxxx] Amended generated school name to be unique

- app/controllers/trainees/employing_schools_controller.rb
- app/controllers/trainees/lead_partners_controller.rb
- app/forms/partners/form.rb
- app/forms/partners/lead_partner_form.rb
- app/forms/schools/employing_school_form.rb
Follow up for https://github.com/DFE-Digital/register-trainee-teachers/pull/4772
* Use existing methods to cast boolean values
* Remove validation
> [7764] Cannot set a Lead Partner if previously set to not applicable - part 2

- Gemfile
- Gemfile.lock
https://github.com/testdouble/azure-blob/pull/5 is is now merged into main, so we can revert back to source
> [xxxx] - revert azure blob to original

- app/views/pages/privacy_notice.md
- spec/features/pages_spec.rb
Privacy notice
Amended the privacy notice
Have a look
https://register-pr-4782.test.teacherservices.cloud/privacy-notice
> [7754] Amended the privacy notice

- app/services/api/get_trainees_service.rb
- public/openapi/v0.1.yaml
- public/openapi/v1.0-pre.yaml
- spec/requests/api/v0_1/get_trainees_spec.rb
- spec/requests/api/v1_0_pre/get_trainees_spec.rb
Nondeterministic ordering
Fixed deterministic ordering
Before pulling down this branch `xxxx-docs-enforcing-deterministic` 
On the `main` branch
Run theses and observe the larger diffs
Repeat and rinse 
On the `xxxx-docs-enforcing-deterministic`  branch
Run theses and observe the smaller diffs
```bash
OPENAPI=1 bundle exec rspec spec/requests/api/v1_0_pre/
OPENAPI=1 bundle exec rspec spec/requests/api/v0_1/ 
OPENAPI=1 bundle exec rspec spec/requests/api/v1_0_pre/get_trainees_spec.rb
OPENAPI=1 bundle exec rspec spec/requests/api/v0_1/get_trainees_spec.rb
```
Helps to address issues as seen in https://github.com/DFE-Digital/register-trainee-teachers/pull/4747#issuecomment-2450390174 …
> [xxxx] Fixed deterministic ordering on the api docs generation

- .devcontainer/Dockerfile
- .github/actions/smoke-test/action.yml
- .rubocop.yml
- .tool-versions
- Dockerfile
- Gemfile
- Gemfile.lock
Ruby 3.3 has been out n the wild for sometime now... it be good to tame it.
Use ruby 3.3
Nothing breaks
> [7770] Upgrade to ruby 3.3

- lib/tasks/example_data.rake
- spec/factories/providers.rb
- spec/features/bulk_upload/bulk_add_trainees_spec.rb
[7813-fix-example-data-rake](https://trello.com/c/KaVgJ8nz/7813-fix-example-data-rake)
* Fix provider creation in the task
* Fix feature spec
> [7813] Fix example_data.rake

- spec/factories/providers.rb
`accreditation_id`
Fixed uniqueness of `accreditation_id`
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/11816063419/job/32918767899?pr=4805
> [xxxx] Fixed uniqueness of `accreditation_id`

- config/settings.yml
- spec/services/determine_sign_off_period_spec.rb
sign off period
Amended to stay outside of sign off period
:ship: 
> [xxxx] Amended to stay outside of sign off period

- app/services/degrees/create_from_csv_row.rb
- app/services/trainees/create_from_csv_row/base.rb
- spec/services/trainees/create_from_csv_row/teach_first_spec.rb
ITT end date not being imported
Corrects ITT end date retrieval
> [7855] - Teach First CSV import fixes

- .github/workflows/database-backup.yml
- .github/workflows/reset-sandbox-database.yml
- docs/setup-development.md
Use an Azure storage account for all backup files
Updates to the database-backup workflow
Check the code
backup and restore to staging test run https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/12057215410 
> Use storage account for all backups

- app/components/record_actions/view.rb
- app/controllers/trainees/withdrawal/starts_controller.rb
- app/views/trainees/withdrawal/starts/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/trainee_actions/withdraw_trainee_spec.rb
- spec/support/features/page_helpers.rb
- spec/support/page_objects/trainees/withdrawal/start.rb
Withdrawals user journey now has a "start" page explaining outlining the process.
adds new controller, route and "show" page for new step
> [1996] - Create interstitial start page for withdrawals

- app/components/performance_profile_banner/view.rb
- app/models/academic_cycle.rb
- app/services/determine_sign_off_period.rb
- app/views/layouts/application.html.erb
- config/settings/review.yml
- spec/components/performance_profile_banner/view_spec.rb
- spec/features/performance_profile_banner_spec.rb
- spec/models/academic_cycle_spec.rb
- spec/services/determine_sign_off_period_spec.rb
performance banner
Show the performance banner
Builds off from this PR https://github.com/DFE-Digital/register-trainee-teachers/pull/4828
As an accredited provider
As an lead partner
The `Sign off your performance profile` link is out scope as the page is not built yet (next cards etc).
> [7851] Show the performance banner

- .github/workflows/build-and-deploy.yml
> [xxxx] Amended merge method

- docs/aks_modules.md
- docs/creating_new_environment.md
Finalise migration from terrafile
Update docs
Review docs
> [2158] Delete terrafile references from docs

- app/lib/bullet/simple_delegator_helpers.rb
- app/lib/user_with_organisation_context.rb
Suggestion on top of https://github.com/DFE-Digital/register-trainee-teachers/pull/4807
> Dependabot/bundler/bullet 8.0.0 part 2

- app/controllers/reports/performance_profiles_controller.rb
- app/views/layouts/application.html.erb
- app/views/reports/performance_profiles/confirmation.html.erb
- config/routes.rb
- spec/features/reports/performance_profile_spec.rb
Performance profile sign off completed page
Added performance profile sign off completed page
> [7923] Performance profile sign off completed page

- config/settings/staging.yml
Sign off period
Setting sign off period to be performance period 
:ship: 
> [7935] Amended sign off period to be performance period for staging

- app/controllers/reports/performance_profiles_controller.rb
- spec/features/reports/performance_profile_spec.rb
Missing title
Added title to have the the academic year
There is test
> [xxxx] Added title to have the the academic year

- config/analytics.yml
- config/analytics_blocklist.yml
- config/analytics_hidden_pii.yml
[Trello card](https://trello.com/c/r1w0e99F)
* Configure 4 additional fields to be sent to BigQuery
> [7952] Send 4 new fields to BigQuery

- app/views/guidance/manage_placements.html.erb
- app/views/guidance/show.html.erb
[Trello card](https://trello.com/c/kUJEWy8w/7817-manage-your-trainee-placement-data-guidance-review-and-update)
* Update guidance content for trainee placement data
* Remove an obsolete feature flag check
> [7817] Manage your trainee placement data guidance review and update

- app/controllers/reports_controller.rb
- app/views/reports/_system_admin_with_no_associated_provider.html.erb
- spec/features/reports/performance_profile_spec.rb
A system admin with no associated provider, errors out
Amended so that something is shown rather then erroring out
You get to see this
> [7990] Amended to show system admin with no associated provider

- .tool-versions
version for azure-cli
Amended version for azure-cli
:shipit: 
> [xxxx] Amended version for azure-cli

- spec/requests/api/rack_attack_spec.rb
Sometime the machine is slow
Time cop said freeze to stop the flake
Borrowed from https://github.com/rack/rack-attack/blob/86650c4f7ea1af24fe4a89d3040e1309ee8a88bc/spec/rack_attack_throttle_spec.rb#L42-L68
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/12790982301/job/35658210363?pr=4951
> [xxxx] Added a timecop freeze block

- app/components/placements/view.html.erb
- app/views/trainees/placements/delete.html.erb
- spec/features/form_sections/teacher_training_data/placements/deleting_draft_trainee_placements_spec.rb
- spec/features/form_sections/teacher_training_data/placements/deleting_trainee_placements_spec.rb
Wording terminology 
Delete to become remove
:pray: :pray: :pray: 
> [7913] Amended from delete to remove

- app/controllers/reports/performance_profiles_controller.rb
https://dfe-teacher-services.sentry.io/issues/6158317097/?alert_rule_id=4544549&alert_type=issue&environment=production&notification_uuid=84336ca9-b7b5-4974-9dfb-886673321bdb&project=5552118&referrer=slack
Ensure there is a return
No more sentry errors
> [xxxx] Fixed double render error

- docs/setup-development.md
- lib/tasks/schools_data.rake
- spec/lib/tasks/schools_data_realign_lead_partner_with_school_name_spec.rb
A rake task to realign the lead partner with the schools
Added rake task to realign the lead partner with the schools
> [xxxx] Added rake task to realign the lead partner with the schools

- db/data/20250117131629_set_urn_for_leeds_scitt.rb
Leeds Scitt's URN
Added Leeds Trinity University 133838 as Leeds Scitt's URN
https://trello.com/c/Yd8boagD/7937-add-urns-to-scitt-lead-partners-who-are-in-partnership-with-hei#comment-678a65c37f8ca28337203080
> [7937] Added Leeds Trinity University 133838 as Leeds Scitt's URN

- terraform/custom_domains/environment_domains/.terraform.lock.hcl
- terraform/custom_domains/environment_domains/main.tf
- terraform/custom_domains/environment_domains/workspace_variables/register_production.tfvars.json
Adding redirects to RTT
Redirecting from apex to www.
https://register-trainee-teachers.service.gov.uk/ to https://www.register-trainee-teachers.service.gov.uk/
> 1656 create redirect with apex domain

- app/services/bulk_update/placements/create_placement_rows.rb
- spec/services/bulk_update/placements/create_placement_rows_spec.rb
trn is not urn :face_exhaling: 
Fixed typo
:shipit: 
> [xxxx] Fixed urn vs trn typo 🤦

- app/jobs/trs/register_for_trn_job.rb
- app/lib/trs/client.rb
- app/services/trs/register_for_trn.rb
- config/settings.yml
- config/settings/production.yml
- config/settings/productiondata.yml
- config/settings/sandbox.yml
- config/settings/staging.yml
- spec/jobs/trs/register_for_trn_job_spec.rb
- spec/lib/trs/client_spec.rb
- spec/services/trs/register_for_trn_spec.rb
The TRS API requires a new registration endpoint to replace the existing DQT endpoint. This ticket focuses on implementing the registration logic.
Adds new service and job
* Trello ticket: https://trello.com/c/LnPV4hUq/8090-trs-registration-endpoint-and-job
> [TRS][8090] - Register for TRN

- terraform/custom_domains/environment_domains/workspace_variables/register_production.tfvars.json
Add apex domain redirects
Add apex domain redirects
Test the redirect
https://register-trainee-teachers.service.gov.uk/ to https://www.register-trainee-teachers.service.gov.uk/
> feat: Fixing apex domain redirect for RTT

- app/views/bulk_update/add_trainees/reference_docs/fields.yaml
[8114-bulk-add-trainees-csv-guidance-minor-content-fixes](https://trello.com/c/uQHBxOsn/8114-bulk-add-trainees-csv-guidance-minor-content-fixes)
* Amended [app/views/bulk_update/add_trainees/reference_docs/fields.yaml](https://github.com/DFE-Digital/register-trainee-teachers/pull/5000/files#diff-83358f368f8017607382cbcb0ad3b6d360e6e28bfd2137a6ed557cd5b9af3845)
> [8114] Bulk Add Trainees CSV guidance: minor content fixes

- spec/factories/bulk_update/trainee_uploads.rb
> [xxxx] Removed rogue const

- app/views/bulk_update/add_trainees/uploads/index.html.erb
show message for no bulk trainee upload
Amended to show message for no bulk trainee upload
Login as `Emma Smith`
https://register-pr-5050.test.teacherservices.cloud/bulk-update/add-trainees/uploads
> [7974] Amended to show message for no bulk trainee upload

- app/views/api_docs/reference/v1.0-pre/_reference.md
- spec/requests/api/v0_1/trainees/post_placement_spec.rb
- spec/requests/api/v0_1/trainees/put_placement_spec.rb
Content for Duplication Validations
Added content for Duplication Validations
- new trainees
- new/existing placements
- new/existing degrees
https://github.com/DFE-Digital/register-trainee-teachers/blob/025393eb879796c31159eb695fa0ba5dd40a3f21/app/controllers/api/trainees_controller.rb#L41
https://github.com/DFE-Digital/register-trainee-teachers/blob/04eb54995136df398919ef59268ab09b62dc4dea/app/services/api/create_trainee.rb#L19
https://github.com/DFE-Digital/register-trainee-teachers/blob/04eb54995136df398919ef59268ab09b62dc4dea/app/services/api/create_trainee.rb#L34-L40
https://github.com/DFE-Digital/register-trainee-teachers/blob/93ab8a053f0314ab71f15dc68cc81906cf0111de/app/services/api/find_duplicate_trainees.rb#L14-L18
https://github.com/DFE-Digital/register-trainee-teachers/blob/b67 …
> [8129] Added content for `Duplication Validations`

- docs/adr/0010-use-token-authentication-for-api-access.md
- docs/adr/index.md
Document decision to use bearer tokens for API Authentication in an ADR.
Add ADR
Trello ticket [here](https://trello.com/c/7LChHUNa)
> [8202] Add ADR for decision to use tokens for API Auth

- app/forms/withdrawal/reason_form.rb
- app/views/trainees/withdrawal/reasons/edit.html.erb
- config/locales/en.yml
https://trello.com/c/muiH9qYZ
Ensure question makes sense based on previous answer provided by the user
> [8199] - Fix dynamic heading on reasons page

- .github/workflows/database-backup.yml
Overnight backup-restore failed in the restore step, as it tried to az logout when it hadn't logged in.
Remove the logout, as that's not required anymore.
successful rerun from this branch https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/13516110043
> Remove az logout from backup workflow

- .github/actions/bring-docker-image-up/action.yml
- .github/actions/build/action.yml
- .github/actions/coverage-tests/action.yml
- .github/actions/deploy/action.yml
- .github/actions/lint/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/build-nocache.yml
- .github/workflows/code-coverage.yml
- .github/workflows/database-backup.yml
- .github/workflows/delete-review-app.yml
- .github/workflows/deploy.yml
- .github/workflows/disable-maintenance.yml
- .github/workflows/enable-maintenance.yml
- .github/workflows/next-academic-year-tests.yml
- .github/workflows/reset-sandbox-database.yml
- .github/workflows/tests.yml
- Makefile
- terraform/aks/provider.tf
Use oidc for github workflows.
Improves security, as this will use managed identities and federated credentials tied to a repo and environment, instead of a single service principal.
https://trello.com/c/FWUebqgi/2201-github-actions-oidc-for-all-services
Update workflows and actions
build and deploy review app: https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/13503212809
code coverage: https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/13503212792
delete review app: https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/13503893965
backup and restore: https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/13520904637
deploy (using deploy-plan)
- qa: https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/13 …
> Use oidc for github workflows

- .github/workflows/postgres-restore.yml
The namespace is missing from the postgres restore workflow, so it fails.
Update the workflow to set the namespace and pass to the restore action.
see https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/13677812345
> Add namespace to postgres restore

- .github/workflows/build-and-deploy.yml
- terraform/custom_domains/environment_domains/output.tf
Implement cicd for domains infrastructure
Add steps to build-and-deploy workflow 
Add terraform output for environment urls, required for environment healthchecks
deploy-plan for infra and all envs: https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/13763352211
make ci domains-infra-plan
make ci qa domains-plan
make ci staging domains-plan
make ci sandbox domains-plan
make ci production domains-plan
> Implement CICD for domains infrastructure

- lib/tasks/reference_data.rake
[Trello card](https://trello.com/c/4smYTvi5/8314-add-missing-burslev-mappings)
* Tweaked the BURSLEV (`funding_method`) check to match the logic in the HESA mapper
* Removed a duplicated check for training route
* Does this look right?
> [8314] Tweak reference data checking task

- config/settings/production.yml
lots of failing jobs for the qualtrics sidekiq jobs
adds the missing config
> [xxxx] - add missing production qualtrics config

- .github/workflows/reset-csv-sandbox-database.yml
Santised restore for CSV sandbox
Added a santised restore for CSV sandbox
Needs to be merged so it can show up in the github aciton
> [8289] Added a santised restore for CSV sandbox

- app/views/bulk_update/add_trainees/reference_docs/fields.yaml
Small change to the CSV docs to clarify the descriptions for degree type and grade.
See https://trello.com/c/4AvMhbP2/8103-update-guidance-for-submitting-only-the-highest-degree-qualification-via-api-or-csv (originally there was a separate and now superseded ticket (https://trello.com/c/G4ccI7DY/8180-update-api-documentation-to-indicate-degree-relates-to-previous-degree).
Update content for CSV docs.
Before:
After:
> [8103] Update CSV ref docs entry about `uk_degree` and `grade`

- .github/workflows/reset-csv-sandbox-database.yml
- .github/workflows/reset-sandbox-database.yml
Fixing items that can only show when literally testing it
Remove az logout as it not needed
Amended to use with vs env as that was wrong
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/14221463608
> [8289] Fix reset db issue

- app/assets/stylesheets/components/_start_page_banner.scss
- app/views/layouts/application.html.erb
- config/settings.yml
- config/settings/csv-sandbox.yml
- config/settings/development.yml
- config/settings/production.yml
- config/settings/productiondata.yml
- config/settings/qa.yml
- config/settings/review.yml
- config/settings/sandbox.yml
- config/settings/staging.yml
- config/settings/test.yml
Turquoise for the CSV sandbox
Added turquoise for the CSV sandbox
Can be view at https://register-csv-sandbox.teacherservices.cloud/
> [8289] Added turquoise for the CSV sandbox

- app/views/guidance/dates_and_deadlines.html.erb
[8178-clarify-data-submission-cadence-expectations
](https://trello.com/c/ujyhVJGb/8178-clarify-data-submission-cadence-expectations)
> [8178] Clarify data submission cadence expectations

- .github/workflows/build-and-deploy.yml
Auto deploy after production
Added `csv-sandbox` to be deploy after production
It should be along the same section as 
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/14374349883/job/40304189707
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/14374349883/job/40304190166
> [8289] Added `csv-sandbox` to be deploy after production

- app/components/csv_sandbox_banner/view.html.erb
- app/components/csv_sandbox_banner/view.rb
- app/views/layouts/application.html.erb
- config/settings.yml
- config/settings/csv-sandbox.yml
- config/settings/development.yml
- config/settings/review.yml
- spec/components/csv_sandbox_banner/view_preview.rb
- spec/components/csv_sandbox_banner/view_spec.rb
- spec/features/csv_sandbox_banner_spec.rb
Csv sandbox banner
Added CSV sandbox banner
Will only show up once logged on the homepage
https://register-pr-5202.test.teacherservices.cloud/view_components/csv_sandbox_banner/view/show_csv_sandbox_banner
> [8289] The CSV sandbox banner

- config/settings/csv-sandbox.yml
CSV Sandbox vs CSV sandbox
It is CSV sandbox not CSV Sandbox 
:shipit: 
> [8289] Fixed casing from CSV Sandbox to CSV sandbox

- terraform/aks/workspace-variables/csv-sandbox.tfvars.json
The CSV sandbox lacks a worker hence there is no asynchronous processing
The CSV sandbox needs at least one workers
CSV is processed asynchronously
> [8289] Amended worker replicas from 0 to 1

- .github/actions/deploy/action.yml
- .github/workflows/reset-csv-sandbox-database.yml
CSV sandbox misalignment with redis deletion and database reset as they was 2 separated units of work.
CSV sandbox alignment with redis deletion and database reset as a  singular unit of work.
Previously when deploying,  the redis queue  is deleted, this leaves a dead end
> [8289] CSV sandbox alignment with redis deletion and database reset

- .github/workflows/reset-csv-sandbox-database.yml
> [8289] Fixed typo

- terraform/aks/workspace-variables/pen.tfvars.json
Worker for pen
Amended to have worker
😶‍🌫️
> [8408] Amended worker for pen

- app/views/bulk_update/add_trainees/reference_docs/fields.yaml
[Trello card](https://trello.com/c/SJcZxpXJ/8412-specifying-a-uk-degree-csv-guidance-content-update)
* Tweak to the `uk_degree` content for CSV docs
* Does it match the Word doc?
> [8412] Update `uk_degree` content for CSV docs

- spec/forms/authentication_token_form_spec.rb
> Minor spec refactor

- db/service_updates.yml
March edition
Added to news section
Content :scroll: 
https://register-pr-5249.test.teacherservices.cloud/service-updates
> [8448] Added March edition to news

- app/views/csv_docs/pages/add_trainees.html.erb
March 2025 Notification of changes
Removed March 2025 Notification of changes
Content re-pointing
https://register-pr-5245.test.teacherservices.cloud/csv-docs
> [8459] Removed March 2025 Notification of changes

- app/views/bulk_update/add_trainees/reference_docs/fields.yaml
CSV  docs contents
Amended CSV docs contents fixes
Content :eyeglasses: 
https://register-pr-5251.test.teacherservices.cloud/csv-docs#summary-card-itt_qualification_aim
https://register-pr-5251.test.teacherservices.cloud/csv-docs#summary-card-itt_aim
https://register-pr-5251.test.teacherservices.cloud/csv-docs#summary-card-training_initiative
https://register-pr-5251.test.teacherservices.cloud/csv-docs#summary-card-additional_training_initiative
https://register-pr-5251.test.teacherservices.cloud/csv-docs#summary-card-non_uk_degree
https://register-pr-5251.test.teacherservices.cloud/csv-docs#summary-card-institution
> [8461] Amended CSV docs contents fixes

- app/views/api_docs/reference/v1.0-pre/_reference.md
- app/views/bulk_update/add_trainees/reference_docs/fields.yaml
Degree subject content
Amended degree subject content updates
Content :eyeglasses: 
https://register-pr-5252.test.teacherservices.cloud/csv-docs#summary-card-subject
https://register-pr-5252.test.teacherservices.cloud/api-docs/reference#degree-object
> [8458] Amended degree subject content updates

- app/controllers/api/base_controller.rb
[8506-undefined-method-provider-for-nil](https://trello.com/c/hXIGRYsR/8506-undefined-method-provider-for-nil)
https://dfe-teacher-services.sentry.io/issues/6582862838/?project=5552118&referrer=performance-related-issues-issue-stream
DfE Analytics is sending `current_user`, where if `auth_token` is `nil` an exception is raised.
[requestable.rb#L18](https://github.com/DFE-Digital/dfe-analytics/blob/14be35cf91c1ca86a18bd87243444cb3e2d9fae2/lib/dfe/analytics/concerns/requestable.rb#L18)
* Use safe nav operator for `#auth_token`
* Refactor `#auth_token`
> [8506] undefined method 'provider' for nil

- db/service_updates.yml
April edition
Added April edition to news
Content :scroll: 
https://register-pr-5250.test.teacherservices.cloud/
https://register-pr-5250.test.teacherservices.cloud/service-updates
> [8414] Added April edition to news

- config/settings/sandbox.yml
Enable DfE::Analytics for Sandbox
Enable DfE::Analytics for Sandbox and use WIF authentication setup using terraform
> Enable DfE::Analytics send to bigquery with WIF

- app/components/csv_sandbox_banner/view.html.erb
- app/components/csv_sandbox_banner/view.rb
- app/views/layouts/application.html.erb
- spec/components/csv_sandbox_banner/view_spec.rb
- spec/features/csv_sandbox_banner_spec.rb
[Trello card](https://trello.com/c/4GKhkTsE/8508-update-the-notification-banner-and-links-for-the-csv-sandbox)
* Minor content updates for CSV Sandbox environment based on UCD feedback
* Does it match the designs?
> [8508] Update phase and notification banners for CSV sandbox

- .github/workflows/build-and-deploy.yml
- .github/workflows/database-backup.yml
Reverts DFE-Digital/register-trainee-teachers#5256
> Revert "[xxxx] - Disable productiondata deploys and restores"

- config/settings/production.yml
Enables TRS and disables DQT in production settings
> [8492] - Updates production.yml config for TRS switchover

- .github/workflows/delete-review-app.yml
- Makefile
Use a standard workflow for deleting review apps.
Update the delete workflow to use a github actions workflow.
Check the delete workflow - https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/14995750816/job/42129433076
https://trello.com/c/7M3ZvinR
> Use delete review app github action

- app/controllers/bulk_update/add_trainees/empty_templates_controller.rb
- app/forms/bulk_update/bulk_add_trainees_upload_form.rb
- app/models/bulk_update/trainee_upload.rb
- app/views/csv_docs/pages/add_trainees.html.erb
- config/analytics_blocklist.yml
- config/initializers/sentry.rb
- db/migrate/20250411083352_add_funding_rules_for_202526.rb
- db/migrate/20250523143758_add_version_to_bulk_update_trainee_upload.rb
- db/schema.rb
- spec/factories/bulk_update/trainee_uploads.rb
- spec/factories/providers.rb
- spec/features/bulk_upload/bulk_add_trainees_spec.rb
- spec/forms/bulk_update/bulk_add_trainees_upload_form_spec.rb
- spec/support/download_helper.rb
[8559-issue-new-version-of-csv-with-release-notes](https://trello.com/c/4EZOFzgy/8559-issue-new-version-of-csv-with-release-notes)
Version CSV trainee upload
* Add version to `BulkUpdate::TraineeUpload`
* Assign version in `BulkUpdate::BulkAddTraineesUploadForm`
* Add version to empty template filename
* Add version in CSV docs
* Fix `Providers` factory `accreditation_id` uniqueness issue
* Fix `add_funding_rules_for_202526.rb` issue when running locally
* Replace `Sentry.logger` with `Sentry.sdk_logger`
> [8559] Issue new version of CSV with release notes

- app/views/csv_docs/pages/add_trainees.html.erb
User research revealed the providers need more information about what  validation checks are being carried out by the CSV tool to send their data directly to Register.
Updates the CSV guidance as per the [Trello Ticket](https://trello.com/c/Xms0HX2E/8307-csv-guidance-update-with-the-explanation-of-the-validation-process)
> [8307] - CSV guidance update

- app/services/api/v0_1/create_hesa_trainee_detail_service.rb
- spec/services/api/v2025_0_rc/create_hesa_trainee_detail_service_spec.rb
- tech_docs/Rakefile
- tech_docs/lib/govuk_tech_docs/contribution_banner.rb
- tech_docs/lib/govuk_tech_docs/path_helpers.rb
fix disabilities transcription in trainee detail record creation
> [8419] - fix disabilities transcription in trainee detail record creation

- app/components/bulk_update/trainee_uploads/show/failed/view.html.erb
- app/components/bulk_update/trainee_uploads/show/pending/view.html.erb
- app/components/bulk_update/trainee_uploads/show/uploaded/view.html.erb
- app/views/bulk_update/add_trainees/uploads/new.html.erb
- spec/features/bulk_upload/bulk_add_trainees_spec.rb
https://trello.com/c/y3zeMG2z/8638-content-changes-to-csv-bulk-add-new-trainees
Updated content for the bulk add trainees pages
> [8638] - Update content of bulk add trainees pages

- config/analytics.yml
- config/analytics_blocklist.yml
[See the thread](https://ukgovernmentdfe.slack.com/archives/CAHAJFR0X/p1753171745415719)
* Move all `hesa_collection_requests` fields to `analytics_blocklist.yml`
> [xxxx] Remove `hesa_collection_requests` from dfe-analytics

- app/models/academic_cycle.rb
https://trello.com/c/ONsgUfKu/8753-test-failures-for-next-academic-year-2026-tests
Alter a couple of methods for particular days of the week in a month of an academic cycle to always be accurate
> [8753] Test failures for next academic year 2026 tests second Wednesday

- app/views/bulk_update/add_trainees/reference_docs/fields.yaml
- tech_docs/Rakefile
- tech_docs/source/api-docs/index.html.md.erb
- tech_docs/source/api-docs/release-notes.html.md
- tech_docs/source/api-docs/v2025.0-rc/objects/degree.html.md
- tech_docs/source/api-docs/v2025.0-rc/objects/placement.html.md
- tech_docs/source/api-docs/v2025.0-rc/objects/trainee.html.md
- tech_docs/source/csv-docs/index.html.md.erb
- tech_docs/source/partials/csv_docs/_field.html.md.erb
- tech_docs/source/stylesheets/_overrides.scss
> [8669] Updates to API and CSV documentation

- app/components/trs_data_summary/view.html.erb
- app/components/trs_data_summary/view.rb
- spec/components/trs_data_summary/view_spec.rb
[8731-missing-translation-overlapping-text
](https://trello.com/c/19PDGhwh/8731-missing-translation-overlapping-text)
The response from TRS has changed at `v3_20250627`
* Refactor qts labels
* Remove `.no-wrap` css
> Refactor TRS component rendering

- config/settings.yml
- config/settings/test.yml
- spec/mailers/csv_submitted_for_processing_first_stage_email_mailer_spec.rb
https://trello.com/c/oaBt1Fi3/8694-send-emails-for-the-first-stage-of-the-of-csv-bulk-create-trainees-process
Sends the email for uploads that have succeeded
> [8694] Set correct template name and status

- tech_docs/source/api-docs/index.html.md.erb
- tech_docs/source/api-docs/v2025.0/developing-on-the-api.html.md
[Trello ticket](https://trello.com/c/iXEBPdYv/8825-%E2%9D%A4%EF%B8%8F%F0%9F%94%A5-update-content-on-process-for-obtaining-tokens)
Content update for token retrieval guidance
> [8825] Update content for obtaining tokens

- app/views/pages/data_sharing_agreement.md
[8829-publish-updates-to-data-sharing-agreement-page
](https://trello.com/c/APRrXo3b/8829-publish-updates-to-data-sharing-agreement-page)
* Update agreement for 2025
> [8829] Publish updates to Data sharing agreement page

- terraform/aks/workspace-variables/csv-sandbox.tfvars.json
[Trello card](https://trello.com/c/MwXuq0dP)
* Scale down csv-sandbox pods to zero to "switch off" pods before the removal of all the associated infrastructure
> [8786] Scale down csv-sandbox pods to zero

- .github/workflows/build-and-deploy.yml
- .github/workflows/database-backup.yml
- .github/workflows/deploy.yml
- config/settings.yml
- config/settings/csv-sandbox.yml
- config/settings/development.yml
- config/settings/pen.yml
- config/settings/production.yml
- config/settings/qa.yml
- config/settings/review.yml
- config/settings/sandbox.yml
- config/settings/staging.yml
[Trello card](https://trello.com/c/G4vKfFsh)
* Set feature flags
* Revert changes from STDD testing on staging
> [8809] Launch Send Trainee Data Direct

- terraform/aks/application.tf
Follow up for https://github.com/DFE-Digital/register-trainee-teachers/pull/5595
* Use worker key for name `register-production-worker1`, `register-production-worker2`
> [8860] Reconfigure production workers to optimise for STDD - part 3

- app/jobs/teacher_training_api/check_courses_for_missing_providers_job.rb
- app/jobs/teacher_training_api/publish_provider_checker_job.rb
- app/jobs/trainees/create_from_apply_job.rb
- config/sidekiq_cron_schedule.yml
- spec/jobs/teacher_training_api/check_courses_for_missing_providers_job_spec.rb
- spec/jobs/teacher_training_api/publish_provider_checker_job_spec.rb
https://trello.com/c/pijgQV0L/8861-adjust-the-publish-checkers-to-reduce-noise-in-slack
Ensure publish checkers only run in production and test
Reduce frequency of provider checker to once per week
Reduce max number of providers displayed to 10
> [8861] - Adjust environments publish checkers run in

- spec/support/page_objects/base.rb
- tech_docs/source/api-docs/index.html.md.erb
- tech_docs/source/partials/reference_data/_attribute.html.md.erb
Bugs were found during the bug party. 
This deploy fixes 3.
Removed full stops on bullet points. 
Added numbered bullets to another section.
Added full terminology to abbreviations.
None - they are simple content changes.
> [8908][8907][8911] Bullet points, change tense, remove valid on API docs

- Gemfile.lock
- tech_docs/Gemfile.lock
Address https://github.com/DFE-Digital/register-trainee-teachers/security/dependabot
* Bump rack version
> Bump rack from 2.2.17 to 2.2.18

- app/forms/course_details_form.rb
Api guard on age range
Removed api guard on age range
Conflicts with real world expectation
Take a sanitise copy and set the age range for 
```
/trainees/TMyMY9uEspVrauAFY4VajhGR
/trainees/JuCWzUWwNzF2ACWWTySJxQrM
/trainees/YW1wK4qxGUMF37np6KEtZxKi
/trainees/9MvPcSncrFro3qbcfWnBD2fu
/trainees/MgMqJMD2QKZj9CxefbXpUccW
```
> [8949] Removed guard as it seems to conflict for real world expectation

- app/services/send_csv_submitted_for_processing_first_stage_email_service.rb
- spec/mailers/csv_submitted_for_processing_first_stage_email_mailer_spec.rb
- spec/services/send_csv_submitted_for_processing_first_stage_email_service_spec.rb
[Trello card](https://trello.com/c/OLgz6Uqn)
* Send CSV bulk add emails to kept users
> [8967] Only send CSV bulk add emails to kept users

- Gemfile
- Gemfile.lock
- terraform/aks/workspace-variables/qa.tfvars.json
> [8884] Upgrade PostgreSQL - QA

- Makefile
Add some commands to the Makefile to assist with postgres upgrades when following https://github.com/DFE-Digital/teacher-services-cloud/blob/main/documentation/postgres-upgrade.md 
Add to Makefile
- list-pglogs
- download-pglogs
- enable-pglogs
- disable-pglogs
- show-service
- scale-app
- scale-worker
make qa list-pglogs
make qa show-service
> Add Makefile commands for pg upgrade
