app/forms/course_details_form.rb
app/views/trainees/course_details/edit.html.erb
config/locales/en.yml
spec/features/form_sections/teacher_training_data/edit_course_details_spec.rb
spec/support/page_objects/trainees/course_details.rb

https://trello.com/c/92avoV21/2622-s-change-other-age-range-autocomplete-to-standard-select
Change 'Other age range' field from autocomplete component to standard select.
- Head to a manual course details page for a provider-led trainee, for example
- Select 'Other age range'
- Check that the revealed field is now a standard select rather than an autocomplete
- Select an age range and check that the form still saves correctly

[2622] Change 'Other age range' field from autocomplete to select

---

lib/tasks/example_data.rake

Running `bundle exec rails db:migrate db:seed example_data:generate`
can sometimes use cached column information. This seems to be blowing up when creating review apps.
This PR forces rails to reload column information before attempting to generate factories.
Fixes https://sentry.io/organizations/dfe-bat/issues/2587744130/
1. remove [extra](https://github.com/DFE-Digital/register-trainee-teachers/blob/bbe99ebdb27aa34608a7c23e945bdee7684dccd7/Gemfile#L157-L160) require calls to faker/factorybot
2. Ensure trainees table column information is reloaded before running this example data generator.
:warning: This will destroy your test database.
- Run `bundle exec rails db:drop db:create db:migrate db:seed example_data:generate RAILS_ENV=test` 
on master, and expect it to blow up with `undefined …

Reload Trainee cache when chaining db setup/seed commands

---

app/models/apply_application.rb
spec/models/apply_application_spec.rb

Forgot to make provider an optional association in #1368.

ApplyApplication provider relationship should be optional in case provider doesn't exist

---

package.json
yarn.lock

The latest webpack-dev-server isn't compatible with webpacker `5.x`. It requires us to install `@webpack-cli/serve` which errors:
we would need to bump webpacker to `6.x` which introduces breaking changes and requires us to re-structure our JS. This pins it to a version which allows `./bin/webpack-dev-server` to run without requiring the package above.
See here for DHH's comment (last one): https://github.com/rails/rails/issues/43062
Not being able to run an explicit webpack dev server means that on demand compilation is painfully slow when making changes to assets.

Bump webpack-dev-server to lower version for compatibility

---

app/lib/dttp/code_sets/qualification_aims.rb
app/lib/dttp/code_sets/routes.rb

https://trello.com/c/CQlrH21t/2654-s-provider-led-ug-add-values-to-dttp-codesets
- Adds the relevant entity ID mapping for route and qualification aim for the Provider-led (undergrad) route.
- Note: the route ID is the same as Provider-led (postgrad), what distinguishes these routes is the course level (UG vs PG)
🚢

[2654] Provider-led (undergrad) qualification aim and route to DTTP

---

config/locales/en.yml

https://trello.com/c/6wci02Mt/2624-s-change-label-of-course-level-filter-to-education-phase
What it says on the tin.
- Check the filter heading and the 'selected filters' label say 'Education phase'

[2624] Update Course level -> Education phase in filters

---

app/components/apply_applications/trainee_data/view.html.erb
app/components/review_draft/draft/view.html.erb
app/forms/trn_submission_form.rb
app/lib/training_route_manager.rb
app/models/trainee.rb
app/views/layouts/trainee_record.html.erb
app/views/trainees/check_details/_draft_trainee_check_details.html.erb
app/views/trainees/personal_details/show.html.erb
config/locales/en.yml
spec/features/end_to_end/provider_led_postgrad_journey_spec.rb
spec/features/end_to_end/provider_led_undergrad_journey_spec.rb
spec/support/features/training_route_steps.rb
spec/support/page_objects/trainees/new.rb

https://trello.com/c/wxGQZ20K/2621-s-provider-led-ug-dont-show-degree-section
- Adds a new method to the `TrainingRouteManager` -> `requires_degree?`
- Removes the degree section (and all related validations) for trainees on an undergrad route (Early years, Opt-in and Provider-led)
- Changes section titles from 'Personal details and education' -> 'Personal details'
- Adds an end-to-end test for Provider-led (undergrad) trainees
- Create a trainee on an undergrad route
- Check that there is no section to add a degree on the '/review-draft' page and the section title is 'Personal details' (not 'Personal details and education')
- Complete the trainee and press 'Check this record'
- Check that there is no section to add a degree on the `/check-details` page and no banner telling you that …

[2621] Remove degree section for undergrad routes

---

app/views/trainees/apply_applications/confirm_courses/show.html.erb
app/views/trainees/apply_applications/trainee_data/edit.html.erb
app/views/trainees/confirm_details/_form.html.erb

Remove `mark_as_review` and `mark_as_completed` text.
- Remove legend text by making it nil.
**First check**
- On the homepage, click on: `View draft trainees imported from Apply`
- Select a trainee and click on `Trainee data`
- Scroll down and look at the checkbox, it should match the prototype and there should be no legend text above it.
**Second check**
- On the homepage, click on: `View draft trainees imported from Apply`
- Select a trainee and click on `Course details`
- Look at the checkbox, it should match the prototype and there should be no legend text above it.
**Third check**
- Navigate to a non apply AO trainee
- Click on `Course details`
- Look at the checkbox, it should match the prototype and there should be no legend text above it.

[2673] Fix "mark_as_review" text

---

app/views/pages/cookie_policy.html.erb

Add back link to cookies page, which sends users to the `root_path`.
- Navigate to the cookies page in the footer
- Click the back link

[2551] Add back link to cookies page

---

app/components/invalid_data_text/view.rb
app/views/trainees/degrees/_uk_degree_form.html.erb
app/views/trainees/publish_course_details/edit.html.erb
spec/components/invalid_data_text/view_spec.rb

https://trello.com/c/W7ioWhlB/2634-snag-fix-markup
* Add row + column to subject specialism selection
* Remove empty hint div on degree partials when there is no hint. Slight refactor of invalid data text component needed. 
Check both normal draft trainee and Apply draft trainee with invalid data to verify correct behaviour of degree partials

[2634] Fix markup snag

---

app/forms/course_details_form.rb
config/locales/en.yml
spec/factories/trainees.rb
spec/forms/course_details_form_spec.rb

https://trello.com/c/xAaSIkyJ/2544-tighten-up-coursestartdate-validation
Course start dates could be up to ten years ago.
* Change so that the earliest course start date allowed is 01/08/2020
Test the form so that validations are triggered (or not) on the correct inputted date

[2544] Tighten start date validation

---

app/components/review_draft/draft/view.html.erb
app/forms/trn_submission_form.rb
app/lib/dttp/params/placement_assignment.rb
app/lib/training_route_manager.rb
app/models/trainee.rb
app/views/layouts/trainee_record.html.erb
app/views/trainees/check_details/_draft_trainee_check_details.html.erb
app/views/trainees/personal_details/show.html.erb
config/initializers/training_routes.rb
config/locales/en.yml
config/settings/development.yml
config/settings/review.yml
spec/components/funding/view_spec.rb
spec/factories/bursaries.rb
spec/factories/trainees.rb
spec/features/end_to_end/opt_in_undergrad_spec.rb
spec/features/end_to_end/provider_led_postgrad_journey_spec.rb
spec/features/end_to_end/provider_led_undergrad_journey_spec.rb
spec/lib/dttp/params/placement_assignment_spec.rb
spec/models/trainee_spec.rb
spec/support/features/training_route_steps.rb
spec/support/page_objects/trainees/new.rb

- [This trello ticket](https://trello.com/c/cjQgZ7Th/2608-s-configure-bursaries-subjects-for-opt-in)
- Added a 9k bursary for Mathematics, Physics and Languages subjects for trainees on the opt-in undergrad route
Head to https://register-pr-1362.london.cloudapps.digital/
Create trainee on the opt in undergrad route
in the course details, select one of the above subjects elegible for a bursary
Go to funding section and click on either of the top two choices
You will see a busary page, mentioning a 9k bursary that is eligible for the trainee

[2608] Configure bursaries subjects for opt in

---

app/services/trainees/create_from_apply.rb
spec/services/trainees/create_from_apply_spec.rb

Non-prod environments can have missing courses which can cause `Trainees::CreateFromApply` to blow up. Added a guard clause the protect the service from this situtation.

[2663] Update Trainees::CreateFromApply to handle missing course

---

app/controllers/trainees_controller.rb
config/initializers/training_routes.rb

Alphabetise  the `Type of training filter`.
- Navigate to the `Trainee records` page .
- Check that the `Type of training` checkboxes are in alphabetical order.

[2619] Alphabetise 'Type of training filter'

---

app/lib/dttp/params/placement_assignment.rb
app/models/trainee.rb
config/initializers/training_routes.rb
config/locales/en.yml
config/settings/development.yml
config/settings/review.yml
spec/factories/bursaries.rb
spec/features/end_to_end/opt_in_undergrad_spec.rb
spec/lib/dttp/params/placement_assignment_spec.rb
spec/models/trainee_spec.rb
spec/support/features/training_route_steps.rb
spec/support/page_objects/trainees/new.rb

https://trello.com/c/nMF8cKf0/2607-add-opt-in-undergrad-route
Add opt in undergrad route
Create a new trainee and select the 'Opt in (undergrad)' radio button. Check that degree section is not visible on `/review-draft` page and `check-details` page.

[2607] Add opt-in undergrad route

---

.gitignore
Dockerfile
db/data_schema.rb
db/schema.rb
lib/tasks/migrate_with_data.rake
terraform/modules/paas/variables.tf

- https://trello.com/c/dIEIo0C1/2470-data-migrations-arent-running
The data migrations were out of sync across non dev environments. They've been synced up to match with prod so the data migration task should run the next logical migration and record them correctly in the `data_migrations`  table.
This PR consolidates the task to run migrations so it includes the data ones if we're deploying to staging or prod otherwise it'll just run the normal migrations command. Also ignores `ActiveRecord::ConcurrentMigrationError errors` and updates the command in both the `Dockerfile` and `variables.tf` (which overrides the startup command in Dockerfile)

[2470] Fix data migrations

---

lib/tasks/example_data.rake

Review apps are getting duplicate personas over time.
* add `dttp_id` as a `create_with` argument
When creating a persona don't include the `SecureRandom.uuid` in the `find_or_create_by` as that will cause it to always create.
There is already a guard clause to prevent the example data script running on a DB with data already present. I'm not sure how this issue is arising, possibly a race condition between the worker instance and the app instance on the review apps. This looks like a likely cause though and is only run on review apps and QA.

[xxx] Fix duplicate persona creation

---

spec/factories/trainees.rb
spec/forms/deferral_form_spec.rb

Fixes a couple of flakey tests which were failing due to:
- Course start date validation issues for other dates (withdrawing etc)
- Random selection of `Dttp::CodeSets::CourseSubjects::MAPPING` should be avoided as we transform some of these values in the actual UI (eg the test was asserting that a subject such as `German language` was rendered by a component when in fact it would be shown as `German` in the UI

Fix some flakes

---

app/jobs/trainees/create_from_apply_job.rb
spec/jobs/trainees/create_trainees_from_apply_job_spec.rb

https://trello.com/c/ueZhqVy9/2653-test-apply-integration-with-real-data-final-snag
- Update `Trainees::CreateFromApplyJob` to only consider providers that have apply sync enabled

[2693] Only import apply applications where the provider has apply sync enabled

---

spec/controllers/trainees/subject_specialisms_controller_spec.rb
spec/factories/courses.rb

This spec is flakey
* Add a factory that creates a subject with an unmappable course and use that for the invalid branch of the spec.
The setup for the course in this spec was indeterminately adding a mappable subject in the `course_with_subjects` factory (I think) and was failing as the `SubjectSpecialismForm` would then end up with a subject already set and be valid.

[xxx] Fix flakey specialism spec

---

app/models/dttp/school.rb
spec/factories/dttp/schools.rb
spec/models/dttp/school_spec.rb

We match our schools to a list of schools from DTTP. DTTP has a weird and wonderful bunch of statuses for these schools but we only match on 'active' when we look them up. There is a production issue where a user has selected a 'new' school in the lead school dropdown for a couple of trainees. It seems like we should include 'new' as a slightly colourful version of 'active'.
Match DTTP schools in status 'active' and 'new' when looking up the DTTP mapping.
New schools can be selected as lead/employing school so we need to be able to map them.

[2708] Consider 'new' schools active

---

config/initializers/age_ranges.rb

DTTP doesn't currently have an 11-18 age range but a user has asked to
enter it. 
Map it to 11-19 in DTTP for now so as the update jobs don't fail for this trainee.

[xxx] Temporary mapping for 11-18

---

app/views/trainees/check_details/show.html.erb

https://trello.com/c/elY9hBK2/2716-add-training-route-indicator-to-check-details-page
Adds the training route indicator to the 'check-details' page.
It looks like this: ✨ 
:shipit:

[2716] Add training route indicator to check details page

---

app/lib/dttp/params/placement_outcomes/withdrawn.rb
spec/lib/dttp/params/placement_outcomes/withdrawn_spec.rb

When a trainee is withdrawn in register they are not appearing correctly in DTTP. 
Withdrawing a trainee shouldn't:
* set datestandardsassessmentpassed
* change the ITT Qualifaction aim
So... don't do that.

[2724] Don't update ITT Qualification aim

---

app/lib/route_data_manager.rb
app/lib/training_route_manager.rb
config/settings/development.yml
config/settings/review.yml
spec/components/course_details/view_spec.rb
spec/factories/trainees.rb
spec/features/end_to_end/early_years_salaried_journey_spec.rb
spec/forms/course_details_form_spec.rb
spec/forms/study_modes_form_spec.rb
spec/lib/route_data_manager_spec.rb
spec/lib/training_route_manager_spec.rb
spec/support/features/course_details_steps.rb
spec/support/features/training_route_steps.rb
spec/support/page_objects/trainees/new.rb

https://trello.com/c/1WEo4EWI/2617-s-ey-salaried-include-study-mode-question
- Updates the logic in method `requires_study_mode?` to reflect the fact that _only_ Assessment only trainees do not require study mode.
- Switches on the `early_years_salaried` route in dev and review
- Create an Early years (salaried) trainee and check that you are asked for the Study mode in the Course details section.
- Create an Assessment only trainee and check that you are not asked for the same.
- All other trainees should be asked the Study mode question.

[2617] Include 'Study mode' question for Early years (salaried) trainees

---

config/settings/staging.yml

- https://trello.com/c/BjJpySL8/2609-send-test-opt-in-undergrad-route-trainee-to-dttp-staging
- https://trello.com/c/n7TYg06U/2611-send-test-early-years-undergrad-route-trainee-to-dttp-staging
- https://trello.com/c/y08mSLVi/2589-provider-led-ug-send-test-in-staging-and-confirm-trn-and-qts-are-working
Turn on flags in staging for undergrad routes in current sprint

Turn on undergrad routes in staging

---

app/lib/dttp/code_sets/age_ranges.rb
config/initializers/age_ranges.rb
config/initializers/course_levels.rb

We have a lot of publish courses with 11-18 age ranges but not many with
11-19. DTTP doesn't currently have 11-18 so we'll map it to 11-19 for
now.
* Add 11-18
* Move 11-19 into the other age range drop down
* Map 11-18 to the 11-19 age range in DTTP
* Check the course details form. 11-18 should now be a radio option. 11-19 will be in the dropdown
* Select an 11-18 course from publish and make sure it is properly rendered in the 'change' form
I’ve made Mathematics (DPN6) an 11-18 course on the review app. 
* Login as Provider A 
* Open Evon Raynor's course details and that course should be available there.

[2722] Add 11-18 age range

---

app/components/form_components/autocomplete/view.rb
app/components/form_components/country_autocomplete/script.js
app/components/form_components/country_autocomplete/view.rb
app/forms/degree_form.rb
app/views/trainees/degrees/_non_uk_degree_form.html.erb
config/locales/en.yml
spec/features/form_sections/personal_and_education_details/degrees/adding_degree_spec.rb
spec/support/page_objects/trainees/new_degree_details.rb

Fixes [this bug](https://trello.com/c/VWaQIEwy/2542-bug-previous-valid-answers-persist-in-forms-if-you-change-them-to-invalid-answers-and-try-to-submit)
Ensure that country autocomplete retains the invalid value across a form reload.
Picked up a bit of the standard autocomplete code and added it to the countries autocomplete to ensure that they both behave in a similar manner.
From the bug report:
1. Go to make a trainee
2. Go to the degrees section and add a degree
3. click non uk degree
4. on country, select sweden (for example)
5. try to submit the form
6. Youre met with errors, but sweden is valid and stays in the input box
7. change sweden to "something invalid" or any invalid answer
8. try to submit the form
9. ~sweden persists, when it shouldnt~ country input shows "something …

[2542] Ensure invalid country selection is persisted across form reloads

---

app/views/trainees/_results.html.erb
app/views/trainees/check_details/show.html.erb
app/views/trainees/review_draft/show.html.erb
config/locales/en.yml

https://trello.com/c/RdFMDuBU/2585-update-content-to-focus-on-trainees-instead-of-records
Some content changes on `/trainees`, `/review-draft` and `check-details`

[2585] Update content to use trainees not records

---

app/components/record_details/view.rb
app/components/training_details/view.html.erb
app/components/training_details/view.rb
app/lib/dttp/code_sets/regions.rb
app/lib/dttp/mappable.rb
app/lib/dttp/params/placement_assignment.rb
app/models/trainee.rb
config/locales/en.yml
spec/components/record_details/view_preview.rb
spec/components/record_details/view_spec.rb
spec/components/training_details/view_preview.rb
spec/components/training_details/view_spec.rb
spec/factories/providers.rb
spec/factories/trainees.rb
spec/lib/dttp/params/placement_assignment_spec.rb

- https://trello.com/c/YZ5CUl5r/2613-s-surface-region-information-to-ui-for-teach-first-providers
- https://trello.com/c/rBf9Om36/2615-s-handle-sending-region-information-to-dttp-for-teach-first-trainees
- Surfaces the region information for trainees belonging to a teach first provider (see components in the review app for preview as we don't have any in the system at the moment)
- Handle sending region information to DTTP

[2613] & [2615] Surface region information to UI and handle DTTP

---

config/environments/production.rb

Production logging config is defined in `config/initializers/semantic_logger.rb`
Don't log active record queries in production
Remove redundant logging config

Don't log active record queries in production

---

app/components/form_components/autocomplete/sort.js

https://trello.com/c/Pey3mefl/2650-zendesk-user-cannot-find-degree-organisation
We're using @babel/polyfill (core-js@2) to provide ES6 functionality to older browsers.
However, the function `fill()` only works from core-js@3.
[@babel/polyfil is now deprecated](https://babeljs.io/docs/en/babel-polyfill) and instead of migrating from core-js@2 to core-js@3 I've fixed the immediate issue be replacing `flat()`.
- Ensure the autocompletes work as before
- Test that the autocompletes work on Edge (old versions 12 - 18)

[2650] Fix JS on Edge by replacing flat function

---

app/components/funding/view.rb
config/locales/en.yml
spec/components/funding/view_spec.rb

https://trello.com/c/FY5CvZj1/2705-s-funding-content-changes-for-all-trainees
A couple of small content changes for the funding section applicable to all trainees (i.e. regardless of whether they're on a scholarship).
**On the bursary form:**
- Hint text for the 'No bursary applied for' radio button should read "For example the trainee is not eligible or is self-funded"
**On the funding summary card:**
- Label on the bursary row should read "Funding method" (rather than "Bursary details")
- When there is a possible bursary, but the user has chosen "Not applying", the row should read "Not funded" (rather than "Not bursary funded")
- For **registered** trainees: When no bursary is applicable, the row should read "Not applicable" (rather than "No bursaries available for this course")
**On …

[2705] Funding content changes

---

app/controllers/trainees/apply_applications/course_details_controller.rb
app/controllers/trainees/publish_course_details_controller.rb
app/controllers/trainees/subject_specialisms_controller.rb
app/forms/publish_course_details_form.rb
app/models/course.rb
app/models/trainee.rb
app/views/trainees/subject_specialisms/edit.html.erb
config/initializers/mappings/publish_to_allocation_subject_mapping.rb
spec/components/course_details/view_spec.rb
spec/components/publish_course_details/view_spec.rb
spec/factories/courses.rb
spec/factories/trainees.rb
spec/features/trainee_actions/change_course_spec.rb
spec/forms/publish_course_details_form_spec.rb
spec/lib/route_data_manager_spec.rb
spec/support/page_objects/trainees/confirm_publish_course_details.rb
spec/support/page_objects/trainees/record.rb

https://trello.com/c/Iie17NYp/2725-bug-changing-course-on-a-non-draft-trainee-record-fails-to-save-the-subject-specialisms
- Remove all the form stash clearing in `PublishCourseDetailsForm` and leave that responsibility to `Trainees::PublishCourseDetailsController` so that it's done towards the end of the request. The was the main source of the bug.
- Remove `PublishCourseDetailsForm#reset_course_subject_fields` as it also interfered with data currently stored in `SubjectSpecialismForm`. It was created to handle the case where a publish subject only has one specialism. We can handle that scenario by updating `Trainees::PublishCourseDetailsController#next_step_path` so that it always directs the user to the specialisms controller which already has the logic to handle single specialisms. …

[2725] Fix: changing course on a non-draft trainee record fails to save the subject specialisms

---

app/views/trainees/funding/bursaries/_non_tiered_bursary_form.html.erb
app/views/trainees/funding/bursaries/_tiered_bursary_form.html.erb
config/locales/en.yml

The funding guidance links should be the same for all trainees regardless of whether they're Early years or not.
https://www.gov.uk/government/publications/funding-initial-teacher-training-itt/funding-initial-teacher-training-itt-academic-year-2021-to-2022
Updates url and link text.

[xxx] Update funding guidance link to be generic

---

app/forms/concerns/course_form_helpers.rb
app/lib/route_data_manager.rb
spec/forms/course_details_form_spec.rb
spec/lib/route_data_manager_spec.rb

If a trainee changes route or course, any previously entered scholarship details may be wrong.
Wipe the scholarship details on route and course change, just like we do for `applying_for_bursary`.

[xxx] Wipe scholarship details on route/course change

---

app/components/application_record_card/view.rb
app/components/route_indicator/view.rb
app/controllers/trainees_controller.rb
spec/components/application_record_card/view_spec.rb

https://trello.com/c/srD42qU5/2738-snag-use-course-name-if-specialism-is-not-set-yet
- Update the `ApplicationRecordCard` and `RouteIndicator::View` to use course name for subject if subject specialism is not set
- Visit the trainee index page filter by "Imported from Apply"
- The course names should be displayed in each item in the list
- Click on a record
- The course name should be displayed in the inset text area just before the course code

[2738] Snag fix: use course name if specialism is not set yet

---

config/initializers/mappings/publish_to_allocation_subject_mapping.rb
lib/tasks/example_data.rake

https://trello.com/c/K3nX2HLn/2760-bug-missing-subject-specialism-mapping-dance
Customer reported that selecting the dance course caused her to land on the specialisms page but with no specialiams:
We didn't have it declared in the publish subject specialism mapping.
- Add "Dance" specialism mapping
- Update rake `example_data` task to include "Dance" course
- Visit a trainee with published courses
- Change course and select Dance
- It should go straight to the confirm page

[2760] Bug - missing publish subject specialism mapping "Dance"

---

app/forms/contact_details_form.rb

We get a lot of validation errors from users trying to submit the form without a value in 'town'.
* Remove the presence validation from 'town'
Add personal details to a trainee but omit town. Should be valid.

[2763] Town is not required

---

app/lib/dttp/code_sets/grades.rb
app/services/degrees/map_from_apply.rb
spec/services/degrees/map_from_apply_spec.rb

We sometimes receive predicted grades from apply, eg: "First class honours (predicted)"
This PR aims to handle them and map them based on HESA codes or the actual predicted grade.
1. Add hesa codes to grades based on https://www.hesa.ac.uk/collection/c20051/a/class
2. When hesa codes are not available, strip the word "predicted" from the grade text, and let the Mapping service work its magic as it does with institution et al.
Try importing and asserting against staging data dump. (of these, some would previously have been marked with a degree grade of "other" and free text.
The expectation here is that they would be mapped correctly to the specified hesa grade code or the predicted degree where possible.

[2777] Improve grade mapping based on hesa_degclss or grade name

---

db/data/20210921134907_reset_update_sha_for_funding.rb

https://trello.com/c/oHhoeW5Q/2525-backfill-funding-details-on-dttp
Adds a data migration which finds all the trainees who's funding details were added before the DTTP integration was switched on and resets their `dttp_update_sha` to nil so that they're synced with DTTP overnight.
On production, this corresponds approx 80 trainees in Register.

[2525] Add data migration for updating trainees with funding on dttp

---

app/controllers/trainees/training_details_controller.rb
spec/controllers/trainees/training_details_controller_spec.rb

Trainee ID not showing confirm page
Fixed redirect to confirm page issue
Find a `apply` trainee and go and click `Check trainee record` then edit from there.

[2770] Fixed Trainee ID redirect to confirm page issue

---

app/controllers/trainees/apply_applications/confirm_courses_controller.rb
app/controllers/trainees/language_specialisms_controller.rb
app/forms/publish_course_details_form.rb

https://trello.com/c/FL1O6Slw/2772-1-2-day-spanish-specialism-subject-didnt-map-correctly
- Fix `Trainees::ApplyApplications::ConfirmCoursesController` so it can map language courses with a single language
- Updated `Trainees::LanguageSpecialismsController` to check if the course has one language specialism and if so just skip the manual selection page and go straight on to the next page (ITT date page or confirmation page)
- Running the following code in the console to find a language course that has one subject mapping to one specialism:
```ruby
Course.all.find { |c| c.subjects.count == 1 && PUBLISH_MODERN_LANGUAGES.include?(c.subjects.pluck(:name).first) }
```
- Visit a trainee with an application
- Enter the course details page
- Change course and select the one matching the course …

[2772] Fix: single language subject not mapping correctly on apply confirm course page

---

app/jobs/trainees/create_from_apply_job.rb
app/services/teacher_training_api/retrieve_courses.rb
app/services/trainees/create_from_apply.rb
spec/jobs/trainees/create_trainees_from_apply_job_spec.rb
spec/services/teacher_training_api/retrieve_courses_spec.rb
spec/services/trainees/create_from_apply_spec.rb

Some courses get withdrawn over the course of time, and these non-findable courses sometimes have apply applications associated with them.
This change is to ensure that we fetch all courses non-findable courses, to enable us to map them to trainees correctly.
1. Ensure we import all courses (including non-findable)
2. in case of a course still not found, raise and capture an exception to sentry

[2779] Import non-findable courses from TTAPI

---

app/components/apply_applications/trainee_data/view.rb
app/views/trainees/apply_applications/trainee_data/edit.html.erb
spec/components/apply_applications/trainee_data/view_preview.rb
spec/components/apply_applications/trainee_data/view_spec.rb

https://trello.com/c/GSquLmWl/2774-missing-data-ui-should-turn-red-on-validation
* One form object instead of two separate ones. Therefore, the errors are carried down from the TraineeDataForm and then into the UI
* Fix tests and view preview
Try to submit an Apply draft with missing data at `trainees/{trainee.slug}/apply-application/trainee-data`. The styling should turn from blue to red. There is another bug where invalid non-degree fields always has 'contains 0 answers that you need to amend'.

[2774] Missing data turns red on UI on submission

---

app/controllers/trainees/diversity/confirm_details_controller.rb
app/controllers/trainees/diversity/disability_disclosures_controller.rb
app/controllers/trainees/diversity/disclosures_controller.rb
app/controllers/trainees/diversity/ethnic_backgrounds_controller.rb
app/controllers/trainees/diversity/ethnic_groups_controller.rb
app/forms/diversities/ethnic_background_form.rb
app/forms/diversities/ethnic_group_form.rb
app/lib/wizards/diversities_step_wizard.rb
app/views/trainees/diversity/ethnic_backgrounds/edit.html.erb
spec/factories/trainees.rb
spec/features/form_sections/personal_and_education_details/diversities/edit_ethnic_group_spec.rb
spec/forms/diversities/disability_disclosure_form_spec.rb
spec/forms/diversities/ethnic_group_form_spec.rb

https://trello.com/c/mP11oLki/2748-ethnicity-regression-follow-the-gif-and-scream-afterwards
- Fixed translation rendering on ethnic background page
- Fixed some diversity bugs related to persisting the choices made in the context of editing non-draft trainees or draft trainees created from an Apply import
- There was a bug in the example data where trainees by default don't disclose diversity information but still had a value for `Trainee#disability_disclosure` which messes the page flow when choosing to disclose diversity information.
- Fix translation bug for label "Another White background"
- Reset local DB: `rake db:reset && rake db:seed && rake example_data:generate`
- Pick a trainee in draft state, imported from Apply and TRN received
- For each trainee, play around with the …

[2748] Ethnicity regression fixes and more

---

app/forms/personal_details_form.rb
config/locales/en.yml
spec/forms/personal_details_form_spec.rb

https://trello.com/c/HGzkiWRF/2754-first-name-exceeds-50-chars
* Added validation for `first_names`, `middle_names` and `last_name` for max length 50
* Personal details section

[2754] max length validation for names

---

app/components/sections/view.rb
spec/components/sections/view_preview.rb
spec/components/sections/view_spec.rb
spec/factories/trainees.rb

sections confirmation view for `trainee_data`
Fixed sections confirmation view
Increase test coverage
Previously a keyword argument parameter was added ([see](https://github.com/DFE-Digital/register-trainee-teachers/pull/1494)) , not enough test broke.
Complete data entry for an `Apply application` go thru the flow etc, when you complete it and get to `/check-details` (example http://127.0.0.1:5000/trainees/r1qUB31EeE6F3YPLdisaFzww/check-details)
it goes :boom: 
On master ![image](https://user-images.githubusercontent.com/470137/134647038-031640b7-ef30-4afd-af8e-4f6c8f6302f7.png)

[2774] Fixed sections confirmation view

---

app/services/dttp/contact_update.rb
spec/services/dttp/contact_update_spec.rb

It seems DTTP no longer supports PATCH. Using POST instead.
https://trello.com/c/WhAQGVz7/2801-bug-contactupdate-uses-patch-instead-of-post
- Update `Dttp::ContactUpdate` to use POST request

[2801] Bug - Dttp::ContactUpdate not working using PATCH requests

---

config/settings/production.yml

This will import all the applications but not create any trainees as all providers in prod do not have `apply_sync_enabled` set to true. There will be a sep. PR for that which will "turn things on".

[2798] Turn apply flag on for prod

---

app/services/dttp/contact_update.rb
spec/services/dttp/contact_update_spec.rb

This reverts #1497 because POST doesn't work which make kinda sense. When POST was use we got back the following DTTP error:
```
"error":{"code":"0x0","message":"Unmapped Request found, PathTemplate:~/entityset/key, HttpVerb:POST"}}, headers: {"cache-control"=>["no-cache"], "allow"=>["GET,PUT,PATCH,DELETE,OPTIONS,GET,HEAD,POST"]
```
DTTP must be preventing a PATCH request for another reason.

Revert "[2801] Bug - Dttp::ContactUpdate not working using PATCH requests"

---

app/forms/funding/bursary_form.rb
app/forms/language_specialisms_form.rb
app/forms/schools/form.rb
app/forms/trainee_form.rb
spec/forms/funding/bursary_form_spec.rb

- https://trello.com/c/QCUY3C5L/2794-bug-prod-error-with-funding
Some form objects will need to stash non model related fields so those fields are properly hydrated when the user is confirming changes (and to also prevent missing data information incorrectly showing). This PR splits out the the method `fields_to_ignore_before_stash_or_save` on the `TraineeForm` into two. So fields can be ignored based on the context (being saved/being stashed)

[2794] Granularize which fields to stash or save

---

app/components/degrees/view.rb
app/controllers/concerns/appliable.rb
app/controllers/trainees/contact_details_controller.rb
app/controllers/trainees/course_details_controller.rb
app/controllers/trainees/degrees_controller.rb
app/controllers/trainees/personal_details_controller.rb

This PR fixes this ticket: https://trello.com/c/adCWoSsb/2813-broken-card-title-when-theres-missing-data and some snags around not being able to update changes for personal/contact details.
Some of the controllers dealt with logic around returning the draft to the correct last page but this is only relevant for apply drafts. Once they're non drafts the controller's default redirect behaviour should be used

A few fixes related to the Apply Integration

---

app/forms/apply_applications/confirm_course_form.rb

When confirming the course, the `@course` found in the form object can have a study mode of `full_time_or_part_time`. We want to set to return `nil` so the user can confirm as part of the normal flow

[xxxx] Fix course study mode for apply

---

app/services/trainees/create_from_apply.rb
spec/services/trainees/create_from_apply_spec.rb

https://trello.com/c/S50pAExe/2816-fix-ethnic-background-for-trainee-apply-applications
This bug came from a real trainee application where the `ethnic_background` was set to "Mixed European" which is not a known background in register. This should have been stored in `additional_ethnic_background` and `ethnic_background` set to "Another ethnic background". This will also fix a DTTP error related to `/dfe_ethnicities() -- is invalid`
- Update `Trainees::CreateFromApply` to handle the scenario when the ethnic background is not listed in `Diversities::BACKGROUNDS`

[2816] Fix ethnicity information from Apply applications

---

config/initializers/filter_parameter_logging.rb
config/initializers/semantic_logger.rb

We need to ensure we aren't logging personal or sensitive data when we
send logs to any external services. This change adds to the custom log
formatter we use with Semantic logger to remove these params in
non-dev and non-test environments. We could in theory have achieved the
same using Rails' filter_params config, but this approach is more
fullproof and we've established that we don't need this data in the
system logs.

[2787] clear out params for post requests in logs

---

app/components/route_indicator/view.rb
app/controllers/trainees/apply_applications/course_details_controller.rb
app/models/apply_application.rb
spec/components/route_indicator/view_preview.rb
spec/components/route_indicator/view_spec.rb
spec/features/form_sections/teacher_training_data/apply_applications_spec.rb
spec/models/apply_application_spec.rb

fixes https://trello.com/c/CREaXO17/2809-changing-course-details-to-another-course-not-listed-crashes-the-course-details-page
Redirect to the publish course selection in the event a trainee does not have a course code assinged to them.
1. Visit course details on an apply draft and optionally, if prompted to "confirm course" choose "No, change the course"
2. On the "What course are they doing" choose "Another course not listed"
3. Continue so that you are taken to the Course details page.
4. From here, skip to the Trainees index page, and visit the same draft trainee. (you are taken to the review draft page)
5. Try to visit the course details section, you are redirected to the publish course selection page.
Compare the same against [main …

[2809] Redirect to publish course details page when course code is not found

---

db/data/20210928103544_update_old_subjects_for_trainees.rb

There are 4 awarded trainees and one draft who have the `course_subject_one` as `creative arts and design`, an old subject which  we changed to `art and design`. 
This PR updates those subjects to the new `Dttp::CodeSets::CourseSubjects::ARTS_AND_DESIGN`

[2836] Update trainees with old subject to their new ones

---

app/views/trainees/_filters.html.erb
config/settings.yml
config/settings/development.yml
config/settings/qa.yml
config/settings/review.yml
config/settings/staging.yml
spec/features/trainee_actions/filtering_trainees_spec.rb

https://trello.com/c/8NpXzaOP/2834-imported-from-apply-filter-being-removed
The bug reported was that:
- if you click on 'View draft trainees imported from Apply (xx)' on the homepage
- then the view is correctly filtered by Apply trainees
- but if you add another filter
- the Apply filter disappears
**This was happening only in production, no other environments**
This was actually due to the fact that the feature flag for the filter itself had been left 'off' in prod.
Since we've now have Apply trainees in the system, I've chosen to remove the feature flag completely.
- Check for any regressions with filtering by Apply trainees, the bug itself is only on production.

[2834] Enable Apply filter in production

---

app/forms/publish_course_details_form.rb
spec/forms/publish_course_details_form_spec.rb

https://trello.com/c/0OT3KsCK/2733-bug-itt-start-date-pre-population
- Stop saving the publish course start date as the trainee's start date for `pg_teaching_apprenticeship` trainees before asking them the ITT start date question
- Create a pgta trainee
- Select a publish course
- Click continue until you get to the ITT start date form
- Check that it's not pre-populated with the publish course start date

[2773] Stop pre-populating the ITT start date with the course start date

---

app/controllers/trainees/not_supported_routes_controller.rb
app/controllers/trainees/training_routes_controller.rb
app/views/trainees/not_supported_route.html.erb
spec/features/trainee_actions/edit_trainee_training_route_spec.rb
spec/support/features/page_helpers.rb

https://trello.com/c/4meZO55D/2747-bug-changing-an-existing-trainees-route-to-other-errors
Fixes two bugs
1) Error on selecting "other" as a training route on an existing trainee
2) When the user goes to not supported route view after selecting other, the go back link takes the user to the `/trainees/new` page. If the trainee has already been created and the route simply needs to be edited, this is not correct. 
* The go back link will take user to `trainees/#{trainee_id}/training-routes/edit` if trainee exists. If a new trainee then `/trainees/new` as before
* Update trainee method returned if 'other' selected to avoid error
Edit an existing trainees route and select 'other' option. And also create a new trainee and do the same.

[2747] bug changing an existing trainees route to other errors

---

config/initializers/training_routes.rb

https://trello.com/c/mbuYHvRR/2840-add-transition-to-teach-initiative-for-school-direct-salaried-trainees
We know that this training initiative is definitely available for School direct (salaried) trainees, so this PR includes it as an option.
- Select a School direct (salaried) trainee and click into funding
- Ensure that 'Transition to teach' now appears as an option alongside the original three:

[2840] Add Transition to teach initiative for School direct (salaried) trainees

---

app/views/trainees/training_routes/_form_fields.html.erb
config/locales/en.yml

https://trello.com/c/zy9zN1ou/2838-add-hint-text-to-provider-led-radios-on-the-route-selection-page
What it says on the tin.
- Add a new trainee and check that the correct hint text appears only below the provider led radio buttons

[2838] Add hint to provider led radio buttons

---

app/components/application_record_card/view.rb
app/controllers/trainees_controller.rb
app/helpers/trainee_helper.rb
app/models/provider.rb
app/models/trainee.rb
spec/components/application_record_card/view_spec.rb
spec/factories/providers.rb
spec/models/trainee_spec.rb

Reference issue https://sentry.io/organizations/dfe-bat/issues/2482629234/?environment=production&project=5552118&query=is%3Aunresolved
Some providers will list courses with the same code. Make sure `#published_course` on the `Trainee` is scope to their own provider

[2814] Make sure published course is scope to trainee's provider

---

app/components/route_indicator/view.rb
spec/components/route_indicator/view_spec.rb

https://trello.com/c/X724UQ5Y/2812-capitalising-for-course-title
Upcases only first letter of course in route indicator component
Check apply draft trainee and make sure their course name is upcased in on the review draft page

[2812] Upcase first letter of course

---

app/lib/dttp/code_sets/institutions.rb

Add former name for university so it's easier to find in our autocomplete.

Add synonym for Swansea University

---

app/helpers/mappings_helper.rb
app/lib/dttp/code_sets/grades.rb
app/services/degrees/map_from_apply.rb
spec/services/degrees/map_from_apply_spec.rb

https://trello.com/c/nOTuiuHL/2843-bug-with-predicted-grade
- Update `Degrees::MapFromApply` to better map grade data, especially when it's from a free text field

[2843] Bug with predicted grade

---

app/view_objects/missing_data_view.rb

Remove the missing data blue notice banners. 
- Remove the `ReviewSummary` component from the confirm details show page.
- Navigate to an apply trainee which has missing details.
- On the `check-details` page, click the Review data/Continue section links.
- Ensure that the blue banner does not appear on any of these pages.
- Ensure that the inset text highlighting the missing details does.
- Check if there is anywhere else that it needs to be removed.

[2579] Remove ReviewSummary banner from confirm details show page.

---

app/controllers/trainees/language_specialisms_controller.rb
spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb

https://trello.com/c/fLz9mxqT/2850-language-specialism-isnt-saving-automatically-from-course-selection
Diagnosed from a user session: selecting a course with one single mappable language subject was broken.
Steps to recreate the original bug on Trello ticket.
Note: I added a failing feature test to check we're now covered.
- Select a course with one single language subject so that you're not shown the subject specialism form
- Continue to the confirm page
- Check that the subject isn't missing
- Check that you can confirm and save

[2850] Fix form for a single mappable language course

---

app/forms/course_details_form.rb

https://trello.com/c/oFFhj2gs/2849-funding-is-cleared-when-only-course-dates-are-changed
This fixes a bug whereby if you re-entered a complete course section and changed the course_start_date, it would clear the funding section because the form changed `course_subject_two` from `nil` to empty string.
- Complete a trainee with a scholarship
- Go back into course details and change the start/end date
- Save
- See that the scholarship information is still present and the funding section is still complete

[2849] Don't save empty strings as course subjects

---

app/services/find_empty_trainees.rb
spec/services/find_empty_trainees_spec.rb

`FindEmptyTrainees#call` sort of caves when dealing with 30K+ trainees largely due to the transformations we make in Ruby with `#filter_map` to load the records into memory and serialize so we can build a digest of values to check against.
This PR delegates the logic to the database so performance is improved and the trainee index page still loads quickly. Tested with a sample size of 30k trainees locally (since that was the point where things caved) and still worked fine after.
- Go to index page
- Check empty trainees are still being filtered out correctly

Improve logic to find empty drafts

---

config/locales/en.yml
spec/services/exports/trainee_search_data_spec.rb

Casing of training initiatives names
Fixed casing of training initiatives names
:shipit:

[2878] Fixed casing of training initiatives names

---

app/lib/dttp/code_sets/degree_types.rb

Our degree type list has two generic options meant as catch-all answers where a degree type is missing. Unfortunately unless users know they're there, they're unlikely to find them.
This adds most of the qualifications listed here as synonyms for the two options.
Tweaks I've made:
* Removed superfluous options
* Added one abbreviation
* Included `Other` as I think users may try typing that

Add synonyms for catch-all degree types

---

app/services/teacher_training_api/retrieve_courses.rb
spec/services/teacher_training_api/retrieve_courses_spec.rb

We only want 2021 courses at the moment. 
Scope the courses query to 2021 recruitment cycle. Hard coding for now to fix a production issue.
Further work will be done to handle years in preparation for registering next cycle's users.

[xxx] Only sync 2021 courses

---

app/lib/dttp/params/placement_assignment.rb
spec/lib/dttp/params/placement_assignment_spec.rb

HPITT trainees have a 'region'. The entity for regions in DTTP is `dfe_goregions` not `dfe_regions`
Fix it.

[xxx] Fix region entity name

---

lib/tasks/hpitt_bulk_submit.rake

One trainee isn't ready to be submitted so they are excluded.
We need to bulk submit ~1500 trainees on the HPITT program that are now ready to be submitted for TRN.
Add a rake task to do this.
The task:
* loops through the HPITT trainees in batches of 10
* if they are valid and draft sets them to submitted
* queues up a job to register them
* queues up a job to poll for the TRN
* increments the delay by 15 seconds after each batch to limit the load
on DTTP
It doesn't log any that aren't valid as these will just remain draft so we'll be able to track that in the app.
This can be run locally on the sanitised prod dump without sidekiq running.
3040 jobs will be put into the ScheduledSet - 2 jobs per trainee.
All of the HPITT trainees will be set to `submitted_for_trn` and the `submitted_at` …

[3093] Rake task to bulk submit HPITT trainees

---

app/webpacker/scripts/live_filter.js

Duplicated history
Replace vs push state in the offending code
When page first loads it is added in the browser history, when javascript loads it is then added to browser history hence the duplication.

[3074] Fixed dupe browser history

---

spec/features/form_sections/teacher_training_data/apply_applications_spec.rb

`pg_teaching_apprenticeship` and `apply application`
Removed `pg_teaching_apprenticeship` from `apply application` as it has its own distinct user journey and is covered [here](https://github.com/DFE-Digital/register-trainee-teacher-data/blob/main/spec/features/end_to_end/pg_teaching_apprenticeship_journey_spec.rb)
Flake introduce here
https://github.com/DFE-Digital/register-trainee-teachers/pull/1695

[xxxx] Removed pg_teaching_apprenticeship from apply applications specs

---

app/models/trainee.rb
spec/models/trainee/state_transitions_spec.rb

Potential fix fox https://sentry.io/organizations/dfe-bat/issues/2635933991
Often, if a `Dttp::RetreiveTrnJob` has been requeued, it will fail as the trainee has already transitioned to a `trn_received` state. This PR aims to make that job idempotent.
Do not raise an `Invalid Transition` exception when retrying `Dttp::RetreiveTrnJob`

Do not raise an Invalid Transition when attempting to receive_trn on an already trn_received trainee

---

db/data/20211102125813_reimport_apply_applications_with_course_uuid.rb

Some of the apply applications imported into register are missing the
course uuid that we added in recently. To ensure that we re-import these
applications, we want to trigger the import job by passing in the
`changed_since` parameter to the apply request.
The earliest changed_since/updated_at value found in our database is
Wed, 09 Dec 2020 14:23:24.000000000 UTC +00:00.
Hence this data migration will ensure that we fetch all applications
added/changed since.
Data migration to re-import all apply applications changed since 9th December 2020

[3107] Reimport apply applications changed since 09 Dec 2020 14:00

---

app/components/form_components/autocomplete/sort.js
app/helpers/degrees_helper.rb
app/webpacker/scripts/autocomplete_sort.spec.js
spec/helpers/degree_helper_spec.rb

https://trello.com/c/ugUIdcik/3104-multi-synonym-bug-in-autocomplete
- Pipe-separate synonyms so that they can be correctly pulled from the data-attribute in JS
- Require **all parts of _at least one_ synonym** to match before progressing onto calculating weights (previously it was reducing the array of synonym matches which didn't make sense)

[3104] Multi-synonym bug in autocomplete

---

app/components/route_indicator/view.rb
app/views/trainees/publish_course_details/edit.html.erb
config/locales/en.yml
spec/components/route_indicator/view_preview.rb
spec/components/route_indicator/view_spec.rb

https://trello.com/c/nYZYSq7v/3029-m-allow-route-change-on-apply-drafts
Clears courses and funding when route is changed, same as manual drafts
Alter route indicator component as per https://github.com/DFE-Digital/register-trainee-teachers-prototype/pull/381
Change manual option text for publish course flow but this isn't being used in the service currently? (bug?)
Create or view apply draft trainee. 
See that text changes on the route indicator inset text:
1)  When course picked
2) After course is cleared when the route is changed

[3029] Allow route change on apply drafts

---

app/components/status_tag/view.rb
app/controllers/trainees/award_recommendations_controller.rb
app/models/trainee.rb
db/data/20211102131145_fix_submission_ready_field.rb
spec/components/status_tag/view_spec.rb
spec/models/trainee_spec.rb

- https://trello.com/c/PHOyn4ok/3100-incomplete-badge-snags
A few snags around the incomplete badge work:
- Conditionally handle tracking completeness only for states waiting on provider action
- Don't show the badge for records considered final
- Fix up 225 records in prod and mark them as complete as per this cycle's requirements

[3100] Incomplete badge snags

---

app/jobs/dttp/queue_trainee_updates_job.rb
spec/jobs/dttp/queue_trainee_updates_job_spec.rb

Changed `queue_trainee_updates_job.rb` query to only fetch valid states. This is causing unnecessary errors in sidekiq as the original query is fetching drafts: The requested resource does not support http method 'PATCH'
https://www.register-trainee-teachers.education.gov.uk/system-admin/sidekiq/morgue/1635897736.6011858-d033ebe78bf0680bfdd12804

Remove draft from invalid states as they do not exist in DTTP.

---

app/components/application_record_card/view.html.erb
app/components/application_record_card/view.rb
app/components/record_details/view.rb
app/models/provider.rb
app/views/trainees/_results.html.erb
config/locales/en.yml
spec/components/application_record_card/view_preview.rb
spec/components/application_record_card/view_spec.rb
spec/components/record_details/view_preview.rb
spec/components/record_details/view_spec.rb
spec/models/provider_spec.rb

Showing provider name / provider name and code
Showing provider name for application record card
Showing provider name and code for record details
Any of the *`_as_system_admin`
https://register-pr-1705.london.cloudapps.digital/view_components/application_record_card/view
https://register-pr-1705.london.cloudapps.digital/view_components/record_details/view

[3117] Show provider name in record card and record when signed in as an admin

---

app/forms/schools/form.rb
config/locales/en.yml
spec/support/shared_examples/school_form_validations.rb

https://trello.com/c/bVoqgmQ4/3080-school-not-available-validation-issue
When error is thrown for both fields being selected, the query field is now highlighted in error

[3080] School not available validation bug

---

app/models/degree.rb
spec/forms/degrees_form_spec.rb
spec/models/degree_spec.rb

https://trello.com/c/X7QI3sDi/3105-sort-degrees-chronologically-when-importing-from-apply
- Add `default_scope` to `Degree` so that the UI renders degrees chronologically (oldest to newest)

[3105] Sort degrees chronologically using graduation year

---

app/controllers/trainees/check_details_controller.rb
app/controllers/trn_submissions_controller.rb
app/forms/submission_ready_form.rb
app/jobs/trainees/update_submission_readiness_job.rb
app/lib/bulk_import.rb
app/models/trainee.rb
config/locales/en.yml
db/data/20211105134900_fix_up_submission_ready.rb
lib/tasks/hpitt_bulk_submit.rake
spec/components/pages/trainees/check_details/view_preview.rb
spec/components/sections/view_preview.rb
spec/components/sections/view_spec.rb
spec/features/trainee_actions/submit_for_trn_spec.rb
spec/forms/submission_ready_form_spec.rb
spec/jobs/dttp/recommend_for_award_job_spec.rb
spec/jobs/dttp/register_for_trn_job_spec.rb
spec/jobs/dttp/retrieve_award_job_spec.rb
spec/jobs/dttp/retrieve_trn_job_spec.rb
spec/services/dttp/create_dormancy_spec.rb
spec/services/dttp/update_dormancy_spec.rb
spec/services/dttp/update_trainee_status_spec.rb

- https://trello.com/c/jbLUTBHD/3168-incomplete-records-that-are-submitted-cant-be-fixed-if-the-complete-checkbox-is-unchecked
This PR fixes a bug whereby non draft trainees would be marked as incomplete due to the `SubmissionReadyForm` returning `valid? => false` for these records. The change is to consider the progress of these records "completed" (business decision) so it returns true for the validity.
The `progress` jsonb field is only relevant to track the record progress for draft trainees so it DOES need to be considered for that state during draft workflows.
There's also a data migration to fix up non draft trainees in prod and I've renamed the form from `TrnSubmissionForm` to `SubmissionReadyForm` to better reflect the puropose

[3168] Incomplete records

---

app/components/user_card/view.html.erb
app/controllers/system_admin/users_controller.rb
app/policies/user_policy.rb
app/views/system_admin/users/edit.html.erb
config/locales/en.yml
config/routes/system_admin_routes.rb
spec/components/user_card/view_preview.rb
spec/factories/users.rb
spec/features/system_admin/users/creating_a_new_user_spec.rb
spec/features/system_admin/users/updating_a_user_spec.rb
spec/features/system_admin/users/viewing_users_spec.rb
spec/support/page_objects/providers/show.rb
spec/support/page_objects/users/edit.rb

Add ability to update a user's email from system-admin.
1. Login as Administrator
2. Find an edit link against any registered user and click on it.
3. Expect to be presented with a form to edit the email address. Make a change, and click "continue"
4. Assert that a success message is shown.

[3123] Add ability to update a user's email address

---

app/controllers/trainees_controller.rb
app/models/trainee_filter.rb
app/services/trainees/filter.rb
app/views/trainees/_filters.html.erb
config/locales/en.yml
spec/features/trainee_actions/filtering_trainees_spec.rb
spec/services/trainees/filter_spec.rb
spec/support/page_objects/trainees/index.rb

https://trello.com/c/VxEtBB7h/3119-m-add-filter-for-incomplete-records
- Add new filter section "Record completion" with checkboxes to filter "complete" or "incomplete" records
- Visit trainees index page
- Try the "complete" and "incomplete" options
- If you check both, then it returns all records

[3119] Add filter for complete/incomplete records

---

app/controllers/system_admin/dttp_users_controller.rb
app/views/system_admin/_provider_tab_nav.html.erb
app/views/system_admin/_tab_nav.html.erb
app/views/system_admin/dttp_providers/index.html.erb
app/views/system_admin/dttp_users/index.html.erb
app/views/system_admin/providers/index.html.erb
app/views/system_admin/providers/show.html.erb
app/views/system_admin/validation_errors/index.html.erb
config/routes/system_admin_routes.rb
spec/features/system_admin/dttp_providers/list_providers_spec.rb
spec/features/system_admin/providers/creating_a_new_provider_spec.rb
spec/features/system_admin/providers/editing_a_provider_spec.rb
spec/features/system_admin/providers/viewing_providers_spec.rb
spec/features/system_admin/users/creating_a_new_user_spec.rb
spec/features/system_admin/users/viewing_users_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/dttp_users/index.rb
spec/support/page_objects/providers/show.rb

https://trello.com/c/vBfdbZOT/3150-s-re-structure-providers-sub-tab-navigation
- Replace providers sub tab with a new version that lists "Registered users" and "DTTP users"
- Make sure your user record has the field `system_admin` set to `true`
- Visit the the `/system-admin/providers`
- Click on a provider
- You should see the follow screen:

[3150] Re-structure providers sub tab navigation

---

app/forms/diversities/disclosure_form.rb
db/data/20211111161328_fix_up_disability_disclosures.rb
spec/forms/diversities/disclosure_form_spec.rb

- https://trello.com/c/M4R3fohK/3186-confirm-reason-for-disability-disclosure-null-entries
- We need to set the `disability_disclosure` field to `disability_not_provided` if a trainee does not disclose diversity information
- Update the `DisclosuresForm` object to toggle this field based on the diversity disclosure value
- Add a data migration to backfill existing trainees in prod

[3186] Set disability disclosure for trainees who have not provided diversity info

---

app/components/record_details/view.rb
app/controllers/trainees/start_dates_controller.rb
spec/components/record_details/view_spec.rb
spec/features/form_sections/teacher_training_data/edit_trainee_start_date_spec.rb

Modifying which start date forms are rendered
- Redirect to `edit_trainee_start_status_path` if commencement date is blank
-  If commencement date is in the future don't render the change links for trainee start date on summary page
- Check that the change link is hidden from the summary page if the ITT date is in the future
- Check that the new form is rendered if the commencement date is blank. You can manually set this to blank on a registered trainee by navigating to a trainee and changing the URL to `trainees/{{slug}}/trainee-start-status/edit`

[3160] Modifying which start date forms are rendered

---

db/data/20211112120154_remove_duplicate_trainees.rb

https://trello.com/c/CizDlWU9/3199-remove-records
- Data migration to remove a trainee record (no longer in DTTP) and update 2 others with TRN values

[3199] Remove duplicate trainees

---

app/components/dynamic_back_link/view.rb
app/components/record_actions/view.rb
app/controllers/trainees/forbidden_deletes_controller.rb
app/controllers/trainees/start_date_verifications_controller.rb
app/controllers/trainees/start_statuses_controller.rb
app/forms/start_date_verification_form.rb
app/forms/trainee_forbidden_delete_form.rb
app/lib/page_tracker.rb
app/views/trainees/deferrals/show.html.erb
app/views/trainees/forbidden_deletes/show.html.erb
app/views/trainees/start_date_verifications/show.html.erb
app/views/trainees/start_statuses/edit.html.erb
app/views/trainees/withdrawals/show.html.erb
config/locales/en.yml
config/routes.rb
spec/features/trainee_actions/delete_trainee_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/trainees/delete_forbidden.rb
spec/support/page_objects/trainees/start_date_verification.rb

https://trello.com/c/NEhZ0PLw/3147-m-course-starts-in-the-past-no-trainee-start-date-delete
- New controller `Trainees::StartDateVerificationsController` with form object and views for the start date verification page
- New controller `Trainees::ForbiddenDeletesController` with form object and views for the delete forbidden page
- Modified `Trainees::StartStatusesController` so it can be used in the context of deleting a trainee
- Click on "Pending TRN" trainees
- Filter by "School direct"
- Click on a trainee and check if it has a "Delete" action. The seed data creates some trainees that can be deleted, but it's done on every other trainee, so you might have to click into the other trainees in the list to find a deletable record.
- Once you find a trainee that can be deleted, click …

[3147] Course starts in the past, no trainee start date — delete

---

config/locales/en.yml
db/service_updates.yml

The copy '...the trainee is employed or funded privately', which appears in the service updates content and on the lead and employing schools pages is ambiguous and not clear enough.
Changed the copy to '...the trainee is funded or employed privately'
Review copy changes in:
- service updates content
- employing schools content
- lead schools content

Change to service update content

---

app/components/confirm_publish_course/view.rb
app/components/course_details/view.rb
app/controllers/trainees/course_details_controller.rb
app/forms/concerns/commencement_date_helpers.rb
app/forms/trainee_form.rb
app/forms/trainee_start_date_form.rb
app/forms/trainee_start_status_form.rb
app/lib/training_route_manager.rb
app/models/trainee.rb
app/views/trainees/start_dates/edit.html.erb
config/initializers/training_routes.rb
config/locales/en.yml
spec/components/course_details/view_spec.rb
spec/features/form_sections/teacher_training_data/edit_course_details_spec.rb
spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb
spec/features/form_sections/teacher_training_data/edit_trainee_start_date_spec.rb
spec/features/form_sections/teacher_training_data/edit_trainee_start_status_spec.rb
spec/forms/course_details_form_spec.rb
spec/forms/trainee_start_date_form_spec.rb
spec/forms/trainee_start_status_form_spec.rb
spec/lib/training_route_manager_spec.rb
spec/support/features/course_details_steps.rb
spec/support/page_objects/trainees/course_details.rb

Adding validation to the start date forms and change course to ITT 
- commencement date cannot be more then 10 years ago
- ~commencement date cannot be before course start date~ **This PR has been amended to remove this validation, based on an ongoing discussion with @ralph-hawkins**
- commencement date cannot be after the course end date
- Remove the constant ITT_TRAINING_ROUTES as this is now redundant
- Change course to ITT 
- Navigate to both start date forms and enter a range of valid and invalid dates as per the changes detailed above and check that we get the expected behaviour. 
- Check that `trainee-start-date/edit` now matches the prototype (screenshot in the Trello ticket).

[3182] Add course start date validations to both start date forms

---

app/components/record_actions/view.rb
app/controllers/trainees/forbidden_withdrawals_controller.rb
app/controllers/trainees/start_date_verifications_controller.rb
app/controllers/trainees/start_statuses_controller.rb
app/forms/start_date_verification_form.rb
app/views/trainees/forbidden_withdrawals/show.html.erb
app/views/trainees/start_date_verifications/show.html.erb
app/views/trainees/start_statuses/edit.html.erb
config/locales/en.yml
config/routes.rb
spec/components/record_actions/view_spec.rb
spec/features/trainee_actions/withdraw_trainee_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/trainees/withdrawal_forbidden.rb

https://trello.com/c/Neir6RLo/3149-m-course-starts-in-the-past-no-trainee-start-date-withdraw
* New withdraw flow for if trainee has started course but trainee start date is not present. If course start date is in future, withdraw link is hidden. If trainee start date is present, trainee is taken straight to withdrawal page. 
* Modified the StartDateVerificationsController to decide whether withdrawal or deletion
* If user says that they haven't started course and the course starts date is in past they are taken to withdrawal forbidden page
Select a non-draft trainee e.g pending trn and make sure it has a 'withdraw' link and go through the withdrawal flow. You should be able to do the routes highlighted in the attachment on the ticket above.

[3149] Course starts in the past, no trainee start date - withdraw

---

app/components/deferral_details/view.html.erb
app/components/deferral_details/view.rb
app/components/record_details/trainee_start_date.rb
app/components/record_details/view.rb
app/components/reinstatement_details/view.html.erb
app/components/reinstatement_details/view.rb
app/controllers/trainees/confirm_deferrals_controller.rb
app/controllers/trainees/confirm_reinstatements_controller.rb
app/controllers/trainees/deferrals_controller.rb
app/controllers/trainees/reinstatements_controller.rb
app/forms/reinstatement_form.rb
app/lib/dttp/params/dormancy.rb
app/models/trainee.rb
app/views/trainees/start_statuses/edit.html.erb
config/locales/en.yml
spec/components/deferral_details/view_preview.rb
spec/components/deferral_details/view_spec.rb
spec/components/record_details/view_spec.rb
spec/features/trainee_actions/defer_trainee_spec.rb
spec/forms/reinstatement_form_spec.rb

- https://trello.com/c/WjPPrUDt/3146-m-course-starts-in-the-future-defer
- https://trello.com/c/qxWQ8yi5/3164-s-reinstating-a-deferred-trainee
- Introduce a new defer flow if the course starts in the future
- Trainee can be deferred in the scenario above but date options aren't shown to provider
- If reinstated, the trainee's `commencement_date` is marked the same as the `reinstate_date`
This flow hinges on the trainee's commencement date not being set as the course start date is in the future. There are tickets removing capturing this from the draft sections and after the trn has been requested. In that scenario, the commencement date is only requested if the course start date is on the current day or in the past. Therefore this field will show as missing data (spoken with Ed) when the …

[3146] Handle course starting in the future for deferring

---

config/initializers/sidekiq.rb

Logit filling up because of BigQuery
Set sidekiq log level to WARN
This will avoid basic start/stop log messages. They are already provided by ActiveJobs.
Same set up as Find and TT API

[xxx] Set sidekiq log level to WARN

---

app/models/trainee.rb
app/views/trainees/withdrawals/show.html.erb
config/locales/en.yml
spec/features/trainee_actions/withdraw_trainee_spec.rb
spec/models/trainee_spec.rb
spec/support/page_objects/sections/duplicate_notice.rb
spec/support/page_objects/trainees/withdrawal.rb

https://trello.com/c/L7Ml1NN5/3227-add-content-to-warn-users-not-to-withdraw-duplicate-records
- Add duplicate notice to withdrawal page
- Visit a non-draft trainee
- Contact me so I can create a duplicate
- Refresh page
- Duplicate record notice should appear

[3227] Add duplicate notice to withdrawal page

---

app/controllers/trainees/publish_course_details_controller.rb
app/jobs/apply_api/import_applications_job.rb
app/jobs/trainees/create_from_apply_job.rb
app/services/apply_api/retrieve_applications.rb
config/settings.yml
db/data/20211123145536_create_job_to_import_2022_apply_applications.rb
spec/factories/apply_applications.rb
spec/factories/courses.rb
spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb
spec/jobs/apply_api/import_applications_job_spec.rb
spec/jobs/trainees/create_trainees_from_apply_job_spec.rb
spec/services/apply_api/retrieve_applications_spec.rb
spec/services/teacher_training_api/retrieve_courses_spec.rb

https://trello.com/c/u7A7YdxV/3233-m-start-syncing-2022-courses-and-applications-from-publish
- Add filter to published courses so that it ignores 2022 courses
- Add new config to allow the Apply import job to fetch 2021 and 2022 applications but only create trainees for 2021 for the moment
- Data migration to kick off the 2022 Apply application import
- This is low-level backend preparation.

[3233] Start syncing 2022 courses and applications from publish

---

app/components/notice_banner/script.js
app/components/notice_banner/style.scss
app/components/notice_banner/view.html.erb
app/components/notice_banner/view.rb
app/controllers/trainees/personal_details_controller.rb
app/controllers/trainees_controller.rb
app/forms/submissions/base_validator.rb
app/forms/submissions/missing_data_validator.rb
app/helpers/course_details_helper.rb
app/helpers/degrees_helper.rb
app/helpers/task_list_helper.rb
app/lib/bulk_import.rb
app/view_objects/missing_data_banner_view.rb
app/views/layouts/trainee_record.html.erb
config/locales/en.yml
spec/components/notice_banner/view_preview.rb
spec/factories/trainees.rb
spec/forms/submissions/missing_data_validator_spec.rb
spec/view_objects/missing_data_banner_view_spec.rb

https://trello.com/c/905rEvfQ/3152-l-add-outstanding-actions-to-trainees-missing-fields-banner
- Adds a generic 'dumb' `NoticeBanner` component which renders and heading and some content with the correct stying, if content is present.
- Adds a mechanism to `Submissions::BaseValidator` by which extra validators can be added to its subclasses. This is needed because we now have a form `TraineeStartDateForm` which needs to be validated for determining whether a trainee has missing fields (and eventually for QTS recommendation) BUT does not need to be validated for TRN in the `TrnValidator`.
- Adds the extra validator to `MissingDataValidator`.
- Adds a new `MissingDataBannerView` which transforms the missing fields for a trainee into a bulleted list of links, linking to the page containing …

[3152] Add missing fields banner to registered trainees

---

app/models/academic_cycle.rb
docs/adr/0006-academic-cycles.md
spec/factories/academic_cycles.rb
spec/models/academic_cycle_spec.rb

- https://trello.com/b/BBEuhbHM/register-sprint-board
We decided to keep this as a soft association with no foreign_key since the trainee's start date can change or end up in another cycle different to the original course details. We'll be able to query the cycle by just passing in dates.
- "associate" trainees to academic cycles based on whether the `commencement_date` or `course_start_date` is available
- add ADR

[3235] Associate trainees with academic cycles

---

app/controllers/trainees/start_date_verifications_controller.rb
app/controllers/trainees_controller.rb
config/routes.rb
spec/features/trainee_actions/delete_trainee_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/not_found.rb

- https://trello.com/c/BtsPLd5D/3262-snag-deleting-a-trainee-itt-start-date-is-in-the-future
- https://trello.com/c/i2eL7YPt/3264-snag-deleting-a-trainee-redirecting-away-from-trainee-show-page
- If a course starts in the future, redirect straight to the confirm delete path when deleting a trainee
- Redirect to 404 page if you attempt to view a deleted trainee
- Create a trainee with a course starting in the future
- Delete the trainee (confirm you're taken straight to the confirm delete page)
- Attempt to return to the trainee slug with `trainees/{slug}` and assert you're redirected to the 404 page

[3262] & [3264] Fix snags in delete flows

---

app/views/trainees/forbidden_withdrawals/show.html.erb
app/views/trainees/start_date_verifications/show.html.erb
config/locales/en.yml
spec/components/record_actions/view_spec.rb

https://trello.com/c/HPMGB4uA/3270-snag-you-cannot-withdraw-this-trainee-page-content-update
https://trello.com/c/QvDbu51Q/3265-snag-deleting-a-trainee-you-cannot-delete-this-record-content-update
https://trello.com/c/NN1wWZs1/3260-snag-record-action-bar-trainee-status-content-update
Updates content to match prototype on following pages:
- `trainees/{slug}/withdrawal-forbidden`
- `trainees/{slug}/delete-forbidden`
- On `trainees/{slug}` record status bar for trainees who are pending TRN and deferred (record -> trainee)
Check the content against the prototype.

[3270] [3265] [3260] General content tweaks

---

app/components/record_actions/view.html.erb
app/components/record_actions/view.rb
app/controllers/trainees_controller.rb
app/views/trainees/show.html.erb
config/locales/en.yml
spec/components/record_actions/view_preview.rb
spec/components/record_actions/view_spec.rb
spec/factories/trainees.rb

https://trello.com/c/10ILGPQN/3241-m-add-outstanding-actions-to-trainees-trainee-status-inset-text
1. If a trainee is missing data, reflect that in the record actions inset text "This trainee requires additional details":
2. If their course has not started yet, reflect that instead "The trainee's ITT starts on...":
For a trainee missing their start date, and their ITT has started:
https://register-pr-1755.london.cloudapps.digital/trainees/icuJGW9pdMB5DdsJiaGWUXCu
For a trainee missing their start date, and their ITT starts in the future:
https://register-pr-1755.london.cloudapps.digital/trainees/FPReEdyCLXPqt3vP64CpvEYc

[3241] Add outstanding actions content to trainee status inset text

---

app/components/course_details/view.rb
app/components/deferral_details/view.rb
app/components/record_details/trainee_start_date.rb
app/components/reinstatement_details/view.rb
app/controllers/trainees/start_statuses_controller.rb
app/view_objects/missing_data_banner_view.rb
app/views/trainees/course_details/edit.html.erb
app/views/trainees/forbidden_deletes/show.html.erb
app/views/trainees/itt_start_dates/edit.html.erb
app/views/trainees/start_date_verifications/show.html.erb
app/views/trainees/start_dates/edit.html.erb
app/views/trainees/start_statuses/edit.html.erb
config/locales/en.yml
spec/components/deferral_details/view_spec.rb
spec/components/record_details/view_spec.rb
spec/controllers/trainees/start_statuses_controller_spec.rb
spec/features/form_sections/teacher_training_data/edit_trainee_start_status_spec.rb
spec/features/trainee_actions/defer_trainee_spec.rb

https://trello.com/c/hX8pkaM4/3266-snag-deleting-withdrawing-deferring-a-trainee-start-date-validations
- Fix `Trainees::StartStatusesController#update` so that it saves the form which will trigger the validations. [2943]
- Fixed the the other specs because they passed previously only because the requests were not authorised. [2943]
- Deferring a trainee - error message content change [3268]
- HTML abbreviation tag for 'ITT' [3261]
- Visit a non-draft trainee
- Use the console to nullify `commencement_date`
- Click on the "Delete" or "Withdraw" link
- Choose "Yes, they started"
- Play around with the start status form - all the expected behaviour should be there since it was already working in a non-draft context.
- Visit a non-draft trainee
- Click defer
- Submit form without choosing an …

[2943][3261][3261] Snag fixes

---

app/components/record_actions/view.rb
spec/components/record_actions/view_spec.rb

If a deferred trainee did not start their ITT, they cannot be withdrawn.
Add a condition to withdraw_allowed? to guard against trainee not having started the course.
Test out in review app

hide withdraw link if trainee is deffered without starting

---

db/data/20211129143641_remove_trainee_records.rb

https://trello.com/c/pIPfv1SW/3274-remove-duplicate-trainee-records-on-register
These trainees were duplicated in CRM (subsequently remove). The Register versions should never have been created as they already have an older version on the DTTP CRM.
- Data migration

[3274] Remove trainees

---

app/lib/training_route_manager.rb
config/initializers/training_routes.rb
lib/tasks/example_data.rake
spec/factories/trainees.rb

Define two new constants LEAD_SCHOOL_ROUTES and EMPLOYING_SCHOOL_ROUTES
and use them in the example_data.rake task, to ensure consistent lead
and employing school assignment.
Also, ensure that the commencement_date (trainee start date) is
generated between the itt/course start and course end dates.
:shipit:

[3277] Improve example data generation

---

app/forms/concerns/commencement_date_helpers.rb
app/views/trainees/start_statuses/edit.html.erb
app/webpacker/styles/_govuk_overrides.scss
config/locales/en.yml
spec/forms/trainee_start_date_form_spec.rb
spec/forms/trainee_start_status_form_spec.rb

- https://trello.com/c/Yo6JA4jK/3258-snag-error-summaries-date-wrapping
- Use a custom presenter given to the GOVUK form builder to customise format of error messages as suggested by @peteryates.
Note - This is only half fixed. There is currently an issue with the formbuilder not rendering safe html markup from translation files for individual fields (see image) Have raised the issue https://github.com/DFE-Digital/govuk-formbuilder/issues/328. If that issue can get resolved then we can merge this in after bumping the formbuilder otherwise we may have to consider alternative copy where the text does not wrap in the interim.

[3258] Fix date wrapping

---

app/controllers/trainees/course_years_controller.rb
app/controllers/trainees/publish_course_details_controller.rb
app/forms/course_education_phase_form.rb
app/forms/course_years_form.rb
app/forms/publish_course_details_form.rb
app/lib/page_tracker.rb
app/views/trainees/course_years/edit.html.erb
app/views/trainees/publish_course_details/edit.html.erb
config/locales/en.yml
config/routes.rb
config/settings.yml
lib/tasks/example_data.rake
spec/forms/course_years_form_spec.rb

https://trello.com/c/6me29388/3234-l-course-years-ui
* Change course year page added
* Publish course details form courses are filtered based on the `year` query param
* `@course_year` defaults to `@trainee.published_course.recruitment_cycle_year` if available otherwise to `Settings.current_default_course_year`.
* If `year` param is invalid, redirected to change course year page.
*  Add provider-led (postgrad) trainee, go to Course details section.

[3234] Course years UI

---

.github/workflows/build.yml
.github/workflows/deploy.yml
Makefile
config/environments/dttpimport.rb
config/settings/dttpimport.yml
terraform/workspace-variables/app_config.yml
terraform/workspace-variables/dttpimport.tfvars.json
terraform/workspace-variables/dttpimport_backend.tfvars

We need a new production like environment to test import from DTTP
Add DTTPIMPORT configuration in app, terraform, makefile, pipeline
Deployed app: https://register-dttpimport.london.cloudapps.digital/
Pipeline run: https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/1535998439

Create dttpimport test environment

---

db/service_updates.yml

The census link should be on its own and not wrapped on to the end of the para. 
Make the census link stand-alone underneath the copy.

fix link issue

---

app/views/trainees/publish_course_details/edit.html.erb

We use the form builder to render a list of courses. When that form goes into an error state the link between the label and the radio is broken.
This is happening when all radio buttons are set to `link_errors: true` the form builder names them all identically so every label in the list is effectively linked to the first radio button.
Removing `link_errors: true` on all radios breaks the link from the error summary.
We want both the error summary link and the label behaviour 🤔
We do have this working on the training route page but on that page the `Assessment only` radio is rendered individually with `link_errors: true` and the rest are then rendered in a loop without that attribute.
So... 🥁 Make only the first radio button `link_errors: true` on the course list page and the rest false. …

[3326] Fix course list label linking

---

db/scripts/sanitise.sql

This script is used to create a sanitised version of the DB. We don't
want to continue storing sensitive trainee data from DTTP.
Null the `response` columns on `dttp_trainees`, `dttp_placement_assignments` and `dttp_degree_qualifications`
🚢

[xxx] Update sanitise.sql to wipe DTTP sync tables

---

config/initializers/academic_cycles.rb
config/initializers/training_routes.rb
db/data/20211207165346_seed_academic_cycles_for_2021_2022.rb

Add the 2022 funding rules with a migration to implement them.
https://trello.com/c/livHHuKM/3240-m-add-2022-funding-rules
Update the new funding rules. Note: there is no such subject grouping currently as 'Ancient languages' and so funding rules couldnt be added.
Check the rules are correct against: https://www.gov.uk/government/publications/funding-initial-teacher-training-itt/funding-initial-teacher-training-itt-academic-year-2022-to-2023

[3240] Add 2022 funding rules

---

app/lib/dttp/params/placement_assignment.rb
app/lib/funding_manager.rb
app/models/academic_cycle.rb
app/models/funding_method.rb
app/models/trainee.rb
db/seeds.rb
spec/components/funding/view_spec.rb
spec/factories/funding_methods.rb
spec/features/form_sections/teacher_training_data/edit_training_initiative_spec.rb
spec/forms/funding/form_validator_spec.rb
spec/lib/dttp/params/placement_assignment_spec.rb
spec/lib/funding_manager_spec.rb
spec/models/funding_method_spec.rb
spec/support/shared_examples/rendering_the_funding_section.rb

https://trello.com/c/eeflRypa/3239-m-choose-which-funding-rules-to-use-based-on-trainee-academic-cycle
- Add `Trainee#academic_cycle`
- Update `FundingManager` to scope funding methods to academic cycle
- Update `Dttp::Params::PlacementAssignment` to not send funding information if the course starts in 2022
The card suggested the Early Years can't have funding info added until the course details are completed (this is existing behaviour for other routes but not currently EY). But after looking into this, it appears that for Early Years, the bursary amount does not come from the database, but `FundingManager::BURSARY_TIER_AMOUNTS`.
The seeds file now associates the funding methods with the current academic cycle: 2021-2022.
- Create a trainee that requires funding information (try various …

[3239] Choose which funding rules to use based on trainee academic cycle

---

db/migrate/20211208144036_remove_null_constraint_from_dttp_placement_assignments.rb
db/schema.rb

Remove null constraint from contact_dttp_id column on dttp_placement_assignments table
When testing the sync, there were dttp_placement_assignment records with no contact_dttp_id.
- Migration to remove null constraint.
🚢

[xxx] Remove null constraint from `dttp_placement_assignments`

---

app/components/form_components/autocomplete/sort/calculateWeight.js
app/components/form_components/autocomplete/sort/clean.js
app/components/form_components/autocomplete/sort/index.js
app/components/form_components/autocomplete/sort/stop_words.js
app/webpacker/scripts/autocomplete/calculateWeight.spec.js
app/webpacker/scripts/autocomplete/sort.spec.js
app/webpacker/scripts/autocomplete/stop_words.spec.js

https://trello.com/c/clMYnXgB/3297-m-autocomplete-add-stop-words-normalisation-support-to-autocomplete
- Extended the autocomplete `clean` function to remove stop words
- Pick an autocomplete field (e.g. degree institutions)
- Try entering a search term with a stop word
- The search results will ignore the stop word

[3297] Add stop words support to autocomplete

---

app/forms/training_details_form.rb
app/views/trainees/training_details/_duplicate_error.html.erb
app/views/trainees/training_details/edit.html.erb
app/webpacker/styles/application.scss
config/locales/en.yml
spec/forms/training_details_form_spec.rb

https://trello.com/c/JhlzfNTy/3282-m-prevent-duplicate-trainee-ids
* Added uniqueness validation to `trainee_id` scoped to `provider_id`
* Add partial for the custom error message for duplicate trainee_id
* Copy trainee_id from an existing record
* Add new trainee, set trainee_id and try to submit Trainee ID form

[3282] Prevent duplicate trainee IDs

---

app/lib/dttp/parsers/placement_assignment.rb
db/migrate/20211209144401_add_extra_columns_to_dttp_placement_assignment.rb
db/schema.rb
spec/factories/dttp/api_placement_assignment.rb
spec/factories/dttp/placement_assignments.rb
spec/lib/dttp/parsers/placement_assignment_spec.rb

https://trello.com/c/opWyzYH6/3350-pull-more-data-out-of-dttp-sync-into-db-columns-for-analysis
Pull out provider_dttp_id, academic_year, trainee_status, programme_start_date
and programme_end_date from the dttp_placement_assignment response.
This is to aid analysis of the raw data e.g. "how many active trainees are there in each year?"
We will need to re-run `Dttp::SyncPlacementAssignmentsJob` after this is added.

[xxx] Extend parsing of dttp_placement_assignments during sync

---

app/controllers/base_trainee_controller.rb
app/controllers/drafts_controller.rb
app/controllers/trainees_controller.rb
app/helpers/navigation_helper.rb
app/helpers/search_helper.rb
app/views/drafts/index.html.erb
app/views/layouts/application.html.erb
app/views/trainees/_action_bar.html.erb
app/views/trainees/_filters.html.erb
app/views/trainees/_results.html.erb
app/views/trainees/_search_results.html.erb
app/views/trainees/_selected_filters.html.erb
app/webpacker/scripts/live_filter.js
app/webpacker/scripts/live_filter.spec.js
config/locales/en.yml
config/routes.rb

- https://trello.com/c/xmrQ8Nzt/3310-l-draft-records-filters
- https://trello.com/c/xmrQ8Nzt/3310-l-draft-records-filters
- Create a sep. page to split draft trainees into their own view
- Create a base trainee controller to be shared between the registered and draft ones
- Clean up mix of instance_vars and helper methods to all just be helper methods lazily invoked from the view, organised into a const so we know which is used where
- Wire up filters for drafts searching
https://register-pr-1792.london.cloudapps.digital/drafts
Test searching and filtering works correctly for the drafts page (and also the trainees page for regressions?)
Notes:
- This page is not linked to at the moment
- The final page may live within `trainees/drafts` and will be a part of a bigger refactor of the routes …

[3283] Build draft records page

---

app/services/exports/trainee_search_data.rb
spec/services/exports/trainee_search_data_spec.rb

Where funding isn't available for a trainee / their course, we should show `not applicable` in the export.
Add not available option to conditional in export.

[3299] Show not available in the export if funding not available

---

spec/models/academic_cycle_spec.rb

Fixes https://github.com/DFE-Digital/register-trainee-teachers/runs/4470307984?check_suite_focus=true, which seems to be a flake.
There doesn't seem to be a consistent way of reproducing it, but running the whole suite seems to trigger it if you are lucky.

Use match array instead of eq

---

app/components/form_components/autocomplete/script.js
app/helpers/degrees_helper.rb
app/lib/dttp/code_sets/degree_types.rb
db/data/20211210162725_change_higher_degree_to_higher_degree_or_equivalent.rb

[3295-substitution-phrases-for-school-search](https://trello.com/c/MBxMhgWo/3296-improve-degree-type-option-for-higher-degree)
- Changed "Higher Degree" to "Higher degree or equivalent"
- Data migration to change existing degrees with "Higher Degree" to "Higher degree or equivalent"
- Visit degree form page
- Type "postgrad" in degree type field
- Hint text should be displayed underneath "Higher Degree"

[3296] Improve degree type option for `Higher Degree`

---

app/forms/personal_details_form.rb
config/locales/en.yml
spec/forms/personal_details_form_spec.rb

https://trello.com/c/rjoQD1ep/3362-add-date-of-birth-validation
We've had an issue whereby a trainee was entered with a Medieval birthday - unsurprisingly the TRN request was rejected.
This PR adds an extra past-date validation.
Try to create a trainee with a birthdate more than 100 years ago. It should fail.

[3362] Validate that date of birth is not too long ago

---

app/services/trainees/create_from_dttp.rb
db/migrate/20211216145323_add_created_from_dttp_to_trainees.rb
db/schema.rb
spec/services/trainees/create_from_dttp_spec.rb

We want to be able to distinguish trainees created via the import from DTTP from trainees created by users in Register.
This will help us running test runs of the import, and also may be used in the future (different UI? blocking updates to DTTP?)
Add boolean field `created_from_dttp` to trainees so we can easily distinguish
them from trainees created by users on Register.
🚢

[xxx] Add `created_from_dttp` to trainees

---

app/services/trainees/create_from_dttp.rb
spec/services/trainees/create_from_dttp_spec.rb
spec/services/trainees/filter_spec.rb

We are [already flagging](https://github.com/DFE-Digital/register-trainee-teachers/blob/4e65e70c7657312644e116e320c9a77b93f3b496/app/services/trainees/create_from_dttp.rb#L34-L37) for cases when we do not recognise the initiative.
This PR completes initiative handling for when no information is available
:shipit:

[3406] Map trainees not on any initiatives

---

app/models/dttp/trainee.rb
app/services/trainees/create_from_dttp.rb
spec/factories/dttp/api_trainee.rb
spec/services/trainees/create_from_dttp_spec.rb

https://trello.com/c/0OczNMS6/3319-investigate-trainees-with-no-addresses-international-addresses
TRN's are set to 999999999 if they never received a TRN for some reason. We think this would be because they didn't start the course. If that's the case, the trainee would be skipped over since we do not map that "DID_NOT_START" status.
Trainee records can be merged into other (more complete) records in DTTP. Don't import these ones.
- Don't set the our trainee's TRN to an invalid one from DTTP.
- Don't try to import merged trainees
* Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' …

[3319] Handle when the trainee is merged or has an invalid TRN

---

app/models/dttp/trainee.rb
app/services/trainees/create_from_dttp.rb
spec/services/trainees/create_from_dttp_spec.rb

https://trello.com/c/0OczNMS6/3319-investigate-trainees-with-no-addresses-international-addresses
- Set the locale_code to uk if the country is explicitly set to a UK country OR postcode is a valid UK postcode
- Set the locale_code to non_uk if the country is present and not in the UK country life
- Otherwise, set nothing.

[3319] Improve handling of addresses

---

app/services/trainees/create_from_dttp.rb
spec/factories/dttp/api_trainee.rb

https://trello.com/c/a1Rww7Je/3412-investigate-21-22-trainees-in-state-nonimportablemissingstate
All dttp_trainees with the state `non_importable_missing_state` were actually QTS Awarded trainees.
This PR fixes the syntax in the case statement so that trainees with the `AWARDED_QTS` state are correctly mapped.
🚢 

[3416] Fix trainee_status method so that AWARDED_QTS trainees are correctly mapped

---

app/lib/dttp/code_sets/degree_types.rb
app/lib/dttp/code_sets/institutions.rb
app/models/dttp/degree_qualification.rb
app/services/degrees/map_from_dttp.rb
spec/services/degrees/map_from_dttp_spec.rb

https://trello.com/c/mhCEJYII/3416-investigate-handle-un-imported-degrees-21-22
Looking at the un-imported degrees from 21/22 the following issues were unearthed:
**Things I haven't solved because we can't immediately save the degree**
- No subject
- No institution
- No end date and/or no start date
**Things I have solved:**
- Missing mapping for degree type "BA (Hons) education" (cf695652-c197-e711-80d8-005056ac45bb)
**Added in an inactive mapping which is searched after the active one. Inactive mappings don't appear in the UI**
- Missing mapping for degree type "BSc (Hons) with intercalated PGCE" (d7695652-c197-e711-80d8-005056ac45bb)
**Added in an inactive mapping as above**
- International degrees with no dfe_name
**Fell back on degree_type when this is not present**
- Unmapped …

[3416] Investigate and handle un-imported degrees 21/22

---

app/lib/dttp/code_sets/training_initiatives.rb
app/services/trainees/create_from_dttp.rb
spec/services/trainees/create_from_dttp_spec.rb

https://trello.com/c/2fus5V0x/3413-investigate-21-22-trainees-in-state-nonimportablemissinginitiative
If a trainees is on the "Additional ITT place for PE with a priority subject" initiative, it actually means they're on PE with Ebacc. So set our ebacc field to true for these trainees and import them with no initiative.
The other missing initiative was "Primary mathematics specialism" but these needs more analysis https://trello.com/c/ceGyQHVL/2621-investigate-primary-with-mathematics-and-specialist-teaching so we'll continue skipping these trainees.
* Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to …

[3412] Handle trainees on an EBACC initiative

---

terraform/workspace-variables/production.tfvars.json

Workers seem to crash under some of our nightly jobs.
Double memory allocation from 512 to 1GB

Increase worker memory

---

app/components/status_tag/view.rb
app/controllers/pages_controller.rb
app/controllers/trainees_controller.rb
app/helpers/navigation_helper.rb
app/helpers/trainee_helper.rb
app/view_objects/home_view.rb
app/views/drafts/index.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/trainees/_filters.html.erb
app/views/trainees/_results.html.erb
app/views/trainees/check_details/show.html.erb
app/views/trainees/index.html.erb
app/views/trainees/new.html.erb
app/views/trainees/review_drafts/show.html.erb
config/locales/en.yml
db/service_updates.yml
spec/features/trainee_actions/filtering_trainees_spec.rb
spec/features/trainee_actions/submit_for_trn_spec.rb
spec/features/trainee_actions/viewing_an_existing_trainee_spec.rb
spec/helpers/trainee_helper_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/trainees/index.rb

- https://trello.com/c/wcIowvJW/3311-s-enable-draft-record-page
- Render the drafts page in the main nav bar
- Update links on the homepage 
- Remove draft sets from registered trainees results
- Fix tests
Have a play with the review app

[3311] Enable draft records page

---

app/models/dttp/trainee.rb
app/services/trainees/create_from_dttp.rb
config/analytics.yml
db/migrate/20220104113614_add_hesa_id_to_trainees.rb
db/schema.rb
spec/factories/dttp/api_trainee.rb
spec/services/trainees/create_from_dttp_spec.rb

https://trello.com/c/9o6CJJ7d/3405-link-the-trainees-created-from-hesa-records-back-to-hesa
- Add a new field `hesa_id` to trainees
- Populate this field when we create Register trainees from DTTP
- `hesa_id` added to the whitelist.

[3405] Add `hesa_id` field to trainees

---

lib/tasks/example_data.rake

https://trello.com/c/LciKfTwy/3451-fix-seed-data-rake-task
- Add require statement to load missing `current_recruitment_cycle_year`
- Run `rake db:reset && rake db:seed && rake example_data:generate`

[3451] Fix seed data rake task

---

app/lib/dttp/code_sets/reasons_for_leaving_course.rb

Add dttp entity ids for `DID_NOT_PASS_ASSESSMENT` and `DID_NOT_PASS_EXAMS`
:shipit:

[3409] Add withdrawal reason entity ids

---

app/lib/dttp/code_sets/degree_types.rb
app/lib/dttp/code_sets/institutions.rb
app/models/dttp/degree_qualification.rb
app/services/degrees/create_from_dttp.rb
app/services/degrees/map_from_dttp.rb
spec/services/degrees/create_from_dttp_spec.rb
spec/services/degrees/map_from_dttp_spec.rb

We failed to import a third of degrees. This was mainly due to degrees missing fields in DTTP.
https://trello.com/c/xNpaH7r4/3447-investigate-handle-missing-degrees-from-recent-21-22-trainee-import
1. If a degree is missing a field (i.e. institution/country/type/subject is NULL) don't skip importing it. This more accurately reflects the data in DTTP and the user is presented with a missing data prompt:
2. If a degrees has an unmapped field (i.e. institution/country/type/subject is NOT NULL but we don't have it in Register) skip importing it and flag the reason. This is the same as we do for DTTP trainees and will allow us to add missing mappings as we go back in time.
3. Add missing mappings for degree types, but don't surface them in the UI.
4. Add some missing institutions - these are …

[3447] Handle missing degrees from recent 21/22 trainee test import

---

app/lib/dttp/code_sets/academic_years.rb
app/lib/dttp/params/placement_assignment.rb
app/models/dttp/trainee.rb
app/services/trainees/create_from_dttp.rb
spec/factories/dttp/placement_assignments.rb
spec/lib/dttp/params/placement_assignment_spec.rb
spec/services/trainees/create_from_dttp_spec.rb

Adding this codeset in will enable us to refine records imported from dttp by matching them to the correct academic year. Currently, we are fetching based on the `programme_start_date` attribute, which in some cases may be missing against a trainee's placement assignment.
1. Add `Dttp::CodeSets::AcademicYears`, which contains all known entity ids.
2. Use this codeset to set the sort order for placement assignments, as opposed to `programme_start_date`.
One bit that stands out: There are [two dttp academic years for 2008/09](https://github.com/DFE-Digital/register-trainee-teachers/compare/3403-investigate-handle-dttptrainees-with-missing-programmestartdate?expand=1#diff-2e20301c1132fe4438b19737319d8cb3e70e28bffe0f0d780d1d5477346ba301R25-R26), both seem to be in use. That said, it doesn't …

[3403] Add AcademicYears codeset from DTTP

---

app/lib/dttp/parsers/contact.rb
db/migrate/20220105173543_add_status_to_dttp_trainees.rb
db/schema.rb
spec/lib/dttp/parsers/contact_spec.rb

We pull out the trainee status on the placement assignment, but not from the trainee.
Extract the status from the dttp trainee and store it in a separate column. This will make querying and analysis easier.
Yes, but we don't send the dttp_trainee entity to BigQuery.

[xxx] Pull out trainee status into separate column on dttp_trainees

---

app/components/form_components/autocomplete/script.js
app/webpacker/scripts/autocomplete/stop_words.spec.js
app/webpacker/scripts/live_filter.js
app/webpacker/scripts/live_filter.spec.js

https://trello.com/c/90z3HP6Q/3340-empty-item-shown-in-autocomplete
- Update autocomplete to not show results if the query string only has spaces 
- Visit a UK degree form page
- Enter multiple spaces into "Awarding institution"
- It should display "No results found"

[3340] Fix empty item shown in autocomplete

---

config/locales/en.yml

Fixes this [sentry exception](https://sentry.io/organizations/dfe-bat/issues/2913413146/?environment=dttpimport&project=5552118&query=is%3Aunresolved).
Add the relevant bits to the locale.yml file.

Enable showing address_line_one to missing data banner

---

app/lib/dttp/code_sets/degree_types.rb
db/data/20220107171921_update_ba_education_degrees_in_dttp.rb

https://trello.com/c/Pq2pV4Ym/3465-investigate-degrees-not-imported-due-to-missing-degreetype
- All degrees marked with `non_importable_missing_type` were due to one missing DTTP ID - for "BA/Education".
- We have "BA/Education" BUT with the wrong DTTP ID 🤦‍♀️ 
- This has always been wrong - it sends "BTech/Education" to DTTP
This PR:
- Update the entity ID in the codeset
- Adds a data migration to update affect trainees in DTTP

[3465] Update the mapping for BA/Education

---

spec/support/date_helpers.rb

Fixes a typo in a spec helper from 10/1 to 1/10 (academic year start date) which breaks our test suite from today.

Use 1st October as academic year start date

---

app/components/withdrawal_details/view.html.erb
app/components/withdrawal_details/view.rb
config/locales/en.yml
spec/components/withdrawal_details/view_spec.rb

For clarity (and consistency with deferral) we should show the user the commencement date when the user withdraws a trainee and allow them to change it
Add commencement date to withdraw flow with change link

show start date when trainee withdraws

---

app/models/trainee.rb
app/services/trainees/create_from_dttp.rb
spec/models/trainee_spec.rb
spec/services/trainees/create_from_dttp_spec.rb

In the 21/22 cycle we addded the HPITT trainees under a single Teach First SCITT.
However, in previous years, DTTP contains trainees on the HPITT route
against various providers. This change will enable us to import these
trainees into register.
Remove a bit of code, to enable all providers to have an HPITT trainee created against them. This does not change the UI for now.

[3444] Enable HPITT route against all providers

---

app/services/trainees/create_from_dttp.rb
spec/services/trainees/create_from_dttp_spec.rb

Adding the dttp_update_sha prevents the nightly job from syncing these records to dttp.
The advantage of this approach is that, it will trigger an update to dttp if some data is changed from within register, while still preventing a sync on initial import.
Set dttp_update_sha when importing from dttp 

[3397] Set dttp_update_sha when importing from dttp 

---

app/controllers/application_controller.rb
app/lib/user_with_organisation_context.rb
config/initializers/audited.rb
spec/controllers/sessions_controller_spec.rb
spec/controllers/trainees/award_recommendations_controller_spec.rb
spec/controllers/trainees/confirm_deferrals_controller_spec.rb
spec/controllers/trainees/confirm_reinstatements_controller_spec.rb
spec/controllers/trainees/confirm_withdrawals_controller_spec.rb
spec/controllers/trainees/degrees_controller_spec.rb
spec/controllers/trainees/lead_schools_controller_spec.rb
spec/controllers/trainees/start_statuses_controller_spec.rb
spec/controllers/trainees_controller_spec.rb
spec/lib/user_with_organisation_context_spec.rb
spec/support/current_user.rb
spec/support/features/authentication_steps.rb

We are working towards supporting users with multiple providers and lead schools. To implement this we're going to decorate the current_user to include an 'organisation context'. This is some initial work on that based on [the spike](https://github.com/DFE-Digital/register-trainee-teachers/pull/1815).
* Add `UserWithOrganisationContext` - a decorator to expose the 'current organisation' and ultimately handle the logic for deriving that in the session. This PR is just to wrap the `providers.first` logic that we are currently using
* Return that from `current_user`
* Add `audit_user`. The audited gem handles non ActiveRecord 'current_user'-ses differently and doesn't attribute the audits correctly so return the AR version as `audit_user` and configure Audited to use that.
* Add a …

[3452] ApplicationController#current_user returns UserWithOrganisationContext

---

app/helpers/application_helper.rb
app/views/system_admin/providers/edit.html.erb
app/views/system_admin/providers/new.html.erb
app/views/system_admin/users/edit.html.erb
app/views/system_admin/users/new.html.erb
app/views/trainees/contact_details/edit.html.erb
app/views/trainees/degrees/_non_uk_degree_form.html.erb
app/views/trainees/diversity/disability_details/edit.html.erb
app/views/trainees/diversity/ethnic_backgrounds/edit.html.erb
app/views/trainees/personal_details/edit.html.erb
app/views/trainees/training_details/edit.html.erb
app/views/trainees/withdrawals/show.html.erb
app/webpacker/scripts/global/disable-browser-autofill.js

This refactors the code to disable browser autofill to make it easier for other teams to use and to make the non-js code more standard.
Issues with previous code:
* It required inputs to have a specific `autocomplete` attribute, but this isn't documented anywhere
* The autocomplete attribute is technically invalid, and so may fail accessibility validators. With this solution, it's only applied when the js runs.

Update disable browser autofill code to use data attribute

---

config/initializers/big_query.rb

Constant reloading on init is deprecated and causes a mahoosive warning when the app initializes.
* Explicitly require `FeatureService` in BigQuery initializer

[xxx] Fix autoloading deprecation warning

---

app/controllers/system_admin/users_controller.rb
app/models/user.rb
app/policies/provider_policy.rb
app/views/system_admin/_tab_nav.html.erb
app/views/system_admin/users/index.html.erb
config/locales/en.yml
config/routes/system_admin_routes.rb
lib/tasks/example_data.rake
spec/features/system_admin/users/list_users_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/users/index.rb

https://trello.com/c/W41YJZPI/3373-s-lead-school-page
- Add users tab to system admin
The providers column will be added when #1868 is merged.

[3375] Add system admin users tab

---

app/components/collapsed_section/view.html.erb
app/components/collapsed_section/view.rb
app/components/sections/view.rb
app/view_objects/apply_invalid_data_view.rb
config/locales/en.yml
lib/tasks/example_data.rake
spec/factories/trainees.rb
spec/view_objects/apply_invalid_data_view_spec.rb

https://trello.com/c/YPJgSwuj/3436-validation-on-missing-data-seems-slightly-broken
- Fix error summary when attempting to mark Trainee Data from Apply applications with no degrees
- Fix the example data so trainee's with an Apply application always have a nationality and degree

[3436] Validation on missing data seems slightly broken

---

app/components/record_details/view.rb
app/services/trainees/create_from_dttp.rb
spec/components/record_details/view_spec.rb
spec/services/trainees/create_from_dttp_spec.rb

https://trello.com/c/AZhT7Rkb/3495-m-withdrawn-trainees-error-due-to-nil-submittedfortrn-date
DTTP trainees can be withdrawn before they, so they end up with no `trn` and no `submitted_for_trn` at. This was breaking our trainee record page since we assumed submitted for trn would always be present.
https://trello.com/c/kIlpwOLS/3497-m-qts-and-eyts-awarded-trainees-are-missing-an-awarded-date
We also were not saving any dates to do with the trainee's award, or withdrawal. I've addressed these in this PR too.
- Fix the view such that it loads without a `submitted_for_trn` date.
- Pull out `outcome_date` and `awarded_at` from the payload and save to trainees
- Pull out `withdraw_date` and `withdraw_reason` from the payload and save the trainee if they are withdrawn
~* Does this PR introduce …

[3495] Save withdrawal details and awarded dates

---

db/migrate/20220106101133_remove_provider_from_users.rb
db/schema.rb
spec/components/user_card/view_preview.rb

https://trello.com/c/Qzaf2eBf/3374-l-provider-users
For PR:
https://github.com/DFE-Digital/register-trainee-teachers/pull/1868
* Migration to remove old provider column from users

[3374] Provider users many to many - remove old provider column from users

---

Gemfile.lock
app/lib/dttp/code_sets/countries.rb
app/services/degrees/map_from_dttp.rb
spec/services/degrees/map_from_dttp_spec.rb

https://trello.com/c/mOY06ML2/3520-m-non-importable-dttp-degrees-missing-country
- Add inactive mapping for countries we're seeing in DTTP but not included in Register
- Expand our list of countries we classify as 'UK degree' (see `united_kingdom_countries` method)
If a trainee has a degree with a country included in the `INACTIVE` mapping, it will still be saved onto the degree, but not available for users to select in the dropdown.

[3520] Add mappings for missing countries

---

app/models/dttp/trainee.rb
app/services/trainees/create_from_dttp.rb
spec/models/dttp/trainee_spec.rb
spec/services/trainees/create_from_dttp_spec.rb

For trainees with multiple placement assignments on multiple courses, we have opted to import the data contained in the 'latest' placement assignment. The latest is determined by the academic year. In case of trainees where multiple placement assignments are available against a trainee in a single academic year, we use the latest one based on the value of `modifiedon`.
1. Update the sort order for placement assignments, and add a has_one relationship for `latest_placement_assignment`
**Note that the sort order for first/last is being changed against `trainee.placement_assignments`**
2. Remove the `non_importable_multi_course` state check, so that these trainee records can be imported by using the latest placement assignment.
Important bit to note: this will change the placement assignment …

[3393] Handle dttp trainees with multiple placement assignments on different courses

---

app/services/trainees/create_from_dttp.rb
spec/services/trainees/create_from_dttp_spec.rb

https://trello.com/c/O1m6vIjD/3511-s-dttp-standards-not-met-trainees-should-be-imported
We were skipping over importing DTTP trainees when their status was 'Standards not met'.
This PR imports them as 'withdrawn' if they have a withdrawal date, or 'trn_received' if they don't.

[3511] Create Standards not met trainees as withdrawn/trn_received

---

app/models/dttp/trainee.rb
app/services/trainees/create_from_dttp.rb
spec/services/trainees/create_from_dttp_spec.rb

The current implementation was mapping a value of "other" gender in DTTP to "gender_not_provided" in register.
Prefer `:other` if gendercode is 389040000. This conversion is lossless in this context, since any update to dttp would map it to the same gendercode.

[3462] Map other gender from DTTP to other in register

---

.github/workflows/deploy.yml

Use new keyvault-yaml-secret action which is more flexible and more secure
Fetching the secrets worked here: https://github.com/DFE-Digital/register-trainee-teachers/runs/4896401876?check_suite_focus=true
(The job failed later on but that's expected)

[498] Deprecate GitHub actions keyvault yaml secret

---

app/services/concerns/has_dttp_mapping.rb
app/services/degrees/map_from_dttp.rb
app/services/trainees/create_from_dttp.rb
app/services/trainees/map_state_from_dttp.rb
spec/factories/dttp/api_trainee.rb
spec/services/trainees/create_from_dttp_spec.rb
spec/services/trainees/map_state_from_dttp_spec.rb

https://trello.com/c/1Ec4keKs/3531-pick-statuses-from-placement-assignments-or-trainee-contacts-when-there-is-a-mismatch
This service:
- Takes a `dttp_trainee` and returns the state to be saved on our trainee
- This is in most cases the 'most progressed' state, i.e. `awarded` wins over all other states, `trn_received` wins over `draft` etc etc
- Adds an error state to the `dttp_trainee` if it cannot determine the state (this is as per the spreadsheet attached to the Trello ticket)

[3531] Add `MapStateFromDttp` service

---

app/services/trainees/create_from_dttp.rb
spec/services/trainees/create_from_dttp_spec.rb

https://trello.com/c/mVnmPhgy/3487-s-for-multiple-disabilities-set-other-and-add-text-hesa-multiple-disabilities
Trainees coming from HESA have the option of 'Multiple disabilities' as a disabilities. We are not given the individual disabilities. Therefore we decided to save this as 'Other' and add a comment in the free text field.
- If the trainee's disabilities is 'Multiple disabilities', then set the additional_disability text to "HESA multiple disabilities"

[3487] Add additional disability text if HESA multiple disabilities

---

terraform/workspace-variables/production.tfvars.json
terraform/workspace-variables/qa.tfvars.json
terraform/workspace-variables/sandbox.tfvars.json
terraform/workspace-variables/staging.tfvars.json

Alerts are currently routed to StatusCake Contact group BAT-DevOps-Slack-All which only forwards to email.
The contact group will be changed to BAT-DevOps-Slack-Prod which will be routed to Slack, email and mobile alerts instead of just email.  Email and mobile alerts are a limited subset of users.  Updated contact groups in workspace variable files for production, qa, sandbox and staging.  
https://trello.com/c/q3F2WvuS
Do the channels match the expected channels.

Update StatusCake contact groups

---

app/jobs/dttp/sync_dormant_periods_job.rb
app/lib/dttp/parsers/dormant_period.rb
app/models/dttp/dormant_period.rb
app/models/dttp/placement_assignment.rb
app/services/dttp/retrieve_dormant_periods.rb
app/services/trainees/create_from_dttp.rb
db/migrate/20220119171355_create_dttp_dormant_periods.rb
db/schema.rb
db/scripts/sanitise.sql
spec/factories/dttp/api_dormant_period.rb
spec/factories/dttp/dormant_periods.rb
spec/jobs/dttp/sync_dormant_periods_job_spec.rb
spec/models/dttp/dormant_period_spec.rb
spec/services/dttp/retrieve_dormant_periods_spec.rb
spec/services/trainees/create_from_dttp_spec.rb

Deferred trainees are missing a deferral date, we need to fetch `dfe_dormant_periods` to be able to populate this information.
1. Add a job and related bits to retreive Dormant Periods
2. Fetch defer_date, reinstate_date, and dormancy_dttp_id to a trainee if they have a dormant period record available.
Preferably commit by commit.

[3496] Add deferral/reinstatement information from DTTP Dormancy Periods

---

app/controllers/base_trainee_controller.rb
app/models/trainee.rb
app/models/trainee_filter.rb
app/services/trainees/filter.rb
app/views/trainees/_filters.html.erb
config/locales/en.yml
spec/factories/trainees.rb
spec/features/trainee_actions/filtering_trainees_spec.rb
spec/models/trainee_spec.rb
spec/services/trainees/filter_spec.rb
spec/support/page_objects/trainees/index.rb

The PR adds the functionality to filter by 'Imported from DTTP' on draft and registered trainee pages, under 'Record Source'. This filter option is only available to admins and does not render for non-admin users.
- `created_from_dttp` scope added to Trainee model
- dttp added to `RECORD_SOURCES` in TraineeFilter model
- `record_source` modified in `filter.rb` to return DTTP trainees correctly
- changes made in `base_trainee_controller.rb` and `_filters.html.erb` so that the DTTP filter renders conditionally
For provider A, we have created one DTTP trainee. Check the below.
Given I am an admin user:
-  when I visit the index page and there is a DTTP trainee, then I can see the 'Imported from DTTP' record source filter
-  when I click on 'Imported from DTTP', then I can see the trainee
- …

3484 s imported trainee filter

---

app/lib/dttp/code_sets/course_subjects.rb
app/lib/dttp/code_sets/training_initiatives.rb
app/services/trainees/create_from_dttp.rb
spec/services/trainees/create_from_dttp_spec.rb

Handle dttp trainees with "Primary Mathematics Specialism" as initiative.
When a trainee has a Primary mathematics specialism initiative, ignore it and map it to `no_initiative`.
Similarly, add an INACTIVE_MAPPING to handle trainees having a duplicate subject entity id of Primary Mathematics Specialist.

[3516] Handle dttp trainees with "Primary Mathematics Specialism" as initiative

---

app/components/contact_details/view.rb
app/forms/contact_details_form.rb
app/views/trainees/contact_details/edit.html.erb
spec/components/contact_details/view_spec.rb
spec/forms/contact_details_form_spec.rb

https://trello.com/c/rrfqtX4n/3490-m-hesa-records-dont-have-an-address
* Contact details section removed address validation for HESA records
* Confirmation page, address row removed for HESA records
* HESA trainee go to contact details section.

[3490] HESA records don’t have an address

---

app/components/funding/view.rb
spec/components/funding/view_spec.rb

The funding component did not render for draft trainees.
This is because it relied on a method `applying_for_grant?` only
available on trainees, and not on the stashed Funding form. The
method common to both is `applying_for_grant`.
Sometimes a form object is passed into the component (when then trainee is in draft) and sometimes a trainee is passed into the form component.
Use the common `applying_for_grant` method.

[xxx] Fix the funding component for draft trainees

---

app/services/trainees/create_from_dttp.rb
spec/services/trainees/create_from_dttp_spec.rb

Handle trainees with placement assignments on multiple providers.
1. When the latest placement assignment provider matches the provider on the trainee record (contact), we have decided to import them as normal
2. When the latest placement assignment provider is different to the trainee/contact provider, we will defer it to dttp-ops for review.
:shipit:  

[3345] Import trainees with placement assignments on multiple providers

---

Gemfile
Gemfile.lock

Puma 5.6.0 isn't playing nicely with our test suite. This PR reverts it back to 5.5.2 so that we can go about BAU.

Revert "Bump puma from 5.5.2 to 5.6.0"

---

app/services/degrees/create_from_dttp.rb
app/services/degrees/map_from_dttp.rb
spec/factories/dttp/placement_assignments.rb
spec/services/degrees/map_from_dttp_spec.rb
spec/services/trainees/create_from_dttp_spec.rb

If the degree is bursary-related, the graduation year is saved onto
the latest placement assignment.
Fall back to this date if there's no degree end date and the degree
is bursary related.
https://trello.com/c/mSdBYJV5/3486-graduation-year-is-incorrectly-set
* Pull the graduation year from the latest placement assignment if the degree has no end date and it's bursary-related.

[3486] Fallback to placement assignment for degree grad date

---

app/views/drafts/index.html.erb
app/views/trainees/index.html.erb
spec/features/trainee_actions/filtering_trainees_spec.rb

Add provider name to index and drafts
* Use primary_provider method to add provider name
* This may need amending once we support multi org users
This was a medium priority bug ticket raised by Design, to add the provider name to the trainee draft and index pages. 
I think this functionality will need to change when we allow for multi org users, as currently primary_provider only picks the first provider. This is also the case for the homepage where we expose the provider name.
* Add logic to `views/drafts/index.html.erb` and `views/trainees/index.html.erb` to show the provider name.
Given I am an admin: 
* when I visit the drafts page, then I cannot see provider name
* when I visit the index page, then I cannot see provider name
Given I am provider A user:
* when I visit the drafts page, …

[3528] Add H1 provider name to draft and registered trainee index pages 

---

app/components/course_details/view.rb
app/forms/course_details_form.rb
app/forms/itt_dates_form.rb
app/views/trainees/course_details/edit.html.erb
app/views/trainees/itt_dates/edit.html.erb
spec/components/course_details/view_spec.rb
spec/forms/course_details_form_spec.rb

https://trello.com/c/f62gKF3L/3489-hesa-records-dont-have-an-itt-end-date
* Updated `itt_dates` form and `course_details` form to hide ITT end date when HESA record
* Updated course details confirmation page to hide ITT end date row when HESA record
* Need HESA record, add course details
* HESA draft record: https://register-pr-1931.london.cloudapps.digital/trainees/4A9KBxfZAc1wkAEygZaPWF2v/course-details/itt-dates/edit
* HESA non-draft: https://register-pr-1931.london.cloudapps.digital/trainees/wj7t5f7NBPFKjEwzajkBLuuo/course-details/itt-dates/edit
* Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send …

[3489] HESA records don’t have an ITT end date

---

app/helpers/mappable_field_helper.rb
app/view_objects/mappable_field_row.rb
app/view_objects/missing_data_banner_view.rb
spec/components/mappable_summary/view_spec.rb
spec/view_objects/mappable_field_row_spec.rb
spec/view_objects/missing_data_banner_view_spec.rb

Once a trainee has been 'awarded', 'recommended for award', or 'withdrawn' we don't want to show the missing data UI.
For trainees in 'awarded', 'recommended for award', or 'withdrawn' states:
1. Don't display the missing data banner even when data is missing
2. Don't show the change links on missing data fields, except if the user is an admin.
On the review app,
- as an admin, visit any of qualification recommended, qualification awarded or withdrawn trainnees, the missing data banner is not shown, but against each attribute that is missing, the missing text, and the change button is visible.
- as a regular user, visit any of qualification recommended, qualification awarded or withdrawn trainnees, the missing data banner is not shown, the change button is not visible, and the text says …

[3500] Do not prompt for missing data on completed records

---

spec/factories/nationalities.rb

Bug ticket raised to fix the nationalities mapping in `specs/factories/nationalities.rb`, so that it uses real nationalities from DTTP and not generic sequenced ones i.e. 'Nationality01'.
- Use `Dttp::CodeSets::Nationalities::MAPPING` to seed nationalities
I think you need to re-seed to be able to check this, so may need to check locally.
- git checkout this branch
- Drop db and set up db with `bin/rails db:drop` and `bin/rails db:setup`
- Re-seed your db with `rake example_data:generate`
- On your localhost, visit http://localhost:5000/trainees/new
- Select any route and go to personal details 
- Scroll down to 'Nationality', click 'other', and type 'na'
- Observe there is no 'Nationality01', 'Nationality02' etc
* Does this PR introduce any PII fields that need to be overwritten or …

[2581] Use a canonical list of nationalities in seed data

---

app/lib/dttp/code_sets/ethnicities.rb
app/services/trainees/create_from_dttp.rb
spec/services/trainees/create_from_dttp_spec.rb

If the DTTP ethnicity is White or Scottish, then we save ethnic_group
as White.
But we also need to save ethnic_background to Not provided, otherwise
the section is incomplete.
I've also fallen back on Not provided for both ethnic_group and
ethnic_background if the DTTP ethnicities is completely missing.
https://trello.com/c/YatgY0qT/3574-ethnicity-sections-for-trainees-with-white-ethnicity-not-showing-as-completed
- Save ethnic_background as "Not provided" in cases where we only have the 'White' ethnicity or it is explicitly not provided in DTTP
- Fall back on ethnic_background and ethnic_group as "Not provided" if the DTTP ethnicity is missing.
~* Does this PR change the database …

[3574] Save `ethnic_background` as "Not provided" for white ethnicities

---

app/services/trainees/map_state_from_dttp.rb
spec/services/trainees/create_from_dttp_spec.rb
spec/services/trainees/map_state_from_dttp_spec.rb

Added a few tweaks based on further analysis.
1. if the trainee record is yet to complete, but the placement assignment is deferred, we use deferred
2. if the placement assignment is yet to complete, but the trainee record is deferred, we stick with yet to complete. This is because DTTP does not always update statuses.
3. Clear out existing non_determinable_statuses, since we've agreed on logical mappings for them now!
4. Map STANDARDS_MET to recommended_for_award or trn received based on these two rules:
- For hesa records, we need to map STANDARDS_MET to `trn_received`, as they do not use this status to signify that a trainee has been `recommended_for_award`.
- For portal records, however, we need to rely on the value of `dfe_recommendtraineetonctl`, which is set to `true` when a record …

[3582] Pick statuses from placement assignments or contact

---

app/forms/course_details_form.rb
app/forms/itt_dates_form.rb
spec/forms/course_details_form_spec.rb

https://trello.com/c/6Lb3Ca9n/3492-fix-itt-start-date-validation
* Updated validation for Course details form to use the academic year
* Removed validation from IttDates form as we're already checking date is within the academic cycle year
* Manually enter course, set date outside of current academic cycle year.

[3492] Fix ITT start date validation

---

app/helpers/application_helper.rb
app/views/system_admin/lead_schools/show.html.erb
app/views/system_admin/providers/show.html.erb
app/views/system_admin/users/index.html.erb

https://trello.com/c/BP9QKYrl/3525-back-links-on-user-tab-going-to-the-wrong-page
I explored using `PageTracker`, but decided not to fiddle with it to work with non-trainee pages. The simpler solution for now is to just add some context to the lead school and provider links so the backlink knows how to get back to the users page. 
- Visit system admin page
- Click on a lead school within the users tab
- Click back link
- Should go back to the users tab
Repeat for provider.

[3525] Fix back links on User/Provider tab going to the wrong page

---

app/components/service_update/view.rb
db/service_updates.yml

https://trello.com/c/0oVDDKXr/3431-line-breaks-in-service-updates-yaml-dont-output-line-breaks-or-paragraphs-when-rendered
- Use `|` instead of `>-` to preserve linebreaks
- Markdown links to include `govuk-link` class

[3575] Fix: line breaks in service updates yaml don't output line breaks or paragraphs when rendered

---

app/forms/course_details_form.rb
app/forms/multi_date_form.rb
app/forms/personal_details_form.rb
app/forms/trainee_form.rb
app/forms/trainee_start_date_form.rb
app/forms/trainee_start_status_form.rb
app/lib/invalid_date.rb

https://trello.com/c/2XLwt9mE/3491-trainee-overview-missing-data-not-missing
- Change `TraineeForm#missing_fields` to check if the attributes are actually empty
- Introduce new object `InvalidDate` so that invalid dates can checked for blank values by `TraineeForm#missing_fields` 
I've updated the following trainee to have the same dates as the trainee highlighted in the Trello card.
Visit https://register-pr-1965.london.cloudapps.digital/trainees/2b7JGBPdhN4PtWkTt7SAqX7f
There should be no message saying the start date is missing.

[3498] Fix: ITT start date labelled as missing even though it's present (but invalid)

---

app/views/trainees/_results.html.erb

https://trello.com/c/o61FRvIt/3526-h2-should-be-removed-on-registered-trainees-page
- Remove `H2` tag from registered trianees page
- Visit registered trainees page
- "Registered trainees" under Sort by heading is not present

[3526] Remove H2 from registered trainees page

---

app/models/dttp/trainee.rb
app/services/trainees/create_from_dttp.rb
spec/factories/dttp/api_trainee.rb
spec/services/trainees/create_from_dttp_spec.rb

It was picked up during the DTTP imports that there were some additional invalid TRNs coming from DTTP that needed to be set as nil in Register. Arlston found these with a regexp and I've implemented that in the code.
We have discussed creating a new metadata column to store the invalid TRNs as these are sometimes used by Ops team as an indication of why a trainee is missing a TRN e.g. `999999999` indicates the trainee came from HESA without a TRN.
Research for which TRNs to include is linked to this trello card: https://trello.com/c/6wuGuyu6/3579-check-do-all-post-submission-trainees-have-trns
* Add TRN_REGEX rule so that we only accept TRNs that are 6 or 7 digits
* Invalid TRNs are saved as nil
* Remove INVALID_TRN constant as this is now covered by the regex rule
* Trim whitespace in …

[3581] Trainees with invalid TRNs

---

spec/features/form_sections/personal_and_education_details/edit_personal_details_spec.rb
spec/support/features/personal_details_steps.rb

Fixes https://github.com/DFE-Digital/register-trainee-teachers/runs/5035494381?check_suite_focus=true
Since we have added a code change to ensure we have real/known
nationalities to the factory, this can sometimes raise an exception:
ActiveRecord::RecordNotUnique:
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_nationalities_on_name"
This change uses find_or_create by to get avoid triggering the
exception.

Fix nationality related flaky spec

---

app/lib/dttp/code_sets/course_study_modes.rb
app/models/dttp/placement_assignment.rb
app/services/trainees/create_from_dttp.rb
spec/services/trainees/create_from_dttp_spec.rb

To confirm: Should 'abridged' be mapped to part time or full time?
_-> confirmed it is full time._
https://trello.com/c/ejyupGqS/3580-trainees-missing-study-modes
- Pull in all possible study mode entity_ids from DTTP and map them to either full time or part time in Register

[3580] Map other DTTP study modes to either part time or full time

---

app/controllers/system_admin/user_lead_schools_controller.rb
app/controllers/system_admin/user_providers_controller.rb
app/views/system_admin/user_lead_schools/new.html.erb
app/views/system_admin/user_providers/new.html.erb
app/views/system_admin/users/index.html.erb
app/views/system_admin/users/show.html.erb
config/routes/system_admin_routes.rb
db/schema.rb
spec/features/system_admin/users/add_a_lead_school_to_user_spec.rb
spec/features/system_admin/users/add_a_provider_to_user_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/users/add_lead_school.rb
spec/support/page_objects/users/add_provider.rb
spec/support/page_objects/users/index.rb
spec/support/page_objects/users/show.rb

Add dropdowns to add providers and lead schools to a user in the system admin section of the application.
Go to /system-admin/users
click on a user
test the 'add a provider' and 'add a lead school' link
New dropdown select screen added to create associations between users and lead schools/ providers

[3377] Add existing user to lead school & provider

---

app/forms/contact_details_form.rb

https://trello.com/c/vMjKzkNx/3577-address-is-missing-is-showing-for-hesa-trainees
* Seems like imported records have some partial data.
* Updated `ContactDetailsForm` to ignore all address fields if hesa record.
* Need HESA trainee with some partial address info
* non-HESA trainee with partial address: https://register-pr-1979.london.cloudapps.digital/trainees/Vtbrin94U3Btm1F1M4GxqpQo/personal-details
* HESA trainee with partial address: https://register-pr-1979.london.cloudapps.digital/trainees/P5RfmiCwVNn5goFtKf8bbTUn/personal-details
* Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send …

[3577] 'Address is missing' is showing for HESA trainees

---

app/lib/dttp/code_sets/training_initiatives.rb
app/services/trainees/create_from_dttp.rb
spec/factories/dttp/api_placement_assignment.rb
spec/services/trainees/create_from_dttp_spec.rb

We have decided to map initiatives which are like "Primary General/Specialist Teaching" to "Specialist Teaching, Primary with Maths" course subject in register.
When this initiative is encountered, override the course subject one to match "Specialist Teaching"

[3591] Map Primary General (with Maths) initiative to specialist teaching

---

app/services/trainees/create_from_dttp.rb
spec/services/trainees/create_from_dttp_spec.rb

We have decided to use programme start date as a fallback for when commencement date is missing as some hesa records have commencement date missing.
Fallback to the programme_start_date if dfe_commencementdate is null.

[3578] Use programme start date where the trainee is missing a commencent date

---

db/migrate/20220204132842_add_additional_dttp_data_to_trainees.rb
db/schema.rb
db/scripts/sanitise.sql

We have some data that comes in from DTTP but isn't currently supported with our functionality. e.g. TRNs that have state info in them rather than TRNs or initiatives that we don't recognise as initiatives.
To enable us to proceed with the imports without losing this we should store these things in a column that has a flexible schema. If we need them in the future we can make proper columns for them.
- Add `additional_dttp_data` jsonb field into the trainees table
- Checkout the branch and run migration, see no errors
- Check the naming is correct i.e. no spelling error
- Check trainees table additional_dttp_data field looks as expected
* ~~Does this PR change the database …

[3598] Add additional_dttp_data field to trainees

---

app/jobs/dttp/sync_bursary_details_job.rb
app/jobs/dttp/sync_training_initiatives_job.rb
app/lib/dttp/parsers/bursary_detail.rb
app/lib/dttp/parsers/training_initiative.rb
app/models/dttp/bursary_detail.rb
app/models/dttp/training_initiative.rb
app/services/dttp/retrieve_bursary_details.rb
app/services/dttp/retrieve_training_initiatives.rb
db/migrate/20220207155623_create_dttp_bursary_details.rb
db/migrate/20220207155734_create_dttp_training_initiatives.rb
db/schema.rb
spec/factories/dttp/api_bursary_detail.rb
spec/factories/dttp/api_training_initiative.rb
spec/factories/dttp/bursary_details.rb
spec/factories/dttp/training_initiatives.rb
spec/jobs/dttp/sync_bursary_details_job_spec.rb
spec/jobs/dttp/sync_training_initiatives_job_spec.rb
spec/models/dttp/bursary_detail_spec.rb
spec/services/dttp/retrieve_bursary_details_spec.rb

https://trello.com/c/PrAg4L3F/3600-s-import-extra-entity-sets-from-dttp
- New Sidekiq jobs to download and import DTTP entities from `/dfe_bursarydetails` and `/dfe_initiatives` 

[3600] Import extra entity sets from DTTP

---

app/views/trainees/_filters.html.erb
config/settings.yml

The start year filter is currently not working. However there is some design work being done currently that will overlap with this, so for now it is agreed to hide the filters.
We need to currently hide the filters instead of fix them due to the mentioned design work but also to ensure out users aren't seeing broken elements in the UI.
- Feature flag added in `config/settings.yml` to switch start years filter on or off (currently set to `false` in this PR)
- Conditional flag added to the filter view to stop start year filter from rendering
As any user (provider or admin):
- given I am on the draft or registered trainee pages, then I do not see the 'Start year filter'
* ~~Does …

[3619] Hide year filters

---

app/lib/dttp/code_sets/institutions.rb

https://trello.com/c/qrYEhXrK/3394-test-run-create-dttp-trainees
Some degrees were skipped over in the last import because we didn't have their DTTP IDs. They're all inactive accounts in DTTP for which we have the correct current account already in our codesets. I've added these old ones to our inactive DTTP mapping.

[xxx] Add some missing inactive DTTP institutions

---

app/lib/dttp/code_sets/bursary_details.rb
app/models/dttp/placement_assignment.rb
app/services/trainees/create_from_dttp.rb
app/services/trainees/map_funding_from_dttp.rb
db/data/20220207122830_add_old_funding_methods.rb
spec/services/trainees/create_from_dttp_spec.rb
spec/services/trainees/map_funding_from_dttp_spec.rb

https://trello.com/c/PznmhKZJ/3499-handle-trainees-with-funding-from-older-years
- Adds 2019/20 funding rules to our DB via data migration. I haven't found nor added any previous to this and I don't know how many trainees this would affect.
- Splits the funding mapping into a separate file for clarity and testing
- Removes the checks we were making on whether funding was appropriate via the `FundingManager` and simply save the correct booleans based on what DTTP is telling us.
- The UI still uses the `FundingManager`. This means that unless there's a matching `FundingMethod` in the DB, the funding section will show "Not applicable".
This is the funding manual for 2019/20: https://www.gov.uk/government/publications/initial-teacher-training-itt-bursary-funding-manual/initial-teacher-training …

[3499] Add old funding rules to Register and import trainees from DTTP

---

app/helpers/degrees_helper.rb
app/lib/dttp/code_sets/degree_types.rb

The hints in the autocomplete are intended to be rendered in grey. This adjusts them to make that happen.
I also added a new hint for the `degree equivalent` option to give it parity with the `higher degree` option.

Improve the display of autocomplete hints

---

app/models/dttp/trainee.rb
app/services/trainees/create_from_dttp.rb
spec/factories/dttp/api_trainee.rb
spec/services/trainees/create_from_dttp_spec.rb

When a record is imported it currently has created_at and updated_at set to the date of import. This is misleading and causes the records to appear at the top of the lists of trainees. This PR will change the created_at and updated_at fields to be set from the createdon and modifiedon ddtp fields instead.

[3485] Created at and Updated at is set from dttp fields

---

app/forms/training_details_form.rb
app/models/trainee.rb
spec/forms/training_details_form_spec.rb
spec/models/trainee_spec.rb

If a trainee is inactive (withdrawn or awarded in a previous cycle) we should be able to create a duplicate of it using the same trainee_id.

[3572] trainee id validation allows duplicates if trainee inactive

---

app/services/form_store.rb
config/initializers/redis.rb

Redis.current has been deprecated.
Add `RedisClient#current` to memoize a `Redis` instance.
Check FormStore is still functioning

[xxx] Replace Redis.current

---

app/controllers/application_controller.rb
app/controllers/concerns/publishable.rb
app/controllers/trainees/check_details_controller.rb
app/controllers/trainees/confirm_details_controller.rb
app/controllers/trainees/degrees/confirm_details_controller.rb
app/controllers/trainees/diversity/confirm_details_controller.rb
app/controllers/trainees/personal_details_controller.rb
app/controllers/trainees_controller.rb
app/policies/trainee_policy.rb
app/views/drafts/index.html.erb
app/views/pages/home.html.erb
app/views/trainees/apply_applications/confirm_courses/show.html.erb
app/views/trainees/apply_applications/trainee_data/edit.html.erb
app/views/trainees/check_details/_apply_draft_trainee_check_details.html.erb
app/views/trainees/check_details/_draft_trainee_check_details.html.erb
app/views/trainees/index.html.erb
app/views/trainees/personal_details/show.html.erb
app/views/trainees/show.html.erb
spec/components/pages/trainees/check_details/view_preview.rb
spec/policies/trainee_policy_spec.rb
spec/views/trainees/personal_details/show.html.erb_spec.rb
spec/views/trainees/show.html.erb_spec.rb

Adresses feedback from https://github.com/DFE-Digital/register-trainee-teachers/pull/2011
1. Update `TraineePolicy#create?` to only allow users in a provider context.
2. Change template checks from `current_user.provider?` to `policy(Trainee).create?` when rendering buttons to add a new trainee.
3. Adds a `trainee_editable?` helper in `ApplicationController`, instead of duplicated checks all over the codebase.

[3603] Trainee Policy edits

---

app/lib/dttp/code_sets/academic_years.rb
app/lib/dttp/params/placement_assignment.rb

We currently have a TRN registration that is failing as we don't support
a start date in 2019/2020 when sending the request to DTTP.
Add this mapping.

[xxx] Support registering trainees from 2019/2020

---

app/lib/dttp/code_sets/ethnicities.rb
app/lib/hesa/code_sets/disabilities.rb
app/lib/hesa/code_sets/ethnicities.rb
app/lib/hesa/parsers/itt_record.rb
app/services/concerns/diversity_attributes.rb
app/services/trainees/create_from_dttp.rb
app/services/trainees/create_from_hesa.rb
config/initializers/diversity_enums.rb
spec/lib/hesa/parsers/itt_record_spec.rb
spec/services/trainees/create_from_hesa_spec.rb
spec/support/api_stubs/hesa_api.rb
spec/support/fixture_helpers.rb

https://trello.com/c/8SisYLpY/3657-hesa-map-ethnicity-and-disability-attributes
- Extended `Trainees::CreateFromHesa` to extract and save ethnicity and disability data from the HESA XML
- Mapped HESA codes for ethnicities and disabilities
- New HESA stub API object to help with testing
- Extracted common diversity code between `Trainees::CreateFromHesa` and `Trainees::CreateFromDttp` into a module to get around Sonar's duplicated code warnings
- Changed `Hesa::Parsers::IttRecord` to accept a student node instead of the root node. The background job will loop through the student nodes and pass then to `Trainees::CreateFromHesa` 
~* Does this PR change the database schema? If so, …

[3657] Map HESA ethnicity and disability attributes

---

app/components/application_record_card/view.rb
app/controllers/base_trainee_controller.rb
app/controllers/trainees_controller.rb
app/models/trainee.rb
spec/components/application_record_card/view_preview.rb
spec/components/application_record_card/view_spec.rb
spec/models/trainee_spec.rb

https://trello.com/c/TURjhLuH/3456-draft-records-last-updated-sort-is-inaccurate
It _looked_ like the drafts weren't being ordered by last updated it.
They actually were. It was the 'Updated' timestamp on the trainee row that was wrong.
We decided to use the last entry on the timeline for this date so as not to confuse users with 'behind the scenes updates'.
But for draft trainees we don't _show_ any timeline events! So this date was always showing created_at, regardless of updates.
This PR:
- Uses the `updated_at` for drafts rather than the (empty) timeline
- Removes method `ordered_by_drafts_then_by` - relic from when drafts and registered were on same page
- Removes method `ordered_by_drafts` - as above
- Removes method `ordered_by_drafts_clause` - as above
- Removes unused method …

[3456] Draft records last updated sort is inaccurate

---

app/lib/funding_manager.rb
spec/lib/funding_manager_spec.rb

We use academic cycle to determine whether funding should be available for a trainee. 
If there is no academic cycle for that trainee (because they don't have a start date yet), we aren't correctly restricting entering funding information before course information on the view. This means they can incorrectly complete their funding section without having course details added.
This PR relaxes the `funding_available?` check by allowing us to look for existing funding methods for the relevant route for other academic years, when `academic_year` is nil. This means we can restrict the entry of funding information better on the UI, which looks for `funding_available?` to be true and `trainee.course_subject_one.blank?` in order to work.
- Update `funding_available?` to look through all previous …

[3618] Users not prevented from starting funding section as they should be

---

app/views/errors/forbidden.html.erb
config/locales/en.yml

Update 403 page
Update 403 page title to read "You do not have permission to perform this action" 
On the review app, login as a user with Lead School access, and try performing an edit action against a trainee, eg
https://register-pr-2058.london.cloudapps.digital/trainees/sCCpHen2mgh2CFMFnoisFLnW/training-routes/edit
You will be presented with the new forbidden page content

[3601] Update 403/forbidden page content

---

spec/lib/funding_manager_spec.rb

Tidied up a few variables on some tests I recently added to make them easier to read. Original ticket:
https://trello.com/c/1gJv5I3L/3618-users-not-prevented-from-starting-funding-section-as-they-should-be
* ~~Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?~~

[xxx] Make tests clearer on funding manager spec

---

app/controllers/drafts_controller.rb
app/helpers/organisation_helper.rb
app/policies/user_policy.rb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
config/settings/review.yml
spec/controllers/pages_controller_spec.rb
spec/features/trainee_actions/viewing_an_existing_trainee_spec.rb
spec/helpers/organisation_helper_spec.rb
spec/policies/user_policy_spec.rb

https://trello.com/c/OCdiDgyG/3669-draft-records-link-and-section-arent-visible
* Helper to hide the link and content on start page
* Updated `UserPolicy` to authorise `drafts#index`
* Login with persona Denise Theominis and choose org Western Flatley University
* See start page
* Go directly to `/drafts` as a lead school user, it should error

[3669] Draft records link and section aren't visible

---

.github/workflows/build-nocache.yml
.github/workflows/build.yml
Makefile
docker-compose.yml
terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf
terraform/terraform.tf
terraform/variables.tf

Containers for this repo are currently published to Dockerhub. Publishing images to GitHub container registry is simpler and more secure.
This commit migrates workflows from Dockerhub to the GitHub Container Packages registry.
- Confirm that image is being published as a GitHub Container Package
- Confirm that deployment is using the correct GitHub Container Package
https://trello.com/c/wVT0QcJ4

Migrate to GitHub container registry

---

app/components/application_record_card/view.html.erb
app/components/application_record_card/view.rb
app/components/record_header/view.html.erb
app/components/record_header/view.rb
app/components/status_tag/view.rb
app/views/layouts/trainee_record.html.erb
app/views/trainees/_results.html.erb
spec/components/record_header/view_spec.rb
spec/components/status_tag/view_spec.rb

When a record is 'incomplete' we label the record in the index and in the titles of various pages.
Users in a lead school context can't 'complete' records so they shouldn't get the 'incomplete' badge anywhere. 
* Incomplete records aren't labelled for lead school users
- Add `hide_progress_tag` boolean into relevant components and views in the app to hide the badge from the record card and the record header
- `hide_progress_tag` defaults to false
- `hide_progress_tag` evaluates to true when `current_user.lead_school?` is true
- Log into the review app as Denise Theominis
- Make sure you are on the Provider B view (see top right)
- In registered trainees, look for trainee with name 'incomplete trainee'. You will see they have an incomplete badge
- Click on 'Provider B' in top right and …

[3670] Hide incomplete badge on registered trainees from lead school users

---

app/forms/contact_details_form.rb
app/models/trainee.rb
spec/forms/contact_details_form_spec.rb

A trainee was failing to update to DTTP because the postcode was longer than 20 characters. It passed our postcode validation because it was correctly formatted but with leading and trailing whitespace.
This probably happens when people copy and paste from another document.
https://sentry.io/organizations/dfe-teacher-services/issues/2777405619/?project=5552118&referrer=slack
- Strip leading and trailing whitespace from postcodes before saving
- Try saving a trainee with a postcode `"    SW1P 3BT   "`
- See that it is actually saved `"SW1P 3BT"`
~* Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send …

[xxx] Strip leading and trailing spaces from postcodes

---

spec/policies/school_policy_spec.rb

Fixes https://github.com/DFE-Digital/register-trainee-teachers/runs/5318503141?check_suite_focus=true
We don't have a need for a explicit order by name spec in the `SchoolPolicy` specs, since the `order_by_name` bit is taken care of by the `School.order_by_name` scope rather than any policy specific logic.
:shipit: 

[xxxx] Remove explicit ordering on SchoolPolicy spec

---

app/lib/dqt/params/trn_request.rb
app/lib/dttp/code_sets/grades.rb
spec/factories/trainees.rb
spec/lib/dqt/params/trn_request_spec.rb

Add a `Dqt::Params::TrnRequest` presenter
Add a presenter similar to [the ones we already have](https://github.com/DFE-Digital/register-trainee-teachers/tree/main/app/lib/dttp/params).
This presenter receives a trainee record and outputs json in the format defined in the [DQT api](https://github.com/DFE-Digital/qualified-teachers-api/blob/d847781b438ce4962fb54558067772b149ea1c60/docs/api-specs/v2.json#L563).
There are a couple of areas that might need a bit of attention: 
1. Training Route mappings (`programmeType` in DQT), and
2. Degree grade mappings (`qualification->class` in DQT). 
Please see notes added in the PR against those two areas. 
* ~Does this PR change the database …

[3708] Add Dqt::Params::TrnRequest params presenter

---

app/components/summary_card/style.scss

Latest Chrome combined with MacOS dark mode and an acrobat extension is causing several issues with the design system (bug raised with GDS).
Additionally, our summary card headers don't have a colour set, and the result is that the header turns white. This copies @ralph-hawkins's fix from https://github.com/DFE-Digital/register-trainee-teachers-prototype/pull/458
Before:
After:

Explicitly set text colour on summary card headings

---

app/jobs/hesa/retrieve_collection_job.rb
app/models/hesa_collection_request.rb
config/settings.yml
config/sidekiq_cron_schedule.yml
db/migrate/20220214142008_create_hesa_collection_requests.rb
db/schema.rb
spec/factories/hesa_collection_requests.rb
spec/jobs/hesa/retrieve_collection_job_spec.rb
spec/models/hesa_collection_request_spec.rb

We want to run two hourly updates from HESA when a collection is open. The update will request XML from the HESA API containing updates since the last request.
* Add Hesa::RetrieveCollectionJob - this job will request the XML, store it and then pass it into the service(s) currently being built to create or update the trainee. Currently it just requests and stores. [Trello ticket for the next bit](https://trello.com/c/pEaVj82M/3689-hook-up-the-hesaretrievecollectionjob-to-create-update-trainees)
* Add HesaCollectionRequest to log the requests and store the XML. We'll store the raw XML in the DB currently as this is the pattern we've adopted for all other integrations. If it turns out these responses are big we can reconsider.
* Use cron sidekiq to schedule the job to run two hourly
* Add a …

[3636] Scheduled task to retrieve HESA data

---

app/components/application_record_card/view.rb
app/components/record_details/view.rb
app/views/trainees/_results.html.erb
app/views/trainees/show.html.erb
spec/components/application_record_card/view_preview.rb
spec/components/application_record_card/view_spec.rb
spec/components/record_details/view_preview.rb
spec/components/record_details/view_spec.rb

https://trello.com/c/4x8q1sXy/3673-add-accrediting-provider-for-lead-school-users
In `RecordDetails::View` and `ApplicationRecordCard::View`:
- Re-purposes the `system_admin` boolean to be a `show_provider` boolean since this is what is actually means for the 'dumb' components.
- Sets `show_provider` to true if the user is a system admin, or in a lead school context.

[3673] Show provider details if a user is in a lead school context

---

lib/tasks/example_data.rake

https://trello.com/c/1rx8S5Wx/3682-snags-with-apply-seed-data
- Explicitly set study mode from sampled course
- Set trainee_id to nil
- Set lead_school_id and employing_school_id to nil
- I can't replicate this, I'm always asked to confirm the course, then the ITT start dates now
- Sounds like this would have been related to the above issue, which now doesn't seem to be happening
- This was a bug fixed here: https://github.com/DFE-Digital/register-trainee-teachers/pull/2036
- Review the imported from Apply trainees seeded in the review app
~* Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send …

[3682] Improve seeded Apply drafts

---

.github/workflows/deploy.yml
db/seeds.rb
lib/tasks/example_data.rake
spec/factories/trainees.rb
terraform/modules/paas/variables.tf

The `example_data:generate` seems to be running for a bit too long:
Local results
```bash
$ time bundle exec rails example_data:generate
bundle exec rails example_data:generate  114.26s user 5.63s system 89% cpu 2:13.28 total
```
This causes the data to not be generated correctly in review apps. This can be reproduced by raising a PR, which will seem to be missing the personas with multi-user accounts, (compare with this PR's review app)
* Move `db:seed` and `example_data:generate` over to the deploy pipeline, similar to the way we do when running data migrations.
* Additionally, update some seeds to use `upsert_all`
:eyes: 
* ~Does this PR change the database schema? If so, have …

Remove db:seed and example_data:generate from review app start command

---

lib/tasks/example_data.rake
spec/controllers/trainees/personal_details_controller_spec.rb
spec/controllers/trainees/training_details_controller_spec.rb
spec/factories/trainees.rb
spec/features/form_sections/personal_and_education_details/degrees/editing_degree_spec.rb
spec/forms/submissions/trn_validator_spec.rb
spec/services/find_empty_trainees_spec.rb
spec/services/trainees/filter_spec.rb
spec/support/shared_examples/rendering_the_funding_section.rb

Fix snags listed in [this trello card](https://trello.com/c/2mKZD7EA/3710-snags-with-seed-data-drafts-trn-start-date).
I've created a separate base PR for the sake of the CI pipeline https://github.com/DFE-Digital/register-trainee-teachers/pull/2070
Also adds the functionality from https://github.com/DFE-Digital/register-trainee-teachers/pull/2073, since this PR moves things around a bit.
- Ensure that ~25% of `submitted_for_trn` trainees do not have a `commencement_date`
- Also use `x/2` instead of `rand` for more explicit percentage calculation
- Move nationality, degree creation *before* creating trainee to allow creation of completed records.
- ~Ensure that 25% of drafts are incomplete.~
- Ensure that  ~75% of drafts are incomplete.
- Update draft trainee factory to contain complete …

[3710] Fix snags with seed data

---

db/data/20220224150322_backfill_missing_provider_ukprns.rb

Staging deployment failed because it doesn't have the provider data expected to run this data migration.
- Make the migration run even if the expected records don't exist

[xxx] Fix data migration

---

app/models/user.rb
config/locales/en.yml
db/migrate/20220302160415_add_uniqueness_to_user_email.rb
db/schema.rb
spec/components/user_card/view_preview.rb
spec/models/user_spec.rb

Ensure email addresses are unique when creating a user.
Add a migration to change the index on `users.email` to be unique.
Add a uniqueness validation.
Tweak the existing definition of `User#active_user?` to compare users by email as opposed to dttp ids.
Define a private method `active_user_by_dttp_id?` on `User` to ensure that existing dttp_id uniqueness validation works as before.
Visit the review app as a system admin, and try to create a user with the same email address.

[3756] Add email uniqueness validation and db constraint

---

app/components/personal_details/view.rb
app/helpers/organisation_helper.rb
app/helpers/users_helper.rb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/trainees/personal_details/show.html.erb
spec/helpers/users_helper_spec.rb
spec/views/trainees/personal_details/show.html.erb_spec.rb

https://trello.com/c/Q1bD0HeP/3744-lead-school-user-should-not-be-able-to-see-gender-nationality-diversity-details
- Add new boolean argument `minimal` to `PersonalDetails::View` to hide gender, nationality and diversity details
- Log in using the Denise Theominis persona
- Choose the lead school
- Visit non-draft trainee and their personal details
- Gender, nationality and diversity details information should not be displayed
~* Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?~0

[3744] Lead school user should not be able to see gender, nationality or diversity details

---

app/jobs/hesa/retrieve_collection_job.rb
db/data/20220303155105_add_missing_providers.rb

`Hesa::RetrieveCollectionJob` crashes after trying to load the large XML from HESA into memory. 
Use an alternative approach to iterate over the XML nodes to reduce memory footprint.

[xxx] Reduce memory footprint when processing very large XML payload from HESA

---

app/services/dqt/register_for_trn.rb
app/services/trainees/submit_for_trn.rb
spec/services/trainees/submit_for_trn_spec.rb

https://trello.com/c/8ZTMCFk7/3764-hook-up-the-dqt-trn-route
* Updated `Trainees::SubmitForTrn` to also schedule `Dqt::RegisterForTrnJob`
* Backend

[3764] Hook up the DQT TRN route

---

app/controllers/trainees/timelines_controller.rb
app/services/trainees/create_timeline.rb
app/services/trainees/create_timeline_events.rb
spec/services/trainees/create_timeline_events_spec.rb
spec/services/trainees/create_timeline_spec.rb

https://trello.com/c/3XvRgc1C/3746-obscure-names-from-timeline-if-its-not-the-same-user-viewing-it
- If the user viewing the timeline is not the same as the user who
made the audit, then only show provider name
- If the user viewing the timeline is a system admin, show the user
name and the provider name
This is kinda funky because there's a cached version of a trainee's timeline on the trainee model, which should not rely on a current_user in the session. We used this cached version to read off the latest updated timestamp in various places across the app.
So, I've left this part of the code untouched:
https://github.com/DFE-Digital/register-trainee-teachers/blob/main/app/models/trainee.rb#L287
And updated the _actual_ timeline as generated in the timelines controller to pass in …

[3746] Obscure some usernames from the timeline

---

config/locales/en.yml

https://sentry.io/organizations/dfe-teacher-services/issues/3083374458/?project=5552118&referrer=slack
We were missing some translations for primary course subjects in the missing details banner.
This PR adds them.
Recreating the issue on dev, with the new translations:

[xxx] Add missing translations for primary subjects

---

app/services/apply_api/import_application.rb
spec/services/apply_api/import_application_spec.rb

Currently we have this issue:
- An Apply application is not imported (and no trainee is created) because of some error in the data
- The Apply application is fixed upstream and we receive an updated application via the API
- However, we do not update our own Apply application in our database, because of a check `return unless application.new_record?`
The application remains in the 'importable' state and errors daily when trying to create a trainee.
- Allow updates to our own Apply applications if the application is in the importable state i.e. no trainee has been created yet.
Any reason why this isn't sensible?
I think we may have blocked updates to applications in a bid to 'freeze' them at the point at which a trainee is created. This change doesn't invalidate that logic.
~* Does this PR …

[xxx] Allow updates to apply applications if not already imported

---

app/lib/dqt/client.rb
app/lib/dqt/params/trn_request.rb
spec/lib/dqt/params/trn_request_spec.rb

We've been testing the DQT API for TRNs. A few small issues were identified. This PR addresses them.
* Fix issue in the client `request.body`
* Send HESA country codes for degrees
This has been succesfully tested against the API and is currently feature flagged. We'll be doing more manual testing so just a quick once over would be good. We need these changes for other work that is in flight so it'll be good to get them into main.

[3787] DQT manual testing snags

---

app/services/trainees/create_from_hesa.rb
spec/services/trainees/create_from_hesa_spec.rb

Enqueue a TRN request by using the `Dqt::RegisterForTrnJob` job.
When a trn is available, use it, and when it isn't available, enqueue the `Dqt::RegisterForTrnJob` job. This job will take care of setting the trainee's state to `submitted_for_trn`.

[3766] Enqueue TRN request when creating hesa records that do not have one

---

app/controllers/trainees/award_recommendations_controller.rb
app/jobs/dqt/recommend_for_award_job.rb
app/lib/dqt/params/award.rb
app/models/dqt_no_award_date_error.rb
app/services/dqt/recommend_for_award.rb
spec/controllers/trainees/award_recommendations_controller_spec.rb
spec/factories/trainees.rb
spec/jobs/dqt/recommend_for_award_job_spec.rb
spec/lib/dqt/params/award_spec.rb
spec/services/dqt/recommend_for_award_spec.rb

https://trello.com/c/DnKaKQRZ/3781-m-dqt-qts-submission
- Update `AwardRecommendationsController` to send to DTTP/DQT depending on which
feature flags are enabled.
- Create `RecommendForAward` service which makes the put request to DQT with the
relevant parameters and returns the award date received in the response.
- Create `RecommendForAwardJob` which calls the services and sets the awarded_at
date on the trainee.
- Create `Dqt::Params::Award` params for formatting the request parameters
DQT API specs:
https://github.com/DFE-Digital/qualified-teachers-api/blob/main/docs/api-specs/v2.json#L8
See `/v2/teachers/{trn}/itt-outcome`
~* Does this PR change the database schema? If so, …

[3781] DQT QTS submission

---

app/components/application_record_card/view.rb
app/policies/trainee_policy.rb
app/views/layouts/trainee_record.html.erb
app/views/trainees/_results.html.erb
spec/components/application_record_card/view_preview.rb
spec/components/application_record_card/view_spec.rb
spec/policies/trainee_policy_spec.rb

https://trello.com/c/EYqO3fg8/3711-l-hesa-records-in-register-view-only-state-for-hesa-records
* Updated `TraineePolicy` to check for hesa record
* Hiding incomplete tag now uses `TraineePolicy`

[3711] HESA records in Register - View only state for HESA records

---

app/models/trainee.rb
app/policies/trainee_policy.rb
app/views/layouts/trainee_record.html.erb
config/locales/en.yml

https://trello.com/c/Cj6PM6Au/3712-hesa-records-in-register-content-telling-users-theyre-record-is-from-hesa-an-cannot-be-edited
- Based on https://github.com/DFE-Digital/register-trainee-teachers/pull/2114
- moved the `hesa_record?` from `TraineePolicy` to `Trainee` to be able to reuse it in the view.
- Add the inset text.
Only https://github.com/DFE-Digital/register-trainee-teachers/pull/2118/commits/fdfd2bc4b8e369d9be17a66af068d533aef7da77 forms part of this PR.
Visit any non-draft trainee on Provider A, to view the content  (i've marked them all as HESA imports)
* Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether …

[3712] hesa records in register content change

---

.github/workflows/build-and-deploy.yml

This fixes an issue where the docker image tag wasn't getting passed to the deploy_all job in the build-and-deploy workflow which was then defaulting to the main tag.
- Add out to test job
- Use output from test job in deploy_all instead of output from build

deploy_all job uses output from test job

---

app/views/trainees/_filters.html.erb
app/views/trainees/_record_completion_filter.html.erb
spec/views/trainees/record_completion.html.erb_spec.rb

Users in lead school context cannot 'complete' and 'incomplete' record so the concept is meaningless to them.
We have a filter on the registered trainees index page that filters for incomplete records. This should be hidden from lead school users.
Hide Record completion filter from lead school users.

[3671] Record completion filter hidden for users in lead school context

---

app/services/trainees/create_from_hesa.rb
spec/services/trainees/create_from_hesa_spec.rb

From the HESA data it appears that a TRN might not always be submitted with an update,
even though a TRN has previously been submitted.
This change prevents a blank TRN in the HESA update from overwriting an existing TRN in register by `compact`ing the attributes.

[3827] Do not overwrite trn if present in register, and the hesa update has a blank trn.

---

.github/workflows/delete-review-app.yml

Review apps are not deleted
Replacing wait with native concurrency feature which is less brittle
Successful delete workflow run: https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/1992434548

Fix: review app not deleted

---

.github/actions/deploy/action.yml

The deployment status update task by default (in version 1.1.0) actively marks previous deployments as inactive, this results in a large number of API calls which in turn causes a rate limiting failure.
This change disables that function, this will leave deployments showing as Active in the deployments page.  An issue has been raised to fix this in the action.

Stop deployment status marking deployment inactive

---

config/locales/en.yml

This might not be true, we should remove it to avoid confusion. When we know how users recommend trainees we can update the message.

Remove message about how trainees can be recommended for QTS/EYTS

---

config/initializers/mappings/allocation_subject_to_specialism_mapping.rb
config/initializers/mappings/publish_to_allocation_subject_mapping.rb
lib/tasks/example_data.rake
spec/factories/courses.rb
spec/factories/trainees.rb

https://trello.com/c/8v7sSyFk/3530-snags-with-seed-data-part-2
- Set education phase for primary trainees to primary
- Map physics to physics and applied physics specialisms
- Choose common age ranges for courses
- Set 80% of trainees to funded if funding available
See ticket for explanation of checklist items not addressed here (i.e. already fixed, or not reproducible) 
Historical data seeds pulled out into separate ticket https://trello.com/c/N972jc7z/3814-historical-data-seeds

[3530] Improve seed data pt 2

---

config/sidekiq.yml

To fix missing DQT queue which is preventing smoke tests from passing.
* Add DQT queue to Sidekiq
* ~~Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?~~

Add the DQT queue to sidekiq

---

.github/workflows/build-and-deploy.yml

Dependabot can't push to GitHub packages because it does not have
enough permissions. Adding the permissions section to include write to
packages ensures dependabot can push properly.
An issue was raised around dependabot failing to push to GitHub packages. The logs were unavailable by the time the issue was looked at, however a similar issue was resolved by manually adding the permissions section in to the workflow file.
Add permission section to workflow file to include packages.
Check review app process works as expected.

Add permissions for dependabot package push

---

terraform/modules/paas/data.tf
terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf
terraform/terraform.tf
terraform/variables.tf
terraform/workspace-variables/staging.tfvars.json

Add DTTP portal route to PaaS for staging.
This is just adding the route, the DNS change will occur later.
https://trello.com/c/272NMS5W/3820-setup-dttp-portal-domains-on-govuk-paas
Update terraform configuration to add route 
Confirm review deploys successfully
confirm in staging env

Add dttp portal PaaS route for staging

---

app/controllers/pages_controller.rb
app/views/pages/start_traineeteacherportal.html.erb
config/environments/development.rb
config/initializers/canonical_rails.rb
config/routes.rb
config/settings/development.yml
config/settings/production.yml
config/settings/qa.yml
config/settings/staging.yml
config/settings/test.yml
spec/controllers/pages_controller_spec.rb
spec/requests/traineeteacherportal_requests_spec.rb

When users go to `traineeteacherportal.education.gov.uk` we will redirect them to Register to keep their journey as seemless as possible. We've decided we'll give them their own start page before they view the main Register start page, the change here is flexible enough to accommodate this or be changed to send them to the normal Register start page.
Accept requests to the `traineeteacherportal.education.gov.uk` (this can be different in different environments), and redirect those users to a custom landing page (`start_traineeteacherportal`).
The redirect mechanism is tricky to test locally, and may only really be testible in a deployed environment. I also tried to create a feature test but for some reason it went into a redirect loop, I think the routing constraint wasn't working …

[3833] add start_traineeteacherportal page

---

service_unavailable_page/web/public/internal/index.html
service_unavailable_page/web/public/internal/stylesheets/style.css

We have scheduled downtime tonight. Update the content on the service unavailable page so as we can enable that.
We have work planned to make this content more configurable so we'll update this soon.

[xxx] Temporarily change unavailable page

---

app/lib/dqt/params/trainee_request.rb
app/services/dqt/trainee_update.rb
spec/lib/dqt/params/trainee_request_spec.rb
spec/services/dqt/trainee_update_spec.rb

Small change in the DQT API that we hadn't picked up.
`birthDate` is a URL querystring parameter. We were passing it in the body payload.
The docs haven't been updated yet but I've discussed this with @gunndabad 

[3787] Fix trainee update path

---

.github/actions/deploy/action.yml

The wait for step wasn't locating the dispatched smoke test workflow so was timing out.  This wasn't failing the workflow because the condition only checked for failures and not timeouts.
Changed the ref used to track the dispatched workflow and altered the condition to fail the workflow if smoke tests not successful.
- Check that the smoke tests are reporting as expected in the build and deploy workflow

Fix check on smoke test outcome

---

config/settings/qa.yml
config/settings/review.yml
config/settings/staging.yml

We're inching ever forward towards enabling the DQT integration.
* Add the URLs for the three environments
* Enable in staging for testing
* The keys have already been added to the secrets in each environment.

[3787] DQT update config and enable on staging

---

app/controllers/trainees/itt_dates_controller.rb
spec/controllers/trainees/itt_dates_controller_spec.rb
spec/factories/courses.rb

Fixes https://sentry.io/organizations/dfe-teacher-services/issues/2967214933
This was getting triggered when a user tries to create a trainee on a course
where previously the full time/part time dates have been set globally.
The exception was being triggered due to the course_uuid not being sent
through to the form.
Stolen from @edwardhorsford 
1. add a new draft trainee for Provider A
2. school direct salaried
3. add course details
4. pick any publish course.
5. Ensure you add the ITT start and end dates, and check the box which starts with "Use these dates for all full time trainees on ..." (see screenshot)
6. Observe success.
Repeat steps for a new trainee, and it should success now. Compare with [QA](qa.register-trainee-teachers.education.gov.uk)
* ~Does this PR introduce any PII …

[3839] Fix undefined method 'recruitment_cycle_year' for nil:NilClass

---

app/lib/dqt/params/award.rb
app/services/dqt/recommend_for_award.rb
spec/lib/dqt/params/award_spec.rb
spec/services/dqt/recommend_for_award_spec.rb

Small change in the DQT API that we hadn't picked up.
birthDate is a URL querystring parameter. We were passing it in the body payload.
The docs haven't been updated yet but I've discussed this with @gunndabad

[3787] Fix recommend for award path

---

app/controllers/system_admin/user_lead_schools_controller.rb
app/forms/system_admin/user_lead_schools_form.rb
app/views/system_admin/user_lead_schools/_no_results.html.erb
app/views/system_admin/user_lead_schools/_results.html.erb
app/views/system_admin/user_lead_schools/index.html.erb
app/views/system_admin/user_lead_schools/new.html.erb
app/views/system_admin/users/show.html.erb
config/locales/en.yml
config/routes/system_admin_routes.rb
spec/features/system_admin/users/add_a_lead_school_to_user_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/users/add_lead_school.rb
spec/support/page_objects/users/lead_schools.rb

https://trello.com/c/y9iFHwee/3783-m-add-autocomplete-to-the-add-lead-school-form
- Based on the lead school's search for trainees, add a JS autocomplete to the lead school search for users.
- Add a non-JS backup route (checkboxes filtered by the user's query)
- Small styling fixes
- Route name change from `lead_schools` to `lead-schools` to match rest of app
- Sign in as a system admin
- Click the system admin link in the top right hand corner
- Click on the name of a user
- Click 'Add lead school'
- Search for a school (hint: there's lots of 'academy's)
- Search for a school by URN
- Search for a school by postcode
- Try submitting an empty field
- Try submitting a field with a search that returns no schools
- Select a school from the list and see that it saves to the user
- **Now turn …

[3783] Add autocomplete to the user's lead school form

---

app/controllers/pages_controller.rb
app/controllers/sessions_controller.rb
app/lib/user_with_organisation_context.rb
app/views/organisations/index.html.erb
config/locales/en.yml
config/locales/pages/no_organisation/en.yml
spec/factories/users.rb
spec/features/organisation_contexts_spec.rb
spec/lib/user_with_organisation_context_spec.rb

Trello ticket: https://trello.com/c/FINAuif9/3832-users-with-no-organisation-get-a-useful-message-when-they-try-to-login
When a user with no organisation set in the DB logs into Register, we redirect them to the organisations path and render the appropriate content to tell them they need to be added to an org.
* Add `current_user.no_organisation?` into organisation path redirect (`login_redirect_path`) in sessions controller
* Users with no org will then be redirected on login to the organisations index, which shows them a helpful message
I've updated Annie Bell on the review app so they are not linked to an organisation.
- Log in as Annie Bell, check that you see the organisations page with the no org content
- Log in as a system admin, check you see the home page as expected
- Log in as …

3832 Redirect users with no organisations yet

---

config/settings.yml
config/settings/qa.yml

We have a feature allowing users to belong to more than one organisation. It is currently turned off as we haven't 'launched' it yet.
* Turn it on
Poke about on the review app and make sure it's working. As the feature was already enabled in review this doesn't really test much. Ideally we need to confirm in production once this is merged.

[xxx] Enable mult-organisation feature

---

app/lib/dqt/params/trn_request.rb
spec/lib/dqt/params/trn_request_spec.rb

https://trello.com/c/rR3r5N1Z/3860-s-handle-undergrad-routes-not-having-degrees
- Change `Dqt::Params::TrnRequest` to not include `qualification` params if there's no degree

[3860] Handle undergrad routes not having degrees

---

config/analytics.yml

The field `provider_id.users` was removed in Jan and `course_code.trainees` in Oct 2021.
https://trello.com/c/ksR3kfIS/3869-remove-old-fields-from-analytics
Data Insights is doing some work to raise issues when fields show up or disappear unexpectedly, so there will be feedback if this change causes errors. Hard to test otherwise.
The fields in `analytics.yml` were also alphabetisation, but that's done in a separate commit for ease of review.

[3869] remove missing fields from analytics.yml

---

app/components/application_record_card/view.html.erb
app/components/application_record_card/view.rb
app/components/record_details/view.rb
app/controllers/base_trainee_controller.rb
app/models/trainee.rb
app/models/trainee_filter.rb
app/services/trainees/filter.rb
app/views/trainees/_filters.html.erb
app/views/trainees/_record_source_filter.html.erb
app/views/trainees/show.html.erb
config/locales/en.yml
spec/components/application_record_card/view_spec.rb
spec/components/record_details/view_spec.rb
spec/factories/trainees.rb
spec/features/trainee_actions/filtering_trainees_spec.rb
spec/models/trainee_spec.rb

For admin users we want to display the 'source' of each trainee record, it can be one of 
```
Manually entered
Imported from Apply
Imported from HESA
Imported from DTTP
```
1. For all users, show the filter on `/drafts`. 
2. Only for system-admin users, show the filter as an "Admin feature" 
3. For system admin users, on the trainee listing page, show the record source like so:
4. For system admin users, on the trainee show page, show the record source:
We've created the four types of trainee (manual, apply, DTTP, HESA) under Annie Bell, Provider A. With the current implementation, DTTP as a record source is hidden for non-admins. This was a previous design decision.
As Annie Bell:
- Navigate to draft trainees
- Observe you can see three record source filter types (manual, apply, HESA)
- …

[3780] show record source for admins

---

app/services/trainees/create_from_dttp.rb
spec/services/trainees/create_from_dttp_spec.rb

When we import trainees from DTTP we don't want to then send updates for all of them to DQT.
* set the dqt_update_sha on Trainee when we create from DTTP.

[3900] Set dqt_update_sha on import

---

db/data/20220324150013_initialize_dqt_update_sha.rb

We determine if a record needs to be sent as an update by setting a SHA of the record and then checking if it has changed. We need to initialize this before we turn on the DQT integration to avoid sending unnecessary updates.
* set dqt_update_sha in a data migration.

[3899] Initialize dqt_update_sha

---

config/settings.yml
config/settings/production.yml
config/settings/review.yml
config/settings/staging.yml

We are switching to using DQT for TRN/QTS directly this evening. We will no longer persist data to DTTP.
In all environments:
* Disable writing to DTTP
* Enable the DQT integration
* The sync from DTT flags are still true although we're not really relying on that now. We can fix that in a future PR
* We likely will still have `Retrieve(Trn|Award)` jobs scheduled. We should let them play out so check this flag change won't affect those 

[3899] Switch production to DQT

---

app/lib/hesa/code_sets/fund_codes.rb
app/lib/hesa/code_sets/genders.rb
app/lib/hesa/code_sets/itt_aims.rb
app/lib/hesa/code_sets/itt_qualification_aims.rb
app/lib/hesa/code_sets/service_leavers.rb
app/lib/hesa/code_sets/study_length_units.rb
app/lib/hesa/code_sets/study_modes.rb
app/lib/hesa/parsers/itt_record.rb
app/models/hesa/metadatum.rb
app/models/trainee.rb
app/services/trainees/create_from_dttp.rb
app/services/trainees/create_from_hesa.rb
app/services/trainees/map_state_from_hesa.rb
db/migrate/20220318111733_add_hesa_updated_at_to_trainees.rb
db/migrate/20220318112417_create_hesa_metadata.rb
db/schema.rb
spec/lib/hesa/parsers/itt_record_spec.rb
spec/services/trainees/create_from_hesa_spec.rb
spec/services/trainees/map_state_from_hesa_spec.rb
spec/support/api_stubs/hesa_api.rb

https://trello.com/c/Csx5hMPq/3778-l-hesa-set-states-correctly
- Fix gender mapping
- Fix state mapping
- Add missing TRN attribute
- Add new field `hesa_updated_at` to trainees to help with data analysis
- Fix `study_mode` mapping
- Remove deferral atributes (there is no defer date or reinstate date in HESA)
- Change the way `created_from_hesa` is set (it shouldn't be touched in future updates)
- Add new table `hesa_metadata` to store important information that can be use dby the funding department later on

[3778] Set HESA states correctly

---

terraform/workspace-variables/production.tfvars.json

Add DTTP portal route to PaaS for production, traineeteacherportal.education.gov.uk.
This is just adding the route, the DNS change will occur later.
https://trello.com/c/272NMS5W/3820-setup-dttp-portal-domains-on-govuk-paas
Add variable to production.tfvars.json
Confirm json & parameter value correct

Add DTTP portal route to PaaS for register-production

---

db/data/20220323125945_add_missing_dttp_import_providers.rb

https://trello.com/c/HWfETSWT/3851-s-add-missing-providers-to-production
- Add three new providers to Register needed for the import of a number of trainees from DTTP.

[3861] Add data migration to add missing providers for DTTP import

---

app/lib/dqt/client.rb

The DQT update endpoint returns a 204 with an empty body so `response.body` is nil. `JSON.parse(nil)` doesn't work.
If `response.body` is nil then return an empty hash.

[xxx] Handle DQT response with no body

---

service_unavailable_page/web/public/internal/index.html
service_unavailable_page/web/public/internal/traineeteacherportal.html

https://trello.com/c/EOTyueAG/3856-s-content-for-the-down-page-while-were-doing-the-import

[3856] Update content for service unavailable pages

---

config/initializers/bursary_tiers.rb
db/migrate/20220324162356_update_bursary_tiers_enum_values.rb
db/schema.rb
spec/models/trainee_spec.rb
spec/services/exports/trainee_search_data_spec.rb

https://trello.com/c/nhlFO3et/3859-m-renumber-the-bursary-tiers
* New migration to update existing `bursary_tier` (+1)
* Updated enums and test
* Check db if updated.

[3859] Renumber the bursary tiers

---

app/lib/dttp/parsers/account.rb
app/services/dttp/retrieve_providers.rb
db/migrate/20220325163438_add_response_to_dttp_providers.rb
db/schema.rb
spec/services/dttp/retrieve_providers_spec.rb

We sync provider records from DTTP. Previously, we only parsed out a few fields. Now we're about to decommission DTTP we want to store all of the fields returned as there are others we will use.
* Add a `response` column to `dttp_providers`. This is consistent with the other `dttp_` tables.
* When we sync providers, store the JSON for each provider in this table. 

[3733] Import accredited provider id from DTTP

---

app/models/degree.rb
app/models/trainee.rb
app/models/trainee_disability.rb

We strip surrounding spaces from some of the trainee fields when the user enters them.
* Expand the list to include address fields and other user entered data and strings that we may import from HESA, DTTP etc
* Add the stripping to `Degree` as well while we're at it 
* Fix a flakey spec 
* Enter a trainee address with extra spaces. They shouldn't be persisted to the database.

[3849] Strip trailing leading whitespace from address fields

---

app/controllers/pages_controller.rb
app/views/pages/dttp_replaced.html.erb
app/views/pages/start_traineeteacherportal.html.erb
config/locales/en.yml
config/locales/pages/dttp_replaced/en.yml
config/routes.rb
spec/controllers/pages_controller_spec.rb
spec/requests/traineeteacherportal_requests_spec.rb

https://trello.com/c/W0YDeJnK/3857-m-add-the-starttraineeteacherportal-page-content
- Update content for the page portal uses see when they are redirected to Register
- Update the path for that page to be `dttp-replaced` rather than `start_traineeteacherportal`
- Check the content on `/dttp-replaced`

[3857] Update content for dttp-replaced page

---

service_unavailable_page/web/public/internal/index.html

The old page didn't mention anything about the migration, and was probably intended for use after the migration is over.

[3856] updated the maintenance pages to match

---

config/settings.yml
config/settings/dttpimport.yml
config/settings/production.yml
config/settings/staging.yml

DTTP has been retired. To avoid DQT errors disable that in non-prod envs for now.
* Set all DTTP integration flags to false in settings.yml
* Remove all overrides from the env specific settings
* Enable DQT only in production for now
I'm trying to set all DTTP to off by default so just need to check I've not missed an override anywhere. 

[xxx] Update feature flags for post DTTP

---

app/components/funding/view.rb
app/lib/funding_manager.rb
app/models/trainee.rb
spec/components/funding/view_spec.rb
spec/models/trainee_spec.rb

https://trello.com/c/wlhtFAyO/3854-m-hide-funding-when-we-dont-have-the-funding-rules-in-register
- Don't render the funding row in the funding component if the trainee is from an academic year for which we have no funding methods in the database.
- Exception: still render the funding row if the trainee is on a tiered bursary. This type of bursary is not stored in the DB anyway.
- Update a trainee to have a start date in the 2018/19 academic year
- Check that there's no funding row on their profile
Example trainee: https://register-pr-2180.london.cloudapps.digital/trainees/dNTT4gbimVbFK9ZTDbuRRbtW
~* Does this PR change the database schema? If so, have you updated the …

[3854] Hide funding row for years we don't know the funding rules

---

app/lib/dttp/code_sets/routes.rb
app/services/trainees/create_from_dttp.rb
spec/factories/dttp/api_placement_assignment.rb
spec/services/trainees/create_from_dttp_spec.rb

This change will resolve a missing trainee on the EYITT - School Direct (Early Years) route
from https://github.com/DFE-Digital/register-trainee-teachers/pull/2191
Add the EYITT - School Direct (Early Years) route as an `INACTIVE_MAPPING`, and map it to early_years_postgrad (EYITT PostGraduate)

[3907] Map trainees on EYITT - School Direct (Early Years) to EYITT postgrad

---

app/controllers/system_admin/providers_controller.rb
app/models/provider.rb
app/views/system_admin/providers/edit.html.erb
app/views/system_admin/providers/new.html.erb
config/locales/en.yml
lib/tasks/example_data.rake
spec/factories/dttp/providers.rb
spec/features/system_admin/providers/creating_a_new_provider_spec.rb
spec/models/provider_spec.rb
spec/support/page_objects/providers/new.rb

https://trello.com/c/5D3EpkuN/3865-s-add-ukprn-field-to-provider-forms
* Added `ukprn` field to add provider form
* Added validation for `ukprn`
* Login as system admin and go to add new provider

[3865] Add UKPRN field to provider forms

---

app/controllers/system_admin/users_controller.rb
app/views/system_admin/users/index.html.erb
spec/features/system_admin/users/search_users_spec.rb
spec/support/page_objects/users/index.rb

Large user lists might be overwhelming for a system admin, so the option to search for users by last name/email address has been added 
New search box under system-admin/users that will filter the list down.

[3785] Add search by user last name and email

---

.github/workflows/build-and-deploy.yml
config/initializers/personas.rb
lib/tasks/example_data.rake
spec/factories/trainees.rb

https://trello.com/c/WOaGU49R/3852-m-add-some-hesa-trainees-and-an-hei-and-user-to-the-seed-data
- Update `example_data.rake` to create a new persona with some HESA trainees associated with a HEI (University) provider
- Open rails console and run `Trainee.where.not(hesa_id: nil).count` - expect 0
- Run `rake db:reset && rake db:seed && rake example_data:generate`
- Open rails console and run `Trainee.where.not(hesa_id: nil).count` - expect 169

[3778] Add some HESA trainees, HEI provider and user to the seed data

---

app/controllers/trainees/employing_schools_controller.rb
app/forms/schools/employing_school_form.rb
app/forms/schools/form.rb
app/forms/schools/lead_school_form.rb
app/views/trainees/employing_schools/_no_results.html.erb
app/views/trainees/employing_schools/_results.html.erb
app/views/trainees/lead_schools/_no_results.html.erb
app/views/trainees/lead_schools/_results.html.erb
config/locales/en.yml
spec/support/shared_examples/school_form_validations.rb

https://trello.com/c/wMpA9i2G/3798-bugs-with-school-picking-flows-part-1-3
As per the numbering (and 'before' screenshots on the ticket:
1. Show error on lead and employing schools form if query entered, no query selected and not applicable selected
2. Cannot reproduce
3. Validation styling on server-side search. Error message now linked to the no-JS results checkboxes.
4. Trainee name caption moved to correct place above h1 on no-JS no results pages
5. Fixed redirect after searching again with an empty search on the no-results no-JS employing school page
- Reproduce steps in Trello card, check all are fixed.
~* Does this PR change the database schema? If so, have you updated the …

[3798] Bugs with school picking flows part 1/3

---

app/views/trainees/personal_details/show.html.erb
spec/features/trainee_actions/viewing_an_existing_trainee_spec.rb

Before:
After:
As it says on the tin.

[3923] Hide add degree details button on non-awaiting action records

---

app/models/trainee.rb
app/services/dqt/trainee_update.rb
spec/jobs/dqt/recommend_for_award_job_spec.rb
spec/jobs/dqt/retrieve_trn_job_spec.rb

https://trello.com/c/UckdmbRv/3908-reset-dqtupdatesha-after-trn-and-award-receipt
- Set `dqt_update_sha` to `Trainee#sha` when TRN is received or Award

[3908] Reset dqt_update_sha after TRN and Award receipt

---

app/forms/subject_specialism_form.rb
app/views/trainees/subject_specialisms/edit.html.erb
spec/forms/subject_specialism_form_spec.rb

https://trello.com/c/NQxoCYfm/3878-subject-specialism-presence-validation-is-broken-for-updating-courses
- Tweak the `SubjectSpecialismForm` and view template
- Select non-draft trainee with existing course
- Change course with mulitple subject specialisms (e.g. art and design)
- Submit empty form

[3878] Fix: subject specialism presence validation is broken for updating courses

---

app/models/trainee.rb
config/analytics.yml
db/migrate/20220329160910_add_cohort_to_trainees.rb
db/schema.rb

We are going to filter on 'cohort' ie past, current and future. This logic is complicated so we're going to set the cohort as a state on trainee.
* Add `Trainee#cohort`. Default to 'current' for now. Logic for updating and maintaining this state will be added in further PRs. Adding this by itself to allow parallel work on the feature.

[3905] Add Trainees#cohort

---

app/lib/dttp/code_sets/degree_types.rb
db/data/20220401140852_map_degree_types_from_hesa_to_register.rb
spec/services/degrees/map_from_dttp_spec.rb

Rename the following HESA mappings to register equivalents:
```
BA (Hons) /Education => BA/Education
BEd (Hons) => BEd
BSc (Hons) /Education => BSc/Education
BTech (Hons) /Education => BTech/Education
BA (Hons) with intercalated PGCE => BA with intercalated PGCE
BSc (Hons) with intercalated PGCE => Bachelor of Science
BA (Hons) Combined Studies/Education of the Deaf => BA Combined Studies/Education of the Deaf
```
This gets rid of the "Degree type is missing" blue banner.
Map the HONS degree types to their non-hons register equivalents.
Add a data migration to update existing records.
* ~Does this PR change the database schema? If so, have you updated the config/analytics.yml file …

[3920] Add register equivalent mappings for some hesa degree types

---

app/models/trainee.rb
spec/models/trainee_spec.rb

Ensure publish courses are ordered alphabetically for manually added trainees. Right now the order can change based on the last created/updated course.
:eyes: 

[xxxx] Order publish courses by name for manually added trainees

---

app/views/layouts/trainee_record.html.erb

The HESA non-editable inset text is only being shown against trainees
that are not in awarded, recommended_for_award, or withdrawn states.
This is also hidden for lead school users, since they cannot edit
records anyway.
Add a check if the user is a provider user, and if the trainee is `awaiting_action?`.
I've set up all trainees on provider A as HESA trainees. as well as if you log in as a lead school user (look for these lovely people: Chadwick, Deanna, Johnathan, Jamika)

[3850] Hide HESA non-editable inset for non-editable trainees

---

app/webpacker/styles/_govuk_overrides.scss

When viewing the service at 400% on a 1280px display, our tables force content to overflow the background. This copies the approach used by the [GOV.UK Cookies page](https://www.gov.uk/help/cookie-details) to instead set the table to overflow.

Force tables to overflow-x

---

app/views/trainees/_action_bar.html.erb
app/webpacker/styles/trainee_list.scss

Swaps the html order of the sort links and export link to match the visual order - as raised by our accessibility audit.
NB: the layout is a bit awkward on mobile - we'll address that in a later PR.

Swap order of action links so it matches visual order

---

config/locales/en.yml

Our accessibility auditors have raised that the abbreviations in our visually hidden text aren't working - the html gets read out instead.

Remove abbr from hidden content

---

app/views/organisations/index.html.erb
config/locales/en.yml

Fixes an issue identified in our accessibility audit - missing page title.
We've copied the pattern seen in other pages. Let us know if we did it wrong!

Add page title and use translation file

---

app/controllers/base_trainee_controller.rb
app/controllers/trainees_controller.rb
app/models/trainee_filter.rb
app/services/trainees/filter.rb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/trainees/_cohort_filter.html.erb
app/views/trainees/_filters.html.erb
app/views/trainees/apply_applications/trainee_data/edit.html.erb
app/views/trainees/check_details/show.html.erb
app/views/trainees/outcome_details/recommended.html.erb
app/views/trainees/review_drafts/show.html.erb
app/views/trn_submissions/show.html.erb
config/locales/en.yml
lib/tasks/example_data.rake
spec/controllers/trainees_controller_spec.rb
spec/factories/trainees.rb
spec/features/trainee_actions/delete_trainee_spec.rb
spec/features/trainee_actions/filtering_trainees_by_cohort_spec.rb
spec/features/trainee_actions/filtering_trainees_spec.rb
spec/features/trainee_actions/recommending_for_qts_spec.rb
spec/features/trainee_actions/submit_for_trn_spec.rb
spec/support/page_objects/trainees/index.rb

https://trello.com/c/KwLaruTJ/3909-cohort-filter-front-end-basic-implementation
- Add basic three checkbox filter on draft and registered trainees
- Only show cohort options that are relevant for that provider's trainees
- Don’t show filter if provider has one cohort
- Auto-select ‘current’ when linking through to drafts/registered trainees.. but clear if you press ‘clear filters’
- Pick a provider with no Apply drafts (because these are the future trainees)
- Check that there is no cohort filter
- Pick a provider with Apply drafts (because these are the future trainees)
- Check that there is a cohort filter and that this works
- Click the 'Draft' and 'Registered' tabs
- Check that the default is that 'current' cohort is applied
~* Does this PR introduce any PII fields that need to be …

[3677] Add cohort filter

---

db/data/20220331152016_fix_lead_schools_not_applicable.rb

https://trello.com/c/tQ12RExk/3918-bug-dttp-import-many-records-of-teaching-apprenticeships-are-missing-a-lead-school
- Data migration to fix DTTP trainess that have an employing school but the lead is 'not applicable'

[3918] DTTP import fix: many records of teaching apprenticeships are missing a lead school

---

app/jobs/trainees/queue_cohort_updates_job.rb
app/jobs/trainees/set_cohort_job.rb
app/models/academic_cycle.rb
app/models/trainee.rb
app/services/trainees/set_cohort.rb
config/sidekiq_cron_schedule.yml
spec/factories/trainees.rb
spec/jobs/trainees/queue_cohort_udpates_job_spec.rb
spec/jobs/trainees/set_cohort_job_spec.rb
spec/models/academic_cycle_spec.rb
spec/models/trainee_spec.rb
spec/services/trainees/set_cohort_spec.rb

Trainees can be considered:
past: they have completed their training (or withdrawn) prior to the current academic cycle
current: they are still training or deferred or have withdrawn or been awarded in the current cycle
future: they start after the end of the current cycle
Changes to the trainee record (e.g. ITT start date or a status change) or a change in the current academic cycle can cause this status to change.
* Add `Trainees:SetCohort`, a service that sets the `Trainee#cohort` field based on the current cycle and trainee state
* Add a job to call this async
* Add a nightly job to run through current and future trainees and update their cohort to ensure this is correctly set
* Add a callback to set the cohort when the trainee is saved
* Add `AcademicCycle.current` to make it easier …

[3905] Maintain cohort state

---

app/controllers/system_admin/dttp_trainees_controller.rb
config/routes/system_admin_routes.rb

We have an archive of DTTP data saved in the database that we have
created trainees from.
Expose the json at:
```
/system-admin/dttp-trainees/<slug>
/system-admin/dttp-trainees/<slug>/placement_assignments
```
This will help when troubleshooting the import
We don't have the DTTP import responses in non-prod environments. This is a system admin feature so just check that it can't be accessed without being logged in as an admin. The actual functionality will need to be tested locally or we can check when it gets to production.

[xxx] Expose DTTP data for system_admins

---

app/jobs/dttp/sync_accounts_job.rb
app/lib/dttp/parsers/account.rb
app/models/dttp/account.rb
app/services/dttp/retrieve_accounts.rb
db/migrate/20220406101914_create_dttp_accounts.rb
db/schema.rb
spec/services/dttp/retrieve_accounts_spec.rb

We have imported all accounts that belong to providers to dttp_providers but we've realised that there may be important data e.g. degree institution UKPRNs that we might want from other accounts.
So... let's import them all.
Once this is merged we'll run this manually as we have with the other entities.
* Add Dttp::Account
* Add Dttp::RetreiveAccounts
* Add Dttp::SyncAccountsJob
This is mostly copy-pasta 🍝 from the Provider version.

[3964] Import dttp_accounts

---

.github/actions/deploy/action.yml
.github/actions/smoke-test/action.yml
.github/workflows/smoke-test.yml

The smoke tests are mainly ran using workflow dispatch from the build workflow.  This makes the logs harder to follow and rerunning failed checks harder. 
https://trello.com/c/D6tyzjoj
This change refactors the workflow as a reusable action.
The `softprops/turnstyle` step has been removed, instead we rely on concurrency at the workflow level to prevent multiple tests running against the same environment (though with the current smoke tests only hitting the healthcheck endpoint this shouldn't be a concern at present).
- Check that smoke tests run as expected when:
- running as part of the `deploy_review` job
- deploying to an environment, eg QA, using the `deploy` workflow
- running manually using the `smoke-test` workflow against an environment, eg QA, and a review app
* Does this PR …

Refactor smoke test workflow as a reusable action

---

app/services/trainees/set_cohort.rb
spec/services/trainees/set_cohort_spec.rb

sentry error: https://sentry.io/organizations/dfe-teacher-services/issues/3167438207/events/latest/?environment=production&project=5552118
When the trainee's ITT start date is nil, we're getting an error when we try to set the cohort.
* When trainee.itt_start_date is nil, do nothing in SetCohort
* Trainees are set to current cohort by default
* Trainees with no ITT start date i.e. draft trainees will therefore be current cohort
* ~~Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?~~

[xxx] Fix SetCohort to handle when trainee.itt_start_date is nil

---

app/controllers/base_trainee_controller.rb
config/sidekiq_cron_schedule.yml
spec/features/trainee_actions/filtering_trainees_by_cohort_spec.rb

- Hide the cohort filter for now since we're not setting cohort correctly for many trainees
- Disable the overnight job because missing data on dttp_trainees means this currently fails for a lot of trainees

[xxx] Hide cohort filter and disable trainee cohort job

---

app/models/trainee.rb
spec/models/trainee_spec.rb

Remove the set_cohort callback which is causing lots of jobs to be kicked off.

[xxx] Remove set_cohort callback

---

app/services/exports/trainee_search_data.rb
spec/services/exports/trainee_search_data_spec.rb

Trello: https://trello.com/c/4lMWy4um/3954-s-hesa-records-in-register-add-record-source-to-csv-for-record-export
We've added record source to the csv export so providers can now see the source of their records.
* Use record_source on trainee model to find trainee record source
* Add record_source to trainee_search_data csv with correct formatting
* Log into review app as Annie Bell, provider A
* Navigate to registered trainees
* I have set three trainees to have record sources of DTTP, HESA and Apply (Porfirio Bayer, Sunshine Medhurst, Linwood Williamson respectively)
* Click on 'Export these records'
* Check the record source column in the export and make sure the above trainees have the correct record source against them
* Check formatting looks ok
* ~~Does this PR introduce any PII …

[3954] HESA records in Register - Add record source to CSV for record export

---

app/views/layouts/_cookie_banner.html.erb
config/locales/pages/cookie_policy/en.yml

Adds visually hidden text to give button more context for screen-reader users
Button now reads "Hide this `cookies` message".

Extra text on ‘Hide this message’ button

---

app/jobs/dqt/recommend_for_award_job.rb
app/jobs/dqt/register_for_trn_job.rb
spec/jobs/dqt/recommend_for_award_job_spec.rb
spec/jobs/dqt/register_for_trn_job_spec.rb

We send requests for TRN and recommendations for award to DQT. We don't want to do this for HESA records at the moment as it will incorrectly set the source of those records in DQT to register rather than HESA and stop them appearing in the ITT portal.
Until we iron this out we should not send them. There likely won't be any/many but if there are any notify slack so as we can work it out manually with the DQT team.
* Notify slack and noop for HESA records in the TRN requests and award recommendation.

[3949] Don't send TRN or award requests to DQT for HESA records

---

.github/actions/deploy/action.yml
.github/workflows/build-and-deploy.yml
.github/workflows/delete-review-app.yml
.github/workflows/deploy.yml

The bobheadxi/deployments GitHub Action is used to update deployment statuses, this is ineffective when deploying to persistent environments such as qa or prod.
This change removes that action from non-review app deployment workflows and uses the built in functionality instead.
Review apps continue to use the bobheadxi/deployments action.
- Check that the [environments page](https://github.com/DFE-Digital/teacher-training-api/deployments) is updated as expected including correct View Deployment link
- Check that delete-review-app workflow functions as expected
* Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you …

Set non-review envs to use job env for dep status

---

app/webpacker/scripts/global/nationality_select.js

The remove links said `Remove second nationality` - but this could be unclear if you've also already picked British or Irish.
This adds the word `additional` to hopefully make it clearer we're talking about these extra ones you've added. This follows a similar convention as seen in Register to vote.

Make text clearer that remove links refer to the additional nationalities

---

app/models/trainee.rb
app/services/trainees/filter.rb
spec/features/trainee_actions/filtering_trainees_spec.rb

Trello ticket: https://trello.com/c/Bwwap0XI/3914-trainees-show-up-when-filtering-by-incomplete-that-we-should-not-be-considering-incomplete
We hadn't quite got the right scope for incomplete/complete trainees when using record completion filter. I've now aligned it with the functionality of the incomplete badge, so that we consider withdrawn/recommended for award/awarded trainees or HESA records as complete even if they aren't technically submission ready in the data (`submission_ready: false`).
* Add new scopes in trainee model `:incomplete_for_filter` and `:complete_for_filter`
* Use these scopes in `submission_ready` method in `filter.rb` which returns the trainees for record completion filter
* `:complete_for_filter` checks if the record is submission ready, or is from HESA, or is …

[3914] Return complete and incomplete trainees correctly

---

app/views/system_admin/user_providers/new.html.erb

trello: https://trello.com/c/Pca1xgkB/3967-please-order-the-provider-list-in-system-admin-to-alph-order
It was raised by support that this list being un-alphabetical was leading to increased human error when adding providers to users.
* Add .sort to the provider drop down when adding a provider to a user
* Log into review app as an admin
* Navigate to system admin > users
* Click through on any user and select 'Add a provider'
* Observe the dropdown list of providers is now alphabetical
* ~~Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?~~

[xxx] Order provider select alphabetically when adding provider to user in system admin

---

app/forms/funding/bursary_form.rb
app/lib/funding_manager.rb
app/views/trainees/funding/bursaries/_grant_form.html.erb
app/views/trainees/funding/bursaries/_non_tiered_bursary_form.html.erb
app/views/trainees/funding/bursaries/_tiered_bursary_form.html.erb
config/locales/en.yml
spec/features/end_to_end/early_years_postgrad_journey_spec.rb
spec/features/form_sections/teacher_training_data/edit_bursary_spec.rb
spec/features/form_sections/teacher_training_data/edit_training_initiative_spec.rb

Ensure that the link to funding guidance is for the correct year relevant to the trainee
Prior to this PR the funding guidance link only went to the 2021/22 funding guidance. Now this link will go to the relevant years funding guidance based on the trainees ITT start date.

[3957] Add dynamic funding guidance link

---

.github/workflows/deploy.yml

Deploy workflow can run at the same time as the Build and Deploy workflow potentially creating conflicting deployments.
Add concurrency to prevent workflows running at the same time.

Add concurency to the deploy workflows

---

db/migrate/20220412173718_add_dttp_accounts_dttp_id_index.rb
db/schema.rb

I'm trying to sync the DTTP accounts entity set into Register.
Add a unique index on dttp_id on the dttp_accounts table. We use this to key an upsert so it has to have a unique index.

[xxx] Add unique index on dttp_accounts dttp_id

---

app/policies/trainee_policy.rb
db/migrate/20220407145510_add_read_only_to_users.rb
db/schema.rb
spec/policies/trainee_policy_spec.rb

Add a read only boolean to the provider users model and do not allow editing of records where this flag is enabled.
https://trello.com/c/LGmo5QAe/3943-read-only-admin-access
Migration to add read only boolean to users model; add check in TraineePolicy to check for this boolean and decide if user can edit records.
Create a user with read_only set to true and check you cannot edit records. 

3943 Add read only function for provider users

---

app/controllers/trainees/course_years_controller.rb
app/forms/apply_applications/confirm_course_form.rb
app/forms/apply_applications/trainee_data_form.rb
app/forms/contact_details_form.rb
app/forms/course_details_form.rb
app/forms/course_education_phase_form.rb
app/forms/diversities/disclosure_form.rb
app/forms/itt_dates_form.rb
app/forms/personal_details_form.rb
app/forms/publish_course_details_form.rb
app/forms/start_date_verification_form.rb
app/forms/trainee_form.rb
app/forms/trainee_start_date_form.rb
app/forms/trainee_start_status_form.rb
app/lib/route_data_manager.rb
app/services/trainees/update.rb
spec/services/trainees/update_spec.rb

We had added some callbacks to i) update DQT and ii) set the trainee cohort when a trainee is updated. These have been problematic and we've removed them.
This is an alternative approach with a service responsible for updating the trainee and doing those two things ^. We use this service when we want the full update and associated tasks.
This gives us the option of updating a trainee without doing those things, e.g. in a data migration, console etc and makes it explicit.
On the downside we need to make sure we use it at the right times.
* Add `Trainee::Update`
* Change the form objects to persist the trainee using the service
* Update some controllers
* We need to check that we're using this everywhere we need to
* There are some places e.g. the state transitions in `Trainee` where …

[3976] `Trainees::Update` service

---

app/services/trainees/create_from_dttp.rb
db/data/20220414085459_fix_employing_schools_not_applicable.rb
spec/factories/dttp/schools.rb
spec/services/trainees/create_from_dttp_spec.rb

Update CreateFromDttp services to handle not applicable lead/employing schools
Add code from https://github.com/DFE-Digital/register-trainee-teachers/pull/2207 to the `Trainees::CreateFromDttp` service.
Also add a data migration to do a similar thing for Employing schools.
I've ignored [these lines](https://github.com/DFE-Digital/register-trainee-teachers/blob/c23e53f9fcdac0736ac99cd5f602dc5a39dfdfb3/db/data/20220331152016_fix_lead_schools_not_applicable.rb#L30-L32) since the GIAS update should handle these in production.
- ~Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?~
- ~Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?~ …

[3962] Update CreateFromDttp services to handle not applicable lead/employing schools

---

db/migrate/20220413165608_add_default_timestamps_for_dttp_accounts.rb
db/schema.rb

When we sync DTTP data into our local tables we use `upsert` which doesn't automatically add timestamps. So... we need to default them in the DB.
* Add default timestamps for dttp_accounts 

[xxx] Add default timestamps

---

config/locales/pages/privacy_policy/en.yml

This link is the wrong colour because it's missing the `govuk-link` class.

Add govuk-link class to link

---

app/forms/concerns/course_form_helpers.rb
app/forms/course_details_form.rb
app/forms/publish_course_details_form.rb
app/models/trainee.rb
app/services/trainees/create_from_hesa.rb
config/analytics.yml
db/data/20220420131249_backfill_allocation_subject_dttp_ids.rb
db/data/20220420131423_add_deprecated_allocation_subjects.rb
db/migrate/20220419083227_add_course_allocation_subject_to_trainees.rb
db/migrate/20220419083257_add_dttp_id_and_deprecated_on_columns_to_allocation_subjects.rb
db/schema.rb
spec/factories/trainees.rb
spec/forms/course_details_form_spec.rb
spec/forms/publish_course_details_form_spec.rb
spec/services/trainees/create_from_hesa_spec.rb

https://trello.com/c/iYGaQtlA/3970-store-allocationsubject-on-the-trainee
- Add a reference to allocation subject to trainee
- Re-calculates allocation subject when a user changes course subjects
- Add `dttp_id` and `deprecated_on` column to `allocation_subjects` table
- Data migration to backfill the `dttp_id` column in `allocation_subjects` table
- Data migration to add deprecated allocation subjects (about 900 trainees have an allocation subject that's no longer available in the current mapping)
- Manual/console data migration to associate each trainee to an allocation subject (see below)
- Reseed the database: `rake db:reset && rake db:seed && rake example_data:generate`
- Choose a trainee from assessment only and salary direct
- Open the rails console and note the current allocation …

[3970] Store course allocation subject on the trainee

---

config/settings/production.yml

https://trello.com/c/OYfb2nvm/4038-turn-off-hesa-import
HESA has added additional security using MFA which is preventing our HESA import job from logging in and fetching the XML. It will be turned back on when we get a service account which allows us to bypass MFA.

[4038] Turn off HESA import

---

.github/workflows/delete-review-app.yml

A GitHub environment is created for each review app that is deployed, this environment persists after the review app is deleted.
- Add a step to the delete-review-app workflow to delete the environment
- Close PR to test delete process, reopen PR once tested
https://trello.com/c/ybnYhCK3

Delete GitHub environment along with review app

---

.github/workflows/build-and-deploy.yml
.github/workflows/build-nocache.yml

Move auditing of vulnerable gems out of the PR build pipeline into the nocache weekly pipeline. 
Remove the 'audit' step of the PR pipeline and move it to a weekly check.

[3950] move workflow into the nocache pipeline

---

.tool-versions
package.json
yarn.lock

Builds are failing as jest-environment-jsdom is no longer included in
whatever included it before.
* Upgrade yarn to 1.22.18
* Specify jest-environment-jsdom in package.json

[xxx] Fix jest dependency

---

terraform/modules/paas/data.tf
terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf

Add register-trainee-teachers.service.gov.uk routes to PaaS for each environment
- Define domain and routes in PaaS terraform configuration for service.gov.uk
Add domain register_service_gov_uk, route web_app_services_gov_uk_route
- Fix education.gov.uk tf route name
rename web_app_service_gov_uk_route to web_app_education_gov_uk_route
- test via make deploy-plan for each env
- check review app 

Add service.gov.uk routes to PaaS

---

app/lib/funding_manager.rb
config/initializers/allocation_subjects.rb
config/initializers/mappings/allocation_subject_to_specialism_mapping.rb
config/initializers/mappings/publish_to_allocation_subject_mapping.rb
db/data/20220422135555_add_new_allocation_subject_ancient_languages.rb
db/data/20220422135700_add_funding_methods_for_ancient_languages.rb
spec/components/funding/view_spec.rb
spec/factories/trainees.rb
spec/features/form_sections/teacher_training_data/edit_training_initiative_spec.rb
spec/forms/funding/form_validator_spec.rb
spec/lib/funding_manager_spec.rb

https://trello.com/c/hT2VezgT/3956-spike-add-new-ancient-languages-allocation-subject-and-remap-ancient-langauge-specialisms
- Update the `FundingManager` to use the new `course_allocation_subject` relationship on trainee
- Add `ANCIENT_LANGUAGES` to `AllocationSubjects` and move `Latin` and `Ancient Hebrew` and `classical Greek studies` under it.
- Data migration to add `ANCIENT_LANGUAGES` to the `allocation_subjects` table
- Another data migration to copy all the funding methods in the current academic year for "Classics" to "Ancient languages". This is to ensure if any trainee gets the allocation subject "Ancient languages", their funding remains the same.

[3956] Add new ancient languages allocation subject and remap ancient langauge specialisms

---

app/controllers/system_admin/dttp_providers_controller.rb
app/controllers/system_admin/providers_controller.rb
app/models/provider.rb
app/views/system_admin/providers/edit.html.erb
app/views/system_admin/providers/new.html.erb
config/locales/en.yml
db/data/20220422144717_backfill_provider_accreditation_id.rb
db/migrate/20220420095158_add_accreditation_id_to_provider.rb
db/schema.rb
lib/tasks/example_data.rake
spec/factories/dttp/account.rb
spec/factories/providers.rb
spec/features/system_admin/dttp_providers/list_providers_spec.rb
spec/features/system_admin/providers/creating_a_new_provider_spec.rb
spec/features/system_admin/providers/editing_a_provider_spec.rb
spec/support/page_objects/providers/new.rb

Providers have an 'accreditation_id'. We don't currently store this on our provider records. It is available in the DTTP data (`dfe_providerid` on the dfe_accounts entity set)
Funding refer to providers using this ID and we need to be able to look up a provider from the funding CSV uploads using it.
NB: we haven't added nullable: false or uniqueness constraints to the db table yet, this is because we want to run the backfill first before adding restrictions
* Add `accreditation_id` to providers table
* Migration to backfill existing provider accreditation IDs
* Add `accreditation_id` required field to views system admin > providers > new and system admin > providers > edit
* Add `dttp_provider_account` method to dttp_provider_controller so we can slice the `accreditation_id` when creating …

[4001] Add accreditation_ID to providers

---

app/components/status_card/view.html.erb

#2240 accidentally introduced a visible trailing space to the links. This uses a different approach of prepending the second item with a space (that doesn't render).
Before:
After:

Fix for errant space being shown visually in link

---

.github/actions/deploy/action.yml
.github/workflows/build-and-deploy.yml
.github/workflows/deploy.yml

The `API_TOKEN_FOR_GITHUB_ACTION` secret isn't needed for most workflows so it has been removed.  It is still required to delete review environments.
- Remove `actions-api-access-token` input from deploy workflow
- Check build & deploy workflow works as expected

Remove unneeded API_TOKEN_FOR_GITHUB_ACTION refs

---

app/models/funding/payment_schedule.rb
app/models/funding/payment_schedule_row.rb
app/models/funding/payment_schedule_row_amount.rb
app/models/funding/trainee_summary.rb
app/models/funding/trainee_summary_row.rb
app/models/funding/trainee_summary_row_amount.rb
app/models/provider.rb
spec/models/funding/payment_schedule_row_amount_spec.rb
spec/models/funding/payment_schedule_row_spec.rb
spec/models/funding/payment_schedule_spec.rb
spec/models/funding/trainee_summary_row_amount_spec.rb
spec/models/funding/trainee_summary_row_spec.rb
spec/models/funding/trainee_summary_spec.rb
spec/models/provider_spec.rb

We've added associations for the funding classes to `Provider` but they can't resolve the class. 
* Add the class
* Rename the association, removing the `funding_` prefix. (possibly a bit controversially on the `trainee_summaries` one. Open to convincing to not do that 😁 (UPDATE: it was controversial so I undid that bit)

[xxx] Fix provider associations

---

app/models/service_update.rb
app/views/pages/start.html.erb
db/service_updates.yml
spec/models/service_update_spec.rb

Add hesa review extension news to the news and guidance section. Additionally ensure that all updates within the last month are displayed on the homepage, not just the most recent update. 
https://trello.com/c/3cAni69E/4064-upload-hesa-review-extension-to-news-and-guidance
Check that guidance renders correctly.

4064 upload hesa review extension to news and guidance

---

app/jobs/degrees/create_from_dttp_placement_assignment_job.rb
app/lib/dttp/code_sets/institutions.rb
app/services/degrees/create_from_dttp_placement_assignment.rb

https://trello.com/c/f9xgRPny/4063-dttp-unmapped-degrees
There are 32095 trainees with no degree. Not all of them need one, but we having a problem of missing degrees. This is because the trainee has no DTTP degree qualifications to import from. The only other place with degree information is their DTTP placement assignment. This creates a new job to create a trainee's degree from their latest placement assignment.
We still have 3 missing instituions that cannot be found.
- Add missing institutions not available in the `dttp_accounts` table
- New job to create degree from trainee's latest DTTP placement assignment

[4004] Fix missing degrees

---

config/settings/dttpimport.yml

https://trello.com/c/aWhhE7oQ/4070-turn-on-hesa-import-for-dttp-import-environment

[4070] Enable HESA import for DTTP import environment

---

app/lib/dttp/code_sets/degree_types.rb
app/services/degrees/create_from_hesa.rb
db/data/20220505125913_fix_degree_types_form_hesa_data_import.rb
spec/services/degrees/create_from_hesa_spec.rb

https://trello.com/c/VXqjt6lu/4090-fix-incorrectly-mapped-degree-types
- Fix `Degrees::CreateFromHesa` so it maps the degree type hesa code to `Dttp::CodeSets::DegreeTypes::MAPPING`, not `Hesa::CodeSets::DegreeTypes::MAPPING`
- Data migration to fix the existing degree types that were import using `Hesa::CodeSets::DegreeTypes::MAPPING`

[4090] Fix incorrectly mapped degree types

---

app/lib/dttp/code_sets/course_subjects.rb
db/data/20220505113306_backfill_missing_course_subjects_from_dttp.rb

https://trello.com/c/nyuC7AOD/4091-itt-subject-not-recognised
- Adds more inactive course subject mappings for missing entity IDs
- Adds data migration to try to backfill all trainees who were created_from_dttp
with a missing course_subject_one
The data migration finds all trainees who were created from DTTP with a missing course_subject_one, finds the relevant mapping, and updates the trainee. If relevant, it also saved the original course name to the additional_dttp_data field on the trainee. 

[4091] Backfill missing course_subject_one from DTTP data

---

.github/workflows/build-nocache.yml

The build-nocache workflow is failing because outputs aren't being passed from the build job to the audit job.
Moved outputs from audit workflow to build workflow.
Review [test run](https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/2292801427) and confirm it works as expected (it is erroring on the bundle audit but these appear unrelated to the workflow definition).

Fixed outputs on build-nocache workflow

---

config/settings/sandbox.yml

After testing the redirect in staging, it's still not enabled for sandbox. Best to sort this out before we do prod.
Enable `education.gov.uk` -> `service.gov.uk` redirect in sandbox env.
DSI service config has been updated to add the `sandbox.register-trainee-teachers.service.gov.uk` domain

[4099] enable service domain redirect in sandbox

---

config/settings/production.yml

We've added and tested code to redirect `education.gov.uk` to `service.gov.uk`. This works in qa, review apps and staging.
Enable the redirect in prod.
Please consider whether any other configuration needs to be updated for this. I've added `www.register-trainee-teachers.service.gov.uk` to the sign-in and sign-out sections of the DFE Sign-In configuration, please also validate those changes if you can.

[4099] enable service domain redirect in prod

---

app/models/provider.rb
db/migrate/20220503114908_add_unique_constraint_to_accrediation_id_on_providers.rb
db/schema.rb
spec/features/system_admin/providers/creating_a_new_provider_spec.rb
spec/features/system_admin/providers/editing_a_provider_spec.rb

https://trello.com/c/joHq9QVg/4053-s-make-accreditation-id-unique-and-required-on-the-provider-model-and-at-the-db-level
- Add a unique constraint on accreditation_id on providers in the DB
- Add a unique validation on accreditation_id the providers model
- Uncomment tests for uniqueness checks
Note: There are a couple of test providers in production and lots in staging that currently have no accreditation_id. We could make up fake (but unique) ones for these providers, but in the interest of getting the uniqueness constraint in, I'm leaving the DB presence out for now.
- Sign in as an admin
- In the system admin interface, add an accreditation ID to a provider that already exists on another provider
- Check the error message is correct when you try and save …

[4053] Make accreditation_id unique on Provider

---

db/data/20220510084951_remove_trainee_duplicate_degrees.rb

trello ticket: https://trello.com/c/51qAPRcB/4092-some-trainees-have-duplicate-degrees
It was identified that some trainees imported from DTTP had duplicate degrees. These need to be removed so providers can check their data easily.
The data migration in this PR takes a couple of minutes to run. We decided to do this as a data migration so that we can keep track of this change to the data.
Note we've managed to remove approx. 6000 duplicates with this migration. We have identified some degrees that are not exact duplicates, but do look very similar (such as the subject name differing slightly), however these would need to be reviewed by the provider on a case by case basis to understand if they are actually duplicates/which one is the correct degree.
List of trainees, where some have …

[4092] Data migration to remove duplicate degrees

---

spec/factories/providers.rb

We've added a uniqueness check to accreditation_id on providers. This has caused a flakey test.
Ensure that when we create providers, we are creating a new accreditation ID by using a four-digit sequence. Providers will now be created like:
```
FactoryBot.build(:provider)
=> #<Provider accreditation_id: "1111">
=> #<Provider accreditation_id: "1112">
=> #<Provider accreditation_id: "1113">
...
```

[xxx] Ensure that accreditation IDs are most likely different

---

app/lib/hesa/code_sets/itt_qualification_aims.rb
app/services/trainees/create_from_hesa.rb
db/data/20220512110703_fix_postgrad_to_undergrad_trainees.rb
spec/services/trainees/create_from_hesa_spec.rb

https://trello.com/c/6jWIRQcH/4116-investigate-ug-vs-pg-incorrect-in-hesa-import
HESA do not distinguish between Provider-led UG and Provider-led PG, and we were assuming all Provider-led trainees are PG.
This PR:
- Updates CreateFromHesa service to look at the itt_qualification_aim to decide whether a provider_led trainee is
undergrad or postgrad
- Adds a data migration to fix affected trainees (TO COME)

[4116] Distinguish between PL UG and PL PG in HESA import

---

.github/workflows/database-backup.yml
.gitignore
.tool-versions
Makefile
bin/download-nightly-backup
bin/restore-nightly-backup
docs/disaster-recovery.md

A DR process is required to handle the loss of the database instance.
- Remove the timestamp on the database backup
- Add a DR process to docs and supporting make recipe and scripts to execute it
- Ensure the process meets the requirements in [technical guidance](https://technical-guidance.education.gov.uk/infrastructure/disaster-recovery/#loss-of-database-instance)
- The solution was developed on a Windows machine running Ubuntu 20 in WSL. It should tested on MacOS ideally or another distribution. A minimal test would be:
- execute the deploy-plan command documented in [recreate-the-lost-postgres-database-instance](https://github.com/DFE-Digital/teacher-training-api/blob/dr-doc-refinements/docs/disaster-recovery.md#recreate-the-lost-postgres-database-instance)
- execute the commands in …

Add dr docs database loss

---

app/jobs/trainees/set_cohort_job.rb
config/settings.yml
spec/jobs/trainees/set_cohort_job_spec.rb

We have a job that updates a trainee's cohort when the record is updated.
This job is failing and we're not ready for the actual feature yet so feature flag it and turn it off for now.

[4150] Add set cohort feature flag

---

app/models/hesa/student.rb
db/data/20220517132907_fix_trainee_ids_imported_from_dttp.rb
db/migrate/20220517105051_change_hesa_id_type_to_string_in_hesa_students.rb
db/schema.rb

https://trello.com/c/tGiv1UlF/4115-investigate-trainee-id-missing-or-incorrect-in-hesa-import
- Data migration to go through all the trainees that have a `Hesa::Student` record and check if the trainee ID's match. If not, we update the trainee record the trainee ID from `Hesa::Student`
- DB migration to change the `hesa_id` column on the `hesa_students` table to `string` , so we can do `Trainee.joins(:hesa_student)` without having to typecast
- Add the inverse relationship to `Trainee#hesa_student`, otherwise rails throws an exception
If you run this against prod database, 2026 trainees get affected. Migration takes about 3-5 minutes.

[4115] Fix trainee ID missing or incorrect in HESA import

---

Makefile
terraform/workspace-variables/production.tfvars.json
terraform/workspace-variables/qa.tfvars.json
terraform/workspace-variables/sandbox.tfvars.json
terraform/workspace-variables/staging.tfvars.json

Changes required as part of the move from education.gov.uk to service.gov.uk
- statuscake website_url updated to the service domain
- Add the service domain to the maintenance page
deploy-plan

Changes for register service domain

---

app/forms/course_details_form.rb
db/data/20220517120014_update_academic_cycle_dates.rb
spec/factories/academic_cycles.rb

The academic cycle should run 1 August to 31 July. However Register has it starting on 1 September.
- This PR adds a data migration to correct the dates for all instances of `AcademicCycle`.
- What are the knock-on effects of this change? I think this change will move a batch of trainees from the 2021 cycle to 2022 because `Trainee#academic_cycle` depends on which `AcademicCycle` the trainee's `commencement_date` or `awarded_at` fall in. (By my calculations there are about 4000 odd trainees have one of these values in August 2021.)

[4106] Add data migration to correct the academic cycle dates

---

app/services/trainees/create_from_hesa.rb
db/data/20220519090946_backfill_deferral_dates_for_hesa_trainees.rb
spec/services/trainees/create_from_hesa_spec.rb

https://trello.com/c/NkWnDd3G/4117-investigate-missing-dates-from-hesa-import
HESA doesn't send us a deferral date, but where available we can use the ENDDATE for deferred trainees.

[4117] Save deferral date during HESA updates

---

config/locales/en.yml

We list the personas on review and QA.
The description should say "responsible for... trainess" not "users"

[xxx] Persona page should say trainees not users

---

app/views/layouts/application.html.erb
app/views/trainees/outcome_details/recommended.html.erb
app/views/trn_submissions/show.html.erb
config/settings.yml
config/settings/production.yml

Ensure feedback link go to the new feedback survey form. Update banner with new form, remove feedback link from trn and qts successful pages.  Update footer so that feedback can be accessed from any page.

[4054] Update feedback survey link

---

db/data/20220519104858_backfill_itt_end_dates_for_hesa_trainees.rb

https://trello.com/c/NkWnDd3G/4117-investigate-missing-dates-from-hesa-import
Where a trainee has a hesa_student, and that hesa_student has an itt_end_date, update our trainee to have that same itt_end_date.
This will not fix the vast majority of trainees because itt_end_date is not required in HESA. But because of this, we don't show it anywhere in the UI.
We may add a further improvement to use study length (e.g. 1 year) which we do get from HESA to calculate and save the itt_end_date.

[4117] Backfill some missing itt_end_dates fro our raw HESA data

---

db/data/20220520150324_backfill_missing_education_phases.rb

https://trello.com/c/F69RQGhy/4108-dttp-missing-education-phase
- Data migration that fixes missing `course_education_phase` for Trainees that are not early years related and have an age range

[4108] Fix missing education phase

---

app/helpers/users_helper.rb
app/policies/user_policy.rb
app/views/layouts/application.html.erb
spec/helpers/users_helper_spec.rb
spec/policies/user_policy_spec.rb

Previously we were hiding the menu item and denying access to _Drafts_ if a user has a lead school even if they were system admins. This came to light on QA because the admin persona there cannot see Drafts.
This change permits system admins to always see Drafts by updating the `UserPolicy`. It also changes the menu rendering check to refer directly to the policy rather than via a helper so that the rules and front-end are easier to keep in sync.
- Is this the correct way to update the authorisation rules?
- Are the tests sufficient?

[4109] Fix admins cannot see draft trainees in QA

---

db/data/20220519162059_fix_primary_pe_subjects.rb

These trainees were submitted with PE as the course_subject_one but they are primary with PE. These should be fixed in HESA or they'll get overwritten in the next collection. Will raise that with the ops team.
Fix the subjects and allocation subjects.
The trainees should all belong to provider 227 and have course_subject_one as 'sports and exercise sciences' but an age range of 5 - 11.

[4118] Fix primary PE subjects

---

db/data/20220518155102_fetch_trns_from_hesa_records.rb

There are 43 trainees in production that have no TRN but do have a TRN
in the HESA data.
Update the trainee records with TRN from HESA where one is available.

[4044] Data migration to update TRN from HESA

---

app/controllers/funding/monthly_payments_controller.rb
app/controllers/funding/payment_schedules_controller.rb
app/models/academic_cycle.rb
app/view_objects/funding/payment_schedule_view.rb
app/views/funding/payment_schedules/_month_breakdown.html.erb
app/views/funding/payment_schedules/show.html.erb
app/views/layouts/application.html.erb
app/webpacker/styles/_govuk_overrides.scss
config/locales/en.yml
config/routes.rb
config/settings/test.yml
spec/features/funding/payment_schedule_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/funding/payment_schedule.rb
spec/view_objects/funding/payment_schedule_view_spec.rb

https://trello.com/c/bh4kk55Z/4080-l-funding-monthly-payments-page
* Add HTML and ruby logic to display the various tables starting from payments, predicted payments and finally the payment breakdown which are wrapped in accordian boxes
- The accordian UI is not exactly the same as the prototype. We're going with the latest `gov-uk` version
- Ralph and Maeve looked at the content for the funding stuff and decided to go with the term "Payment Schedule" in the UI instead of "Monthly Payments"
* Open the review app https://register-pr-2355.london.cloudapps.digital/ and log in as Denise Theominis
* Select provider on the org page
* Navigate to https://register-pr-2355.london.cloudapps.digital/funding/payments-schedule page
* Check that the design more or less matches the prototype
* Go back …

[4080] Funding payment schedule page

---

app/controllers/funding/trainee_summaries_controller.rb
app/view_objects/funding/trainee_summary_view.rb
app/views/funding/trainee_summaries/_bursaries.html.erb
app/views/funding/trainee_summaries/_grants.html.erb
app/views/funding/trainee_summaries/_scholarships.html.erb
app/views/funding/trainee_summaries/_summary.html.erb
app/views/funding/trainee_summaries/_tiered_bursaries.html.erb
app/views/funding/trainee_summaries/show.html.erb
config/locales/en.yml
spec/features/funding/trainee_summary_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/funding/trainee_summary.rb
spec/view_objects/funding/trainee_summary_view_spec.rb

Trello ticket: https://trello.com/c/03SxjJas/4081-m-funding-trainee-summary-page
This ticket adds the UI for the trainee summary page. In this ticket we expose more detailed information about bursaries, scholarships, EYITT bursaries and grants, if there are any for that organisation. This is to help organisations track their funding in Register.
For providers:
intro and summary:
burs:
schol:
EYITT:
For lead school:
intro and summary:
grants:
empty state for prov:
empty state lead school
* Add trainee_summary/show.html.erb and 5 partials, for bursaries, scholarships, grants, EYITT bursaries and a summary table
* Add methods `sort` and `empty?` to the TraineeSummaryView view object to order data and render the empty state respectively in the view
* Update `format_pounds` method to remove …

[4081] Trainee summary page UI

---

app/models/service_update.rb

The original trello card has been archived - but there was some discussion on Slack about only displaying the two most recent updates on the homepage. I've implemented that in this PR.
https://trello.com/c/6zBh71i1/4153-remove-old-news-and-updates-content
* Update `recent_updates` method so we only display the two most recent updates which have dates greater than 1 month ago
* View the sign in page on the review app
* Observe you only see two updates now

[4153] Display only two latest updates on start page

---

app/forms/course_details_form.rb
app/forms/language_specialisms_form.rb
app/forms/subject_specialism_form.rb
app/models/trainee.rb
config/initializers/academic_cycles.rb
config/initializers/training_routes.rb
db/data/20220509110941_seed_academic_cycles_for20222023.rb
db/data/20220510141655_add_funding_methods_for20222023.rb
db/seeds.rb
spec/models/trainee_spec.rb

https://trello.com/c/ojucDzfT/4041-add-academic-year-22-23-funding-rules
- Add 2022/23 rules in the initializer (i'm still not 100% that it should be living there.. but i've kept it as-is for now)
- Add data migration to add those funding methods to deployed envs
- Update the seeds to include three years of funding in the review envs
**Related course_allocation_subject bug fixes**
- Set `course_allocation_subject` on EY trainees as soon as they are created like we do for `course_subject_one` (otherwise their allocation subject is nil when it comes to funding)
- Following on from above, only set `course_allocation_subject` in the form if it's not an Early years trainee - otherwise this would re-set it to nil
- Set `course_allocation_subject` on subject specialism and language specialism …

[4041] Add funding rules for academic year 22/23

---

spec/jobs/hesa/retrieve_collection_job_spec.rb

I got an off by one second error here because the code under test runs
before we use Timecop to freeze time so if you are very unlucky the
clock will tick a second between the code running and the freeze.
Solution here is to just move the freeze to an `around` block that
should run before the `before` block.
A side-effect here is that we are freezing time for all examples in the given context rather than just the one that actually needs it. Is there a tidier way?

Fix flakey spec

---

config/locales/en.yml

There are accessibility issues with this tag and we expect that most
users should be familiar with this abbreviation. So it makes sense to
remove these tags.
Just remove the `abbr` tags that wrap _ITT_.
- Have I missed any?

[4023] Remove `abbr` tags for ITT

---

app/views/pages/accessibility.html.erb
app/views/pages/check_data.html.erb
app/views/pages/guidance.html.erb
app/views/pages/home.html.erb
app/views/sign_in/index.html.erb
app/views/system_admin/providers/users/delete.html.erb
app/views/system_admin/providers/users/new.html.erb
app/views/trainees/confirm_deletes/show.html.erb
app/views/trainees/course_details/edit.html.erb
app/views/trainees/course_years/edit.html.erb
app/views/trainees/degrees/edit.html.erb
app/views/trainees/degrees/new.html.erb
app/views/trainees/forbidden_withdrawals/show.html.erb
app/views/trainees/language_specialisms/edit.html.erb
app/views/trainees/outcome_details/confirm.html.erb
app/views/trainees/publish_course_details/edit.html.erb
app/views/trainees/subject_specialisms/edit.html.erb
app/views/trainees/training_details/edit.html.erb
config/locales/en.yml
spec/features/auth/sign_in_page_spec.rb

On a number of pages the page title does not match the level 1 heading on that page.
From the accessibility report:
"Users navigating the service will find that in some instances the page title does not follow the GOV Design System specifications. The page title in this case does not include the heading level one."
Pages identified on the card with mismatches are:
* Sign-in
* Home
* Training id
* Course details
* Delete this course record
See https://trello.com/c/fohMelgs/4022-page-headings-and-page-titles-dont-match-in-a-few-places
Note that some page titles are deliberately different to the level 1 headings. In particular we do not include any PII in page titles in cases where the headings do do so.
- Make the page title match the heading in the cases listed above.
- Identify any other …

[4022] Fix page heading / title mismatches

---

app/services/trainees/create_from_dttp.rb
db/data/20220526104624_add_missing_withdrawn_trainee.rb

https://trello.com/c/0PqA4b9l/4160-2021-2022-record-not-imported-into-register-from-dttp-sheffield-hallam-university
- Update `Trainees::CreateFromDttp` to accept a placement assignment other than the latest
- Fix `Trainees::CreateFromDttp` so it sets the `course_allocation_subject`
- Data migration to create a duplicate record of the trainee so it captures a previous placement assignment
- You can download the prod DB and run it against it. I did it already and it works as expected. Worth noting that the `trainee_id` is different for each record because it comes from the placement assignment.

[4160] 2021-2022 record not imported into register from DTTP

---

.github/workflows/build-and-deploy.yml

Add SNYK security scan of the docker image to the build workflow. 
It will scan on PR (but not for dependabot) and merge to main.
Any High (or above) vulnerability will cause the build workflow to fail,
and will need to be fixed (or excluded) for the build to continue.
https://trello.com/c/aqX2HVlk/338-scan-docker-images
Additions to the build-and-deploy workflow
Check workflow runs as expected

Add SNYK scan to build workflow

---

db/data/20220526104624_add_missing_withdrawn_trainee.rb

Staging is failing to deploy with the following error:
```
2022-05-30T13:35:17.33+0100 [APP/TASK/70c5c4f0/0] ERR rails aborted!
2022-05-30T13:35:17.33+0100 [APP/TASK/70c5c4f0/0] ERR StandardError: An error has occurred, this and all later migrations canceled:
2022-05-30T13:35:17.33+0100 [APP/TASK/70c5c4f0/0] ERR Couldn't find Dttp::Trainee with 'id'=29820
2022-05-30T13:35:17.33+0100 [APP/TASK/70c5c4f0/0] ERR /app/db/data/20220526104624_add_missing_withdrawn_trainee.rb:8:in `block in up'
```
This is the PR https://github.com/DFE-Digital/register-trainee-teachers/pull/2380, we didn't realise that data migrations also ran in the staging env.
Make `AddMissingWithdrawnTrainee` migration a noop if the trainee is missing in a deployed environment (e.g. staging)
- You can run this specific …

[xxx] Fix data migration for missing trainee

---

app/components/summary_card/style.scss

The summary card and the GDS summary list both add space to the bottom item - this means the last row of the summary card currently has too much whitespace. The prototype already had a fix for this but it wasn't applied to production.
Before:
After:

Tweak margin bottom on summary cards so there's less whitespace

---

app/views/layouts/application.html.erb
config/locales/en.yml
config/locales/pages/privacy_policy/en.yml
spec/support/page_objects/start.rb

This PR is just a wording change, from 'policy' to 'notice' on the 'Register privacy policy'.
See https://trello.com/c/OlU1TBW2/4052-change-wording-of-policy-to-notice-on-register-privacy-policy
- Change page title
- Change heading and content on privacy notice page
- Change link in footer to just be 'Privacy'
- Anything missing?

[4052] Wording change 'Privacy policy' to 'Privacy notice'

---

config/initializers/personas.rb
lib/tasks/example_data.rake
spec/factories/funding/payment_schedule_rows.rb
spec/factories/funding/payment_schedules.rb
spec/factories/funding/trainee_summaries.rb
spec/factories/funding/trainee_summary_rows.rb
spec/factories/schools.rb

https://trello.com/c/vKKZ5ktF/4180-update-exampledata-rake-to-include-funding-information
- Update factory for `payment_schedules` to create a full year's worth of payments, taking everything after the current month as predicted
- Update factory for `trainee_summaries` to create different types of rows (bursaries/scholarhips/tiers/grants)
- Use new factories in example_data.rake to create one trainee summary and one payment schedule for each provider / lead school associated with our personas.
- Update provider names to be more realistic
Payment schedule created today:
Payment schedule that would be created in September this year:
- Sign in with different personas and check the funding pages for each provider / lead school
NB: Please notify the #twd_data_insights team and ask for a review …

[4180] Update example_data.rake to include funding information

---

app/lib/dqt/params/trn_request.rb
spec/lib/dqt/params/trn_request_spec.rb

The DQT API can now accept the same gender codes as Register.
* Update the params.
* Stop mapping gender_not_provided to Other on the TRN request that's made to DQT.
* Introduce gender_not_available as a new code that HESA are introducing soon.
Thanks @benilovj for the original PR 👏

[xxx] Update the gender codes due to changes in the DQT API

---

app/view_objects/funding/payment_schedule_view.rb
app/views/funding/payment_schedules/_month_breakdown.html.erb
app/views/funding/payment_schedules/show.html.erb
spec/view_objects/funding/payment_schedule_view_spec.rb

On the funding payment schedule page we display a list of summary tables by month in an accordion component. We want the last actual month to be open when the user visits the page.
* Use the govuk_accordion component
* Add `last_actual_month?` boolean to the `MonthBreakdown` struct that we return from the view object
* Expand the last actual month accordion element
* Update the formatting of the subheading to render the full month name. It was rendering an abbreviated version e.g. Jun

[4189] Payment schedule accordion behaviour

---

app/services/funding/payable_trainee_summaries_importer.rb
lib/tasks/funding.rake
spec/services/funding/lead_school_trainee_summaries_importer_spec.rb
spec/services/funding/provider_trainee_summaries_importer_spec.rb

With the current implementation of the funding rake tasks `import_provider_trainee_summaries` and `import_lead_school_trainee_summaries` if there is an unrecognised provider accreditation ID or lead school URN in the csv (i.e. it doesn't exist in the DB), the rake task will abort at the point that it hits this organisation.
We want to handle such errors, continue the import and report any missing ids at the end of the task.
- This PR is very closely related to https://github.com/DFE-Digital/register-trainee-teachers/pull/2384/files . I've tried to use the approach suggested in comments on that PR.
- I'm not too sure about putting extra logic in the rake tasks because it's not covered by any automated tests. I've tested both rake tasks manually.
NB: Please notify the #twd_data_insights …

[4178] Trainee summaries import: skip missing providers and lead schools

---

app/view_objects/funding/trainee_summary_view.rb
app/views/funding/_navigation.html.erb
app/views/funding/payment_schedules/show.html.erb
app/views/funding/trainee_summaries/_tiered_bursaries.html.erb
app/views/funding/trainee_summaries/show.html.erb
config/locales/en.yml
spec/view_objects/funding/trainee_summary_view_spec.rb

https://trello.com/c/ZKEGWHsN/4183-trainee-summary-view-bugs
* Update the page title to 'Funding - Trainee summary 2021 to 2022'
* Correct the typo on the Summary table - 'ITT scholarships'
On the EYITT table:
* Make the table full-width (like the bursaries and scholarships tables)
* Add a new first column which displays the route
* Sort table by route and then tier 
- View the funding trainee summary for a provider
- Check that the above issues have been addressed

[4183] Trainee summary view bugs

---

app/view_objects/funding/payment_schedule_view.rb
app/views/funding/payment_schedules/_month_breakdown.html.erb
app/views/funding/payment_schedules/show.html.erb
config/locales/en.yml

https://trello.com/c/dN9vrcwM/4188-payment-schedule-view-bugs
- Add header to empty state page
- Fix typo in para on empty state page
- Add space between minus sign and currency delimiter
- Changed monthly breakdown column name from "Running total" to "Running total for payment type"
Note: page title changed in this PR https://github.com/DFE-Digital/register-trainee-teachers/pull/2392
- View a funding payment schedule and check the above points

[4188] Payment schedule view bugs

---

app/services/funding/payable_payment_schedules_importer.rb
lib/tasks/funding.rake
spec/services/funding/lead_school_payment_schedules_importer_spec.rb
spec/services/funding/provider_payment_schedules_importer_spec.rb

https://trello.com/c/gvr8epcX/4179-payment-schedule-import-skip-providers-and-lead-schools-that-do-not-exist-and-report-them-at-end
- Change `Funding::PayablePaymentSchedulesImporter` so it doesn't blow if a provider or lead school is missing. It instead tracks the missing organisations and reports them after the import
- Download a local copy of the prod DB
- Open the each CSV and pick an ID (files are attached to the Trello card)
- Open the console and find the provider and school for each ID
- Change the ID so the import won't be able to find it
- Run the follow rake tasks
```
rake funding:import_lead_school_payment_schedules["SDS_Profile_Apr.csv",1]
```
and
```
rake funding:import_lead_school_payment_schedules["SDS_Profile_Apr.csv",1]
```
- After the import is finished, it should …

[4179] Skip providers and lead schools that do not exist and report them at end

---

spec/features/system_admin/users/add_a_lead_school_to_user_spec.rb

This test is flakey due to random school names generated by Faker.
Hard code list of school names to avoid two potential sources of bugs:
1. Duplicate names that cause the assertion that the autocomplete contains exactly one match to fail.
2. Names that start with the same characters, e.g. _Lakeacre High_ and _Lakeacre High School_ causing the wrong school to be selected in the autocomplete.
I tried using `minimum: 1` rather than `count: 1` in the assertion but this causes other issues. Also using `unique` in the factory causes many other tests to fail.

Fix flakey spec for lead school autocomplete

---

app/view_objects/funding/payment_schedule_view.rb
spec/view_objects/funding/payment_schedule_view_spec.rb

Currently the predicted payment running total is starting at 0 instead of carrying on from the actual payment running total.
We need to make sure we are adding the last running total on the actual payments to the predicted payment running total.
- Is this all that needs to be done? Are there other places that we make this calculation?

[4185] Include actual payments in predicted payments running total

---

app/forms/course_details_form.rb
spec/forms/course_details_form_spec.rb

https://trello.com/c/YXc61urj/4216-if-the-allocation-subject-of-a-trainee-changes-away-from-what-the-attached-publish-course-has-we-should-delete-publish-course-re
- Update `CourseDetailsForm#update_trainee_attributes` to nullify `Trainee#course_uuid` if the course allocation subject is changed via manually changing the subject specialism
- Choose a provider-led draft trainee
- Enter the course details section and change the subject
- The course information section of the summary should now display "Course details added manually" instead of the course name and code

[4216] Remove reference to published course if subject specialism is changed manually

---

app/views/organisations/index.html.erb

The organisation picker can have multiple lead schools and accredited bodies. The lead school formatting was broken.
Move <li> tag into the loop.

[xxx] Fix multiple lead school formatting

---

app/components/service_update/view.html.erb
app/components/service_update/view.rb
app/views/pages/start.html.erb
spec/components/service_update/view_spec.rb

https://trello.com/c/dTGtDNFx/4202-headings-for-service-updates-are-in-illogical-order-on-the-start-page
- `ServiceUpdate` can now be initialized with optional `title_tag` string
- `title_tag` defaults to 'h2'
- `title_tag` must be valid <h?> tag i.e. 1-6, otherwise it defaults to h2
- `title_tag` determines what html tag to use for the title only
- Check `/service-updates` and see that titles of updates are still all `<h2>`
- Check start page and see that titles of updates are now all `<h3>`

[4202] Add title_tag attribute to our ServiceUpdate component

---

app/controllers/funding/trainee_summaries_controller.rb
app/services/exports/funding_trainee_summary_data.rb
app/view_objects/funding/navigation_view.rb
app/views/funding/payment_schedules/show.html.erb
app/views/funding/trainee_summaries/show.html.erb
config/locales/en.yml
spec/factories/funding/trainee_summary_rows.rb
spec/features/funding/trainee_summary_spec.rb
spec/services/exports/funding_trainee_summary_data_spec.rb
spec/support/page_objects/funding/trainee_summary.rb

Add csv export function for trainee summary, The rows are the payment details per route and course combinations. 
Adding the button in to actually download the csv still needs to be done, Could use advice on where this needs to go.
Add a csv exporter class that consumes a trainee_summary and produces a csv
Download csv link: 
Csv Output:

[4182] export for trainee summary

---

app/services/exports/funding_schedule_data.rb
spec/services/exports/funding_schedule_data_spec.rb

This is a follow-up to https://github.com/DFE-Digital/register-trainee-teachers/pull/2401 to sanitise CSV data making it more consistent with other CSV exports.
Add sanitisation of vulnerable characters in `Exports::FundingScheduleData`.
Should we generalise this by extracting the sanitisation logic into a service class of some sort? (in a follow-up PR).

[4185] Sanitise CSV output in payment schedule export

---

app/controllers/trainees/degrees/type_controller.rb
app/views/trainees/degrees/new.html.erb
spec/features/form_sections/personal_and_education_details/degrees/adding_degree_spec.rb
spec/support/page_objects/trainees/new_degree_details.rb

This PR attempts to fix an issue with the back link in the new degree flow in which the degree type selection is lost when navigating back to it from the degree details page.
Because the new degree record is not persisted until the user completes the details form we have to pass the original degree type selection (uk or non-uk) explicitly (as a URL param) and read this into the model before rendering the form.
- Is there a simpler way to do this?

[4021] Preserve selection of degree type when navigating back

---

app/view_objects/funding/navigation_view.rb

Url on the trainee summary path shows .html at the end. This should be removed

[4245] remove .html from trainee summary path

---

app/controllers/pages_controller.rb
app/views/layouts/application.html.erb
app/views/pages/privacy_notice.html.erb
config/locales/en.yml
config/locales/pages/data_sharing_agreement/en.yml
config/locales/pages/privacy_policy/en.yml
config/routes.rb
spec/features/static_pages_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/base.rb

https://trello.com/c/55UX3DRp/4191-change-the-register-privacy-notice-url-from-policy-to-notice-and-redirect-the-link
- Update the footer link and data sharing agreement link to go to /privacy-notice
- Rename all methods and files to reference notice rather than policy, for tidyness
- Redirect old /privacy-policy to /privacy-notice
- Click the Privacy link in the footer
- Check that it goes to /privacy-notice
- Directly access /privacy-policy via the browser
- Check that this redirects to /privacy-notice

[4191] Change /privacy-policy to /privacy-notice

---

db/migrate/20220615133237_add_start_and_end_academic_cycle_to_trainees.rb
db/schema.rb
package.json
yarn.lock

https://trello.com/c/9jBdTZQD/4255-s-add-start-academic-cycle-and-end-academic-cycle-to-trainees
We will be implementing a start year / end year filter for trainees. This is the start of that piece of work, allowing us to associate the trainee to academic cycles.
- Creates a migration that adds two foreign keys to the trainees table, both to table 'academic_cycles':
-  start_academic_cycle
- end_academic_cycle
🚢 

[4255] Add start_academic_cycle and end_academic_cycle to trainees

---

app/jobs/hesa/upload_trn_file_job.rb
app/lib/hesa/client.rb
app/models/hesa/trn_submission.rb
app/services/hesa/upload_trn_file.rb
config/settings.yml
db/migrate/20220616093411_create_hesa_trn_submissions.rb
db/schema.rb
spec/factories/hesa/student.rb
spec/factories/trainees.rb
spec/jobs/hesa/upload_trn_file_job_spec.rb
spec/lib/hesa/client_spec.rb
spec/services/hesa/upload_trn_file_spec.rb

https://trello.com/c/qMssCMFv/4217-l-trn-requests-from-hesa
- New service `Hesa::UploadTrnFile` that takes care of the file upload of TRN data to HESA
- New model `Hesa::TrnSubmission` to log the HESA uploads
- New background job to to run all this
The code was tested against the real API endpoint and return a 200 with the body containing the text "True". I'm assuming it works, but we'll need to try it out with real data to be 100% sure.

[4218] Send TRNs to HESA

---

app/views/funding/trainee_summaries/show.html.erb

Bad merge or something - the back link was refactored into a funding/navigation partial but remained in the main view too.
Remove the back link from the main view, keep it in the shared partial.
On the trainee summary view:
Before:
After:

[xxx] Remove double back link from trainee summary

---

app/services/exports/funding_trainee_summary_data.rb
spec/services/exports/funding_trainee_summary_data_spec.rb

We create a CSV from trainee summary data. The rows of that data sometimes have no associated amounts. We need to not error in that situation and also not display them in the export.
* Skip the amount-less rows

[4270] Skip funding rows without amounts

---

app/lib/dqt/params/trainee_request.rb
app/lib/dqt/params/trn_request.rb
spec/lib/dqt/params/trainee_request_spec.rb

Add 'husid' field to the trn request and update endpoints. This field is not implemented yet on the DQT side but will be added soon.
Add 'husid' field to request body of trn request and update actions.

[4221] Add hesa id to trn request

---

app/controllers/funding/payment_schedules_controller.rb
app/helpers/exports_helper.rb
app/models/funding/payment_schedule.rb
app/services/exports/funding_schedule_data.rb
app/services/exports/funding_trainee_summary_data.rb
app/services/exports/trainee_search_data.rb
spec/models/funding/payment_schedule_spec.rb
spec/services/exports/funding_schedule_data_spec.rb
spec/services/exports/funding_trainee_summary_data_spec.rb

Fix small issues with the csv exports: 
* the filenames should match the prototype e.g.
* west-park-primary-school-payment-schedule-2021-to-2022.csv
* west-park-primary-school-trainee-summary-2021-to-2022.csv
* the lead school trainee summary shouldn't include the 'lead school' column
* the vulnerable character escaping is rendering `'` characters into the CSV that are visible to the user

[4246] funding csv exports

---

app/helpers/funding_helper.rb
spec/components/sections/view_spec.rb
spec/factories/trainees.rb
spec/features/end_to_end/assessment_only_journey_spec.rb
spec/features/end_to_end/early_years_assessment_only_journey_spec.rb
spec/features/end_to_end/early_years_postgrad_journey_spec.rb
spec/features/end_to_end/early_years_salaried_journey_spec.rb
spec/features/end_to_end/opt_in_undergrad_spec.rb
spec/features/end_to_end/pg_teaching_apprenticeship_journey_spec.rb
spec/features/end_to_end/provider_led_postgrad_journey_spec.rb
spec/features/end_to_end/provider_led_undergrad_journey_spec.rb
spec/features/end_to_end/school_direct_salaried_journey_spec.rb
spec/features/end_to_end/school_direct_tuition_fee_journey_spec.rb
spec/features/end_to_end/teach_first_journey_spec.rb
spec/lib/funding_manager_spec.rb
spec/support/features/training_route_steps.rb
spec/support/shared_examples/rendering_the_funding_section.rb

This fix is related to these two trello tickets: 
https://trello.com/c/sScbSWdC/4201-funding-early-years-salaried-doesnt-show-grant-funding-question-unless-youve-filled-in-course-details
https://trello.com/c/gYvAknvX/4203-funding-page-crashes-if-you-visit-funding-before-filling-in-course-details
For early years routes, we set the subject to `EARLY_YEARS_TEACHING`, which meant that  the original `cannot_start_funding?`  method returned false as course_subject_one was not blank. Therefore the funding section could be accessed before we had the academic year info.
I think it makes sense to prevent providers from filling out this section until we have an academic year for the trainee i.e. they've filled out the course details. This is what we do currently for other routes.
We first tried this …

[4201] Restrict access to funding link until we have an academic year

---

config/locales/pages/data_sharing_agreement/en.yml

We want to update the Register DSA so that Lead Schools can sign it in order to access Register and it makes sense to them.
Some parts of the existing DSA may cause Lead Schools to contact their trainees to ask permission to input their data, when the accredited body should have already done this.
- Just update the content

[4211] Update the Data Sharing Agreement

---

app/jobs/apply_api/import_applications_job.rb
app/lib/apply_api/client.rb
app/services/apply_api/retrieve_applications.rb
config/settings.yml
db/data/20220613001509_backfill_apply_application_sync_requests_recruitment_cycle_year.rb
spec/jobs/apply_api/import_applications_job_spec.rb
spec/lib/apply_api/client_spec.rb
spec/services/apply_api/retrieve_applications_spec.rb

This PR is dependent on https://github.com/DFE-Digital/register-trainee-teachers/pull/2423
We import applications from the Apply register API into our apply_applications table. There are a couple of problems with this.
1. We are in some cases requesting the wrong applications. The API has an `updated_since` parameter. We keep track of the last time we called the API (using a `ApplyApplicationSyncRequest` record) and use this to fill the `updated_since` next time. The logic here is wrong since we started calling the API multiple times for different recruitment cycles. We need to track the last successful call _per recruitment cycle_.2. 
2. The API itself has been failing, particularly when retrieving 2022 applications. This seems to be because the Apply API is timing out when retrieving …

[4228] Fix 2022 apply applications not being requested properly data migration

---

app/lib/dqt/params/trn_request.rb
spec/lib/dqt/params/trn_request_spec.rb

https://trello.com/c/ee2KkgeM/4283-fix-dqt-country-mapping
While investigating an issue with updating a trainee's DQT record, it was discovered that the country value was missing from the DQT payload. Further investigation revealed that the degree country data can sometimes have two variations of the same country, e.g. "Hong Kong" and "Hong Kong (Special Administrative Region of China) [Hong Kong]" or "Iran" and "Iran [Iran, Islamic Republic of]". The `Hesa::CodeSets::Countries::MAPPING` only holds one variation.
- Update `Dqt::Params::TrnRequest` to lookup country code using partial string search instead of the whole string

[4283] Fix DQT country mapping

---

app/services/trainees/set_academic_cycles.rb
spec/services/trainees/set_academic_cycles_spec.rb

Current end academic cycle estimation code predicts 2 months too long for course end date for course lengths 1 year or greater, update code to calculate the correct value.

[4284] Update end academic cycle estimation

---

app/services/funding/payable_payment_schedules_importer.rb
app/views/funding/payment_schedules/show.html.erb
spec/services/funding/lead_school_payment_schedules_importer_spec.rb
spec/services/funding/provider_payment_schedules_importer_spec.rb

For July each year the funding data will be all actual months and non-predicted.
* Update the import services to allow not passing of `first_predicted_month` to signify that there isn't one.
* Update the view to now render the title and header row of the 'predicted' section when there aren't any
Before:
After:
To test upload a payment schedule CSV and omit the first_predicted_month argument
e.g. `bundle exec rake "funding:import_provider_payment_schedules[<file-path>]"

[4167] Support no predicted months for funding

---

app/jobs/big_query/send_event_job.rb
config/initializers/big_query.rb
config/sidekiq.yml

This was removed prematurely, we need to clean out the job queues before
we disable this job and queue completely. This change re-introduces them
and once the queue is cleared of jobs, we can remove the queue from
Redis (if needed), and then remove this job.
Previous PR for this ticket removed `SendEventJob`.

[4239] restore SendEventJob for BigQuery

---

config/settings.yml

We had switched this off while working on fixes. Those fixes are now
deployed so we can re-enable synching for 2022.
There is a backlog of ~2K applications so the first time this runs we
will have to monitor this carefully.
- Just reinstates 2022 in the list of recruitment cycle years to sync.
- Anything missing?

[4228] Reinstate apply apply synching for 2022

---

app/helpers/exports_helper.rb
app/services/funding/payable_payment_schedules_importer.rb
spec/services/exports/funding_schedule_data_spec.rb
spec/services/exports/trainee_search_data_spec.rb
spec/services/funding/lead_school_payment_schedules_importer_spec.rb
spec/services/funding/provider_payment_schedules_importer_spec.rb

A user has reported some issues with funding data.
* some values are being weirdly rounded
* numeric values are being prepended by a 'weird' character and treated as text
* Strip commas from 'numeric' values to avoid them being truncated by `to_d`
* Remove the vulnerable character prefixing for now. We'll review how we're doing this and fix [trello](https://trello.com/c/vPp4EaD0/3334-rework-vulnerable-character-handling-in-funding-exports)
I've just removed the escaping tests as checking that a string had quotes seemed a bit tricky. We'll fix in the attached card.

[4291] Funding rounding issues

---

db/data/20220623151318_backfill_missing_institution_uuids.rb

https://trello.com/c/CZj7B0sf/4281-investigate-backfilling-of-missing-institutionuuids
- These degrees were still missing institution UUIDs after we ran
our big backfill based on HESA codes, names and name synonyms
- I've manually pulled the UUIDs from the list in the dfe-reference-data
gem
**Only merge after https://github.com/DFE-Digital/register-trainee-teachers/pull/2459 has been run, otherwise the rake task will unset the UUIDs**

[4281] Backfill missing institution UUIDs for remaining degrees

---

config/settings.yml
spec/factories/courses.rb
spec/factories/trainees.rb

We have a default course year setting which determines what year of courses we display when a user is setting course details on a trainee.
Set it to 2022 as most users will be adding trainees for next academic cycle now.
* The course list should default to 22/23 courses in the course details section.
* I did some possibly controversial defaulting in the factories to fix a few tests that broke once the year was incremented. 

[4282] Switch default course year to 2022

---

app/controllers/application_controller.rb
spec/controllers/application_controller_spec.rb
spec/controllers/sign_out_controller_spec.rb
spec/services/dfe_sign_in_users/update_spec.rb

When we authenticate users via DfE Sign-in (DSI) our service gets a callback from DSI immediately after successful authentication that we use to associate the session with a User record.
To match the correct User record we use the `email` address given by DSI to lookup the User record. We then update the `User#dfe_sign_in_uid` which is also provided in the callback by DSI.
We should be looking up the by `dfe_sign_in_uid` in the first instance, falling back to `email` only when no match is found. This will allow us to automatically handle any changes in a users email address (registered with DSI).
Note that we still need to be able to lookup by `email` for the first time that a new user logs in because at that stage we don't have their `dfe_sign_in_uid`.
- At the start of a user session we …

[4278] Lookup existing dsi users by UUID at signin

---

spec/features/end_to_end/provider_led_postgrad_journey_spec.rb
spec/features/trainee_actions/withdraw_trainee_spec.rb
spec/rails_helper.rb

Now we're getting to the end of an academic cycle, some trainees were being created in the next academic cycle.
Also, itt_end_date occuring in June 'threw up' some issues with tests filling in commencement dates of today (i.e. 1 July)
Fix the tests.

[xxx] Fix spec issues re itt_end_date / commencement date / trainees being created in the next academic cycle

---

db/data/20220629102150_backfill_hesa_updated_at_on_trainees.rb

Trello: https://trello.com/c/UW954uIW/4316-s-backfill-the-hesaupdatedat-field-from-the-hesastudents-table-to-the-trainees-table
Backfill the hesa_updated_at for hesa students on the trainees table. This is so we can show HEIs when the hesa trainees were updated on HESA which makes their data sign off easier.
* Add backfill for hesa_updated_at on trainees
* We've used the scope `imported_from_hesa` to find the right trainees. We're not sure if this is the right/best way to select those trainees
* We deployed this to the dttp import env and it looked to run fine. The deploy job took approx 9 minutes. 40235 trainees were updated 
* We checked in prod, and all hesa_trainees have a hesa_updated_at value
NB: Please notify the #twd_data_insights team and ask for a review if new fields are being …

[4316] Update hesa_updated_at on trainees

---

app/controllers/base_trainee_controller.rb
app/controllers/trainees_controller.rb
app/models/trainee.rb
app/models/trainee_filter.rb
app/services/trainees/filter.rb
app/views/trainees/_filters.html.erb
config/locales/en.yml
spec/features/trainee_actions/filtering_trainees_spec.rb
spec/models/trainee_filter_spec.rb
spec/models/trainee_spec.rb
spec/services/trainees/filter_spec.rb
spec/support/page_objects/trainees/index.rb

To enable us to update the squares on the home page we need a new 'Trainee status' filter on the registered trainees view. Add a filter with the following options:
* Course not started yet - non-draft trainees with ITT_start_date is in the future. This should only be visible if the user has trainees that are yet to start - **new trainee scope added to cover this case**
* In training - Default selected if there are no other filters. submitted_for_trn, trn_received, recommended_for_award and excluding course not started yet - **new trainee scope added to cover this case**
* Deferred - **existing trainee scope exists to cover this case**
* Awarded - **existing trainee scope exists to cover this case**
* Withdrawn - **existing trainee scope exists to cover this case**
Remove old state filter …

[4252] Add status filter

---

db/data/20220630135320_correct_provider_codes.rb

https://trello.com/c/FNfaCnjE/4229-s-correct-provider-codes-on-register-in-the-registerproviders-table
Adds a data migration to fix some providers with incorrect codes.
Check against the spreadsheet in the ticket to check that I've copied them all over correctly.

[4229] Fix some incorrect provider codes

---

app/views/trainees/_filters.html.erb

We have filters. They are in the wrong order.
Put them in the correct order. Move start/end year filter above the record completion filter.

[xxx] Move start/end year filter

---

db/data/20220628122356_fix_missing_degrees_from_dttp.rb

There are a number of trainees in the database with missing degree records. It seems that quite a few of these could have been imported from DTTP because there are `Dttp::DegreeQualification` records that were synced from DTTP.
There are other cases where there are `Dttp::PlacementAssignment` records from which we could fill in more of the gaps.
This PR adds a data migration that fetches a list of trainees that do not have an associated `Degree` record but do have importable DTTP degrees. It then to run the `Degrees::CreateFromDttp` service on each trainee found.
This PR needs a bit more work and some sanity checking to make sure I've interpreted the data correctly. Specifically:
- Are there any reasons why the `Dttp::DegreeQualification` records picked out by the query in the migration …

[4298] Add data migration for unimported degrees from DTTP

---

Makefile

The -P command has been found to be incompatible on Mac OS. Updating to use awk.

Update the get-image-tag recipe

---

app/components/course_details/view.rb
config/locales/en.yml
spec/components/course_details/view_spec.rb

Now that we have an end academic cycle for HESA trainees we can display that as their expected course end date. The frontend has been updated with this information.
Add conditional to the ITT End Date section to display the expected end date for hesa trainees with an end_academic_cycle.

Add end date display for hesa records

---

app/forms/degree_form.rb
app/helpers/degrees_helper.rb
app/helpers/mappings_helper.rb
app/lib/dttp/code_sets/degree_types.rb
app/models/degree.rb
app/services/degrees/map_from_apply.rb
config/analytics.yml
db/migrate/20220630135252_add_uuid_columns_to_degrees.rb
db/schema.rb
spec/components/invalid_data_text/view_spec.rb
spec/factories/apply_applications.rb
spec/factories/degrees.rb
spec/factories/trainees.rb
spec/forms/degree_form_spec.rb
spec/helpers/degree_helper_spec.rb
spec/helpers/mappings_helper_spec.rb
spec/helpers/trainee_helper_spec.rb
spec/services/degrees/create_from_apply_spec.rb
spec/services/degrees/map_from_apply_spec.rb
spec/support/api_stubs/apply_api.rb

https://trello.com/c/3ccIySaQ/4305-m-set-uuid-fields-when-importing-from-apply
- DB migration to add `uk_degree_uuid`, `subject_uuid` and `grade_uuid` to degrees table
- Update `Degrees::MapFromApply` to use `DfE::ReferenceData`
- Fix various specs that broke after using `DfE::ReferenceData`. `DfE::ReferenceData` is slightly different than the DTTP codesets data. For example, names are sentence case, not title case.
- Add new database fields to `analytics.yml`

[4305] Set UUID fields when importing from Apply

---

db/data/20220705100148_backfill_hesa_updated_at_for_leading_zero_hesa_ids_on_trainees.rb

Trello ticket: https://trello.com/c/UW954uIW/4316-s-backfill-the-hesaupdatedat-field-from-the-hesastudents-table-to-the-trainees-table
The original backfill that we merged for this piece of work failed to backfill some of the `hesa_updated_at` for some trainees. This is because some trainee hesa_ids have leading zeros in the trainees table, but not in the hesa_students table.
In this ticket we format the `trainee.hesa_id` to remove leading zeros and then match to the `hesa_students` table.
The scoped trainees is about 31568. I'll run on DTTP import to see how many we manage to update and some of these are not present in the hesa_students table.
In the long term we should probably fix the data on `hesa_students` /fix however we added this data to `hesa_students` for next collection. I've …

[4316] Add backfill for hesa_updated_at on trainees which handles leading zeros on hesa_id

---

db/data/20220707105550_backfill_hesa_updated_at_for_dttp_trainees_on_trainees.rb

We realised there are a few trainees starting in this academic cycle that are HESA trainees, but came from DTTP. I wasn't able to backfill the `hesa_updated_at` from `hesa_students` for these, so I've taken it from the latest placement assignment instead.
I'm using `"dfe_hesamodifiedon"` or `"dfe_hesacreatedon"` in the latest placement assignment response to update the date.
* Backfill to add hesa_updated_at to hesa trainees that came from DTTP
* I've run this on DTTP import and it runs fast (3 mins to deployment)
* All 13 trainees have been updated with a `hesa_updated_at`
* There now shouldn't be any trainees starting this academic year without a `hesa_updated_at`

[4316] Use placement assignment data to add hesa_updated_at to hesa trainees created from DTTP

---

app/helpers/exports_helper.rb
spec/services/exports/funding_schedule_data_spec.rb

Trello ticket: https://trello.com/c/vPp4EaD0/4306-m-rework-vulnerable-character-handling-in-funding-exports
We had introduced some vulnerable character handling on the CSV exports. This was rendering numeric values starting with a minus sign as strings in Excel, which meant that providers could not easily manipulate their financial data.
In this PR I've reintroduced the vulnerable character handling but have added a regex to exclude numeric values starting with '-£' 
I've been reading the OWASP guidance which also suggests the below:
* Wrap each cell field in double quotes
* Prepend each cell field with a single quote
* Escape every double quote using an additional double quote
I originally implemented this but it looks horrible in some of the fields and made the data harder to use.
* Add …

[4306] Rework vulnerable character handling to render negative amounts correctly

---

app/services/degrees/fix_to_match_reference_data.rb
lib/tasks/fix_invalid_degrees.rake
spec/services/degrees/fix_to_match_reference_data_spec.rb

We used to use reference lists pulled from DTTP for the following degree fields:
institution
type (currently called 'uk_degree' in register 🤦)
grade
subject
User's picked from those lists and the string values were stored on the trainee model.
We are moving towards using the DfE::ReferenceData library for these lists and some no longer match so appear invalid, preventing users recommending their trainees.
In most cases the values either match a synonym in the reference data or are slightly differently cased.
We need to update the values we hold with their reference data equivalent.
We will do further work to add the UUIDs but that has not been included in this PR as this is a production issue that needs to be fixed.
* Add `Degrees::FixToMatchReferenceData` service. This service takes a …

[4352] Missing data not being recognised after being entered

---

app/controllers/trainees_controller.rb
app/helpers/filter_helper.rb
app/views/trainees/_selected_filters.html.erb
spec/features/trainee_actions/filtering_trainees_spec.rb

https://trello.com/c/5ua7Fnm6/4330-pre-select-in-training-filter-when-visiting-register-trainees-tab-with-no-filters-applied
When a user visits the registered trainee tab with no filters applied (eg using the header nav), we should pre-select the 'in training' filter. This is to show the most relevant trainees to the user.
- When navigating to the Registered trainees page with no filters applied, select in-training status by default
Check that the filter is applied when you click from the nav bar, from back buttons etc
Check that clearing the filters still works

[4330] Pre-select in-training filter

---

app/services/degrees/fix_to_match_reference_data.rb
lib/tasks/fix_invalid_degrees.rake
spec/services/degrees/fix_to_match_reference_data_spec.rb

We fixed the UK degrees so as the string values match the DfE::ReferenceData that we're using for validation. Turns out we need to fix the subject and grade on non-uk too.
* Support non_uk in the service. (It probably would be ok to just run the uk version but reduce the params for non_uk to be sure)
* Add a non_uk version of the rake task.

4352 missing data not being recognised after being entered part 2

---

app/lib/dqt/params/trn_request.rb
spec/lib/dqt/params/trainee_request_spec.rb
spec/lib/dqt/params/trn_request_spec.rb

https://trello.com/c/YmlyPtIj/4381-update-dqt-params-to-use-dfereferencedata-for-degrees
- We updated all degree subjects to use the name from the DfE::ReferenceData set
which may have been slightly different to our original lists from HESA
- This broke the params we were sending to DQT as we were still reverse-looking up
the subjects from the original list
- Update our params to look up the HESA code for the degree subjects from the
DfE::ReferenceData gem

[4381] Use DfE::Reference data for sending degree subjects to DQT

---

app/lib/hesa/code_sets/countries.rb

We look up HESA codes for non-uk degree countries to send to DQT.  We have a 'North Macedonia' degree that is currently stuck as we don't have a value for it.
Update the HESA codeset with 'North Macedonia' which replaced the previous value as per https://www.hesa.ac.uk/collection/c21054/a/nation

[4377] Fix 'North Macedonia'

---

app/services/degrees/create_from_hesa.rb
spec/services/degrees/create_from_hesa_spec.rb

HESA guidance tells users to select the country and leave the institution blank for UK degrees where the institution isn't present in the HESA codeset.
Our import is currently failing as we don't handle that https://sentry.io/organizations/dfe-teacher-services/issues/3422498115
* Update the `Degrees::CreateFromHesa` service to handle this. Set the degree as UK and leave the institution blank.
This is tricky to run locally without using production credentials. I have a failing XML file that I can share. We can run on dttpimport before deploying.

[4389] Handle UK degrees with no institution

---

app/services/trainees/create_from_hesa.rb
db/data/20220712142843_fix_course_education_phases.rb
spec/services/trainees/create_from_hesa_spec.rb

https://trello.com/c/8shswIbm/4369-l-fix-hesa-july-import-primary-with-trainees-to-be-primary-not-secondary
- Data migration for fix the `course_education_phase` for existing non-early years trainees
- Fix `Trainees::CreateFromHesa` to calculate `course_education_phase` using course age range
- Add missing "primary teaching" subject or move "primary teaching" to `course_subject_one` if neccessary
Out of 99459 trainees (excluding early years):
- 900 trainees have `course_education_phase` as `secondary` but `course_max_age` is less than 11
That data migration will correct this.

[4369] Fix HESA July import primary with trainees to be primary not secondary

---

config/settings/dttpimport.yml
config/settings/production.yml
config/settings/sandbox.yml

We are bulk importing lead school users and have an email to send them to tell them that they have been added to the system.
We don't want to email them again with the welcome email which is currently sent after they first login.
Disable it for now and we'll decide if we get rid of it altogether or send it at a different point.
* Set send_email feature flag to false in all environments
The flag is set to false by default in config/settings.yml

[xxx] Disable welcome email

---

Gemfile
Gemfile.lock
app/helpers/degrees_helper.rb
app/lib/dqt/params/trn_request.rb
app/models/degree.rb
app/services/degrees/fix_to_match_reference_data.rb
app/services/degrees/map_from_apply.rb
lib/tasks/fix_invalid_degrees.rake
spec/helpers/degree_helper_spec.rb
spec/lib/dqt/params/trainee_request_spec.rb
spec/lib/dqt/params/trn_request_spec.rb
spec/services/degrees/fix_to_match_reference_data_spec.rb
spec/services/degrees/map_from_apply_spec.rb

We now have the DfE::ReferenceData library to reference for degree fields. We have backfilled the institution name with varying degrees of success.
This PR expands that to backfill correct values and their associated UUIDs for:
* type (annoyingly referred to as uk_degree and uk_degree_uuid currently)
* institution
* subject
* grade
* Upgrade the DfE::ReferenceData to commit 96e1b7d which is a release candidate with some breaking changes. This includes the synonyms, abbreviations and extra values that we need
* Expand the backfill to include the extra fields and UUIDs
* Improve the matching to include name, match_synonyms and abbreviation and strip and downcase both sides of the match
* Update references to `hesa_itt_code` for subjects which is now called `hecos_code`
* Fix some missed …

[4304] Backfill degree UUIDS

---

config/settings/dttpimport.yml

We are going to start creating 22/23 trainees from apply but want to test this first.
Enable in dttpimport

[4371] Enable apply trainee creation on dttpimport

---

app/jobs/dqt/retrieve_award_job.rb
app/services/dqt/retrieve_teacher.rb
app/services/trainees/update.rb
lib/tasks/backfill_missing_award_dates.rake
spec/jobs/dqt/retrieve_award_job_spec.rb

https://trello.com/c/9hxg3LkC/4370-s-update-csv-export-for-start-and-end-academic-cycles
There's about 25k awarded trainees with no award date (mostly from DTTP). We can use DQT to get the QTS date and backfill these trainees. We'll also need to poll for award data from DQT that has been entered via the ITT portal.
- New client to fetch data from DQT teachers API
- New job to fetch award date from DQT and update trainee
- Rake task to backfill missing award dates for awarded trainees
Due to the API rate limit, it takes 1-2 hours to run the rake task. We will need to disable PR merges during the task run.

[4367] Backfill and import award date from DQT

---

db/data/20220720142825_fix_degree_institutions.rb

There are some mismatches that weren't picked up when we ran through all of the degrees with `Degrees::FixToMatchReferenceData`.
Fix them 'manually'

[xxx] Migration to fix invalid institutions

---

Gemfile
Gemfile.lock
db/data/20220722130512_rename_doctor_of_philosphy.rb

The version of dfe-reference-data we are using has an ambiguous 'Doctor of Philosophy' entry that is causing a duplicate entry in our degree type autocomplete and a frustrating amount of flakiness in CI.
This as been fixed in https://github.com/DFE-Digital/dfe-reference-data/pull/42
* Update to the fixed version
* Update the existing degree string values to keep things all valid and peachy
Would be good to check the autocomplete is still working for adding and updating degrees. It now has the abbreviation twice which is mildly annoying but still an improvement. 

[xxx] No more Doctor Phil

---

app/services/trainees/create_from_apply.rb
app/services/trainees/create_from_hesa.rb
spec/services/trainees/create_from_apply_spec.rb
spec/services/trainees/create_from_hesa_spec.rb

We need to set the academic cycles when trainees are created if we know the course details. This can happen from the create from hesa service or the create from apply service. Start and end academic cycles should be set from these services now. 
Add parameter to the two services to assign start and end academic cycles for which there is a course.

4331 set academic cycles on create

---

lib/tasks/example_data.rake

https://trello.com/c/wrpShJxi/4396-apply-drafts-users-not-asked-to-confirm-course
When Apply trainees are imported, we fill in the course uuid not the subjects. When the course is then confirmed, we fill in the subjects. If the subjects are present, we skip the 'confirm course' page.
Update the seeds to ensure we're not pre-filling Apply trainee subjects and hence the 'confirm course' page is shown
- Click into a draft Apply trainee
- Click into review course details
- Check that you're shown the confirm course page, not taken straight to the review page.

[4396] Ensure apply trainee seeds are shown the confirm course page

---

app/services/degrees/create_from_hesa.rb

Some data from HESA such as subject or grade is missing. We should still create the degree with the remaining data
- Update logic to protect against missing data which prevent the `dfe-reference` gem from finding the correct item.
- Ran the import against prod data locally. Ran without throwing any exceptions.

[xxx] Fix more bugs related to HESA degree import 

---

app/services/degrees/map_from_apply.rb
spec/services/degrees/map_from_apply_spec.rb

We've switched to using the reference data for Apply imports. There is a failing import (at least one) that doesn't have a matching value for grade. Handle that by setting the grade to other.
* Set unrecognised grade to other
We should review which values are being set with this and maybe revise the 'solution'. This will hopefully allow the test import to succeed and we can card up any further work.

[4371] Handle unrecognised grade

---

app/helpers/degrees_helper.rb
app/models/degree.rb
spec/helpers/degree_helper_spec.rb

We have a user that is unable to recommend a trainee as they need an 'Other' option for institution which the DfE::ReferenceData doesn't support.
* Add 'Other' option to dropdown
* Add 'Other' option to constant
This fixes an issue a user is currently having in production. Work to refactor this to wrap all access to DfE::ReferenceData has been carded up to do this properly.
I've added a UUID for the 'Other' option but am not sure whether that's really a good idea or not. It probably does run the risk that we'll send it somewhere else and that will break something. 

[4415] Add other option to dfe institutions

---

app/services/trainees/map_state_from_hesa.rb
spec/services/trainees/create_from_hesa_spec.rb
spec/services/trainees/map_state_from_hesa_spec.rb

We receive updates from the HESA API. We are incorrectly setting trainees to 'awarded' when we receive a successful course completion but the two things are different.
* Don't set trainees to awarded because they have successfully completed the course.

[xxx] Don't set HESA students to awarded

---

app/views/system_admin/lead_schools/show.html.erb
app/views/system_admin/providers/show.html.erb

We have soft delete on the User model. Only show 'kept' users on the lead school and provider pages in system admin.
* Add the kept scope for these pages

[xxx] Don't display discarded users in system_admin

---

app/forms/publish_course_details_form.rb
app/views/trainees/publish_course_details/edit.html.erb

https://trello.com/c/svXYFlXU/4242-pages-where-data-is-not-preserved-if-users-use-back-links-publish-course-details
**Issue**
If you go to the course picker page, then pick manual, then back, then refresh - you'll see the answer isn't saved whereas if you pick a course, then go back, then refresh, the answer is saved.
**Tech context:**
- We stash forms for registered trainees so that the data is not overwritten until users confirm the changes
- We save forms for draft trainees. The data is immediately overwritten.
- Stash `course_uuid: "not_listed"` in the redis form store when the form is stashed OR saved (i.e for both registered trainees and draft trainees) so that the form can re-hydrate from this value
Follow the steps as per the trello card and check that the radio button "Another …

[4242] Preserve choice of 'Another course not listed'

---

app/lib/dqt/params/trn_request.rb

Training route is sent to the DQT API as part of the TRN request.
Pass more granular training routes upon requesting TRN from DQT. 
The [DQT API has now been updated to accept values for provider-led postgrad and undergrad routes](https://qualified-teachers-api-tech-docs.london.cloudapps.digital/#schema-ittprogrammetype), to ensure that no data granularity is lost.
n/a

Pass more granular training routes upon requesting TRN from DQT

---

app/lib/dqt/params/trn_request.rb

By @benilovj #2569 
Training route is sent to the DQT API as part of the TRN request.
Pass more granular training routes upon requesting TRN from DQT. 
The [DQT API has now been updated to accept values for provider-led postgrad and undergrad routes](https://qualified-teachers-api-tech-docs.london.cloudapps.digital/#schema-ittprogrammetype), to ensure that no data granularity is lost.
n/a

More granular training routes on dqt trn request

---

terraform/workspace-variables/production.tfvars.json
terraform/workspace-variables/qa.tfvars.json
terraform/workspace-variables/sandbox.tfvars.json
terraform/workspace-variables/staging.tfvars.json

Remove statuscake alerts before adding back during the terraform provider upgrade
Remove alert config from workspace variables 
deploy-plan

Remove statuscake alerts before provider upgrade

---

terraform/.terraform.lock.hcl
terraform/modules/paas/main.tf
terraform/modules/statuscake/main.tf
terraform/modules/statuscake/provider.tf
terraform/terraform.tf
terraform/workspace-variables/production.tfvars.json
terraform/workspace-variables/qa.tfvars.json
terraform/workspace-variables/sandbox.tfvars.json
terraform/workspace-variables/staging.tfvars.json

Currently it is not possible to run our Terraform scripts in an Apple ARM environment because we need newer versions of the CloudFoundry and StatusCake modules.
Update cloudfoundry module to 0.15.3
Update statuscake to module 2.0.2-pre
Resource changes for statuscake in main.cf
Also hardcoded some of the statuscake settings in the main.cf,
so we no longer need to set them multiple times in the workspace files for each env.
- trigger_rate
- regions (changed to 2 and in the new required format)
- confirmation
- request_method
- status_codes (required by the tf provider)
- timeout (default has changed to 15, so reset to 40)
- enabled follow_redirects
deployed to review app
deploy-plan all envs …

Upgrade cloudfoundry and statuscake providers.

---

app/services/trainees/create_from_apply.rb
spec/services/trainees/create_from_apply_spec.rb

https://trello.com/c/2ZJCtdWY/4420-investigate-why-trainees-when-imported-from-apply-are-no-longer-being-set-for-their-phase
- Update `Trainees::CreateFromApply` set `Trainee#course_education_phase`

[4420] Set course_education_phase during Apply import

---

Gemfile

This gem is relevant in any deployed env in GPaaS.

load cloudfront-rails in deployed envs

---

app/helpers/degrees_helper.rb
spec/helpers/degree_helper_spec.rb

Trello: https://trello.com/c/pKMNYdwv/4459-s-degree-autocompletes-not-matching-synonyms
Our degree autocompletes were not using the synonyms to help populate the data, which meant we weren't able to match on some values that should have returned a result.
We've now added in `match_synonyms` and `suggestion_synonyms` to institution, degree type and subject mappings so these should now return results in the autocomplete.
* Add match and suggestion synonym mapping for institution, subject, type
* Check I haven't broken anything in the non-uk degree path
* Check I've handled any `nil` values that might throw an error
For prod review:
* Log in as a non-admin user
* Create a trainee record (any route)
* Go to add a degree for the trainee
* In Awarding Institution, type 'central functions' - you …

[4459] Use match and suggestion synonyms in degree autocomplete

---

app/models/course.rb
app/services/teacher_training_api/import_course.rb
app/services/trainees/create_from_hesa.rb
config/initializers/age_ranges.rb
db/data/20220727102458_remove_age_range_from_incompatible_courses.rb
db/migrate/20220726160157_remove_presence_validation_for_course_age_range.rb
db/schema.rb
spec/models/course_spec.rb
spec/services/degrees/dfe_reference_spec.rb
spec/services/teacher_training_api/import_course_spec.rb

https://trello.com/c/z5jOlXF2/4475-m-fix-publish-courses-with-primary-level-and-max-age-greater-than-11
- Removed age range validation on `Course` model
- Update `TeacherTrainingApi::ImportCourse` to set `min_age` and `max_age` conditionally
- Data migration to remove the `min_age` and `max_age` from those courses that are primary level but the `max_age` is beyond 11
Mainly backend changeds.

[4475] Fix publish courses with primary level and max age greater than 11

---

spec/services/degrees/dfe_reference_spec.rb

Not all items in the dfe-reference gem have a HESA code - we have to search for one to ensure the spec always passes
- Update spec to find reference data with a HESA code to ensure spec always passes

[xxx] Fix flakey Degrees::DfeReference spec

---

app/lib/apply_api/code_sets/nationalities.rb

I noticed this when running the Apply import on productiondata - we were getting this [Sentry error](https://sentry.io/organizations/dfe-teacher-services/issues/3460796196/?environment=productiondata&project=5552118&query=is%3Aunresolved).
Apply had corrected the nationality mapping back in Oct 2021 from RP to RO and we still had the incorrect code in Register.
I've updated the code to RO. I checked the data running the below query. There were 92 trainees imported after the date that Apply made the fix. They all have nationalities that look legit so I don't think we need to correct any data. 
```
Trainee.with_apply_application.where("trainees.created_at > ?", date.to_date).where(start_academic_cycle: 7).where.not
(itt_start_date: nil).count …
```

[xxx] Fix Romania mapping for Apply import

---

.github/actions/deploy/action.yml

Delete redis queues for productiondata on deploy, as the healthcheck will fail if they exist
Add step to delete via the redis-cli in the deploy workflow
Only deletes if env is productiondata and paas_worker_app_instances is 0
tested in review app

Delete redis queues for productiondata on deploy

---

app/components/funding/view.rb
app/forms/apply_applications/trainee_data_form.rb
app/forms/course_details_form.rb
app/forms/publish_course_details_form.rb
app/helpers/funding_helper.rb
app/lib/funding_manager.rb
app/models/trainee.rb
app/services/trainees/update.rb
spec/components/funding/view_spec.rb
spec/components/sections/view_spec.rb
spec/models/trainee_spec.rb
spec/services/exports/trainee_search_data_spec.rb
spec/support/shared_examples/rendering_the_funding_section.rb

The new start_academic_cycle field on trainee should replace the old 'academic_cycle' trainee method. This requires some test fiddling to ensure all trainees in the specs have a start_academic_cycle. The set academic cycle method has also to be called after the course details are added for the feature specs to work.

[4384] Remove academic cycle method from trainee

---

app/services/trainees/filter.rb
config/initializers/academic_cycles.rb
lib/tasks/example_data.rake
spec/controllers/trainees/start_statuses_controller_spec.rb
spec/controllers/trainees_controller_spec.rb
spec/factories/academic_cycles.rb
spec/factories/courses.rb
spec/factories/dttp/api_placement_assignment.rb
spec/factories/dttp/placement_assignments.rb
spec/factories/funding/payment_schedule_rows.rb
spec/factories/funding_methods.rb
spec/factories/trainees.rb
spec/features/funding/payment_schedule_spec.rb
spec/features/trainee_actions/recommending_for_qts_spec.rb
spec/forms/course_details_form_spec.rb
spec/forms/withdrawal_form_spec.rb
spec/lib/funding_manager_spec.rb
spec/services/exports/funding_schedule_data_spec.rb
spec/services/exports/trainee_search_data_spec.rb
spec/services/trainees/filter_spec.rb
spec/support/current_academic_cycle.rb
spec/support/date_helpers.rb
spec/view_objects/academic_year_filter_options_spec.rb
spec/view_objects/home_view_spec.rb

The specs were not robust enough to handle the change in academic cycle which occurs automatically on 1 August.
- Change the way the current academic cycle is computed during spec run
- New helper method `compute_valid_itt_start_date` to ensures we always have a date in the past
- Add new constants `ACADEMIC_CYCLE_START_MONTH` and `ACADEMIC_CYCLE_END_MONTH`

[xxx] Fix broken tests

---

app/services/degrees/map_from_apply.rb
spec/services/degrees/map_from_apply_spec.rb
spec/support/api_stubs/apply_api.rb

Trello: https://trello.com/c/bV4sKRnr/4460-m-determining-the-uk-ness-of-a-degree
When Apply import snagging we found that some degrees were being imported as UK degrees, when they were not. I've updated the `uk_degree?` check to now look at `hesa_degctry` first and then fall back to `comparable_uk_degree` and `non_uk_qualification_type`.
* Update uk_degree? in `/app/services/degrees/map_from_apply.rb`
* I'm not sure if we should be/need to check both `comparable_uk_degree` AND `non_uk_qualification_type` are nil - would be good to get thoughts

[4460] Update check for uk_degree? on Apply degree mapping

---

app/forms/course_years_form.rb
spec/features/trainee_actions/change_course_spec.rb
spec/forms/course_years_form_spec.rb

Trello: https://trello.com/c/0uO9YRcl/4397-get-rid-of-current-year-and-2023-to-2024-on-course-years-page
It was reported that users were accidentally registering their trainees too early, in a future year. We don't have the publish courses yet for 2023 - 2024 so we decided to remove this year option.
We've also removed 'current year' as this was potentially confusing users.
* Update /app/forms/course_years_form.rb to only include this year and last year as options
* Remove 'current year' text
* Navigate to the course year page by creating a new trainee record, clicking on course details and clicking on the year change link
* Check the course year picker page looks and works as expected …

[4397] Update course years form

---

config/analytics.yml
config/analytics_blocklist.yml

Working on https://trello.com/c/wmnFFOF4/4436-add-dqttrnrequests-to-bq to add the dqt_trn_requests table to BigQuery for analysis.
Remove the dqt_trn_requests table from the config/blocklist.yml and add to the config/analytics.yml
no
yes - we do

4436 add dqt trn requests to bq

---

config/settings.yml

https://trello.com/c/cGpb0uO5/4311-switch-on-apply-create-trainees
We're currently importing Apply applications from 2022. Now we want to enable creating trainees from them in production.
We are also running this in the production console:
```
ApplyApplication.where(recruitment_cycle_year: 2022).destroy_all
ApplyApplicationSyncRequest.where(recruitment_cycle_year: 2022).destroy_all
ApplyApi::ImportApplicationsJob.perform_later(from_date: Date.parse("2021-10-12"))
```
This is to ensure we get a fresh set of recruited applications from which we will create our 2022 trainees.

[4311] Switch on creating 2022 Apply trainees in production

---

app/controllers/trainees/start_statuses_controller.rb
app/lib/dqt/params/trn_request.rb
spec/controllers/trainees/start_statuses_controller_spec.rb
spec/factories/hesa/metadata.rb
spec/factories/trainees.rb
spec/lib/dqt/params/trainee_request_spec.rb
spec/lib/dqt/params/trn_request_spec.rb

https://trello.com/c/zycc6dpI/4364-m-send-fittaim-and-fqlaim-for-hesa-trainees
- Update `Dqt::Params::TrnRequest` to send `ittQualificationAim`

[4364] Send ITT aim and qualification to DQT

---

config/locales/en.yml

There was a missing end bracket on 'View draft trainees imported from Apply (6'.
Add the missing end bracket.
https://trello.com/c/eO7zXIkF/464-the-end-bracket-is-missing-on-view-draft-trainees-imported-from-apply-6
Check I haven't broken **everything** and that there is no longer a missing end bracket.
Blame @peteryates if it does break everything.

Add missing end bracket draft Apply trainees

---

config/locales/en.yml

Remove uppercase d in 'Trainee Data'.
'Trainee Data' should be 'Trainee data'.
https://trello.com/c/YyfRQWjd/468-trainee-data-page-has-upper-case-d-it-should-be-a-lower-case-d
Change the uppercase D to a lowercase d.
Check that I haven't broken anything and it's lowercase. 

Correct casing for 'Trainee Data'

---

app/views/trainees/apply_applications/trainee_data/edit.html.erb

'Return to this draft record later' shouldn't be on this page.
https://trello.com/c/owESgrCC/4506-get-rid-of-return-to-draft-link-on-trainee-data-page
On the 'trainee data' page, when registering a trainee, there's a 'return to draft link'. This shouldn't be there and it should be removed.
Delete 'Return to draft record later' text and link.
Check I haven't broken anything and the link is removed. I got rid of the paragraph around it. Hoping that doesn't break anything!
P.S. this is non-urgent, so please feel free to ignore till we're less busy.

Remove 'Return to drafts' link on Trainee data

---

config/analytics_blocklist.yml
db/migrate/20220809102256_add_collection_reference_to_hesa_students.rb
db/schema.rb

https://trello.com/c/7abU2Eac/4502-s-update-hesastudents-with-the-full-c21053-collection
We're not sure how long the `hesa_students` table will be around for. It has proved to be very useful in backfilling missing data. With the C21053 collection coming to a close, we want to backup the whole collection from the start of the academic year just in case we need it for future reference. Adding a `collection_reference` column will help us know the source of each record, especially if we intend on storing future collections.
- Database migration to add `collection_reference` to `hesa_students` table
Re-seeding the `hesa_students` table could be done using a data migration, but the size of the XML (40k+ nodes) has proved to be a problem when loaded into memory. The container running the data …

[4502] Add collection_reference column to hesa_students table

---

app/forms/withdrawal_form.rb
app/jobs/dqt/recommend_for_award_job.rb
app/jobs/dqt/retrieve_award_job.rb
app/services/trainees/update.rb
app/services/trainees/withdraw.rb
lib/tasks/backfill_missing_award_dates.rake
spec/forms/withdrawal_form_spec.rb
spec/jobs/dqt/recommend_for_award_job_spec.rb
spec/jobs/dqt/retrieve_award_job_spec.rb
spec/services/trainees/withdraw_spec.rb

This bug: https://trello.com/c/jybTs1QZ/4399-filter-for-trainees-awarded-next-year-has-trainees-awarded-this-year
We realised that we weren't setting academic cycles again after trainees were awarded and withdrawn. This meant the trainees' cycles weren't updating based on newly added award or withdraw dates.
Trainees::Update is where the cycle setting job happens (Trainees::SetAcademicCyclesJob)
**NOTE** Backfill on affected trainees coming in separate PR
* Add Trainees::Update into RecommendForAwardJob
* Add Trainees::Update into WithdrawalForm
* Don't send either of these updates to DQT as they aren't needed by them - it's just so we can set cycles correctly on our end
* I chose to trigger the update in the WithdrawalForm rather than the withdrawal job - I did this as thought it made …

[4399] Run Trainees::Update on to set academic cycles on awarded and withdrawn trainees

---

spec/lib/dqt/params/trainee_request_spec.rb

RSpec does no autoloading.
Sometimes this `stub_const` would run before `Dqt::CodeSets::DegreeTypes` was loaded and the tests would fail with:
https://github.com/DFE-Digital/register-trainee-teachers/runs/7765168857?check_suite_focus=true
`uninitialized constant Dqt::CodeSets::DegreeTypes::FOUNDATIONS`
From [sub_const docs](https://relishapp.com/rspec/rspec-mocks/v/3-11/docs/mutating-constants/stub-undefined-constant):
> When the constant is not already defined, all the necessary intermediary modules will be dynamically created
It was making it's own `Dqt::CodeSets::DegreeTypes` module with just `MAPPING` defined.
In this PR I've remove the use of stub const completely, which fixes the test issue.
We could also do this:
```
stub_const("#{Dqt::CodeSets::DegreeTypes}::MAPPING", { …
```

[xxx] Fix degree type tests by removing constant stubbing

---

config/analytics.yml
config/analytics_blocklist.yml

Need to remove the payload field from the hesa_trn_subission entity so PII is not sent to BigQuery

Remove the hesa-Trn_submission payload field from Update analytics.yml

---

app/services/degrees/create_from_hesa.rb
db/data/20220729144112_delete_empty_degrees.rb
spec/services/degrees/create_from_hesa_spec.rb

Trello: https://trello.com/c/bOpAYUtb/4439-l-investigate-hesa-import-creating-other-grade-degrees-that-arent-visible
We have around 8k degrees (mostly linked to undergrad trainees) that contain grade: "Other" and no other useful information. We realised these are most likely being created when HESA sends us degrees with `degree_type: "999"` (their code for 'unknown'). These degrees contain no other useful information e.g. subject, institution, grade, etc. 
We've changed the code so that we no longer create these degrees. 
This ticket also includes a backfill to delete the incorrectly created degrees.
* Update `/degrees/create_from_hesa.rb` so that we skip over any degrees with `degree_type: "999"`
* Add a data migration to destroy the approx 8k degrees
* Check that how I've scoped the …

[4439] HESA import: don't create degrees with degree_type: '999'

---

app/lib/dqt/params/trn_request.rb
app/services/trainees/calculate_itt_end_date.rb
app/services/trainees/set_academic_cycles.rb
spec/lib/dqt/params/trn_request_spec.rb
spec/services/trainees/calculate_itt_end_date_spec.rb

https://trello.com/c/EBevEsH4/4549-cant-sending-hesa-trainees-to-dqt-for-trn-because-of-missing-ittenddate
We're trying to request TRN's from DQT using HESA trainees. `Dqt::Params::TrnRequest` expects an `itt_end_date` but it's missing in most HESA trainees. We can work it out by falling back on the course duration data that's stored in the `hesa_metadata` table.
- Extract code to calculate end date from `Trainees::SetAcademicCycles` into a new service `Trainees::CalculateIttEndDate`
- Update `Dqt::Params::TrnRequest` to use `Trainees::CalculateIttEndDate` if `trainee.itt_end_date` is missing

[4549] Fix: can't sending HESA trainees to DQT for TRN because of missing itt_end_date

---

lib/tasks/set_academic_cycles_on_some_trainees.rake

Bug: https://trello.com/c/H8KOaaii/4499-backfill-pr-filter-for-trainees-awarded-next-year-has-trainees-awarded-this-year
We have some trainees that have been awarded/withdrawn but haven't had their end academic cycle updated correctly. This data migration updates those trainees by running the `SetAcademicCycleJob` on them.
We created the new job in June so I've scoped it to trainees updated since then.
* Add data migration to run SetAcademicCycleJob on trainees with award or withdraw states, updated after 01/06/2022
* I'll run it on productiondata to see if it works (runs ok locally)
* Check my scope makes sense and I'm targeting the right trainees

[4499] Fix academic cycles for awarded and withdrawn trainees

---

db/service_updates.yml

Removed line about applications going through HESA to make it less confusing for users in that applications don’t go through HESA anyway. 
Shaun flagged that the second paragraph might be confusing to users.
Removing a sentence. I thought it better to remove than try and explain what we mean and making this even more confusing. We’ve also already sent out comms about the details so this section doesn’t need it.

Removing sentence in news and updates about HESA

---

app/lib/dqt/params/trn_request.rb
spec/lib/dqt/params/trn_request_spec.rb

We got an error come through in Sentry where we were sending an empty string to DQT when there was no `heQualificationType` (it this case it was a non uk degree). Instead, we need to send `nil`.
* Update `dqt/params/trn_request.rb` to not send an empty string when there is no `heQualificationType`
* Once this is merged I can re-run the failed DQT job and see that the trainee goes through successfully this time

[xxx] Send nil to DQT for heQualificationType when it is nil

---

app/components/application_record_card/view.rb
app/components/record_details/view.rb
app/controllers/trainees_controller.rb
app/jobs/hesa/retrieve_collection_job.rb
app/jobs/hesa/retrieve_job.rb
app/jobs/hesa/retrieve_trn_data_job.rb
app/models/trainee.rb
app/services/exports/trainee_search_data.rb
app/services/trainees/create_from_apply.rb
app/services/trainees/create_from_dttp.rb
app/services/trainees/create_from_hesa.rb
app/views/trainees/training_routes/_form_fields.html.erb
config/analytics.yml
config/initializers/record_sources.rb
config/rubocop/rspec.yml
db/migrate/20220812143158_add_record_source_field_to_trainees.rb
db/schema.rb
lib/tasks/example_data.rake
spec/factories/trainees.rb
spec/features/trainee_actions/creating_a_new_trainee_spec.rb
spec/jobs/hesa/retrieve_collection_job_spec.rb
spec/jobs/hesa/retrieve_trn_data_job_spec.rb
spec/models/trainee_spec.rb
spec/services/trainees/create_from_apply_spec.rb
spec/services/trainees/create_from_dttp_spec.rb
spec/services/trainees/create_from_hesa_spec.rb

https://trello.com/c/fUMWQZqP/4534-add-record-source-field-to-trainee-to-show-us-when-its-only-been-trn-requested
We need a way of distinguishing between trainees who were created over the HESA TRN data endpoint and have never come to us over the HESA collection endpoint. These need to be excluded from the UI.
We decided to add a record_source field to track this. We can also use this to clean up our code elsewhere where we derive the record source from various things (see renamed `def derived_record_source` which can be removed once we do the backfill). Then we can swap the record source filter and all the various scopes to use this new field.
- Add record_source field to trainees
- Set manually created trainees record_source to manual
- Save trainees created from Apply record source to …

[4534] Add record_source field to trainee

---

app/services/trainees/create_from_hesa.rb
spec/services/trainees/create_from_hesa_spec.rb

We're setting some trainees to `submitted_for_trn` during the HESA import (if they're missing a TRN). 
We're also going to kick off the `RegisterForTrnJob` off the the back of this.
Currently `RegisterForTrn` service will fail due to lack of `submitted_for_trn_at`
- Update `submitted_for_trn_at` when we set the state to be `submitted_for_trn` in the `CreateFromHesa` service.

[xxx] Save submitted_for_trn on trainee during hesa import

---

app/services/trainees/filter.rb
spec/services/trainees/filter_spec.rb

https://trello.com/c/dkz9DVtT/4541-hide-trainees-when-they-have-only-been-requested-for-trn-via-hesa-in-register-ui-and-user-exports
Use our new `record_source` field on trainees to hide those with `HESA TRN data` source.
- Check that the HESA TRN data trainee with TRN 3638452 is not visible in the Registered trainees list
- Check that they're also not visible in the download

[4541] Hide trainees when they have only been requested for TRN via HESA

---

app/services/trainees/filter.rb
spec/services/trainees/filter_spec.rb

Too many trainees hidden! draft trainees with null record_source are hidden.
Revert changes in  https://github.com/DFE-Digital/register-trainee-teachers/pull/2640
🚢 

[xxx] Undo code that hides too many trainees

---

Gemfile
Gemfile.lock
spec/spec_helper.rb

Trello: https://trello.com/c/Bcoyw3fw/4510-s-capture-more-information-around-the-flakey-tests-so-we-can-try-and-fix-them
We have some issues with flakey specs on Register - we are going to add rspec-retry as a first step and then build some form of reporting for the flakey specs.
We are using a [DfE Digital forked version](https://github.com/DFE-Digital/rspec-retry) of rspec-retry because this has some custom functionality. Apply are also using this.
* Add DfE-Digital forked version of rspec-retry
* Set to retry 3 times across failing tests
* Run the test suite locally and take a look at CI, make sure nothing untoward.
* Check if you think retrying 3 times is the right number of tries …

[4510] Add rspec-retry gem to Register

---

app/services/degrees/dfe_reference.rb
spec/lib/dqt/params/trainee_request_spec.rb
spec/lib/dqt/params/trn_request_spec.rb

The test suite was failing due to a non-deterministic test when the grade selected was `Other`
Fix the `find_item` method to use the constants defined within the same class rather than directly from the ReferenceData gem.
This test should no longer fail on random runs:
```bash
bundle exec rspec ./spec/forms/degree_form_spec.rb:150
```
These tests failed after the actual code changes and have been updated:
```bash
bundle exec rspec ./spec/lib/dqt/params/trainee_request_spec.rb:53
bundle exec rspec ./spec/lib/dqt/params/trn_request_spec.rb:76
```

[4550] Adjust find_item to use internal DfeReference

---

app/services/teacher_training_api/import_course.rb

https://github.com/DFE-Digital/publish-teacher-training/pull/2940
We're streamlining the values sent within the Course's `state` property in the Publish API. This PR updates the `ImportCourse` sync to accommodate the changes.
- In publish, `empty` and `draft` are now synonymous. So have removed this as I think Register just needs `rolled_over`, `published` and `withdrawn`?
- Remove `published_with_unpublished_changes` as these courses will be returned under `published`. I don't think Register distinguishes between the two internally?
See the changes, let me know if all ok :)

[xxx] Update importable states in course sync

---

app/lib/dqt/params/trn_request.rb
spec/lib/dqt/params/trainee_request_spec.rb
spec/lib/dqt/params/trn_request_spec.rb

We're sending the `ittQualificationAim` in the qualification to DQT.
It should be in the `initialTeacherTraining`.
- Move the attribute into the correct position in the JSON.
🚢 

[xxx] Move `ittQualificationAim` attribute in DQT params

---

config/locales/en.yml

https://trello.com/c/Sgs5kQaC/4573-confirm-course-training-details-delete-comma-from-hint-text
There is a comma in hint text where there shouldn't be.
Remove the comma.
Check the comma is removed.

Removed comma from change hint

---

app/services/trainees/filter.rb
lib/tasks/example_data.rake
spec/factories/trainees.rb
spec/services/trainees/filter_spec.rb

https://trello.com/c/dkz9DVtT/4541-hide-trainees-when-they-have-only-been-requested-for-trn-via-hesa-in-register-ui-and-user-exports
- Hide trainees whose record source is HESA TRN data from the UI
- Ensure that we don't hide trainees with nil record_source before the backfill is run :)
- Check that the HESA TRN data trainee (TRN 9922817) is not in the list nor the download

[4541] Hide HESA TRN data trainees

---

app/jobs/dqt/register_for_trn_job.rb
app/jobs/hesa/retrieve_trn_data_job.rb
app/lib/dqt/params/trn_request.rb
app/models/trainee.rb
app/services/hesa/upload_trn_file.rb
config/settings.yml
config/settings/productiondata.yml
spec/jobs/dqt/register_for_trn_job_spec.rb
spec/lib/dqt/params/trainee_request_spec.rb
spec/lib/dqt/params/trn_request_spec.rb

https://trello.com/c/II1neZuc/4368-enable-hesa-trn-requests
This PR is the outcome of testing HESA<->Register<->DQT integration, especially around TRN requests from HESA.
- Add feature flag to use HESA's test URLs in non-prod environment
- Turn on HESA TRN data import in productiondata environment
- Add ittQualificationType to Dqt::Params::TrnRequest
- Remove HESA guard clause
- Replace Trainees::CalculateIttEndDate with internal method
- Fix GENDER_CODES mapping to reflect changes in HESA schema
- Allow Trainee to access it's DQT TRN request record
- Use provider instead of hesa_student to get UKPRN
- Add preprod DQT API URL to productiondata environment
- Update HESA collection start date for 2022-23 academic year
NB: Please notify the #twd_data_insights team and ask for a review if new …

[4368] Enable HESA TRN requests (productiondata env)

---

config/settings/productiondata.yml

This feature flag was not turned on in `productiondata` environment. Overlooked in PR #2662.

[xxx] Enable DQT integration in productiondata environment

---

app/lib/hesa/parsers/itt_record.rb

During testing HESA TRNData integration, the XML returned contains "Null" instead of "NULL" (this is likely a manual typo). Instead of getting HESA to fix this, it's quicker to handle both cases within Register and prevent issues around this in the future.
This is preventing `Trainees::MapStateFromHesa` from calculating the correct state which in turn prevents `submitted_for_trn_at` from been set leading to a error running `Dqt::RetrieveTrnJob` which depends on it. 
- Downcase XML values and compare to "null"

[xxx] Handle HESA XML with null values in various cases

---

app/lib/dqt/params/trn_request.rb
app/lib/hesa/parsers/itt_record.rb
spec/lib/dqt/params/trn_request_spec.rb

Graduation year for trainees imported from HESA could potentially nil. We need to handle this when sending them over to DQT.
Currently there's a bug in Register because:
```
Date.parse("01-01-#{nil}").iso8601
=> "2022-08-01"
```
`Date.parse("01-01-#{nil}")` == `Date.parse("01-01-")` == `Date.parse("01")` == First of the current month 
Send nil as the qualification date if the graduation year on the degree is nil.

[xxx] Handle nil graduation year in DQT params

---

docs/disaster-recovery.md
terraform/.terraform.lock.hcl
terraform/modules/statuscake/provider.tf
terraform/terraform.tf

Update the StatusCake provider to ensure it is not using a preview
version.

Update Terraform StatusCake provider to 2.0.3

---

app/jobs/hesa/upload_trn_file_job.rb
app/models/trainee.rb
app/services/trainees/create_from_hesa.rb
config/sidekiq_cron_schedule.yml
spec/services/trainees/create_from_hesa_spec.rb

Some minor bug fixes that came out of `HESA TRNData<->Register<->DQT` integration testing.
- Update `Hesa::UploadTrnFileJob` to use a better scope so only HESA trainees from TRNData are selected for file upload.
- Update `Trainees::CreateFromHesa` so it sets `submitted_for_trn_at` for withdrawn trainees because they are expected to have a TRN

[xxx] Minor bug fixes from HESA TRNData integration testing

---

app/lib/dqt/params/trn_request.rb
spec/lib/dqt/params/trn_request_spec.rb

Trello: https://trello.com/c/p3WjA8NW/4593-m-derive-ittenddate-where-a-trainee-has-no-hesa-expectedenddate
ITT end date is optional in HESA. This means some HESA trainees may not have an exact end date. 
DQT needs an ITT end date for trainees. When there is no itt_end_date, derive this from the start date plus course duration and send this to DQT.
Matrix for the course durations: https://docs.google.com/spreadsheets/d/1whYdDcMqOtWDoy12Pk3sIIRnEEN4m4LvtR1ojd37xdk/edit?pli=1#gid=0
* Update `def estimated_course_duration`
* Check the matrix - have I got the durations right?
* Sense check I haven't missed anything in the logic

[4593] Derive itt_end_date to send to DQT

---

app/jobs/dqt/register_for_trn_job.rb
spec/jobs/dqt/register_for_trn_job_spec.rb

During testing we were manually kicking off TRN requests for trainees who already had TRNs, which confused matters. this shouldn't happen in _real life_ , but this is just an extra check.
- Check that the trainee doesn't already have a TRN before we request a TRN from DQT.

[xxx] Don't request a TRN from DQT if we already have one

---

app/jobs/dqt/sync_states_job.rb
config/settings.yml

I added a limit on the number of trainees we were syncing states for from DQT for testing purposes.
We've now run the job with the full number of trainees so we don't need to limit it anymore.
🚢 

[xxx] Remove the limit on the trainees we're syncing states for from DQT

---

config/settings/productiondata.yml
terraform/workspace-variables/productiondata.tfvars.json

We've finished testing the HESA / DQT integrations in the productiondata env.
Switch off the settings in productiondata env that pulls in TRN data and sends trainees to DQT.

[xxx] Turn off DQT integration in productiondata env

---

app/services/trainees/calculate_itt_end_date.rb
spec/services/trainees/set_academic_cycles_spec.rb

- We were raising an error during setting academic cycles if the
course length was longer than 5 years
- We are now aware that some courses are 8 years long
- Update the code to not error when attempting to set the academic
cycle for these trainees
🚢 

[4494] Allow course lengths greater than 8 years

---

Gemfile
Gemfile.lock
app/services/exports/trainee_search_data.rb

The `format_trainees` method caused `production` instances to crash due to a lack of memory.
Built a new query to fetch as much info as possible in one go using `:includes` for eager loading and `find_each` for batching (defaults to [1000](https://apidock.com/rails/ActiveRecord/Batches/ClassMethods/find_each))
We can't easily eager load `:published_course` until we [upgrade](https://github.com/rails/rails/pull/42553) rails. Therefore, I have left `course = Course.where(uuid: trainee.course_uuid).first` in there and it will still be called once per trainee and cause a db call each time :-( 
Make sure nothing has been broken

[xxx] Mini refactor `format_trainees`

---

config/settings/production.yml

HESA have now switched the endpoint for C22053 from test data to real data.
We can now turn on our integration to start pulling these trainees into Register (from both the collection and TRN endpoint)
- Enable retrieving collection from HESA (hesa.sync_collection)
- Enable retrieving TRN data from HESA (hesa.sync_trn_data)
- Enable sending TRNs back to HESA (hesa_trn_requests)

[4368] Enable HESA collection / TRN requests in prod

---

config/initializers/academic_cycles.rb
db/data/20220830134128_add_future_academic_cycles.rb

- Now we know that courses can be 8 years long, we need at least 8
future academic cycles in the database
- This is because we associate a trainee with an end_academic_cycle
- Add a data migration to include academic cycles up until the year 2031
- Check that adding these extra cycles hasn't 'broken' any of the UI (year dropdowns?)

[4494] Create academic cycles in the future

---

app/controllers/guidance_controller.rb
app/views/guidance/dates_and_deadlines.html.erb
config/routes.rb
spec/controllers/guidance_controller_spec.rb

Trello: https://trello.com/c/SHnCG4gJ/4594-create-page-for-dates-and-deadlines-for-the-2022-to-2023-academic-year
This is the new guidance page 'Dates and deadlines'. I have used an ERB template because the page is predominantly a table. This is probably better suited to HTML.
I have not put the content in translations files but can do so if necessary.
* new route 'guidance/dates-and-deadlines'
* new controller method def dates_and_deadlines
* new ERB file 'guidance/dates_and_deadlines.html.erb'
* ERB file instead of markdown because the page is a table and not longform content
* No translation files added - can change if we think we need them

[4594] Add new guidance pages

---

app/controllers/guidance_controller.rb
app/views/guidance/_manually_registering_trainees.md
app/views/guidance/_withdrawing_or_deferring_a_trainee.md
app/views/guidance/manually_registering_trainees.html.erb
app/views/layouts/guidance_markdown.html.erb
config/routes.rb
spec/controllers/guidance_controller_spec.rb

Trello: https://trello.com/c/ASwBVJh8/4591-create-page-for-registering-trainees-manually-in-this-service
Add new guidance page 'Registering trainees manually in this service'. I have used markdown partials to render the content chunks. These are rendered in between the govuk-details components in the ERB file.
* Add two md partials, _manually_registering_trainees.md and _withdrawing_or_deferring_a_trainee.md
* Add manually_registering_trainees.html.erb
* Use govuk_details component
* Set up new route and controller action(set the layout to use guidance_markdown)

[4591] Add Registering trainees manually guidance page

---

app/views/layouts/application.html.erb

We have a new guidance section called 'How to use this service'. We want to link to it in the footer of every page on Register.
A small link entitled 'How to use this service' should now appear at the bottom of every page/

[4588] Add guidance link to footer

---

app/controllers/reports_controller.rb
app/helpers/date_of_the_nth_weekday_helper.rb
app/helpers/users_helper.rb
app/policies/user_policy.rb
app/services/exports/trainee_search_data.rb
app/services/new_starter_trainees_service.rb
app/views/layouts/application.html.erb
app/views/reports/index.html.erb
app/views/reports/itt_new_starter_data_sign_off.html.erb
config/routes.rb
config/settings.yml
spec/helpers/date_of_the_nth_weekday_helper_spec.rb
spec/services/exports/trainee_search_data_spec.rb
spec/services/new_starter_trainees_service_spec.rb

Providers need to know what data they're signing off on. It's helpful if they can see all the data (which requires some filtering that we don't currently offer on the Registered trainees page) in a report. This allows them to check their data to confirm it.
A reports section has been added to the navigation bar; with a page leading to some guidance and a download report button. 
Add reports section nav bar heading
Add a reports page 
Add an itt_signoff reports page with a link to download the report 

[4442] building the report for sign off

---

app/controllers/guidance_controller.rb
app/views/guidance/_manually_registering_trainees.md
app/views/guidance/_registering_trainees_through_hesa.md
app/views/guidance/_withdrawing_or_deferring_a_trainee.md
app/views/guidance/about_register_trainee_teachers.md
app/views/guidance/registering_trainees_through_hesa.html.erb
app/views/layouts/guidance_markdown.html.erb
config/routes.rb
spec/controllers/guidance_controller_spec.rb

Trello: https://trello.com/c/kteEJH3D/4590-create-page-for-registering-trainees-through-hesa
Add guidance page 'Registering trainees through HESA'
Make some changes to some existing guidance pages and guidance layout to set correct heading sizes.
Ideally we will update the Govuk-markdown gem to have correct heading sizes/be configurable, but as a quick fix, adding HTML into the md files.
I've added `page_title` into the front matter on markdown pages, this is because sometimes the page title is different to the page heading.
* add new route
* add new controller action
* add new md file and erb file
* update existing md files to have correct HTML heading classes
* update guidance_markdown.html.erb to handle page_title and use correct title heading class …

[4590] Add Registering trainees through HESA guidance page

---

app/controllers/guidance_controller.rb
app/views/guidance/check_data.md
config/routes.rb
spec/controllers/guidance_controller_spec.rb

Edit content for new page  ‘Check what data you need to provide’.
This is because we are improving and expanding the guidance pages for Register. 
add new markdown file and html.erb file to render the guidance page on the check-data route 
Go to the guidance/check-data route and ensure the markdown has rendered correctly.

[4589] Add check data page

---

app/jobs/dqt/sync_states_job.rb
config/sidekiq_cron_schedule.yml

We manually ran the job last week and it took 3 hours with 37k trainees.
After that run, we now only have 13k HESA trainees in `trn_received` so this job will take approx 1 hour.
We also fixed all of the 50 trainees that 404'd during the first run, so we're happy to now run this on a schedule.
- Run the `Dqt::SyncStatesJob` daily at 11am.
- Add a comment about the DQT API rate limit.
- Is 11am a reasonable time to run it? I decided that if we were to get errors we'd rather see them during the day rather than wake up to them?
- Are we happy running this daily, or is it ok being a weekly thing? We could then bump up the frequency during busy 'awarding' periods.

[4612] Add the Dqt::SyncStatesJob to the sidekiq scheduler

---

app/controllers/guidance_controller.rb
app/views/guidance/_manually_registering_trainees.md
app/views/guidance/_withdrawing_or_deferring_a_trainee.md
app/views/guidance/about_register_trainee_teachers.md
app/views/guidance/show.html.erb
app/views/pages/home.html.erb

Trello: https://trello.com/c/P0foCnnX/4587-create-how-to-use-the-service-section-on-homepage-for-signed-in-users
Added changes to homepage to include new guidance links. 
Also refactor the guidance show page to use the govuk component `govuk-link-to` instead of lots of HTML.
~~NOTE: The old check-data page is still being used for these links. We'll need to make sure we switch to the new link in the last ticket where we create the new check-data page.~~ Now done.
* Update home.html.erb to use the new links
* Refactor guidance/show.html.erb
* Add a couple content changes from Maeve
* ~~All links should work correctly except for the data check - this is coming in another PR~~ - all links should now work!
NB: Please notify the #twd_data_insights team and ask for a review if new fields are …

[4587] Update homepage with new guidance sections

---

config/settings.yml
config/settings/production.yml

The DQT API has four environments:
dev: https://qualified-teachers-api-dev.london.cloudapps.digital
test: https://test-teacher-qualifications-api.education.gov.uk/
pre-prod: https://qualified-teachers-api-preprod.london.cloudapps.digital/
production: https://teacher-qualifications-api.education.gov.uk/
The default setting was set to the production URL and then overridden in the environment files. This has a risk of unintentionally configuring an environment against production.
* Make the dev URL the default and explicitly set the production URL in production
* Default productiondata to dev as we'd generally not want that to talk to DQT unless we're explicitly testing that in which case we can add the configuration.
NB: Please notify the #twd_data_insights team and ask for a review if new …

[xxx] Make dev default DQT API URL

---

db/data/20220902100022_backfill_record_source_on_trainees.rb

https://trello.com/c/8mRrqx6O/4555-backfill-the-record-source-field-on-trainees
Backfill the `record_source` field on trainees.
- No backfill for TRN data trainees, as their record source should be being set correctly (although currently there are non of these)
- Check the scope logic in https://github.com/DFE-Digital/register-trainee-teachers/blob/main/app/models/trainee.rb - this is what i've based the data migration on.
- Since we show "HESA" in the UI for trainees who were originally imported from DTTP but have a HESA ID, I've mirrored this in setting record_source. But this means that `Trainee.created_from_dttp` will return more trainees than the new `Trainee.where(record_source: "dttp")`. Something to be aware of.
NB: Please notify the #twd_data_insights team and ask for a review if …

[4555] Add data migration to fill in record source on trainees

---

app/services/hesa/upload_trn_file.rb
spec/services/hesa/upload_trn_file_spec.rb

HESA are receiving empty csv files when no trainees are in scope.
Do not upload a csv file with zero records.
From the development console check that:
```ruby
Hesa::UploadTrnFile.call(trainees: []).nil?
=> true
```

[4636] Do not upload a trn file when no trainees are in scope

---

app/services/degrees/create_from_hesa.rb
db/data/20220906090020_fix_degrees_with_unmapped_types.rb
spec/services/degrees/create_from_hesa_spec.rb

https://trello.com/c/wxSW1Cet/4554-investigate-why-hesa-degree-type-008-is-not-getting-mapped-correctly
We've had a small number of cases of trainee degrees with missing degree type because the HESA code is 002, 004, 006, 008 and 010 which is not supported by the dfe-reference gem. Some trainees have duplicates, so the data migration will remove all degrees and recreate them using data from `hesa_students` table.
- Data migration to fix missing degree types
- Minor refactoring of `Degrees::CreateFromHesa`
- Add test example to prove that `Degrees::CreateFromHesa` can map unsupported HESA codes such as 008
- The data migration will take about 12 minutes to run
- About 500 degrees have a missing degree type that needs to be fixed …

[4554] Investigate why HESA degree type 008 is not getting mapped correctly

---

config/initializers/mappings/allocation_subject_to_specialism_mapping.rb
config/initializers/mappings/publish_to_allocation_subject_mapping.rb
db/data/20220907110350_move_english_as_second_language_under_english_allocation_subject.rb

https://trello.com/c/4Sb4HT6w/4621-update-english-as-a-second-or-other-language
The specialism `English as a second language` should have the allocation subject of `English`, not 'modern languages' - this was a mistake.
Also worth reading to understand to wider challenge of having this subject specialism: https://ukgovernmentdfe.slack.com/archives/C03EM9URG0N/p1662545107189089
- Remove `English as a second or other language` from modern languages and move it under the allocation subject `English`
- You can choose a modern languages course and check it doesn't appear in the list

[4621] Remove 'English as a second or other language' from modern languages

---

app/controllers/reports_controller.rb
app/services/find_new_starter_trainees.rb
app/services/new_starter_trainees_service.rb
spec/services/find_new_starter_trainees_spec.rb
spec/services/new_starter_trainees_service_spec.rb

https://trello.com/c/TZ8Cx3gJ/4634-trainees-from-the-hesa-trn-data-endpoint-will-end-up-in-the-new-starter-report
- Add another `where` scope to `NewStarterTraineesService` that excludes trainees sourced from HESA TRNData
- Rename `NewStarterTraineesService` to `FindNewStarterTrainees` (Service objects ideally should have a verb to signify the action that takes place when called. It's also unnecessary to have the world 'Service' at the end of the class name.)

[4634] Exclude HESA TRNData trainees from new starter report

---

app/forms/apply_applications/trainee_data_form.rb
app/forms/course_details_form.rb
app/forms/publish_course_details_form.rb
app/services/trainees/update.rb
spec/features/end_to_end/assessment_only_journey_spec.rb
spec/features/end_to_end/early_years_assessment_only_journey_spec.rb
spec/features/end_to_end/early_years_postgrad_journey_spec.rb
spec/features/end_to_end/early_years_salaried_journey_spec.rb
spec/features/end_to_end/opt_in_undergrad_spec.rb
spec/features/end_to_end/pg_teaching_apprenticeship_journey_spec.rb
spec/features/end_to_end/provider_led_postgrad_journey_spec.rb
spec/features/end_to_end/provider_led_undergrad_journey_spec.rb
spec/features/end_to_end/school_direct_salaried_journey_spec.rb
spec/features/end_to_end/school_direct_tuition_fee_journey_spec.rb
spec/features/end_to_end/teach_first_journey_spec.rb
spec/features/form_sections/personal_and_education_details/degrees/adding_degree_spec.rb
spec/features/form_sections/personal_and_education_details/degrees/editing_degree_spec.rb
spec/features/form_sections/personal_and_education_details/edit_personal_details_spec.rb
spec/features/form_sections/teacher_training_data/apply_applications_spec.rb
spec/features/form_sections/teacher_training_data/edit_trainee_start_status_spec.rb
spec/features/form_sections/teacher_training_data/employing_school_search_spec.rb
spec/features/trainee_actions/withdraw_trainee_spec.rb
spec/jobs/dqt/sync_states_batch_job_spec.rb
spec/services/trainees/submit_for_trn_spec.rb

Due to a misunderstanding with how perform_now and perform_later works I added a check in the update method that would cause the setacademiccycle job to be performed now if updated from the UI. This should be reverted so that the update returns to its previous asynchronous behaviour.  

[4495] Remove perform_now from trainees update

---

db/data/20220909131155_remove_duplicate_degrees_from_hesa_trainees.rb

https://trello.com/c/egpS9hjF/4508-duplicate-degrees-on-some-hesa-imported-trainees
Recent code fixes should prevent duplicates from been created in the future.
- Data migration to remove duplicate degrees
Takes about 3 minutes to run. Approximately 1400 trainees from last year's academic cycle have their degrees removed and recreated using data from the `hesa_students` table. Trial runs demonstrate that the code works as expected.

[4508] Data migration to remove duplicate degrees belonging to HESA trainees

---

app/views/guidance/_manually_registering_trainees.md
app/views/guidance/about_register_trainee_teachers.md
app/views/guidance/check_data.md
app/views/guidance/dates_and_deadlines.html.erb

Fixups from the snagging session for guidance pages:
1. Remove full-stops from the end of link text (they should be outside of the link). Change these links to not be the whole sentence, so only link where the square brackets are below:
* Find out what the [dates and deadlines are for the 2022 to 2023 academic year].
* Read about how to [register your trainees manually].
* Read more about how to [register your trainees through HESA].
1. Add a ‘no wrap’ class to all the dates so they do not split over multiple lines
1. Under the section PE with EBacc, make the mailto link have a subject line of ‘Registering trainees on a PE with EBacc course’
1. Change all the lists to use html unordered list instead of paragraph tags
2. Change spacing of the horizontal line to: <hr …

4644 guidance page snagging fixups

---

Gemfile
Gemfile.lock

https://trello.com/c/9qNctNxM/4652-register-trainee-teachers
New institution is Institute of Chartered Accountants of Scotland
- Update `Gemfile` to reference the latest dfe-reference gem commit
- Add/edit a UK degree
- Search for ICAS or type "Institute..."
- Institute of Chartered Accountants of Scotland should appear

[4652] Update dfe-reference gem to bring in new institution

---

.github/workflows/build-and-deploy.yml
spec/spec_helper.rb
spec/support/sentry_for_rspec.rb

Trello: https://trello.com/c/Bcoyw3fw/4510-s-capture-more-information-around-the-flakey-tests-so-we-can-try-and-fix-them
We want to add some functionality to easily detect and report on flakey specs. We want to send a capture_message to Sentry when a test has been retried so we can see which ones are flakey.
I've customised the sentry events so that they are grouped by the test path. This means the counts and grouping should increment successfully in Sentry for each fail, like below:
I've added a custom scope so that we can track the information we need, you can see this in the Sentry UI:
I've also added a custom tag (location) but we might not need this/might want more. That allows us to filter by tag in Sentry. Perhaps an 'rspec' tag would be helpful?
~~I've added …

[4510] Fire Sentry message when tests are retried in CI

---

app/controllers/trainees_controller.rb
app/helpers/filter_helper.rb
app/views/trainees/_selected_filters.html.erb
spec/features/trainee_actions/filtering_trainees_spec.rb

From Round 25 of UR and support tickets, we know that users are finding it confusing that the 'registered trainees' page has a filter for 'in training' selected. It needs to be deselected to search for historic trainees.
Remove the pre-selected 'in training' filter on the 'registered trainees' page here: https://www.register-trainee-teachers.service.gov.uk/trainees
not a lot!

[4704] - Remove pre-selected in-training filter for 'registered trainees' in top navigation

---

app/forms/apply_applications/confirm_course_form.rb
app/forms/concerns/course_form_helpers.rb
app/forms/course_details_form.rb
app/forms/publish_course_details_form.rb
db/data/20220921084032_fix_apply_draft_training_routes.rb
spec/features/form_sections/teacher_training_data/apply_applications_spec.rb

https://trello.com/c/8KhAFVTW/4659-course-not-showing-as-correct-route-from-apply
- Update `PublishCourseDetailsForm` to copy course route onto `training_route` and to clear funding information of the training routes changes
- Data migration to fix some Apply draft trainees that have a different training route to the course route
- Find a trainee e.g school direct (fee funded)
- Change course with a different route
- New training route should be displayed in the trainee show page

[4659] Course not showing correct route from Apply

---

.github/workflows/database-backup.yml

https://trello.com/c/sNdDNMXW/678-remove-bat-cf-and-db-github-secrets
The database backup workflow references some Github secrets that are also maintained elsewhere
- Cf user and pwd, changed to reference Azure keyvault values
- cf space, changed to reference workspace variables
- Storage account connection key, changed to reference Azure keyvault values  
Update database-backup workflow
Check workflow 
Check test run 
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/3105525276/jobs/5032139097

Move CF and DB github secrets to Azure keyvault

---

.github/workflows/database-backup.yml

Remove an if statement that shouldn't be in the db backup workflow
Added incorrectly under PR 2744
removed
if: env.TF_STATE_EXISTS == 'true'
check syntax

remove TF_STATE_EXISTS from db backup workflow

---

app/views/guidance/dates_and_deadlines.html.erb

Due to the bank holiday, HESA have pushed the deadline for an HEI's first data submission from 14 October to 17 October.
Changed '14 October' to '17 October'
Check it didn't break anything.
https://trello.com/c/xSN4mO3U/4706-let-providers-know-were-extending-the-dates-and-deadlines-for-sign-off-by-an-extra-day

Update dates and deadlines from bank holiday

---

config/locales/en.yml

'System admin' isn't terminology used by any other BAT service. We want to use 'Support for Register' as this is what support agents would understand and it's more consistent. We have a later ticket to change URLs and other parts.
- Change the content for 'system admin' to 'Support for Register'.
- Check it didn't break anything.
- 

Change system admin to 'Support for Register'

---

app/services/degrees/create_from_csv_row.rb
app/services/trainees/create_from_csv_row.rb
lib/tasks/trainees_bulk_submit_hpitt.rake
lib/tasks/trainees_create_from_csv.rake
spec/lib/tasks/trainees_create_from_csv_spec.rb
spec/services/trainees/create_from_csv_row_spec.rb

Follow on work from https://github.com/DFE-Digital/register-trainee-teachers/pull/2741
I didn't want to rename the files in the same PR so that the diff was preserved for ease of review.
Rename the HPITT rake task and service now that they can be used for any SCITT.
Decide whether you like the names, then 👍 or 👎 . 

[4656] Rename HPITT service and rake task

---

config/analytics_pii.yml

All provider facing services (Publish, Manage and Register) each have their own provider users in their services. There is currently no shared identifier across the services for provider users that is accessible for analytics. Therefore there isn't a method through BQ to see which provider users engage with each service.
With ITT reform changing how we onboard providers into TS, it's important for us to have a true reflection of provider users across the service.
Register has a dfe_sign_in_uid in the users table which is not anonymised.
Apply has a dfe_sign_in_uid in the provider_users and support_users tables which is anonymised
Publish has a sign_in_user_id in the user table which I've confirmed with @avinhurry matches the above IDs, but currently isn't streamed at all (it's in their …

Anonymise dfe_sign_in_uid

---

app/controllers/guidance_controller.rb
app/views/guidance/_course_details.html.erb
app/views/guidance/_database_only.html.erb
app/views/guidance/_funding.html.erb
app/views/guidance/_personal_details.html.erb
app/views/guidance/_schools.html.erb
app/views/guidance/_trainee_progress.html.erb
app/views/guidance/hesa_register_data_mapping.html.erb
app/views/guidance/show.html.erb
app/views/pages/home.html.erb
config/routes.rb
spec/controllers/guidance_controller_spec.rb

Create new page of content 'Check the data mapping between HESA and Register trainee teachers'
This is because we are improving and expanding the guidance pages for Register. 
- The Guidance index page has a link to the new page. The link should be called 'Check the data mapping between HESA and Register trainee teachers' - Guidance index page in the prototype: https://register-prototype.herokuapp.com/guidance
- The Homepage has a link to the new page. The link should be called 'Check the data mapping between HESA and Register trainee teachers' - Homepage in the prototype: https://register-prototype.herokuapp.com/home
- New page is created with URL: register-trainee-teachers.service.gov.uk/guidance/hesa-register-data-mapping
- It has the content from the prototype: …

[4631] Add hesa data mapping page

---

app/services/trainees/create_from_apply.rb
app/services/trainees/create_timeline_events.rb

https://trello.com/c/Dy9EkYtf/4568-multiple-timeline-entries-for-record-imported-from-hesa
- Fix `Trainees::CreateTimelineEvents` so that it doesn't show 'Record imported from HESA' more than once. This was happening because code was considering new degrees as a trainee record import.
Not possible to test in a PR environment. The following screenshots are taken from real trainee in production that was the example used in the Trello card:
Before           |  After
:-------------------------:|:-------------------------:

[4568] Fix multiple timeline entries for 'Record imported from HESA'

---

app/components/course_details/view.rb
spec/components/course_details/view_spec.rb

https://trello.com/c/8KhAFVTW/4659-course-not-showing-as-correct-route-from-apply
This PR is a postfix for #2743 which updates a trainee's route to the course route on change, but the confirm page was not showing the new root.
- Find a trainee e.g school direct (fee funded)
- Change course with a different route
- New training route should be displayed in confirm course page

[4659] Fix CourseDetails::View, so it can display a changed route

---

lib/tasks/trainees_hpitt_bulk_submit.rake

https://trello.com/c/G22kJqb7/4707-m-prepare-bulk-submission-of-teachfirst-trainees-for-their-trns
Update and renames tasks to submit hpitt trainees for TRN.
If you change one of your providers locally to have the "HPITT" code, you could run this task and check that their completed drafts are submitted for TRN.

[4707] Tidy up HPITT bulk submit task

---

app/views/guidance/_course_details.html.erb
app/views/guidance/_personal_details.html.erb
app/views/guidance/_trainee_progress.html.erb

We've changed some of the CSV column names but this was not reflected in the guidance. These are content edits to make sure the guidance matches the CSV.
Updating CSV names mentioned in the HESA to Register data mapping guidance
Relates to this ticket: https://trello.com/c/0BCChnXI/4665-change-column-names-in-the-register-csv-to-match-the-ui

Updating guidance to match new csv names

---

app/jobs/dqt/register_for_trn_job.rb
app/models/dqt/trn_request.rb
app/services/dqt/register_for_trn.rb
spec/jobs/dqt/register_for_trn_job_spec.rb
spec/models/dqt/trn_request_spec.rb
spec/services/dqt/register_for_trn_spec.rb

Sometimes we receive a 500 from DQT even though the TRN request is eventually successful. Because of this, we still want to save the dqt_trn_request to the DB when it fails. This means we can kick off a `RetrieveTrnJob` (which requires the request_id) in the future.
- Add a new `failed` state enum to the Dqt::TrnRequest model
- Update `RegisterForTrn` service to:
- save a failed Dqt::TrnRequest on failure
- find_or_create the `Dqt::TrnRequest` so that we're using the same request_id for subsequent calls to DQT.
- Update `RegiserForTrnJob` to only kick off `RetrieveTrnJob` if the dqt_trn_request is not in a failure state.

[4746] Create a Dqt::TrnRequest when the request fails

---

config/settings/production.yml

We turned off pulling in HESA data to send to DQT because we had an incident whereby dupes were being created on DQT. We (and DQT) have done the work to stop this happening now.
Fix:
https://github.com/DFE-Digital/register-trainee-teachers/pull/2786
Turn the HESA collection back on.

[xxx] Turn the HESA collection back on after incident

---

.github/actions/deploy/action.yml
.github/workflows/delete-review-app.yml
.tool-versions
terraform/terraform.tf

Dependabot is erroring when trying to check the azurerm provider update against version 1.2.3 of Terraform. Update to 1.2.8 to see if this resolves the issue.
Bump Terraform to 1.2.8

Update Terraform version to 1.2.8

---

app/jobs/dqt/sync_trainee_trn_job.rb
app/services/dqt/find_teacher.rb
spec/jobs/dqt/synv_trainee_trn_job_spec.rb
spec/services/dqt/find_teacher_spec.rb

https://trello.com/c/fZe1yFlJ/4749-create-or-update-service-to-retrieve-a-trn-without-a-requestid
- Create Dqt::FindTeacher that takes a trainee and hits the /teachers/find
DQT API endpoint, passing the first_names, last_name and date_of_birth
as params
- If no teachers or multiple teachers are found, it errors
- Create Dqt::SyncTraineeTrnJob which calls the Dqt::FindTeacher service
and updates the trainee with the returned TRN
- If no TRN is returned, it errors
To be used like so:
```
trainees = Trainee.where({some_condition})
trainees.find_each do |trainee|
Dqt::SyncTraineeTrnJob.perform_later(trainee: trainee)
end
```

[4749] Service to retrieve a teacher from DQT without a `requestid`

---

app/jobs/dqt/sync_trainee_trn_job.rb
spec/jobs/dqt/synv_trainee_trn_job_spec.rb

Another change :)
As well as assigning the trn to the trainee, we need to transition them to `trn_received`. There is logic in the trainee model which ensures that only `submitted_for_trn`, `withdrawn` or `deferred` trainees can be transitioned to `trn_received`
- Transition the trainees to `trn_received` using our custom `trn_received!(trn)` method which also set the trn
- Stop using the `Trainees::Update` service since we don't need anything it does (setting academic cycles, updating DQT) 
- Also pass around the trainee ID rather than the whole trainee, this is erroring.

[xxx] Transition the trainees to trn_received in Dqt::SyncTraineeTrnJob

---

app/models/trainee.rb
spec/models/trainee_spec.rb

Provider is trying to delete draft records but having issues: trainees were moved back into draft, but after they had requests made for TRNs. This is preventing deletes owing to the foreign key in `dqt_trn_requests`
Add `dependent: :destroy` to allow the trn request record to be deleted as well.

[4757] - add dependent: :destroy to trainee's trn request

---

db/data/20221005141340_import_apply_applications_no_longer_seen_as_duplicates.rb

https://trello.com/c/dM4kLSzT/4711-apply-duplicate-record-check-doesnt-scope-by-provider-or-active-trainees
This PR was meant to also contain the logic that checks if the new trainee exists, but that got accidently commited in another [PR](#2761).
- Data migration that runs through all the Apply applications marked as `non_importable_duplicate` (approx 900) and tries to re-import them using the new logic that checks if the trainee exists.
The data migration was tested locally using prod data. 6 news trainees were created. Takes only a few seconds to run.

[4711] Data migration to import Apply applications no longer seen as duplicates

---

config/settings.yml

Within Register, we have this defining which years we request:
```yaml
apply_applications:
import:
recruitment_cycle_years:
- 2021
- 2022
```
* Over on Apply’s side, upon receiving our request they check that the recruitment_cycle_year being sent is within the range they define as RecruitmentCycle.years_visible_to_providers here
* This references the current_year as defined in the CycleTimetable.
* At the moment this calculates the current year as 2023 meaning they only accept requests for 2023 (current year) and 2022 (previous year)
* We can fix this by losing 2021 in the definition above.
Further discussion [here](https://ukgovernmentdfe.slack.com/archives/CGVNJ2Q2F/p1664975872165529) and [here](https://ukgovernmentdfe.slack.com/archives/CAHBLU6ET/p1664962366889509) 
NB: Please notify …

[4254] - remove 2021 from recruitment_cycle_years

---

app/forms/concerns/course_form_helpers.rb
app/forms/course_details_form.rb
app/forms/publish_course_details_form.rb

https://trello.com/c/F9QZeh9e/4748-course-dates-get-lost-on-registered-trainees-when-changing-course
`PublishCourseDetailsForm` wasn't showing `itt_start_date` or `itt_end_date` because it was wrapped in a conditional which I don't think is relevant anymore. I think the conditional was added before we created the ITT dates page.
- Remove conditional from `PublishCourseDetailsForm#itt_start_date` and `PublishCourseDetailsForm#itt_end_date`. The idea here is that if the `IttDatesForm` has stashed dates, we have to assume it was used previously and `PublishCourseDetailsForm` should default to its values first before falling back to the course dates.
- Extract method to clear all stashes used beforehand and put it in `CourseFormHelpers` so it can be use by `CourseDetailsForm` which was …

[4742] Fix: course dates get lost when changing course.

---

app/jobs/hesa/upload_trn_file_job.rb

- Trainees can be submitted for TRN and for census at the same time from HESA.
- If this happens, when the `UploadTrnFileJob` runs, they have a record source of `hesa_collection` and won't be included in the CSV.
- We still want to send the TRNs back in this case!
- We've checked with HESA and they've confirmed that they're happy for TRNs to be returned for trainees regardless of whether they were submitted as part of the collection or over the TRN data endpoint.
https://trello.com/c/r3tCZxpE/4760-not-returning-trns-to-hesa-for-trainees-submitted-via-the-trn-data-endpoint-and-then-very-quickly-over-the-collection-endpoint
- Widen the scope so that we send back TRNs for trainees with record source `hesa_collection` too.
- This is what we originally had! …

[4760] Dont limit the TRN upload to just trn_data hesa trainees

---

config/sidekiq_cron_schedule.yml

Duplicate trainees are being created when they are submitted over the TRN data endpoint and HESA collection endpoint simultaneously.
Stagger the jobs to lessen the chance of this happening.

[xxx] Stagger HESA import jobs

---

app/forms/publish_course_details_form.rb
app/forms/subject_specialism_form.rb
spec/forms/publish_course_details_form_spec.rb
spec/forms/subject_specialism_form_spec.rb

https://trello.com/c/oKixSiln/4742-drafts-changing-from-a-course-without-funding-to-one-with-funding-user-is-not-asked-about-funding-again
- Clear funding in `SubjectSpecialismForm` as that is where subject specialism are computed and assigned
- Remove couse subject updates from `PublishCourseDetailsForm` as it will always happen in `SubjectSpecialismForm`
- Find a draft traine with a published course
- Change that course to something else
- The review draft page should show funding as incomplete

[4742] Fix: funding not cleared properly when changing courses multiple times

---

Gemfile
Gemfile.lock
app/jobs/dqt/register_for_trn_job.rb
config/initializers/sidekiq.rb

DQT is receiving multiple requests almost simultaneously
We'd like to throttle our trn requests until DQT have increased their confidence in their handling of duplicate requests

Reduce the concurrency for register for trn jobs

---

app/lib/apply_api/code_sets/genders.rb
spec/services/trainees/create_from_apply_spec.rb

Apply has changed one of their radio button values on the gender/sex question for E&D from intersex to other. This is not currently handled by Register's mapping when creating trainees from Apply. Old values are not being updated so there will be both intersex and other values.
* Add 'other' key-value pair to mapping

[xxx] Add other to gender code mapping

---

app/jobs/dqt/recommend_for_award_job.rb
app/jobs/dqt/register_for_trn_job.rb
app/jobs/dqt/retrieve_award_job.rb
app/jobs/dqt/retrieve_trn_job.rb

DQT background jobs are going into the default queue. There is a dedicated `dqt` queue that is already used by two other related jobs.
Use the `dqt` queue for DQT related background jobs.

Move dqt jobs to their own queue
