- db/data/20221010142433_backfill_unmapped_hesa_degree_grades.rb
The data migration from #2819 is breaking main deployment because the staging environment doesn't have the credentials for HESA login. This quick fix makes sure the XML is valid before continuing any further.
> [xxx] Fix data migration so it works in staging environment

- app/services/trainees/create_from_hesa.rb
- app/services/trainees/map_state_from_hesa.rb
- spec/services/trainees/map_state_from_hesa_spec.rb
This is the timeline which is causing the bug (i think):
- We receive a trainee from HESA over the TRN endpoint and request a TRN from DQT
- We get a TRN back and save it on the trainee in Register, transitioning it to trn_received
- We receive the same trainee from HESA over the collection endpoint, with no TRN (in HESA) and re-set the state to submitted_for_trn
- We send the TRN data back to HESA and they save it on the trainee.
https://trello.com/c/RjRU4lY3/4777-hesa-trainee-updates-overwrite-trainee-state-in-register
- Check that a trainee has a TRN in Register before calculating the state, otherwise if HESA haven't yet set it their end, we'll likely transition the trainee back to submitted_for_trn.
NB: Please notify the #twd_data_insights team and ask for a review if new fields are …
> [4777] Check for a trn in Register when setting the trainee state from HESA

- app/jobs/trainees/set_academic_cycles_job.rb
https://trello.com/c/92cvxDcL/4778-trying-to-set-academic-cycle-on-a-trainee-that-doesnt-exist
- Update `Trainees::SetAcademicCyclesJob` so that it doesn't proceed unless the trainee exists
> [4778] Protect Trainees::SetAcademicCyclesJob from deleted trainees

- app/services/dqt/trainee_update.rb
- spec/services/dqt/trainee_update_spec.rb
Worked with Mark on this - we have decided to raise an error if we call TraineeUpdate on a trainee with no TRN. This was causing 405s on the Dqt::UpdateTraineeJob. We need the TRN to be able to send the update to DQT, so let's not call the job, but instead catch the errors. 
* raise an error if trainee.trn.blank? when we call TraineeUpdate
> [xxx] Add nil TRN check to TraineeUpdate

- app/services/exports/trainee_search_data.rb
- spec/services/exports/trainee_search_data_spec.rb
Fixes the nil handling error we've seen repeatedly on the ReportsController#itt_new_starter_data_sign_off
https://sentry.io/organizations/dfe-teacher-services/issues/3554532428/?environment=production&project=5552118&query=is%3Aunresolved
There might be a better way to handle this but stops the erroring for now.
* Add nil handling in trainee_search_data.rb
* We let them export the CSV but I've added a string to say there is no data
* Delete trainees for a user and log in as them (I used Damian Campbell persona locally)
* Navigate to reports
* Export the CSV
* See that the CSV successfully exports and contains the message "No trainee data to export"
> [xxx] Fix nil error on new starter data sign off export

- app/jobs/hesa/retrieve_job.rb
- app/jobs/hesa/upload_trn_file_job.rb
- config/sidekiq_cron_schedule.yml
- db/data/20221013154712_backfill_hesa_trn_submissions_rerun.rb
- spec/jobs/hesa/upload_trn_file_job_spec.rb
HESA expect to receive a CSV from Register on a daily basis. Hourly CSVs have led to duplicate automated emails being sent to HEIs.
- Only send the CSV to HESA once per day at 10:10
- Move HESA jobs to `hesa` queue
- Record the trn submission id on the trainee record
> [4792] Decrease rate of sending csv to HESA

- app/services/degrees/create_from_hesa.rb
- spec/services/degrees/create_from_hesa_spec.rb
https://trello.com/c/NT6fgpnB/4791-investigate-why-so-many-trainees-are-being-returned-without-their-degree-country
HESA institution code 0133 (Institute of Education) is not listed in the `dfe-reference` gem but it is part of University College London (0149), therefore it can be remapped.
There is one trainee that is affected by this and will be fixed manually once the PR has been approved and merged.
> [4791] Add mapping rule for degree institution (HESA import)

- app/components/course_details/view.rb
- config/locales/en.yml
- spec/components/course_details/view_spec.rb
HESA now send us an ITT end date, so we should show this on the record if present
Before:
After:
Find a HESA trainee
See that their itt_end_date is now shown
> [4745] Show itt_end_date for HESA trainees

- Gemfile
- Gemfile.lock
- app/services/degrees/create_from_hesa.rb
- app/services/degrees/dfe_reference.rb
- db/data/20221020131904_fix_unmapped_degree_institutions.rb
- spec/services/degrees/create_from_hesa_spec.rb
https://trello.com/c/TmgbXgRa/4800-unmapped-institutions-from-def-reference-gem-causing-missing-country-errors
- Update `Degrees::DfeReference` to use the `DfE::ReferenceData::Degrees::INSTITUTIONS_INCLUDING_GENERICS`
- Update `Degrees::CreateFromHesa` to fallback to "Other UK institution" if the institution HESA code is not in the `dfe-reference` gem
- Data migration to re-create degrees for those trainees that had an insitution HESA code but couldn't be found in the `dfe-reference` gem. This will make those degrees UK based instead of non-UK.
"Other UK institution" has now been added to the degree institution list and can be tested by visiting a new or edit degree page
> [4800] Unmapped institutions from def-reference gem causing missing country errors

- config/sidekiq_cron_schedule.yml
Trainees are getting marked as awarded whether they have EYTS or QTS
Disabling the scheduled run of `sync_trainee_states_with_dqt`
> [4866] Remove sync_trainee_states_with_dqt cron

- config/locales/en.yml
We've had a couple cases of providers not able to locate schools - it would help if they searched first on GIAS before contacting us.
In one example, they were searching using a postcode that was different than the postcode in GIAS
In the other the school name was too common and they had the wrong URN.
This is a copy of the [same change in the prototype](https://github.com/DFE-Digital/register-trainee-teachers-prototype/pull/581).
> Link to GIAS service from school picker pages

- app/forms/concerns/course_form_helpers.rb
- app/forms/course_details_form.rb
- app/forms/publish_course_details_form.rb
Worked on this with John. We think the [downcase error](https://sentry.io/organizations/dfe-teacher-services/issues/3662991514/?project=5552118) is being caused by some dodgy stashed data on the CourseDetailsForm. We recently changed some code which meant we were no longer clearing that stash in the same way on that form. We've added code to make sure we clear the stash correctly as we do with other course related forms.
* Update method name `def clear_all_course_related_stashes` and add forms CourseEducationPhaseForm, CourseDetailsForm and PublishCourseDetailsForm
> [4830] Clear form stashes as well as other course related stashes

- app/services/trainees/create_from_hesa.rb
- db/data/20221025091052_fix_trainee_states.rb
https://trello.com/c/VVsDRyYA/4860-trainee-not-coming-through-on-hesa-correctly
Trainees that have been withdrawn or deferred can return to the course (state goes back to `trn_received`). Therefore we should wipe the data related to withdrawal or deferral. In card we have one such case:
> This trainee (Kylie Nash, link below) withdrew from Wolverhampton in 2021. They have now returned and are reported as being on the course in HESA. It's still saying they are withdrawn on Register with a leave date of October 2021 and a start date of September 2022, which is obviously contradictory.
- Remove `compact` statement to allow for `nil` values that are intended to clear previously populated data based on the previous state
NB: Please notify the #twd_data_insights team and ask for a review if new …
> [4860] Clear data about withdrawal or deferred if trainee goes back to `trn_received`

- app/services/degrees/create_from_hesa.rb
- db/data/20221025133503_add_other_to_no_country_no_institution_degrees.rb
- spec/services/degrees/create_from_hesa_spec.rb
These are degrees that are coming from HESA with no country and no institution resulting in failed TRN requests.
* Map a HESA degree with no country to UK
* Map a HESA degree with no institution to `Other UK institution`
* Backfill HESA degrees with nil country and nil institution to the above.
* Check changes in `app/services/degrees/create_from_hesa.rb`
* Check degree filter in `db/data/20221025133503_add_other_to_no_country_no_institution_degrees.rb` is sensible
> [4879] - fix HESA degrees with no institution and country

- db/data/20221026095735_fix_incorrectly_awarded_trainees.rb
Data migration to fix the states of some trainees that were accidentally awarded. We synced their state with DQT but accidentally picked up their EYTS records. These trainees are awarded EYTS and not QTS. So setting them back to trn_received.
* Add data migration
* I ran this locally by updating trainees to have these TRNs. It ran ok and they updated successfully.
* Will test in production data
> [4876] Fix incorrectly awarded trainees

- terraform/workspace-variables/production.tfvars.json
https://trello.com/c/TE5yaN2z/4897-investigate-register-performance-under-high-load
Production has been going down due to excessive load on expensive pages such as `/trainees`. After load testing the site, it was determined that 2 app instances is not enough especially during busy periods such as Oct-Nov. 4 app instances proved to be much more performant and was able to handle heavy load. Autoscaling is probably the long term approach, but for now, adding more resources gives the users a better experience and reduces downtime.
- Update Terraform config to increase production app instances from 2 to 4
> [4897] Increase production app instances to 4

- db/data/20221027124342_fix_incorrectly_withdrawn_trainees.rb
Trello: https://trello.com/c/gfJLvUUa/4903-move-withdrawn-trainees-to-trn-received
We accidentally set some trainees to withdrawn. Set them back to trn_received.
We also have some withdrawal reasons and dates for deferred and trn_received trainees. Remove the withdrawal info.
I've used the slugs as the TRNs are no longer reliable unique identifiers for trainees.
* Add data migration
* Ran locally and worked fine. Will test on prod data too. 
> [4903] Set incorrectly withdrawn trainees back to trn_received

- app/views/guidance/_database_only.html.erb
- app/views/guidance/_schools.html.erb
All lines of content should be in 2/3 columns. These were overlooked when this was delivered.
Before:
After:
> Put paragraphs in 2/3 grid column

- app/components/sort_links/style.scss
- app/components/sort_links/view.rb
- app/controllers/base_trainee_controller.rb
- app/helpers/exports_helper.rb
- app/views/funding/payment_schedules/show.html.erb
- app/views/funding/trainee_summaries/show.html.erb
- app/views/trainees/_action_bar.html.erb
- app/webpacker/styles/trainee_list.scss
- config/settings.yml
- spec/helpers/exports_helper_spec.rb
Trello: https://trello.com/c/4W7x9nWU/4858-add-limit-to-number-of-trainees-that-can-be-exported-in-system-admin
This came out of the incident review. We will prevent system admins from exporting over 100 trainees. This PR is cosmetic and hides the link, but does not alter export permissions.
* Update application.scss
* Update style.scss
* Update ExportsHelper with `def exceeds_export_limit?`
* Update _action_bar_html.erb
* Update components/sort_links/view.rb to get the padding right on the sorting in the action bar
* Are there any other export links I've missed? I haven't done anything to the reports export as part of this ticket. This is scoped to year and is more difficult to extract by accident.
NB: Please notify the #twd_data_insights team and ask for a review if new fields are being …
> [4858] Remove export link for System admin when more than 100 trainees

- app/services/concerns/has_diversity_attributes.rb
This is the first year that HESA has supported multiple disabilities. They might not have thought to add validation that some of the options are mutually exclusive. For example, one trainee had "Mental health condition" and "No known disability" which shouldn't be possible. "No known disability" is not in the database of disabilities therefore Disability.find_by(name: disability) return nil and that led to a ActiveRecord error AssociationTypeMismatch during the save operation. Using `compact` will ensure nil values are removed, but hopefully HESA will implement validation in the future.
> [xxx] Fix HESA importer with regards to disabilities

- .github/actions/deploy/action.yml
The set-output command is being deprecated soon.
Resolution is to use $GITHUB_OUTPUT as per the workflow commands docs.
Confirm impacted workflows work as expected:
> Stop using set-output in check_sp workflow

- app/components/funding/view.rb
Troops to teachers bursary currently doesnt show the correct funding value in the register UI. This will need to be changed eventually - probably with a refactor of the funding work. In order not to confuse users we should hide the funding value for trainees on the troops to teachers initiative. 
> [4733] Hide funding row if troops to teachers initiative trainee

- app/services/trainees/create_from_hesa.rb
If Trainees::MapStateFromHesa returns nil, it means we don't know enough to transition it to withdrawn, so it should stay as deferred or TRN received
- Add a `compact` statement to remove `nil` values
> [xxx] Don't override trainee state if HESA importer computes it as nil

- db/data/20221108114154_update_dqt.rb
https://trello.com/c/wFWg0GfD/4912-investigate-if-we-are-sending-updates-for-hesa-records-to-dqt
- Move `next` statement into its correct position so it can access `trainee`. The batch approach was added towards the end due to the 300/minute DQT API rate limit, so the position of `next` was overlooked during refactoring.
- Also forget to recalculate the academic cycle dates as part of https://trello.com/c/tQj4nowc/4893-2022-23-itt-record-export-showing-different-value-compared-to-on-screen.
> [xxx] Fix DQT update migration

- Gemfile
- Gemfile.lock
- config/analytics_blocklist.yml
- db/migrate/20221114121151_add_more_columns_to_hesa_students.rb
- db/schema.rb
- lib/tasks/update_hesa_students_table.rake
https://trello.com/c/45l1fWTK/4983-refresh-the-hesastudents-table-with-the-records-for-c22053-collection
There is work been done to remove the duplicate HESA trainees from Register after providers mistakely submitted trainees with the wrong HESA ID. Populating the `hesa_students` table with the latest HESA collection will help facilate this goal.
- New rake task `hesa:update_students_table`
- Migration file to add more fields to the `hesa_students` table after recent updates to `Hesa::Parsers::IttRecord::TAG_MAP`
- Run `rake hesa:update_students_table`
- XML should be fetched and processed (takes awhile, but there is a progress bar)
> [4983] New rake task to update `hesa_students` table

- app/lib/dqt/params/trn_request.rb
- spec/lib/dqt/params/trn_request_spec.rb
@robertcollier13 reported to us that we currently map school_direct_tuition_fee to school direct training programme (self funded) in the Register to DQT API
This is incorrect - self-funded is a niche course that isn't used anymore.
We should change the mapping for these routes from SchoolDirectTrainingProgrammeSelfFunded to  SchoolDirectTrainingProgrammeSalaried.
> [4994] Change schooldirecttuitionfee mapping in dqt api

- lib/tasks/update_hesa_students_table.rake
`Nokogiri::XML(xml_response).root.children.size` was causing the rake task to get killed for using too much memory probably because Nokogiri was loading all XML nodes into memory before counting.
- Use `String#scan` instead of `Nokogiri::XML`
> [xxx] Fix: rake task to update hesa_students table getting killed for memory usage

- app/views/guidance/check_data.md
We had some feedback from a user that they thought this section was referring to placement schools. Working with @johndoates we've reworded the heading to match what the task list shows - which should hopefully make the meaning clearer.
> Update heading to make clearer which schools we mean.

- app/services/hesa/backfill_trainee_states.rb
- lib/tasks/fix_incorrect_hesa_trainee_states.rake
- spec/services/hesa/backfill_trainee_states_spec.rb
Trello: https://trello.com/c/JBDzn2SU/4927-records-not-transitioning-from-deferred-to-withdrawn
Some HESA trainees that we classified as deferred should actually have been classed as withdrawn. This happened because if a trainee has transitioned from deferred -> withdrawn in HESA, they still send us the dormant code for MODE. Our check wasn't robust enough to recognise that these trainees were actually withdrawn (they had dormant code in addition to withdrawal information). We fixed the root issue but making the check stricter.
This is a rake task to backfill the correct withdrawal attributes on those incorrectly deferred trainees. We have no way of knowing which deferred HESA trainees have been affected, so the rake will run against all deferred HESA trainees (approx 3090).
* Add …
> [4927] Backfill correct withdrawn attributes for incorrectly deferred trainees

- db/data/20221117160629_remove_duplicate_hesa_trainees.rb
https://trello.com/c/E52FrdFl/4974-l-check-duplicate-hesa-trainees-to-be-deleted-and-then-delete-these-trainees-from-register
- Data migration to remove duplicate trainees
- Takes about 2 minutes to run
- Removes 940 duplicate trainees
- Leaves behind 3 duplicates that have to be dealt with manually because they are each in the HESA collection XML except for their HESA ID (one using 13 digit format, the other the new 17 digit format). We need to go back to HESA to ask the provider to re-commit the data using either the 13 digit HUSID or the 17 digit HUSID, but not both.
> [4974] Data migration to remove duplicate HESA trainees

- app/services/trainees/create_from_hesa.rb
- db/data/20221124151149_backfill_non_applicable_schools_for_trainees.rb
- spec/services/trainees/create_from_hesa_spec.rb
https://trello.com/c/kWc2qlIL/5008-hesa-lead-and-employing-schools-not-mapping-codes
- Update `Trainees::CreateFromHesa` so it can handle the schools URN's 900000 and 900010 and map it as not applicable
- Data migration to fix existing trainees using their HESA student record
After the data migration:
- 177 trainees will have `lead_school_not_applicable` set to `true`
- 5 trainees will have `employing_school_not_applicable` set to `true`
> [5008] HESA lead and employing schools not mapping codes

- app/controllers/trainees/personal_details_controller.rb
- app/lib/apply_api/code_sets/nationalities.rb
- app/lib/dttp/code_sets/nationalities.rb
- app/models/nationality.rb
- db/data/20221125114348_add_cypriot_nationalities.rb
- spec/models/nationality_spec.rb
Trello: https://trello.com/c/edXQJ5f4/4907-itt-register-portal-data-check-for-c22053
Cypriot nationality did not map for some HESA trainees because we did not hold the HESA codes XA and XB in Register. Apply also does not currently hold them in their nationalities mapping, but does in their countries and territories: https://github.com/DFE-Digital/apply-for-teacher-training/pull/6584
I spoke with Duncan and we agreed that Register should accept the valid HESA nationality codes for Cyprus, and allow them to be added to our seeded nationalities. They will also display in our nationality autocomplete. We should hide the existing generic 'cypriot' option from the autocomplete so that providers must choose between EU or non-EU.
We do not need to alter any existing Cypriot trainee …
> [4907] Add HESA Cyprus codes

- app/components/application_record_card/view.rb
- app/controllers/application_controller.rb
- app/controllers/application_controller_dev.rb
- app/services/feature_service.rb
During the load testing performed after the recent incident that brought register down it was noticed that there were a lot of requests to the `/trainees` endpoint and it is quite an expensive request.
* remove calls to the audit table for each trainee (a trainees `updated_at` field is now updated through `touch` callbacks where relevant)
* academic cycle year is retrieved via trainee rather than searched for via trainees 
* adds helper module for performance testing (not invested in this if it looks like bloat!)
> [4992] - Improve the performance of the trainees endpoint

- db/data/20221125160837_backfill_cyprus_nationality_for_hesa_trainees.rb
HESA trainees with nationality code "XA" have not had their nationality mapped. This fixes that. I got the ids of the relevant trainees and this adds the Cypriot EU nationalisation for them.
* Data migration to add Cypriot EU nationalisations for relevant trainees
* Run data migration, see nothing explodes
> [5022] Add EU Cypriot nationality for HESA trainees

- app/controllers/trainees/confirm_details_controller.rb
https://trello.com/c/APnECMWK/4740-weird-text-for-trainee-start-date-flash-messages
- Tweak the `Trainees::ConfirmDetailsController#confirm_section_title`
- Find a registered trainee without a start date
- Add a start date
- Look at flash message.
> [4740] Fix weird text for trainee start date flash messages

- app/views/guidance/dates_and_deadlines.html.erb
We currently tell users the deadline for signing off census data but not for signing off performance profile data.
As well as adding a line about the performance profiles in the same style as the census information, I have:
- made a couple of small tweaks to the 1 November census entry so that I could fit the new one in more easily, for example saying that the data will be used for the census publication
- removed “Wednesday” from the first date, since the ‘what happens’ already explains it’s always on a Wednesday - by removing it we match the other date formats and can make the ‘what happens’ column a bit wider
> Add performance profiles deadline to dates and deadlines

- db/data/20221201163748_backfill_university_of_hull_trainees.rb
trello: https://trello.com/c/c7raaZT4/5040-university-of-hull-register-update
Amending details for some trainees at providers request. They need to be withdrawn. The trainees have either transferred to non ITT and were not returned in the census as a result, or were withdrawn before census and not returned by the provider. 
These might need updating on DQT - but currently we aren't sending things over the withdraw job so could send everything over once that's fixed (ticket to fix this in bugs)
* migration to update trainees to withdrawn with relevant info
* i've done an 'update_columns' so that we don't update the updated_at
* migration does not error
> [5040] Backfill trainees to be withdrawn

- app/components/form_components/users_autocomplete/script.js
- app/controllers/api/schools_controller.rb
- app/controllers/api/users_controller.rb
- app/controllers/system_admin/users_controller.rb
- app/models/user.rb
- app/services/user_search.rb
- app/views/system_admin/users/index.html.erb
- config/locales/en.yml
- config/routes/api_routes.rb
https://trello.com/c/PbsihW8T/4737-m-support-add-autocomplete-to-search-for-users
- Add autocomplete functionality to user search input field on `/system-admin/users`
- Login as system admin
- Visit the users page
- Begin search for users
- Suggestions should appear
- Choose one
- Page should automatically redirect to user page
> [4737] Support: add autocomplete to search for users

- app/models/trainee.rb
- app/services/trainees/filter.rb
- app/view_objects/home_view.rb
- spec/features/trainee_actions/filtering_trainees_spec.rb
- spec/models/trainee_spec.rb
- spec/view_objects/home_view_spec.rb
https://trello.com/c/yrVGKZ2r/5020-hesa-user-seeing-incomplete-on-record-shouldnt-incomplete-be-suppressed-for-hesa-records-can-we-check
- Return incomplete HESA trainees in the incomplete filter since we're showing the incomplete tag for these trainees
- Rename filter because it does return incomplete/complete trainees now
- Add missing tests for scope
- Find an incomplete HESA trainee
- Check that they are returned in the incomplete filter
> [4945] Return HESA incomplete trainees in filter

- app/controllers/base_trainee_controller.rb
- app/controllers/trainees_controller.rb
- app/helpers/trainee_helper.rb
- app/models/academic_cycle.rb
- app/models/trainee_filter.rb
- app/services/trainees/filter.rb
- app/views/trainees/_academic_year_filter.html.erb
- app/views/trainees/_filters.html.erb
- config/locales/en.yml
- spec/factories/academic_cycles.rb
- spec/models/academic_cycle_spec.rb
- spec/models/trainee_filter_spec.rb
- spec/services/trainees/filter_spec.rb
Trello: https://trello.com/c/q3r1pMkl/5045-l-add-new-academic-year-filter-to-registered-trainees-index-page
We want to be able to filter registered trainees by their academic year. This PR introduces that. The new trainee filter for academic year can also be used for the performance profile reports.
One thing to note - when selecting trainees by their academic year I have reused `def trainees_starting` and `def trainees_ending`. These methods also return trainees that have no start/end academic cycle in the current academic year. As we are only implementing the filter for registered trainees, this shouldn't really affect the trainees returned (they should all have start and end cycles by this point). But calling `AcademicCycle.current.total_trainees` will return those with nil cycles as …
> [5045] Add new academic year filter to registered trainees index page

- app/components/application_record_card/view.html.erb
- app/components/application_record_card/view.rb
- spec/components/application_record_card/view_spec.rb
End year is intended to be shown alongside start year where we have it.
Please let me know if this needs tests or not!
> Add end year to application cards

- app/controllers/funding/base_funding_controller.rb
- spec/features/funding/payment_schedule_spec.rb
The provider funding page always shows the `last` cycle of funding whether or not it is for the current academic year
Scope the funding data to only include the current academic year
If you have seeded your local db lately then seed funding data will be for the current academic year. You can bump all funding to the previous year with the following console commands:
```ruby
Funding::PaymentScheduleRowAmount.where(year: 2022).update_all(year: 2021)
Funding::PaymentScheduleRowAmount.where(year: 2023).update_all(year: 2022)
```
Funding data should no longer be visible:
> [5062] Fix show funding payment schedule

- Makefile
- terraform/modules/azure/README.md
- terraform/modules/azure/data.tf
- terraform/modules/azure/main.tf
- terraform/modules/azure/storage.tf
- terraform/modules/azure/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace-variables/production.tfvars.json
- terraform/workspace-variables/productiondata.tfvars.json
- terraform/workspace-variables/qa.tfvars.json
- terraform/workspace-variables/staging.tfvars.json
The team required a storage account that could be used to store temporary data while it is processed by the service. These storage accounts have been created manually in Azure through the Portal or by ARM templates in qa, staging, production and productiondata.
To ensure these are also controlled properly the need adding in to the Terraform code. We are unable to deploy these through the current workflows because the existing service principal does not have contributor privileges. Therefore, the creation of a storage account has been tested locally and the ARM templates of the existing storage account and that created using Terraform compared to ensure they aligned as much as possible.
The new Terraform resources have been commented out and can be brought in to use at a future date or …
> Add temp data Azure storage account to Terraform

- app/jobs/dqt/recommend_for_award_job.rb
- spec/jobs/dqt/recommend_for_award_job_spec.rb
https://trello.com/c/LvA4GAK4/5074-if-a-hesa-trainee-record-is-recommended-for-qts-in-support-we-should-allow-it-to-send-to-dqt
- Remove the guard clause that stopped HESA trainees from being awarded on HESA
View of HESA trainee as a normal user, still no award button:
> [5074] Send HESA awards to DQT

- app/jobs/dqt/withdraw_trainee_job.rb
- app/services/trainees/create_from_hesa.rb
- app/services/trainees/withdraw.rb
- spec/factories/funding/payment_schedule_row_amounts.rb
- spec/jobs/dqt/withdraw_trainee_job_spec.rb
- spec/services/trainees/create_from_hesa_spec.rb
- spec/services/trainees/withdraw_spec.rb
https://trello.com/c/qevoV3jl/5041-update-dqt-when-hesa-trainees-are-withdrawn
- Remove guard clauses to allow withdrawl updates to DQT from `Dqt::WithdrawTraineeJob` and `Trainees::Withdraw`
- Run `Dqt::WithdrawTraineeJob` in `CreateFromHesa` if trainee is in a withdrawn state but only if a TRN is present, otherwise, it will wait until a TRN has been issued
- Can't be reviewed manually
> [5041] Update DQT when HESA trainees are withdrawn

- app/controllers/guidance_controller.rb
- app/controllers/reports_controller.rb
- app/controllers/trainees_controller.rb
- app/helpers/navigation_helper.rb
- app/models/academic_cycle.rb
- app/views/guidance/performance_profiles.html.erb
- app/views/guidance/show.html.erb
- app/views/layouts/application.html.erb
- app/views/reports/index.html.erb
- app/views/reports/itt_new_starter_data_sign_off.html.erb
- app/views/reports/performance_profiles.html.erb
- config/routes.rb
- config/settings.yml
- spec/controllers/guidance_controller_spec.rb
- spec/controllers/reports_controller_spec.rb
- spec/features/reports/viewing_performance_profiles_spec.rb
- spec/support/features/page_helpers.rb
- spec/support/page_objects/reports/index.rb
- spec/support/page_objects/reports/performance_profiles.rb
https://trello.com/c/zx8ed8hy/5063-m-create-report-for-performance-profiles
- Add link on reports index for performance profiles
- Add new page and content for performance profile sign off
- Use new academic cycles filter to return trainees for performance profiles export
- Add new guidance page
- Fixed active link 'Reports' in nav
- Made more dates dynamic
- Sign in as a provider
- Click on the reports tab
- Check the link to the performance profiles sign off
- Click through and review the content
- Download the CSV and check the data
- Navigate to guidance, check the new list format
- Click into performance profiles guidance, check the content
> [5063] Create report for performance profiles

- app/views/funding/payment_schedules/_month_breakdown.html.erb
From the cross government slack:
> Placing the visually-hidden class directly on the <caption> tag causes the NVDA screen reader to read the table with an incorrect number of rows.
The [bug appears to be in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=995888).
Moves the visually hidden class to a span to avoid this bug. NB this may mildly affect the margins.
> Use hidden span rather than class to fix NVDA bug

- app/forms/training_details_form.rb
- app/services/find_empty_trainees.rb
- spec/forms/training_details_form_spec.rb
- spec/services/find_empty_trainees_spec.rb
Our previous trainee_id uniqueness check is inadequate as when there's an existing deleted record with the same trainee id, it will prevent the reuse of that ID. Additionally if one makes a draft trainee with a given ID, clicks return to this trainee later and tries to reuse the ID an error would be thrown.
This PR also covers a bug whereby if a trainee_id was entered for a record with no other details the record would be supressed as an empty record; but the uniqueness constraint would ensure the provider could never reuse that id. Trainees with a trainee_id will no longer be considered empty or supressed.
* Providers are prevented from having two 'active' records with the same trainee id. 
* Should be able to register a new trainee with a trainee id that is already on a withdrawn or …
> [5010] Improve uniqueness check on trainee id

- app/components/form_components/schools_autocomplete/script.js
- app/views/system_admin/lead_schools/index.html.erb
As a quick fix we want to add the autocomplete to the lead school index page in System Admin. This will enable the support team to find lead schools more easily.
There will be a future piece of work to build an autocomplete for all schools and consolidate the schools/lead schools lists into one index page. 
Currently I have not built the no-js equivalent as we hope to replace this with something nicer soon. If a user disables javascript, we hide the autocomplete.
* Update `schools_autocomplete/script.js`
* Update index page to add new autocomplete
* Log in as an admin
* Navigate to the system-admin/lead-schools
* Observe autocomplete
* Use autocomplete to find a school by name, URN or postcode
* Select a school
* Observe you are taken to the show page for that school
* Double check that …
> [5081] Add autocomplete to lead school admin index page

- app/jobs/dqt/withdraw_trainee_job.rb
- spec/jobs/dqt/withdraw_trainee_job_spec.rb
Using `Trainee#submitted_for_trn_at` to calculate the timeout was not a good idea since it sometimes can be nil or it's too far in the past to be useful. This job can we kicked off anytime in the future, so we just need to terminate it after a number of days if unsuccessful.
- Update `Dqt::WithdrawTraineeJob` to calculate the timeout without using `Trainee#submitted_for_trn_at` 
> [xxx] Fix Dqt::WithdrawTraineeJob

- db/service_updates.yml
I've added a news item about the new academic year filter.
The news item tells users that: 
- they can now filter the trainee list by academic year
- academic years now appear in the trainee data export
> Added news entry about academic year filter

- app/models/reports/trainee_report.rb
- app/models/reports/trainees_report.rb
- spec/models/reports/trainee_report_spec.rb
- spec/services/exports/export_trainees_service_spec.rb
- spec/services/exports/export_trainees_to_file_service_spec.rb
We've had multiple providers write in to support whilst doing their performance profiles sign off to tell us the value held in `course_award` as shown on the csv export is incorrect.
The value shown is the string text for `course_summary` that we get from Publish. It may be something like `PGCE with QTS full time`. The problem is that trainees may later drop the PGCE. The providers have then seen this in the column and ask us to remove the PGCE bit.
The column was originally added for completeness and to help providers identify courses. But in this situation it's causing concern where the publish course text doesn't match what the trainee is *now* doing. As a short term fix I think it better to just remove this from the export.
@ devs - please let me know if I've done this correctly. I …
> Remove course_award column that has been confusing users

- app/views/sign_in/index.html.erb
- config/initializers/omniauth.rb
- config/routes.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/production.yml
- config/settings/productiondata.yml
- config/settings/qa.yml
- config/settings/review.yml
- config/settings/staging.yml
- config/settings/test.yml
- docs/support_playbook.md
- spec/config/settings_spec.rb
- spec/features/auth/otp_authentication_spec.rb
- spec/features/auth/sign_in_page_spec.rb
- spec/requests/dfe_analytics_events_spec.rb
- spec/support/features.rb
The sign in method is currently determined by two bools: `use_dfe_sign_in` and `use_otp_sign_in` to decide which buttons and routes to expose. This is confusing for development as there is a 3rd sign in `persona` which is exposed dependent on the `use_dfe_sign_in` bool.
Use a new setting `sign_in_method` to determine which buttons and routes to expose.
make sure sign in works as expected using: `otp`, `dfe` and `persona`
> Add sign_in_method Setting

- app/services/trainees/map_state_from_hesa.rb
- spec/services/trainees/map_state_from_hesa_spec.rb
https://trello.com/c/llFG6p8g/5114-investigate-why-trainees-were-unawarded-on-register
`Trainees::MapStateFromHesa` had a bug whereby awarded trainees that got an update from HESA and the `reason_for_leaving` is empty would revert back to `trn_received` because the logic didn't check if the trainee was already awarded. The logic only returns `awarded` if `reason_for_leaving` meets certain values.
Essentially, we should never 'action' awards of QTS from HESA. We should only get that from DQT.
-  Update `Trainees::MapStateFromHesa` to check if trainee is already awarded
> [5114] Fix: Trainees::MapStateFromHesa should not override an awarded trainee

- app/services/hesa/validate_mapping.rb
- app/services/trainees/create_from_hesa.rb
- spec/services/trainees/create_from_hesa_spec.rb
When we create from hesa or use send a trn request we check the hesa codesets to ensure there is a valid mapping. There is a new service added to ensure this.
This spike: 
* applies to all fields where we take HESA data and that have mapping codes
* make sure alert is fired where we don't map to something.
This should be useful for cases where:
* HESA has added new values but we haven't
* We've intentionally not mapped something because we don't think it's relevant - but we get the value from HESA anyway.
New ValidateHesaMappings service which checks that the codesets work and there are no unmapped values
> [SPIKE] send alert when no hesa mapping

- app/controllers/guidance_controller.rb
- app/views/guidance/performance_profiles.html.erb
We were contacted by someone from a higher education institution which wanted to fix data for a trainee who is:
- listed in Register as training
- not in the current year's HESA initial teacher training collection
They cannot fix this themselves but the guidance page said that they could.
I've added text to clarify that they need to email us in the circumstances described.
> Clarify how HEIs should fix performance profile data

- app/lib/apply_api/code_sets/disabilities.rb
- app/services/trainees/create_from_apply.rb
- config/initializers/diversity_enums.rb
- spec/services/trainees/create_from_apply_spec.rb
- spec/support/api_stubs/apply_api.rb
We were using the disability_disclosed field from the apply api to assess whether a trainee had submitted a disability; this is incorrect. The disability_disclosed field was a free text field where a trainee could type the nature of their disability. The new logic is based on fields added to the apply api 'disabilities' fields ('no' and 'opt_out' values for not disabiled and prefer not to say respectively). This should ensure future incoming trainees are correct. 
Pull down some 2023 trainees from the apply api and run the create from apply service on them. There should be some with 'no' and 'opt_out' disability options.
> [4733] Fix apply disability mapping

- app/models/reports/trainee_report.rb
- app/models/reports/trainees_report.rb
- spec/models/reports/trainee_report_spec.rb
- spec/services/exports/export_trainees_service_spec.rb
- spec/services/exports/export_trainees_to_file_service_spec.rb
We've had a number of queries in to support about populating these columns that are blank, or else changing the data in them. The columns are optional and are only expected to be populated where a trainee is linked to a Publish course. This won't have happened for:
* HESA trainees
* Trainees added prior to Register launching
* Trainees with manual course details
We've done well at describing the columns or that they don't *need* to be populated. As a short term fix we're going to remove them from the export entirely.
We expect to revert this commit at some point in a few weeks time - potentially with some further design changes.
> Temporarily remove course columns that are causing confusion

- app/components/record_details/view.rb
- app/controllers/trainees/confirm_withdrawals_controller.rb
- app/forms/withdrawal_form.rb
- app/policies/trainee_policy.rb
- app/services/trainees/create_timeline_events.rb
- spec/features/trainee_actions/withdraw_trainee_spec.rb
- spec/forms/withdrawal_form_spec.rb
- spec/policies/trainee_policy_spec.rb
- spec/support/page_objects/trainees/record.rb
Trello: https://trello.com/c/Ux0SXTjs/5166-m-allow-for-withdrawal-dates-on-withdrawn-trainees-to-be-edited-by-system-admin-support
We want to make withdrawal details for trainees editable to system admins (but not provider users). If a trainee is withdrawn, add a change link that allows for withdrawal details to be edited. Add an event to the timeline if withdrawal date is edited.
If a trainee is already in a withdrawn state, don't run the withdrawal service. This means a job will not be kicked off to DQT.
* Update record view trainee status row
* Update `def withdraw?` in trainee policy to relax permissions if a trainee is already withdrawn
* Add logic to WithdrawalForm and ConfirmWithdrawalsController to prevent re-withdrawing the trainee and sending to DQT
* Add new timeline event for …
> [5166] Allow changes to withdrawal dates and reasons for system admins

- Gemfile
- Gemfile.lock
- app/services/degrees/dfe_reference.rb
- db/data/20230123100908_fix_unmapped_trainee_degree_subjects.rb
- spec/services/degrees/create_from_hesa_spec.rb
- spec/services/degrees/dfe_reference_spec.rb
https://trello.com/c/iW12D20B/5158-prod-trainees-showing-as-missing-degree-subject-but-it-was-present-in-hesa-update
- Update `dfe-reference` gem so we get support for "Not known" or "Not applicable" HESA degree subject codes
- Data migration to backfill missing subjects for those degrees that had a "Not known" or "Not applicable" subject
- Tested code locally. Works as expected.
- It will fix 183 degree records, not just the 4 mentioned in the card.
> [5158] Fix trainees showing as missing degree subject for unknown or not applicable HESA codes

- app/services/trainees/create_from_hesa.rb
- spec/services/trainees/create_from_hesa_spec.rb
We're getting a lot of DQT withdrawal jobs fail recently. The source of the problem is partly due to lots of unnecessary jobs been created when the trainee has already been withdrawn.
- Update `Trainees::CreateFromHesa` so it only creates a withdrawal job if the trainee is transititioning to `:withdrawn` from another state 
> [xxx] Fix: Trainees::CreateFromHesa creating unnecessary DQT withdrawal jobs

- app/services/dead_jobs/base.rb
- spec/support/shared_examples/dead_jobs.rb
fixes row drift from compacting dead jobs `.to_a`
> fix csv row drift in dead jobs CSV export

- app/forms/course_details_form.rb
- app/forms/itt_dates_form.rb
- app/helpers/dates_helper.rb
- app/views/trainees/course_details/edit.html.erb
- app/views/trainees/itt_dates/edit.html.erb
- spec/forms/course_details_form_spec.rb
Trello: https://trello.com/c/izTv1bao/5113-cannot-edit-itt-end-date-for-hesa-trainees-in-system-admin
We weren't showing the ITT end date boxes on the course details form for HESA trainees, so system admins could not edit the ITT end date. Allow them to edit this.
I have included HESA trainees in the end date validation but have slightly amended the rules to accept a nil `itt_end_date` for HESA trainees if one is not provided on the form - this is because for historic HESA trainees, it's possible that we don't have an end date. This would be a blocker to submitting the form if we amended something else on the course form for these older records.
Other validation for HESA trainees should work as expected (should only allow nil, or a valid date) and existing validation for other trainees …
> [5113] Allow system admin to edit ITT end date for HESA trainees

- db/data/20230127111000_fix_trainees_with_incorrect_submission_ready_value.rb
https://trello.com/c/VtgFbdjq/5157-prod-trainees-showing-as-incomplete-but-with-no-banner-saying-whats-missing
There is a small number (127 approximately) of trainees that for some unknown reason ended with the wrong value for `Trainee#submission_ready` (should be `true` instead of `false`). This data migration will correct those values and we will revisit the database in the future to see if this type of problem resurfaces. If it does, hopefully the audit trail will gives us more insight on what's going on.
- Data migration to re-run `Trainee#set_submission_ready` on a selected number of trainees
Tested it locally. Works as expected.
> [5157] Data migration to fix Trainee#submission_ready values

- app/jobs/sidekiq/remove_dead_duplicates_job.rb
- app/services/sidekiq/remove_dead_duplicates.rb
- config/sidekiq_cron_schedule.yml
- spec/jobs/sidekiq/remove_dead_duplicates_job_spec.rb
- spec/services/sidekiq/remove_dead_duplicates_spec.rb
https://trello.com/c/JPPG3NUI/5193-dead-job-set-cron-tasks
The sidekiq dead queue is frequently polluted by duplicated jobs which makes the support role more tedious when trying to fix and clear those jobs.
- New service `Sidekiq::RemoveDeadDuplicates` to scan for duplicate dead jobs and remove them
- Background job to run the service every minute
> [5193] Check and remove duplicate jobs in Sidekiq deadset every minute

- app/jobs/sidekiq/remove_dead_duplicates_job.rb
- spec/jobs/sidekiq/remove_dead_duplicates_job_spec.rb
This is causing an error per minute in QA.
Only run dead de-duping job in prod.
> [xxx] Only run RemoveDeadDuplicatesJob in prod

- app/controllers/system_admin/dead_jobs_controller.rb
- app/services/dead_jobs/base.rb
- app/services/dead_jobs/dqt_update_trainee.rb
- app/views/system_admin/dead_jobs/index.html.erb
- config/environments/development.rb
- docs/testing_data_migrations.md
- spec/services/dead_jobs/dqt_recommend_for_award_spec.rb
- spec/services/dead_jobs/dqt_update_trainee_spec.rb
- spec/services/dead_jobs/dqt_withdraw_trainee_spec.rb
- spec/support/shared_examples/dead_jobs.rb
The dead jobs CSV export lacks a few useful attributes and context
* adds job_id, params_sent (UpdateTrainee only) and trainee state to the CSV export
* adds DQT status and option to retrieve it (with warning) to the CSV export
* names CSV file with current date
* only testable in production, unless overriding the `def initialize(dead_set = Sidekiq::DeadSet.new)` in `app/services/dead_jobs/base.rb`
* check specs and make sure new fields are useful/needed and raise any more that could go in.
> [5195] - add job_id, params_sent, state, dqt_status

- app/jobs/dqt/withdraw_trainee_job.rb
- spec/jobs/dqt/withdraw_trainee_job_spec.rb
We're getting a lot of dead withdraw jobs because the trainee is already withdrawn in DQT. Not sure how the trainee got to be withdrawn before Register knew about it, but for now, this workaround will reduce the workload on support.
The trade-off is the withdraw job may end up doing 2 API calls to DQT which may impact the 3000/per minute rate limit during busy periods.
- Add DQT check to `Dqt::WithdrawTraineeJob`
> [xxx] Cancel withdraw job if trainee is already withdrawn in DQT

- app/components/dqt_data_summary/view.html.erb
- app/components/dqt_data_summary/view.rb
- app/components/hesa_student_summary/view.html.erb
- app/controllers/trainees/admins_controller.rb
- app/views/trainees/admins/show.html.erb
- spec/components/dqt_data_summary/view_preview.rb
- spec/components/dqt_data_summary/view_spec.rb
https://trello.com/c/8clT8XTR/5211-show-the-output-from-the-dqt-api-for-a-trainee
- Create new DqtDataSummary component, a table which displays
the response of the DQT get teacher API
- Call the get teacher API endpoint from the trainee admin controller
rescuing any exceptions
- Render the data summary on the trainee show page
You can't view this in dev / review / QA etc, but you can view the component with mock data here: 
https://register-pr-3084.london.cloudapps.digital/view_components/dqt_data_summary/view/default
Head to a registered trainee show page, admin tab to see where it would render, and how the 'no data' scenario is handled.
> [5211] Show the output from the DQT API for a trainee

- app/services/trainees/map_state_from_hesa.rb
- docs/support_playbook.md
- spec/services/trainees/map_state_from_hesa_spec.rb
HESA sometimes send us TRNs. These can't be trusted, so don't include them in our decision to set the trainee's state/register for TRN on our end. 
* Remove `hesa_trainee[:trn]` from our `MapStateFromHesa` service
> [xxx] Do not use HESA TRN to set state

- app/services/dead_jobs/base.rb
- app/services/dead_jobs/dqt_update_trainee.rb
- spec/services/dead_jobs/dqt_update_trainee_spec.rb
- spec/support/shared_examples/dead_jobs.rb
DQT have asked for more information on the programme details.
- Add `programme_route`, `programme_start_date` and `programme_end_date` to `DeadJobs::Base`
- Code was tested manually in production to produce CSV for DQT
> [xxx] Add programme details to dead job CSV export

- app/services/degrees/dfe_reference.rb
https://trello.com/c/LZzx9IJW/5223-new-degree-form-is-missing-many-degree-grades
The reference data gem zero padded the hesa codes, but we didn't update our lookup code to reflect this:
https://github.com/DFE-Digital/dfe-reference-data/commit/9a3f42d8723e9c44619b006eb04cae7a2553a7cc
Zero pad the hesa code on the lookup for the form options.
Go to add a new degree and see that the full list of grades is there.
> [5223] Zero pad the hesa codes on lookup

- app/components/dqt_data_summary/view.html.erb
- app/components/dqt_data_summary/view.rb
- spec/components/dqt_data_summary/view_spec.rb
Fix the DQT API view for trainees who are missing ITT / QTS info etc
Render "No data" when whole sections are nil.
Hard to view on review app, but this is what it looks like when initial_teacher_training, induction, qualified_teacher_status and qualifications are all empty:
> [xxx] Fix DQT admin view when there's missing data

- app/services/dead_jobs/base.rb
- app/views/system_admin/dead_jobs/index.html.erb
- app/views/system_admin/dead_jobs/show.html.erb
- spec/features/system_admin/dead_jobs/viewing_dead_jobs_spec.rb
- spec/support/features/page_helpers.rb
- spec/support/page_objects/system_admin/dead_jobs/dead_background_jobs_summary.rb
- spec/support/page_objects/system_admin/dead_jobs/dead_jobs_dqt_update_trainee.rb
Link to trainees from the show page of dead job viewer.
Add a button to link to the trainee from the dead job viewer.
> [5194] Link to trainees from dead job viewer

- app/jobs/dqt/sync_teacher_job.rb
- app/jobs/dqt/sync_teachers_batch_job.rb
- app/jobs/dqt/sync_teachers_job.rb
- app/jobs/dqt/withdraw_trainee_job.rb
- app/models/dqt/teacher.rb
- app/models/dqt/teacher_training.rb
- app/models/trainee.rb
- app/services/dead_jobs/base.rb
- app/services/dqt/retrieve_training.rb
- app/services/dqt/sync_state.rb
- app/services/dqt/sync_teacher.rb
- config/analytics_blocklist.yml
- config/settings.yml
- config/settings/production.yml
- db/migrate/20230216153013_create_dqt_teachers.rb
- db/migrate/20230216154509_create_dqt_teacher_trainings.rb
- db/schema.rb
- spec/jobs/dqt/sync_teacher_job_spec.rb
- spec/jobs/dqt/sync_teachers_batch_job_spec.rb
- spec/jobs/dqt/sync_teachers_job_spec.rb
- spec/jobs/dqt/withdraw_trainee_job_spec.rb
- spec/models/trainee_spec.rb
- spec/services/dqt/retrieve_training_spec.rb
- spec/support/shared_examples/dead_jobs.rb
https://trello.com/c/tM1y9DnR/5248-l-create-way-to-check-how-and-if-trainees-in-register-are-synced-to-dqt
- New models: `Dqt::Teacher` and `Dqt::TeacherTraining` (`has_many` association)
- New `Trainee` associations:
- `Trainee#dqt_teacher`
- `Trainee#dqt_teacher_trainings`
- Background jobs to pull data down from DQT
- Tested it locally. Works as expected.
> [5248] New models and jobs to pull down data from DQT

- app/controllers/system_admin/dead_jobs_controller.rb
- app/services/dead_jobs/base.rb
- app/views/system_admin/dead_jobs/show.html.erb
Add pagination to dead job view. 
Dead job view now paginates (30 items per page). Please note that testing this in browser is quite annoying. Happy to demonstrate. Unsure of how best to test this feature; I couldnt find any other tests for pagination. It should be covered by the base pagination tests.
Spoof the dead jobs set in dead jobs base.rb. Happy to demonstrate. 
> [5213] Paginate dead job view

- app/models/dqt/teacher.rb
- app/models/dqt/teacher_training.rb
- app/services/dqt/sync_teacher.rb
- config/analytics_blocklist.yml
- db/migrate/20230228134944_add_hesa_id_to_dqt_teachers.rb
- db/migrate/20230228135922_add_hesa_id_to_dqt_teacher_trainings.rb
- db/schema.rb
https://trello.com/c/ekLTYXl2/5295-add-hesaid-to-our-dqt-tables-and-re-run-the-sync
- Update DQT tables and sync job to capture `hesa_id`
> [5295] Add HESA ID to DQT tables

- app/views/request_an_account/index.html.erb
- config/locales/en.yml
The content of the 'request account' page said that people should contact us to request their own account. But if their organisation already uses Register then they should ask a colleague with an account to contact us. This is now the most common situation.
I've made the content accurate and also taken the opportunity to also make minor content improvements throughout.
In addition, this page was referring to content in /config/locales/en.yml. That made it difficult to update and was unnecessary since we do not have other language versions. I've replaced these references with html. In future we may change the page so that it uses markdown.
I removed the content about the request page from /config/locales/en.yml to tidy up the code.
> Updated 'request account' page

- app/models/dqt/teacher_training.rb
- app/services/dqt/retrieve_teacher.rb
- app/services/dqt/retrieve_training.rb
- app/services/dqt/sync_teacher.rb
- config/analytics_blocklist.yml
- db/migrate/20230302155425_add_active_column_to_dqt_teacher_trainings.rb
- db/schema.rb
- spec/services/dqt/retrieve_training_spec.rb
https://trello.com/c/VDMGU0fw/5302-download-inactive-dqt-training-records
- Update `Dqt::RetrieveTeacher` to include inactive training records
- Update `Dqt::SyncTeacher` to capture the `active` field in `initialTeacherTraining`
- Migration to add `active` column to `dqt_teacher_trainings` table
Tested locally. Works as expected.
> [5295] Include DQT inactive training records during sync

- app/controllers/bulk_update/recommendations_controller.rb
- app/controllers/bulk_update/recommendations_uploads_controller.rb
- app/models/bulk_update/recommendations_upload.rb
- app/models/bulk_update/recommendations_upload_row.rb
- app/services/bulk_update/recommend.rb
- app/services/bulk_update/recommendations_uploads/create_recommendations_upload_rows.rb
- app/views/bulk_update/recommendations_uploads/check.html.erb
- app/views/bulk_update/recommendations_uploads/confirmation.html.erb
- app/views/bulk_update/recommendations_uploads/show.html.erb
- config/routes.rb
- spec/factories/bulk_update/recommendations_upload_row.rb
- spec/features/bulk_upload/recommending_trainees_spec.rb
- spec/models/bulk_update/recommendations_upload_row_spec.rb
- spec/services/bulk_update/recommend_spec.rb
https://trello.com/c/skZsrbIS/5273-bulk-qts-service-to-send-the-recommendations-to-dqt
- Add new BulkUpdate::RecommendationsController responsible for recommending the trainees in bulk
- Add new BulkUpdate::Recommend service that recommends all trainees given a recommendations_uplpad
- Add a new confirmation page
With more trainees to recommend:
With no more trainees to recommend:
> [5273] Bulk recommend trainees

- app/lib/dqt/params/trn_request.rb
- spec/lib/dqt/params/trn_request_spec.rb
https://trello.com/c/u3EeymlA/5286-s-send-iqts-trainees-when-registered-to-dqt
- Map iQTS training route to DQT programme type `InternationalQualifiedTeacherStatus`
> [5286] Add support for DQT programme type InternationalQualifiedTeacherStatus

- app/lib/dqt/params/trn_request.rb
- config/settings/production.yml
- config/settings/productiondata.yml
- spec/lib/dqt/params/trainee_request_spec.rb
- spec/lib/dqt/params/trn_request_spec.rb
https://trello.com/c/CZa1lZ29/5098-l-test-and-turn-on-iqts-registration
- Send `trainingCountryCode` to DQT for iQTS training routes
- Turn on feature flag for `production` and `productiondata` environments
- Testing was done to see if DQT would create a TRN using new iQTS training route. I didn't at first because the `trainingCountryCode` was missing. Worked after it was added.
> [5098] Turn on iQTS registration

- app/controllers/trainees/confirm_deferrals_controller.rb
- app/forms/deferral_form.rb
- app/jobs/dqt/withdraw_trainee_job.rb
- app/lib/dqt/params/update.rb
- app/services/dead_jobs/dqt_update_trainee.rb
- app/services/dqt/trainee_update.rb
- spec/controllers/trainees/confirm_deferrals_controller_spec.rb
- spec/forms/deferral_form_spec.rb
- spec/jobs/dqt/withdraw_trainee_job_spec.rb
- spec/lib/dqt/params/update_spec.rb
- spec/services/dead_jobs/dqt_update_trainee_spec.rb
- spec/services/dqt/update_spec.rb
https://trello.com/c/09POs7RQ/5296-s-add-outcome-to-the-dqt-trainee-update-endpoint
- Rename `Dqt::Params::TraineeRequest` to `Dqt::Params::Update` (TraineeRequest doesn't really convey any meaning)
- Add `outcome` param to `Dqt::Params::Update` based on conditional logic
- Remove the check on withdrawing already withdrawn trainees in DQT
- Worked with @MrKevJoy to test that we can go between `Deferred` => `InTraining` or `UnderAssessment` and vice versa
- Also confirm that withdrawing a trainee more than once doesn't cause any errors
> [5296] Add `outcome` to the DQT trainee update endpoint

- app/services/trainees/create_from_hesa.rb
- spec/services/trainees/create_from_hesa_spec.rb
An awarded trainee has been updated for some of their fields after an award. This should not be possible.
Add a guard clause to not allow trainees to be updated from hesa once they are awarded.
> [5261] Prevent update to trainee after award

- app/controllers/bulk_update/recommendations_checks_controller.rb
- app/models/bulk_update/recommendations_upload_row.rb
- app/views/bulk_update/recommendations_checks/_table.html.erb
- app/views/bulk_update/recommendations_checks/show.html.erb
- app/webpacker/packs/application.js
- app/webpacker/scripts/global/stick_to_window_when_scrolling.js
- app/webpacker/styles/application.scss
- app/webpacker/styles/stick_to_window_when_scrolling.scss
- app/webpacker/styles/tables.scss
- spec/features/bulk_upload/recommending_trainees_spec.rb
https://trello.com/c/QTZ0f0VF/5287-m-bulk-recommend-accordion-page
- Accordian logic that breaks the number of rows into chucks of 50 if there's more that 50 rows to display
- New Javascript and CSS that allows the recommend button to remain visible at the bottom during scrolling
- Visit `/bulk-update/recommend/upload`
- Upload CSV
- Click button "Check who you’ll recommend"
- If number of trainees is less than 50, then no accordian breakdown is shown
> [5287] Bulk recommend - accordion page

- app/controllers/application_controller.rb
- app/policies/trainee_policy.rb
- app/views/layouts/trainee_record.html.erb
- app/views/trainees/show.html.erb
- config/locales/en.yml
- spec/policies/trainee_policy_spec.rb
- spec/views/trainees/show.html.erb_spec.rb
https://trello.com/c/nPzWmher/5326-m-allow-hesa-trainees-to-be-deferred-reinstated-awarded-or-withdrawn-in-register
- Update trainee policy so the actions bar is avalable to HESA trainees
- Change the HESA inset text to reflect the actions that can now be taken 
- Log in as a provider
- Find an in-training HESA trainee
- Should see inset text and actions bar
> [5326] Allow hesa trainees to be deferred reinstated awarded or withdrawn in register

- app/controllers/bulk_update/recommendations_errors_controller.rb
- app/views/bulk_update/recommendations_errors/show.html.erb
- config/routes.rb
- spec/features/bulk_upload/recommending_trainees_spec.rb
- spec/support/page_objects/bulk_update/recommendations_checks/show.rb
https://trello.com/c/biSsSqUH/5334-bulk-recommend-fix-errors-renders-incorrect-page-if-user-gets-an-error-uploading
- Update `BulkUpdate::RecommendationsErrorsController` to handle file uploads separate to `BulkUpdate::RecommendationsUploadsController` 
- Log in as a provider
- Visit "Bulk recommend"
- Download CSV
- Edit CSV and fill the column "Date QTS or EYTS standards met" with at least one cell containing an incorrect future date e.g. 7000-03-01
- Upload CSV
- View errors
- Click the upload button without attaching a file
- Form errors should appear on the current page
> [5334] Bulk recommend fix errors renders incorrect page if user gets an error uploading

- .github/workflows/deploy.yml
- Makefile
- config/environments/pen.rb
- config/settings/pen.yml
- terraform/workspace-variables/app_config.yml
- terraform/workspace-variables/pen.tfvars.json
- terraform/workspace-variables/pen_backend.tfvars
A dedicated environment is required to support pen testing.
- Add the environment to the deploy workflow inputs
- Add the config to the `Makefile`
- Add Ruby config
- Add Terraform app config
- Add Terraform variable and backend files
https://github.com/DFE-Digital/bat-infrastructure/pull/124
Confirm the environment is available on https://pen.register-trainee-teachers.service.gov.uk and https://pen.register-trainee-teachers.education.gov.uk redirects to the service domain.
> Add pen environment configuration

- app/services/trainees/create_from_hesa.rb
The guard clause in the previous PR was placed in the wrong place. This would allow trainees to still be saved, meaning they would have updates made to their hesa metadata and degrees. 
See comments on last PR: 
https://github.com/DFE-Digital/register-trainee-teachers/pull/3135/files#r1144620348
Putting the guard clause right at the front will prevent this from happening.
> [5261] Prevent hesa metadata and degrees being updated

- app/models/reports/bulk_recommend_report.rb
- app/services/bulk_update/recommendations_uploads/create_csv_with_errors.rb
- app/services/bulk_update/recommendations_uploads/create_recommendations_upload_rows.rb
- spec/fixtures/files/bulk_update/recommendations_upload/missing_do_not_edit_row.csv
- spec/services/bulk_update/recommendations_uploads/create_recommendations_upload_rows_spec.rb
https://trello.com/c/3w7vmdwc/5346-m-bulk-recommend-support-users-removing-the-do-not-edit-row
- Update `CreateRecommendationsUploadRows` service to detect whether a row contains
"Do not edit" and skip creating row if it does.
- Update `CreateCsvWithErrors` services to detect whether a row contains "Do not edit" and
add correct string if it does.
Before, both of these services skipped the first row assuming it was the "Do not edit" row.
- Upload a file with the "Do not edit" row missing and an error in one of your trainees
- Check that the summary counts look correct
- Click to 'Fix errors'
- Check that the download does not contain the "Do not edit" row and that the error is against the correct trainee
Now do the same checks but move the "Do not edit" row to somewhere in the middle (as …
> [5346] Bulk recommend - Support users removing (or moving) "Do not edit" row

- app/views/bulk_update/recommendations_checks/show.html.erb
- app/views/bulk_update/recommendations_errors/show.html.erb
- app/views/bulk_update/recommendations_uploads/edit.html.erb
- app/views/bulk_update/recommendations_uploads/new.html.erb
- app/views/bulk_update/recommendations_uploads/show.html.erb
- config/routes.rb
- spec/support/page_objects/bulk_update/recommendations_checks/show.rb
- spec/support/page_objects/bulk_update/recommendations_errors/show.rb
- spec/support/page_objects/bulk_update/recommendations_uploads/cancel.rb
- spec/support/page_objects/bulk_update/recommendations_uploads/edit.rb
- spec/support/page_objects/bulk_update/recommendations_uploads/new.rb
https://trello.com/c/EoyMqGYK/5359-update-bulk-recommendation-urls-h1-heading-and-captions
- Update all captions to say "Bulk recommend"
- Update URLs as per spreadsheet on Trello
- Update start page h1 to "Choose who to recommend for QTS or EYTS"
- Check URLs are all correct
- Check all captions have been changed
> [5359] Update bulk recommendation URLs, h1 and captions

- app/models/bulk_update/recommendations_upload_row.rb
- app/services/bulk_update/recommendations_uploads/validate_csv.rb
- config/locales/en.yml
- spec/services/bulk_update/recommendations_uploads/validate_csv_spec.rb
https://trello.com/c/z08URxkV/5348-s-show-error-when-there-are-0-trainees-in-the-csv-file-when-bulk-recommending-for-qts-or-eyts
- Add validation and error message for when there are the expected header / headers but no trainees
- Fix for row methods (there's not always a `matched_trainee`)
- Upload a file with just the header row and check the error
- Upload a file with just the header row and the "Do not edit" row and check the error
- Check for regressions in other scenarios
> [5348] Bulk recommend - add error for no trainees in file

- app/views/bulk_update/recommendations_uploads/_no_trainees.html.erb
- app/views/bulk_update/recommendations_uploads/_upload_trainees.html.erb
- app/views/guidance/bulk_recommend_trainees.md
- app/views/guidance/show.html.erb
- app/views/layouts/guidance.html.erb
https://trello.com/c/97zFVf4g/5379-add-links-to-bulk-qts-eyts-guidance-page-and-make-sure-it-is-linked-to-in-the-correct-pages
- Add link to guidance from guidance index
- Update link within guidance to the start of the bulk recommend journey
- Add link to guidance from upload page (with and without trainees)
Extra:
- Removes the green upload button from the 'You have no trainees to recommend' page whilst i was there
Check everything is linked correctly.
> [5379] Update links to/from bulk recommend guidance

- app/views/bulk_update/recommendations_errors/show.html.erb
- app/views/bulk_update/recommendations_uploads/_no_trainees.html.erb
- app/views/bulk_update/recommendations_uploads/_upload_trainees.html.erb
- app/views/bulk_update/recommendations_uploads/new.html.erb
https://trello.com/c/nW2ZTgzw/5381-make-changes-to-the-download-csv-page-the-first-page-in-bulk-recommendation
- Remove extra 'for' on upload page with no trainees
- Move full stop outside link on upload page with trainees
- Ensure page titles get "Error" prepended when upload page (and review errors page) has an error
Check content tweaks as above.
No extra "for" on no trainees page:
Page title in error:
> [5381] Tweaks to bulk recommend upload page

- app/helpers/recommendations_upload_helper.rb
- app/views/bulk_update/recommendations_checks/_table.html.erb
- app/views/bulk_update/recommendations_checks/show.html.erb
https://trello.com/c/dbm4aTUr/5382-make-changes-to-the-accordion-page-in-bulk-recommendation-for-qts
- Improve text on section heading if there's only one trainee in section:
- It should say "Trainee 6" rather than "Trainees 6 to 6" for example
- Include HESA ID in table if the trainee has one
- Upload a CSV with 6 trainees to recommend, one being HESA
- Check that on the "check who you'll recommend" page the HESA ID shows for the trainee that has one
- Check that the last section title is correct
> [5382] Bulk recommend - improvements to the accordion page

- app/views/guidance/bulk_recommend_trainees.md
It’s only possible to bulk recommend trainees who met the standards within the past 12 months. We need to mention this in the guidance.
[Trello card](https://trello.com/c/5UClq1sD/5376-mention-in-guidance-that-its-only-possible-to-bulk-recommend-trainees-who-met-the-standards-within-the-past-12-months)
I've added a paragraph to the bulk recommendation guidance.
None.
- [no] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [no] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?
- [no] Do we need to send any updates to DQT as part of the work in this PR?
- [no] Does this PR need an ADR?
NB: Please notify the #twd_data_insights …
> Change guidance to mention 12 month deadline to bulk recommend

- app/models/hesa/student.rb
- db/migrate/20230413130025_remove_itt_start_date_and_trainee_start_date_from_hesa_students.rb
- db/schema.rb
itt_start_date and trainee_start_date used to be keys in the Hesa::IttParser and thus have corresponding fields in the hesa_students table.
We renamed these commencement_date and itt_commncement_date to more closely align with what hesa name them. We also added new fields in hesa_students to save them.
However, we didn’t remove the old columns.
Remove itt_start_date and trainee_start_date from hesa_students.
Note: The trello card mentions "We should also check that this then fixes the HESA admin page for trainees.". I am unsure what was supposed to be broken on the page? Locally when i view students imported from hesa as an admin it seems to be working well. 
> [5392] Remove trainee and itt start dates from hesa students

- app/services/trainees/create_from_hesa.rb
- spec/services/trainees/create_from_hesa_spec.rb
We were erroring when a TRN from HESA doesn't match what we have, but we don't actually do anything when this happens so it's just noise.
Remove the error.
Also remove TRN regex that wasn't used anymore.
🚢 
> [xxx] Remove error when TRN doesn't match from HESA

- app/views/layouts/trainee_record.html.erb
- app/views/trainees/withdrawals/show.html.erb
- config/locales/en.yml
- spec/features/trainee_actions/defer_trainee_spec.rb
- spec/features/trainee_actions/reinstating_a_trainee_spec.rb
- spec/features/trainee_actions/withdraw_trainee_spec.rb
https://trello.com/c/8D6UROhZ/5371-s-update-withdrawal-date-question
- Legend updated to Date the trainee withdrew
- Hint text added
- 3rd radio option updated to say  "Another date"
- Removed unused translation key not related to these card
- Choose an in-training trainee
- Click withdraw
- Text should reflect the changes made
> [5371] Update withdrawal date question

- db/data/20230420144916_backfill_missing_trainee_nationalities.rb
https://trello.com/c/a7f7uoGB/5181-hesa-trainee-shows-missing-nationality-but-it-seems-to-be-in-hesastudents-table
- Data migration to finds those trainees that have a missing nationality and uses their HESA students records to backfill the missing data assuming the nationality information is available
- Ran locally - fixed trainee mentioned in the card and also fixed 1118 other trainees that have the same issue
- Takes about 20 seconds to run
> [5181] Backfill missing trainee nationalities

- app/services/bulk_update/recommend.rb
- spec/services/bulk_update/recommend_spec.rb
https://trello.com/c/GXQbFvD3/5414-s-fix-the-to-dos-when-recommending-find-the-matched-trainee-instead-of-finding-just-on-trn
- When bulk recommending trainees, use the rows matched trainee now we have
that association
- Update the test and add a new test for when the trainee is already awarded
(maybe by another user in another tab)
> [5414] Fix TODO - recommend matched trainees

- app/components/deferral_details/view.html.erb
- app/components/deferral_details/view.rb
- app/components/outcome_details/view.html.erb
- app/components/outcome_details/view.rb
- app/components/record_details/view.rb
- app/components/summary_card/view.html.erb
- app/components/summary_card/view.rb
- app/components/withdrawal_details/view.html.erb
- app/components/withdrawal_details/view.rb
- app/views/trainees/show.html.erb
- lib/tasks/example_data.rake
- spec/components/record_details/view_spec.rb
- spec/features/trainee_actions/withdraw_trainee_spec.rb
- spec/support/page_objects/trainees/record.rb
- spec/views/trainees/show.html.erb_spec.rb
Add details components for awarded, withdrawn and deferred trainees to the trainee record page. 
Should be a new details component on the trainee show page for awarded, deferred and withdrawn trainees/
Good candidate to check in the browser.
> [5352] Surface details for awarded, deferred and withdrawn trainees

- terraform/custom_domains/environment_domains/workspace_variables/register_audit.tfvars.json
- terraform/custom_domains/environment_domains/workspace_variables/register_pen.tfvars.json
- terraform/custom_domains/environment_domains/workspace_variables/register_production.tfvars.json
- terraform/custom_domains/environment_domains/workspace_variables/register_qa.tfvars.json
- terraform/custom_domains/environment_domains/workspace_variables/register_staging.tfvars.json
Change to the default TTL to 60 for all register CNAMES
TTL Changed to 60
- Azure portal dns zone CNAME records to display TTL value of 60
> Change the TTL to 60 for Register EDU and SVC CNAME Records

- app/models/reports/bulk_recommend_report.rb
- app/services/bulk_update/recommendations_uploads/row.rb
- spec/services/exports/bulk_recommend_export_spec.rb
https://trello.com/c/G1JsHEus/5412-s-handle-17-digit-hesaids-in-the-bulk-recommendation-csvs
- Prefix HESA IDs with a single quote character to to prevent Excel from displaying it in scientific notation
- Modify CSV importer to ignore single quote character 
- Log in as a provider
- Go through the bulk recommendation process and open CSV files in Excel to confirm that HESA IDs are no longer show in scientific notation
> [5412] Prevent Excel from using scientific notation when displaying HESA IDs

- app/views/guidance/bulk_recommend_trainees.md
There was an error in the first section of the guidance. 
The word "deferred" should have been "withdrawn".
> Fix error in bulk recommend guidance

- app/services/trainees/create_timeline_events.rb
https://dfe-teacher-services.sentry.io/issues/4147798659/events/37c2ea14daac427a8be47ddd372a53cf/?project=5552118
only use the `withdrawal_undone?` timeline event block for un-withdraws that have a user associated (and thus a comment)
> [4147798659] - only show undo-withdraw timeline events for non-HESA audits

- app/models/reports/bulk_recommend_report.rb
- app/views/bulk_update/recommendations_checks/_table.html.erb
- config/analytics_blocklist.yml
- spec/features/bulk_upload/recommending_trainees_spec.rb
On the rest of the Register service, we generally put first name before surname. We want bulk recommendation to match this.
Swap order of last name and first name in the csv and accordion page.
> [5418] Swap order of first and last name on csv

- app/components/award_details/view.html.erb
- app/components/award_details/view.rb
- app/views/trainees/show.html.erb
- spec/components/award_details/view_spec.rb
https://trello.com/c/dXYprQwW/5442-date-qts-award-is-met-is-not-showing-on-some-awarded-trainees
- Display award date instead of outcome date
> [5442] Date QTS award is met is not showing on some awarded trainees

- app/services/degrees/create_from_hesa.rb
- app/services/degrees/dfe_reference.rb
- db/data/20230504111909_backfill_missing_hesa_degree_types.rb
- spec/services/degrees/create_from_hesa_spec.rb
We show trainees as 'incomplete' when they have DEGTYPE for '999' from HESA. This is a valid entry in HESA for 'Unknown'
We want to  map '999' to 'Not available' for Degree type, and not show the record as incomplete on our platform.
- Extracts the DEGTYPE mapping from `dfe-reference-data` gem (and sort out the upgrade of the gem at a later date due to complications with lots of specs failing).
- Contains the data migration file that does the backfill.
TICKET: https://trello.com/c/lNjocxMF
The migration was executed locally. No issues found. 352 trainees affected.
- Get a copy of the prod data locally
- Run the migration
- Check the affected trainees
> 5405 - Map DEGTYPE 999 to 'Not Available'

- app/forms/bulk_update/recommendations_upload_form.rb
- app/services/bulk_update/recommendations_uploads/config.rb
- app/services/bulk_update/recommendations_uploads/create_csv_with_errors.rb
- app/services/bulk_update/recommendations_uploads/create_recommendations_upload_rows.rb
- app/services/bulk_update/recommendations_uploads/row.rb
- app/services/bulk_update/recommendations_uploads/validate_csv_row.rb
- app/services/bulk_update/recommendations_uploads/validate_trainee.rb
- spec/services/bulk_update/recommendations_uploads/validate_csv_spec.rb
https://trello.com/c/DyVuDA2z/5453-bug-ticket
* moves some constants and regex's into a BulkRecommend config file
* compares sanitised HESA_IDs from a CSV to a trainee's hesa_id
* try uploading a bulk update csv with several recommended trainees that have a mix of unquoted and quoted hesa_ids (both at the start and the end of the hesa_id string)
> [5453] - Allow quoted and unquoted HESA_IDs on upload

- app/controllers/guidance_controller.rb
- app/views/guidance/performance_profiles_outside.html.erb
- app/views/guidance/show.html.erb
- app/views/reports/_inside.html.erb
- app/views/reports/_outside.html.erb
- app/views/reports/index.html.erb
- config/settings.yml
- spec/features/reports/viewing_performance_profiles_spec.rb
- spec/support/page_objects/reports/index.rb
Some of the guidance and reports content only makes sense inside the census or performance profiles sign off periods. For example, the performance profiles guidance mentions a deadline which is now in the past.
* defines new copy in views
* adds `Setting` for `in_sign_off_period?` set to `false` for now
> [5434] - new guidance for outside sign-off period

- config/initializers/redis.rb
- config/initializers/sidekiq.rb
- docker-compose.yml
- terraform/aks/databases.tf
- terraform/modules/kubernetes/variables.tf
The current app configuration looks for an environment var called REDIS_URL or gets the redis url from VCAP services for the redis cache instance and only uses VCAP services to get the redis url for the redis queue instance.
This needs to be updated to use the AKS redis instances so app can point to these instances when migrated to aks from paas
App code has been updated to point to environment variables for the redis cache and redis queue instances for aks migration.
Deploy in PAAS and aks to verify all is working as expeceted.
> Change app config to use AKS Redis instances without disrupting paas app

- app/forms/personal_details_form.rb
- config/locales/en.yml
- spec/forms/personal_details_form_spec.rb
When adding a new trainee manually / editing dates of birth, we should require that the trainee be at least 16 years old.
We've had a handful trainees added with 2022 as a year of birth - this is clearly wrong, but as the date is in the past, Register accepted it. We should prevent this with sensible validation.
16 Chosen as the likely youngest age an undergrad person might start
Add to the date validator a check for over 16 years old.
Try to add a new manual record under 16 years old. 
> [5372] Add over 16 validation to dob

- app/controllers/bulk_update/recommendations_base_controller.rb
- app/models/bulk_update/recommendations_upload.rb
- app/models/bulk_update/recommendations_upload_row.rb
- app/services/bulk_update/recommendations_uploads/row.rb
- app/services/bulk_update/recommendations_uploads/validate_csv_row.rb
- app/services/bulk_update/recommendations_uploads/validate_trainee.rb
- spec/services/bulk_update/recommendations_uploads/validate_csv_row_spec.rb
- spec/services/bulk_update/recommendations_uploads/validate_trainee_spec.rb
Submitting a CSV with a blank row leads to the error message ”  must match a trainee record”.
However the csv file should instead be accepted.
Add a guard method to ensure that a blank row csv is accepted.
Try to submit a blank row csv.
> [5454] Allow upload of csv with blank rows

- app/models/reports/trainee_report.rb
- spec/models/reports/trainee_report_spec.rb
In bulk recommendations testing, we found that age range was showing incorrectly for some early years trainees. We need to fix this.
As eyts trainees dont have age ranges we show a blank value in the export.
> 5422 return blank age range for eyts trainees

- app/views/guidance/bulk_recommend_trainees.md
- app/views/guidance/show.html.erb
- app/views/guidance/withdraw_defer_reinstate_or_recommend_a_trainee.md
- config/routes.rb
We’re turning off the ITT provider portal, so the process for submitting outcomes for trainees is changing. We are updating our guidance pages to reflect this.
- Add new guidance page called “Withdraw, defer, reinstate or recommend a trainee for QTS or EYTS” with the URL guidance/withdraw-defer-reinstate-recommend-a-trainee.
- Make changes to the “Bulk recommend trainees for QTS or EYTS” page.
- Make changes to the guidance index page.
New page can be seen at `/guidance/withdraw-defer-reinstate-or-recommend-a-trainee`
Copy update at: `/guidance`
Copy update at: `/guidance/bulk-recommend-trainees`
Ticket: https://trello.com/c/m3biawzK
> [5482] Copy changes

- .gitignore
- .tool-versions
- Makefile
- docs/aks_modules.md
- terraform/aks/.terraform.lock.hcl
- terraform/aks/application.tf
- terraform/aks/cluster_data.tf
- terraform/aks/databases.tf
- terraform/aks/workspace-variables/dv_review_aks_Terrafile
- terraform/aks/workspace-variables/production_aks_Terrafile
- terraform/aks/workspace-variables/productiondata_aks_Terrafile
- terraform/aks/workspace-variables/qa_aks_Terrafile
- terraform/aks/workspace-variables/review_aks_Terrafile
- terraform/aks/workspace-variables/staging_aks_Terrafile
We want to be able to use different module versions depending on the environment. Unfortunately the reference cannot be a variable as terraform fails with `variable not allowed here`.
Use [terrafile](https://github.com/coretech/terrafile) to manage versions and use main/testing/stable depending on the environment
Run deploy-plan with the review app
> [338] Manage terraform modules via terrafile

- app/components/placement_details/view.rb
- app/models/hesa/student.rb
- app/models/reports/trainee_report.rb
- app/models/trainee.rb
- spec/components/placement_details/view_spec.rb
- spec/models/reports/trainee_report_spec.rb
- spec/models/trainee_spec.rb
Get placements for latest hesa collection per trainee
Get placements for latest hesa collection per trainee instead of using the hesa collection reference from the `Settings.yml` file.
Pick an awarded trainee that finished last year.
`/trainees/fiCo6GaXLPNEcJGwfQNANrSK`
> [5489] Get placements for latest hesa collection per trainee

- .gitignore
- db/data/20230518115341_update_institution_on_degrees_with_wrong_mapping.rb
Update the institution name for given degrees
We noticed that the given degrees have the wrong institution name.
There seems to be only 7 degrees affected by this.
The institution_uuid is correctly assigned, but the name was not
mapped to the expected value.
The expected correct name is: University of St Andrews.
This issue is causing the affected trainee records to show as incomplete.
This mapping is expected to happen during the Apply Import. We suspect that this data was updated before we have introduced the `match_synonyms`:  https://github.com/DFE-Digital/dfe-reference-data/blob/main/lib/dfe/reference_data/degrees/institutions.rb#L1139 and the apply importer at that time was not doing this mapping.
Proposing to fix these records and monitor the situation moving forward. Please check …
> [5473] - BUGFIX - Degree recognition issue

- app/components/confirm_trainee_delete/view.html.erb
- app/components/confirm_trainee_delete/view.rb
- app/controllers/system_admin/trainee_deletions/confirmations_controller.rb
- app/controllers/system_admin/trainee_deletions/reasons_controller.rb
- app/forms/system_admin/delete_trainee_form.rb
- app/policies/trainee_policy.rb
- app/services/form_store.rb
- app/services/trainees/filter.rb
- app/views/system_admin/trainee_deletions/confirmations/show.html.erb
- app/views/system_admin/trainee_deletions/reasons/edit.html.erb
- app/views/trainees/admins/show.html.erb
- config/locales/en.yml
- config/routes/system_admin_routes.rb
- spec/features/system_admin/trainees/delete_a_trainee_spec.rb
- spec/forms/system_admin/delete_trainee_form_spec.rb
- spec/support/features/page_helpers.rb
- spec/support/page_objects/system_admin/trainee_deletions/confirmation.rb
- spec/support/page_objects/system_admin/trainee_deletions/reasons.rb
- spec/support/page_objects/trainees/admin.rb
https://trello.com/c/uog5bcBM/5449-l-add-feature-to-allow-admins-to-delete-records
- New journey to soft delete non-awarded traineea
- Log in as admin
- Pick a non-awarded trainee and remember the name for later
- Click the admin table and click "Delete this trainee" link at the bottom
- Follow the journey and play around looking for bugs
- If everything goes as expected the trainee should be delete and not show up on the trainees index page
> [5449] Allow admins to delete records

- app/controllers/trainees/award_recommendations_controller.rb
- app/jobs/auditing/trainee_auditor_job.rb
- app/models/reports/trainee_report.rb
- app/services/bulk_update/recommend.rb
- app/services/bulk_update/recommendations_uploads/create_recommendations_upload_rows.rb
- app/services/bulk_update/recommendations_uploads/trainee_lookup.rb
- app/services/bulk_update/recommendations_uploads/validate_trainee.rb
- spec/fixtures/files/bulk_update/recommendations_upload/complete.csv
- spec/jobs/auditing/trainee_auditor_job_spec.rb
- spec/services/bulk_update/recommend_spec.rb
- spec/services/bulk_update/recommendations_uploads/trainee_lookup_spec.rb
- spec/services/bulk_update/recommendations_uploads/validate_trainee_spec.rb
https://trello.com/c/cP6Ojw7t/5476-when-bulk-recommending-308-trainees-it-took-a-long-time-performance-test-bulk-recommendation
- Speed up the processing time for the action `BulkUpdate::RecommendationsUploadsController#update`
- New class `BulkUpdate::RecommendationsUploads::TraineeLookup` which uses hash maps built on-demand supporting trainee lookup by TRN, HESA ID or Trainee ID
- Change `Reports::TraineeReport` so it only loads `degree` and `course` on demand (prevents hundreds of unnecessary DB calls during the creation of each row)
**The processing time has gone from on average 30 seconds to 10-12 seconds.** 
- Go through the bulk recommend process locally using prod data to get an realistic idea of performance
- Run the test on `main` branch and then switch to this PR branch to …
> [5476] Improve bulk QTS recommend performance

- app/models/reports/trainee_report.rb
- spec/models/reports/trainee_report_spec.rb
The current bug:
There was a logic error in the code that was setting
the date range to ' ' for all trainees of type EYTS,
in the CSV export, even for trainees that did in fact
have a date range available.
This behaviour was preventing providers to bulk recommend
EYTS trainees.
Mark the date range as ' ' only for trainees that have no date range available.
- Pick a provider
- Go to bulk recommend
- Download the trainees
- Pick some that have a blank date range
- Try to recommend them
- It should not throw a validation error anymore
> [5512] Fix date range bug

- config/environments/production.rb
- terraform/aks/variables.tf
- terraform/aks/workspace-variables/dv_review_aks.tfvars.json
- terraform/aks/workspace-variables/production_aks.tfvars.json
- terraform/aks/workspace-variables/productiondata_aks.tfvars.json
- terraform/aks/workspace-variables/qa_aks.tfvars.json
- terraform/aks/workspace-variables/review_aks.tfvars.json
- terraform/aks/workspace-variables/staging_aks.tfvars.json
Add application startup/liveness probes
Without the startup probe review apps can fail as the deploy workflow continues while db:migrate is still running
Add /ping as the probe_path for each aks env
Remove rails ssl https redirect for /ping as this causes aks probe issues as requires http internally
deploy_v2 aks workflow
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/5090080650/jobs/9148643474
deploy paas workflow
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/5090250366/jobs/9149000656
> Add application probes

- app/components/dqt_data_summary/view.html.erb
- app/controllers/system_admin/dead_jobs_controller.rb
- app/controllers/system_admin/pending_trns/base_controller.rb
- app/controllers/system_admin/pending_trns/request_trns_controller.rb
- app/controllers/system_admin/pending_trns/retrieve_trns_controller.rb
- app/controllers/system_admin/pending_trns_controller.rb
- app/jobs/dqt/register_for_trn_job.rb
- app/views/system_admin/_tab_nav.html.erb
- app/views/system_admin/pending_trns/index.html.erb
- config/routes/system_admin_routes.rb
https://trello.com/c/PkUZo1w7/5500-spike-for-2-days-think-of-and-create-solutions-for-monitoring-when-trn-requests-fail-trainees-are-left-in-pending-trn
- New support tab "Pending TRNs"
- Pending TRNs page lists all trainees waiting for TRNs and 2 action buttons to try and retrieve TRN or re-request for TRN
- No really possible to test in PR environment. Was tested locally apart from re-requesting TRN
> [5500] Support admin feature to manage trainees with pending TRNs

- app/controllers/api/users_controller.rb
- app/controllers/system_admin/users_controller.rb
- spec/features/system_admin/users/deleting_a_user_spec.rb
- spec/support/page_objects/system_admin/users/index.rb
Discarded users show up on the `system-admin/users` index when searching (via the API). They can also be accessed via their `show`
* API searches only `kept` users
* a user is retrieved using `kept` when they are `shown`
* delete a non admin user and try to search for them
* try accessing their show page by visiting their `/system-admin/users/:id`
> [5514] - Don't show discarded users in system admin UI

- app/controllers/system_admin/dead_jobs_controller.rb
- app/services/dead_jobs/base.rb
- app/services/dead_jobs/dqt_update_trainee.rb
- app/views/system_admin/dead_jobs/show.html.erb
- config/routes/system_admin_routes.rb
- spec/features/system_admin/dead_jobs/viewing_dead_jobs_spec.rb
- spec/services/dead_jobs/dqt_recommend_for_award_spec.rb
- spec/services/dead_jobs/dqt_update_trainee_spec.rb
- spec/services/dead_jobs/dqt_withdraw_trainee_spec.rb
- spec/support/page_objects/system_admin/dead_jobs/dead_jobs_dqt_update_trainee.rb
- spec/support/shared_examples/dead_jobs.rb
We want to make it easier for Register and DQT to resolve dead jobs. Some of these should be possible without dev support, if we make the right information and actions available to DQT/TRA operations.
* adds new fields to the CSV export
* refactors the base class to make it a bit easier to understand
* adds retry and delete actions for individual jobs
> [5516] - improve dead jobs interface

- app/controllers/system_admin/pending_trns/request_trns_controller.rb
- app/controllers/system_admin/pending_trns_controller.rb
- app/jobs/dqt/update_trainee_job.rb
- app/views/system_admin/pending_trns/index.html.erb
- config/routes/system_admin_routes.rb
- spec/factories/trainees.rb
- spec/features/system_admin/pending_trns/pending_trns_spec.rb
- spec/support/features/page_helpers.rb
- spec/support/page_objects/system_admin/pending_trns/pending_trns.rb
There was a bug in a previous PR https://github.com/DFE-Digital/register-trainee-teachers/pull/3303
The "Re-request for TRN" button did not function as expected.
- Fix the broken button
- Add relevant tests
- Rename the button to "Re-submit for TRN"
- As this is an admin only feature it can be tested in production
> [5500] Fix "Re-request for TRN" button

- terraform/aks/databases.tf
- terraform/aks/workspace-variables/production_aks_Terrafile
- terraform/aks/workspace-variables/productiondata_aks_Terrafile
- terraform/aks/workspace-variables/staging_aks_Terrafile
AKS database modules will use long service name in resource name, instead of short service name.
see https://github.com/DFE-Digital/terraform-modules/pull/30
Update aks modules to pass service_name
change aks modules using stable to testing
ran make against module branch
deploy aks_review app when above PR merged
> terraform aks db modules name using service_name

- app/forms/degrees_form.rb
- app/models/trainee.rb
- spec/forms/degrees_form_spec.rb
The details confirmation form was not working properly when degrees where updated from the UI as the cached values were not applied to the `DegreeForm`.
Remove thew original degree_forms method as it was not applying the values for the cache store.
Also refactor some methods to avoid the confusion between degrees and degree_forms.
Pick any TRN form the ticket and try to manually update the missing attributes.
> [5525][BUG FIX] Fix form degrees validation mechanism

- app/services/bulk_update/recommendations_uploads/validate_csv_row.rb
- config/locales/en.yml
- config/webpacker.yml
- spec/services/bulk_update/recommendations_uploads/validate_csv_row_spec.rb
When bulk recommending trainees, if you give dates that don’t make any sense, like ‘01/85/2022’, it’s an unhandled error. This means you’ll just see the ‘Sorry, something has gone wrong’ page, rather than specific error on the bulk recommend error CSV to correct your mistake.
This PR fixes that; adding an error and handling the issue with a popup message.
Add new error to handle impossible date.
Add new error; try to upload an impossible date.
> [5475] Handle impossible dates in bulk upload

- app/forms/submissions/base_validator.rb
- db/data/20230607105025_remove_incomplete_tag_from_hesa_trainees_with_missing_degree_fields.rb
- spec/forms/submissions/missing_data_validator_spec.rb
This is because a lot of this information is optional over HESA. However, these trainees were still able to get a TRN, so we do not think we should be flagging this as incomplete, until we can make this information compulsory for 2024-2025.
- Modify `Submissions::BaseValidator` so it ignores degree validation for HESA trainees
- Data migration to recalculate `Trainee#submission_ready`
- Data migration affects about 300 trainees
> [5521] Do not show HESA trainees as incomplete with missing degree information

- app/models/trainee.rb
- app/services/trainees/create_from_hesa.rb
- spec/services/trainees/create_from_hesa_spec.rb
Update the behaviour of HESA importer for trainees.
The following new rules will apply to the importer:
- if the ITT start date has changed and if the trainee is ‘withdrawn’ or ‘awarded’ in Register THEN create a new record
- if the ITT start date has changed and if the trainee is not in ‘withdrawn’ or ‘awarded’ in Register THEN update the record as normal
- if the ITT start date has not changed and if the trainee is ‘withdrawn’ or ‘awarded’ in Register THEN do not create a new record and do not update the record
- if the ITT start date has not changed and if the trainee is not in ‘withdrawn’ or ‘awarded’ in Register THEN update the record as norma
> [5545] - Update HESA Trainees Importer

- .github/actions/deploy_v2/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/deploy-v2.yml
- .github/workflows/scheduled-aks-db-restore.yml
- .gitignore
- terraform/aks/databases.tf
- terraform/aks/variables.tf
- terraform/aks/workspace-variables/productiondata_aks.tfvars.json
Create AKS productiondata env
Add productiondata_aks env to workflows
It will be deployed in merge to main, but failure to deploy the env will not cause a workflow failure.
Productiondata postgres db will be reloaded from the paas env db daily
No worker process.
Secrets copied from paas env, with some modifications.
make productiondata_aks deploy-plan
check workflow on merge.
> Add AKS productiondata environment

- app/helpers/funding_helper.rb
- config/initializers/training_routes.rb
- config/locales/en.yml
- spec/models/trainee_spec.rb
Update training initiatives
- Remove “Troops to teach” as a selectable option
- Remove “Maths and Physics/…..“ as a selectable option
- Create “Veteran teaching undergraduate bursary”
- Create “International Relocation Payment “
The trainee records with old training initiatives will remain as they are.
> [5546] - Update training initiatives

- app/lib/dqt/params/trn_request.rb
- spec/lib/dqt/params/trn_request_spec.rb
- Several trainees are stuck retrieving a `TRN`
- Their requests failed as they were missing `trainingCountryCode`
- These are blank as `Dqt::Params::TrnRequest` uses the HESA country codeset mappings to retrieve an iqts country code
Use DTTP codesets to retrieve the country code - this is used to build the autofill iqts country form so should match up correctly all of the time.
> [5559] - use DTTP codeset for country code lookup

- .gitignore
- bin/dev
Make dev startup a little easier.
- Add `./bin/dev` to fire up all required processes in dev (uses Procfile.dev). This comes out of the box in Rails 7.1 (if using esbuild etc which we'll probably transition into)
- Add `.node-version` to `.gitignore` for those of us who don't use ASDF. 
- You can try it out locally
> [xxx] - Add bin/dev for easier startup

- config/initializers/training_routes.rb
- db/data/20230619122848_add_funding_rules_for_20232024.rb
- db/seeds.rb
https://trello.com/c/lRyQNdvc/4979-m-update-register-for-23-24-funding-rules
- Adds the funding rules for 2023/24 in line with this [spreadsheet](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/Shared%20Documents/Becoming%20a%20Teacher/TWD-REGISTER/4.%20Business%20Analyst/Routes,%20data%20and%20funding.xlsx?d=wfaaa7ba88b434d2681bb56a19f83aee3&csf=1&web=1&e=BRsRmZ)
- Data migration to seed environments with new values
- Create a trainee in the next academic cycle by setting the itt start date correctly (eg 11/9/2023)
- Assert the correct funding information is shown for relevant route (after completing course details)
Language specific funding will be handled via copy in the UI, we're treating these under the general Modern Languages allocation subject to simplify things
> [4979] Add funding rules for 2023/24

- .github/workflows/build-and-deploy.yml
The dependabot merge step in the build-and-deploy workflow needs to use a token with the appropriate rights,
otherwise it won't trigger a deployment on merge
Change secret to use a valid token
Confirm workflows triggered after merge.
> Change github token used for dependabot merge

- config/locales/en.yml
Currently breaking [this build](https://github.com/DFE-Digital/register-trainee-teachers/pull/3347), but presumably not for any reason to do with a minor version upgrade to Faker.
Change a locale key from `flow_validator` to `form_validator`
If the tests pass, life is good.
> Fixes the locale key for the diversity form validator

- app/controllers/trainees/award_recommendations_controller.rb
- app/forms/trainee_form.rb
- app/services/dqt/trainee_update.rb
- spec/controllers/trainees/award_recommendations_controller_spec.rb
- spec/forms/outcome_date_form_spec.rb
We are seeing a few dead jobs (https://www.register-trainee-teachers.service.gov.uk/system-admin/dead_jobs) that indicate a repeatedly failing Sidekiq job caused by a DQT API error that happens when we recommend a trainee. It appears to be a race condition between a call to the `update` and `itt-outcome` endpoints.
There is already an API call to the `itt-outcome` endpoint and we should not need to make a separate call to `update`. It seems that if the calls happen in the wrong sequence we end up with a dead update job because you can't update a teacher record that has already got a QTS/EYTS date.
This PR skips the update call.
For one of the problem cases there are 3 separate updates in the audit trail with the following kinds of changes:
1. `{"outcome_date": [null, "2023-06-14"]}` - …
> Don't make DQT API update call when recommending

- Gemfile
- Gemfile.lock
- app/forms/degree_form.rb
- app/helpers/degrees_helper.rb
- app/lib/dfe_reference/degrees_query.rb
- app/lib/dfe_reference/disabilities_query.rb
- app/lib/dqt/params/trn_request.rb
- app/models/disability.rb
- app/services/degrees/create_from_csv_row.rb
- app/services/degrees/create_from_hesa.rb
- app/services/degrees/map_from_apply.rb
- app/services/trainees/create_from_apply.rb
- app/views/trainees/degrees/_uk_degree_form.html.erb
- config/analytics_blocklist.yml
- db/data/20220803141230_backfill_missing_degree_uuids.rb
- db/data/20221025133503_add_other_to_no_country_no_institution_degrees.rb
- db/data/20221025155728_backfill_uk_degrees_with_other_institution.rb
- db/data/20230123100908_fix_unmapped_trainee_degree_subjects.rb
- db/data/20230612133512_backfill_disability_uuids_from_dfe_reference_gem.rb
- db/migrate/20230612131445_add_uuid_to_disabilities.rb
- db/schema.rb
- spec/factories/degrees.rb
- spec/forms/degree_form_spec.rb
- spec/helpers/degree_helper_spec.rb
- spec/lib/dfe_reference/degrees_query_spec.rb
- spec/lib/dqt/params/trn_request_spec.rb
- spec/lib/dqt/params/update_spec.rb
- spec/services/trainees/create_from_apply_spec.rb
- spec/support/api_stubs/apply_api.rb
https://trello.com/c/pr1UWEdo/5547-l-add-disability-reference-data-to-register
- Rename `Degrees::DfEReference` to `DfEReference::DegreesQuery`. This class is actually not a service like the other services with a `call` method. Moving it into `lib` because more classes will be added under the namespace `DfEReference`
- Update `Trainees::CreateFromApply` to use the newly added disability UUID's from Apply to map trainees to the `disabilities` table
- Migration to add `uuid` column to `disabilities` table
- Data migration to populate `uuid` fields
> [5547] Use disability reference data for Apply imports

- app/services/trainees/create_from_apply.rb
- spec/services/trainees/create_from_apply_spec.rb
When importing trainees from Apply we had previously assumed that the `disabilities_and_health_conditions` attribute would contain a non-nil value. This turns out not to be the case and is leading to errors:
https://dfe-teacher-services.sentry.io/issues/4272037653/?project=5552118&referrer=slack
We need to interpret `nil` `disabilities_and_health_conditions` values as an empty list of disabilities.
Is there anything missing here?
> Handle `nil` `disabilities_and_health_conditions`

- Dockerfile
Bump pkgconf version to fix CVE-2023-24056
Update pkgconf to version 1.8.1-r0
[Build No Cache](https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/5382073526/jobs/9766988985) is green
> Bump pkgconf version to fix CVE-2023-24056

- spec/spec_helper.rb
We seem to have enough data in Sentry to point us in the direction of common flakey tests https://dfe-teacher-services.sentry.io/issues/?environment=test&project=5552118&query=is%3Aunresolved&referrer=issue-stream&stream_index=1. 
Removing this code to reduce the noise in Sentry so we can make a plan on what to do re: above.
> [xxx] Remove sentry rspec code

- .github/actions/deploy_v2/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/deploy-v2.yml
- .github/workflows/scheduled-aks-db-restore.yml
- config/settings/production_aks.yml
- terraform/aks/databases.tf
- terraform/aks/variables.tf
- terraform/aks/workspace-variables/production_aks.tfvars.json
Create AKS production env
differences from paas prod
- send_data_to_big_query: false
- integrate_with_dqt: false
- google-tag-manager removed
- extra basic auth added
- notify apikey removed from secrets
Add production_aks env to workflows
It will be deployed in merge to main, but failure to deploy the env will not cause a workflow failure.
Production postgres db will be reloaded from the paas env db daily
Secrets copied from paas env, with some modifications.
Builds analysis postgres db.
make production_aks deploy-plan
check workflow on merge.
> Add aks production env to workflows

- app/views/guidance/bulk_recommend_trainees.md
the bulk recommend guidance page has a broken link `/guidance/bulk-recommend-trainees`
corrects the link to `/bulk-update/recommend/choose-who-to-recommend`
> [xxxx] - fix bulk recommend guidance broken link

- app/components/provider_card/view.html.erb
- app/components/provider_card/view.rb
- app/controllers/system_admin/providers_controller.rb
- spec/components/provider_card/view_spec.rb
The view component that renders each provider on this page also looks up the `provider.users.kept.count`.
Adding a join to the users table and a customer select list we can pull this information back in a single query.
Visit: `/system-admin/providers`
Log extract before
```
2023-06-28 17:25:44.399007 D [44813:puma srv tp 001] (0.708ms) ActiveRecord -- Provider Load -- { :sql => "SELECT \"providers\".* FROM \"providers\" ORDER BY \"providers\".\"name\" ASC", :allocations => 242, :cached => nil }
2023-06-28 17:25:44.403723 D [44813:puma srv tp 001] (0.992ms) ActiveRecord -- User Count -- { :sql => "SELECT COUNT(*) FROM \"users\" INNER JOIN \"provider_users\" ON \"users\".\"id\" = \"provider_users\".\"user_id\" WHERE \"provider_users\".\"provider_id\" = $1 AND \"users\".\"discarded_at\" IS …
```
> [5600] Fix for a 1+n query on the providers index page

- app/controllers/trainees/publish_course_details_controller.rb
- config/settings.yml
- lib/tasks/example_data.rake
- spec/factories/courses.rb
- spec/factories/trainees.rb
- spec/features/form_sections/teacher_training_data/apply_applications_spec.rb
- spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb
- spec/features/trainee_actions/change_course_spec.rb
The academic year is going to change
Amended the default course year
Everything that academic year entails
Not sure, don't think so.
> [5577] Amended the default course year as the academic year is going to change

- app/controllers/trainees/publish_course_details_controller.rb
- config/settings.yml
- lib/tasks/example_data.rake
- spec/factories/courses.rb
- spec/factories/trainees.rb
- spec/features/end_to_end/provider_led_postgrad_journey_spec.rb
- spec/features/form_sections/teacher_training_data/apply_applications_spec.rb
- spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb
- spec/features/trainee_actions/change_course_spec.rb
- spec/features/trainee_actions/edit_trainee_training_route_spec.rb
- spec/services/exports/funding_trainee_summary_data_spec.rb
- spec/support/current_academic_cycle.rb
Preparing 2023-2024 academic year
Amended `current_recruitment_cycle_year` to `2023`
This is for the 2022 to 2023 recruitment cycle courses in order to serve the 2023-2024 academic year to register a trainee
Specs was realigned as
1. A trainee by default when created from scratch will fall into `current` academic cycle based on today date instead of allowing for `next`academic cycle
2. Some of the forms bypass the creating a trainee and ends up using stale trainee from previous
3. Certain specs was locked down to a particular time as there are 2 academic cycles in play and the specs are designed for a singular academic cycle
Don't think there any below is applicable. 
> [5582] Amended `current_recruitment_cycle_year` to `2023`

- db/data/20230703103109_sync_intraining_trainees_to_dqt_prior_to_feb2023.rb
Rob wants us to send an initial 500 trainee updates as a smoke check. This is a slim down version of the larger update to follow on from this https://github.com/DFE-Digital/register-trainee-teachers/pull/3367.
> [5579] Sync an initial batch of 500 trainees to DQT

- app/controllers/base_trainee_controller.rb
- app/views/trainees/_action_bar.html.erb
We are seeing a (kind of) 1+n query on the trainees index page. 
https://dfe-teacher-services.sentry.io/issues/4200266000/?environment=production&project=5552118&query=is%3Aunresolved&referrer=issue-stream&stream_index=1
There are a number of repeated SQL queries that fetch the filtered count of trainees in the `BaseTraineeController`. I think we can safely memoize these on a per request basis to avoid the 1+n query.
Does this change look safe?
To reproduce the issue you just need to type something into the search box on the main trainee index page and check the logs for repeating queries that look a bit like this:
```
SELECT trainees.* FROM trainees INNER JOIN
(SELECT trainees.id AS pg_search_id,
(ts_rank((to_tsvector('simple', coalesce(trainees.first_names::text, ''))
|| …
```
> [5599] Memoize counts in TraineesController#index

- app/controllers/drafts_controller.rb
- app/controllers/trainees_controller.rb
https://trello.com/c/XrhWvkwh/5598-n1-query-traineesreviewdraftscontrollershow
Getting N+1 queries on the drafts/registered pages for academic cycles/apply applications (some cached some aren't). This also happens every time filtering via JavaScript is performed.
- Add necessary includes
Before:
> [5598] Resolve N+1 issues on drafts/registered page

- app/components/flash_banner/view.html.erb
- app/components/year_change_banner/view.html.erb
- app/components/year_change_banner/view.rb
- app/views/layouts/application.html.erb
- config/initializers/date_formats.rb
- spec/components/year_change_banner/view_preview.rb
- spec/components/year_change_banner/view_spec.rb
- spec/support/page_objects/system_admin/uploads/index.rb
- spec/support/page_objects/system_admin/users/index.rb
- spec/support/page_objects/system_admin/users/show.rb
We want to warn users before the academic year changes, and after it’s just changed, so they’re not surprised by it changing. Many users think that the new year starts in September, when in reality it starts 1 August.
Add a new component, `YearChangeBanner::View`, to display a banner with a link to the dates guidance page.
This component can be 'rendered' all year round because it works out whether to display itself based on the current date.
I'm not sure whether this should be displayed all the time. The ticket implies that it should be displayed for the full 2 months (on every page). Do we think this is overkill/potentially annoying?
> [5626] Add a YearChangeBanner component and render

- app/controllers/trainees/apply_applications/course_details_controller.rb
- app/controllers/trainees/language_specialisms_controller.rb
- app/controllers/trainees/subject_specialisms_controller.rb
- app/forms/language_specialisms_form.rb
- app/forms/publish_course_details_form.rb
- app/helpers/course_details_helper.rb
- app/services/calculate_subject_specialism_type.rb
- app/views/trainees/language_specialisms/edit.html.erb
- config/locales/en.yml
- spec/features/form_sections/teacher_training_data/apply_applications_spec.rb
- spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb
- spec/forms/language_specialisms_form_spec.rb
- spec/support/page_objects/trainees/language_specialism.rb
The current language specialisms form (for modern languages courses) presents a set of check boxes from which the user can select up to 3 language choices. This does not capture the priority order of the languages which will be needed for the next recruitment cycle.
Change the UI from a field set of checkboxes to three (order significant) `select` elements.
e.g. A fictitious Modern languages with Biology course prompts for 1-2 languages...
...followed by a Biology specialism:
- Have I missed anything in the backend form-data mapping?
- Are there any other tests that might be useful here?
> [5578] - Update view and LanguageSpecialismsForm for multiple selects

- db/data/20230710091532_fix_incorrectly_awarded_trainees_5666.rb
https://trello.com/c/FI7dTdr8/5666-status-change
https://trello.com/c/KyHB4tnP/5669-incorrect-recommendation-for-qts
https://trello.com/c/hnPIBXju/5670-qts-recommendation-in-error
https://trello.com/c/MCOztjmA/5665-mistakes-after-trainees-have-been-recommended
We have a few trainees which have been incorrectly awarded/recommended. Some will need to be withdrawn but need to be put into an `in training` state so the provider can properly withdraw the trainee.
- Data migration to put these trainees back into an `in training` state, in this case `trn_received`.
Tested locally
DQT have already updated the trainees on their end
> [5666] Fix incorrectly awarded and recommended trainees

- app/jobs/dqt/sync_teachers_job.rb
- app/services/dead_jobs/base.rb
- config/sidekiq_cron_schedule.yml
- spec/factories/dqt/dqt_teacher_trainings.rb
- spec/factories/dqt/dqt_teachers.rb
- spec/support/shared_examples/dead_jobs.rb
https://trello.com/c/w10d50pf/5661-spike-dead-jobs-export-failing-for-large-volume-of-updatejobs
When we have a lot of dead jobs, the export timeouts due to having to make network requests to DQT to fetch the trainee's record to be compared with for each one in the set.
We introduced a pattern in early register days when working with DTTP to keep local sync tables so we can query third party data we needed quicker. We currently have a couple for the DQT teacher/teacher training records in Register. We should probably use these to look up the information instead of having to fetch them over the wire every time.
The changes here build on top of this PR https://github.com/DFE-Digital/register-trainee-teachers/pull/3114, which had the same idea. The team discussed having a job which ran …
> [5661] Refactor dead job export logic to use DQT tables

- app/webpacker/styles/application.scss
There is no margin between the start banner and notificaiton bar which doesn't look right. 
Attempting to fix that here with a custom css rule just of navigation bars following the start page banner.
Before:
After:
Is there a better place to drop CSS rules like this?
> Fix layout of notification banner on the start page

- db/data/20230515083653_trainee_withdrawal_reasons.rb
[This migration error occurs in staging](https://dfe-teacher-services.sentry.io/issues/4307396315/?environment=staging_aks&project=5552118&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=0)
Don't try and `insert_all` unless there are attributes to pass in.
> [xxxx] - Fix empty attribute withdrawal reasons migration

- app/forms/course_years_form.rb
- app/services/trainees/set_academic_cycles.rb
- app/views/trainees/course_years/edit.html.erb
- spec/components/funding/view_spec.rb
- spec/factories/trainees.rb
- spec/features/trainee_actions/change_course_spec.rb
- spec/forms/course_years_form_spec.rb
- spec/services/trainees/set_academic_cycles_spec.rb
This PR changes the default recruitment cycle for trainees entered manually in the month before the start of the new academic year.
e.g. In July 23 we are still in the 22-23 recruitment cycle but most providers entering a new trainee will be doing so for the 23-24 recruitment cycle so we should make that the default.
- Are the changes made in the right places?
- Are the tests sufficient?
> [5627] Change default course cycle for trainees registered after 1 July

- app/views/trainees/funding/bursaries/_grant_form.html.erb
- app/views/trainees/funding/bursaries/_non_tiered_bursary_form.html.erb
- app/views/trainees/funding/bursaries/_tiered_bursary_form.html.erb
- config/locales/en.yml
We’ve already updated the funding mapping for 23-24 academic year in this ticket completed last sprint.  Now we want to update the funding UI page for 2023 for two reasons:
- Scholarships for 23/24 are more nuanced and need extra text
- The page is very bursary focused with other stuff tacked on. We want to make it more agnostic to types of funding.
- The page assumes scholarships will always appear with bursaries. It would be better if any the page could work with any type of funding agnostically.
updates existing locales and partials to reflect new funding outcomes wording
There's multiple tracks for the different funding partials and the conditionals within them, I believe this is all of them. To get to each of them, find a draft trainee (or create one and start by changing their …
> [5625] - Update funding UI page for 2023/2024

- app/models/application_record.rb
`DEPRECATION WARNING`
Removed unneeded code
This was making my :exploding_head: 
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/5576298381/jobs/10187504930?pr=3431#step:4:1279
```
***"host":"register-pr-3431-854f66f869-s2g29","application":"Semantic Logger","environment":"review_aks","time":"2023-07-17T14:38:33.340+01:00","level":"info","level_index":2,"pid":24,"thread":"7700","name":"Rails","message":"DEPRECATION WARNING: DfE::Analytics::Entities was manually included in a model (AcademicCycle), but it's included automatically since v1.4. You're running v1.10.0. To silence this warning, remove the include from model definitions in app/models."***
***"host":"register-pr-3431-854f66f869-s2g29","application":"Semantic …
```
> [xxxx] Removed unneeded code causing `DEPRECATION WARNING`

- app/views/layouts/application.html.erb
- config/settings.yml
https://trello.com/c/Co1YIN6k/5680-s-monday-17th-july-show-temporary-banner-to-warn-users-of-planned-system-downtime-on-wednesday-19th-july
- Add a temporary instance of the govuk notification banner with the content
- Comment out the existing year change banner
https://register-pr-3431.test.teacherservices.cloud
> [5680] Add banner to warn of downtime

- app/services/trainees/create_from_apply.rb
- app/services/trainees/find_duplicates.rb
- spec/services/trainees/create_from_apply_spec.rb
- spec/services/trainees/find_duplicates_spec.rb
We have a duplicate record check to avoid importing an Apply drafts where the provider has manually registered a trainee. This currently strictly checks the first and last name with DOB.
We saw in 2021 that this duplicate check missed a number of records - primarily where the names didn't 100% match because one side had a middle name and the other didn't.
We also have an issue that our check will block applications from different years. So if someone was recruited (and then withdrew) in one year, then later re-applied to the same provider, the new application will get blocked. Similar for trainees who do EYTS and then QTS.
This PR updates the duplicate match logic in `Trainees::CreateFromApply` to implement the following strategy:
- Find any `Trainee` records that match the provider, …
> [4727] Improve apply draft import duplicate record check

- app/views/trainees/funding/bursaries/_tiered_bursary_form.html.erb
adds missing academic year declaration to funding guidance link
> [xxxx] - fix broken link in tiered bursary form

- app/models/trainee.rb
- config/analytics.yml
- db/migrate/20230719151850_add_trainees_sent_slug_to_dqt.rb
- db/schema.rb
We have a plan to use `slug` values to identify DQT records in order to help match trainee records more accurately between Register and DQT. This PR adds a database column that will be needed when we start sending `slug` values to DQT at the point we create a new record so that we know later to include the `slug` when we send, for example, update requests to DQT for that same trainee.
This is just a migration to add the `trainees.slug_sent_to_dqt_at` (`datetime`) column to the schema. The column is nullable because `null` is a meaningful value, indicating that we have not sent the `slug` for this trainee to DQT yet.
- Does a timestamp make sense for this purpose?
- Is there a better name for it?
NB: Please notify the #twd_data_insights team and ask for a review if new fields are being …
> Migration to add `trainees.slug_sent_to_dqt_at`

- app/services/dqt/recommend_for_award.rb
- app/services/dqt/trainee_update.rb
- app/services/dqt/withdraw_trainee.rb
- spec/services/dqt/recommend_for_award_spec.rb
- spec/services/dqt/update_spec.rb
- spec/services/dqt/withdraw_trainee_spec.rb
We want to use the slug identifier to help us identify records between Register and DQT. This should improve some data problems we’ve had.
When we use the DQT API to update a trainee, we should add the slug identifier as what we check on to send the update, rather than date of birth.
Replaces trainee `birthdate` with `slug` in calls to the `itt-outcome` endpoint (withdrawal and award)
dependant on #3447 and #3449
> [5709] - update itt-outcome DQT endpoints with trainee slug

- app/lib/dqt/params/trn_request.rb
- app/services/dqt/register_for_trn.rb
- app/services/trainees/set_slug_sent_at.rb
- spec/lib/dqt/params/trn_request_spec.rb
- spec/services/trainees/set_slug_sent_at_spec.rb
We have a plan to use `slug` values to identify DQT records in order to help match trainee records more accurately between Register and DQT. This PR deals with sending the `Trainee#slug` to DQT service when we create a new trainee record in Register.
We send the `slugid` attribute in requests to the `/v2/trn-requests/...` (request a TRN) DQT endpoint.
We also set the `Trainee#slug_sent_to_dqt_at` attribute so that we can track whether or not DQT has been sent the `slug` for a given trainee record.
This PR depends on https://github.com/DFE-Digital/register-trainee-teachers/pull/3447 and will remain in draft until that gets merged.
- Is there anything missing?
- Does this need to be behind a feature flag? (I've assumed not but can change that).
NB: Please notify the #twd_data_insights team …
> [5710] Add `slugid` to DQT `trn_request` calls

- terraform/aks/workspace-variables/review_aks.tfvars.json
Review apps are currently failing to deploy due to the strong migrations gem causing an error when trying to run every migration and marking some as unsafe. 
Ideally, for review/preview apps, we should be loading the latest schema rather than try to run every migration defined in the app. The schema represents the latest state of the database so we should use it. It also helps avoid complaints by gems such as the strong migrations.
- Switch AKS review app startup command to use `db:schema:load`
- The review app builds and deploys
- The seed and example data are still populated successfully
> [xxxx] Switch to schema load for review app

- app/models/trainee.rb
- config/analytics.yml
- db/migrate/20230726105546_add_alternative_hesa_id_to_trainees.rb
- db/schema.rb
https://trello.com/c/dPHAQP0z/5749-add-alternative-hesa-id-field
Providers can sometimes change the `hesa_id` field for hesa trainees which can lead us to creating duplicate records. We're tightening up the matching rules but if the `hesa_id` has changed, we'll need to capture the old one.
- Add a `previous_hesa_id` field to `trainees`. This by default will and should ideally be empty. It's only used for situations where the current `hesa_id` has been changed and it becomes the `previous_hesa_id`.
As far as the ticket goes, we've only ever seen an original `hesa_id` and a new/alternative one in the data. We don't yet know if we need to capture many old ids. One additional field seems low risk than drastically changing the implementation to support many old ids right now (we don't …
> [5749] Add previous hesa id field

- Gemfile
- Gemfile.lock
- config/initializers/console.rb
We want to be able to easily attribute changes made in `rails console` on production to the developer that ran them.
This PR adds a prompt to ask for your name when you open `rails console` in a production environment. It uses the name input to attribute all audit entries generated as a result of any subsequent commands in that console session.
Have I missed anything?
> [xxxx] Add prompt for audited user in production console

- app/services/dqt/recommend_for_award.rb
- app/services/dqt/trainee_update.rb
- app/services/dqt/withdraw_trainee.rb
- spec/services/dqt/recommend_for_award_spec.rb
- spec/services/dqt/update_spec.rb
- spec/services/dqt/withdraw_trainee_spec.rb
reinstates #3454
We want to use the slug identifier to help us identify records between Register and DQT. This should improve some data problems we’ve had.
When we use the DQT API to update a trainee, we should add the slug identifier as what we check on to send the update, rather than date of birth.
Replaces trainee `birthdate` with `slug` in calls to the `itt-outcome` endpoint (withdrawal and award)
dependant on #3447 and #3449
When this was initially merged in via #3454 DQT began erroring. This was raised and then later addressed in [this slack thread](https://ukgovernmentdfe.slack.com/archives/C04HLTPG1RR/p1690279545985769)
> [reinstate] [5709] - update itt-outcome DQT endpoints with trainee slug

- app/components/award_details/view.rb
- config/locales/en.yml
- spec/components/award_details/view_spec.rb
This PR implements a small copy change to make things clear for trainees that have been recommended for QTS, see https://becoming-a-teacher.design-history.education.gov.uk/register-trainee-teachers/making-it-clearer-that-a-trainee-is-waiting-to-be-awarded-teaching-status/
Rather than leave the award date field blank we render a message to indicate when the trainee was recommended for qualification.
> [5716] New copy for waiting to be awarded teaching status

- Gemfile
- Gemfile.lock
- app/controllers/heartbeat_controller.rb
- spec/requests/heartbeat_spec.rb
Reverts DFE-Digital/register-trainee-teachers#3444
Causing deploys to fail due to Redis version being under what's required by the Sidekiq bump:
```shell
You are connecting to Redis 6.0.14, Sidekiq requires Redis 6.2.0 or greater
/usr/local/bundle/gems/sidekiq-7.0.0/lib/sidekiq/cli.rb:77:in `run'
/usr/local/bundle/gems/sidekiq-7.0.0/bin/sidekiq:31:in `<top (required)>'
/usr/local/bundle/bin/sidekiq:25:in `load'
/usr/local/bundle/bin/sidekiq:25:in `<top (required)>'
/usr/local/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
/usr/local/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
/usr/local/lib/ruby/3.1.0/bundler/cli.rb:486:in `exec'
/usr/local/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run' …
```
> Revert "Bump sidekiq from 6.5.8 to 7.0.0"

- app/views/guidance/performance_profiles.html.erb
- app/views/request_an_account/index.html.erb
- config/locales/en.yml
- config/locales/pages/accessibility/en.yml
- config/locales/pages/data_sharing_agreement/en.yml
- config/locales/pages/guidance/en.yml
- config/locales/pages/no_organisation/en.yml
- config/locales/pages/privacy_policy/en.yml
- config/settings.yml
- db/service_updates.yml
- docs/disaster-recovery.md
- docs/govuk_paas.md
- docs/maintenance-mode.md
- service_unavailable_page/web/public/internal/index.html
- service_unavailable_page/web/public/internal/traineeteacherportal.html
- spec/helpers/support_email_helper_spec.rb
- spec/services/bulk_update/recommendations_uploads/validate_trainee_spec.rb
This subdomain is no longer used by the DfE, and is replaced by `education.gov.uk`.
Trello: https://trello.com/c/ZKqm9Qwy/5767-remove-old-digital-becomingateacherdigitaleducationgovuk-email-address
> Remove references to the `digital.education.gov.uk` subdomain

- app/lib/apply_api/code_sets/nationalities.rb
https://trello.com/c/BkGbAb4t/5788-fix-nationalities-not-mapped-from-hesa
Maps the following HESA codes to our `british` Nationality value.
- Isle of man
- Jersey
- Guernsey
- British Indian Ocean Territory
- Falkland islands
Nothing much, just new keys added to the existing code sets.
> [5788] Map British hesa codes to British

- app/lib/hesa/parsers/itt_record.rb
- app/models/hesa/student.rb
- app/models/trainee.rb
- app/services/hesa/sync_students.rb
- config/analytics.yml
- config/analytics_blocklist.yml
- db/migrate/20230728103033_add_alternative_hesa_id_to_hesa_students.rb
- db/schema.rb
- spec/lib/hesa/parsers/itt_record_spec.rb
- spec/services/hesa/sync_students_spec.rb
https://trello.com/c/X3UIHFWw/5718-hesa-import-add-secondary-check-for-existing-trainees
Updates from HESA can cause duplicates as some providers change the hesa id for their existing trainees and if we do not have that hesa id in Register we create a new record and therefore a duplicate.
This work is to add a secondary checks to be performed where a `hesa_id` is not found in trainees table.
- Adds some secondary checks for a record using the `previous_hesa_id` or biographic information before deciding to create a new one
- Moves the `previous_hesa_id` field introduced via https://github.com/DFE-Digital/register-trainee-teachers/pull/3464/files to the `hesa_students` table as that's where it should be (doh)
- Removes the `student_instance_id` field from `hesa_students` to store `NUMHUS` …
> 5718] Tighten up hesa matching rules

- app/services/dead_jobs/base.rb
- spec/features/system_admin/dead_jobs/viewing_dead_jobs_spec.rb
- spec/support/shared_examples/dead_jobs.rb
Support personnel should be able to see how old a dead job is.
This PR adds a new column to the dead jobs table using Sidekiq's `JobRecord#enqueued_at`.
Before:
After:
Are the tests sufficient?
> [5781] Add _Days waiting_ column to dead jobs table

- .tool-versions
- README.md
- docs/alerting_and_monitoring.md
- docs/authentication.md
- docs/configuration.md
- docs/emails.md
- docs/healthcheck_and_ping_endpoints.md
- docs/machine-setup.md
- docs/setup-development.md
- docs/testing.md
https://trello.com/c/k5RIs2wr/5801-various-references-to-paas-cloudfoundry-in-the-dev-docs
- Overhauls the README layout and puts information in specific docs
- Removes references to PaaS/CF
- Removes stuff which is no longer relevant
This is a similar structure used in https://github.com/DFE-Digital/get-into-teaching-app, and https://github.com/DFE-Digital/publish-teacher-training providing some sort of consistency across the Bat repos.
> [5801] Overhaul README

- Gemfile
- Gemfile.lock
- app/services/trainees/create_timeline.rb
- config/environments/development.rb
- config/environments/test.rb
- spec/rails_helper.rb
We are currently investigating a few 1+N queries that have been flagged in Sentry. We don't have a means of detecting 1+N queries as part of our CI/build process. We've tried to implement this with `bullet` in the past but it's proved to be too noisy. This PR reinstates the `bullet` gem without detection of unused eager loads (so just focused on N+1 queries) with a view to making it a part of our CI build.
We are also looking at an alternative gem to `bullet` called `prosopite` and there is a corresponding PR here...
https://github.com/DFE-Digital/register-trainee-teachers/pull/3482
Bullet is setup here for `development` and `test` environments. In `test` it raises an error when a 1+N query is detected. In `development` the error is logged.
For now we've disabled the detection of unused …
> [5771] Reinstate Bullet gem for 1+N query detection

- app/jobs/hesa/sync_students_job.rb
- app/services/hesa/sync_students.rb
- config/settings.yml
- config/settings/production.yml
HESA are closing their old 22-23 collection API on 9th August.  We need to put in place a fallback until we’re ready to connect to their new 23-24 API (After Thursday’s testing)
Production will access the current collection via the file we have uploaded (id: 12)
> [5828] - HESA fallback

- db/data/20230809161841_add_funding_method_subjects_for_early_years_postgrad.rb
Grant funding methods should be available for _Early years ITT_ for the _early_years_postgrad_ training route as well as the _early_years_salaried_ training route.
The PR adds a data migration to create the missing funding methods if they are not already present.
I've tested this data migration manually. What is the testing best practice for these kinds of data migration?
> [5724] Add migration to creating missing funding methods

- .github/workflows/database-backup.yml
While we test the new HESA collection, it would be helpful not to overwrite the staging database every night.
> Pause staging db restore

- app/models/reports/trainee_report.rb
- app/models/reports/trainees_report.rb
Addressing exporting large number of trainees on report page issues
Fix the low hanging fruits
[Amended select then first to be just find](https://github.com/DFE-Digital/register-trainee-teachers/commit/0f21069be98bb82c90da29e2306455286e349c36) 
It's an array Just find the first rather then select the filter then return first.
[[5782] Added additional caching for trainee_allocation_subject](https://github.com/DFE-Digital/register-trainee-teachers/commit/22952f13c1eef637b582d347f032cd7efa375612)
[[5782] Added additional caching for calculated_subject](https://github.com/DFE-Digital/register-trainee-teachers/commit/1b3ba7f725a9d5cc6e1fffb5367ad61f9e033d66)
Lookup for the sake of lookup, once looked at there is no point in second journey to database calls. Cache it for the day so any other …
> [5782] Addressing exporting large number of trainees on report page issues

- .github/workflows/build-and-deploy.yml
Disables automatic deploys to staging when merging to main. This is until we have finished testing the HESA integration for the 2023-24 academic year mappings.
> [5717] - disable deploys to staging whilst HESA testing

- db/scripts/sanitise.sql
Logging into staging will fail if the user account has a OTP secret record which can’t be decrypted.
staging should either:
- have the same ACTIVE_RECORD_ENCRYPTION keys as prod so user login doesn’t break
- OR we amend the copy from PROD => STAGING sql copy to NULL `users.otp_secret`
`NULL`'s `users.otp_secret` in the sanitise script. a new OTP secret is generated if/when we need to test/use OTP sign-in on staging.
> [5839] - NULL otp_secret when copying sanitised-prod => staging

- app/services/exports/funding_trainee_summary_data.rb
- app/services/trainees/create_from_csv_row.rb
- config/locales/en.yml
- spec/factories/funding/trainee_summary_rows.rb
- spec/fixtures/files/bulk_update/recommendations_upload/complete.csv
- spec/fixtures/files/bulk_update/recommendations_upload/date_in_future.csv
- spec/fixtures/files/bulk_update/recommendations_upload/missing_date.csv
- spec/fixtures/files/bulk_update/recommendations_upload/missing_do_not_edit_row.csv
- spec/fixtures/files/bulk_update/recommendations_upload/missing_required_header.csv
- spec/fixtures/files/bulk_update/recommendations_upload/no_date.csv
- spec/fixtures/files/bulk_update/recommendations_upload/with_invalid_trn.csv
Rename early years routes
Amended `Early years (undergrad)` to `Early years undergraduate`
Amended `Early years (salaried)` to `Early years graduate employment based`
Amended `Early years (postgrad)` to `Early years graduate entry`
Amended `Early years (assessment only)` to `Early years assessment only`
> [5869] Rename early years routes

- app/components/export_with_count_button/view.html.erb
- app/components/export_with_count_button/view.rb
- app/controllers/reports_controller.rb
- app/helpers/exports_helper.rb
- app/views/reports/itt_new_starter_data_sign_off.html.erb
- spec/components/export_with_count_button/view_preview.rb
- spec/components/export_with_count_button/view_spec.rb
https://trello.com/c/vyMXhAno/5871-show-count-of-trainees-on-report-page
The reports page somewhat assumes providers will have trainees to export - but that may not always be the case.
To help with this, show a count of trainees that will be exported in the export button.
- Add view component to contain logic for showing count/fallback text
A bit fiddly to review as it's behind some conditional logic. 
[This is the page (login with Annie Bell) ](https://register-pr-3514.test.teacherservices.cloud/reports/itt-new-starter-data-sign-off)to check which should show the count of some trainees. With no trainees it'll look like this:
> [5871] Add export button component

- app/models/trainee.rb
- app/services/degrees/create_from_dttp_placement_assignment.rb
- app/services/degrees/map_from_apply.rb
- app/services/degrees/map_from_dttp.rb
- config/analytics.yml
- spec/components/contact_details/view_spec.rb
- spec/components/pages/trainees/check_details/view_preview.rb
- spec/factories/trainees.rb
- spec/models/trainee_spec.rb
- spec/services/degrees/map_from_apply_spec.rb
- spec/services/degrees/map_from_dttp_spec.rb
We are removing address fields from Register. We don't need them any longer.
This PR https://github.com/DFE-Digital/register-trainee-teachers/pull/3504 has done the bulk of the work to remove the UI and various API interactions. We now need to remove the columns from the database and this PR is the first of two steps to do that (safely).
NOTE THAT THIS PR CANNOT BE MERGED UNTIL https://github.com/DFE-Digital/register-trainee-teachers/pull/3504 IS MERGED AND DEPLOYED.
* Add address attributes to the list of `ignored_attributes`.
* Remove address attributes from `analytics.yml` (only 3 of them were present because I guess `address_line_one` etc. is PII).
Is there anything more to do here? …
> [5864] Delete addresses we hold in register (part 1/2)

- app/models/trainee.rb
- db/migrate/20230818092637_drop_trainee_address_columns.rb
- db/schema.rb
Two earlier PRs (https://github.com/DFE-Digital/register-trainee-teachers/pull/3516 and https://github.com/DFE-Digital/register-trainee-teachers/pull/3504) cleaned up references to trainee address fields in Register. This PR is the final part - it just drops the 6 address columns in the `trainees` database table.
Drop the following columns using safe migrations:
- `address_line_one`
- `address_line_two`
- `town_city`
- `postcode`
- `locale_code`
- `international_address`
- Is there anything missing?
> [5864] Delete addresses we hold in register schema change part 2/2

- app/models/reports/trainee_report.rb
- db/data/20230822072153_correct_course_allocation_subject_for_non_draft.rb
- spec/factories/trainees.rb
https://trello.com/c/xlzSIlfP/5782-spike-test-exporting-large-number-of-trainees-on-report-page
The current reporting class does some unnecessary calculation of the allocation subject when it's already available via the trainee's `course_allocation_subject` (reference PR is here https://github.com/DFE-Digital/register-trainee-teachers/pull/2250)
- Switch out redundant code to make use of `course_allocation_subject`
- Data migration to correct `course_allocation_subject` on non draft trainees who have it missing (around 92 in prod)
- Fix `for_export` trainee factory as it was not correctly representing the final state of the trainee for an export in tests
This PR is one part of a two step improvement to this area. This optimises the underlying query but needs to be combined with the …
> [5782] Improve TraineeReport performance

- app/models/reports/trainee_report.rb
- app/models/reports/trainees_report.rb
- spec/models/reports/trainee_report_spec.rb
https://trello.com/c/mlYZrxEE/5082-add-to-trainee-exports-if-trainee-is-incomplete-complete
Adds a new column for `is_complete` to the trainee export.
- Expose `submission_ready` from the trainee to the report class
You can check this with the example data in QA. Make sure to use sweet old Annie Bell
https://register-pr-3532.test.teacherservices.cloud/reports/performance-profiles
> [5082] Add complete? to trainee report

- app/controllers/personas_controller.rb
- app/controllers/reports_controller.rb
- app/models/persona.rb
- app/services/exports/report_csv_enumerator_service.rb
- spec/controllers/reports_controller_spec.rb
- spec/services/exports/report_csv_enumerator_service_spec.rb
Return csv as a stream
Amended to return csv as a stream
The end points `performance_profiles` &`itt_new_starter_data_sign_off` now support streaming.
Log in as a persona and head to https://register-pr-3495.test.teacherservices.cloud/reports/performance-profiles, the available persona are from the sanitised backup which will reflect a closer real life experience. Click on the `Export` button should trigger the download without any delay.
All the current one does the calculation and generation before the file can be saved.
> [5782] Amended so that the csv is downloaded as a stream

- app/controllers/guidance_controller.rb
- app/views/guidance/show.html.erb
The wording for the sign-off link(s) was made dynamic in #3496 and static in #3535 this reverts it back to being dynamic base the period determined in `app/services/determine_sign_off_period.rb`
> Refactor sign off wording

- app/lib/dqt/params/trn_request.rb
https://trello.com/c/jbTLFoT1/5858-handle-teach-first-programme-type-when-submitting-data-to-dqt
- Uses the new HPITT specific DQT programme type sourced from https://qualified-teachers-api-preprod.london.cloudapps.digital/swagger/v2.json (search for `IttProgrammeType`)
Could be tested on staging by sending a HPITT trainee to DQT pre-prod (but will need to be done separately outside of this PR or deploy directly to staging)
> [5858] Handle Teach First programme type when submitting data to DQT

- app/jobs/apply_api/import_application_job.rb
- app/jobs/apply_api/import_applications_job.rb
- spec/jobs/apply_api/import_application_job_spec.rb
- spec/jobs/apply_api/import_applications_job_spec.rb
https://trello.com/c/apNQUzHG/5848-improve-reliability-of-traineescreatefromapplyjob
We have a job that runs nightly and loops through importable ApplyApplication-ses and creates trainees from them. Currently if one creation fails the job halts and starts to retry. If there are 300 to import and the first one fails, 299 get stuck. 
This also makes it not immediately obvious which application is failing.
Fans out the `ImportApplicationsJob` into smaller individual jobs for each application so it's consistent with other import jobs.
- Follow this https://github.com/DFE-Digital/register-trainee-teachers/blob/main/docs/setup-development.md#running-apply-application-import-against-example-data (get an auth key from apply sandbox console or dm me)
- Run instructions in the example
- Check …
> [5848] Improve reliability of Trainees::CreateFromApplyJob

- app/components/collapsed_section/view.html.erb
- app/components/sections/view.rb
- app/forms/submissions/trn_validator.rb
- app/views/trainees/check_details/show.html.erb
- spec/controllers/trainees/personal_details_controller_spec.rb
- spec/controllers/trainees/training_details_controller_spec.rb
- spec/factories/trainees.rb
- spec/features/trainee_actions/submit_for_trn_spec.rb
- spec/forms/diversities/form_validator_spec.rb
- spec/forms/submissions/trn_validator_spec.rb
Error summary links to the section to be completed
Amended the error summary links to the section to be completed
https://register-pr-3544.test.teacherservices.cloud/view_components/pages/trainees/check_details/view
Create a trainee and do not completely fill it in then attempt to submit it for `Register trainee and request for TRN`
> [3292] Error summary on check record page should link to sections to complete

- app/jobs/dqt/base_job.rb
- app/jobs/dqt/recommend_for_award_job.rb
- app/jobs/dqt/register_for_trn_job.rb
- app/jobs/dqt/retrieve_trn_job.rb
- app/jobs/dqt/sync_states_batch_job.rb
- app/jobs/dqt/sync_states_job.rb
- app/jobs/dqt/sync_teacher_job.rb
- app/jobs/dqt/sync_teachers_batch_job.rb
- app/jobs/dqt/sync_teachers_job.rb
- app/jobs/dqt/sync_trainee_state_job.rb
- app/jobs/dqt/sync_trainee_trn_job.rb
- app/jobs/dqt/update_trainee_job.rb
- app/jobs/dqt/withdraw_trainee_job.rb
There are a number of trainees that are stuck in the `recommended_for_award` status. Normally this status is short-lived and the trainee transitions to `awarded` as soon as a successful call to DQT is made to obtain an award date. However things sometimes go wrong and after repeated attempts the job ends up in the dead queue at which point it becomes visible in the sys admin interface.
At the moment the job that controls the `recommended_for_award` to `awarded` transition will retry 25 times (over 3 weeks). A much shorter time to failure is needed because we don't flag jobs as problematic until they hit the dead queue.
This PR adds a base class that declares a default of 10 retries (about 4 hours elapsed time). This should mean that problematic DQT jobs appear in the system admin …
> Throttle DQT Sidekiq job retries

- app/models/provider.rb
- app/views/system_admin/providers/edit.html.erb
- app/views/system_admin/providers/new.html.erb
- spec/factories/dttp/trainees.rb
- spec/factories/providers.rb
- spec/features/system_admin/providers/creating_a_new_provider_spec.rb
- spec/models/provider_spec.rb
- spec/services/trainees/create_from_dttp_spec.rb
DTTP ID
Amended provider dttp id to be optional
Amended form to state optional
For support agent both the add & edit provider page
Te fields that is optional is now called out.
ie
From `DTTP ID` to `DTTP ID (optional)`
From `Provider code` to `Provider code (optional)`
> [5567] Make dttpid field optional in add provider UI

- app/services/degrees/create_from_csv_row.rb
- app/services/trainees/create_from_csv_row.rb
when we import from HESA and update a trainee, we clear their degrees before re-creating them:
```ruby
def create_degrees!
trainee.transaction do
trainee.degrees.destroy_all
hesa_degrees.each do |hesa_degree|
next unless importable?(hesa_degree)
subject = DfEReference::DegreesQuery.find_subject(hecos_code: hesa_degree[:subject_one])
degree = trainee.degrees.new(
subject: subject&.name,
subject_uuid: subject&.id,
graduation_year: hesa_degree[:graduation_date]&.to_date&.year,
)
set_country_specific_attributes(degree, hesa_degree)
set_grade_attributes(degree, hesa_degree)
degree.save!
end
end
end
```
This isn't the case in the `app/services/degrees/create_from_csv_row.rb`.
This matches the behaviour in the HESA import service to get the goldsmiths trainee data in (which will have been …
> [5830] - clear degrees when importing from CSV

- app/components/record_details/view.rb
- config/locales/en.yml
- spec/components/record_details/view_spec.rb
- spec/features/form_sections/teacher_training_data/edit_trainee_start_date_spec.rb
- spec/features/form_sections/teacher_training_data/edit_trainee_start_status_spec.rb
- spec/rails_helper.rb
- spec/views/trainees/show.html.erb_spec.rb
We want the trainee record to be a more complete picture of the trainee that has information contained in the export.
Add HESA ID, start year, end year to trainee view
https://trello.com/c/KQAKFQwY/5474-s-add-metadata-fields-to-trainee-record
Check review app
> Add HESA ID, start year and end year to trainee record

- app/services/determine_sign_off_period.rb
- config/settings.yml
- spec/services/determine_sign_off_period_spec.rb
_As we iron out final preparations for the ITT census sign-off period, we realise that it would be helpful to keep the report page showing the ITT census related material for a little longer than originally specified [in this ticket](https://trello.com/c/ERWgb7NB/5787-switch-between-alternative-versions-of-reports-and-guidance-for-census-and-performance-profiles-outside-sign-off-periods) Change ITT census period end date from 31st October to 7th November. This gives providers a 7 calendar day grace period to get their data signed off._
* This refactors the `app/services/determine_sign_off_period.rb` to use more specific dates
* this also adds in a manual override for the sign off period which is [requested in this ticket](https://trello.com/c/QbGosKFz/5988-check-with-sarah-two-versions-of- …
> [5962] Extend census period + manual period override

- app/services/form_store.rb
We use Redis to cache data across multi-page forms. There is a potential for interference between the caches used by different parallel testing environments. This is because the same Redis DB is used across all tests and we don't partition the keys by environment.
This PR simply used the `TEST_ENV_NUMBER` environment variable if it's present to partition Redis keys. In theory this should prevent any keys being overwritten by a parallel environment.
- This PR assumes that the only source of trouble is in the `FormStore`. Is this reasonable or can we use completely different Redis environments to create a more generic solution?
> Include parallel test env number in Redis keys

- spec/components/personal_details/view_spec.rb
- spec/features/system_admin/pending_trns/pending_trns_spec.rb
There is a slim chance these hard-coded ids could cause problems due to clashes with PostgreSQL auto-incrementing `id's. 
Remove hard-coded `Trainee#id` values in tests
Any downsides?
> [5953] Remove hard-coded `Trainee#id` values in tests

- app/controllers/system_admin/pending_awards_controller.rb
- app/helpers/sidekiq_jobs_helper.rb
- app/services/dqt/base_find_jobs.rb
- app/services/dqt/find_dead_jobs.rb
- app/services/dqt/find_retry_jobs.rb
- app/views/system_admin/_tab_nav.html.erb
- app/views/system_admin/pending_awards/index.html.erb
- config/routes/system_admin_routes.rb
- spec/features/system_admin/pending_awards/pending_awards_spec.rb
- spec/helpers/sidekiq_jobs_helper_spec.rb
There are a number of trainees that have been in the `recommended_for_award` status for longer than expected. When this happens they are not always visible to the support and DQT teams. 
This PR adds a `Pending awards` tab to the support interface that simply lists all those trainees that are in the `recommended_for_award` status together with information about any associated Sidekiq jobs that may have failed.
In future we may wish to add better diagnostics to this feature, e.g. a history of DQT API responses including error messages.
Are the tests sufficient?
> [5857] Pending award tab in the support interface

- config/routes/system_admin_routes.rb
- spec/features/system_admin/pending_awards/pending_awards_spec.rb
- spec/features/system_admin/pending_trns/pending_trns_spec.rb
Non-sys-admins don't see the menu items for any of the sys-admin pages but can navigate to them. This shouldn't happen.
Add a constraint at the route level to authorise all sys-admin requests.
Are there any loopholes we need to keep open. Currently there are 70 odd sys-admins so I'm guess most people that need access already have it.
> Enforce sys-admin constraint on all sys-admin routes

- app/views/guidance/census_sign_off.md
- app/views/guidance/performance_profiles.html.erb
- app/views/request_an_account/index.html.erb
- config/locales/en.yml
- config/locales/pages/accessibility/en.yml
- config/locales/pages/data_sharing_agreement/en.yml
- config/locales/pages/guidance/en.yml
- config/locales/pages/no_organisation/en.yml
- config/locales/pages/privacy_policy/en.yml
- config/settings.yml
- db/service_updates.yml
- service_unavailable_page/web/public/internal/index.html
- service_unavailable_page/web/public/internal/traineeteacherportal.html
- spec/helpers/support_email_helper_spec.rb
- spec/services/bulk_update/recommendations_uploads/validate_trainee_spec.rb
Support have identified an issue with the email redirect and have requested that all references to ‘becomingateacher@education.gov.uk’ be updated to ‘becoming.ateacher@education.gov.uk’
Change email links from ‘becomingateacher@education.gov.uk’ to ‘becoming.ateacher@education.gov.uk’
> Fix incorrect support email address

- .rubocop.yml
- spec/support/features/lead_and_employing_school_steps.rb
Rubocop extension not loaded
We are now loading
- rubocop-capybara
- rubocop-factory_bot
It no longer print out
```
spec/support/features/lead_and_employing_school_steps.rb: RSpec/Capybara/SpecificActions has the wrong namespace - should be Capybara
1886 files inspected, no offenses detected
The following RuboCop extension libraries are installed but not loaded in config:
* rubocop-capybara
* rubocop-factory_bot
You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
AllCops:
SuggestExtensions: false
```
> [5949] Rubocop extension not loaded

- db/scripts/sanitise.sql
Since they [don't exist any more](https://github.com/DFE-Digital/register-trainee-teachers/commit/b73ea89af718c5063f8ce5d831066bdf9c0874a0).
https://trello.com/c/aiKYi9bi/6036-db-anonymisation-isnt-working
We removed address fields from Trainee, but the sanitise script is still trying to back them up (and anonymise them). Hence sanitisation is not working.
Update sanitise script such that it doesn't update non-existent fields
Does sanitisation work?
> Remove address fields from trainee sanitisation

- app/jobs/trainees/create_from_application_job.rb
- app/jobs/trainees/create_from_apply_job.rb
- spec/jobs/trainees/create_trainees_from_apply_job_spec.rb
This sort of [sentry error ](https://dfe-teacher-services.sentry.io/issues/4113839544/?environment=production&project=5552118&query=is%3Aarchived&referrer=issue-stream&stream_index=2) is quite difficult to diagnose (I've spent ages on a similar one in the past). 
`CreateFromApplyJob` is setup to process applications in one big job and rescues any errors for each. The problem is some of the important context (eg the application being processed so we can track down the issue) isn't surfaced in Sentry. 
Like this PR https://github.com/DFE-Digital/register-trainee-teachers/pull/3541, this fans out the job so it's consistent with the approach we use in other areas. When an error occurs, we get the application context to make debugging a little easier:
You can kick off the job locally with some …
> [6009] Fan out CreateFromApplyJob

- db/data/20230913164507_backfill_veteran_teaching_undergraduate_bursary_initiative.rb
Trainees imported from HESA with bursary level 'C' should be allocated the 'Veteran Teaching Undergraduate Bursary' training initiative.
Data migration to correct the training initiative for trainees imported from HESA with the matching bursary level.
Does this make sense?
> [6012] Backfill 'Veteran Teaching Undergraduate Bursary' initiative

- app/services/trainees/create_from_hesa.rb
- spec/services/trainees/create_from_hesa_spec.rb
When bursary_level is set to 'C' by HESA we should set the maps the trainee to the veteran teaching undergraduate bursary training initiative.
This PR just updates the HESA mapping logic. There is a separate PR to backfill historic records - https://github.com/DFE-Digital/register-trainee-teachers/pull/3601
Is this the right place to add this logic?
> [6012] Map veteran bursary correctly on HESA import

- app/models/reports/trainee_report.rb
- spec/models/reports/trainee_report_spec.rb
HESA increased the length of the HESAID from 13 digit to 17 digits. This is a length that when it is exported to Excel, as a number, it is corrupted, and the last 2 digits of the HESAID are lost.
This means when HEIs are trying to check their records, in Excel, they can't match correctly on HESAIDs, and it's much more difficult for them.
https://trello.com/c/ZKRDPkJu/6033-check-hesaid-is-exported-correctly-if-not-fix
Wrap the HESA ID in single quotes so that Excel doesn't get ideas above its station.
> Export HESA ID in a format that Excel will not convert to scientific notation

- app/models/upload.rb
- app/validators/file_validator.rb
- config/locales/en.yml
- spec/factories/uploads.rb
- spec/features/system_admin/uploads/create_spec.rb
- spec/features/system_admin/uploads/delete_spec.rb
- spec/fixtures/files/test.csv
- spec/models/upload_spec.rb
https://trello.com/c/k6OnoVN1/6031-insecure-file-upload-medium
- Add some basic validation to file types in uploads
- Head to system admin, uploads and try to upload some funny files
- Have just allowed the file types we seem to use this area for (backfilling etc) 
- Follow on ticket to do additional virus scanning with Azure defender on uploads (will be useful for the zip formats)
> [6031] Add file validations to uploads

- app/controllers/funding/base_funding_controller.rb
- app/controllers/funding/payment_schedules_controller.rb
- app/controllers/funding_controller.rb
- app/controllers/system_admin/funding/payment_schedules_controller.rb
- app/controllers/system_admin/funding/trainee_summaries_controller.rb
- app/controllers/system_admin/funding_controller.rb
- app/view_objects/funding/navigation_view.rb
- app/views/funding/_navigation.html.erb
- app/views/funding/show.html.erb
- config/locales/en.yml
- config/routes.rb
- config/routes/system_admin_routes.rb
- spec/features/funding/show_spec.rb
- spec/support/features/page_helpers.rb
- spec/support/page_objects/funding/show.rb
Users should be able to view and download historic funding - at least for the year prior to the current year.
Suggested changes:
* Funding pages rendered on /funding/YYYY/page-name
* Funding link in nav defaults to linking to the current year
* The breadcrumb on each funding page links to a funding years index
* The year index lists years where we have funding information available (expected to be at least 3)
Clicking on the link takes the user to the relevant year's funding pages.
* adds funding index page `/funding`
* redirects to latest funding year when clicking on the nav bar funding link
* splits the two funding types on the index page Trainee Summary, Payment Schedule
Ideally should be tested in production data
> [5957] Let users view and download historic funding information

- config/settings/productiondata.yml
- config/settings/staging.yml
- spec/components/record_details/view_spec.rb
We need to enable the `changed_accredited_provider` feature on `productiondata` to allow product review.
Enable the `changed_accredited_provider` feature flag on `productiondata` and `staging`.
We don't want this going live on `production` yet.
> [6029] Enable `change_accredited_provider` FF on proddata

- app/components/record_details/view.rb
- spec/components/record_details/view_spec.rb
There was a discrepancy between the values we show for end year in the list view and details view, as described here: https://trello.com/c/vpnqUnbc/6061-end-year-displayed-on-summary-list-view-of-trainees-shows-incorrect-academic-year
Always base start year and end year on the `start_academic_cycle` and `end_academic_cycle` fields, rather than `estimated_end_date`, which we should probably get rid of.
Look at the trainees index and see if end year matches in the list and details views.
> Display trainee start and end years correctly on the summary list view

- app/controllers/system_admin/accredited_providers/confirmations_controller.rb
- app/controllers/system_admin/accredited_providers/providers_controller.rb
- app/controllers/system_admin/accredited_providers/reasons_controller.rb
- app/views/system_admin/accredited_providers/confirmations/show.html.erb
- app/views/system_admin/accredited_providers/providers/edit.html.erb
- app/views/system_admin/accredited_providers/reasons/edit.html.erb
- config/environments/development.rb
- config/settings/development.yml
- config/settings/review.yml
https://trello.com/c/GRhphnFr/6028-change-accredited-provider-cancel-flow
Builds on from https://github.com/DFE-Digital/register-trainee-teachers/pull/3609 
- Adds cancel links and page titles to AP flow
- Turns AP flag on in development settings
- Click each cancel link and check it goes back to the correct path (the record page)
- Assert page titles are show correctly on normal and error states
> [6028] Cancel links to change AP flow

- app/controllers/system_admin/accredited_providers/confirmations_controller.rb
- app/controllers/system_admin/accredited_providers/providers_controller.rb
- app/controllers/system_admin/accredited_providers/reasons_controller.rb
- app/views/system_admin/accredited_providers/confirmations/show.html.erb
- config/settings/development.yml
- spec/features/system_admin/accredited_providers/change_accredited_provider_spec.rb
https://trello.com/c/7ORLVhzH/6027-change-the-confirmation-change-link
- Adds change links to the AP flow confirm
ation page to be able to go back and update answers
- Wire up page tracker to return users to the correct page
- Visit review app and sign in as support admin
- Head to a trainee and complete the AP flow
- Go back and update answers
> [6027] Implement confirm page change links

- app/helpers/course_details_helper.rb
- app/views/system_admin/accredited_providers/providers/edit.html.erb
- spec/helpers/course_details_helper_spec.rb
We want to make it easy for administrators to find providers when select a new accredited provider for a trainee.
This PR progressively enhances the original `select` element (dropdown) using the accessible autocomplete component.
- The user can search (autocomplete) based on the provider name, code or UKPRN.
- Full details including the name, code or UKPRN are included in the dropdown portion of the autocomplete.
Initial state:
Dropdown open:
If the user has disabled JavaScript the original `select` element is displayed and the system continues to function.
Is the UX right?
This can be reused on the provider list page in the Support interface (there is a ticket - https://trello.com/c/b2iVds7q/641-support-add-autocomplete-to-search-for-providers)
NB: Please notify the #twd_data_insights …
> [6065] Autocomplete for changing accredited provider

- app/views/system_admin/accredited_providers/confirmations/show.html.erb
- config/locales/en.yml
- spec/components/record_details/view_spec.rb
- spec/features/system_admin/accredited_providers/change_accredited_provider_spec.rb
There were a couple of mistakes in the content that this PR aims to correct.
Any other mistakes?
> [6029] Content corrections 'Accredited' not 'Accrediting' provider

- app/controllers/trainees_controller.rb
- app/lib/page_tracker.rb
- app/views/system_admin/accredited_providers/confirmations/show.html.erb
- app/views/system_admin/accredited_providers/providers/edit.html.erb
- app/views/system_admin/accredited_providers/reasons/edit.html.erb
- spec/features/system_admin/accredited_providers/change_accredited_provider_spec.rb
https://trello.com/c/dPLLOzqJ/6123-change-ap-flow-back-links
The page tracker thing has always been a bit funny to rely on so I think key is to be a bit more explicit when using it. Also worth noting that I've made one of the original methods public to help clearing out the session when needed (I think we should probably be doing that so every section begins with a fresh state).
- Add back links to AP flow
- Go to review app and complete the flow to confirm page, go back to sections and hit the back link. Check it behaves correctly.
> [6123] Add back links to AP flow

- config/analytics.yml
- config/analytics_blocklist.yml
`application_choice_id` seems redundant for data insights team.
see: https://trello.com/c/23GqB007/6041-applicationchoiceid-all-showing-as-rugged-abacus-218110dataformapplyapplicationslatestregister and https://trello.com/c/WEIHSeYB/6128-applicationchoiceid-all-showing-as-rugged-abacus-218110dataformapplyapplicationslatestregister
> [6128] - remove application_choice_id from analytics

- .github/workflows/database-backup.yml
Daily database backup/restore is failing in the create sanitised db backup step as it's running out of disk space  
Add compression to sanitise backup pg_dump
Check workflow syntax
> Compress sanitised db backup to use less space

- app/components/timeline/view.html.erb
- app/components/timeline/view.rb
- app/forms/system_admin/change_accredited_provider_form.rb
- app/helpers/timeline_helper.rb
- app/services/trainees/create_timeline_events.rb
- config/locales/en.yml
- spec/forms/system_admin/change_accredited_provider_form_spec.rb
- spec/helpers/timeline_helper_spec.rb
- spec/services/trainees/create_timeline_events_spec.rb
When a sys-admin updates a trainee's accredited provider we want to see that change highlighted in the timeline with relevant details.
Update the timeline to show the old and new provider name and display the reason for changing providers.
- Does the markup change make sense? Is there a better way?
- Have I missed any useful content?
- I've put a question on the ticket https://trello.com/c/mhvxSOSo/6131-change-accredited-provider-update-timeline about whether we should show the original provider name and code too.
> [6131] Change accredited provider update timeline

- app/forms/system_admin/change_accredited_provider_form.rb
- spec/features/system_admin/accredited_providers/change_accredited_provider_spec.rb
We need to notify DQT because it records the provider against a teacher's training record.
Call the appropriate service to make the necessary API call.
Is there more to it than this?
> [6177] Ensure that DQT is notified about provider changes

- app/services/teacher_training_api/import_course.rb
- spec/services/teacher_training_api/import_course_spec.rb
These are now coming through from Publish, so we need to handle them.
Related commit in Publish: https://github.com/DFE-Digital/publish-teacher-training/commit/6171524194a38a413615ffe5de5accd835779e67
Trello: https://trello.com/c/oP5Ooc90/6179-handle-scittsalariedprogramme-and-highereducationsalariedprogramme-training-routes
Add scitt_salaried_programme and higher_education_salaried_programme training routes to the course importer.
> Add scitt_salaried_programme and higher_education_salaried_programme training routes

- .github/workflows/database-backup.yml
Database backup/restore still failing with space issues after adding compression
It's currently failing during the local creatdb as there is only 7G available
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/root       87204404 79796528   7391492  92% /
- Split steps to make it clearer where it's failing
- add step to remove unused files from the github runner
check code
see run https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/6411121899/job/17405878447
> Fix space issues for database backup

- db/service_updates.yml
As per [Trello](https://trello.com/c/X30LKYzy/6139-notify-providers-to-let-them-know-they-can-now-access-historic-funding-information-in-register)
> Add historic funding information service update

- app/jobs/malware_scanning_job.rb
- spec/jobs/malware_scan_job_spec.rb
- spec/jobs/malware_scanning_job_spec.rb
the malware background job was [miscalling the scan job](https://dfe-teacher-services.sentry.io/issues/4527743234/events/bd9946479bac419a9af4f788bc79ffb0/?project=5552118) in `app/jobs/malware_scanning_job.rb`
* corrects the `upload` to `upload_id`
* adds some specs for regression
> [6127] - fix job calls, add specs.

- app/controllers/system_admin/pending_trns/base_controller.rb
- app/controllers/system_admin/pending_trns/request_trns_controller.rb
- app/controllers/system_admin/pending_trns/retrieve_trns_controller.rb
- spec/features/system_admin/pending_trns/pending_trns_spec.rb
* `/system-admin/pending_trns` allows system admins to check and resubmit for TRNS
* sometimes trainees will be in the list who have been submitted for TRN but who's TRN request has been deleted (probably manually)
* this will result in an [exception being thrown](https://dfe-teacher-services.sentry.io/issues/4538254525/?environment=production&project=5552118&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=3) when submitting or checking for a TRN
* redirects back to the pending TRN page if a trainee has no TRN request when _checking_ for a TRN
* no longer throws exception when submitting for a _new_ TRN request (by guarding the `.destroy!`)
* rather than filter the list of trainees to exclude those without we still list the trainee and opt to show the warning …
> [6214] - check for trn request when using pending trn service

- app/view_objects/home_view.rb
- app/views/landing_page/home.html.erb
- config/locales/en.yml
These appear to be causing significant database load issues.
https://trello.com/c/uidKG528/6222-temporarily-remove-counts-from-register-home-page
Hold your nose.
> Temporarily remove counts from home page

- app/jobs/malware_scanning_job.rb
With no uploads to scan, we keep getting [this error in sentry](https://dfe-teacher-services.sentry.io/issues/4535555353/?environment=staging&project=5552118&query=is%3Aarchived&referrer=issue-stream&statsPeriod=24h&stream_index=0)
don't `.find_each` unless we have a set to loop over.
> [xxxx] don't .find_each unless upload records exist.

- terraform/aks/workspace-variables/staging_aks.tfvars.json
Staging postgres db is only a burstable B_Standard_B1ms and has cpu issues with the staging workload
Increase from B_Standard_B1ms to GP_Standard_D2ds_v4
Check db is upgraded during the deploy workflow.
module.postgres.azurerm_postgresql_flexible_server.main[0] will be updated in-place
> Increase staging postgres db size

- app/view_objects/home_view.rb
- app/views/landing_page/home.html.erb
- config/locales/en.yml
- spec/view_objects/home_view_spec.rb
We have narrowed down the performance problem to a single query, therefore we can restore trainee numbers to the landing page.
https://trello.com/c/uidKG528/6222-temporarily-remove-counts-from-register-home-page
Revert 3c80b6ccec2a6057293e41d4296decc862c9ae7b
Just hide the incomplete badge, as it's this specific query that's causing a database performance problem.
> Restore most landing page counts

- app/view_objects/home_view.rb
- spec/view_objects/home_view_spec.rb
We've [fixed](https://github.com/DFE-Digital/register-trainee-teachers/pull/3677) the trainee incomplete scope that was causing the database CPU to max out.
Put the incomplete badge back.
> Restore incomplete count badge on landing page

- app/components/funding/view.rb
- app/lib/dttp/code_sets/bursary_details.rb
- app/lib/dttp/mappable.rb
- app/lib/hesa/code_sets/bursary_levels.rb
- app/services/trainees/map_funding_from_dttp_entity_id.rb
- config/locales/en.yml
- spec/components/funding/view_spec.rb
- spec/factories/dttp/api_placement_assignment.rb
- spec/factories/hesa/student.rb
https://trello.com/c/6nIlr6Kn/6164-show-hesa-funding-information-on-the-funding-summary
- Expose two new rows in the funding card for hesa records to show the hesa values for bursary eligibility and level
- Update hesa bursary constants
- Remove some deprecated code in these classes no longer in use
- This is a bit fiddly to check but might be best to be deployed in `productiondata` and looking at hesa specific trainees
- The bursary level row will only show for hesa records imported in the current collection. Currently the logic does not support showing the info for older records. We'll need to do additional thinking around behaviour and logic if this is required
> [6164] Render hesa values for bursary in funding card

- app/services/trainees/create_from_hesa.rb
Sometimes we get a Hesa import which has failed to create a trainee due to some validation error, eg [like this one](https://dfe-teacher-services.sentry.io/issues/4553700850/?environment=production&project=5552118&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=1). In this scenario, we need to get the provider to double check the information on the hesa record to correct if needed. At the moment, when this error is raised in Sentry there is no additional information to help identify the exact hesa trainee the provider might need to update. 
This PR surfaces the hesa id so we can track down the record causing issues in the import.
> [626] Surface hesa id for easier debugging

- app/controllers/trainees/base_controller.rb
- app/controllers/trainees/placements_controller.rb
- app/forms/placement_form.rb
- app/views/trainees/placements/_form.html.erb
- app/views/trainees/placements/new.html.erb
- app/views/trainees/show.html.erb
- config/routes.rb
- config/settings/development.yml
- config/settings/review.yml
- spec/features/trainee_actions/adding_trainee_placements_spec.rb
- spec/forms/placement_form_spec.rb
This PR is a (small) part of the trainee placements epic that gives providers the ability to add placement details to trainee records.
This PR attempts to add just enough to show the basic UI. Persistence and other logic will be in a follow-up PR/ticket.
- New route `POST /trainees/:trainee_id/placements/new`. Returns 404 unless `trainee_placement` is active.
- New controller `Trainees::PlacementsController` (only a `new` action for now)
- New form object `PlacementForm`
- New view for the controller action
- Feature spec for the _Add placement_ flow (will need to be completed when backend logic etc. is added)
https://trello.com/c/LeTbJtIt/6243-add-edit-a-placement-page-ui
- Are the tests sufficient?
- Does this fit the overall architecture for the epic? …
> [6243] Add new placement form

- app/components/placements/view.html.erb
- app/components/placements/view.rb
- app/controllers/trainees/confirm_details_controller.rb
- app/forms/placements_form.rb
- app/helpers/confirm_details_helper.rb
- app/models/progress.rb
- config/locales/en.yml
- config/routes.rb
- spec/components/placements/view_preview.rb
- spec/components/placements/view_spec.rb
- spec/forms/placements_form_spec.rb
Confirm placement details page UI
Bare minimum to show the page
There is/will be  a follow up PR to flesh this out the reminders, this PR is only concerned with UI only
https://register-pr-3684.test.teacherservices.cloud/trainees/W67bCLabETnsnzpGgHtYeW3R/placements/confirm
https://register-pr-3684.test.teacherservices.cloud/view_components/placements/view
Nope 
> [6241] Confirm placement details page UI

- spec/features/form_sections/teacher_training_data/placements/confirm_spec.rb
`I have completed this section`
Added specs to cover off the state
The perks of using `Trainees::ConfirmDetailsController` is that it covers the well trodden paths.
Nothing really to see other then verification that it works as expected.
Nope
> [6221] Added specs to cover off the state

- app/forms/placement_form.rb
- app/views/trainees/placements/_form.html.erb
- app/views/trainees/placements/new.html.erb
This PR is part of the Placements EPIC that will give providers the ability to add and edit placement details for each trainee record.
https://trello.com/c/Ma5Qo7K2/6236-implement-the-typeahead-box
Add an autocomplete field to the _Create placement_ form. This field uses existing front-end logic to populate a list of matching schools names together with their address and URN.
Also wrap the existing fields (used to enter details for a new school) in a summary component so that they are not visible initially.
Is there anything else to do at this point? Backend logic will be implemented in a separate ticket & PR.
> [6236] Add school autocomplete on placement form

- app/models/provider.rb
- app/views/trainees/training_routes/_form_fields.html.erb
- config/initializers/personas.rb
- spec/components/record_details/view_preview.rb
- spec/components/training_details/view_preview.rb
- spec/factories/providers.rb
- spec/features/end_to_end/teach_first_journey_spec.rb
- spec/models/provider_spec.rb
If a user is aligned to the provider: Teach First, when they create a a draft trainee, the only course route they can select is `HPITT`. This is out of date now: the Teach First provider now have "normal-route" options that they advertise via Publish and we import these trainees from Apply. This is new for 23/24.
simplifies training route list to display "HPITT" training route in addition to other routes only if provider is TeachFirst.
*  _(if in a review app create a provider "teach first" with code `1TF`)_
* create draft trainee with non-TeachFirst provider attached to user and see no HPITT training route option in list
* create draft trainee with TeachFirst provider attached to user and see HPITT training route option in addition to regular list
> [6200] - expose all training routes for TeachFirst trainee registration

- app/jobs/bulk_update/analytics_job.rb
The change here:
https://github.com/DFE-Digital/register-trainee-teachers/pull/3627/
For bulk uploads causes an error on the BQ side. This means the Trainee awarded status is not synchronised with BigQuery.
An entity table name is required rather than a model name; i.e. the parameter passed to the Event should be @‌model.table_name rather than @‌model
> [6292] - send table name not model

- app/components/iqts_country/view.html.erb
- app/components/schools/view.html.erb
- app/components/summary_card/view.rb
- app/components/training_details/view.html.erb
- spec/components/record_details/view_preview.rb
- spec/components/training_details/view_preview.rb
- spec/support/page_objects/trainees/record.rb
It was flagged in the accessibility report that there are some template summary page instances which have an `<h1>` title but use `<h2>` tags both in the page for subheadings AND as the title of each summary card causing a WCAG AA fail.
* defaults to H3 for summary cards
> [6201] change some summary card headings

- app/components/review_draft/draft/view.html.erb
- app/controllers/trainees/placements/details_controller.rb
- app/forms/placement_detail_form.rb
- app/helpers/task_list_helper.rb
- app/lib/training_route_manager.rb
- app/models/trainee.rb
- app/services/form_store.rb
- app/views/trainees/placements/details/edit.html.erb
- config/initializers/placement_enums.rb
- config/locales/en.yml
- config/routes.rb
- spec/features/form_sections/teacher_training_data/placements/details_spec.rb
- spec/forms/placement_detail_form_spec.rb
- spec/lib/training_route_manager_spec.rb
https://trello.com/c/ftfQZB4M/6247-do-you-have-any-of-the-trainees-placement-details-page-ui
https://github.com/DFE-Digital/register-trainee-teachers/assets/616080/0a8a2a71-b043-4f28-bbe6-3f5e5072784e
This PR wires up some foundational things to get the first step of the placements flow (from a UI perspective) functional and connected to the others.
- Sets up the section entry on the draft page (the logic for the complete/incomplete states will be finalised later)
- Adds the code to implement the first step so the provider can choose whether placement details are available (the saving is not yet implemented)
- Routes to the correct step depending on the answer selected (full stashing and returning behaviour is not completely wired up yet)
- Go to the review app, choose any route …
> [6247] Wire up flow for placements first step (placement details)

- app/models/trainee.rb
- spec/services/trainees/create_timeline_events_spec.rb
- spec/services/trainees/create_timeline_spec.rb
It's (sometimes) not possible to create a new degree because (it seems) there is a callback issue between `Degree` and `Trainee`. When a new `Degree` is saved it touches the `Trainee`. There is also an `after_touch` callback on Trainee that ends up calling save which triggers a second `INSERT` on the degrees table.
Do we really need to `save` after touch on a `Trainee`?
This PR just removes the `after_touch :save` callback.
This changes doesn't _appear_ to have any negative impact. The 2 broken specs were fixed by doing a simple `reload`. Can you see any wider implications? 
> [6261] Attempt to fix problem creating degrees

- config/initializers/sentry.rb
We're massively exceeding our Sentry quota with performance monitoring data, and we don't seem to use it
Turn off performance monitoring in Sentry
Does it look comfortingly similar to [this](https://github.com/DFE-Digital/get-a-teacher-relocation-payment/pull/324)?
> Turn off performance monitoring in Sentry

- app/views/trainees/placements/details/edit.html.erb
- app/views/trainees/placements/new.html.erb
- spec/features/form_sections/teacher_training_data/placements/progress_spec.rb
https://trello.com/c/kjERzvDM/6326-back-links-for-placements-create-flow
This PR makes sure the back links behave correctly in the placements flow. 
- Wire up the back links with the correct paths for the flow
https://github.com/DFE-Digital/register-trainee-teachers/assets/616080/8ae1fe42-8135-4c35-9902-40a987df8509
> [6326] Make sure back links behave correctly

- app/helpers/degrees_helper.rb
- app/lib/dqt/params/trn_request.rb
- spec/helpers/degrees_helper_spec.rb
iQTS record where a trainee studied.  You need to record the country using a drop-down menu of countries/territories. A  provider is unable to select “Cayman Islands” or “Isle of Mann”
* Uses the `DfE::Reference` gem for countries and territories listing for iQTS
* Uses `DfE::Reference` gem for mapping to country code when parsing trainee for DQT
> [6215]  use Dfe::Reference for iQTS country

- app/lib/route_data_manager.rb
- spec/factories/trainees.rb
- spec/lib/route_data_manager_spec.rb
Route changes
Resets placements
Works with draft trainees in the same manner as course details and funding details.
Once the route has changed the previously stored placements details may no longer be valid or applicable.
> [6349] Added route changes resets placements

- app/jobs/hesa/create_from_hesa_job.rb
- app/jobs/hesa/retrieve_job.rb
- app/services/trainees/create_from_hesa.rb
- spec/jobs/hesa/create_from_hesa_job_spec.rb
- spec/jobs/hesa/retrieve_collection_job_spec.rb
- spec/jobs/hesa/retrieve_trn_data_job_spec.rb
- spec/services/trainees/create_from_hesa_spec.rb
The `Hesa::RetrieveJob` job runs as one giant job and if any of the inline `Trainees::CreateFromHesa.call` fails it halts processing of subsequent records.
This PR refactors `Hesa::RetrieveJob` to fan out the `Trainees::CreateFromHesa` calls into their own jobs. This will allow our collection process to continuously run and not get coupled to problematic records.
- Updates `Hesa::RetrieveJob`
- Move the mapping logic from XML to a hash outside of `Trainees::CreateFromHesa` so it can be serialised properly when passed into the job
- Update specs 
This will now look like so:
> [6340] Refactor Hesa::RetrieveJob job to fan out

- app/components/placement_details/view.rb
- spec/components/placement_details/view_spec.rb
Editable links
Fixed editable links, so that they are only shown when applicable.
When the record is non editable then the non editable version is shown else the editable.
https://register-pr-3729.test.teacherservices.cloud/view_components/placement_details/view
n/a
> [6231] Fixed editable links

- app/lib/dqt/params/trn_request.rb
- spec/lib/dqt/params/trn_request_spec.rb
https://trello.com/c/lJCqD5v0/6357-pgce-trainee-pending-trn
A trainee is stuck with pending TRN because DQT doesn't understand the degree class we're sending.
These params:
```
{"class"=>"OrdinaryDegree", "date"=>"2022-01-01", "heQualificationType"=>"BachelorOfArts"}
```
Result in this error:
```
"$.qualification.class\":[\"The JSON value could not be converted to System.Nullable`1[TeachingRecordSystem.Api.V2.ApiModels.ClassDivision]. Path: $.qualification.class | LineNumber: 0 | BytePositionInLine: 816.\"
```
The issue is that DQT expects `"Ordinary"` rather than `"OrdinaryDegree"`.
Send DQT `"Ordinary"` rather than `"OrdinaryDegree"`.
Do you trust me haha
> Fix: change mapping of 'Ordinary degree' class to 'Ordinary' for DQT

- app/services/degrees/create_from_csv_row.rb
this [missing students ticket](https://trello.com/c/9nD7wcY3/5994-missing-students) produces some errors when importing as it's trying to create two non-existent non-uk degrees upon importing the CSV.
adds a guard clause in the `Degrees::CreateFromCSVRow`
> [5994] - don't run create degree if no degrees

- app/controllers/guidance_controller.rb
- app/views/guidance/_census_sign_off_inside.html.erb
- app/views/guidance/_census_sign_off_outside.html.erb
- app/views/guidance/census_sign_off.html.erb
- spec/controllers/guidance_controller_spec.rb
census sign off guidance is currently static. Some updates were requested as we are now outside of the period:
* [changes](https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/_layouts/15/doc2.aspx?action=edit&sourcedoc=%7B734f536f-ff48-41c4-a414-8a874e673ea3%7D)
* [trello ticket](https://downdetector.co.uk/status/trello/)
* creates two separate partials for census sign-off guidance
* the inside census partial dynamically loads current academic year dates
* check that new content changes match those [in the document](https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/_layouts/15/doc2.aspx?action=edit&sourcedoc=%7B734f536f-ff48-41c4-a414-8a874e673ea3%7D)
* you can manually set the sign off period in settings by adding `sign_off_period: census_period` to your …
> [6332] - make census sign off page dynamic

- app/forms/placements_form.rb
- spec/forms/placements_form_spec.rb
https://trello.com/c/puwJeK3H/6252-create-placements-snag-list
Minor snag to make sure we reset the `placement_detail` field on the trainee when placements are added.
> [6252] Reset placement_detail when adding placements

- app/helpers/degrees_helper.rb
- spec/helpers/degrees_helper_spec.rb
Looks like the validation on the ‘Country’ field isn’t working.  If you select a ‘valid’ country from the reference data, a validation error appears.  Doesn’t matter what country you select, you will always get the validation error.
> note: this was only effecting countries with a word length greater than one
* removes downcase on option creation which was resulting in mismatched sets between the JS autocomplete and the list used for validating selections.
> [6373] - Validation on the 'Country' field doesn't seem to work

- app/models/placement.rb
- app/services/trainees/create_timeline_events.rb
- app/services/trainees/get_placement_name_from_audit.rb
- config/locales/en.yml
- spec/services/trainees/create_timeline_events_spec.rb
- spec/services/trainees/create_timeline_spec.rb
- spec/services/trainees/get_placement_name_from_audit_spec.rb
We have recently added the capability to add, modify and delete placements associated with trainee records. Changes to placements should be reflected in the trainee timeline.
Add specific entries to the timeline for create, modify and delete placement events.
The data displayed on the timeline (the placement/school names) is harvested from the audit trail only because the value at the time of a given event may have changed on the placement record itself since that event took place.
Update: Now that all the CRUD PRs have been merged it should be possible to test this fully on the Review app or locally.
> [6361] Update the timeline when a placement change occurs

- app/forms/submissions/missing_data_validator.rb
- spec/forms/submissions/missing_data_validator_spec.rb
We don’t need the banner saying "You need to give additional details before you can recommend the trainee for QTS. You need to enter: Placement details" as we are no longer mandating it for QTS recommendation.
I've removed placements from the list of validators on this page.
> [6409] Remove placement validations from trainee page banner

- app/components/placements/view.html.erb
- spec/components/placements/view_spec.rb
The link to guidance about placements on the placements landing page has the wrong content.
Shorten the content for the link.
Have I missed anything?
> [6410] Correction to copy for link to placement guidance

- app/components/hesa_warning_inset/view.html.erb
- app/components/hesa_warning_inset/view.rb
- app/views/layouts/trainee_record.html.erb
- config/locales/en.yml
- spec/components/hesa_warning_inset/view_spec.rb
For a HESA-derived trainee, there should be a warning displayed to users that their data could be overwritten if they send further updates via HESA. 
Add timestamp to the existing HESA warning inset because it doesn't match the new design.
Non-editable trainee:
Editable trainee:
This PR extracts this message into a new `HesaWarningInset::View` component (mainly so that I could test it properly).
Have I missed anything?
> [6411] Add timestamp to HESA warning inset

- app/views/trainees/placements/delete.html.erb
Should go back to the confirmation page if that's where we arrived from, otherwise back to the main trainee page. (It was linking back to the edit placement details page).
Use standard backlink.
> [6432] Correction to back link on delete placement page

- app/forms/placement_form.rb
- app/views/trainees/placements/_form.html.erb
- config/locales/en.yml
- spec/forms/placement_form_spec.rb
Placement Validation
Fixed the correctiveness of validation
Added ability to open collapsed section due to validation
Removed unneeded validation
Go and mess about with placements
- The summary error links should jump to the field
- Urn is now optional
- if urn or postcode is fiiled then expect school or setting name to be filled as well
- if the school or setting name fails validation the details summary is opened
> [6412] Placement snagging II validation fixes

- app/assets/stylesheets/application.scss
- app/views/trainees/placements/_form.html.erb
Some of the input fields on the placement (new/edit) form are inconsistent with the prototype.
Apply different styles to the autocomplete, postcode and URN inputs so that they reflect the size of the input data. Also applied upper case style to postcode.
Before:
After:
Have I missed anything else?
> [6429] Shorten placement input fields consistent with prototype

- app/views/trainees/check_details/_apply_draft_trainee_check_details.html.erb
It looks like the placeholders for placement details were put into the non-Apply template but not the Apply one.
Before:
After:
This stuff doesn't seem to be tested anywhere unless I'm missing something?
> [6441] Placements on check details page for Apply imported trainees

- app/forms/placement_form.rb
- config/locales/en.yml
- spec/forms/placement_form_spec.rb
Placement urn 
Added unique urn validation
Add a first placement with a urn like `1238316`
Then try to add a second placement using urn `1238316` either via autocomplete or manually
> [6445] Added unique urn validation

- app/forms/placements_form.rb
- app/view_objects/missing_data_banner_view.rb
- spec/view_objects/missing_data_banner_view_spec.rb
We don’t need the banner saying _You need to give additional details before you can recommend the trainee for QTS. You need to enter: Placement details_ as we are no longer mandating it for QTS recommendation
However we don't want to skip the validations because this drives features like the placeholders on the confirm details page.
First attempt to implement this removed validations (https://github.com/DFE-Digital/register-trainee-teachers/pull/3766). However we don't want to skip these validations because they drives features like the placeholders on the confirm details page.
So this PR just excludes the placement details validation errors from the banner.
The original (partial) fix for this was https://github.com/DFE-Digital/register-trainee-teachers/pull/3754 and …
> [6409] Exclude placement validation in banner

- app/models/trainee.rb
- db/migrate/20231127134319_drop_trainees_application_choice_id_foreign_key.rb
- db/schema.rb
We want to store the Apply application_choice_id on Trainee records so that we can better integrate with Apply.
This is a partial rollback of a schema change made in https://github.com/DFE-Digital/register-trainee-teachers/pull/3780
It probably isn't a good idea to have a foreign key from `trainees.application_choice_id` to `apply_applications.apply_id` because this column may be used for trainees that have not been imported from Apply and therefore will not reference a record in the `apply_applications` table. (It may be a reference to `hesa_students.application_choice_id` instead).
Does this make sense?
> [6355] Drop foreign from `trainees.application_choice_id`

- app/components/placements/view.html.erb
- app/controllers/trainees/placements/details_controller.rb
- app/forms/placement_detail_form.rb
- app/views/trainees/placements/details/edit.html.erb
- spec/features/form_sections/teacher_training_data/placements/details_spec.rb
- spec/features/form_sections/teacher_training_data/placements/progress_spec.rb
- spec/forms/placement_detail_form_spec.rb
Miscellaneous minor placement issues
Added missing trainee name on placement details
Amended school placement link
Amended the redirects for no
Added ability to set trainee progess placements to true if details not provided
> [6433] Fixed miscellaneous minor placement issues

- app/forms/submissions/missing_data_validator.rb
- app/view_objects/missing_data_banner_view.rb
- app/views/trainees/show.html.erb
- config/locales/en.yml
- spec/factories/trainees.rb
- spec/features/trainee_actions/viewing_an_existing_trainee_spec.rb
- spec/forms/submissions/missing_data_validator_spec.rb
- spec/view_objects/missing_data_banner_view_spec.rb
We want to adjust the banner message that appears to warn users about missing information. When placement are missing it's not true to say that the trainee cannot be submitted (request for QTS) when there is missing placement data.
The messaging in the banner should only say that info is needed to recommend a trainee if mandatory fields (ie. not just placement fields) are missing. But if it's just placements that are missing we use the softer language.
> [6409] Reinstate placements message in missing banner

- app/components/flash_banner/view.html.erb
- app/components/flash_banner/view.rb
- app/controllers/trainees/placements_controller.rb
- app/forms/destroy_placement_form.rb
- app/forms/placements_form.rb
- app/views/trainees/placements/delete.html.erb
- config/locales/en.yml
- spec/features/form_sections/teacher_training_data/placements/deleting_draft_trainee_placements_spec.rb
- spec/features/form_sections/teacher_training_data/placements/deleting_trainee_placements_spec.rb
- spec/forms/destroy_placement_form_spec.rb
- Bug 5. Placements aren’t seem to be getting deleted on draft trainees because we are stashing the delete operation rather than executing it immediately.
- Bug 9. When we attempt to delete an unsaved placement (on a registered trainee record) we get a 404 page because the placement is not yet in the database.
- Bug 13. On the prototype after clicking the red button to remove a placement the user is taken back to the Manage Placements page with a confirmation that the action has completed successfully. This is missing on Prod
- Bug 5. Alter logic in forms that implement this logic to execute the destroy action immediately for draft trainees.
- Bug 9. Handle the case where the user asks to delete an unsaved placement by just removing it from the temporary stashed data store.
- Bug 13. Add …
> [6466] Fix delete placements issues 5, 9 and 13 (from bug party)

- app/views/trainees/placements/details/edit.html.erb
Wordings
This wording is needed instead of previous one
> You need to add the details of at least 2 schools. These can be added at any time.
> [6465] Amended wordings

- app/controllers/trainees/placements/details_controller.rb
- app/views/trainees/placements/new.html.erb
- spec/features/form_sections/teacher_training_data/placements/adding_trainee_placements_spec.rb
- spec/features/form_sections/teacher_training_data/placements/details_spec.rb
Looped journery
Added tests to flush out loopiness
Amended to use placement count to decide which back link to use
Removed loopiness
The review draft page is should be the only origin page.
The bug occurs as previously the  placement-details page set it self as the origin, which only surfaces the loop.
When after a placement is added and the the user is expected to return to the review draft page from the confirmation page, instead the user find themselves back on the placement-details page.
> [xxxx] Fixed placement details looped journery

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/utilities.scss
- app/helpers/support_email_helper.rb
- app/views/funding/payment_schedules/show.html.erb
- app/views/funding/trainee_summaries/show.html.erb
- app/views/pages/dttp_replaced.html.erb
- app/views/trainees/employing_schools/edit.html.erb
- app/views/trainees/forbidden_withdrawals/show.html.erb
- app/views/trainees/lead_schools/edit.html.erb
- app/views/trainees/withdrawal/dates/edit.html.erb
- spec/helpers/support_email_helper_spec.rb
https://trello.com/c/gcMCik0T/6344-email-addresses-break-page-width-at-400-and-1289-x-1024px
Fixes the accesibility issue highlighted in the screenshot below:
Test this out in the org list. Sign in as a persona belong to multiple orgs, hit shift+cmd+r to enter responsive mode in safari and scale down.
> [6344] Fix accessibility issue with long support email

- app/assets/stylesheets/application.scss
https://trello.com/c/TAxKSixD/6345-remove-links-on-nationality-are-misplaced-visually-and-in-code
Aligns the links visually for accessibility reasons. 
Before:
After:
> [6345] Fix nationality remove links

- app/controllers/system_admin/funding/payment_schedules_controller.rb
- app/services/exports/funding_schedule_data.rb
- spec/services/exports/funding_schedule_data_spec.rb
This is a bug that was raised via support. From the funding page you can view and download the payment schedule for the current academic cycle or earlier ones.
For earlier academic cycles the years and data for each row are displayed correctly when viewed in the browser. However when downloaded as a CSV the years are wrong because the CSV rendering code seems we assume that we are always interested in the current cycle.
https://trello.com/c/IsvsFfeJ/6490-dates-incorrect-on-previous-year-funding-download
To fix this we can just pass the `start_year` and `end_year` into `Exports::FundingScheduleData`.
Does this make sense and is there anywhere else we are likely to have a similar issue?
How do we test this manually?
NB: Please notify the #twd_data_insights team and ask for a review if new …
> [6490] Fix previous cycle dates for funding schedule CSV download

- app/controllers/trainees/funding/bursaries_controller.rb
- app/forms/funding/form_validator.rb
- app/forms/funding/grant_and_tiered_bursary_form.rb
- config/locales/en.yml
- spec/forms/funding/form_validator_spec.rb
This was reported as a support issue - a provider was unable to save bursary info on a trainee record.
https://trello.com/c/G5RmNWk4/6456-should-a-bursary-be-selectable
I was able to reproduce this locally using an Early years graduate entry/Early years ITT trainee. When clicking funding from the main trainee dashboard they user sees the grant and tiered bursary form (which is fairly new I think):
After selecting (say) a tiered bursary and clicking continue the user sees a confirmation page. However the confirmation page does not include the selection and pressing the _Update_ button doesn't save the selection as it should.
This problem seems to be due to a discrepancy between the form selected to persist the changes to the FormStore (namely `Funding::GrantAndTieredBursaryForm`) and the …
> [6456] Fix stash and save of grant and tiered bursaries

- app/components/award_details/view.rb
- spec/components/award_details/view_spec.rb
`outcome_date` stores the date at which the user said that the trainee met conditions whereas `recommended_for_award_at` only records when the provider filled in the form on Register.
Use `Trainee#outcome_date` in the `AwardDetails::View` component. Fallback to `recommended_for_award_at` if there is no `outcome_date`.
Is there anywhere else we need to do similar?
> [6492] Use `outcome_date` for awarded at component

- terraform/aks/workspace-variables/dv_review_aks.tfvars.json
When deploying to dev cluster, the app fails with:
```
bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)
Undeclared attribute type for enum 'training_route'. Enums must be backed by a database column or declared with an explicit type via `attribute`.
/app/db/migrate/20210118132920_regenerate_slugs_on_trainees.rb:5:in `up'
Caused by:
Undeclared attribute type for enum 'training_route'. Enums must be backed by a database column or declared with an explicit type via `attribute`.
/app/db/migrate/20210118132920_regenerate_slugs_on_trainees.rb:5:in `up'
Tasks: TOP => db:migrate
```
Make it the same as the review apps
Deployed to dev cluster 1: https://register-111111.cluster1.development.teacherservices.cloud/ …
> Update dv_review app startup command

- app/controllers/trainees/placements/confirm_details_controller.rb
- app/controllers/trainees/placements_controller.rb
- app/helpers/trainee_helper.rb
- app/policies/trainee_policy.rb
- app/views/trainees/show.html.erb
- spec/features/form_sections/teacher_training_data/placements/adding_trainee_placements_spec.rb
- spec/forms/placements_form_spec.rb
It should be possible to add placements to trainees in the awarded or recommended states. However for non-sys-admins this was not possible due to us reusing standard permission rules - specifically the rule that says you can't edit a trainee in a completed state.
We need to special case adding placements such that a provider that would normally have permission to make changes to a trainee record can add placements regardless of the state of the trainee.
- Adds a new permission: `TraineePolicy.write_placements?`
- Applies this policy in 2 places:
- View logic that renders link to _Manage placements_
- Controller logic in `ConfirmDetailsController` (for creates) and `PlacementsController` (for updates and deletes).
- Adds an assertion to verify that we don't call DQT when adding a …
> [6530] Adding placements to trainees in awarded state

- app/services/determine_sign_off_period.rb
- app/views/reports/_performance_period.html.erb
- spec/features/reports/index_spec.rb
- spec/services/determine_sign_off_period_spec.rb
https://trello.com/c/UDrQNHXh/6507-change-dates-on-the-report-tab-to-show-performance-profiles-report
- Updates the profile performance logic to expand dates to 1st Dec - 17th Feb
Check the review app, reports tab and the performance profile link should be available
Review app - https://register-pr-3839.test.teacherservices.cloud/
> [6507] Update date range for performance profile

- app/policies/trainee_policy.rb
- spec/policies/trainee_policy_spec.rb
Including for trainees that are already QTS-awarded and regardless of whether they’ve been enabled for editing.
We think that HEI users should be able to manage placement data, including for trainees that are already QTS-awarded and regardless of whether they’ve been enabled for editing.
Trello: https://trello.com/c/jHVfmliV/6538-enable-placement-add-edit-delete-for-hesa-imported-trainees
Update policy to allow editing of placements for all trainees as long as the user is in the appropriate context.
- Log in as an HEI user (not an admin user)
- Filter trainees as HESA-imported and QTS-awarded
- Check you can edit placements
> [6538] Allow providers to manage placements for HESA imported trainees

- app/services/trainees/create_timeline.rb
- spec/services/trainees/create_timeline_spec.rb
We filter the timeline to only include the last audit entry in each set grouped by `request_uuid`. This means that if, say, you add two placements at a time then you'll only see the last one in the timeline. This is a bug for placements.
We solve that here by special casing placement audit entries and returning all entries for a given `request_uuid` if one or more of those entries relates to a `Placement`.
Is there a more elegant way to fix this?
> [6543] Include multiple placement events in timeline

- app/services/trainees/create_from_apply.rb
- app/services/trainees/create_from_hesa.rb
- spec/services/trainees/create_from_apply_spec.rb
- spec/services/trainees/create_from_hesa_spec.rb
We want to have a record of the Apply `application_choice_id`, whether it is imported from Apply directly or via HESA.
This is meant to cover ongoing syncing of `application_choice_id`s. There will be a follow-up backfill PR.
> [6355] Import Apply application choice id from HESA and Apply

- app/views/trainees/contact_details/edit.html.erb
- app/views/trainees/placements/details/edit.html.erb
The error panels on the _Contact details_ and _Placement details_ forms are not in the correct positions. 
> [6500] Fix some layout issues with error messages

- app/services/concerns/has_amounts_in_pence.rb
- spec/services/concerns/has_amounts_in_pence_spec.rb
CSV importer
When a `£` is provided in the csv is sets the value as zero.
Remove it before conversation 
Run with a csv that has `£` and see the magic happen
```
bundle exec rake funding:import_lead_school_payment_schedules['funding.csv',2]
```
> [6454] Fixed issue whereby values with `£` returns zero values

- app/lib/system_admin_constraint.rb
- app/models/dfe_sign_in_user.rb
- app/models/otp_sign_in_user.rb
- spec/features/auth/otp_authentication_spec.rb
- spec/lib/system_admin_constraint_spec.rb
- spec/models/dfe_sign_in_user_spec.rb
The guard that restricts the support interface to authenticated sysadmin users currently blocks all users logged in via the DSI fallback (OTP) authentication route.
https://trello.com/c/aozd7eKM/6524-when-logged-in-using-dsi-fallback-cannot-access-support
Permit sysadmins to access the support interface regardless of the way that they have been authenticated.
- Does this present any loopholes?
- How should we test it? Deploy and switch on the fallback on production data?
> [6524] Fix access to support interface when logged in via DSI fallback

- app/services/trainees/create_from_hesa.rb
- db/data/20231219120311_update_hesa_trainees_with_lead_school_urn.rb
- spec/services/trainees/create_from_hesa_spec.rb
There are some School Direct tuition fee trainees at MMU that show as lead school “not applicable” in Register. However, in the admin section of their record in the HESA drop down can see the lead school URN provided.
* fixes a suspected bug where `lead_school_not_applicable` once set to `true` prevents subsequent HESA updates from assigning a `lead_school` to a trainee owing to a `before_save` hook `before_save :clear_lead_school_id, if: :lead_school_not_applicable?`
* adds a migration to backfill any `trainee` with nil `lead_school` with `lead_scool_urn` present in the `hesa_students` table.
> [6491] - Lead schools not correctly populated from hesa data

- config/settings/productiondata.yml
This is purely to test https://trello.com/c/aozd7eKM/6524-when-logged-in-using-dsi-fallback-cannot-access-support
We need to just deploy this, make sure that the support interface is available to those that should see it and issue a new PR to revert back.
Switch proddata to use OTP authentication.
Is there an easier way?
> [6524] Switch on DSI Fallback on proddata for testing

- config/settings/productiondata.yml
Switch off the OTP fallback mechanism so that we are using normal DSI authentication again on productiondata.
Reverses https://github.com/DFE-Digital/register-trainee-teachers/pull/3879
> [6524] Reinstate DSI on productiondata

- Gemfile
- config/initializers/sentry.rb
Enables Sentry's performance and profile monitoring so we can setup some anomaly alerts around this category. Start with a low `traces_sample_rate` rate. We'll assess how noisy it is in Sentry and adjust accordingly.
> [6527] Enable performance/profile monitoring

- app/services/degrees/create_from_csv_row.rb
- app/services/trainees/create_from_csv_row.rb
- db/data/20231220151357_add_other_degree_grade_to_teach_first_trainees.rb
- spec/data_migrations/add_other_degree_grade_to_teach_first_trainees_spec.rb
- spec/services/degrees/create_from_csv_row_spec.rb
The CSV teachfirst import previously was unable to parse `Degree: UK grade` that followed the `Other: other grade` pattern. this fixes this and includes a migration to correct teachfirst trainees impacted.
> [6477] - parse 'other' uk grade type. migrate teachfirst data

- app/controllers/otp_controller.rb
- app/forms/concerns/throttle_requests.rb
- app/forms/otp_form.rb
- app/forms/otp_verifications_form.rb
- spec/forms/otp_form_spec.rb
- spec/forms/otp_verifications_form_spec.rb
Our IT Health Check highlighted potential malicious requests to the OTP generation form. 
`OtpVerificationsForm` already implements a mechanism to prevent too many repeated attempts to submit an OTP code (to limit the number of guesses a malicious user gets). So I've extracted that throttling logic into a `ThrottleRequests` concern and reused it in `OtpForm` to limit the number of OTP generation requests a user can make.
Is there a better way?
> [6487] Throttle OTP generation requests (DSI fallback)

- terraform/aks/application.tf
- terraform/aks/variables.tf
- terraform/aks/workspace-variables/production_aks.tfvars.json
https://trello.com/c/YoiWymj0/795-alerting-for-container-restarts
Add monitoring for container restarts now that we have the required metrics available.
Set enable_container_monitoring too true for production env.
**This PR can only be merged once the terraform-modules application PR has moved to stable on 18/12.**
make production_aks deploy-plan
> Add alerting for container restarts

- config/initializers/sentry.rb
Register uses a lot of mission critical cron jobs. Sentry can monitor those and let us know information about their status. We should probably turn that on. Have also reduced the sample rate following convo with Colin.
> [xxx] Setup cron monitoring and reduce sample rate

- app/views/bulk_update/bulk_updates/_no_trainees.html.erb
- app/views/guidance/_course_details.html.erb
- app/views/guidance/bulk_recommend_trainees.md
- config/locales/en.yml
- spec/components/course_details/view_spec.rb
- spec/support/features/course_details_steps.rb
https://trello.com/c/2PJ30OIv/6501-update-itt-end-date-to-expected-end-date
Updates the ITT end date label in views to Expected end date
Head to the review app and check the following areas
- Manual course details form
- Early years course details form
- Course dates form
- Summary cards / tables
- CSV export
- Guidance
There was a question in the ticket asking if we should update the db column name. If there is appetite for that then I think it's best for another ticket. As we would need to coordinate introducing a new column and safely transition over to that rather than a simple rename in the migration (which could lead to some errors with background jobs). The immediate requirement is to update the label in the views so I've just left this ticket to that.
> [6501] Update ITT end date to Expected end date in views

- Gemfile
- Gemfile.lock
- app/services/bulk_update/recommendations_uploads/validate_file.rb
- config/locales/en.yml
- spec/services/bulk_update/recommendations_uploads/validate_file_spec.rb
We only accept UTF-8 CSV in the bulk recommendation for QTS/EYTS feature. We want to show an error that specifies we don’t take that particular form of CSVs.
adds a validation using `charlock_holmes` that detects if a file uploaded is indeed `UTF-8` encoded.
> [5377] - check bulk recommend files uploaded are UTF-8 encoded

- app/controllers/bulk_update/recommendations_uploads_controller.rb
- app/controllers/reports_controller.rb
- app/models/reports/bulk_recommend_empty_report.rb
- app/services/exports/bulk_recommend_empty_export.rb
- app/views/bulk_update/recommendations_uploads/new.html.erb
- config/routes.rb
- spec/features/bulk_upload/recommending_trainees_spec.rb
- spec/services/exports/bulk_recommend_empty_export_spec.rb
- spec/support/recommendations_uploads_helper.rb
This PR is a continuation of https://github.com/DFE-Digital/register-trainee-teachers/pull/3898 and extends the bulk recommendation feature to allow provider users to download an empty template file (CSV) which they can fill in to upload their recommendations.
Allow users to export an empty CSV template with fewer headers and make the necessary adjustments to the import logic to handle this type of template. (Since the required column names are all present in the simplified empty template the import works the same was as with the pre-populated template _I think_).
Are the tests sufficient?
> [6572] Update bulk recommend logic for empty template

- app/controllers/system_admin/duplicate_apply_applications_controller.rb
- app/models/apply_application.rb
- app/services/trainees/find_duplicates.rb
- app/services/trainees/find_potential_duplicates.rb
- app/views/system_admin/_tab_nav.html.erb
- app/views/system_admin/duplicate_apply_applications/index.html.erb
- app/views/system_admin/duplicate_apply_applications/show.html.erb
- config/locales/en.yml
- config/routes/system_admin_routes.rb
- spec/factories/apply_applications.rb
- spec/features/system_admin/duplicate_apply_applications/viewing_duplicate_apply_applications_spec.rb
- spec/features/trainee_actions/change_course_spec.rb
- spec/models/apply_application_spec.rb
Some applications imported from the Apply service are flagged as duplicates because, at the time of import, Register identifies a potential matching Trainee record already in the database. Such applications end up in the `non_importable_duplicate` state.
We need a way to view Apply applications that have ended up in this state so that the support team can investigate.
We've added a new _Duplicate apply applications_ page to the support interface with a corresponding menu item. This lists the basic details of each duplicate:
The _View_ button on each row drills down to each record and attempts to identify the duplicate Trainee record(s).
- The UX could clearly be improved. Any suggestions welcome.
- What other information would be useful in helping to determine whether the flagged Apply …
> [6364] Support page for duplicate apply applications

- app/forms/placement_form.rb
- config/locales/en.yml
- spec/forms/placement_form_spec.rb
When acceptance testing the recent trainee placements feature we identified some improvements to tighten up validation for manual placement entry. 
Validate that:
- `Placement#postcode` is a valid postcode
- `Placement#urn` is a valid URN (6-digit string)
- Does the review app work as expected?
- Are there other tests we should do?
> [6532] Validate `Placement#postcode` and `urn`

- app/forms/withdrawal/extra_information_form.rb
- config/locales/en.yml
- spec/features/trainee_actions/withdraw_trainee_spec.rb
Related to: https://github.com/DFE-Digital/register-trainee-teachers/pull/3860
* Made the character limit for withdrawal reasons 1000 characters.
* Fixed a typo with the error message when a reason is too long. 
> Withdrawal Reason Character Limit

- app/assets/stylesheets/components/_accordion.scss
- app/assets/stylesheets/components/_all.scss
- app/helpers/support/dqt_helper.rb
- app/models/dqt/trn_request.rb
- app/views/system_admin/pending_trns/index.html.erb
- config/locales/en.yml
- spec/features/system_admin/pending_trns/pending_trns_spec.rb
- spec/helpers/support/dqt_helper_spec.rb
- spec/models/dqt/trn_request_spec.rb
https://trello.com/c/5qVI6mgI/6438-add-body-and-error-message-to-pending-trns-report
Before:
After:
- Refactors the pending trn page layout to list all the trainees using the govuk accordion
- Includes the trn request response details into each row for more details
If this works, we can apply to other layouts. The accordion allows us to add any type of information without layout constraints in each row if needed. We regards to filtering/sorting, we could simply have these as buttons in a sort of "toolbar" above the results which would then filter based on the query params 🤷.
> [6438] Refactor pending trns page to include trn response

- lib/tasks/example_data.rake
- spec/factories/placements.rb
This task was failing with a duplicate key error on the `Placement#slug` attribute. This happens due to a side-effect of the validation for trainees with placements. The validation triggers logic in `PlacementsForm` that ends up populating the `Trainee#placements` association from the `FormStore`.
There are a number of un-answered questions here:
- Why does `FormStore` get populated when we are just creating data via a rake task (there is no form)?
- Why does the validation for `Trainee` end up mutating the data?
The change in this PR is a workaround to get the rake task working pending further investigation.
Clear the `FormCache` before saving (and validating) new trainees created by the rake task.
What is the best longer-term solution to the underlying issue with placements?
NB: Please …
> [6586] Fix `example_data:generate` rake task (workaround)

- app/models/reports/bulk_placement_report.rb
- app/services/bulk_update/placements/config.rb
- app/services/bulk_update/placements/validate_csv.rb
- app/views/bulk_update/bulk_updates/index.html.erb
- spec/fixtures/files/bulk_update/placements/complete-with-extra-placements.csv
- spec/fixtures/files/bulk_update/placements/complete-with-too-many-placements.csv
- spec/services/bulk_update/placements/create_placement_rows_spec.rb
- spec/services/bulk_update/placements/validate_csv_spec.rb
Some providers would like to be able to add more than two placements per trainee in the bulk upload process
Continue to generate the placements export with just two placement URN columns, but when processing the upload, check for extra placement columns that have been added (up to a total of 5)
Try it out.
> Allow up to 5 placement URN columns in bulk update CSV

- app/controllers/system_admin/duplicate_apply_applications_controller.rb
- app/views/system_admin/duplicate_apply_applications/show.html.erb
- spec/features/system_admin/duplicate_apply_applications/viewing_duplicate_apply_applications_spec.rb
Fixes rendering of duplicate records on the duplicate apply applications show page. Correction to https://github.com/DFE-Digital/register-trainee-teachers/pull/3896
Fix the dumb bug and return the correct duplicate trainee record.
Note that we are still reviewing with support how this page should look and what the process will be going forward to handle duplicate Apply applications. This is just a fix to what is there so far.
> [6364] Fix incorrect duplicate trainee

- app/services/exports/funding_trainee_summary_data.rb
- lib/tasks/example_data.rake
- spec/factories/funding/trainee_summaries.rb
- spec/factories/funding/trainee_summary_rows.rb
- spec/services/exports/funding_trainee_summary_data_spec.rb
This issue originated from a support issue. A provider exported their trainee summary for 2022 to 2023, but the download was missing a trainee on a scholarship so the total in column H of the downloaded spreadsheet too low and did not match that shown in the user interface.
This is happening because the CSV export logic only considers the first amount per row. It should consider all amounts.
https://trello.com/c/mhT1Gd4h/6489-tkatt-scitt-scholarship-trainee-missing-from-the-funding-download
Include multiple rows in the exported funding CSV when there are multiple amounts per summary row (for different funding types).
For this funding summary (appearing here in the Web UI):
CSV download before (with mismatched total):
and after (with matching total):
I've added some data to the example …
> [6489] Scholarship trainee missing from the funding download

- app/lib/dqt/params/trn_request.rb
- spec/lib/dqt/params/trn_request_spec.rb
We currently use the DfE Reference Data gem to map country values between their human-readable names and two-letter ISO codes. DQT expects a two-letter ISO code. However it's list of countries is not exactly the same as ours and it rejects codes with a region, e.g. AE-AY (Abu Dhabi in the United Arab Emirates).
Without harmonising our country lists across all services we need to implement some non-standard mappings at the point we send this information to DQT.
- _Cyprus_ needs to be mapped the country code `XC` and not `CY`.
- All country codes with regions need to have those stripped. e.g. `AE` not `AE-AY`. This applies to a few other countries like St Helena and Caribbean Netherlands.
- I've looked for all the places in the DQT interface that pass country codes - I've only found two …
> [6609] Workaround missing/alternate country codes implemented by DQT

- app/views/guidance/manage_placements.html.erb
- app/views/guidance/performance_profiles.html.erb
Now that HEIs are ready to sign off their performance profiles by 31 Jan 2024 so there is a need to update 2 Register guidance pages.
https://trello.com/c/jwQElDPg/6551-performance-profile-guidance-page-minor-updates-x-2
- Remove inset text from _Manage your trainee placement data_ page.
- Remove heading about SCITTS from _Sign off your list of trainees from 2022 to 2023 for the performance profiles publication_ page.
See review app
> [6551] Content updates for performance profile guidance

- config/settings.yml
- spec/smoke/login_spec.rb
- spec/spec_helper_smoke.rb
An incident happened [Incident report some_users_unable_to_sign_in_to_register 20231207](https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/Shared%20Documents/Becoming%20a%20Teacher/Incidents/Incident%20report%20some_users_unable_to_sign_in_to_register%2020231207.docx?d=w7b0377219b4e41ecba14394e9e17017e&csf=1&web=1&e=yZsN8l)
This adds smoke testing that uses a test user account to log into the service on deploy.
* creates a new smoke test user - added to production, productiondata and staging
* simple capybara test that visits the live deployed
* username/pass are added to the ENV for each relevant site
* this skips the tests if OTP sign-in method is enabled (this will need to be a separate spec if wanted)
> [6528] - Add logins to the smoke tests

- spec/smoke/login_spec.rb
- spec/spec_helper_smoke.rb
relates to #3954 
This adds `js: true` to the smoke tests and removes unnecessary path check
> [6528] add logins to the smoke tests - corrects faulty spec

- app/controllers/sessions_controller.rb
- app/controllers/system_admin/users_controller.rb
- app/services/send_welcome_email_service.rb
- spec/controllers/sessions_controller_spec.rb
- spec/features/system_admin/users/creating_a_new_user_spec.rb
- spec/services/send_welcome_email_service_spec.rb
We currently send out our 'welcome email' to new users right after they first log in. Since this email contains information about how to actually login it makes more sense to have it sent straight after the user is created in the system admin interface.
Move call to `SendWelcomeEmailService` from the `SessionsController#callback` action to `SysAdmin::UsersController#create`.
> [6618] Send welcome email after user creation not first login

- app/forms/reinstatement_form.rb
- spec/forms/reinstatement_form_spec.rb
https://trello.com/c/5jC7GKNC/6622-clear-funding-method-if-the-start-year-of-a-trainee-changes
Clears the funding information on the Trainee whenever reinstatement happens
- Find a deferred trainee with some funding applied (look for courses in math, computer science, etc)
- Reinstate them
- Check the funding method is asked for on the trainee page
> [6622] Clear funding when reinstatement happens

- app/services/trainees/create_from_hesa.rb
- db/data/20240122123547_backfill_missing_hesa_defferal_dates.rb
- spec/services/trainees/create_from_hesa_spec.rb
Originally `F_ENDDATE` was used to set the `defer_date` on the trainee if HESA deferred the `itt_record` but was replaced with `EXPECTEDENDDATE`:
https://www.hesa.ac.uk/innovation/records/reviews/ITT-2022-23-AnnualUpdate
https://github.com/DFE-Digital/register-trainee-teachers/pull/2632
It appears we did not update https://github.com/DFE-Digital/register-trainee-teachers/blob/5d230a06fd3a03d031f218dd40c6647b66f5f191/app/services/trainees/create_from_hesa.rb#L124 to reflect the change.
Since then,` F_ENDDATE` was actually removed from the mapping as part of further api changes:
https://github.com/DFE-Digital/register-trainee-teachers/commit/7996391991303b667461f93d1b4c811d30bdc3d5#diff-7c04bf014ac455d32803dbf8a4fb1c7ab1e987b7365010559bd22a8ffd271ab9L27
Looking at the earlier updates, HESA …
> [6623] Update hesa deferral logic

- app/controllers/trainees/placements_controller.rb
- app/forms/placement_form.rb
When creating a new placement (in a JS enabled browser) the user is redirected into the non-JS flow and prompted to reselect the choice of school that they already picked from the autocomplete. This was a bug introduced by https://github.com/DFE-Digital/register-trainee-teachers/pull/3923
As the non-JS flow is triggered by the presence of the `school_search` param in the `create` action so we avoid pushing that into the `PlacementForm` except on the `edit` action (where it sets the initial value of the search box when a user wants to change a placement).
Is there a better way to test for this kind of regression?
> [6681] Add new placement regression - uses non-JS flow

- app/controllers/system_admin/user_lead_schools_controller.rb
- app/controllers/system_admin/users_controller.rb
- spec/features/system_admin/users/add_a_lead_school_to_user_spec.rb
- spec/features/system_admin/users/creating_a_new_user_spec.rb
This is a follow up fix for https://github.com/DFE-Digital/register-trainee-teachers/pull/3940
There is logic in the `SendWelcomeEmailService` to skip the email unless the user is associated with a lead school so triggering this service immediately after create a user doesn't work.
Instead we can trigger the service straight after adding a lead school to a user as this is the earliest possible time for a user to be 'eligible' to receive a welcome email.
We can safely call this service multiple times because in contains a check based on the `User#welcome_email_sent_at` timestamp to prevent multiple emails being sent to the same user.
- Is there a better way to test this than deploying straight to production?
NB: Please notify the #twd_data_insights team and ask for a review if new fields …
> [6618] Move welcome email trigger to lead school controller

- app/controllers/autocomplete/application_controller.rb
- app/controllers/autocomplete/providers_controller.rb
- app/controllers/autocomplete/schools_controller.rb
- app/controllers/autocomplete/users_controller.rb
- app/javascript/scripts/components/form_components/providers_autocomplete.js
- app/javascript/scripts/components/form_components/schools_autocomplete.js
- app/javascript/scripts/components/form_components/users_autocomplete.js
- config/routes.rb
- config/routes/api_routes.rb
- config/routes/autocomplete_routes.rb
- spec/controllers/autocomplete/providers_controller_spec.rb
- spec/controllers/autocomplete/schools_controller_spec.rb
There were a number of routes that used the `/api` root path and `Api` module. These service the various autocomplete components that we have in our frontend. Now that we are building a 'real' API (see https://github.com/DFE-Digital/register-trainee-teachers/pull/3982) these are somewhat confusing and out of place. Note that they've never been used as an external API or documented as such despite appearances.
This PR moves existing routes under `/api` to the `/autocomplete` root path. The idea being that this should make it very clear what they are used for. 
We need to just make sure that the autocompletes for schools, users and providers still work.
I've tried this on the review app for the users and providers pages in sys-admin and the providers add placement page for schools. e.g.
NB: …
> [6667] Move legacy `/api` routes to `/autocomplete`

- .github/workflows/database-backup.yml
DB backup failure after making the RBAC change: https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/7720580472/job/21045713443
Add the missing kubelogin
It's the same setup as the deploy workflow
> [937] Add missing kubelogin to DB backup workflow

- app/controllers/api/guide_controller.rb
- app/views/api/guide/show.md
- app/views/layouts/api/guide.html.erb
- config/routes/api_routes.rb
- spec/requests/api/v0.1/guide_spec.rb
Need to set up the framework to store the content of the documentation
* adds a "guide" route and controller into the api route structure 
* uses markdown to render a simple guidance page via `show`
run locally and visit `/api/v0.1/guide`
> [6668] initial api documentation set up framework to read content

- app/components/reinstatement_details/view.html.erb
- app/components/reinstatement_details/view.rb
- app/controllers/trainees/confirm_reinstatements_controller.rb
- app/controllers/trainees/reinstatements/update_end_dates_controller.rb
- app/controllers/trainees/reinstatements_controller.rb
- app/forms/itt_end_date_form.rb
- app/services/form_store.rb
- app/views/trainees/confirm_reinstatements/show.html.erb
- app/views/trainees/reinstatements/show.html.erb
- app/views/trainees/reinstatements/update_end_dates/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/components/reinstatement_details/view_preview.rb
- spec/components/reinstatement_details/view_spec.rb
- spec/controllers/trainees/confirm_reinstatements_controller_spec.rb
- spec/features/trainee_actions/reinstating_a_trainee_spec.rb
- spec/forms/itt_end_date_form_spec.rb
Expected end date
Added the ability for a provider to update the expected end date when reinstating the trainee
There are 2 journeys.
The new journey of a trainee being reinstate and the course is in the past.  
Existing journey of a trainee being reinstate but the course is in the future, this will bypass the need to update the expected end date, this stays as is.
> [6620] Add new page updating expected end date when trainees are reinstated

- app/models/placement.rb
- app/models/reports/trainee_report.rb
- app/services/placements_imported_from_hesa.rb
- spec/models/reports/trainee_report_spec.rb
- spec/services/placements_imported_from_hesa_spec.rb
Providers have reported that placements added manually or bulk uploaded appear in the wrong order in the trainees CSV download. This is because we deliberately reverse the order due to them being wrong when imported from HESA.
We need to avoid reversing placements when exporting trainees unless those placements have been imported from HESA.
- I've extracted the workaround logic into a `PlacementsImportedFromHesa` service.
- I tried this on the review app by adding two placements to this trainee and checking the export https://register-pr-3966.test.teacherservices.cloud/trainees/bNFu297ao6FfvjNviCSSDRfA
> [6628] Fix placements CSV export placements in wrong order

- .github/workflows/database-backup.yml
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/7735617030/job/21092772758
Fix environment name
Run: `make ci staging get-cluster-credentials`
> [937] Fix environment name in DB backup job

- app/controllers/bulk_update/recommendations_uploads_controller.rb
- spec/features/bulk_upload/recommending_trainees_spec.rb
- spec/support/recommendations_uploads_helper.rb
A provider has reported errors when attempting to upload a CSV for bulk recommendations. This is happening because when a provider uploads an invalid CSV file (maybe because it’s too large or the wrong format) we attempt to render the new view. This fails because it relies on a Navigation component that doesn’t get instantiated in this case. As a result the provider doesn’t see a helpful error message, just a ‘something went wrong page’.
Sentry error:
https://dfe-teacher-services.sentry.io/issues/4848046002/events/9d7491cb77f04b6bb980d6437e1f99b3/
https://trello.com/c/4SXGEhnO/6734-fix-error-handling-for-bulk-recommend
- Fix the bug in the `BulkUpdate::RecommendationsUploadsController` by instantiating the `Funding::NavigationView` component before rendering the `new` view.
- Add a …
> [6734] Add test for bulk recommend with invalid CSV

- app/lib/funding/parsers/base.rb
We recently introduced a fix to handle very weird invisible characters in funding upload csv files https://github.com/DFE-Digital/register-trainee-teachers/pull/4001/commits/e4b1efcbc6c57d1b99a7e0e988e673283918d595.
Adding the same check for when the data is actually built via `to_attributes` otherwise it'll run into a similar error by one of the `Funding::*Importer` classes.
> [xxx] Fix headers in Funding::Parsers::Base

- app/components/course_details/view.rb
The update course details confirm page was throwing an error when the user selected an 'other' secondary subject. This was because the `primary_course_subject` method was comparing the data model's `primary_course_subjects` attribute (which is a string) to the symbol `:other`.
Relates to [this bug report in Trello](https://trello.com/c/C8njszCP/6722-performance-profiles-sign-off), introduced by [this commit](https://github.com/DFE-Digital/register-trainee-teachers/commit/2f013dbf706915c72c9a2d4ea9045e4b7bd21558).
Compare apples with apples; don't compare apples with oranges.
> Fix primary course confirm page bug

- Gemfile
- Gemfile.lock
- config/initializers/rack_attack.rb
- config/settings.yml
This PR sets up the rack-attack gem to help us prevent abusive requests for the Register API. 
- Sets up a way to block requests from an IP list
- Sets up a way to block requests from specific user agents (bots, etc)
- Sets up a basic throttling configuration which can be changed in settings
Does it make sense?
> [6671] Basic Rack attack setup for API

- config/initializers/filter_parameter_logging.rb
- config/initializers/semantic_logger.rb
- config/initializers/sentry.rb
This PR just glazes a few bits on top of what's already in place to help filter out PII/sensitive info from logs/sentry. 
- Filter out TRNs from Sentry
- Filter out `Authorisation` header from logs
- Reduce Sentry's noise level so it only outputs `[INFO]` calls in the logger
> [6718] Filter out any other sensitive info

- app/controllers/api/base_controller.rb
- app/controllers/api/trainees/withdraws_controller.rb
- app/controllers/api/trainees_controller.rb
- app/controllers/concerns/api/validations_and_error_handling.rb
- config/routes/api_routes.rb
- spec/requests/api/v0.1/trainees/withdraw_spec.rb
- spec/requests/api/v0.1/trainees_spec.rb
An endpoint for withdrawing a trainee.
Added an endpoint to withdraw a trainee
Trainee existences otherwise 404.
Only withdraw-able trainee will be withdrawn
Basis errors for invalid parameters (need to move to form)
Standardised the error format, same/similar to `Apply` see [here](https://www.apply-for-teacher-training.service.gov.uk/api-docs/v1.4/reference#error-object)
Form to be done in another PR?
```
curl --request POST \
--url 'http://#replace_me/api/v0.1/trainees/#replaceme/withdraw?withdraw_date=1&withdraw_reasons_details=2' \
--header 'Authorization: #replace_me' 
```
> [6715] Endpoint post trainees withdraw

- app/models/reports/trainee_report.rb
- app/models/reports/trainees_report.rb
- spec/models/reports/trainee_report_spec.rb
Small one to address having a `?` in column headers for CSV exports.
- Updates the column header in the export
- Aliases method so rubocop doesn't complain over `is_*?` method names
Test out the export in the review app
> [6678] Fix complete? column in export

- app/models/authentication_token.rb
Just a tidy up. I think the autogenerated comments for the `AuthenticationToken` schema got out of sync. 
Just reran `bundle exec rails db:migrate` to fix it.
> Fix out of synch schema comments

- app/controllers/api/base_controller.rb
- app/services/trainees/create_timeline_events.rb
- spec/requests/api/v0.1/audit_trail_attribution_spec.rb
- spec/services/trainees/create_timeline_events_spec.rb
Whenever an API call runs that modifies application data we create audit records to track whatever changes are made. So that we can trace these changes back to the provider that performed them we need to make sure that every audit record created via the API is attributed to the authenticated provider.
- Add a `BaseController#authenticated_user` method returning the `current_provider`. The `audited` gem should pick this up and attribute all audit records created during the API call to the authenticated provider.
- Also fixes the timeline to handle provider users. It was broken by provider users in the audit trail due to assumptions made in `CreateTimelineEvents`. So those are fixed and I've flagged provider user entries as coming via the API.
Not ready yet. We can add a couple of tests for …
> [6676] Declare current_provider as the user for auditing

- app/lib/malware_scan.rb
- spec/lib/malware_scan_spec.rb
Uploads from register are stored in the tempdata blob service, not "uploads" 
corrects the scan job to look under tempdata
> [xxxx] - corrects the path that malware scanning job looks under

- app/lib/dqt/params/update.rb
- app/models/dqt/teacher.rb
- app/services/dqt/sync_teacher.rb
- config/analytics_blocklist.yml
- db/migrate/20240208131836_add_pii_field_to_dqt_teachers.rb
- db/schema.rb
- spec/lib/dqt/params/update_spec.rb
DQT have started sending us a parameter to let us know if the trainee's PII information can be updated when sending update requests. This PR adds the ability to do that.
Currently, we sync all the DQT teacher records to a local table and link them up to each respective trainee. Every trainee sent to DQT will have[ at least one](https://github.com/DFE-Digital/register-trainee-teachers/blob/e629eebc8e4a0118af86c0ee9ba4a365d4387a23/app/models/trainee.rb#L156) `trainee.dqt_teacher` record. 
The syncing is done every Monday via https://github.com/DFE-Digital/register-trainee-teachers/blob/e629eebc8e4a0118af86c0ee9ba4a365d4387a23/app/services/dqt/sync_teacher.rb#L4 in:
- Add the field to the `DqtTeacher` table so we can easily check for it via the `trainee`
- Conditionally merge in PII fields …
> [6751] Update PII info when sending DQT updates if allowed

- app/services/add_ethnicity_from_csv.rb
- db/data/20240208151204_add_ethnicity_to_best_practice_network.rb
- lib/tasks/diversity.rake
- spec/services/add_ethnicity_from_csv_spec.rb
#4021 didn't quite work as expected. This adds a rake task and service for importing ethnicity data.
Ideally we would get bulk import files formatted correctly, but often this isn't the case. this is a quick service for correcting ethnicity. it was previously in a migration task, but there is a good chance we will need to run this again in the future, hence the introduction of a service.
_note: this has been run on production data and the data sampled/checked_
> [6704] - adds service for importing ethnicity via rake task and upload

- app/services/trainees/create_from_hesa.rb
- db/data/20240212171923_rollback_backfill_missing_hesa_deferral_dates.rb
- spec/services/trainees/create_from_hesa_spec.rb
Changes were previously made in https://github.com/DFE-Digital/register-trainee-teachers/pull/3956 which changed the logic for setting the `defer_data` (as per this [Trello card](https://trello.com/c/GEjEZ4V5/1405-infer-a-deferred-date-if-one-was-not-supplied-at-the-time-of-deferral)). A data migration was also created to backfill missing deferral dates.
However, it turns out that setting the `defer_date` in this way is not the most helpful thing for ITT funding so we want to revert the previous changes.
* Removed all code to set the `defer_date` in `CreateFromHesa` because the previous `end_date` value is not being used by HESA any more.
* Added a data migration to 'reset' the `defer_date` to `nil` for records that were previously populated, based on [the suggested …
> [6768] Rollback deferral date logic change

- app/components/funding/view.rb
- config/locales/en.yml
We added some new bursary fields as part of this original PR https://github.com/DFE-Digital/register-trainee-teachers/pull/3625/files. If these fields are missing, currently the application [errors](https://dfe-teacher-services.sentry.io/issues/4979945187/?alert_rule_id=4544549&alert_type=issue&environment=production&notification_uuid=f8dfacff-7852-4494-abe0-25c003109f6e&project=5552118&referrer=slack) as we have not mapped their missing fields properly. 
- Declare the new fields as potential missing attributes in the translation lookup
Before:
After:
This can be tested against the original trainee which triggers the error https://www.register-trainee-teachers.service.gov.uk/trainees/txHSffNT8zaWZWv2hxC3qrQn in production data.
> [6789] Fix missing fields mapping

- terraform/aks/workspace-variables/sandbox.tfvars.json
We created the sandbox environment but it requires a `replicas` value to be on.
> [6811] Fix sandbox health checks

- Gemfile.lock
While we're waiting to be able to [move to sidekiq v7](https://github.com/DFE-Digital/register-trainee-teachers/pull/4043), it makes sense to update to the latest v6.
* Bump sidekiq from 6.5.8 to 6.5.12
* Make sure nothing is broken.
> Bump sidekiq from 6.5.8 to 6.5.12

- .github/workflows/database-backup.yml
Daily backup can take over 60 minutes, and this causes the backup to fail as the konduit timeout default is 3600 seconds for backups.
Increase timeout to 7200 (2 hours)
review code update
> Increase konduit timeout for db backup to 7200

- app/components/sort_by/view.html.erb
- app/components/sort_by/view.rb
- app/controllers/system_admin/dead_jobs_controller.rb
- app/controllers/system_admin/pending_awards_controller.rb
- app/controllers/system_admin/pending_trns_controller.rb
- app/services/dead_jobs/base.rb
- app/views/system_admin/dead_jobs/show.html.erb
- app/views/system_admin/pending_awards/index.html.erb
- app/views/system_admin/pending_trns/index.html.erb
- spec/features/system_admin/dead_jobs/sorting_dead_jobs_spec.rb
- spec/features/system_admin/pending_awards/sort_by_pending_awards_spec.rb
- spec/features/system_admin/pending_trns/sort_by_pending_trns_spec.rb
- spec/support/features/page_helpers.rb
- spec/support/page_objects/system_admin/dead_jobs/dead_jobs_dqt_update_trainee.rb
- spec/support/page_objects/system_admin/pending_awards/pending_awards.rb
- spec/support/page_objects/system_admin/pending_trns/pending_trns.rb
DQT support team would like to be able to sort/order dead jobs by fields such as TRN, name(s), days waiting. job status etc
adds a sort-by feature to dead jobs, pending awards and pending TRNS. Defaults to "Days waiting"
This is a little tricky to test locally as you'll need real data to see pending awards/TRNS. as for dead jobs this is probably only testable in production as most/all other environments won't have any.
> [6578] - adds sorting to admin views

- app/controllers/application_controller.rb
- app/controllers/funding_controller.rb
Fixes the following [Sentry error](https://dfe-teacher-services.sentry.io/issues/4976329281/?environment=production&project=5552118&referrer=issue-stream&statsPeriod=7d&stream_index=0).
It's quite difficult to re-produce these sort of issues where the context of the organisation is crucial. I've set this as a Sentry tag to help debug in the future.
> [6812] Handle nil case for year based on Sentry error

- app/controllers/application_controller.rb
Check for organisation as system admins do not have one.
> [xxx] Check for organisation 

- app/helpers/navigation_helper.rb
> [6680] Fix funding nav item

- app/components/header/view.html.erb
Navigation menu drop down always shows in Firefox if JS is disabled
**Before**
**After**
> [6679] - show nav menu toggle only when js is enabled

- config/settings/sandbox.yml
Sandbox at the moment is pulling apply applications from Apply's live environment. This PR updates the url to use their sandbox environment so the pipeline is consistent.
> [xxx] Use correct apply import url

- app/forms/personal_details_form.rb
- app/models/api/trainee_attributes/v01.rb
- app/validators/personal_details_validations.rb
After [this spike](https://trello.com/c/h9FjRGd7/6823-spike-investigate-different-approaches-to-route-based-validation-implementation) we have decided that validation logic for each Form service used in the trainee creation journey should be pulled, making each available to: API, UI, BulkUpdate. with the latter two being the focus of this ticket.
* Pulls personal detail validations into a separate module
* New module  is used in TraineeAttributes and PersonalDetailsForm
* sanity check approach
* are we happy with moving all these validations into `app/validators/xxxx_xxxx_validations.rb`
> [6843] - extract PersonalDetailsForm validation

- app/services/api/create_trainee.rb
- spec/requests/api/v0.1/post_trainees_spec.rb
We assume that trainees coming from vendors can be registered and submitted for a TRN, as long as they pass our validation checks.
- Submits the trainee for TRN on save in `Api::CreateTrainee`
The submission will need to be wrapped by our `TrnValidator` checks. There is [currently a spike on this](https://github.com/DFE-Digital/register-trainee-teachers/pull/4123) but leaving a note here.
> [6868] Submit trainee for trn on API POST

- .github/workflows/reset-sandbox-database.yml
- lib/tasks/vendor.rake
- spec/lib/tasks/vendor_create_spec.rb
- spec/lib/tasks/vendor_swap_spec.rb
API setup providers in sandbox for vendor testing
Restore sanitised database
Swap a number of named vendors
Swap ten vendors
Send a slack message regardlessly
Due to github action limitations ie, the workflow needs to be merged in so that the `workflow_dispatch` can work hence this [commit](https://github.com/DFE-Digital/register-trainee-teachers/pull/4129/commits/355d74ca04530f0bb3d653a1ea2a47f79aa0e1cb) as a stop gap to flush it issues prior to merge
Added tokens to be displayed 
> [6863] Api Set up providers in sandbox for vendor testing

- app/models/api/trainee_attributes/v01.rb
- app/services/api/map_hesa_attributes/v01.rb
- spec/models/api/trainee_attributes/v01_spec.rb
- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
https://trello.com/c/gsX6phzU/6907-check-hesa-mapping-for-sex-is-working-for-post-trainee
I couldn't reproduce the issue with the `sex` attribute, seems to work fine when given the correct params but I did notice another issue around properly setting the `course_allocation_subject` which I've addressed.
- Updates mapper and trainee attributes class to set `course_allocation_subject` via the `course_allocation_subject_id` so ActiveRecord doesn't blow up expecting an instance when a hash of attributes for the course allocation subject is given.
You can verify this with the same request params locally to assert the trainee does get created:
```json
{
"data": {
"first_names": "John",
"last_name": "Doe",
"date_of_birth": "1990-01-01",
"sex": "11",
"email": "john.doe@example.com", …
```
> [6907] Fix course allocation subject issue

- .github/actions/bring-docker-image-up/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/build-nocache.yml
- .github/workflows/tests.yml
- docker-compose.yml
- docs/setup-development.md
- docs/testing.md
Our GH action builds use docker compose v1 command which is being removed. See https://github.com/actions/runner-images/issues/9557
* Change `docker-compose` to `docker compose`
* GH Actions succeed
> Update docker compose command to v2

- app/views/trainees/reinstatements/update_end_dates/show.html.erb
recurring [error seen here](https://dfe-teacher-services.sentry.io/issues/4972605330/?alert_rule_id=4544549&alert_type=issue&environment=production&notification_uuid=5644104a-3048-4305-8502-7f23060b5a93&project=5552118&referrer=slack) is crashing the reinstatement journey.
Hides the hint which tells user to use the existing `itt_end_date`. Code incorrectly assume this always exists.
> [6896] - Hide hint if no itt_end_date (undefined method `to_fs')

- app/controllers/api/trainees_controller.rb
- app/models/api/hesa_trainee_detail_attributes/v01.rb
- app/models/api/trainee_attributes/v01.rb
- app/services/api/create_trainee.rb
- spec/requests/api/v0.1/duplicate_trainees_spec.rb
- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
When POSTing a Trainee, some fields are not required when they should be:
- nationality
- itt_aim
- itt_qualification_aim
- year_of_course
- course_age_range
- fund_code
- funding_method
- hesa_id
this fixes the `hesa_trainee_details` to write these attributes and require them via validation callback in CreateTrainee
> 6962 some trainee fields arent required but should be

- app/jobs/bulk_update/analytics_job.rb
- config/initializers/dfe_analytics.rb
- config/settings.yml
- config/settings/sandbox.yml
- spec/jobs/bulk_update/analytics_job_spec.rb
Guard against using dfe analytics when disabled
Added guard against using dfe analytics when disabled
https://github.com/DFE-Digital/dfe-analytics
> [6973] Guard against using dfe analytics when disabled

- app/controllers/api/base_controller.rb
- app/controllers/api/trainees/degrees_controller.rb
- app/controllers/api/trainees/placements_controller.rb
- app/controllers/api/trainees/withdraw_controller.rb
- app/controllers/api/trainees_controller.rb
- app/lib/api/attributable.rb
- app/lib/api/serializable.rb
- app/services/api/append_metadata.rb
- app/services/api/create_trainee.rb
- app/services/api/find_duplicate_trainees.rb
- app/services/api/trainees/save_degree_response.rb
- app/services/api/trainees/save_placement_response.rb
- app/services/api/trainees/withdraw_response.rb
- spec/services/api/append_metadata_spec.rb
- spec/services/api/find_duplicate_trainees_spec.rb
[6940-remove-progress-object-foreign-keys-and-any-internal-fields-from-responses](https://trello.com/c/hFL7lfYy/6940-remove-progress-object-foreign-keys-and-any-internal-fields-from-responses)
Follow up PR related with [PR 4187](https://github.com/DFE-Digital/register-trainee-teachers/pull/4187)
Addresses https://github.com/DFE-Digital/register-trainee-teachers/pull/4187#discussion_r1560811977 and proposes further refactoring.
* Rename `serializer` to `serializer_klass`
* Rename `serializer_class` to `serializer_klass`
* Rename `attributes_class` to `attributes_klass`
* Extract `serializer_klass` to `Api::Serializable`
* Extract `attributes_klass` to `Api::Attributable`
>  [6940] Refactor v01 Serializers - Part 2

- app/forms/submissions/api_trn_validator.rb
- app/services/api/create_trainee.rb
The `ApiTrnValidator` is not being used. This should be included in the validation process within CreateTrainee
https://ukgovernmentdfe.slack.com/archives/C03SR5B5EGH/p1712912778396529
checks the `ApiTrnValidator` for validation messages before saving the trainee
> [6977] - Use ApiTrnValidator

- config/initializers/rack_attack.rb
- spec/requests/api/rack_attack_spec.rb
We currently limit the http requests per IP address. This PR adds a request spec to test that behaviour of `Rack::Attack` with our configuration.
* Add a request spec to test throttling
* Remove `if Rails.env.local?` statement for `Rack::Attack` since we use `NullStore` in dev environment and the requests won't be throttled.
> [6968] Add a test for Rack::Attack throttling

- app/models/api/trainee_attributes/v01.rb
- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
- spec/requests/api/v0.1/put_trainee_spec.rb
[6985-potential-bug-providertraineeid-not-being-set
](https://trello.com/c/rnHluegR/6985-potential-bug-providertraineeid-not-being-set)
Fix for `Trainee#provider_trainee_id` not set on create / update
* Permit attribute for POST / (PUT | PATCH) trainee/s
> Allow Trainee#provider_trainee_id to be set

- app/models/api/trainee_attributes/v01.rb
- app/serializers/trainee_serializer/v01.rb
- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
- spec/requests/api/v0.1/put_trainee_spec.rb
- spec/requests/api/v0.1/updating_trainees_spec.rb
- spec/serializers/trainee_serializer/v01_spec.rb
Validation issue when updating a trainee
Fix validation issue when updating a trainee
Basically test to flush it out, fix it, and align the tests.
This issue only affects trainees that
- has a course 
- that can have a particular form of financial incentives
- for a particular academic year
- for a particular training route
Encompasses
https://github.com/DFE-Digital/register-trainee-teachers/pull/4215
https://github.com/DFE-Digital/register-trainee-teachers/pull/4214
> [6983] Fix validation issue when updating a trainee

- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
test to ensure date of birth does not have translation errors
Added test to ensure date of birth does not have translation errors
Previously there was a translation errors
Is the returned error object corrected?
> [6999] Added test to ensure date of birth does not have translation errors

- app/views/bulk_update/recommendations_checks/show.html.erb
https://trello.com/c/rKX6nPIY/7000-recommending-trainee-teachers-for-qts-error
Provider getting error when trying to bulk recommend 52 trainees for QTS via CSV file.
* Fix syntax for govuk_accordion `id` setting
* Try uploading a CSV for bulk recommendation which has more than 50 trainees, so the accordion is displayed
> [7000] Fix error when bulk recommending Trainee teachers for QTS 

- app/models/api/degree_attributes/v01.rb
[7022-investigate-flakey-test-for-duplicate-degrees](https://trello.com/c/AJRoZpzs/7022-investigate-flakey-test-for-duplicate-degrees)
When the `country` is not submitted in the params the `locale_code` would default to `"uk"` by the return value of `Api::MapHesaAttributes::Degrees::V01#locale_code`.
In combination with the fact that the `exists?`
query would check with both `{ locale_code: "uk", country: nil }` could result in inconsistencies in the return value of `duplicates?`
* Don't use the `locale_code` to check for duplicates
* Remove any `nil` values that may come from the request body when checking for duplicates
> [7022] Refactor Api::DegreeAttributes#duplicates?

- app/controllers/api/trainees_controller.rb
- app/serializers/hesa_trainee_detail_serializer/v01.rb
- app/serializers/trainee_serializer/v01.rb
- spec/serializers/trainee_serializer/v01_spec.rb
The data in the HESA trainee details fields didn't seem to be returned correctly by the serializer.
* Amended and refactored the `HesaTraineeDetailSerializer` to return data and be more like the other serializers
* Added a test to catch missing data being returned from serializer
* Tweaked a couple of other things
Check that values are returned for the HESA trainee details fields for trainees created by the API
> [7035] Fix HESA Trainee details serializer

- app/services/api/map_hesa_attributes/degrees/v01.rb
- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
We had some old logic in the degree mapping, which was assuming that the graduation year is a date string. 
We're now checking if the provided date is a valid date first, or if just the year is given. 
> [7047] Graduation Year Bug

- app/views/api_docs/reference/v0.1/_reference.md
- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
The `previous_last_name` field in the API docs is wrongly called `previous_surname` and there was a question about whether this field was being correctly updated.
* Amended the API docs with correct field name
* Added `previous_last_name` to the POST Trainee spec
Check that API docs are accurate and the field can be set and updated.
> [7058] Update docs for `previous_last_name` and make sure its saved correctly

- .github/workflows/build-and-deploy.yml
- app/models/api/trainee_attributes/v01.rb
- app/services/api/map_hesa_attributes/v01.rb
- app/services/api/update_trainee_service/v01.rb
- spec/factories/trainees.rb
- spec/models/api/trainee_attributes/v01_spec.rb
- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
- spec/requests/api/v0.1/put_trainee_spec.rb
Validation for sex values
Added validation for sex
There is validation
`Api::TraineeAttributes::V01` (all those nested V01 attributes validations)
`Submissions::ApiTrnValidator` (ui forms validations)
so api is a little bit tighter then ui
There was a mapping issue `attributes` was overused to the point that there was an issue of is it referring to `parameter` or `self`.
There was a update issue where by it generated a new object rather than assigning attributes
Added `TraineeAttributesValidation` as a stop gap as the chain for `update` and `create` a trainee should be similar.
1. `Api::CreateTrainee` seems to be the more concise as it deals with 
1. validation for both `trainee_attributes` and `api_trn_validator`
2. returning the `right response` for creating a trainee
3.  the class is …
> [7055] Added validation for sex

- app/models/api/trainee_attributes/v01.rb
- app/services/api/map_hesa_attributes/v01.rb
- app/services/concerns/has_course_attributes.rb
- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
- spec/requests/api/v0.1/put_trainee_spec.rb
The study mode for the course wasn't being returned in API responses, even when it was provided in the request.
It turns out that the study mode wasn't being saved correctly when the trainee was created. So this adds the missing method to the mapping class so that it now gets included. 
> [7050] Return Study Mode in API Responses

- spec/factories/hesa/trainee_details.rb
- spec/serializers/trainee_serializer/v01_spec.rb
We [recently changed](https://github.com/DFE-Digital/register-trainee-teachers/pull/4222) the `hesa_disabilities` column on `hesa_trainee_details` from an array to a json column. But we didn't update the factory as part of that. We also still had some data in our test environment that was stored as an array, leading us to think there was a problem when serialising the data.
I've updated the factory to give us the correct value and added a test to the serialiser, so we know that we're getting exactly what we want. 
> Update Specs and Factory for HESA Disabilities

- app/models/api/trainee_attributes/v01.rb
- app/models/trainee.rb
- app/services/api/map_hesa_attributes/v01.rb
- spec/models/api/trainee_attributes/v01_spec.rb
- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
- spec/requests/api/v0.1/put_trainee_spec.rb
[7056-validate-ethnicity-values](https://trello.com/c/dt5AxKx9/7056-validate-ethnicity-values)
Trainee `ethnicity` was not validated for the HESA allowed values
* Add inclusion validation to `Api::TraineeAttributes` for ethnicity
* Add `attr_accessor :ethnicity` to `Trainee` to allow for the attribute to be assigned
* Remove from `Api::MapHesaAttributes::V01` `ethnicity` from the excluded `ATTRIBUTES`
> [7056] - Validate ethnicity values

- app/forms/course_details_form.rb
- app/forms/funding/training_initiatives_form.rb
- app/forms/personal_details_form.rb
- app/jobs/hesa/retrieve_collection_job.rb
- app/jobs/hesa/retrieve_trn_data_job.rb
- app/models/api/trainee_attributes/v01.rb
- app/models/concerns/sourceable.rb
- app/models/trainee.rb
- app/services/trainees/create_from_apply.rb
- app/services/trainees/create_from_csv_row.rb
- app/services/trainees/create_from_hesa.rb
- app/services/trainees/filter.rb
- app/views/trainees/training_routes/_form_fields.html.erb
- db/data/20220902100022_backfill_record_source_on_trainees.rb
- db/data/20220921084032_fix_apply_draft_training_routes.rb
- spec/features/trainee_actions/creating_a_new_trainee_spec.rb
- spec/jobs/hesa/create_from_hesa_job_spec.rb
- spec/jobs/hesa/retrieve_collection_job_spec.rb
- spec/jobs/hesa/retrieve_trn_data_job_spec.rb
- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
- spec/services/find_new_starter_trainees_spec.rb
- spec/services/trainees/create_from_apply_spec.rb
- spec/services/trainees/create_from_csv_row_spec.rb
- spec/services/trainees/create_from_hesa_spec.rb
- spec/services/trainees/filter_spec.rb
- spec/services/trainees/find_duplicates_spec.rb
We have a record_source column on the trainees table. This is a string column with only a certain number of allowed values. These were being defined in an initialiser called record_sources, which defined this module:
```ruby
module RecordSources
APPLY = "apply"
DTTP = "dttp"
HESA_COLLECTION = "hesa_collection"
HESA_TRN_DATA = "hesa_trn_data"
MANUAL = "manual"
API = "api"
ALL = [APPLY, DTTP, HESA_COLLECTION, HESA_TRN_DATA, API, MANUAL].freeze
end
```
This seemed like a good use case for an enum, so I've created a concern called Sourceable, which contains the enum and all of these string values as constants. 
I've included the concern in the Trainee model, so now trainees get all of the enum convenience methods, such as:
```ruby
trainee.api_record?
trainee.hesa_collection_record? …
```
> Refactor Record Sources

- .github/workflows/build-and-deploy.yml
As part of Zoonou accessibility testing, we are providing a static environment for them to assess changes made since their first pass.
https://trello.com/c/WpjA7ij1/7102-change-qa-so-that-zoonou-can-use-it-for-accessbility-testing-disabled-user-testing
removes QA from the deploy pipeline
> [7102] - temp remove QA from deploy pipeline

- app/services/sidekiq/remove_dead_duplicates.rb
The RemoveDeadDuplicates job runs every 2 minutes and expects there to be a trainee id in the dead job to find.
If there are jobs without this (in this case HESA failure) then the dead jobs service will continually fail trying to process these entries.
Guard against a nil trainee_id
> [7105] - guard against nil trainee_id and error in RemoveDeadDuplicates job

- app/controllers/api/trainees_controller.rb
- app/models/api/trainee_attributes/v01.rb
- app/models/trainee.rb
- app/services/api/create_trainee.rb
- app/services/api/map_hesa_attributes/v01.rb
- app/views/api_docs/reference/v0.1/_reference.md
- spec/models/api/trainee_attributes/v01_spec.rb
- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
- spec/requests/api/v0.1/put_trainee_spec.rb
[7051-some-fields-should-be-read-only](https://trello.com/c/RhSSe0Ge/7051-some-fields-should-be-read-only)
1. Ensure that `trn`, `ethnic_background` and `ethnic_group` cannot be manually set by request.
2. Resolve bug where if the `ethnicity` attribute was not included in the request body, then the `ethnic_background` and `ethnic_group` were defaulted to not provided.
This PR proposes the following changes:
* Remove `begin` block from `Api::TraineesController#update`
* Remove `trainee_update_params` from `Api::TraineesController`
* Remove `trn` from `TraineeAttributes::V01`
* Ensure that `Api::TraineesController#create` returns the newly created trainee nested in the `data` key
* Refactor `Api::MapHesaAttributes::V01` 
- Add `ethnic_group`, `ethnic_background` to `ATTRIBUTES` so as to be …
> [7051] - Some fields should be read-only

- app/models/api/hesa_trainee_detail_attributes/v01.rb
- app/models/api/trainee_attributes/v01.rb
- app/services/api/map_hesa_attributes/v01.rb
- config/analytics_blocklist.yml
- db/migrate/20240515134857_rename_hesa_trainee_details_postgrad_apprenticeship_start_date.rb
- db/schema.rb
- spec/factories/hesa/trainee_details.rb
- spec/models/api/trainee_attributes/v01_spec.rb
- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
- spec/requests/api/v0.1/put_trainee_spec.rb
- spec/serializers/trainee_serializer/v01_spec.rb
[7109-incomplete-data-returned-by-post-trainee-b](https://trello.com/c/JUX7zlm6/7109-incomplete-data-returned-by-post-trainee-b)
* Rename to `Api::HesaTraineeDetailAttributes::V01#pg_apprenticeship_start_date` to make it consistent with `Hesa::Metadatum#pg_apprenticeship_start_date`
* Allow the following to be set internally by the API based on
`employing_school_urn`, `lead_school_urn`:
- `lead_school_id`
- `lead_school_not_applicable`
- `employing_school_id`
- `employing_school_not_applicable`
> [7109] Incomplete data returned by POST trainee (B)

- docs/smoke_testing.md
Owing to the build process breaking recently, we need some guidance on what to do in the case of a DSI password reset.
Adds smoke testing guidance on how to reset passwords for the smoke testing account and update the corresponding GitHub action credentials.
Check this makes sense and is understandable/useful
> [xxxx] - updates the smoke test guidance

- config/application.rb
An IT Health Check was conducted on the Register service in April 2024. This is one of the recommendations from the report, that is to be remediated by the team “to enhance the overall security posture offered”.
[FID0024-2614_DfE_Register-ITHC-2024_v1_0.pdf](https://educationgovuk.sharepoint.com/:b:/r/sites/TeacherServices/Shared%20Documents/Becoming%20a%20Teacher/TWD-REGISTER/Register%20service%20BAU/Security/ITHC%20-%20APRIL%202024/FID0024-2614_DfE_Register-ITHC-2024_v1_0.pdf?csf=1&web=1&e=ZR0M91)
Issue no. 10
Issue: cookies not set with HttpOnly and Secure flag
Criticality: info
Report reference 6.1.6
Recommendation: Ensure cookies are set with the HttpOnly and Secure flags
Configured session cookies with `HttpOnly` flag to prevent client-side access. Set secure flag for cookies to …
> [7158] - Secure session cookies: set HttpOnly and Secure flags

- app/controllers/api/trainees_controller.rb
- app/serializers/trainee_serializer/v01.rb
- app/services/api/map_hesa_attributes/v01.rb
- app/services/concerns/has_course_attributes.rb
- spec/requests/api/v0.1/post_hesa_trainees_spec.rb
- spec/requests/api/v0.1/put_trainee_spec.rb
- spec/serializers/trainee_serializer/v01_spec.rb
https://trello.com/c/hX9mu2iQ/7110-incomplete-data-returned-by-post-trainee-c
* Serialize `course_subject_two` and `course_subject_three` to HESA format
> [7110] - Incomplete data returned by POST trainee (C)

- lib/tasks/cleanup.rake
- spec/fixtures/files/cleanup_emails.txt
- spec/lib/tasks/cleanup_trainees_spec.rb
- spec/lib/tasks/cleanup_users_spec.rb
[Trello](https://trello.com/c/lA8GyJm7)
[It's been found](https://educationgovuk.sharepoint.com.mcas.ms/:x:/r/sites/TeacherServices/_layouts/15/doc2.aspx?sourcedoc=%7BFCACCD27-B893-4ED0-A212-E37FAABBE6AF%7D&file=user_activity_2024.xlsx&action=default&mobileredirect=true) that we have several hundred Trainees in register that are considered inactive, because they haven't signed in for over a year, or they've never signed in at all.
This adds a rake task that can be given a text file full of emails addresses and it will discard (soft delete) them. There's a small chance that some users will want their account reinstated so soft deletes are preferred.
Once this is merged, I can create the text file with the email addresses on production and run the rake task with the file from there. 
NB: …
> [6971] Add Rake Task to Cleanup Stale Users

- config/initializers/dfe_analytics.rb
This was added to perform maintenance in BigQuery. We are now reverting this as the maintenance should be added through an environment variable rather than a code change.
Revert a previous commit.
> Revert BigQuery maintenance window

- app/models/api/v0_1/withdrawal_attributes.rb
- app/serializers/api/v0_1/trainee_serializer.rb
- app/services/api/get_trainees_service.rb
- app/views/api_docs/reference/v0.1/_reference.md
- config/locales/en.yml
- spec/models/api/v0_1/withdrawal_attributes_spec.rb
- spec/requests/api/v0_1/trainees/post_withdraw_spec.rb
- spec/serializers/api/v0_1/trainee_serializer_spec.rb
- spec/services/api/trainees/withdraw_response_spec.rb
https://trello.com/c/gDCbBL2E
We had feedback that the withdrawal `reasons` were not documented. We wanted to rectify that and also make sure they are validated.
* List all the valid withdrawal `reasons` in the API docs
* Validate the reasons against the current list of reasons
* Add the withdrawal reasons to the serializer so they appear in the API response
* Fix a Bullet warning
Does the `/withdraw` endpoint work as expected and are the docs clear and accurate.
> [7187] Validate withdrawal reasons against current list of reasons and add to docs

- app/controllers/api/trainees_controller.rb
- app/models/api/v0_1/trainee_attributes.rb
- app/services/api/v0_1/hesa_mapper/attributes.rb
- app/services/api/v0_1/update_trainee_service.rb
- spec/components/diversity/view_spec.rb
- spec/factories/disabilities.rb
- spec/factories/hesa/trainee_details.rb
- spec/factories/trainee_disabilities.rb
- spec/factories/trainees.rb
- spec/models/api/v0_1/trainee_attributes_spec.rb
- spec/models/reports/trainee_report_spec.rb
- spec/requests/api/v0_1/put_trainee_spec.rb
- spec/serializers/api/v0_1/trainee_serializer_spec.rb
Hesa disabilities and trainee disabilities
Ensure Hesa disabilities and trainee disabilities stays in sync
Ensure new additions does not remove exising
Ensure updating existing does not add addition
> [7190] Make sure existing disabilities aren't removed when new ones are added

- terraform/aks/application.tf
- terraform/aks/variables.tf
- terraform/aks/workspace-variables/dv_review.tfvars.json
- terraform/aks/workspace-variables/pen.tfvars.json
- terraform/aks/workspace-variables/productiondata.tfvars.json
- terraform/aks/workspace-variables/review.tfvars.json
- terraform/aks/workspace-variables/sandbox.tfvars.json
https://trello.com/c/T3eEa0zE/1763-migrate-register-to-google-oidc
Set enable_gcp_wif:true for worker deployments that send data to gcp
update terraform 
make env deploy-plan
> Enable enable_gcp_wif for workers

- terraform/aks/workspace-variables/review.tfvars.json
Enables workload identity federation in the Azure Infrastructure for review Apps. It is not used by the Application until we enable it explicitly within the App. 
Enables workload identity federation in the Azure Infrastructure Only, but not actually use it.
This is part of a wider DevOps change.
> Enable workload identity federation in Azure infrastrure only for review Apps

- config/initializers/dfe_analytics.rb
- config/settings.yml
- config/settings/review.yml
This is part of a wider BigQuery Assurance piece to to harden the security around BigQuery.
It allows the use of OAuth mechanism for authentication to BigQuery rather than relying on plain text JSON API Keys.
The Data Insights ticket is [here](https://trello.com/c/IDG7vXFy).
Enable Azure workload identity federation within DfE Analytics
See [Dfe Analytics GEM](https://github.com/DFE-Digital/dfe-analytics) for further details.
> Enable workload identity federation in the review App

- config/settings/qa.yml
- terraform/aks/workspace-variables/qa.tfvars.json
This is part of a wider BigQuery Assurance piece to to harden the security around BigQuery.
It allows the use of OAuth mechanism for authentication to BigQuery rather than relying on plain text JSON API Keys.
The Data Insights ticket is [here](https://trello.com/c/IDG7vXFy).
Enable Azure workload identity federation within DfE Analytics
See [Dfe Analytics GEM](https://github.com/DFE-Digital/dfe-analytics) for further details.
> Enable workload identity federation in the QA environment

- config/initializers/dfe_analytics.rb
- config/settings.yml
- config/settings/qa.yml
- config/settings/review.yml
- docs/big_query_setup.md
- terraform/aks/workspace-variables/pen.tfvars.json
- terraform/aks/workspace-variables/production.tfvars.json
- terraform/aks/workspace-variables/productiondata.tfvars.json
- terraform/aks/workspace-variables/sandbox.tfvars.json
- terraform/aks/workspace-variables/staging.tfvars.json
This is part of a wider BigQuery Assurance piece to to harden the security around BigQuery.
It allows the use of OAuth mechanism for authentication to BigQuery rather than relying on plain text JSON API Keys.
The Data Insights ticket is [here](https://trello.com/c/IDG7vXFy).
Enable Azure workload identity federation within DfE Analytics
See [Dfe Analytics GEM](https://github.com/DFE-Digital/dfe-analytics) for further details.
> Rollout workload identity federation to all environments

- jest.config.js
- package.json
- yarn.lock
https://trello.com/c/gle2qp5x/7274-resolve-high-severity-vulnerability-in-an-npm-package
`ebuild-jest` has a security vulnerability as found by dependabot. https://github.com/DFE-Digital/register-trainee-teachers/security/dependabot/106
The package has not been updated in three years, so we will replace it with `ebuild-jest-transform`
> [7274] Replace esbuild-jest package

- app/models/reports/bulk_recommend_report.rb
- app/models/reports/trainee_report.rb
- spec/models/reports/trainee_report_spec.rb
- spec/services/exports/bulk_recommend_export_spec.rb
[Trello](https://trello.com/c/hw6jt51K)
In some cases, when a user was downloading a CSV file to do a bulk recommendation, they were seeing two single quotes at the start and end of some values. For example, the CSV would show the hesa_id like this: 
`''1234567890123''`
The value in the database doesn't have these quotes, which pointed to something in the CSV generation, which must be altering the value before sending it to the user.
In the [BulkRecommendReport](https://github.com/DFE-Digital/register-trainee-teachers/blob/4dce11f9540db391bc053f810012c36000197389/app/models/reports/bulk_recommend_report.rb#L106) model, you can see that we're passing every value in the CSV through a [CsvValueSanitiser](https://github.com/DFE-Digital/register-trainee-teachers/blob/4dce11f9540db391bc053f81001 …
> Fix Quotation Mark Issue in Bulk Uploads

- app/models/academic_cycle.rb
- spec/support/features/course_details_steps.rb
A test started failing when we got to 1 July. I think this is because the new funding for the next academic year has not been set up yet and this start date in this test now falls in the next academic year.
* Temporarily change the start date until the funding has been added
> Change course start date to fix tests

- app/models/lead_partner.rb
- spec/factories/lead_partners.rb
- spec/models/lead_partner_spec.rb
We now know that there will be some SCITTs who were Accredited Providers and are now losing their accreditation and becoming Lead Partners. We need to treat them in a similar way to HEIs who are becoming Lead Partners.
* The Lead Partner model can accommodate SCITT providers
* Where Lead Partners are used in Register, they can be SCITTs, e.g.
* Support console
* Autocomplete
I think the only work needed here is to add a new `scitt` record type to lead partners, and to add some tests for that. I can't see any other logic around this that needs to change. 
> Add SCITT Providers to Lead Partners

- app/views/api_docs/reference/v1.0/_reference.md
- public/openapi/v1.0.yaml
- spec/requests/api/v1_0/trainees/post_withdraw_spec.rb
[Trello](https://trello.com/c/pw2kXUkK)
We want to refactor the withdraw endpoint to have the params sent in the request body (rather than the query string) so that it is consistent with the other POST ‘action’ endpoints like defer and recommend-for-qts.
The [withdrawal controller](https://github.com/DFE-Digital/register-trainee-teachers/blob/de2f12d48a63bf7dba6410291d1507bbceea9192/app/controllers/api/trainees/withdraw_controller.rb#L29) for the API already supported sending params in the request body, as well as query params. So the only things to update were the documentation and the [hopscotch settings](https://hoppscotch.io/). 
`api-docs/v1.0/reference#code-post-trainees-trainee_id-withdraw-code`
Updated by editing [app/views/api_docs/reference/v1.0/_reference.md](https://github.com/D …
> Refactor Withdraw Endpoint

- app/models/reports/trainee_report.rb
- app/services/bulk_update/recommendations_uploads/validate_csv_row.rb
Following on from https://github.com/DFE-Digital/register-trainee-teachers/pull/4405 there was an issue when prefixed `hesa_id`s were compared after the CSV upload.
* Sanitise both `hesa_id`s before comparing so that prefixed quotes `'` are ignored.
Generate a bulk award CSV, download it and add an award date, then upload it to check that no errors are shown.
> [7323] Fix bulk award uploads

- app/components/trainee_about/view.html.erb
- app/components/trainee_about/view.rb
- app/controllers/concerns/missing_fields_checkable.rb
- app/controllers/trainees/base_controller.rb
- app/controllers/trainees_controller.rb
- app/forms/degrees_form.rb
- app/forms/submissions/missing_data_validator.rb
- app/views/trainees/show.html.erb
- config/locales/en.yml
- spec/components/trainee_about/view_spec.rb
- spec/factories/trainees.rb
- spec/features/trainee_actions/recording_training_outcome_spec.rb
- spec/forms/submissions/missing_data_validator_spec.rb
Prevent trainees to be submitted for QTS award recommendation if they are missing a degree
[7308-prevent-qts-recommendation-being-made-in-register-ui-if-degree-information-has-not-been-added](https://trello.com/c/Rsaqpi4T/7308-prevent-qts-recommendation-being-made-in-register-ui-if-degree-information-has-not-been-added)
* Refactor to enable missing degrees validation to be triggered on recommend for QTS award
* Fix `#can_recommend_for_award?` to conditionally render the 'Recommend trainee for QTS' button
> [7308] Prevent QTS recommendation being made in Register UI if degree information has not been added.

- app/controllers/system_admin/duplicate_apply_applications_controller.rb
- app/services/teacher_training_api/import_course.rb
- config/initializers/training_routes.rb
- config/settings/test.yml
- spec/features/trainee_actions/change_course_spec.rb
- spec/features/trainee_actions/edit_trainee_training_route_spec.rb
- spec/services/teacher_training_api/import_course_spec.rb
- spec/support/api_stubs/recruits_api.rb
Preparing 2024-2025 academic year
Amended the course program type mapping for 2023-2024 and 2024-2025
This is for the 2023 to 2024 recruitment cycle courses in order to serve the 2024-2025 academic year to register a trainee
Amended the course program type mapping to training route as it changing as well.
`provider_led_postgrad_salaried` is no in place yet
You should be present with this view
nb, previously we envisaged it with `provider_led_postgrad_salaried` but that has since changed `school_direct_salaried`
Old mappings
|publish course program type|register training route|
|-|-|
|higher_education_programme |provider_led_postgrad|
|school_direct_salaried_training_programme |school_direct_salaried|
|school_direct_training_programme |school_direct_tuition_fee|
|scitt_programme …
> [7229] Amended the course program type mapping for 2023-2024 and 2024-2025

- app/forms/submissions/missing_data_validator.rb
- app/services/bulk_update/recommendations_uploads/trainee_lookup.rb
- app/services/bulk_update/recommendations_uploads/validate_trainee.rb
- app/views/trainees/show.html.erb
- spec/factories/trainees.rb
- spec/features/bulk_upload/recommending_trainees_spec.rb
- spec/services/bulk_update/recommendations_uploads/validate_trainee_spec.rb
- spec/support/features/page_helpers.rb
- spec/support/page_objects/bulk_update/recommendations_uploads/confirmation.rb
- spec/support/page_objects/bulk_update/recommendations_uploads/show.rb
[7309-prevent-qts-recommendation-being-made-in-bulk-recommend-if-degree-information-has-not-been-added](https://trello.com/c/qqPmzQQ9/7309-prevent-qts-recommendation-being-made-in-bulk-recommend-if-degree-information-has-not-been-added)
Validate trainees from CSV bulk upload to allow recommendation for QTS award
* Refactor `BulkUpdate::RecommendationsUploads::ValidateTrainee` by making use of `Submissions::MissingDataValidator`
> Prevent QTS recommendation being made in Bulk Recommend if degree information has not been added.

- app/views/trainees/training_routes/_form_fields.html.erb
- config/locales/en.yml
- spec/features/end_to_end/provider_led_postgrad_salaried_journey_spec.rb
- spec/features/trainee_actions/creating_a_new_trainee_spec.rb
Apply requested changes from Market Regs
[7333-revise-the-what-type-of-training-are-they-doing-page-for-2024-2025-academic-year](https://trello.com/c/DLD69f6E/7333-revise-the-what-type-of-training-are-they-doing-page-for-2024-2025-academic-year)
* Refactor `training_routes/form_fields.html.erb`
* Refactor `en.yml`
> [7333] Revise the What type of training are they doing? page for 2024-2025 academic year

- docs/support_playbook.md
- lib/tasks/remove_duplicates.rake
When trying to run this rake task, we noticed that the file path argument could not be found, even when it was explicitly specified.
This updates the task and the documentation around it, to reflect the now working version. 
> Fix RemoveDuplicates Rake Task

- app/controllers/api/base_controller.rb
- app/controllers/application_controller.rb
- app/controllers/concerns/api_monitorable.rb
- app/controllers/concerns/basic_authenticable.rb
- config/initializers/yabeda.rb
- config/routes.rb
- config/routes/system_admin_routes.rb
- docs/api-monitoring.md
- spec/requests/api/monitoring_spec.rb
- spec/requests/authentication_spec.rb
[Trello](https://trello.com/c/tVYRKhhR)
After speaking to @RMcVelia about what's needed to get Grafana set up for Register, it turns out that our `/metrics` endpoint is behind basic auth, so our Prometheus instance can't pull metrics from it at the moment. Prometheus also requires that the endpoint is just `/metrics` and not `system-admin/metrics` or anything like that. 
* I've moved the metrics route to the correct place and added a test to make sure that basic auth is not enforced.
* I've also added some additional metrics that I thought would be useful.
* Number of unsuccessful API requests
* The size (in bytes) of the responses we're sending. 
* The types of errors were returning, with their codes and messages.    
* Since the logic around monitoring was starting to grow, I moved it …
> Metrics Endpoint for API Monitoring 

- config/settings/productiondata.yml
We need to set the recruitment cycle to 2024 to get a supply of Apply applications to productiondata in order to test the integration for the new academic cycle.
I've also reset the last successful import timestamp manually for 2024 by deleting `ApplyApplicationSyncRequest` records. So once we deploy this hange we _should_ start seeing new Apply applications appear in productiondata.
Note that the 2 jobs that perform the import run at 1am and 4am.
Change Apply import to pull 2024 applications rather than 2023.
Is there anything missing?
We'll have to test this by either manually triggering the `RecruitsApi::ImportApplicationsJob` and then `Trainees::CreateFromApplyJob` once the first job finishes or waiting for the overnight run. …
> [7349] Switch productiondata to import 2024 Apply apps

- Gemfile
- Gemfile.lock
- app/lib/malware_scan.rb
- config/settings.yml
- config/storage.yml
- spec/lib/malware_scan_spec.rb
[Trello](https://trello.com/c/8PO7X0Ej)
Azure Storage Ruby client libraries will be retired on 13 September 2024.
https://github.com/testdouble/azure-blob has been developed as a replacement gem. This PR follows the migration steps there and makes other changes as necessary.
We have a library class called [MalwareScan](https://github.com/DFE-Digital/register-trainee-teachers/blob/main/app/lib/malware_scan.rb), which was using `Azure::Storage::Blob::BlobService` directly. The API for that is now different, so I've changed that class and the spec for it to use the new interface.  
Our version of Faraday was also being constrained because of the old gem. So I've updated this as well as part of this. 
* The new gem requires that the client is initialised with the name of an Azure container. I …
> Migrate to azure-blob Gem From azure-storage-blob

- app/models/api/v0_1/trainee_attributes.rb
- spec/factories/trainees.rb
- spec/models/api/v0_1/trainee_attributes_spec.rb
- spec/requests/api/v0_1/post_hesa_trainees_spec.rb
- spec/requests/api/v0_1/put_trainee_spec.rb
- spec/requests/api/v1_0_pre/post_hesa_trainees_spec.rb
- spec/requests/api/v1_0_pre/put_trainee_spec.rb
[7354-implement-itt-reform-on-register-api](https://trello.com/c/gMzDEEyF/7354-implement-itt-reform-on-register-api)
As part of the ITT reform introduce an inclusion validation for trainee training route
* Add an inclusion validation for `training_route` dependant on the ITT reform year
> [7354] Implement ITT reform on Register API - part 2

- app/components/route_indicator/view.rb
- app/views/trainees/funding/bursaries/_grant_form.html.erb
- app/views/trainees/funding/bursaries/_non_tiered_bursary_form.html.erb
- config/locales/en.yml
- spec/components/route_indicator/view_spec.rb
- spec/features/form_sections/teacher_training_data/apply_applications_spec.rb
Using the correct variant of ITT reform training route naming
To show the correct variant of ITT reform training route naming for next academic year
trainees/:slug/publish-course-details/edit?year=2023
> [7400] Added variant of itt reform training route naming

- app/models/academic_cycle.rb
Logic depending on this method is inaccurate on July 31st, since “end_date” has a time equal to the start of the day. 
So we specify the beginning of the start date and the end of the end date.
> Update AcademicCycle#current? Method to Include the Full End Date

- config/settings.yml
- spec/factories/trainees.rb
- spec/features/trainee_actions/recording_training_outcome_spec.rb
Recruitment cycle year and course year
Amended recruitment cycle year and default course year to `2024`
> [7229] Amended recruitment cycle year and default course year to `2024`

- spec/factories/trainees.rb
https://trello.com/c/VFds9crk/7177-update-existing-provider-led-routes-so-that-providers-can-optionally-add-a-lead-partner
Allow users to optionally add Lead Partner and Employing Schools on the new trainee journey. Also replaces Lead Schools with Lead Partners on the same journey and in the playback.
> [7177] Optionally add lead partner

- app/models/lead_partner.rb
- spec/features/funding/payment_schedule_spec.rb
- spec/models/lead_partner_spec.rb
Resolves issue with funding not been able to be rendered for Lead Partners
[7420-funding-page-error-for-carmel-college-in-productiondata
](https://trello.com/c/yivzaVig/7420-funding-page-error-for-carmel-college-in-productiondata)
* Delegate LeadPartner#funding_payment_schedules
> Delegate LeadPartner#funding_payment_schedules

- terraform/aks/workspace-variables/productiondata.tfvars.json
[7425-turn-off-productiondata-worker
](https://trello.com/c/YZpa5ud6/7425-turn-off-productiondata-worker)
This reverts commit eed1bb43f247d89f4f8c7d2eee87271a546c4c25.
* Switch off worker for `productiondata`
> Revert "Enable Sidekiq worker for productiondata"

- app/views/system_admin/lead_partners/index.html.erb
[Support console: remove 'type' column from Lead partners tab](https://trello.com/c/ZAvDqLhv/7423-support-console-remove-type-column-from-lead-partners-tab)
* Remove type column from Lead Partners system admin index page
> Remove type column from lead_partners#index

- app/views/guidance/_schools.html.erb
[This Sentry error](https://dfe-teacher-services.sentry.io/issues/5691326746/?alert_rule_id=4544549&alert_type=issue&environment=production&notification_uuid=c5995da4-b948-45b4-a408-5eadca24398c&project=5552118&referrer=slack) was caused due to a missing partial. This was removed as part of [this PR](https://github.com/DFE-Digital/register-trainee-teachers/pull/4527), thinking it was unused. So this puts it back for now. There are references to lead_school in here that will need to be updated or removed, but this will fix the bug for now. 
> Put Back Missing Partial for Schools

- app/services/trainees/create_from_apply.rb
- config/sidekiq_cron_schedule.yml
https://trello.com/c/R0hNBrBl/7452-missingcourseerrors-in-sandbox
Apply sandbox is trying to create courses that don't exist. For now we will disable the import job on the sandbox environment.
> unschedule create from apply job on sandbox

- .tool-versions
- app/lib/notify_on_timeout.rb
- app/services/dqt/trainee_update.rb
- package.json
Sentry trainee related error should use trainee slug and not id
Replaces ID with slug and provides a URL to the trainee
> [7460] - use slug in error reporting

- config/settings/production.yml
[Trello ticket](https://trello.com/c/GHtAFaXi/7504-turn-off-hesa-import-during-hesa-api-testing-window)
We want to switch off the HESA import, and any other HESA integrations, on `production`, before the testing period for the new HESA collection.
* Turn off features flags used by the HESA integration jobs
* Has anything been missed?
* Are they any unwanted implications of this?
> [7504] Disable HESA integration on production

- app/helpers/users_helper.rb
- app/policies/user_policy.rb
- spec/policies/user_policy_spec.rb
https://trello.com/c/7IS2Gfbn/7453-checking-leadpartneruser-all-over-the-place-rather-than-using-policy
Use UserPolicy for checking if a user is a lead_partner_user
> [7453] Replace `lead_partner_user?`

- config/settings/production.yml
[Trello ticket](https://trello.com/c/GHtAFaXi/7504-turn-off-hesa-import-during-hesa-api-testing-window)
We want to switch off the HESA import, and any other HESA integrations, on `production`, before the testing period for the new HESA collection.
* Turn off features flags used by the HESA integration jobs
* Has anything been missed?
* Are they any unwanted implications of this?
> [7504] Disable HESA integration on production (take 2)

- app/services/set_hesa_test_records.rb
Two TRNs were mixed up in the #4585 PR this corrects the mistake
> [7502] - correct TRN

- app/services/trainees/create_from_hesa.rb
- spec/services/trainees/create_from_hesa_spec.rb
https://trello.com/c/9eFE9tuU/7505-implement-lp-to-ap-matching-for-2024-2025-for-7-partnerships
There are seven formerly accredited providers who will be importing trainees for the 24-25 academic cycle. The ex-accredited provider will be set as the lead partner and the new accredited provider will be set in their place.
> [7505] - Add ex accredited provider to new accredited provider mapping

- terraform/aks/databases.tf
- terraform/aks/variables.tf
- terraform/aks/workspace-variables/production.tfvars.json
We’ve received production Postgres CPU usage alerts and usage will keep increasing as the API is released. 
So we would like to upgrade to a more powerful server.
There may be some service impact, so this will be merged at 6pm Wed 28th.
Change from GP_Standard_D2ds_v4 to GP_Standard_D4ds_v5
which increases
- from 2 to 4 vcpu
- from 8G to 16G 
Separate the snapshot db (analysis) sku as that uses the same setting as prod, and that doesn't need to be updated.
make production deploy-plan
> Upgrade prod postgres sku to GP_Standard_D4ds_v5

- docs/support_playbook.md
An issue was identified where the incorrect `provider_type` on Publish prevented the creation of trainees on Register. 
This misalignment disrupted the normal flow of application data between systems, leading to missing trainees.
Added guidance to the support playbook to assist in addressing this issue should it arise again.
:shipit: 
> [7515] Add Developer Support guidance for: Resolving Incorrect `provider_type` on Publish, Ensuring Trainees are Created on Register

- app/services/trainees/create_from_hesa.rb
- spec/services/trainees/create_from_hesa_spec.rb
- spec/smoke/login_spec.rb
As the create from HESA process also updates existing trainees, we want to make sure that we only apply the LP to AP matching for trainees in academic year 2024 and onwards.
* Add logic to check the start academic year is 2024 or later before doing LP to AP matching
* Does the new logic make sense?
> [7352] Update Lead Partner to Accredited Provider mapping for 2024 onwards

- app/models/trainee.rb
- db/schema.rb
- spec/models/trainee/state_transitions_spec.rb
- spec/services/bulk_update/recommend_spec.rb
- spec/services/trainees/create_timeline_events_spec.rb
https://trello.com/c/mg1yfcVM/7534-update-degree-requirement-for-recommend-for-qts-endpoint
Change `recommend_for_award` transition so that it requires degree information to be present
> [7534] Improve validation for api recommend-for-qts endpoint

- app/controllers/trainees/degrees/type_controller.rb
- app/controllers/trainees/degrees_controller.rb
- app/policies/degrees/trainee_policy.rb
- spec/factories/trainees.rb
- spec/features/system_admin/trainees/edit_a_trainee_spec.rb
- spec/policies/degrees/trainee_policy_spec.rb
- spec/support/features/trainee_steps.rb
- spec/support/page_objects/trainees/record.rb
[7526-change-bat-support-admin-permissions-to-remove-dependency-on-provider-membership-in-register](https://trello.com/c/lUgCZQz6/7526-change-bat-support-admin-permissions-to-remove-dependency-on-provider-membership-in-register)
* Allow System admins to add new degrees to Trainees
* Add `Degrees::TraineePolicy`
* Override `authorize_trainee` in `Degrees::TypeController`, `Trainees::DegreesController`
> [7526] Change BAT Support admin permissions

- lib/tasks/trainees_create_from_apply.rake
- spec/factories/apply_applications.rb
- spec/lib/tasks/trainees_create_from_apply_spec.rb
There is a gap, whereby an applicant can be a trainee missing vital checkpoints.
Added ability to be able to go back in time to add a trainee.
A provider on `apply` finally gets around to marking an applicant/candidate as recruited`` after the end of the academic year has elapsed.
> [7501] Added a rake task to manuelly import apply application and creation of trainners

- app/models/api/v0_1/trainee_attributes.rb
- app/services/api/v0_1/hesa_mapper/attributes.rb
- app/services/concerns/has_course_attributes.rb
- app/services/concerns/primary_course_subjects.rb
- app/services/trainees/create_from_csv_row.rb
- app/services/trainees/create_from_hesa.rb
- spec/requests/api/v0_1/post_hesa_trainees_spec.rb
- spec/requests/api/v0_1/put_trainee_spec.rb
- spec/requests/api/v1_0_pre/post_hesa_trainees_spec.rb
- spec/requests/api/v1_0_pre/put_trainee_spec.rb
[7585-investigate-issues-saving-serialising-coursemaxage-and-courseminage-with-post-trainees-api-endpoint
](https://trello.com/c/5hlI6uSg/7585-investigate-issues-saving-serialising-coursemaxage-and-courseminage-with-post-trainees-api-endpoint)
`course_max_age` wasn't be set as it was returning `params[:course_max_age]` instead the value from `course_age_range`.
There was also an issue with `course_subjects` as the order of courses were determined in the HESA attributes mapper where for existing trainees on update the order of subjects could not been determined as the Trainee record is not available.
* Fix issue determining course_min_age and course_max_age based on course_age_range
* Extract course subjects order logic to `PrimaryCourseSubjects` concern …
> [7585] Refactor course_min_age, course_max_age

- spec/smoke/login_spec.rb
[DfE Sign-In pages have been changed slightly](https://ukgovernmentdfe.slack.com/archives/C5S500XB6/p1727856661948639) on `pre-prod` so our smoke tests are failing on `staging` which is preventing deploys to `production`.
* Update smoke test sign-in flow to click button based on the type of button, rather than button text, so future button text changes will not affect our smoke test.
* This should tolerate differences in button text between the different environments too.
> Make smoke test sign-in step resilient to button text changes

- .github/workflows/build-and-deploy.yml
- .github/workflows/database-backup.yml
relates to #4693 Disables production data auto-deploys and backup whilst checking Ambition and TeachFirst data
> [7544] - disable productiondata deploy/backup

- app/models/api/v0_1/placement_attributes.rb
- app/models/placement.rb
- app/serializers/api/v0_1/placement_serializer.rb
- app/services/api/trainees/save_degree_response.rb
- app/services/api/trainees/save_placement_response.rb
- app/validators/postcode_validator.rb
- app/views/api_docs/reference/v0.1/_reference.md
- app/views/api_docs/reference/v1.0-pre/_reference.md
- public/openapi/v0.1.yaml
- public/openapi/v1.0-pre.yaml
- spec/components/placements/view_spec.rb
- spec/factories/placements.rb
- spec/factories/trainees.rb
- spec/features/form_sections/teacher_training_data/placements/deleting_trainee_placements_spec.rb
- spec/forms/placement_form_spec.rb
- spec/forms/placements_form_spec.rb
- spec/models/api/v0_1/placement_attributes_spec.rb
- spec/models/placement_spec.rb
- spec/models/reports/trainee_report_spec.rb
- spec/requests/api/v0_1/trainees/post_placement_spec.rb
- spec/requests/api/v0_1/trainees/put_placement_spec.rb
- spec/requests/api/v1_0_pre/trainees/post_placement_spec.rb
- spec/requests/api/v1_0_pre/trainees/put_placement_spec.rb
- spec/serializers/api/v0_1/placement_serializer_spec.rb
- spec/services/api/trainees/save_placement_response_spec.rb
- spec/services/trainees/create_timeline_events_spec.rb
- spec/services/trainees/get_placement_name_from_audit_spec.rb
[7602-update-api-documentation-for-placements](https://trello.com/c/oKK5xr0C/[7602-update-api-documentation-for-placements)
Refactor and update documentation for placements endpoints to ensure parity with the frontend implementation
- Make `name` required if school record cannot be found by `urn`
- Don't allow the `school_id` to be set by the request body
- Don't allow `address` to be set by the request body. Instead return the `Placement#full_address`
- Delegate `urn`, `postcode` to School
- Update OpenApi docs
> [7602] Update API documentation for Placements

- app/services/trainees/create_from_hesa.rb
[Trello Card](https://trello.com/c/0VkhyWjz/7672-lead-partner-showing-in-register-when-not-reported)
* Added a check for blank `lead_partner_urn`s
> [7672] Add check for blank lead partner URN

- db/data/20241021090400_fix_data_for_wrong_lead_partner_from_hesa_import.rb
[Trello card](https://trello.com/c/0VkhyWjz)
[A bug](https://github.com/DFE-Digital/register-trainee-teachers/pull/4733) has caused an incorrect lead partner to be set for trainees that have been imported from HESA. We need to update these trainee records with the intended data which was a blank lead partner URN.
We have considered the following:
1. Are there any circumstances under which lead partner `1335` should be set?
* No, we don't think there are, because we know of no partnerships with any HEIs for `1335` for 2024, and for previous years this lead partner could not have been a lead school.
3. New trainees from HESA and updates to existing trainees from HESA
* We want to update both these scenarios which have been affected.
4. Trainee records which have `hesa_editable = true`
* If …
> [7672] Data migration to correct Lead Partner for HESA trainees

- Gemfile
- Gemfile.lock
[7664-remove-pii-from-logs-sent-to-logitio](https://trello.com/c/hqiak3Al/7664-remove-pii-from-logs-sent-to-logitio)
The app is currently logging sql queries in the Sidekiq workers. 
`rails_semantic_logger` `4.17.0` implements changes to their Sidekiq logging mechanism https://github.com/reidmorrison/rails_semantic_logger/compare/v4.16.0...v4.17.0
By locking the gem to `4.16.0` seems to resolve the issue.
* Lock `rails_semantic_logger` to `4.16.0`
Can be tested locally by commenting out the `unless` statement at [semantic_logger.rb#L66](https://github.com/DFE-Digital/register-trainee-teachers/blob/main/config/initializers/semantic_logger.rb#L66)
> [7664] Remove PII from logs sent to logit.io

- app/controllers/api/trainees_controller.rb
- app/serializers/api/v0_1/degree_serializer.rb
- app/serializers/api/v0_1/trainee_serializer.rb
- spec/requests/api/v0_1/get_trainee_spec.rb
- spec/serializers/api/v0_1/degree_serializer_spec.rb
- spec/serializers/api/v0_1/placement_serializer_spec.rb
- spec/serializers/api/v0_1/trainee_serializer_spec.rb
[Investigate duplicate fields being returned from GET /trainees/{trainee_id}](https://trello.com/c/x4ueTgbj/7700-stub-investigate-duplicate-fields-being-returned-from-get-trainees-traineeid)
* Use `#with_indifferent_access` to allow for the keys to be merged to the String keys of the attributes
> [7700] Investigate duplicate fields being returned from GET /trainees/{trainee_id}

- spec/services/determine_sign_off_period_spec.rb
Determine signoff
Amended to the test the whole year
Previously the available block of time that was sampled missed a chunk so it failed intermittently.
```bash
bundle exec rspec ./spec/services/determine_sign_off_period_spec.rb 
```
> [7650] Amended to test the whole year

- Gemfile
- Gemfile.lock
- app/lib/malware_scan.rb
- spec/lib/malware_scan_spec.rb
* Uploaded files are scanned by Azure to mark them safe or suspect.
* The current service has a bug and is just looking for the expected "safe" tag in the actual uploaded file content
* NOTE: there are two parts to this, this PR and the [forked gem changes](https://github.com/d-a-v-e/azure-blob/pull/1/files)
* This points the azure-blob gem to a forked version with [these changes I made ](https://github.com/testdouble/azure-blob/pull/5/files)
* refactors the actual service to make use of the new endpoint
* refactors the specs
* these specs are incredibly "dumb" They have to stub a lot
* The `azure-blob` gem is pretty small in scope as it stands, and seems to have a single maintainer, not sure how quickly the suggested change will go in
* I need to write some specs for the actual gem …
> [7648] MalwareScanJob failing silently

- spec/support/shared_examples/register_api_endpoint.rb
When adding some documentation for Grafana, I removed some metrics that Yabeda was giving us by default. There were still some tests around this that were failing.
This just removes those tests as they're no longer necessary. 
> Remove Unnecessary Yabeda Tests

- app/jobs/dqt/retrieve_trn_job.rb
- spec/jobs/dqt/retrieve_trn_job_spec.rb
https://trello.com/c/rCDEPvXl/7708-retrieve-trn-job-is-timing-out
October is a busy month for DQT which means there are a substantial amount of potential duplicates who can't be assigned TRNs. This is causing a large number of timeout errors for the `RetrieveTRN` job on Register. Increasing the timeout during the busy period should reduce the amount of noisy error messages that come through to the Support channel on slack during this period.
> [7708] - increase timeout on retrieve trn job during October

- app/services/concerns/hashable.rb
- app/services/dead_jobs/base.rb
- app/services/sidekiq/remove_dead_duplicates.rb
- docs/support_playbook.md
- spec/concerns/hashable_spec.rb
- spec/features/system_admin/dead_jobs/sorting_dead_jobs_spec.rb
- spec/features/system_admin/dead_jobs/viewing_dead_jobs_spec.rb
- spec/services/sidekiq/remove_dead_duplicates_spec.rb
- spec/support/shared_examples/dead_jobs.rb
[Error with Dead Jobs](7728-error-with-dead-jobs)
Some jobs had the global id nested inside a Hash which resulted in the reported error.
ex.
`{"trainee"=>{"_aj_globalid"=>"gid://register-trainee-teachers/Trainee/:trainee_id"}`
* Account for keyword arguments when accessing `_aj_globalid`
> [7728] Error with Dead Jobs

- app/controllers/trainees/employing_schools_controller.rb
- app/controllers/trainees/lead_partners_controller.rb
- app/forms/schools/form.rb
- config/locales/en.yml
- spec/features/trainee_actions/add_lead_partner_and_employing_school_spec.rb
- spec/forms/partners/lead_partner_form_spec.rb
- spec/forms/schools/employing_school_form_spec.rb
[Handle visiting lead partners / employing schools edit page by url](https://trello.com/c/EUdJZd8J/7727-handle-visiting-lead-partners-employing-schools-edit-page-by-url)
- Redirect to `trainees/:trainee_id/lead-partners/details/edit` If a user attempts to visit `trainees/:trainee_id/lead-partners/edit` and `lead_partner_not_applicable` is set to `true` 
- Redirect to `trainees/:trainee_id/employing-schools/details/edit` If a user attempts to visit `trainees/:trainee_id/employing-schools/edit` and `employing_school_not_applicable` is set to `true` 
- Remove `both_fields_are_not_selected` validation
> [7727] - Handle visiting lead partners / employing schools edit page by url

- config/locales/en.yml
- spec/features/bulk_upload/recommending_trainees_spec.rb
- spec/services/bulk_update/recommendations_uploads/validate_file_spec.rb
[Trello ticket](https://trello.com/c/zeaIWcar/7765-csv-file-upload-error-message-update)
A content review of error messages has suggested this could be more aligned with [Design System guidance](https://design-system.service.gov.uk/components/error-message/).
* Update file encoding error message
> [7765] Update file encoding error message to new content

- spec/factories/trainees.rb
A trainee is withdrawing
A valid withdraw date
If a trainee is withdrawing then they must of started and not still be `potential`
`potential_itt_start_date` can be before `itt_start_date`
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/11629565463/job/32390279102?pr=4776
> [xxxx] Amended dates to be in a valid range

- .scss-lint.yml
- Gemfile
- Gemfile.lock
[Update/review really old gem sass](https://trello.com/c/81rQkegV/7772-update-review-really-old-gem-sass)
Fairly sure this gem isn't being used, have removed and will see if anything fails in CI
> [7772] - remove scss_lint-govuk

- docs/support_playbook.md
Adding a previous trainee for a former accredited provider
Added playbook notes for `Adding a previous trainee for a former accredited provider
For the next support dev
> [7745] Added playbook notes for `Adding a previous trainee for a former accredited provider

- Gemfile
- Gemfile.lock
`webdriver` is no longer needed and selenium-webdriver should be used instead
* Removes `webdriver` and adds `selenium-webdriver`
* Smoke testing has been run by @d-a-v-e and still works with new gem-set
> [7773] - replace webdriver gem

- app/components/personal_details/view.rb
- app/forms/personal_details_form.rb
- app/helpers/nationalities_helper.rb
- app/lib/code_sets/nationalities.rb
- config/initializers/string.rb
- spec/config/initializers/string_spec.rb
- spec/factories/nationalities.rb
- spec/features/form_sections/personal_and_education_details/reviewing_apply_trainee_data_spec.rb
- spec/forms/personal_details_form_spec.rb
- spec/helpers/nationalities_helper_spec.rb
- spec/support/features/personal_details_steps.rb
citizen of guinea-bissau
Flake it with `citizen of guinea-bissau``
```
rspec ./spec/features/form_sections/personal_and_education_details/reviewing_apply_trainee_data_spec.rb:27 # edit training details changing an attribute
```
> [xxxx] Fixed `citizen of guinea-bissau` flaky issue

- Gemfile
- Gemfile.lock
- config/initializers/filter_parameter_logging.rb
[Rails Semantic Logger](https://github.com/reidmorrison/rails_semantic_logger) does not filter sensitive information, as defined by the `Rails.configuration.filter_paramters` setting from the sql statements in the log file.
I have forked the repo and put in a [Pull Request](https://github.com/reidmorrison/rails_semantic_logger/pull/247) to address this issue. 
I've also added `audited_changes` as a filtered parameter to ensure PII does not sent to third parties that way.
Use the forked version of `Rails Semantic Logger` until the PR has been accepted.
> [7748] remove pii from logs sent to logitio

- spec/features/trainee_actions/change_course_spec.rb
`language_specialism_options`
Fixed `language_specialism_options` issues
Was removed in https://github.com/DFE-Digital/register-trainee-teachers/pull/3350 
Before fix run and you see it breaks
```bash
for i in {1..100} 
do
bundle exec rspec ./spec/features/trainee_actions/change_course_spec.rb:9  --seed 27910
done
```
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/11819236768/job/32928810800?pr=4804
[Page](https://github.com/DFE-Digital/register-trainee-teachers/blob/83c395d249d4b30c126a16bf78a888ccd7e8b67d/spec/support/page_objects/trainees/language_specialism.rb) it was referring to.
> [xxxx] Fixed `language_specialism_options` issues

- app/controllers/bulk_update/trainees/submissions_controller.rb
- app/controllers/bulk_update/trainees/uploads_controller.rb
- app/forms/bulk_update/bulk_add_trainees_submit_form.rb
- app/forms/bulk_update/bulk_add_trainees_upload_form.rb
- app/models/bulk_update/row_error.rb
- app/models/bulk_update/trainee_upload.rb
- app/models/bulk_update/trainee_upload_row.rb
- app/policies/bulk_update/submissions/trainee_upload_policy.rb
- app/policies/bulk_update/trainee_upload_policy.rb
- app/services/bulk_update/add_trainees/import_rows.rb
- app/services/bulk_update/add_trainees/validate_file.rb
- app/services/bulk_update/recommendations_uploads/validate_trainee.rb
- app/views/bulk_update/bulk_updates/index.html.erb
- app/views/bulk_update/trainees/uploads/new.html.erb
- app/views/bulk_update/trainees/uploads/show.html.erb
- config/analytics.yml
- config/locales/en.yml
- db/migrate/20241101133718_add_error_type_to_bulk_update_row_error.rb
- db/migrate/20241114153414_add_index_errored_on_id_errored_on_type_to_bulk_update_errors.rb
- db/schema.rb
- spec/factories/bulk_update/trainee_upload_rows.rb
- spec/factories/bulk_update/trainee_uploads.rb
- spec/factories/users.rb
- spec/features/bulk_upload/bulk_add_trainees_spec.rb
- spec/models/bulk_update/row_error_spec.rb
- spec/models/bulk_update/trainee_upload_row_spec.rb
- spec/models/bulk_update/trainee_upload_spec.rb
- spec/policies/bulk_update/submissions/trainee_upload_policy_spec.rb
- spec/policies/bulk_update/trainee_upload_policy_spec.rb
- spec/services/bulk_update/add_trainees/import_rows_spec.rb
[Create upload summary page - part 2](https://trello.com/c/hQCuFxFe/7744-create-upload-summary-page-part-2)
This PR implements the summary page which renders the following:
1. The number of trainees to be created if the upload is successful
2. The number of validation errors
3. The number of duplicate errors
* Add `row_errors` association for trainee uploads
* Add enum to to `BulkUpdate::RowError` to determine if each row is of type `validation` or `duplicate`
* Refactors the uploads show page 
* Refactors the `BulkAddTraineesUploadForm`
* Add `BulkUpdate::TraineeUploadPolicy`
* Add `BulkUpdate::Submissions::TraineeUploadPolicy`
* Currently `row_errors` are not created if a validation error occurs and this logic will be implemented as part of a separate ticket.  …
> [7744] Create upload summary page part 2

- config/initializers/sentry.rb
After merging https://github.com/DFE-Digital/register-trainee-teachers/pull/4817
Which created monitors [here](https://dfe-teacher-services.sentry.io/crons/) without notice
An influx of annoying missed check-ins notification happened 
Removed Sentry automatic capture for check-ins
https://docs.sentry.io/platforms/ruby/crons/#job-monitoring
There is a cost associated, we survived this long with monitoring, there seems to be very little need.
> [xxxxx] Removed Sentry automatic capture for check-ins

- Gemfile
- Gemfile.lock
- app/javascript/application.js
- app/javascript/scripts/components/form_components/lead_partners_autocomplete.js
- app/views/layouts/application.html.erb
- app/views/trainees/employing_schools/details/edit.html.erb
- app/views/trainees/lead_partners/details/edit.html.erb
- config/initializers/content_security_policy.rb
- package.json
- yarn.lock
[7833-install-turbo-rails](https://trello.com/c/XvobXmPU/7833-install-turbo-rails)
`turbo-rails` is required to support links with the `delete` method
* Install `turbo-rails` gem
* Disable turbo drive by default for links and form submissions
* Fix autocomplete bug for lead partners
> [7833] Install turbo-rails

- app/models/api/v0_1/trainee_attributes.rb
- spec/components/diversity/view_spec.rb
- spec/factories/trainees.rb
- spec/models/api/v0_1/trainee_attributes_spec.rb
Reported via [Trello](https://trello.com/c/qXbNhw5V/24-updating-trainees-without-including-disability-fields) this is a bug where we don't handle blank values for disability.
The fix is simple, but when looking at reproducing this, it raised a couple of other questions around the handling of blank values, and HESA trainee details not being set prior to an update request. These will be looked at in subsequent tickets, so we can get this fix out quickly.
* Add a test for this scenario
* Guard for blank disabilities
* Fixes some spellings and tweaks names
> [7852] Fix bug with updating disabilities via the API

- app/components/performance_profile_banner/view.html.erb
- app/components/performance_profile_banner/view.rb
- app/models/provider.rb
- app/models/sign_off.rb
- spec/components/performance_profile_banner/view_preview.rb
- spec/components/performance_profile_banner/view_spec.rb
- spec/models/provider_spec.rb
The performance profile banner
Added the component
Just the component
https://register-pr-4828.test.teacherservices.cloud/view_components/performance_profile_banner/view
There a a few loose ends, will be fix in future PRs (actually showing it to the user)
> [7851] Add performance profile banner as a view component

- app/components/bulk_update/trainee_uploads/row/view.html.erb
- app/components/bulk_update/trainee_uploads/row/view.rb
- app/controllers/bulk_update/trainees/uploads_controller.rb
- app/forms/bulk_update/bulk_add_trainees_submit_form.rb
- app/forms/bulk_update/bulk_add_trainees_upload_form.rb
- app/jobs/bulk_update/add_trainees/remove_cancelled_and_failed_job.rb
- app/models/bulk_update/trainee_upload.rb
- app/services/bulk_update/add_trainees/import_rows.rb
- app/services/bulk_update/add_trainees/remove_uploads.rb
- app/views/bulk_update/bulk_updates/index.html.erb
- app/views/bulk_update/trainees/uploads/index.html.erb
- app/views/bulk_update/trainees/uploads/show.html.erb
- config/analytics_blocklist.yml
- config/initializers/date_formats.rb
- config/routes.rb
- config/sidekiq_cron_schedule.yml
- db/migrate/20241121135207_add_submitted_at_to_bulk_update_trainee_uploads.rb
- db/migrate/20241121151740_add_status_default_to_bulk_update_trainee_uploads.rb
- db/migrate/20241126164709_add_status_index_to_bulk_update_trainee_upload.rb
- db/schema.rb
- spec/components/bulk_update/trainee_uploads/row/view_spec.rb
- spec/factories/bulk_update/trainee_uploads.rb
- spec/features/bulk_upload/bulk_add_trainees_spec.rb
- spec/jobs/bulk_update/add_trainees/remove_cancelled_and_failed_job_spec.rb
- spec/models/bulk_update/trainee_upload_row_spec.rb
- spec/models/bulk_update/trainee_upload_spec.rb
- spec/services/bulk_update/add_trainees/remove_uploads_spec.rb
[7850-create-status-of-new-trainee-files-page](https://trello.com/c/MNr8s1Cc/7850-create-status-of-new-trainee-files-page)
* Use `stateful_enum` for `BulkUpdate::TraineeUpload#status`
* Use the events instead of the delegated enum method for `BulkUpdate::TraineeUpload#status`
* Add `BulkUpdate::TraineeUploadsController#index`
* Add `BulkUpdate::TraineeUploads::Row::View` component to render each row in the index page
* Add `BulkUpdate::AddTrainees::RemoveUploads`
* Add `BulkUpdate::AddTrainees::RemoveCancelledAndFailedJob`
* Add `submitted_at` to capture the `datetime` of the submitted for `in_progress` upload
* Set `pending` as the default `BulkUpdate::TraineeUpload#status`
* Add index for `BulkUpdate::TraineeUpload#status` …
> [7850] Create status of new trainee files page

- app/controllers/reports_controller.rb
- app/policies/user_policy.rb
- app/services/determine_sign_off_period.rb
- app/views/reports/_census_period.html.erb
- app/views/reports/_performance_period.html.erb
- app/views/reports/index.html.erb
- spec/features/reports/index_spec.rb
- spec/services/determine_sign_off_period_spec.rb
Performance Profiles Reports Page
The Reports Page should show different content based on the different date periods 
https://register-pr-4849.test.teacherservices.cloud/reports
Review app is set to this one
Show only if they have not signed off performance profile
Show when outside or when performance profile has been signed off
> Performance Profiles Reports Page

- app/helpers/application_helper.rb
- app/lib/funding/parsers/lead_partner_trainee_summaries.rb
- app/services/funding/lead_partner_trainee_summaries_importer.rb
- spec/lib/funding/parsers/lead_partner_trainee_summaries_spec.rb
- spec/services/funding/lead_partner_trainee_summaries_importer_spec.rb
- spec/support/fixtures/invalid_lead_partner_trainee_summaries.csv
- spec/support/fixtures/lead_partner_trainee_summaries.csv
[Trello card](https://trello.com/c/qiLsHmS9/7902-update-funding-uploads-to-support-2024-trainee-summary-csvs)
Funding payment has changed for 2024 due to ITT Reform. Payments now all go to APs, rather than being split between APs and Lead Schools, as previously.
The funding team have produced a CSV for SDS and PGTA routes which should now be allocated to Providers rather than Lead Partners (see [Trello card](https://trello.com/c/qiLsHmS9/7902-update-funding-uploads-to-support-2024-trainee-summary-csvs)).
We need to support this and process the funding CSV correctly. We will revisit the funding uploads more generally separately to this.
* Amend the `LeadPartnerTraineeSummaries` to support the new funding CSV format for SDS and PGTA routes
* Update tests and fixtures
* Fix a [deprecation …
> [7902] Update funding uploads to support 2024 trainee summary CSVs

- app/components/bulk_update/trainee_uploads/row/view.rb
- app/controllers/bulk_update/add_trainees/details_controller.rb
- app/controllers/bulk_update/add_trainees/review_errors_controller.rb
- app/controllers/bulk_update/add_trainees/submissions_controller.rb
- app/controllers/bulk_update/add_trainees/uploads_controller.rb
- app/services/send_csv_submitted_for_processing_email_service.rb
- app/views/bulk_update/add_trainees/details/show.html.erb
- app/views/bulk_update/add_trainees/review_errors/show.html.erb
- app/views/bulk_update/add_trainees/submissions/show.html.erb
- app/views/bulk_update/add_trainees/uploads/index.html.erb
- app/views/bulk_update/add_trainees/uploads/new.html.erb
- app/views/bulk_update/add_trainees/uploads/show.html.erb
- app/views/bulk_update/bulk_updates/index.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/bulk_upload/bulk_add_trainees_spec.rb
[7908-rename-the-namespace-of-bulkupdatetrainees](https://trello.com/c/lwF6E8DK/7908-rename-the-namespace-of-bulkupdatetrainees)
* Rename the controller namespace of `BulkUpdate::Trainees` to `BulkUpdate::AddTrainees`
* Change the paths from `/bulk-update/trainees` to `/bulk-update/add-trainees`
> [7908] Rename the namespace of BulkUpdate::Trainees

- app/models/trainee.rb
- app/services/find_duplicates_base.rb
- app/services/trainees/find_duplicates_of_apply_application.rb
- spec/models/trainee_spec.rb
- spec/requests/api/v1_0_pre/duplicate_trainees_spec.rb
- spec/services/trainees/find_duplicates_of_apply_application_spec.rb
- spec/services/trainees/find_duplicates_of_hesa_trainee_spec.rb
[Trello card](https://trello.com/c/LMxf20Yd/7928-api-duplicate-checking-for-trainees-includes-soft-deleted-trainees)
It appears that our duplicate checking is not filtering out discarded trainees.
We shouldn't include discarded trainees in our duplicate checking.
* Added `.kept` to duplicate scope and duplicate methods
* Added a couple of tests which check desired behaviour
* Any other duplicate checks that need to be updated?
> [7928] API duplicate checking for trainees includes soft deleted trainees

- app/controllers/trainees/withdrawal/extra_informations_controller.rb
- app/controllers/trainees/withdrawal/future_interests_controller.rb
- app/forms/withdrawal/future_interest_form.rb
- app/services/form_store.rb
- app/views/trainees/withdrawal/future_interests/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/trainee_actions/withdraw_trainee_spec.rb
- spec/forms/withdrawal/future_interest_form_spec.rb
- spec/support/features/page_helpers.rb
- spec/support/page_objects/trainees/withdrawal/future_interest.rb
https://trello.com/c/uhWRag0n/7917-create-would-this-trainee-be-interested-in-becoming-a-teacher-in-the-future-page
Add page to determine if withdrawing trainee would have any interest in reapplying in the future
> [7917] - add page for future interest

- app/components/performance_profile_banner/view.html.erb
- app/components/performance_profile_banner/view.rb
- app/controllers/reports/performance_profiles_controller.rb
- app/controllers/reports_controller.rb
- app/forms/performance_profile_sign_off_form.rb
- app/models/provider.rb
- app/views/guidance/performance_profiles.html.erb
- app/views/layouts/application.html.erb
- app/views/reports/_performance_period.html.erb
- app/views/reports/performance_profiles/index.html.erb
- app/views/reports/performance_profiles/new.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/reports/performance_profiles_controller_spec.rb
- spec/controllers/reports_controller_spec.rb
- spec/features/performance_profile_banner_spec.rb
- spec/features/reports/performance_profile_spec.rb
- spec/forms/performance_profile_sign_off_form_spec.rb
ITT performance profile sign off for the 2023 to 2024 academic year page
Add ITT performance profile sign off for the 2023 to 2024 academic year page
Once signed off the performance profile flow is locked down, (Annie Bell is locked down, try one of the other personas)
> [7905] ITT performance profile sign off for the 2023 to 2024 academic year page

- app/controllers/guidance_controller.rb
- app/views/guidance/dates_and_deadlines.html.erb
- app/views/reports/_outside_period.html.erb
- app/views/reports/performance_profiles/confirmation.html.erb
Performance profiles sign off in register testing 
Fixes for performance profiles sign off in register testing 
https://register-pr-4905.test.teacherservices.cloud/guidance/dates-and-deadlines
Need to go through the flow (University of BAT was used so pick something else)
https://register-pr-4905.test.teacherservices.cloud/reports/performance-profiles/confirmation
Need to go through the flow (University of BAT was used so pick something else)
https://register-pr-4905.test.teacherservices.cloud/reports
> [7936] Fixes for performance profiles sign off in register testing 

- app/models/bulk_update/trainee_upload.rb
- app/policies/bulk_update/submissions/trainee_upload_policy.rb
- app/views/bulk_update/add_trainees/submissions/show.html.erb
- app/views/bulk_update/add_trainees/uploads/show.html.erb
- config/routes.rb
- spec/factories/bulk_update/trainee_uploads.rb
- spec/features/bulk_upload/bulk_add_trainees_spec.rb
- spec/models/bulk_update/trainee_upload_spec.rb
- spec/policies/bulk_update/submissions/trainee_upload_policy_spec.rb
[7925-bulk-csv-trainee-upload-handle-errors-after-submission
](https://trello.com/c/4x9Z8ELb/7925-bulk-csv-trainee-upload-handle-errors-after-submission)
Handle failed trainee creation uploads upon submission
* Allow a failed upload to be cancelled
* Change paths to submissions to be in singular form
* Add links to status of trainee files
* Refactor `submissions/show` page
> [7925] Bulk CSV trainee upload - handle errors after submission

- app/forms/undo_withdrawal_form.rb
- spec/factories/trainees.rb
- spec/features/trainee_actions/undo_withdraw_trainee_spec.rb
https://trello.com/c/pNcirSIp/7951-undo-withdrawal?filter=member:chrisgannon23
Undo withdrawal process will discard the current withdrawal whilst leaving the withdrawal reasons intact. It will leave an audit comment for and update the timeline. Previous timeline events for undoing a withdrawal should still be valid.
> [7951] - Update undo withdrawals process

- app/controllers/api/trainees/withdraw_controller.rb
- app/models/api/v0_1/withdrawal_attributes.rb
- spec/requests/api/v0_1/audit_trail_attribution_spec.rb
- spec/requests/api/v0_1/trainees/post_withdraw_spec.rb
- spec/requests/api/v1_0_pre/audit_trail_attribution_spec.rb
- spec/requests/api/v1_0_pre/trainees/post_withdraw_spec.rb
[Trello card](https://trello.com/c/uYJU07Y2/8038-fix-api-withdrawals-endpoint-params)
* Fix withdrawals endpoint params data structure to match the docs and other endpoints
* Fix an incorrect field name in `WithdrawalAttributes`
* Update tests
> [8038] Fix API withdrawals endpoint params

- spec/features/bulk_upload/bulk_upload_placements_spec.rb
- spec/fixtures/files/bulk_update/placements/missing_trn.csv
Missing trn
Added spec for missing trn
This is in relation to https://ukgovernmentdfe.slack.com/archives/C023EC79M6Y/p1736844647466419?thread_ts=1736844297.593359&cid=C023EC79M6Y
This error is actually handled
https://github.com/DFE-Digital/register-trainee-teachers/blob/e222a8c40d78570ea09982db3d8c072769bd1c0a/app/forms/bulk_update/placements_form.rb#L80-L86
Consideration, maybe we need to review this, since it captures the errors and advise the user to check the csv in question.
Is there a real need to send the error to sentry?
> [xxxx] Added spec for missing trn

- app/components/bulk_update/trainee_uploads/row/view.html.erb
- app/components/bulk_update/trainee_uploads/row/view.rb
- app/views/bulk_update/add_trainees/uploads/index.html.erb
- spec/components/bulk_update/trainee_uploads/row/view_spec.rb
- spec/features/bulk_upload/bulk_add_trainees_spec.rb
[7986-csv-bug-party-no-date-for-failed-uploads-6](https://trello.com/c/rDGW7LGc/7986-csv-bug-party-no-date-for-failed-uploads-6)
* Use `BulkUpdate::TraineeUpload#created_at` instead of `submitted_at`
* Changing heading to `Uploaded`
* Hide `created_at` if the upload is `cancelled`
> [7986] CSV bug party - No date for failed uploads (6)

- app/controllers/bulk_update/add_trainees/empty_templates_controller.rb
- spec/features/bulk_upload/bulk_add_trainees_spec.rb
[8046-make-csv-template-download-available-without-signing-in](https://trello.com/c/GAduUJHG/8046-make-csv-template-download-available-without-signing-in)
* Remove authentication for CSV template file by inheriting from `CsvDocs::BaseController`
> [8046] Make CSV template download available without signing in

- app/models/school.rb
- spec/models/school_spec.rb
- spec/services/school_search_spec.rb
Fixed flaky punctuation school search
There isn't a really town with punctuation in there name
Apart from [Westward Ho!](https://en.wikipedia.org/wiki/Westward_Ho!) but that is more of a village
> [xxxx] Fixed flaky punctuation school search

- app/services/send_csv_submitted_for_processing_email_service.rb
- app/services/send_performance_profile_submitted_email_service.rb
- spec/services/send_csv_submitted_for_processing_email_service_spec.rb
- spec/services/send_performance_profile_submitted_email_service_spec.rb
https://trello.com/c/BISN0iEr/8058-provider-has-not-received-sign-off-confirmation
The `send_emails` feature flag is not needed for these mailers.
> [8058] - remove feature flag from mailers

- app/models/reports/bulk_placement_report.rb
- app/services/bulk_update/placements/create_placement_rows.rb
- db/data/20250123124723_remove_failed_placement_with_urn_added_manually.rb
- spec/factories/trainees.rb
- spec/services/bulk_update/placements/create_placement_rows_spec.rb
Pointless Placement rows
Skip placement row that has been set `ADDED MANUALLY`
A csv with urn set to `ADDED MANUALLY` was attempted to be bulk uploaded.
> [8051] Skip placement row that has been set ADDED MANUALLY

- app/lib/trs/client.rb
- config/settings.yml
- config/settings/production.yml
- config/settings/productiondata.yml
- config/settings/qa.yml
- config/settings/review.yml
- config/settings/sandbox.yml
- config/settings/staging.yml
- spec/lib/trs/client_spec.rb
The transition from DQT to TRS requires new client. This ticket covers the creation of a new client.
Adds a new namespace and offers new client for `TRS`
Can be tested locally:
Add to `config/settings/development.local.yml`:
```yml
trs:
base_url: https://preprod.teacher-qualifications-api.education.gov.uk
api_key: <get from staging secrets or ask @d-a-v-e >
```
In console run:
```ruby
Trs::Client.get("/v3/persons/1234567")
```
Can expect back:
* The specs for `client.rb` are heavily stubbed - test for the endpoint files we will create later may be more useful.
* Trello: https://trello.com/c/hIZrG9qE/8083-trs-client
> [TRS][8083] - Client and Settings

- app/components/bulk_update/trainee_uploads/row/view.rb
- app/forms/bulk_update/bulk_add_trainees_import_rows_form.rb
- app/forms/bulk_update/bulk_add_trainees_upload_form.rb
- app/models/bulk_update/trainee_upload.rb
- app/views/bulk_update/add_trainees/uploads/show.html.erb
- db/migrate/20250122151655_change_bulk_update_trainee_uploads_status_default.rb
- db/schema.rb
- spec/components/bulk_update/trainee_uploads/row/view_spec.rb
- spec/factories/bulk_update/trainee_uploads.rb
- spec/forms/bulk_update/bulk_add_trainees_import_rows_form_spec.rb
- spec/models/bulk_update/trainee_upload_spec.rb
- spec/services/bulk_update/add_trainees/import_rows_spec.rb
[8067-separate-the-validation-background-job-from-bulkupdatebulkaddtraineesuploadform](https://trello.com/c/nuZnB0jk/8067-separate-the-validation-background-job-from-bulkupdatebulkaddtraineesuploadform)
There is the requirement to split the upload of the CSV file into two steps by first uploading the file and then validating the actual trainee records. This PR extracts the creation of `BulkUpdate::TraineeUploadRow` and `BulkUpdate::RowError` records to a form object. Because we have dependent tests on the current flow, the newly introduced form object `BulkUpdate:: BulkAddTraineesImportRowsForm` will be temporarily called in `BulkUpdate::TraineeUploadForm`. 
* Change default value of `BulkUpdate::TraineeUpload#status` to `uploaded`
* Move `BulkUpdate::AddTrainees::ImportRowsJob` to …
> [8067] Separate the validation background job from BulkUpdate::BulkAddTraineesUploadForm

- app/controllers/bulk_update/add_trainees/imports_controller.rb
- app/controllers/bulk_update/add_trainees/uploads_controller.rb
- app/forms/bulk_update/bulk_add_trainees_import_rows_form.rb
- app/policies/bulk_update/imports/trainee_upload_policy.rb
- config/locales/en.yml
- config/routes.rb
- spec/features/bulk_upload/bulk_add_trainees_spec.rb
- spec/models/bulk_update/trainee_upload_spec.rb
- spec/policies/bulk_update/imports/trainee_upload_policy_spec.rb
- spec/services/bulk_update/add_trainees/import_rows_spec.rb
[8086-add-a-separate-screen-to-perform-the-validation-of-the-csv-trainee-records-from-the-bulk-upload](https://trello.com/c/Mxjk90zh/8086-add-a-separate-screen-to-perform-the-validation-of-the-csv-trainee-records-from-the-bulk-upload)
Perform the importing of rows and validate the trainee records to be created in a separate action 
* Add `BulkUpdate::AddTrainees::ImportsController#create`
* Add `BulkUpdate::Imports::TraineeUploadPolicy`
> [8086] Add a separate screen to perform the validation of the CSV trainee records from the bulk upload

- .gitignore
- app/models/persona.rb
- app/policies/degrees/trainee_policy.rb
- config/initializers/personas.rb
- docs/setup-development.md
- spec/models/persona_spec.rb
- spec/policies/degrees/trainee_policy_spec.rb
Degree policies
Relax the degree policies
As long as the trainee is created, then the provider of which the trainee belongs to can create and amend the trainee's degree.
1. Take a copy of the `Sanitised Data`
2. Setup `config/initializers/sanitised_data_users_persona.rb`
```ruby
SANITISED_DATA_USERS_IDS_PERSONA = [1813]
```
3. Log in as user
4. CRUD those degrees for traine with slug `zuYybg6JnTNP7DS1sGHLS1c5`
> [8054] Amended the degree policies

- config/locales/en.yml
- spec/view_objects/funding/trainee_summary_view_spec.rb
[8125-change-postgrad-and-undergrad-on-training-routes-page](https://trello.com/c/ETP72qS0/8125-change-postgrad-and-undergrad-on-training-routes-page)
Make the suggested label changes based on the new design
https://register-pr-5028.test.teacherservices.cloud/trainees
https://register-pr-5028.test.teacherservices.cloud/trainees/lz1s1r6fxco148ug5sgys4ot/training-routes/edit
* This change affects how the routes are been rendered in the funding summary page as well.
> [8125] Change postgrad and undergrad on training routes page

- spec/factories/courses.rb
- spec/factories/subjects.rb
- spec/factories/trainees.rb
- spec/features/trainee_actions/change_course_spec.rb
Flakey tests
The factory was producing data with questionable integrity
Run this a billion times, this only reduces the collision of poor data integrity.
```bash
bundle exec rspec ./spec/features/trainee_actions/change_course_spec.rb:11
```
The issue is something along the lines of
- the trainee created was using a publish course that maybe primary but should of been a secondary
- the new publish course created for the trainee to use maybe primary but should of been a secondary
- the subject that was created was a maybe modern language
- subject cannot be a modern language as it is not a real thing
- a publish course can be a modern language only as a second
- a primary or a secondary course should use the respective subjects …
> [xxxx] Fixed by ensuring that there is some data integrity for secondary courses vs primary courses

- config/initializers/training_routes.rb
- config/locales/en.yml
- spec/features/end_to_end/early_years_undergrad_journey_spec.rb
- spec/support/features/course_details_steps.rb
- spec/support/features/training_route_steps.rb
[8162-enable-setting-lead-partners-for-early-years-ug-trainees](https://trello.com/c/Jg881UFJ/8162-enable-setting-lead-partners-for-early-years-ug-trainees)
* Allow setting a lead partner for `early_years_undergrad` trainees
> [8162] Enable lead partners for early_years_undergrad

- terraform/aks/terraform.tf
- terraform/aks/variables.tf
- terraform/aks/workspace-variables/production.tfvars.json
- terraform/modules/azure/storage.tf
- terraform/modules/azure/variables.tf
Create a separate storage account that will hold the sanitised database backup.
Provides better security, especially with upcoming move to oidc for github workflows.
Add terraform config for new storage account
make production deploy-plan (should show 3 new resources for sanitised stg account)
make qa deploy-plan (no extra resources)
> Create separate storage account for sanitised bkp

- .github/workflows/next-academic-year-tests.yml
next-academic-year-tests github workflow is missing pull-request write permission
see https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/13537623474
Add permission to workflow
see https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/13539894039
> Fix permissions on next-academic-year-tests gh wf

- .github/actions/bring-docker-image-up/action.yml
- .github/actions/coverage-tests/action.yml
- .github/actions/lint/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/code-coverage.yml
- .github/workflows/tests.yml
We use azure key vault to store the review app sentry dsn but use a dummy variable
It's used in lots of testing workflows where we connect to azure and download but we don't need to do this (unless I'm missing something)
Remove the azure login and kv secret download for the review app sentry dsn.
Check the workflows run ok.
> Stop using azure kv for review app sentry dsn

- .github/workflows/maintenance.yml
- maintenance_page/manifests/maintenance/deployment_maintenance.yml.tmpl
- maintenance_page/manifests/staging/ingress_external_to_main.yml
- maintenance_page/manifests/staging/ingress_external_to_main2.yml
- maintenance_page/manifests/staging/ingress_external_to_maintenance.yml
- maintenance_page/manifests/staging/ingress_external_to_maintenance2.yml
- maintenance_page/manifests/staging/ingress_internal_to_main.yml
- maintenance_page/manifests/staging/ingress_internal_to_maintenance.yml
- maintenance_page/manifests/staging/ingress_maintenance.yml
- maintenance_page/manifests/staging/ingress_temp_to_main.yml
Add staging env to the maintenance page configuration
Add some security settings to the deployment
- Add staging as an option to the workflow
- Add staging mainfest files
- Add securityContext to deployment terraform
to be tested
> Add staging to maintenance page

- app/models/api/v0_1/hesa_trainee_detail_attributes.rb
- app/services/api/v0_1/hesa_mapper/attributes.rb
- app/views/api_docs/reference/v0.1/_reference.md
- app/views/api_docs/reference/v1.0-pre/_reference.md
- app/views/bulk_update/add_trainees/reference_docs/fields.yaml
- config/locales/en.yml
- public/openapi/v0.1.yaml
- public/openapi/v1.0-pre.yaml
- spec/models/api/v0_1/degree_attributes_spec.rb
- spec/models/api/v0_1/hesa_trainee_detail_attributes_spec.rb
- spec/models/api/v0_1/trainee_attributes_spec.rb
- spec/requests/api/v0_1/duplicate_trainees_spec.rb
- spec/requests/api/v0_1/post_hesa_trainees_spec.rb
- spec/requests/api/v0_1/put_trainee_spec.rb
- spec/requests/api/v1_0_pre/duplicate_trainees_spec.rb
- spec/requests/api/v1_0_pre/post_hesa_trainees_spec.rb
- spec/requests/api/v1_0_pre/put_trainee_spec.rb
- spec/requests/api/v1_0_pre/trainees/put_degrees_spec.rb
[8225-update-the-logic-for-ittaim-and-ittqualificationaim-to-align-with-hesa
](https://trello.com/c/LUjx8wrx/8225-update-the-logic-for-ittaim-and-ittqualificationaim-to-align-with-hesa)
Change validation for `itt_qualification_aim` presence to rely on `itt_aim` value
* Add inclusion validation for `itt_aim`
* Add inclusion validation for `itt_qualification_aim`
* Refactor `itt_qualification_aim` presence validation
* Remove `itt_qualification_aim` from `Api::V01::HesaMapper::Attributes`
* Update docs
> [8225] Update the logic for itt_aim and itt_qualification_aim to align with HESA

- app/models/trainee.rb
- app/models/trainee_withdrawal.rb
- docs/support_playbook.md
- spec/factories/trainees.rb
- spec/models/trainee_withdrawal_spec.rb
[8229-add-audits-to-trainee-withdrawals
](https://trello.com/c/xqPY4m4j/8229-add-audits-to-trainee-withdrawals)
Enable audits in TraineeWithdrawal
* Refactor `Trainee#current_withdrawal`
* Add audited to `TraineeWithdrawal`
* Refactor factory
* Update support playbook 
> [8229] Add audits to trainee withdrawals

- app/services/send_performance_profile_submitted_email_service.rb
- spec/services/send_performance_profile_submitted_email_service_spec.rb
https://trello.com/c/wYtUHNFn/8237-removing-user-from-register
Only send out performance profile emails to active users of an organisation
> [8237] - stop emailing inactive users of an organisation

- app/jobs/dqt/retrieve_trn_job.rb
- spec/jobs/dqt/retrieve_trn_job_spec.rb
there are lots of `RuntimeError: Invalid transition` failed `Dqt::RetrieveTrnJob` jobs
if a trainee has their TRN, we should update the request instead of re-submitting the job
validate logic - is anything not being considered here? why isn't this already being done?
> [xxxx] - exit RetrieveTrnJob if TRN is present

- app/jobs/dqt/retrieve_trn_job.rb
- app/jobs/trs/retrieve_trn_job.rb
- spec/jobs/dqt/retrieve_trn_job_spec.rb
- spec/jobs/trs/retrieve_trn_job_spec.rb
Amendment to "exit RetrieveTrnJob if TRN is present" #5130
* now only TRN presence is checked to see if the RetrieveTrnJob needs to run
* rule is applied to the yet-to-be-used TRS job
> [xxxx] - Amendment to "exit RetrieveTrnJob if TRN is present" #5130

- app/jobs/dqt/retrieve_trn_job.rb
- app/jobs/trs/retrieve_trn_job.rb
- spec/jobs/dqt/retrieve_trn_job_spec.rb
- spec/jobs/trs/retrieve_trn_job_spec.rb
Ok, last one, this covers TRN retrieval requests that belong to discarded trainees (the remainder of the dead trn request jobs). relates to #5135 and #5130 
Checks discard status of a trainee before running the task
> [xxxx] - Check for discard status before retrieving TRN

- app/components/authentication_tokens/details/view.rb
- app/controllers/authentication_tokens_controller.rb
- app/models/authentication_token.rb
- app/policies/authentication_token_policy.rb
- app/views/organisation_settings/show.html.erb
- db/migrate/20250314141354_add_attributes_to_authetication_tokens.rb
- db/migrate/20250321143706_add_status_last_used_at_index_to_authentication_tokens.rb
- db/schema.rb
- lib/tasks/example_data.rake
- spec/factories/authentication_tokens.rb
- spec/features/organisation_settings_spec.rb
- spec/policies/authentication_token_policy_spec.rb
[8272-create-new-self-serve-token-management-index-page
](https://trello.com/c/epDJSjwz/8272-create-new-self-serve-token-management-index-page)
Follow up PR
* Order tokens by `status` and `last_used_at`
* Make content changes to index page
* Refactor `AuthenticationTokenPolicy` to forbid access to Lead Partners
* Refactor `AddAttributesToAutheticationTokens`
> [8272] Create new self-serve token management index page - part 2

- app/controllers/authentication_tokens_controller.rb
- app/jobs/authentication_tokens/expire_tokens_job.rb
- app/models/authentication_token.rb
- config/sidekiq_cron_schedule.yml
- db/migrate/20250324100449_add_expires_at_index_to_authentication_tokens.rb
- db/schema.rb
- spec/jobs/authentication_tokens/expire_tokens_job_spec.rb
- spec/models/authentication_token_spec.rb
[8297-add-a-cron-job-to-expire-authentication-tokens](https://trello.com/c/7zPcVuKz/8297-add-a-cron-job-to-expire-authentication-tokens)
Based on the `expires_at` date, set the status of relevant `active` tokens as `expired`
* Add `will_expire` scope to `AuthenticationToken`
* Add `AuthenticationTokens:: ExpireTokensJob`
* Add `expires_at` index to `AuthenticationToken`
> [8297] Add a Cron job to expire Authentication tokens

- app/views/bulk_update/add_trainees/reference_docs/fields.yaml
- app/views/csv_docs/pages/add_trainees.html.erb
[8181-csv-guidance-clarify-that-we-dont-need-courseid-or-ctitle](https://trello.com/c/PQEfpPwb/8181-csv-guidance-clarify-that-we-dont-need-courseid-or-ctitle)
[8188-bulk-add-trainees-csv-guidance-minor-content-additions](https://trello.com/c/0ZsgpgPN/8188-bulk-add-trainees-csv-guidance-minor-content-additions)
* Content changes in `add_trainees.html.erb`
* Content changes in `reference_docs/fields.yaml`
> [8188] / [8181] - Update CSV docs for bulk_update/add_trainees / CSV Guidance clarify that we don't need COURSEID or CTITLE

- app/models/trainee.rb
- app/serializers/api/v0_1/trainee_serializer.rb
- app/services/api/trainees/withdraw_response.rb
- spec/requests/api/v0_1/trainees/post_withdraw_spec.rb
- spec/requests/api/v1_0_pre/trainees/post_withdraw_spec.rb
- spec/services/api/trainees/withdraw_response_spec.rb
See the [Trello ticket](https://trello.com/c/RvM5FM9A/8304-withdraw-endpoint-not-behaving-as-expected)
* Update the tests for the withdraw endpoint
* Return the withdraw reasons in the trainee serializer, and the correct withdraw date
* Fix the setting of the withdraw date  
* Has anything been missed?
* Is this consistent with the withdraw process through the web UI?
> [8304] Withdraw endpoint not behaving as expected

- app/serializers/api/v0_1/trainee_serializer.rb
- app/views/api_docs/reference/v0.1/_reference.md
- app/views/api_docs/reference/v1.0-pre/_reference.md
- spec/requests/api/v0_1/post_hesa_trainees_spec.rb
- spec/requests/api/v0_1/put_trainee_spec.rb
- spec/requests/api/v1_0_pre/post_hesa_trainees_spec.rb
- spec/requests/api/v1_0_pre/put_trainee_spec.rb
- spec/serializers/api/v0_1/trainee_serializer_spec.rb
[8294-remove-some-internal-register-fields-from-api-responses](https://trello.com/c/xh4OHX8A/8294-remove-some-internal-register-fields-from-api-responses)
* Exclude various attributes from `TraineeSerializer`
* Update reference docs
> [8294] Remove some internal Register fields from API responses

- app/controllers/api/trainees/deferrals_controller.rb
- app/models/authentication_token.rb
- app/models/trainee.rb
- app/services/api/trainees/deferral_service.rb
- app/views/api_docs/reference/v0.1/_reference.md
- app/views/api_docs/reference/v1.0-pre/_reference.md
- config/analytics.yml
- db/migrate/20250326142810_add_defer_reason_to_trainees.rb
- db/schema.rb
- public/openapi/v0.1.yaml
- public/openapi/v1.0-pre.yaml
- spec/requests/api/v0_1/trainees/post_deferral_spec.rb
- spec/requests/api/v0_1/trainees/post_placement_spec.rb
- spec/requests/api/v1_0_pre/trainees/post_placement_spec.rb
- spec/serializers/api/v0_1/trainee_serializer_spec.rb
- spec/services/api/trainees/deferral_service_spec.rb
[8310-add-deferral-reason-to-api-endpoint-post-trainees-traineeid-defer](https://trello.com/c/hd9TAkJM/8310-add-deferral-reason-to-api-endpoint-post-trainees-traineeid-defer)
Add support for `defer_reason` optional string attribute limited to 500 characters to the deferral endpoint.
* Add `defer_reason` to 'trainees'
* Refactor `DeferralService`
* Refactor `TraineeSerializer`
* Update docs
> [8310] Add deferral reason to API endpoint POST /trainees/{trainee_id}/defer

- .github/workflows/reset-csv-sandbox-database.yml
- app/models/provider.rb
- app/models/provider_user.rb
- lib/tasks/user.rake
- spec/factories/providers.rb
- spec/lib/tasks/user_retain_hei_and_system_admin_users_only_spec.rb
- spec/models/provider_spec.rb
- spec/models/provider_user_spec.rb
Active HEI provider users
Retain active hei provider users only
To test pull down and restore a sanitised database back up and run the rake task
```
bundle exec rake user:retain_hei_and_system_admin_users_only
```
Only the user relationship of a HEI is retained
`LeadPartnerUser` will be destroyed, this is to prevent a user that has both `HEI` and `LeadPartner` provider to interactive as a `LeadPartner`
`ProviderUser` may be destroyed (only `HEI` related will be retained) this is to prevent a user that has both `HEI` and `SCITT` provider to interactive as a `SCITT`
`User`'s `dfe_sign_in_uid` will either be retained if `HEI` related or a `system admin` otherwise it will all be nil out, this is to prevent any other users to interactive during our selective testing …
> [8289] Active HEI provider users only

- app/models/api/v0_1/trainee_attributes.rb
- app/validators/uniqueness_validator.rb
- config/locales/en.yml
- spec/requests/api/v0_1/post_hesa_trainees_spec.rb
- spec/requests/api/v0_1/put_trainee_spec.rb
- spec/requests/api/v1_0_pre/post_hesa_trainees_spec.rb
- spec/requests/api/v1_0_pre/put_trainee_spec.rb
[8380-sending-the-same-disability-code-in-2-fields-to-the-api-causes-a-500-error](https://trello.com/c/z0BDAKto/8380-sending-the-same-disability-code-in-2-fields-to-the-api-causes-a-500-error)
* Add UniquenessValidator
* Validate for unique disabilities in `Api::V01::TraineesAttributes`
> [8380] Sending the same disability code in 2 fields to the API causes a 500 error

- Gemfile
- Gemfile.lock
- spec/requests/api/v0_1/trainees/post_degrees_spec.rb
- spec/requests/api/v1_0_pre/trainees/post_degrees_spec.rb
[8371-add-missing-degree-type-mapping-for-4-specific-degrees](https://trello.com/c/1MBUPAiU/8371-add-missing-degree-type-mapping-for-4-specific-degrees)
Bump DfE data reference gem to `v3.7.0`
https://github.com/DFE-Digital/dfe-reference-data/pull/141
* Refactor specs to test DfE reference gem new degree type
> [8371] Add missing degree type mapping for 4 specific degrees

- app/policies/trainee_policy.rb
- spec/features/trainee_actions/defer_trainee_spec.rb
- spec/policies/trainee_policy_spec.rb
- spec/support/page_objects/trainees/record.rb
Users and support agents are not able to change the deferral date of a deferred trainee. This is despite there being a 'Change' link on the trainee record.
It seems like the intention was to allow this date to be changed but the permissions were not set up correctly, and there was no test for it.
* Allow users to change the deferral date of a deferred trainee
* Prevent getting a permission denied when using the 'Change' link
* Add a feature test to cover this scenario
* Any unintended consequences?
> [8389] Allow users to change deferral date

- app/components/authentication_tokens/details/view.html.erb
- app/components/authentication_tokens/details/view.rb
- app/controllers/authentication_tokens/revokes_controller.rb
- app/policies/authentication_token_policy.rb
- app/views/authentication_tokens/revokes/show.html.erb
- config/routes.rb
- spec/features/authentication_tokens/revoke_authentication_token_spec.rb
https://trello.com/c/47mHovqF/8275-add-new-revoke-a-token-page
Add process for revoking authentication token
> [8275] - Add new 'revoke a token' page

- app/views/organisation_settings/show.html.erb
- spec/features/organisation_settings_spec.rb
[This Support ticket](https://trello.com/c/cnmsWSLQ/8432-removing-team-members-from-register) highlights a confusing experience a user is having when viewing team members, currently the team members listed under an organisation include discarded users
use `.kept` to display only the non-discarded users
> [8432] - only display non-discarded team members

- app/jobs/dqt/recommend_for_award_job.rb
- spec/jobs/dqt/recommend_for_award_job_spec.rb
Updates the Survey sending rule to "Don't send survey for Assessment Only routes **or** EYTS awards"
> [xxxx] - Update survey sending requirement

- .github/workflows/database-backup.yml
Database backups [have been failing](https://github.com/DFE-Digital/register-trainee-teachers/actions/workflows/database-backup.yml). They currently run at the same time as a scheduled job.
* Change database backup time to avoid scheduled jobs
> [xxxx] Change database backup time to avoid scheduled jobs

- spec/services/trainees/create_from_apply_spec.rb
- spec/support/api_stubs/recruits_api.rb
Feasibility tests for `pending_conditions`
Added a feasibility tests for `pending_conditions`
The tests just validates a trainee can be created for from apply when the status is`pending_conditions`.
> [8438] Added feasibility tests for `pending_conditions`

- .github/workflows/build-and-deploy.yml
- .github/workflows/database-backup.yml
To keep data static in `productiondata`, we must disable the automatic deploys and nightly restore GitHub aciton
Disables the aforementioned processes
> [xxxx] - Disable productiondata deploys and restores

- Gemfile
- Gemfile.lock
- spec/requests/api/v0_1/trainees/post_degrees_spec.rb
- spec/requests/api/v1_0_pre/trainees/post_degrees_spec.rb
- spec/services/degrees/create_from_hesa_spec.rb
[8372-add-274-missing-institutions-for-previous-degrees](https://trello.com/c/7Xn8GyQo/8372-add-274-missing-institutions-for-previous-degrees)
Refactor specs to test DfE reference gem new degree type
https://github.com/DFE-Digital/dfe-reference-data/pull/143
* Test for new institutions
> [8372] - Add 274 missing institutions for previous degrees

- config/settings.yml
- config/settings/csv-sandbox.yml
- config/settings/development.yml
- config/settings/pen.yml
- config/settings/production.yml
- config/settings/qa.yml
- config/settings/review.yml
We want to prevent users on the `sandbox` env from using CSV bulk add trainees at the moment.
Provider testing for this feature will be happening on the `csv-sandbox`.
* Turn off feature on `sandbox`
* Refactor to make feature 'off' by default
* The the envs settings look right?
> [8485] Switch off CSV bulk add trainees in sandbox

- Gemfile
- Gemfile.lock
- app/controllers/api/base_controller.rb
- spec/requests/dfe_analytics_api_request_events_spec.rb
Send api request events to BigQuery
Trello ticket [here](https://trello.com/c/bbU5kOXr/2625-dfeanalytics-add-native-support-for-api-requests)
Update DfE::Analytcsi GEM.
Include DfE::Analytics module to API Base controller to send api_request events.
> Send api_request events to BigQuery

- config/settings/sandbox.yml
We want to allow vendors in the `sandbox` env to use CSV bulk add trainees now that it's available for providers in `csv-sandbox`.
* Turn on feature in `sandbox`
> [8511] Switch on CSV bulk add trainees in sandbox for vendors

- app/models/api/v0_1/trainee_attributes.rb
- app/models/api/v2025_0_rc/trainee_attributes.rb
- app/services/api/v0_1/update_trainee_service.rb
- app/services/concerns/has_diversity_attributes.rb
- app/services/trainees/create_from_hesa.rb
- spec/requests/api/v0_1/put_trainee_spec.rb
- spec/requests/api/v2025_0_rc/put_trainee_spec.rb
- spec/services/trainees/create_from_hesa_spec.rb
[8499-clear-disabilities-if-values-change-in-a-hesa-api-update](https://trello.com/c/dP5mYZGr/8499-clear-disabilities-if-values-change-in-a-hesa-api-update)
* Refactor Api/V01/UpdateTraineeService disabilities
* Refactor Trainees::CreateFromHesa disabilities
> [8499] Clear disabilities if values change in a HESA/API update

- .github/workflows/delete-review-app.yml
Delete review app is not running for dependabot PR's raised for dependencies
Add back if statement from previous update
Check delete-review-app runs on dependencies after merge
> Fix delete-review-app for dependencies

- app/controllers/system_admin/pending_trns/retrieve_trns_controller.rb
- spec/controllers/system_admin/pending_trns/retrieve_trns_controller_spec.rb
Currently calling "Retrieve TRN" via the admin only writes the trn to the trainee. We need to then make a call to TRS with the new training status
Queues up `Trs::UpdateProfessionalStatusJob` when a successful TRN retrieval has occurred.
> [8492] - Update professional status retrieving TRN via admin console

- spec/factories/providers.rb
- spec/spec_helper.rb
Code coverage test runs are failing on `Faker::UniqueGenerator::RetryLimitExceeded` due to the numbers generated by the Provider factory.
* Reset the `Faker::Number.unique` before each test (https://github.com/faker-ruby/faker?tab=readme-ov-file#ensuring-unique-values)
* Also tweak the `accreditation_id` to be 4 digits to match the real ones
> [xxxx] Fix failing specs on Faker unique numbers limit

- app/models/api/v0_1/hesa_trainee_detail_attributes.rb
- app/models/api/v0_1/withdrawal_attributes.rb
- app/models/api/v2025_0_rc/withdrawal_attributes.rb
- app/services/api/trainees/award_recommendation_service.rb
- app/services/api/trainees/deferral_service.rb
- app/validators/api/trainees/award_recommendation_validator.rb
- app/validators/api/trainees/deferral_validator.rb
- config/locales/en.yml
- spec/requests/api/v0_1/trainees/post_deferral_spec.rb
- spec/requests/api/v0_1/trainees/post_recommend_for_qts_spec.rb
- spec/requests/api/v2025_0_rc/trainees/post_deferral_spec.rb
- spec/requests/api/v2025_0_rc/trainees/post_recommend_for_qts_spec.rb
- spec/requests/api/v2025_0_rc/trainees/post_withdraw_spec.rb
- spec/services/api/trainees/award_recommendation_service_spec.rb
- spec/services/api/trainees/deferral_service_spec.rb
- spec/services/api/trainees/withdraw_response_spec.rb
[8515-update-complex-error-messages-used-by-api-only](https://trello.com/c/JcGCFAp1/8515-update-complex-error-messages-used-by-api-only)
* Add custom error messages for withdrawals
* Add custom error messages for award recommendations
* Add custom error messages for deferrals
* Remove `trainee.submission_ready` translation key
> [8515] Update complex error messages used by API only

- app/services/dead_jobs/dqt_recommend_for_award.rb
- app/services/dead_jobs/dqt_update_trainee.rb
- app/services/dead_jobs/dqt_withdraw_trainee.rb
- app/services/dead_jobs/trs_register_for_trn.rb
- app/services/dead_jobs/trs_retrieve_trn.rb
- app/services/dead_jobs/trs_update_professional_status.rb
- app/services/dead_jobs/trs_update_trainee.rb
- spec/services/dead_jobs/trs_register_for_trn_spec.rb
- spec/services/dead_jobs/trs_retrieve_trn_spec.rb
- spec/services/dead_jobs/trs_update_professional_status_spec.rb
Dead Jobs currently only expose DQT failures. We need to list any dead jobs resulting from failed TRS.
[Trello Ticket](https://trello.com/c/FBajrj7R/8558-trs-dead-jobs)
Adds definitions for the TRS jobs to dead jobs
Excludes `UpdateTraineeJob` failures as these weren't useful for the TRS team.
> [8558] - adds TRS jobs to dead jobs retrieval list

- app/controllers/authentication_tokens/revokes_controller.rb
- app/controllers/authentication_tokens_controller.rb
- app/lib/user_with_organisation_context.rb
- app/policies/authentication_token_policy.rb
- app/policies/bulk_update/imports/trainee_upload_policy.rb
- app/policies/bulk_update/trainee_upload_policy.rb
- spec/factories/users.rb
- spec/features/authentication_tokens/create_new_authentication_token_spec.rb
- spec/features/authentication_tokens/revoke_authentication_token_spec.rb
- spec/features/organisation_settings_spec.rb
- spec/lib/user_with_organisation_context_spec.rb
- spec/models/authentication_token_spec.rb
- spec/policies/authentication_token_policy_spec.rb
- spec/support/features/authentication_steps.rb
[Trello card](https://trello.com/c/Q0ZJAXK7/8523-restrict-api-token-management-to-hei-providers)
* Update `AuthenticationTokenPolicy` to only allow HEI providers to use `AuthenticationToken`s
* Add and update tests
* Fix some permissions for token management pages
* Also restricted token management and CSV bulk add trainees to _accredited_ HEIs only
* Anything missing?
> [8523] Restrict API token management to HEI providers

- app/validators/email_format_validator.rb
- spec/models/api/v0_1/trainee_attributes_spec.rb
- spec/validators/email_format_validator_spec.rb
A provider using the CSV sandbox reported email addresses with containing capital letters were failing validation. Further exploration revealed that this happens when an email address has capital letters in the top level domain (.com, .co.uk etc).  We don’t know if the same happens with the API, but likely it does
[Trello Ticket](https://trello.com/c/E0tJ3dTg/8565-stop-email-addresses-with-capital-letters-in-top-level-domain-from-failing-validation)
Removes case case cehcking from the email regex
> [8565] - Allow any case for email via api

- .github/workflows/database-backup.yml
DB backup workflow runs have been failing. The recommendation is to tweak the timing to see if that helps.
* Run the db backup workflow 15 mins earlier
> Change timing of db backup workflow

- tech_docs/source/api-docs/index.html.md.erb
We have agreed a new [versioning strategy](https://dfedigital.atlassian.net/wiki/spaces/Register/pages/5309759547/Versioning+strategy) and need to update the docs to make this clear for users.
* Update API versioning strategy in API docs
* Does it make sense and align with the [versioning strategy](https://dfedigital.atlassian.net/wiki/spaces/Register/pages/5309759547/Versioning+strategy)?
> [8626] Update API docs with versioning strategy

- app/lib/user_with_organisation_context.rb
- app/models/provider.rb
- app/policies/bulk_update/imports/trainee_upload_policy.rb
- app/policies/bulk_update/trainee_upload_policy.rb
- spec/lib/user_with_organisation_context_spec.rb
- spec/policies/bulk_update/imports/trainee_upload_policy_spec.rb
- spec/policies/bulk_update/trainee_upload_policy_spec.rb
[Trello card](https://trello.com/c/vIxvTMS9)
* Update policies to allow users in previously-accredited HEIs (who are now all Lead Partners) to use the CSV bulk create trainee feature in the CSV sandbox
> [8629] Allow HEI lead partners access to CSV create trainee on CSV Sandbox

- app/components/service_update/view.rb
- app/controllers/service_updates_controller.rb
- app/models/service_update.rb
- app/views/landing_page/start.html.erb
- app/views/service_updates/index.html.erb
- app/views/service_updates/show.html.erb
- config/routes.rb
- spec/controllers/service_updates_controller_spec.rb
- spec/models/service_update_spec.rb
[Trello Ticket](https://trello.com/c/WieebKrO/8630-implement-new-news-service-updates-front-end)
With the new role of communicating changes to the sector, we need a means for communications to persist.
Part of the solution is to direct users from email notifications containing high-level information to the Register News and Updates section for more comprehensive content. Currently, that section is just a list of in-page links with short posts below.
We want to expand this to utilise a standard blog post format, similar to what is used via 11ty for the design histories.
Updates the existing code to move the content to a show view
The review app can be used
> [8630] - service updates new design

- app/lib/code_sets/trs.rb
- app/lib/trs/params/professional_status.rb
- app/services/trs/update_professional_status.rb
- config/settings.yml
- spec/lib/code_sets/trs_spec.rb
- spec/lib/trs/params/professional_status_spec.rb
- spec/services/trs/update_professional_status_spec.rb
[8645-update-trs-professional-statuses-endpoint-integration](https://trello.com/c/E9nuRTUa/8645-update-trs-professional-statuses-endpoint-integration)
Refactor the integration with PUT `/v3/persons/<trn>/professional-statuses/<reference>` according to [20250627 ](https://github.com/DFE-Digital/teaching-record-system/blob/main/CHANGELOG.md#put-v3personstrnprofessional-statusesreference)
* Change endpoint to routes-to-professional-statuses
* Replace routeTypeId with routeToProfessionalStatusTypeId
* Replace Awarded with Holds
* Replace awardedDate with holdsFrom
> [8645] Update TRS Professional Statuses endpoint integration

- app/forms/language_specialisms_form.rb
The trainee in [this ticket](https://trello.com/c/sjij95OA/8712-amendment-for-subject-on-qts) needs their course updated but are getting a "something went wrong" message. The error thrown can be [seen here](https://dfe-teacher-services.sentry.io/issues/6592903172/events/16113ea44ad24d9297d7475abe1fbc2b/?project=5552118).
Guard clauses for the `non_language_subject` method.
I've tested updating the trainee using sanitised production data and was able to get through to the end of the form without an error.
> [8712] - non_language_subject not defined error fix

- app/controllers/bulk_update/add_trainees/empty_templates_controller.rb
- app/controllers/csv_docs/base_controller.rb
- spec/features/bulk_upload/bulk_add_trainees_spec.rb
The CSV template download link is not working from the CSV docs page in production
* Remove the feature flag check for the CSV template download
* Remove unused controller
> [8710] Bug: Download CSV template link not working

- app/lib/trs/params/professional_status.rb
- spec/lib/trs/params/professional_status_spec.rb
A trainee record is stuck in pending due to an unsupported country code. See [this ticket](https://trello.com/c/I6Jx4rFx/8719-record-stuck-in-pending-awards-queue)
Adds an additional mapping to `TERRITORY_FALLBACK_MAPPING`
> [8719] - additional country mapping for professional status params

- config/settings.yml
- config/settings/production.yml
- config/settings/productiondata.yml
- spec/services/teacher_training_api/import_course_spec.rb
- spec/support/api_stubs/teacher_training_api.rb
[Trello Ticket](https://trello.com/c/VF0A5kf9/8743-remove-feature-flag-from-teacher-degree-apprenticeship-route)
We need to enable the `teacher_degree_apprenticeship` route for 2025/26
Sets flags to true in `production` and `productiondata`
> [8743] - Enable teacher_degree_apprenticeship in prod/prod-data

- config/initializers/training_routes/funding/2026_2027/training_initiatives.rb
Several tests are failing today due to the new academic year beginning today.
This PR is an attempt to fix the `features/end_to_end` specs for USE_NEXT_ACADEMIC_YEAR=true.
Just made a copy of the `training_routes/funding/2025_2026/training_initiatives` config for 26-27. 
For now I've not added 26-27 config for bursaries, grants and scholarship config found in the same directory. These will have to be tackled later when we have the correct numbers presumably.
> [8753] Add training initiatives etc. for 2026-27

- terraform/aks/statuscake.tf
- terraform/aks/workspace-variables/production.tfvars.json
We aren't monitoring the apex ssl certificates
Add monitoring
make env deploy-plan 
- production should add 2 ssl monitors, other envs no change
> Add statuscake apex ssl monitors

- .github/actions/deploy/action.yml
- terraform/aks/.terraform.lock.hcl
- terraform/aks/application.tf
- terraform/aks/data.tf
- terraform/aks/provider.tf
- terraform/aks/variables.tf
- terraform/aks/workspace-variables/csv-sandbox.tfvars.json
- terraform/aks/workspace-variables/dv_review.tfvars.json
- terraform/aks/workspace-variables/local.tfvars.json
- terraform/aks/workspace-variables/pen.tfvars.json
- terraform/aks/workspace-variables/production.tfvars.json
- terraform/aks/workspace-variables/productiondata.tfvars.json
- terraform/aks/workspace-variables/qa.tfvars.json
- terraform/aks/workspace-variables/review.tfvars.json
- terraform/aks/workspace-variables/sandbox.tfvars.json
- terraform/aks/workspace-variables/staging.tfvars.json
Reconfiguring to remove yaml secrets
yaml secrets added to kv as single secrets for review env
references to yaml secrets removed for infra and app
terraform reconfigured not to use the yaml secrets
workflow updated so the yaml secret is not used.
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/16223179661
https://trello.com/c/t0BmIeL3/2377-remove-yaml-secrets
> Reconfiguring to remove yaml secrets

- lib/tasks/load_test.rake
[8715-load-test-csv-bulk-add-trainees
](https://trello.com/c/Xue2dnyS/8715-load-test-csv-bulk-add-trainees)
* Add task to execute multiple bulk trainee uploads on the background for load testing purposes
> [8715] Load test CSV bulk add trainees

- config/settings.yml
- config/settings/test.yml
- spec/mailers/csv_submitted_for_processing_first_stage_email_mailer_spec.rb
https://trello.com/c/oaBt1Fi3/8694-send-emails-for-the-first-stage-of-the-of-csv-bulk-create-trainees-process
Set templates for correct statuses for first stage of bulk upload process
> [8694] Set correct template statuses for first stage

- app/services/api/create_trainee.rb
- app/services/bulk_update/add_trainees/import_row.rb
- app/services/bulk_update/add_trainees/import_rows.rb
- spec/features/bulk_upload/bulk_add_trainees_spec.rb
- spec/services/bulk_update/add_trainees/import_rows_spec.rb
[8890-missing-trn-requests-for-trainees-created-via-csv-bulk-add-trainees
](https://trello.com/c/t07UAvf6/8890-missing-trn-requests-for-trainees-created-via-csv-bulk-add-trainees)
* Ensure request for TRN occurs after the trainees have been created
> [8890] Missing TRN requests for trainees created via CSV bulk add trainees

- app/controllers/trainees/forbidden_deletes_controller.rb
An old path had not been updated since the new withdrawal journey was put in place. [Reported by Sentry](https://dfe-teacher-services.sentry.io/issues/6888332646/events/c96c01b36ec5413097ba679acd146505/)
* Update the path
> [xxxx] Fix old trainee withdrawal path

- app/controllers/reports/censuses_controller.rb
- app/services/find_new_starter_trainees.rb
- spec/controllers/reports/censuses_controller_spec.rb
- spec/services/find_new_starter_trainees_spec.rb
There are two support tickets with a similar issue around census sign off data:
[One](https://trello.com/c/jPv8m0ck/8984-chester-uni-sign-off-showing-125-out-of-400-new-starters) [Two](https://trello.com/c/JQohhoSK/8986-sign-off-issue)
Additionally, there we should be filtering out AO trainees according to this [support ticket](https://trello.com/c/dgt1c324/8949-cannot-add-age-range-to-trainees)
* It looks like the CSV export is using a different date than the guidance. This changes the `itt_new_starter_trainees` range used to `second_wednesday_of_october` which matches the range used for the view.
* Filter out AO trainees
sanity check the change. This could be deployed to production data to verify the fix, a review app won't tell us much.
NB: Please notify the #twd_data_insights team and …
> [8986, 8984, 8949] - Second Wednesday for census sign off and remove AO trainees
